### ISSUE TITLE
need to import clr twice to make clr.Addreference work

### ISSUE THREAD

**Issue by juavid** [pythonnet/pythonnet#1005]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.5 32bit
-   Operating System: Windows 10

### Details

-   Describe what you were trying to get done.

I want to use a dotnet dll within my program so I import the dll using

import clr
clr.AddReference('lib')

I dont get any error but no internal class from the library appears. However, if I execute again 

import clr

Then it works. Any suggestions on how to avoid this second step and why this might be happening?

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by filmor** [comment]
What do you mean by "appears"? What exactly are you trying to do?

**Comment by juavid** [comment]
it is basically a dll that interfaces with a software allowing you to run some simulation. As I indicated, the second time I call "import clr" then it is made visible when I type clr.classlib where classlib is part of the dll. It is like by executing import clr after clr.AddReference truly loads in memory the content of the dll.

**Comment by filmor** [comment]
This is far too vague for me to make anything of it.

If a class `Example` is in a namespace `SomeNamespace`, then you have to import it explicitly via `from SomeNamespace import Example` or `import SomeNamespace`. It will not magically appear just because you added the reference. If it does so now this is purely accidental.

**Comment by juavid** [comment]
Sorry, I think I expressed myself incorrectly, Basically, it doesn't load the namespace.

`# code 1`
`import clr`
`clr.AddReference('library')`

then clr doesnt have the namespace

`# code 2`
`import clr`
`clr.AddReference('library')`
`import clr`

Now the namespace is available

**Comment by juavid** [comment]
It is not a critical issue because it works that way but I was just wondering why. And thanks for trying to answer my question I am no expert programmer :).

**Comment by filmor** [comment]
The namespace should always be available after `clr.AddReference` by importing it. It's not necessarily shown by tab-completion or anything like that because it is loaded only on demand. The pseudo-python module we create here and the actual .NET reference are different things.
