### ISSUE TITLE
Is raspberry pi(arm) supported?

### ISSUE THREAD

**Issue by feeho** [pythonnet/pythonnet#1006]
### Environment

-   Pythonnet version:lastest
-   Python version:3.7
-   Operating System:raspbian

### Details

pi@raspberrypi:~/pythonnet-2.4.0 $ pip3 install setup.py
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting setup.py
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/setup-py/

**Comment by filmor** [comment]
That's not how pip works. Check the respective manpages.

**Comment by jaredbroad** [comment]
@filmor Do you mind answering the title question -- do you know if it has it ever been used on a pi/arm architecture successfully? 

@feeho - I'm hacking at this on my spare time as well. Happy to collaborate.

**Comment by jaredbroad** [comment]
@feeho I got pip install working with some fixes to the csproj files + python3.6
 pip3.6 install git+https://github.com/QuantConnect/pythonnet@bug-linux-capitals

But it doesn't work importing the CLR:
```root@lean-pi:/home/pi/Lean/Launcher/bin/Debug# python
Python 3.6.8 (default, Dec  3 2019, 01:05:08)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/libmonosgen-2.0.so.1: undefined symbol: _ZTIPi```

**Comment by filmor** [comment]
That error is documented, downgrade Mono below 6 and you should be fine. I tried it on my RPi a while ago (a few months) and don't remember having to fix anything about the project files, it just worked.
