### ISSUE TITLE
Failure to install on mac os

### ISSUE THREAD

**Issue by asyrovprog** [pythonnet/pythonnet#1012]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7
-   Operating System: Mac OS Mojave 10.14.6

### Details

The package fails to install with `pip install pythonnet`

Output:

Collecting pythonnet
  Downloading https://files.pythonhosted.org/packages/4a/0a/5964a5a1fdf207fab8e718edd1f8d3578e0681577fe9abe0d9006f9718c2/pythonnet-2.4.0.tar.gz (1.8MB)
    100% |████████████████████████████████| 1.9MB 1.2MB/s 
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /usr/local/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-uidyeff7/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-6tlqc96t/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/usr/local/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-uidyeff7/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-6tlqc96t/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-uidyeff7/pythonnet/

**Comment by filmor** [comment]
Plenty of examples of the exact same error here and elsewhere on the internet. Please verify your `pip`, `setuptools` etc. are up-to-date.
