### ISSUE TITLE
Py.GIL() hangs

### ISSUE THREAD

**Issue by oujunke** [pythonnet/pythonnet#1023]
After calling Py.GIL() in a child thread and releasing it, if the thread has not completed execution, it will cause the next Py.GIL() to hang

**Comment by lostmsu** [comment]
@oujunke can you provide repro steps (or even better - minimal project)?

**Comment by oujunke** [comment]
System environment:
  1.Win10
  2.Python3.7
  3.Python.Runtime.NETStandard3.7.1
Code:
![image](https://user-images.githubusercontent.com/26790160/71300733-8fbf3a80-23d2-11ea-950b-d214833e3be2.png)
Result:
![image](https://user-images.githubusercontent.com/26790160/71300752-cf862200-23d2-11ea-9b1f-18f5b89e933a.png)
Suspended location:
![image](https://user-images.githubusercontent.com/26790160/71300771-f7758580-23d2-11ea-9334-9b683eb234f7.png)

**Comment by oujunke** [comment]
Python3.7 X64

**Comment by oujunke** [comment]
@lostmsu

**Comment by lostmsu** [comment]
@oujunke it looks like you are using a fork of this project: https://github.com/henon/pythonnet_netstandard , so you should direct your issue there. However, I'd try to fiddle with `PythonEngine.BeginAllowThreads()`

**Comment by oujunke** [comment]
Thanks, sorry for mentioning the wrong location
