### ISSUE TITLE
no module named numpy in winform application.

### ISSUE THREAD

**Issue by qtbhappy** [pythonnet/pythonnet#1028]
### Environment

-   Pythonnet version:3.7
-   Python version:2.4.0
-   Operating System:windows 7

### Details

In visual studio 2019, c#. The following code works in console application. But in winform application, it says no module numpy. I read the issues here and wiki  relating it, but still cannot make it work. What I expect mostly is that you put a very simple example in the github if you have time. Thanks in advance.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Python.Runtime;

namespace WindowsFormsApp1
{
    public partial class Form1 : Form
    {

        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {

            var pythonPath = @"D:\vnstudio";
            Environment.SetEnvironmentVariable("PATH", $@"{pythonPath};" + Environment.GetEnvironmentVariable("PATH"));
            Environment.SetEnvironmentVariable("PYTHONHOME", pythonPath);
            Environment.SetEnvironmentVariable("PYTHONPATH ", $@"{pythonPath}\Lib");

            MessageBox.Show(pythonPath);

            using (Py.GIL())
            {

                //Console.WriteLine(PythonEngine.PythonPath);
                dynamic np = Py.Import("numpy");
                //Console.WriteLine(np.cos(np.pi * 2));
              
            }
        }
    }
}

**Comment by filmor** [comment]
This is not a support forum.
