### ISSUE TITLE
how to execute within  Entrance "if  __name__ == "__main__":"

### ISSUE THREAD

**Issue by heartacker** [pythonnet/pythonnet#1029]
Here is a simple python file and I would like to try to execute it like main file in my .Net application. But I didn't find a way. Is there any way to do this? thx a lot
```python
import sys
import clr


def func1():
    print('func1')


def func2(a, b):
    print(a+b)
    print('func2')
    return a+b


if  __name__ == "__main__":
    print(func2(1,2))
    sys.exit(0)
```

**Comment by filmor** [comment]
Please check the existing documentation. The easiest way to go about this is using the `Scope` API, check the last section of http://pythonnet.github.io/.

**Comment by NiKeYiGuN** [comment]
I ’m obsessed by this problem too.and i can't find any solution in  http://pythonnet.github.io/.
