### ISSUE TITLE
is "Customizing interop" supported?

### ISSUE THREAD

**Issue by philippdoersek** [pythonnet/pythonnet#1030]
Hi,

According to the "Customizing interop" wiki page (https://github.com/pythonnet/pythonnet/wiki/Customizing-interop), there are some interfaces and classes to handle custom conversions of Python types into .NET objects. However, it doesn't appear that any of those classes actually exist (e.g., IPyArgumentConverter, DefaultPyArgumentConverter). Is this indeed supported, or is this rather a suggested feature?

Thanks and regards,
Philipp

**Comment by lostmsu** [comment]
It's there in [2.4.1](https://github.com/pythonnet/pythonnet/pull/835) which I think has not been released yet.
You can [install from master](https://github.com/pythonnet/pythonnet/wiki/Installation#github-installation-from-master-branch)

**Comment by philippdoersek** [comment]
Thanks for the prompt reply, that explains it.
