### ISSUE TITLE
Many unnecessary assemblies loaded by PythonEngine.Initialize

### ISSUE THREAD

**Issue by cjm1905** [pythonnet/pythonnet#1032]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.5
-   Operating System: Win10 x64 and x86

### Details

-   Describe what you were trying to get done.
We are using PythonNet as an embedded script engine for application extension and automation.

In our scripting test code it works brilliantly. When we moved the test code into our main application we noticed that calling PythonEngine.Initialize caused very many assemblies to be loaded  into the application, most of which would never be loaded normally. The main application uses the DevExpress libraries and and it was these that were the problem. For example in test code with a single DevExpress button on a window and no PythonNet included we get a maximum of three assemblies loaded:

GAC_MSIL\DevExpress.XtraEditors.v19.2\v4.0_19.2.3.0__b88d1754d700e49a\DevExpress.XtraEditors.v19.2.dll'.
GAC_MSIL\DevExpress.Utils.v19.2\v4.0_19.2.3.0__b88d1754d700e49a\DevExpress.Utils.v19.2.dll'. 
GAC_MSIL\DevExpress.Data.v19.2\v4.0_19.2.3.0__b88d1754d700e49a\DevExpress.Data.v19.2.dll'.

If PythonNet is included we get:

GAC_MSIL\DevExpress.XtraEditors.v19.2\v4.0_19.2.3.0__b88d1754d700e49a\DevExpress.XtraEditors.v19.2.dll'. 
GAC_MSIL\DevExpress.Utils.v19.2\v4.0_19.2.3.0__b88d1754d700e49a\DevExpress.Utils.v19.2.dll'. 
GAC_MSIL\DevExpress.Data.v19.2\v4.0_19.2.3.0__b88d1754d700e49a\DevExpress.Data.v19.2.dll'. 
GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. 
GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. 
GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. 
GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. 
GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. 
GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. 
studio\2019\community\common7\ide\commonextensions\microsoft\xamldiagnostics\Framework\x86\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. 
GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. 
GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. 
GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. 
GAC_MSIL\DevExpress.Printing.v19.2.Core\v4.0_19.2.3.0__b88d1754d700e49a\DevExpress.Printing.v19.2.Core.dll'. 
GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll'. 
GAC_MSIL\System.IdentityModel\v4.0_4.0.0.0__b77a5c561934e089\System.IdentityModel.dll'. 
GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll'. 
GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.Wrapper.dll'. 
GAC_MSIL\System.Runtime.DurableInstancing\v4.0_4.0.0.0__31bf3856ad364e35\System.Runtime.DurableInstancing.dll'. 
GAC_MSIL\DevExpress.Pdf.v19.2.Core\v4.0_19.2.3.0__b88d1754d700e49a\DevExpress.Pdf.v19.2.Core.dll'. 
GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll'. 
GAC_MSIL\DevExpress.Sparkline.v19.2.Core\v4.0_19.2.3.0__b88d1754d700e49a\DevExpress.Sparkline.v19.2.Core.dll'. 

Examining the source code I can see that this is caused by the AssemblyManager.ScanAssembly method which is getting all public types from all loaded assemblies and thereby causing a cascade of further assemblies to be loaded.

Is this behaviour what was intended? It seems unacceptable to have to load a heap of unnecessary assemblies. For now we are putting the PythonNet runtime into a separate AppDomain but it makes it a lot more complicated.

**Comment by filmor** [comment]
I can't reproduce this, feel free to reopen if you can provide a reproducible example.
