### ISSUE TITLE
Unable to find assembly 'xxx.dll'. at Python.Runtime.CLRModule.AddReference(String name)

### ISSUE THREAD

**Issue by fjing1** [pythonnet/pythonnet#1038]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.6.3
-   Operating System:Win 10

### Details

-   Describe what you were trying to get done.

    _I am a first timer user of pythonnet. I have installed it properly and trying to use clr.addreference to load/import my API to python. And getting this error  Unable to find assembly 'xxx.dll'.
   at Python.Runtime.CLRModule.AddReference(String name)
I 

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    sys.path.append('\_dlls') ## this is folder name of where i put the dll, its in the same folder of the project
    AddReference('xxx.dll')
background: I have copy the xx.dll to the python project folder. I used  addReferece(r'extact location of the dll'), and it not working. Then I start trying to direct the sys.path.append 
```
This could be an easy fix, but I could not find any solution online. Thanks for your time and effort

**Comment by lostmsu** [comment]
@fjing1 a few notes:
1. You append call lacks `r` character before the string, so `\` is treated as an escape character. Also in Windows starting path from slash means drive root.
2. I don't think pythonnet uses `sys.path`. Instead, you might want to add the full path to the directory containing your DLL to the PATH environment variable.
3. "exact location of the dll" won't work if DLL has dependencies

**Comment by filmor** [comment]
`sys.path` is used for the lookup.

**Comment by fjing1** [comment]
@lostmsu what should I be doing then? How do I know if the DLL has dependencies.
Thank you

**Comment by lostmsu** [comment]
@fjing1 what you could try is to load up C# Interactive and try `Assembly.LoadFile` there.
Also, can you be more specific regarding which error you see when you specify the full path to the assembly? Is it also "Unable to find"?

**Comment by fjing1** [comment]
@lostmsu Yes, it is the same. 
FileNotFoundException: Unable to find assembly
Could this be a python problem?

**Comment by lostmsu** [comment]
@fjing1 very unlikely. `FileNotFoundException` has a `FileName` property, which I would check in case there is a simple mistake. Also you can try [Fusion Log](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer)

**Comment by fjing1** [comment]
Another thing, my python is 64 bits, but this API is 32 bits. Someone says i need to have 32 bits python to find this API

**Comment by filmor** [comment]
That is correct, yes. You can't load 32bit DLLs within a 64bit program.

**Comment by fjing1** [comment]
Get a 64 bit version API and problem solved. Thank you guys
