### ISSUE TITLE
What does Py.import() import? .py files and .pyd files?

### ISSUE THREAD

**Issue by zappfinger** [pythonnet/pythonnet#1042]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.6
-   Operating System:Windows

### Details
Does Py.Import work only with pure python files or also with .pyd files?

**Comment by filmor** [comment]
`Py.Import` uses Python's own `import` logic, so it will be able to load both `.py` as well as `.pyd` modules.

**Comment by zappfinger** [comment]
It does not seem to work for us. In my C# project I set the working directory to a folder containing a .pyd file. I tried all of these:
`//dynamic aag = Py.Import("aag.cp36-win_amd64.pyd");
 dynamic aag = Py.Import("aag.cp36-win_amd64");
 //dynamic aag = Py.Import("aag");`
All of them give: "No module named 'aag'"

Then I added a simple python file (test.py) to this directory:
`def func():
	return "from test.py"`

(sorry, the code formatting does not seem to work)
using this C# code:

dynamic test = Py.Import("test");
Console.WriteLine(test.func());

But it complained: AttributeError : module 'test' has no attribute 'func''

**Comment by filmor** [comment]
This is not a support forum and the issues you are having are as far as I can tell unrelated to pythonnet. The reason importing `test` "worked" for you is that this is a module that is included in the standard library (https://docs.python.org/3.7/library/test.html). You are probably missing the current path in `sys.path`, which is the default for embedded Python instances.

1. Try doing this directly from Python and see whether it works
2. Try setting the environment variable `PYTHONPATH` or update `sys.path` to include `.`, which is not necessarily given (see https://stackoverflow.com/questions/16021013/how-can-i-import-a-python-library-located-in-the-current-working-directory)
3. If all of this doesn't help, ask on StackOverflow or a similar place for further help

**Comment by aaronamm** [comment]
@filmor suggestion is good which point me to the right direction.

@zappfinger Here is the example code that works for me.
```csharp
    dynamic os = Py.Import("os");
    dynamic sys = Py.Import("sys");
    sys.path.append(os.getcwd());

    dynamic test = Py.Import("test");
    Console.WriteLine(test.func());      
```
