### ISSUE TITLE
Custom DLL not importing (potential dependency issue?)

### ISSUE THREAD

**Issue by wsapia** [pythonnet/pythonnet#1046]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.4
-   Operating System: Win 10 x86_64

### Details

I'm trying to use a custom DLL, but can't seem to get it to load correctly. I'm able to add a reference to it, but it still says "ModuleNotFoundError" when I try to import it. I think it might be due to the dependency versions being incorrect.

Here are the dependencies listed when I run the following from System.Reflection as well as the error message when I try to import it. Note that I removed the name of the module since it's proprietary:

#### Code:
```python
import clr
from System.Reflection import Assembly
test = Assembly.GetReferencedAssemblies(clr.AddReference('*DLL_NAME*'))
print('Dependencies:')
[print(i) for i in test]
print('\nLoaded:')
[print(i) for i in clr.ListAssemblies(1)]
import *DLL_NAME*
```

#### Result:
```python
Dependencies:
System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Loaded:
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
clrmodule, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null
Python.Runtime, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null
System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
__CodeGenerator_Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
e__NativeCall_Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
*DLL_NAME*, Version=2.2019.32500.47, Culture=neutral, PublicKeyToken=null
System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Traceback (most recent call last):
  File "*PATH*", line 8, in <module>
    import *DLL_NAME*
ModuleNotFoundError: No module named '*DLL_NAME*'
```

As you can see, the dependencies are all 3.5 and lower while the loaded assemblies are 4.0. How can I load the correct versions of all the assemblies? Could this be the reason that I can't seem to import the module?

Thanks for any help you can provide.

**Comment by filmor** [comment]
The `import` statement doesn't care about the DLL name, it matters what your namespaces are called within .NET. Did you try that?

**Comment by wsapia** [comment]
Hi filmor,

Yeah, I'm using the namespace for the import, but thanks for the suggestion.

**Comment by wsapia** [comment]
I spoke with the creator of the DLL, and it seems as though it wasn't built correctly. That seems to have been the issue, as a new version of the DLL is working as expected.

Closing this thread.
