### ISSUE TITLE
ModuleObject __getattribute__ doesn't treat exceptions ocurred during internal GetAttribute

### ISSUE THREAD

**Issue by andreydani** [pythonnet/pythonnet#1047]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.6
-   Operating System: Windows 10

### Details

From Python code, using clr, when trying to access a class 'Plugin' inside a ModuleObject an exception System.IO.FileNotFoundException is thrown (this isn't a bug on pythonnet) and is never caught, so it isn't converted into a python exception.
The program aborts abnormally, and the Python code never receives the exception.

```python
   module_clr = __import__(namespace_assembly)
   if 'ModuleObject' in self.modulo_clr.__class__.__name__:
      plugin = module_clr.Plugin
```

**Comment by lostmsu** [comment]
Since #1048 is merged, I am closing this issue. Please, open if it resurfaces on `master`
