### ISSUE TITLE
Move NuGet package ownership to pythonnet organization

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1049]
In order to resume releases on NuGet, we need package administration rights.

**Comment by lostmsu** [comment]
@denfromufa can you do that? I sent you an email via NuGet.

Can you transfer the ownership of the NuGet package to us?
1.	IF you own NuGet organization https://www.nuget.org/profiles/pythonnet , please add https://www.nuget.org/profiles/lost as administrator, and transfer packages to it.
2.	IF you do not own that organization, please transfer package ownership to https://www.nuget.org/organization/Python.NET

@filmor , what is your alias on NuGet?

**Comment by denfromufa** [comment]
done

**Comment by lostmsu** [comment]
@denfromufa, thanks for quick response! Is there an email alias on pythondotnet@python.org just for maintainers? If not, we can create a new one. Otherwise somebody might potentially be able to get access to NuGet organization simply by joining the mailing list.

**Comment by lostmsu** [comment]
@denfromufa package https://www.nuget.org/packages/pythonnet/ still seems to be owned by you.

**Comment by lostmsu** [comment]
@Cronan can you move the package ot https://www.nuget.org/organization/pythonnet ?

**Comment by Cronan** [comment]
Sure, just finished off work, going for dinner, will do this later tonight (I’m GMT). Is it possible to change a package’s org?

**Comment by lostmsu** [comment]
@Cronan Yeah, this should do: https://www.nuget.org/packages/pythonnet/Manage

**Comment by Cronan** [comment]
All three packages are now Pending Approval status for user pythonnet

**Comment by lostmsu** [comment]
@Cronan thanks!
