### ISSUE TITLE
Visual Studio 2015 Support

### ISSUE THREAD

**Issue by wagnerpeer** [pythonnet/pythonnet#105]
The newest Visual Studio does not build the solution correctly. Although all projects can be build separately if building the solution something goes wrong and one of the projects fails to build. Therefore no clr.pyd is generated.
As I am no experienced user regarding Visual Studio I do not have a recommendation at hand to solve the problem.

**Comment by filmor** [comment]
Which project fails? I can build Python.NET fine with VS2015.

**Comment by yever** [comment]
I'm using Visual Studio 2015 and I can get [pythonnet_9.sln](https://github.com/pythonnet/pythonnet/blob/master/pythonnet_9.sln) and [pythonnet_8.sln](https://github.com/pythonnet/pythonnet/blob/master/pythonnet_8.sln) to build (I get a message that I have to do a "One-way upgrade", but it works fine).

[pythonnet.sln](https://github.com/pythonnet/pythonnet/blob/master/pythonnet.sln), on the other, doesn't work. I get the following errors:
```
Severity	Code	Description	Project	File	Line
Error	CS0246	The type or namespace name 'RGiesecke' could not be found (are you missing a using directive or an assembly reference?)	clrmodule	D:\Code\pythonnet\src\clrmodule\ClrModule.cs	42
Error	CS0246	The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly reference?)	Python.Runtime	D:\Code\pythonnet\src\runtime\monosupport.cs	14
Error	CS0246	The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly reference?)	Python.Runtime	D:\Code\pythonnet\src\runtime\runtime.cs	15
Error	CS0246	The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly reference?)	Python.Runtime	D:\Code\pythonnet\src\runtime\runtime.cs	15
Error	CS0103	The name 'UnixMarshal' does not exist in the current context	Python.Runtime	D:\Code\pythonnet\src\runtime\monosupport.cs	34
Error	CS0103	The name 'UnixMarshal' does not exist in the current context	Python.Runtime	D:\Code\pythonnet\src\runtime\monosupport.cs	47
Error	CS0103	The name 'UnixMarshal' does not exist in the current context	Python.Runtime	D:\Code\pythonnet\src\runtime\monosupport.cs	54
Error	CS0103	The name 'UnixMarshal' does not exist in the current context	Python.Runtime	D:\Code\pythonnet\src\runtime\runtime.cs	1165
Error		Metadata file 'D:\Code\pythonnet\src\runtime\bin\x64\DebugMono\Python.Runtime.dll' could not be found	Console	D:\Code\pythonnet\src\console\CSC	
Error		Metadata file 'D:\Code\pythonnet\src\runtime\bin\x64\DebugMono\Python.Runtime.dll' could not be found	Python.EmbeddingTest	D:\Code\pythonnet\src\embed_tests\CSC	
Error		Metadata file 'D:\Code\pythonnet\src\runtime\bin\x64\DebugMono\Python.Runtime.dll' could not be found	Python.Test	D:\Code\pythonnet\src\testing\CSC	
```

I guess the ones that work are meant for older versions of Visual Studio.

**Comment by filmor** [comment]
It looks like you're building the wrong build configuration, namely one that is meant for Mono. Select either Release or Debug and you should be fine.

**Comment by yever** [comment]
Oh, silly me. I didn't notice that there were different configurations for Windows and for Mono.
Thanks, now it works fine.

**Comment by denfromufa** [comment]
@yever please close this issue if no problem is left.

**Comment by yever** [comment]
@denfromufa, I didn't open the issue. I just reported (mistakenly) a similar problem. I think @wagnerpeer opened it.

**Comment by denfromufa** [comment]
@yever, sorry I missed that part.

**Comment by wagnerpeer** [comment]
For me it was not a problem of wrong configuration but I solved my issue by getting rid of all unnecessary parts. I will close the ticket without a fix to my original problem.
