### ISSUE TITLE
Docker containers are outdated

### ISSUE THREAD

**Issue by michaelosthege** [pythonnet/pythonnet#1056]
Dear pythonnet devs,

First of all thank you for your great work! My work is much more productive because of you!

I primarily use `pythonnet` with Docker images from https://github.com/jonemo/pythonnet-docker, because the ones from https://hub.docker.com/r/pythonnet/pythonnet/tags go only up to Python 3.5.

It would be great if you could update the "official" images for Python 3.6/3.7 and maybe even do it automatically in your CI pipeline.

cheers

**Comment by filmor** [comment]
I don't think we need to provide our own docker containers.
