### ISSUE TITLE
Travis tests for 2.7 mono randomly crash with segfault

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1060]
> ...
> => Python.EmbeddingTest.TestPyWith.TestWithPositive
> Enter
> Enter
> Exit
> => Python.EmbeddingTest.TestRuntime.PlatformCache
> => Python.EmbeddingTest.TestRuntime.Py_IsInitializedValue
> => Python.EmbeddingTest.TestRuntime.PyCheck_Iter_PyObject_IsIterable_Test
> => Python.EmbeddingTest.TestRuntime.PyCheck_Iter_PyObject_IsIterable_ThreadingLock_Test
> 
> =================================================================
> 	Native Crash Reporting
> =================================================================
> Got a SIGSEGV while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries 
> used by your application.
> =================================================================
> /proc/self/maps:
> 00400000-00849000 r-xp 00000000 08:01 4431                               /usr/bin/mono-sgen
> 00a49000-00a50000 r--p 00449000 08:01 4431                               /usr/bin/mono-sgen
> 00a50000-00a55000 rw-p 00450000 08:01 4431                               /usr/bin/mono-sgen
> 00a55000-00a6c000 rw-p 00000000 00:00 0 
> 00f27000-012a2000 rw-p 00000000 00:00 0                                  [heap]
> 400c2000-40355000 rwxp 00000000 00:00 0 
> 403e6000-403f6000 rwxp 00000000 00:00 0 
> 40815000-40885000 rwxp 00000000 00:00 0 
> 41c4d000-41d50000 rwxp 00000000 00:00 0 
> 7f2a88300000-7f2a88400000 rw-p 00000000 00:00 0 
> 7f2a88500000-7f2a88600000 rw-p 00000000 00:00 0 
> 7f2a88700000-7f2a88800000 rw-p 00000000 00:00 0 
> 7f2a88870000-7f2a88873000 r-xp 00000000 08:01 546082                     /opt/python/2.7.15/lib/python2.7/lib-dynload/fcntl.so
> 7f2a88873000-7f2a88a73000 ---p 00003000 08:01 546082                     /opt/python/2.7.15/lib/python2.7/lib-dynload/fcntl.so
> 7f2a88a73000-7f2a88a74000 r--p 00003000 08:01 546082                     /opt/python/2.7.15/lib/python2.7/lib-dynload/fcntl.so
> 7f2a88a74000-7f2a88a75000 rw-p 00004000 08:01 546082                     /opt/python/2.7.15/lib/python2.7/lib-dynload/fcntl.so
> 7f2a88a75000-7f2a88a78000 r-xp 00000000 08:01 546074                     /opt/python/2.7.15/lib/python2.7/lib-dynload/_random.so
> 7f2a88a78000-7f2a88c77000 ---p 00003000 08:01 546074                     /opt/python/2.7.15/lib/python2.7/lib-dynload/_random.so
> 7f2a88c77000-7f2a88c78000 r--p 00002000 08:01 546074                     /opt/python/2.7.15/lib/python2.7/lib-dynload/_random.so
> 7f2a88c78000-7f2a88c79000 rw-p 00003000 08:01 546074                     /opt/python/2.7.15/lib/python2.7/lib-dynload/_random.so
> 7f2a88c79000-7f2a88e94000 r-xp 00000000 08:01 11799                      /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
> 7f2a88e94000-7f2a89093000 ---p 0021b000 08:01 11799                      /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
> 7f2a89093000-7f2a890af000 r--p 0021a000 08:01 11799                      /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
> 7f2a890af000-7f2a890bb000 rw-p 00236000 08:01 11799                      /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
> 7f2a890bb000-7f2a890be000 rw-p 00000000 00:00 0 
> mono_coop_cond_signal Cannot transition thread 0x7f2ab38f5700 from STATE_BLOCKING with DO_BLOCKING
> 
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
> 
> The build has been terminated

**Comment by filmor** [comment]
This doesn't seem to be happening anymore and we are dropping 2.7 now, so I'll close this issue.
