### ISSUE TITLE
CI conda build script is taking most of the build times

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1063]
See for instance https://ci.appveyor.com/project/pythonnet/pythonnet/builds/31089363/job/8vgpb5s1ww5pkrvl

conda build receipt is nearly 4 minutes of 5.

For comparison, the C# embed tests take under 15 seconds, and even performance tests only take about 1 minute. We should see if there is a way to optimize it.

**Comment by lostmsu** [comment]
@filmor can you look into this? Do we even release pythonnet on conda?

**Comment by filmor** [comment]
I don't think we need to. It's perfectly fine to do that manually and just for releases. I'll prepare a PR.

**Comment by filmor** [comment]
I fixed it directly on `master`, the conda package build only runs on tagged versions now.
