### ISSUE TITLE
Problem using both Pythonnet and SWIG bindings in same python script

### ISSUE THREAD

**Issue by koliyo** [pythonnet/pythonnet#1064]
### Environment

-   Pythonnet version: 2.4.1 (sha: 146353855b6ed2414f3c5fd1b4bf231c2a985da8)
-   Python version: 3.7.6
-   Operating System: Mac (same on Linux/Windows)

### Details

I'm trying to use Pythonnet dynamic bindings together with SWIG bindings from C++ library. My python script needs to call methods both in the C# application API, and in the C++ library API.

Currently Pythonnet intercepts all calls to the C++ SWIG API and rejects these calls.

This is the call in an example
```py
    g = agx.Vec3(0,0,-2)
    print(f'set gravity: {g} ({g.__class__}), sim: {sim.AgxSimulation.__class__}')
    sim.AgxSimulation.setUniformGravity(g)
```

then I get the following error from Pythonnet
```
set gravity: [ 0, 0, -2] (<class 'agx.Vec3'>), sim: <class 'agxSDK.Simulation'>
[13:30:07 ERR] Python error: TypeError : No method matches given arguments for setUniformGravity: (<class 'agx.Vec3'>)
```

And if I instead try and call the method as a function, and explicitly pass the `self` parameter I get passed Pythonnet but get an error in SWIG bindings
```py
    agxSDK.Simulation.setUniformGravity(sim.AgxSimulation, g)
```
gives
```
[13:31:22 ERR] Python error: TypeError : in method 'Simulation_setUniformGravity', argument 1 of type 'agxSDK::Simulation *'
```

Here is a visual diagram of the application setup

![Python integration](https://user-images.githubusercontent.com/770348/75445620-114cbf00-5966-11ea-8cf2-9fd37cfe37de.png)

Any pointers on how I should resolve this?

**Comment by filmor** [comment]
Could it be that you are trying to mix objects coming from Python.NET and SWIG? That's not possible.

**Comment by koliyo** [comment]
Sorry for late reply.

Yes, mixing of Pythonnet and SWIG objects seem to be the issue. Unfortunately, this was exactly the integration we were hoping to be able to leverage.

We create an object in C#, which is actually a native C++ object wrapped in SWIG.NET. We then access this object in python where both Pythonnet and SWIG.Python are initialized.  And we would like to use the SWIG.Python bindings on this object, but since it was allocated through the C# environment, it is considered managed by Pythonnet.

It does not matter if we create the wrapped object directly in C# or if we create it inside C++ and get access to it using a helper function.

We have managed to figure out a workaround, and that is to use a hosted .NET environment (HostFXR), which is launched from the C++ environment.

https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting

I understand all this seems like a complicated setup, and it kind of is, but it now seems to work very well across the bindings. As long as the objects are created in the native C++ environment, we can then access them both from SWIG.Python, and SWIG.NET. And we can additionally access custom C# application code from python via Pythonnet. All in the same process.

**Comment by koliyo** [comment]
I'm closing this issue, since this seems out of scope of Pythonnet
