### ISSUE TITLE
AppVeyor 2.7 x64 consistently fails DomainReloadAndGC test

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1069]
### Environment

-   Pythonnet version: `master`
-   Python version: 2.7
-   Operating System: Windows x64

### Details

The hang seems to be in `TestDomainReload.RunAssemblyAndUnload` line `AppDomain.Unload(domain);`

According to various sources, this can happen, if `AppDomain` has some threads still running in it, however we don't start any explicitly.

I can not reproduce it locally.

Guesses:
- .NET tries to finalize objects in that `AppDomain` and finalizer thread either hangs or silently crashes due to a race condition. The issue might be in our `Finalizer` somewhere.
- some external process running in AppVeyor (antivirus?) creates a thread in the test process, and it happens to be in that test `AppDomain` somehow

Example failed run (link to the memory dump): https://ci.appveyor.com/project/pythonnet/pythonnet/builds/31110307/job/jbdhufqcik7tcm0a/artifacts

**Comment by filmor** [comment]
This doesn't seem to be happening anymore and we are dropping 2.7 now, so I'll close this issue.
