### ISSUE TITLE
TestFinalizer.CollectBasicObject test failure

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1072]
I think this one might actually be interesting: it indicates there is some issue with finalization, which might be the reason for many different failures.

### Environment

-   Pythonnet version: **master**
-   Python version: **2.7 x86**
-   Operating System: **Windows**
-   XPLAT: **NO**

### Details

See the test report: https://ci.appveyor.com/project/pythonnet/pythonnet/builds/31135195/job/16ksywu2adlcwfs6#L609

-   If there was a crash, please include the traceback here.

> The event handler was not called during finalization
> Expected: `True`
> But was:  `False`
>  at `Python.EmbeddingTest.TestFinalizer.CollectBasicObject()` in C:\projects\pythonnet\src\embed_tests\TestFinalizer.cs:line 87

**Comment by filmor** [comment]
Doesn't happen anymore.
