### ISSUE TITLE
python script in STA (Single-Threaded Apartment)

### ISSUE THREAD

**Issue by thu2004** [pythonnet/pythonnet#108]
We GUI automate windows desktop applications using pythononet and Ranorex. 

```python
import clr
clr.AddReference('Ranorex.Core')
```
Ranorex require client to be set to STA and it always print out this warning.

"The apartment state of the current thread is not set to STA. Please make sure that all threads accessing Ranorex methods have their apartment state set to STA."

How to put python script to STA ? Any advice would be greatly appreciated.

/Chi Thu Le

**Comment by tonyroberts** [comment]
Try setting sys.coinit_flags and importing pythoncom (or calling pythoncom.CoInitializeEx if using a background thread) before importing clr.

**Comment by heri16** [comment]
Could you provide an example code?

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/blob/master/demo/wordpad.py

**Comment by fizxmike** [comment]
This worked for me
```python
import pythonnet
pythonnet.CoInitialize()
import clr
# ...
```

**Comment by denfromufa** [comment]
@fizxmike  or ctypes call from standard library for Python:

```
import ctypes
ctypes.windll.ole32.CoInitialize()`
``
