### ISSUE TITLE
'list' value cannot be converted to System.Collections.IEnumerable

### ISSUE THREAD

**Issue by niko86** [pythonnet/pythonnet#1082]
### Environment

-   Pythonnet version: 2.4
-   Python version: 3.7
-   Operating System: Windows 10

### Details

-   Describe what you were trying to get done.

    I am trying to add data to a WPF datagrid, using instructions on a StackOverflow [answer](https://stackoverflow.com/a/58439381). The script fails with an error: 
```
'list' value cannot be converted to System.Collections.IEnumerable
```

-   What commands did you run to trigger this issue? 

```python
    col1 = DataGridTextColumn()
    col1.Binding = Binding("filename")
    col1.Header = "Filename"
    TestDataGrid.Columns.Add(col1) # Added TestDataGrid from xaml file with LogicalTreeHelper.FindLogicalNode(window, "TestDataGrid")
    
    datasource = []
    for file_name in file_names:
        filename = Path.GetFileNameWithoutExtension(file_name)
        datasource.append(DataClass(filename)) # DataClass is a python class with filename as property.
    TestDataGrid.ItemsSource = datasource
```

**Comment by filmor** [comment]
The instructions on StackOverflow are for IronPython (a .NET implementation of Python). There should be an example in our repository somewhere for exactly this case.

You can generally try to instantiate the list explicitly:

    from System.Collections.Generic import List

    # ...
    datasource = List[WhateverTypeItemsSourceHas]()
    for file_name in file_names:
         # ...
         datasource.Add(DataClass(filename))
    # ...

That way you are using the .NET type expected here instead of Python's `list`.

**Comment by niko86** [comment]
Followed this with the following change and results in an error:
```items = List[MyData]```
```TypeError : type(s) expected```
And if I add a type to the MyData class it results in a further error:
```items = List[MyData[str]]```
```TypeError : 'type' object is not subscriptable```
I appreciate this might not be a bug but its hard to find a solution in the documentation and searching through the repo.

**Comment by 1006079161** [comment]
`   data_table = WPFData.DataTable()
   data_table.Columns.Add("ID")
   data_table.Columns.Add("Title")
   data_table.Columns.Add("Content")

   #Add data 
   data_table.Rows.Add("Andre", "Piratas", "1973")
   data_table.Rows.Add("Andres", "Piratass", "1973s")

   myDataGrid.ItemsSource = data_table.DefaultView    `




上面的代码 暂时可用



items = List[System.Object]()    这样虽然不报错,但仍然不行
