### ISSUE TITLE
using(Py.Gil()) hangs while calling from other than init thread

### ISSUE THREAD

**Issue by zwadar** [pythonnet/pythonnet#109]
Hi,
I'm using python.net in C# app and mainly calling python from worker threads. However it always hangs when trying to acquirelock from different thread than thread that did first initialization.
I'm not familiar with exact workflow with GIL, but for me, adding BeginAllowThreads() and EndAllowThreads() to GILState class helped, but I'm not sure it is proper solution.
```C#
 public class GILState : IDisposable
        {
            private IntPtr state;
            private IntPtr thread_state;
            internal GILState()
            {
                thread_state = PythonEngine.BeginAllowThreads();
                state = PythonEngine.AcquireLock();
            }
            public void Dispose()
            {
                PythonEngine.ReleaseLock(state);
                GC.SuppressFinalize(this);
                PythonEngine.EndAllowThreads(thread_state);
            }
            ~GILState()
            {
                Dispose();
            }
        }
```

**Comment by denfromufa** [comment]
Someone tried this before:
https://mail.python.org/pipermail/pythondotnet/2010-December/001058.html

**Comment by tonyroberts** [comment]
The main thread will hold the GIL after initialization until you explicitly release it by calling PythonEngine.BeginAllowThreads() from the main thread (not from your background thread). This is how python threading works, it's not specific to pythonnet.

**Comment by jakrivan** [comment]
I'd vote for reopening this issue.
The .net wrapper can handle threading gracefully while ensuring the underlying threading model of CPython. This can be nasured e.g. by holding internal register of all threads attempting to enter python (via PythonEngine.AcquireLock) engine and calling the ensure/release for them. Example solution in C++ can be found here: https://stackoverflow.com/questions/29100082/python-gil-and-threads

I'll try to find some time to create pull request.

**Comment by jakrivan** [comment]
Btw. untill this is fixed, there probably should not be finalizer on PyObject. It's much better to have some memory leacks; rather than having entire finalizer thread locked up - as finalizer thread is dfefinitely guaranteed to run on different thread than the thread acquiring the engine
