### ISSUE TITLE
CSC: error CS1617: Invalid -langversion option `7.3'. It must be `ISO-1', `ISO-2', Default, Latest or value in range 1 to 7.2

### ISSUE THREAD

**Issue by MyBlackHole** [pythonnet/pythonnet#1100]
### Environment

-   Pythonnet version:2.4.1
-   Python version:3.82
-   Operating System:ubuntu 20.04

### Details

xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON38%3BPYTHON3%3BUCS4%3BMONO_LINUX%3BPYTHON_WITHOUT_ENABLE_SHARED" /p:PythonBuildDir="/media/black/BlackHole/Downloads/zip/pypi/pythonnet/build/lib.linux-x86_64-3.8" /p:PythonInteropFile="interop38.cs" /p:PackageId=pythonnet_py38_x64 /verbosity:normal /t:Build

### ERROR
CSC: error CS1617: Invalid -langversion option `7.3'. It must be `ISO-1', `ISO-2', Default, Latest or value in range 1 to 7.2

**Comment by lostmsu** [comment]
@MyBlackHole Mono versions 5.0+ support using `msbuild` instead of `xbuild`. `xbuild` is considered legacy now.

See https://www.mono-project.com/docs/about-mono/releases/5.0.0/#msbuild
