### ISSUE TITLE
Error in Wiki code sample

### ISSUE THREAD

**Issue by ericjohannsen** [pythonnet/pythonnet#1102]
### Environment
N/A

### Details
This code:

```C#
Environment.SetEnvironmentVariable("PYTHONPATH", $"{pathToVirtualEnv}\\Lib\\site-packages;{pythonPath}\\Lib", EnvironmentVariableTarget.Process);
```
[from the wiki](https://github.com/pythonnet/pythonnet/wiki/Using-Python.NET-with-Virtual-Environments) references a variable `pythonPath` that isn't defined. Is that supposed to be `pathToVirtualEnv` or something else?

**Comment by koubaa** [comment]
@ericjohannsen the wiki can't know where the reader installed python or a virtual environment.  pathToVirtualEnv is meant to be substituted by the reader

**Comment by ericjohannsen** [comment]
@koubaa That's not the issue. The pathToVirtualEnv isn't defined as a variable, and it probably should actually be pythonPath anyhow.
