### ISSUE TITLE
VS2019 build from source fails

### ISSUE THREAD

**Issue by ericjohannsen** [pythonnet/pythonnet#1103]
### Environment

-   Pythonnet version: Latest source
-   Python version: 3.7 (Miniconda)
-   Operating System: Windows 10 Pro

### Details

-   Describe what you were trying to get done.

Attempting to build from source following the instructions in the Wiki for VS.

-   What commands did you run to trigger this issue? 

Cloned from Git, opened in VS2019, attempted to build DebugWinPY3

Received this error message:

> The "RGiesecke.DllExport.MSBuild.DllExportAppDomainIsolatedTask" task could not be loaded from the assembly E:\Dev\pythonnet\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.MSBuild.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by lostmsu** [comment]
@ericjohannsen not sure what the problem is, but if your plan is to call Python from C#, you don't need to build `clrmodule` (that is the project that uses `UnmanagedExports`).

**Comment by lostmsu** [comment]
@ericjohannsen if you need it, try [Fusion Log](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) to trace the issue. Light googling tells you might need .NET Framework 3.5 feature enabled in "Turn Windows features on or off".

**Comment by koubaa** [comment]
@lostmsu I remember hitting this issue.  maybe setup.py should explicitly check for .net framework 3.5 and give a better error.

**Comment by filmor** [comment]
This dependency ia not used anymore.
