### ISSUE TITLE
Travis CI build results are not being picked up in PRs

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1108]
Not sure if it is us (e.g. some key has expired and needs regenerating), or a service issue.

@filmor can you look at it? For example: https://github.com/pythonnet/pythonnet/pull/1106 . The Travis build is [complete](https://travis-ci.org/github/pythonnet/pythonnet/builds/673072111), but PR says "Expected — Waiting for status to be reported "

**Comment by filmor** [comment]
I didn't see this in the meantime, please reopen if it happens again.
