### ISSUE TITLE
how to covert python list to C# string array

### ISSUE THREAD

**Issue by davesliu** [pythonnet/pythonnet#1111]
### Environment

-   Pythonnet version: 3.7.6  64bit
-   Python version: 2.4.0
-   Operating System: Windows

### Details

-   Describe what you were trying to get done.
    I use the pythonnet to call a C# API,
   its C# API function looks like below:
          Init(string[] args)

  It shall set a string array arguments args to the Init() funciton.
  I use below code in pythons script
     args = ['param1', 'param2'] 
     Init(args)
The python script will crash immediately without any error info, even I set the try/catch method, it still doesn't work at all.
So I'm not sure if this problem is caused by the type of args in python as it is a list. How can I convert the python list string to the C# string array?

Thanks in advance if anyone can help.

**Comment by filmor** [comment]
This is not a support forum. Ask questions like this on StackOverflow or the mailing list.

**Comment by heartacker** [comment]
@davesliu how did you fix this problem , I have the same problem,
And I search again and again， I can not find solution.
can you help me please https://github.com/pythonnet/pythonnet/discussions/1889
