### ISSUE TITLE
Issue with installing pythonnet on ubuntu

### ISSUE THREAD

**Issue by alirezaarmion** [pythonnet/pythonnet#1114]
### Environment

-   Pythonnet version: latest version - Apr 2020
-   Python version: 3.6 
-   Operating System: Ubuntu

### Details

-   Describe what you were trying to get done.

    I'm trying to install pythonnet on Ubuntu. I have installed it on windows previously without any issues, but I'm following the steps recommended in wiki, but I get errors: 

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

I did try all the recommendations in https://github.com/pythonnet/pythonnet/wiki/Installation 

I also tried the recommendations on this links as well: 
https://stackoverflow.com/questions/55058757/install-pythonnet-on-ubuntu-18-04-python-3-6-7-64-bit-mono-5-16-fails

Upgrading pip didn't help either as recommended in one of the previous issues ... 

```python
    pip install pythonnet
```

-   If there was a crash, please include the traceback here.

```
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k6qcg3lf/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k6qcg3lf/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-q8losx9d
       cwd: /tmp/pip-install-k6qcg3lf/pythonnet/
  Complete output (50 lines):
  running bdist_wheel
  running build
  running build_ext
  
  Unhandled Exception:
  System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
  File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    at NuGet.CommandLine.Program.Main (System.String[] args) [0x00005] in <d0f788a4af354971807e5d8ca6fc682e>:0
  [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
  File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    at NuGet.CommandLine.Program.Main (System.String[] args) [0x00005] in <d0f788a4af354971807e5d8ca6fc682e>:0
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-k6qcg3lf/pythonnet/setup.py", line 658, in <module>
      zip_safe=False,
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-k6qcg3lf/pythonnet/setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-k6qcg3lf/pythonnet/setup.py", line 245, in build_extension
      self._install_packages()
    File "/tmp/pip-install-k6qcg3lf/pythonnet/setup.py", line 424, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k6qcg3lf/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k6qcg3lf/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-whtoazdo/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/alivm/.local/include/python3.6m/pythonnet
         cwd: /tmp/pip-install-k6qcg3lf/pythonnet/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k6qcg3lf/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k6qcg3lf/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-whtoazdo/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/alivm/.local/include/python3.6m/pythonnet Check the logs for full command output.
```

**Comment by PidgeyUsedGust** [comment]
Mono is not correctly installed. I'd suggest installing Mono 5.20 as follows (replace third line with correct Ubuntu version).

```
sudo apt install gnupg ca-certificates
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic/snapshots/5.20 main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update
```

Then install dependencies:
```
sudo apt-get install clang
sudo apt-get install libglib2.0-dev
sudo apt-get install python3-dev
```

Then install pythonnet:
```
pip install pycparser
pip install pythonnet
```

**Comment by alirezaarmion** [comment]
Hi Gust, 

Thanks for your comments. I did follow the steps, and everything went fine except the last step, which is the main one, installing pythonnet. It gave the same error. the version of my Ubuntu is bionic (see blow please). I did replace ".../ubuntu stable-bionic ..." as well as replacing it with ".../ubuntu bionic..." but no difference. 

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic


 Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x8swava6/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x8swava6/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-9gi7vkpr
       cwd: /tmp/pip-install-x8swava6/pythonnet/
  Complete output (50 lines):
  running bdist_wheel
  running build
  running build_ext
  
  Unhandled Exception:
  System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
  File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    at NuGet.CommandLine.Program.Main (System.String[] args) [0x00005] in <d0f788a4af354971807e5d8ca6fc682e>:0
  [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
  File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    at NuGet.CommandLine.Program.Main (System.String[] args) [0x00005] in <d0f788a4af354971807e5d8ca6fc682e>:0
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-x8swava6/pythonnet/setup.py", line 658, in <module>
      zip_safe=False,
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-x8swava6/pythonnet/setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-x8swava6/pythonnet/setup.py", line 245, in build_extension
      self._install_packages()
    File "/tmp/pip-install-x8swava6/pythonnet/setup.py", line 424, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x8swava6/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x8swava6/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mn6mb5tm/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/alivm/.local/include/python3.6m/pythonnet
         cwd: /tmp/pip-install-x8swava6/pythonnet/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x8swava6/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x8swava6/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mn6mb5tm/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/alivm/.local/include/python3.6m/pythonnet Check the logs for full command output.



I did follow the recommendations in the following links as well, but no luck yet: 
https://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind 

https://github.com/FPGAwars/apio/issues/144

**Comment by PidgeyUsedGust** [comment]
`--single-version-externally-managed` is not the main problem, the main problem is this
```
Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 1.
```
which indicates that Mono was not found on your path. I just realised that the actual Mono install is missing from my previous post. Running
```
sudo apt install mono-complete 
```
should do the trick.

**Comment by ayalalazaro** [comment]
I managed to install pythonnet on ubuntu 18, python 3.6, virtual environment, following this guide but when I try to import it in the python prompt I get an error

> Python 3.6.9 (default, Nov  7 2019, 10:44:02)
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import clr
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: /usr/lib/libmonosgen-2.0.so.1: undefined symbol: _ZTIPi
> 
Any idea? Thanks

**Comment by ayalalazaro** [comment]
I am sorry. I have just realized that this issue was addressed here : 
https://github.com/pythonnet/pythonnet/issues/939

**Comment by filmor** [comment]
Since #939 is solved, I deem this one solved as well. Feel free to reopen if you still have issues.
