### ISSUE TITLE
Unnecesary glib dependency

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1120]
`clrmodule` uses glib in a single place: `main_thread_handler` takes a parameter of type `gobject` from `glib`, which is actually just a pointer to `PyNet_Args` (a cast is used). As `main_thread_handler` is an internal function, this dependency seems unnecessary.

**Comment by lostmsu** [comment]
Workaround on Ubuntu: `sudo apt install libglib2.0-dev`

**Comment by filmor** [comment]
I guess this can be closed :)
