### ISSUE TITLE
Retrieve current python global scope on C# side called from an already running interpreter?

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [pythonnet/pythonnet#1127]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7
-   Operating System: win

### Details

Is there a way to retrieve python object on C# side called from an already running interpreter? 
Specifically a way to retrieve global scope from calling python so that any modification will be reflected on both sides?

For example, declaring some variable on python side
```
clr.AddReference("MyAssembly")
from MyNS import MyCSCls


a_var = 123
MyCSCls.retrieve()
```
And then retrive the variable from C# side via global scope
```
public class MyCSCls{
...
    static void retrieve(){
        PyScope scope = ???
        dynamic a_var = scope.Get("a_var");
        // Also would like to do the same from C# side
        scope.Set("b_var", 321);
    }
...
}
```

**Comment by UNDEFINED-BEHAVIOR** [comment]
Looks like I can just declare new global variables like this but still have no idea how to retrieve one.
```            
using (Py.GIL())
        {
            PythonEngine.Exec("b_var = 321");
        }
```

**Comment by filmor** [comment]
`PyScope` does not implement "attaching" to random scopes, it creates its own scope. `PythonEngine.Eval("b_var")` should get you the value as a `PyObject` instance. Both functions just execute within the current "context", `global` in Python doesn't mean that a value is available from everywhere within your program.

Note, that this is not a support forum, ask questions like this on StackOverflow.
