### ISSUE TITLE
invoking conda environment

### ISSUE THREAD

**Issue by user015** [pythonnet/pythonnet#1129]
### Environment

-   Pythonnet version: 
-   Python version: 3.7.6
-   Operating System: Windows 10
### Details

-   Describe what you were trying to get done.

 Trying to invoke conda environment from a .NET application. 
I have been using python by itself from .NET (via python.net) with no issues.  Now I am trying to use a test conda environment instead.  Setting the pythonhome variable to the python installation within conda throws errors when trying to import modules like numpy.  This is probably related to not activating the environment before trying to access python.

When invoking this test environment from command prompt, there is a bat file which activates this environment.  How can something like this be done here ? 

Thank you,
    

-

**Comment by lostmsu** [comment]
AFAIK, the only two things you need to do is to set `PATH` environment variable to ensure you a loading python37.dll from the conda environment directory instead of the system interpreter, and set `PythonEngine.PythonHome` to the conda environment's home.

**Comment by user015** [comment]
> AFAIK, the only two things you need to do is to set `PATH` environment variable to ensure you are loading python37.dll from the conda environment directory instead of the system interpreter, and set `PythonEngine.PythonHome` to the conda environment's home before calling `PythonEngine.Initialize()`.

Thank you for the reply, did you have conda already installed on your system ?  I am trying to do it without having to install conda. The batch file in my case when run from the command prompt sets up the test environment and I can use all the packages and run scripts.  However I am trying to see if there is some way I can invoke this functionality via a .Net App and python.net.  Can you give a example of how you are setting up your path variable ? I was using PythonEngine.pythonHome successfully earlier (with regular python) and everything worked fine.

**Comment by lostmsu** [comment]
The two steps I mentioned do not require conda to be installed. Try that, ensure you get the correct python37.dll loaded (you can see in Modules window in Visual Studio debugger), then ask if it still does not work.

**Comment by user015** [comment]
> The two steps I mentioned do not require conda to be installed. Try that, ensure you get the correct python37.dll loaded (you can see in Modules window in Visual Studio debugger), then ask if it still does not work.

I have tried these already, I am invoking the correct python installation from the conda environment. The issue is Conda environment is not being activated as I wrote earlier.

**Comment by lostmsu** [comment]
@user015 first, you did not add the error message here.
Second, you still have not confirmed, that the correct `python37.dll` gets loaded.

**Comment by angeliand** [comment]
If you check activate.bat in your conda scripts, you will find that activating a conda environment just prepends certain directories to the PATH system variable basically. You can emulate this in .NET, eg.:

```
            string environmentPath = @"Your\Env\Root\Folder";
            string scriptsPath = $@"{environmentPath}\Scripts";
            string libraryPath = $@"{environmentPath}\Library";
            string binPath = $@"{environmentPath}\bin";
            string exeutablePath = @$"{environmentPath}\Library\bin";
            string mingwBinPath = $@"{environmentPath}\Library\mingw-w64\bin";
            string oldPath = Environment.GetEnvironmentVariable("PATH");

            Environment.SetEnvironmentVariable("PATH", environmentPath + ";" + scriptsPath + ";" + 
                libraryPath + ";" + binPath + ";" + exeutablePath + ";" + mingwBinPath + ";" + oldPath, EnvironmentVariableTarget.Process);

            Environment.SetEnvironmentVariable("PYTHONHOME", environmentPath, EnvironmentVariableTarget.Process);
                        
            PythonEngine.PythonHome = environmentPath;
```

Though it is not clear to me whether you want to create a conda environment from scratch using Python.NET or you want to use an existing one. If it is the latter, then the above code snippet should help you out.

**Comment by user015** [comment]
> t in your conda scripts, you will find that activating a conda environment just prepends certain directories to the PATH system variable basically. You can emulate this in .NET, eg.:

Sorry about the delayed response. Yes, this is what I did. Thank you @lostmsu  and @angeliand. You can consider this issue closed.
