### ISSUE TITLE
Converting python dict to c#

### ISSUE THREAD

**Issue by rspadim** [pythonnet/pythonnet#1130]
Hello i'm using last version of pythonnet and python 3.8
my doubt is about conversions from python to c#, i'm coding at c# side.

I want to convert a python list of dict, to c# dictionary (probably a <string, string> dict)

is there any example? best pratices? i'm fetching data from python world and reporting it to c# world

**Comment by filmor** [comment]
This is not a support forum. Try the mailing list or StackOverflow.

**Comment by lostmsu** [comment]
@rspadim I've just added a wiki page about new unstable feature targeted to your exact scenario: [Codecs: .NET <-> Python conversions](https://github.com/pythonnet/pythonnet/wiki/Codecs:-customizing-object-marshalling-between-.NET-and-Python)

**Comment by rspadim** [comment]
thanks @lostmsu , this kind of informations are a bit hidden at wiki/doc
