### ISSUE TITLE
Passing multidimensional array to Python results in a flat list

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1141]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: any
-   Operating System: any

### Details

```csharp
var array = new int[5,5];
dynamic numpyArray = np.array(array);
Console.WriteLine(numpyArray.shape);
```
Expected:
> (5, 5)

Actual:

> 25

### Workaround

Write a custom `IPyObjectEncoder` for multidimensional arrays.

**Comment by filmor** [comment]
If you really want this to work efficiently, you should implement https://numpy.org/devdocs/reference/arrays.interface.html for `Array`. It would be nice if we had a generic way to influence the facades produced by our conversion functions. Something like

    class ArrayFacade<T> : IPythonFacade<T[]> {
        T __getitem__(PyObject indexOrSlice) {
             return Self[indexOrSlice]
              ///
        }

        PyDict __array_interface__ {
            get {
                new PyDict() { ["shape"] => /* shape tuple from array */ ... }
            }
         }
    }

**Comment by lostmsu** [comment]
@filmor I am currently thinking facades (or rather adapters I guess) is the way to go forward with some of our conversion shenanigans. Standard .NET types should get wrappers implementing corresponding Python interfaces on top of the type's own, and vice versa.

E.g. one should be able to call both `.Add(` and `.append(` from Python on the passed `List<T>` instance.

Should be a separate issue really though. This one is very specific.

**Comment by filmor** [comment]
Sure, but in a less generic fashion you should already be able to implement this with a codec by encoding a .NET array to a wrapper object that implements the correct `__array_interface__` property.

**Comment by lostmsu** [comment]
Turns out this was implemented (including tests) in https://github.com/pythonnet/pythonnet/pull/1511
