### ISSUE TITLE
. net initializes system.dllnotfoundexception in Python: "cannot load DLL" python37 ": the specified module cannot be found. (exception from HResult: 0x8007007e). "

### ISSUE THREAD

**Issue by feelsyt** [pythonnet/pythonnet#1142]
. net console loading using（ Py.GIL ()) in this step, it will be reported that python37 cannot be found. I have configured it python3.7 , not yet supported python3.7？？？？？？

**Comment by filmor** [comment]
Python 3.7 is supported, you need to make sure that it can be found. Check the documentation. Setting `PYTHONHOME` could help.
