### ISSUE TITLE
Get unicode string from python to netcore (only on linux).

### ISSUE THREAD

**Issue by novecento** [pythonnet/pythonnet#1144]
### Environment

-   Pythonnet version: NETSTANDARD2.1 (conditional compilation symbols: PYTHON3;PYTHON36;UCS4;NETSTANDARD) (UCS2 for windows)
-   Python version: 3.6.6
-   Operating System: Linux

### Details

-   Describe what you were trying to get done.

Hi,
I'm using PythonNet on .net core 3.1 successfully on windows (thanks a lot for this amazing library).
Now I'm moving on linux container and all it works but I have a problem with string econding

My use is load a script like module (pyScript), call a python method (getExtraInfo) and get return value:

PyObject info = pyScript.getExtraInfo();
var s = (string)info.AsManagedObject(typeof(string));
var ss = info.As<string>();
info.Handle.ToManaged(typeof(string), out object handle, false);

All this tests to convert string return strange unicode charts, i.e.
on Py I return "hello hello" string, on c# i get "h\u0000e\u0000l\u0000l\u0000o\u0000 " (trunked)

Do you have any hints for me?

**Comment by filmor** [comment]
Have you tried swapping the `UCS` value? This looks like you are getting `UCS4` where you are expecting `UCS2`.

**Comment by novecento** [comment]
Same behavior for both :-(

**Comment by markuspalme** [comment]
I have experienced the same issue with the NuGet package `pythonnet_netstandard_py37_linux` inside a docker container based on the image `mcr.microsoft.com/dotnet/aspnet:5.0` .

**Comment by filmor** [comment]
This Nuget package is not supported by this project. It's a fork at some random old state of the repo. Do you experience the same problem with the current master branch?

**Comment by markuspalme** [comment]
@filmor Looking at the issues, there seems to be quite some confusion regarding the NuGet packages. Are there event official NuGet packages?

**Comment by filmor** [comment]
We produce official weekly (preview) nuget packages now.
