### ISSUE TITLE
Error GOT STR

### ISSUE THREAD

**Issue by darkjhesus** [pythonnet/pythonnet#1146]
Dear, I have this simple C# example, I create the dll file and import in ironPython 2.7 using clr, when execute cpp.Connect("A", 102) the next error appear "TypeError: expected Class1, got str".
Firstly I import clr module and "import ClassLibrary1.Class1 as cpp"

using System;

namespace ClassLibrary1
{
    public class Class1
    {
        public void Connect(string hostname, int tcpPort)
        {
            string a = hostname + ":" + tcpPort;
        }
    }
}

Why is this error in my code?

**Comment by lostmsu** [comment]
IronPython is a different project: https://github.com/IronLanguages/ironpython2

For your error my guess is your method must be `static`.
