### ISSUE TITLE
How to convert a byte[] into a Python bytes-object

### ISSUE THREAD

**Issue by henon** [pythonnet/pythonnet#1150]
I have searched all issues and also StackOverflow and I searched the whole pythonnet code but couldn't find any functions that take in a byte[].

The only way I found was to convert the byte[] to base64 in C# and call `base64.decode()` on the Python side to get a bytes-object like this. 

```c#
                var bytes=new byte[] {0x80, 0x03, (byte) '}', (byte) 'q'};
                var bytes_base64 = System.Convert.ToBase64String(bytes);
                dynamic base64 = Py.Import("base64");
                var bytes_object=base64.b64decode(bytes_base64);
                Console.WriteLine(bytes_object.ToString());
```

which outputs:  `b'\x80\x03}q`

Is there no direct way?

**Comment by lostmsu** [comment]
@henon try this:
```csharp
PyObject builtins = Py.Import("builtins");
PyObject bytes = builtins.GetAttr("bytes");
bytes.Invoke(yourByteArray.ToPython());
```

Also, questions like this are better suited for StackOverflow.

**Comment by henon** [comment]
Thanks, it works!
