### ISSUE TITLE
Error installing in Windows 10 1909 (18363.836)

### ISSUE THREAD

**Issue by IBIT-ZEE** [pythonnet/pythonnet#1152]
### Environment
-   Pythonnet version  :  pythonnet-2.4.0.tar.gz (1.8 MB)
-   Python version       :  Python 3.8.3rc1
-   Pip version             :  pip 20.1.1 from c:\python\lib\site-packages\pip (python 3.8)
-   Operating System  :  Windows 10 1909 (18363.836)

### Details
command was:
    pip install pythonnet
    (also tested with --pre switch)

### Error

```
    (....)
    File "C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-install-z9z07b82\pythonnet\setup.py", line 298, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "c:\python\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\python\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop38.cs']' returned non-zero exit status 1.
    (....)
```

### Details

   Installing pythonnet with pip

**Comment by filmor** [comment]
Version 2.4 doesn't support Python 3.8. You'll have to wait a few more days for 2.5 to land on Pypi or use the current master.

**Comment by IBIT-ZEE** [comment]
> Version 2.4 doesn't support Python 3.8. You'll have to wait a few more days for 2.5 to land on Pypi or use the current master.

OK,,, <<<WAITIN' ANXIOUSLY''' ;-) >>>
