### ISSUE TITLE
In py file all code works well, but when i compile my code to pyd file, it reported "ModuleNotFoundError: No module named 'xxx'"

### ISSUE THREAD

**Issue by szhuangli88** [pythonnet/pythonnet#1154]
### Environment

-   Pythonnet version: 
-   Python version:3.7.6
-   Operating System:windows 10

In py file all code works well, but when i compile my code to pyd file, it reported "ModuleNotFoundError: No module named 'PowerMonitor'"

clr.AddReference('PowerMonitor')
from PowerMonitor import PowerMonitorController

**Comment by filmor** [comment]
This is not a support forum. Python.NET does some magic with regard to importing that may not work in your use-case.
