### ISSUE TITLE
Issue integrating Python into .NET on Debian 9

### ISSUE THREAD

**Issue by AleTarello** [pythonnet/pythonnet#1155]
-   Pythonnet version: 2.4.0
-   Python version: 3.7.3
-   Operating System: Debian 9.12

I am trying to integrate Python code into .NET, with using((Py.GIL())); I am actually using the exact example provided with the PythonNet documentation. 

I compile with neither errors nor even warnings, but when I try to run the executable, I get an error message. I compiled with both dotnet (in visualstudio) and mcs, adding in both cases a reference to the Python.Runtime.dll file which is in a site-packages folders in anaconda3. 

In the first case, I get:

Unhandled exception. System.MissingMethodException: Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.
   at Python.Runtime.CodeGenerator..ctor()
   at Python.Runtime.DelegateManager..ctor()
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at Python.Runtime.Py.GIL()
   at Python_Integration.Python_Integration.Main(String[] args) [...]

In the second I get:
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Python.Runtime, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Python.Runtime, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Python.Runtime, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Python.Runtime, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null'

I understand that the assembly files straight out of pip have some compatibility issue with .Net Core, I have tried to compile pythonnet from setup.py but it throws me an error message. I used 
python setup.py bdist_wheel --xplat (it does not work if I remove --xplat as per the documentation). 
My mono is 5.14.

I have gone through quite a lot of other issues reported here and tried different suggestions, but was not very successful.... thank you for your attention.

**Comment by lostmsu** [comment]
Depending on your use case you might just want to use https://www.nuget.org/packages/Python.Runtime.UnofficialNetStandard/ until Python.NET 3 is officially released with full .NET Core support, and, hopefully, .NET Standard packages.

**Comment by AleTarello** [comment]
Thanks a lot. Following your advice, I only had to add an environment variable and it worked.

**Comment by lostmsu** [comment]
@AleTarello out of curiosity, which environment variable are you referring to?

**Comment by AleTarello** [comment]
After adding the new reference, the error message changed and it could not find "python37m". So I added LD_LIBRARY_PATH with the path to the *.so files
