### ISSUE TITLE
TypeError: No method matches given arguments for Exists: (<class 'bool'>)

### ISSUE THREAD

**Issue by ahmadshobake** [pythonnet/pythonnet#1161]
### Environment

-   Pythonnet version:2.5.0
-   Python version: 3.6.5
-   Operating System: Windows

### Details

Trying to Know if field is exit in List or No

    _TODO_

def isTrue(field):
    return( field.InternalName == "Title")
isTrue(field)

_listFieldDetails.Exists(isTrue(field))

TypeError: No method matches given arguments for Exists: (<class 'bool'>)

**Comment by filmor** [comment]
This is not a support forum. Please direct questions like this towards the Mailing List or StackOverflow.

What you are trying to do there is not even value C#. The [`Exists` function](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.exists) on `List<T>` (which I just assume `_listFieldDetails` is, even though you never wrote that) takes a [`Predicate<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.predicate-1), not a boolean. That is what this `TypeError` is telling you. You should be able to generate a delegate object though like this:

    from System import Predicate

    d = Predicate[YourFieldDetailsType](isTrue)

    _listFieldDetails.Exists(d)
