### ISSUE TITLE
Bad refcounting in ClassBase.tp_repr (2.x backport)

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1162]
Need to backport #1160

**Comment by filmor** [comment]
As soon as you have pushed your other fix I'll release 2.5.1.

**Comment by filmor** [comment]
Done, https://github.com/pythonnet/pythonnet/tree/backports-2.5. Release is under way, source release already published on Pypi: https://pypi.org/project/pythonnet/.
