### ISSUE TITLE
Cannot install 2.5.1 with setup.py inside .venv but can install 2.5.0

### ISSUE THREAD

**Issue by Kaatjie** [pythonnet/pythonnet#1165]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.7.6
-   Operating System: Win 10

### Details

I am trying to set up my virtual environment (venv) for python, which up until today I have been successful with. Now when I run, I get this error when installing pythonnet:

> Running setup.py install for pythonnet ... error
>     ERROR: Command errored out with exit status 1:
>      command: 'c:\[redacted]\.venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\[redacted]\\AppData\\Local\\Temp\\pip-install-ifzbxjxk\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\[redacted]\\AppData\\Local\\Temp\\pip-install-ifzbxjxk\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\[redacted]\AppData\Local\Temp\pip-record-7w1bv9m6\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\[redacted]\.venv\include\site\python3.7\pythonnet'
>          cwd: C:\[redacted]\AppData\Local\Temp\pip-install-ifzbxjxk\pythonnet\
>     Complete output (6 lines):
>     usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>        or: setup.py --help [cmd1 cmd2 ...]
>        or: setup.py --help-commands
>        or: setup.py cmd --help
> 
>     error: option --single-version-externally-managed not recognized
>     ----------------------------------------
>   Rolling back uninstall of pythonnet

I am not having this problem if I roll back to 2.5.0
This is possibly related to #1159 however I do not see the issue on 2.5.0 where as the poster of that issue does.

**Comment by filmor** [comment]
The problem is that I haven't uploaded the precompiled wheel, yet. I'll do that now.

**Comment by filmor** [comment]
Done, please try again and close if that solves your issue.

**Comment by Kaatjie** [comment]
Yep, that solved it. Thanks :-)
