### ISSUE TITLE
Passing large bytes block to C# causes OutOfMemoryException exception

### ISSUE THREAD

**Issue by VisuMap** [pythonnet/pythonnet#1166]
### Environment

-   Pythonnet version: 2.5.0
-   Python version: 3.6.6
-   Operating System: Windows 10 - 64 bits

### Details

I want to passed a large numpy array (>1.5GB) from python to C# program. I used the following method: 
       matrix = np.load('large.npy')
       netObj.MyMethod(bytes(matrix.data))

This method works fine for small data file, but crashed for large files with the following error message:

System.OutOfMemoryException: 'Array dimensions exceeded supported range.'

Both my C# program and python are 64 bit app. Is there a way to solve this problem?

**Comment by filmor** [comment]
This is a problem in C#: https://stackoverflow.com/questions/1391672/what-is-the-maximum-size-that-an-array-can-hold
