### ISSUE TITLE
embed python in wpf and how to using package with virtualenv 

### ISSUE THREAD

**Issue by heartacker** [pythonnet/pythonnet#1168]
### Environment

-   Pythonnet version: 2.4.1（nuget: Python.Runtime.NetStandard）
-   Python version:3.7.7_x86
-   Operating System:Win 10

### Details

-   Describe what you were trying to get done.

HI, I created a python-env using virtualenv ,and I add the folder-path of `.env`(Scripts,lib) to syetem path  with `Environment.SetEnvironmentVariable()`;
After that   PythonEngine Initializes successfully. But it seems that it can't use those package installed in virtualenv.  Is There any way to use those package.

THX

**Comment by filmor** [comment]
This is not a support forum. Please check on StackOverflow or the Mailing List for help. `PYTHONPATH` may help you.
