### ISSUE TITLE
Make traceback information of an error publicly available

### ISSUE THREAD

**Issue by mmisol** [pythonnet/pythonnet#1169]
Greetings everyone!

First of all, sorry for not following the template, but this more like a feature request than a bug report.

What I'm trying to do is get the traceback information from a Python error to show in a custom message in my application. Taking a look at the source of `PythonException`, I was able to see the traceback is available as part of the `StackTrace`, and is also available in a private field of the exception, named `_tb`.

What I ended up doing, for getting just the traceback, is accessing the private field using reflection (bad idea).

Would you consider adding a public property, maybe named `TraceBack`, in `PythonException` that provided this information?

Thanks!

**Comment by filmor** [comment]
Access to these is public now.
