### ISSUE TITLE
I have a problem in my python script to return the list of values ​for a .NET DLL

### ISSUE THREAD

**Issue by wscardua** [pythonnet/pythonnet#1171]
Hy Guys,

I'm trying to work with a .NET DLL ... but I have a problem returning a lis

```
import clr
clr.AddReference(r"F:\dir\WatchComm.dll")

from org.cesar.dmplight.watchComm.api import *
from org.cesar.dmplight.watchComm.impl import *
from org.cesar.dmplight.watchComm.impl.printpoint import *
from org.cesar.dmplight.watchComm.business import *


def main():

    comm = TCPComm('172.10.10.10',3000)
    comm.SetTimeOut(15000)

    IntanciaRep = WatchComm(WatchProtocolType.PrintPoint, comm, 1, None, WatchConnectionType.ConnectedMode, '01.00.0000')

    IntanciaRep.OpenConnection()

    employees = IntanciaRep.InquiryEmployeeList()
    for employee in employees:
        print(f'{employee.Pis}, {employee.Name}, {employee.Password}')


    IntanciaRep.CloseConnection()


>> Result: 123, Jonhathn, mypassword
```

lock the .Net class

Can you help me ?

![printpointapi](https://user-images.githubusercontent.com/47982596/85790911-6a0b4900-b707-11ea-8f1b-8a7e40137832.PNG)
------------------------------------------------------------------------------------------------------------------------------
![inquireList](https://user-images.githubusercontent.com/47982596/85790920-6c6da300-b707-11ea-9604-e59780c467d2.PNG)
------------------------------------------------------------------------------------------------------------------------------
![Example_in_dotNEt](https://user-images.githubusercontent.com/47982596/85790923-6d063980-b707-11ea-8da3-8d861c0414e7.PNG)

**Comment by lostmsu** [comment]
@wscardua this is not a support forum, and you problem is not well-described.
