### ISSUE TITLE
Unable to load DLL 'python3.7'? (similar to #973)

### ISSUE THREAD

**Issue by younguklee** [pythonnet/pythonnet#1172]
### Environment

-   Pythonnet version: 3.0.0.0 (python.runtime.dll version, built by visual studio 2019, I got the source from https://github.com/pythonnet/pythonnet )
-   Python version: 3.7.6
-   conda version: 4.8.2
-   Operating System: Windows10 Pro
-   Visual studio 2015

### Details

-   Describe what you were trying to get done.

    I am trying to import my Python file within my C# code and I am getting a
System.DllNotFoundException: Unable to load DLL 'python3.7': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   I have the exception on 'PythonEngine.PythonHome = PYTHON_HOME;'
   I'm sure I register the path of Anaconda3 and there is the file 'python37.dll'. (It's interesting. There is only 'python37.dll' but the exception code says 'python3.7')
   
   I registered the path like this.()
       System variables - Path
![System variables_Path](https://user-images.githubusercontent.com/67233320/85804656-21927080-b785-11ea-816d-244072000dc4.PNG)
          D:\WORK\Anaconda3\
          D:\WORK\Anaconda3\Lib\site-packages\
      System variables - PYTHONPATH
![System variables_PYTHONPATH](https://user-images.githubusercontent.com/67233320/85804663-25be8e00-b785-11ea-8992-7dc5cee6fe63.PNG)
          D:\WORK\Anaconda3\
          D:\WORK\Anaconda3\Library\bin
          D:\WORK\Anaconda3\Lib\site-packages\
        
I'm a newbie. Do you have any idea the reason why the exception occur? If you do, please help me. 
Thanks in advance.

==================================================================================
Source        

                var PYTHON_HOME = Environment.ExpandEnvironmentVariables(@"D:\WORK\Anaconda3\");
                var PYTHON_LIB = Environment.ExpandEnvironmentVariables(@"D:\WORK\Anaconda3\Library\bin");
                var PYTHON_SITE = Environment.ExpandEnvironmentVariables(@"D:\WORK\Anaconda3\Lib\site-packages\");

                AddEnvPath(PYTHON_HOME);
                AddEnvPath(PYTHON_LIB);
                AddEnvPath(PYTHON_SITE);

                // Python Home
                PythonEngine.PythonHome = PYTHON_HOME;
...

Source
 
                public void AddEnvPath(params string[] paths)
                {
                            Environment.SetEnvironmentVariable("PATH", string.Join(System.IO.Path.PathSeparator.ToString(), envPaths), EnvironmentVariableTarget.Process);
                            Environment.SetEnvironmentVariable("PYTHONPATH", string.Join(System.IO.Path.PathSeparator.ToString(), envPaths), EnvironmentVariableTarget.Process);
                 }
==================================================================================

**Comment by lostmsu** [comment]
Please, follow the wiki: [Troubleshooting](https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX#1-build-in-visual-studio).

This is not a support forum.

**Comment by younguklee** [comment]
Thanks for the link.
