### ISSUE TITLE
Does pythonnet work with .NET Core

### ISSUE THREAD

**Issue by jeffzi19** [pythonnet/pythonnet#1178]
I'm developing a platform that uses .NET as a "backend" and python as the front-end user driven language.  Users will write python scripts that will access a handful of objects written in .NET.

This works fine on windows and with .NET framework compiled binaries.  I can get the .NET binaries to compile in .NET Core and they're running fine on linux.

What I cannot do is get pythonnet to load .NET libraries written for .NET Core.  In reading through the various posts I can't determine if this is something that is supported or should work.  I don't have a specific tie to a version of python or pythonnnet.  At the moment I'm using python 3.6.7 and just updated to the latest pythonnet (2.5.1).

When I make a normal console app using .NET Core and try and import I'm getting the following error:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    from LinuxNetCoreTest import *
ModuleNotFoundError: No module named 'LinuxNetCoreTest'

when running everything the same but using a .NET Framework compiled binary this is working fine.  I've tried this with and without clr.AddReference - neither are working.

At this point I just need to know if this is possible or if I need to look at a completely different path to solve this problem.

Thanks in advance.

**Comment by lostmsu** [comment]
The [issue about .NET Core support](https://github.com/pythonnet/pythonnet/issues/984) is actually pinned at the top.

**Comment by jeffzi19** [comment]
Thanks for the link - after posting this I did see that and was wondering if that was the official word / issue to track.

That said - what do you mean by "pinned at the top"?  The top of what?

**Comment by lostmsu** [comment]
@jeffzi19 when you got to https://github.com/pythonnet/pythonnet/issues , it is pinned above the search.

Actually, I think this GitHub feature does not work as intended. I never paid attention to them to be honest :)

**Comment by jeffzi19** [comment]
HA - I see it now.  Thanks - I figured I was missing something.

Thanks for the link and the heads-up on where to find hot issues!  Take care.

**Comment by torch016** [comment]
It would be nice to know what the answer was though. If you don''t mind posting ti here. We would be glad.

**Comment by filmor** [comment]
@torch016 Please stop necro-posting or you will be banned from commenting here for a while. Either you actually start reading the existing information (I gave you two links on another issue you commented on) or you will have to wait for official documentation.
