### ISSUE TITLE
string can't be callable

### ISSUE THREAD

**Issue by alexmasis** [pythonnet/pythonnet#1180]
### Environment

-   Pythonnet version: 2.5.1 ( clr )
-   Python version: 2.7.11
-   Operating System: Windows 10

### Details

-   Describe what you were trying to get done.

The debugging variables are not available when using Squish IDE or Eclipse
The callable objects are filtered out by the debugger, however some objects are not callable like:

-  print("Is System.String a callable? %s" % callable(System.String("Foo"))) 
The above print shows that string is a callable object...
```python
    print('TODO')
 print("Is System.String a callable? %s" % callable(System.String("Foo")))
String should NOT be callable .
```

-   If there was a crash, please include the traceback here.
No
```python
    print('TODO')
```

**Comment by lostmsu** [comment]
If anyone wants to work on this, the fix will be to make `ClassObject.tp_call` private and fill the `tp_call` slot in `TypeManager` but only for delegate types.

**Comment by alxnull** [comment]
@lostmsu I'd try to work on this, but might need some further insights:

You mentioned the `ClassObject.tp_call` method, so I started to investigate from there. Apparently, removing this method already did the trick for me. Delegate types seem to have a separate implementation for being callable in `DelegateObject.tp_call`, so I'm wondering when the implementation in `ClassObject` is actually used?

With `ClassObject.tp_call` removed, it gives:

```
String callable? False
Double callable? False
Action callable? True
Func callable? True
```

Thanks for any help.

**Comment by lostmsu** [comment]
@alxnull if you did not run the full test suit locally yet, you can try submitting a PR with your changes, and see if any CI tests fail. Perhaps one of the implementations is dead code indeed.
