### ISSUE TITLE
pythonnet can't deployment in iis?

### ISSUE THREAD

**Issue by 896722590** [pythonnet/pythonnet#1183]
### Environment

-   Pythonnet version:2.5.1
-   Python version:3.8.3
-   Operating System:win 10
-   netframework:dotnet4

### Details

-   can't deployment in iis?

using (Py.GIL())
{
    dynamic np = Py.Import("numpy");
    dynamic scipy = Py.Import("scipy.stats");
    dynamic dataList1 = np.array(new List<float> { 28, 31, 36, 35, 32, 33, 21, 12, 12, 23, 19, 13, 20, 17, 14, 19 });
    dynamic dataList2 = np.array(new List<float> { 12, 18, 19, 14, 20, 19, 12, 11, 8, 9, 10, 15, 16, 17, 10, 16 });
    var value1 = scipy.stats.ttest_rel(dataList1, dataList2);
    var v1 = value1.statistic;
    var v2 = value1.pvalue;
    var value2 = scipy.stats.mannwhitneyu(dataList1, dataList2);
    var v3 = value2.statistic;
    var v4 = value2.pvalue;
}

I plan to write an API interface to call python. But I found that it can't be deployed in the IIS environment. As soon as the interface API is started, the application pool stops. I tried the following address https://www.cnblogs.com/68681395/p/3612119.html To solve the problem, but failed to solve it.

应用程序池“XXX”将被自动禁用，原因是为此应用程序池提供服务的进程中出现一系列错误。

**Comment by filmor** [comment]
This is not a support forum.
