### ISSUE TITLE
Running python scripts in c# using pythonnet

### ISSUE THREAD

**Issue by prene112** [pythonnet/pythonnet#1185]
### Environment

-   Pythonnet version: 3.7.1
-   Python version: 3.7
-   Operating System: windows 10 home

### Details

-   Describe what you were trying to get done.

    I was trying to run the same code that was shown in this link https://github.com/pythonnet/pythonnet/issues/356. I created the same python script and created a pythonnet project to run the c# code. I installed the nuget package for pythonnet as well with no complications. However, when I ran the program, I kept getting an error that says (Python.Runtime.PythonException: 'ModuleNotFoundError : No module named 'clsTest'') I am unsure as to why because I also included the python script in the same directory as the c# script. I was not getting the same result that the people got in the post that I linked to above. If anyone could help me, that would be greatly appreciated. Thank you.

**Comment by lostmsu** [comment]
@prene112 please, refer to [Python module search paths](https://realpython.com/lessons/module-search-path/)
