### ISSUE TITLE
PyScope.Exec(code) never returns, if it is called in an async/await method in C# second time.

### ISSUE THREAD

**Issue by tetsushmz** [pythonnet/pythonnet#1188]
### Environment

-   Pythonnet version: V2.5.1.
-   Python version: V3.8.4 (64 bit)
-   Operating System: Windows 10 (64 bit)

### Details

1. Create a WPF (.NetFramework) app with Visual Studio 2019.
2. Uncheck "Prefer 32 bit" in the project properties/Build page.
3. Add a Button in Grid with a Click handler in MainWindow.xaml.
4. Add the following C# code in MainWindow.xaml.cs.
```python
private async void ButtonBase_OnClick(object sender, RoutedEventArgs e)
{
    var result = string.Empty;
    await Task.Run(() =>
    {
        using (Py.GIL())
        {
            dynamic sys = PythonEngine.ImportModule("sys");
            var script =
                "import sys\n" +
                "from io import StringIO\n" +
                "sys.stdout = StringIO()\n" +
                "sys.stdout.flush()\n" +
                "sys.stderr = StringIO()\n" +
                "sys.stderr.flush()\n" +
                "print('hello')\n";
            var scope = Py.CreateScope();
            scope.Exec(script);
            result = sys.stdout.getvalue();
        }
    });

    MessageBox.Show(result);
}
```
5. Run it.
6. Click the Button.
7. A message box with "hello" is displayed as expected.
8. Click OK.
9. Immediately click the Button again.
10. A message box with "hello" is displayed.
11. So far, so good.
12. Now, wait 30 seconds.
13. Click the Button.
14. The message is never displayed. This is because "scope.Exec(script)" call never returns.

My actual Python script is a long running task with numpy/scipy and can take several minutes. So, I don't want to execute it on the main UI thread. This is why I used a Task with async/await. If I remove the Task and async/await, then the code works every time regardless of how long I wait between the button clicks.

I guess there can be a threading issue with GIL().

I'd appreciate it if you'd get me any suggestions.

Thanks,

**Comment by lostmsu** [comment]
Please, refer to [Threading](https://github.com/pythonnet/pythonnet/wiki/Threading).
