### ISSUE TITLE
Python.Runtime.PythonException: 'ModuleNotFoundError : No module named 'numpy''

### ISSUE THREAD

**Issue by hotwired** [pythonnet/pythonnet#1189]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.6.8
-   Operating System: Win2k12 R2

### Details

-   Describe what you were trying to get done.

this is only one Python (3.6.8)  installed to C:\PYTHON36.  numpy 1.19.1 + MLK installed.  
using VS 2019,  I created the project:

//===================================
using System;
using Python.Runtime;
using System.IO;

namespace demo_py3
{
    class Program
    {
        private static string pathToPython = @"C:\PYTHON36";
        static void Main(string[] args)
        {

            Console.WriteLine("Hello World!");
            PythonEngine.Initialize();
            Console.WriteLine("Initialized");
            var lib = new[]
            {
                Path.Combine(pathToPython, "Lib"),
               // Path.Combine(pathToPython, "Lib\\site-packages"),
               // Path.Combine(pathToPython, "DLLs")
            };
            PythonEngine.PythonHome = pathToPython;
            string paths = string.Join("; ", lib);
            PythonEngine.PythonPath = paths;

            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                Console.WriteLine(np.cos(np.pi * 2));
            }

        }
    }
}
//=====================================================
         

-   What commands did you run to trigger this issue? If you can provide 
     
     (1) In VS2019 IDE,  right click the project demo_py3 -> debug -> start new instancce
     (2) or direct run the compiled binary  : demo_py3.exe

```python
    print('TODO')
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.0
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************

C:\Users\mysid\source\repos\demo_py3>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print(np.__version__)
1.19.1
>>> print('TODO')
TODO
>>>

-   If there was a crash, please include the traceback here.

C:\Users\mysid\source\repos\demo_py3\bin\x64\Debug>demo_py3.exe
Hello World!
Initialized

Unhandled Exception: Python.Runtime.PythonException: ModuleNotFoundError : No mo
dule named 'numpy'
   at Python.Runtime.Runtime.CheckExceptionOccurred()
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at demo_py3.Program.Main(String[] args) in C:\Users\mysid\source\repos\demo_
py3\Program.cs:line 28

C:\Users\mysid\source\repos\demo_py3\bin\x64\Debug>

```python
    print('TODO')
```

**Comment by filmor** [comment]
This is not a support forum. Please ensure that all paths (and paths to dependencies) are set up correctly and insert a few `print`s to see what Python thinks its paths are.
