### ISSUE TITLE
Failed to add a .dll which reference is an embedded resource 

### ISSUE THREAD

**Issue by MPapus** [pythonnet/pythonnet#1198]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.6.3:2c5fed8
-   Operating System: Windows 10 1909 18363.959

### Details

-   I was trying to load a class Library I build for .Net Framework 4.7.1 which I included one of its references as an embedded resource, and then catch it up in AppDomain.AssemblyResolve so I can load it from resources. First dll has types that inherit from the embedded dll, just FYI.
-   If I build another Class Library which uses the first one issue does not appear.

-   Steps

```python
   import sys
   testpath = r"path\to\dlllocation"
   sys.path.append(testpath)
   import clr
   clr.AddReference('NameOfDllIncludingReferenceAsEmbeddedResource')
   from SomeNamespace import SomeClass
   ModuleNotFoundError: No module named 'SomeNamespace'
```

While debugging 2.5.1 code of pythonnet's solution I found out the problem is here [assemblymanager.cs](https://github.com/pythonnet/pythonnet/blob/master/src/runtime/assemblymanager.cs) (line 499). Here is where Python.Net AssemblyResolve is fired up.

Is there a way to address this? like overriding the AssemblyResolve event or something similar...

Thank you very much!

**Comment by lostmsu** [comment]
Sorry for the late reply, but where is `SomeNamespace` defined? For the sample code to work it must be defined in `NameOfDllIncludingReferenceAsEmbeddedResource`.

**Comment by MPapus** [comment]
Hi, no problem! Yes, it is defined inside the reference I'm adding, not the embedded one.

**Comment by lostmsu** [comment]
`SomeClass` must be public, and be defined in `SomeNamespace` in 'NameOfDllIncludingReferenceAsEmbeddedResource'.

Is it by any chance some special type?
Considering `AddReference` itself does not fail, a problem might be elsewhere. Check the spelling.

**Comment by MPapus** [comment]
Maybe I was not 100% clear. 

If I put a copy of the embedded dll reference in the same directory, it works like a charm. Problem appears when the types being used in the dll imported to Python.NET inherit from types inside an embedded reference. Always using the same dll, always importing public classes.

**Comment by taruntadikonda** [comment]
Facing same Issue.

I am calling a c# dll from python and getting the following error.
Traceback (most recent call last):
  File "mft.py", line 29, in <module>
    from mfttestdll import Test
ImportError: cannot import name 'Test'

My python code

`import clr`
`clr.AddReference(R'C:\Users\tarun\Desktop\office\pythonprojects\mfttestdll\mfttestdll\bin\x64\Release\mfttestdll.dll')`
`from mfttestdll import Test`

My C# code 

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RGiesecke.DllExport;
using System.Runtime.InteropServices;
using System.Windows.Forms;
namespace mfttestdll
{
    public class Test
    {
        [DllExport("get", CallingConvention = CallingConvention.Cdecl)]
        public static string get(string a)
        {
            MessageBox.Show(a);
            return a;
        }
    }
}`

**Comment by lostmsu** [comment]
@MPapus so far I am not convinced this is a Python.NET issue. When you reference that DLL from C#, how does it load the dependency from an embedded resource? Which step of that process do you think is broken by Python.NET?

**Comment by MPapus** [comment]
Sorry for the late reply. You were right @lostmsu, I was embedding wrongly the needed assemblies. I'm closing this

**Comment by MPapus** [comment]
Sorry for the late reply. You were right @lostmsu , I was embedding wrongly the needed assemblies. I'm closing this
