### ISSUE TITLE
add python 3 support

### ISSUE THREAD

**Issue by tonyroberts** [pythonnet/pythonnet#12]

**Comment by hognala** [comment]
How's the python 3 and general version 2.0 working going?

**Comment by tonyroberts** [comment]
The python3 branch (https://github.com/renshawbay/pythonnet) has now been rebased on the main pythonnet repo so it's not in too bad shape. The newer features that I'd like to see in 2.0 are in that branch too (subclassing .net classes in python etc). Everything in that branch is unittested and working for python 2, but there are some problems with some of the tests for python 3 still (see build status on the other fork's page). The 3.2 x64 build is what I'm currently using, which is working fine for me (and passing all unittests). I'll keep chipping away at the remaining problems as time permits, but unfortunately it's not a priority for me at the moment. If you want to dive in and take a look at any of the remaining issues please do, I'm always happy to review/merge pull requests!

**Comment by tonyroberts** [comment]
Done in 138bda7260b77e9bd0d2ca4f1447fbc5f0fbfe33
