### ISSUE TITLE
Unable to find type [Python.Runtime.Py].

### ISSUE THREAD

**Issue by EadderYin** [pythonnet/pythonnet#1202]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.7.8
-   Operating System: windows 10 pro

### Details

-   Describe what you were trying to get done.

    I installed pythonnet as '`pip install pythonnet`', and snek as '`Install-Module -Name Snek`'
But, when I's trying to import python module in powershell as '`Import-PythonModule Requests`', It gives me an error like:'
`Unable to find type [Python.Runtime.Py].                                                                                                                       At C:\Program Files\WindowsPowerShell\Modules\snek\1.3\snek.psm1:48 char:13                                                                                    +     $ar.add([Python.Runtime.Py]::Import($Name)) | Out-Null                                                                                                   +             ~~~~~~~~~~~~~~~~~~~                                                                                                                                  + CategoryInfo          : InvalidOperation: (Python.Runtime.Py:TypeName) [], RuntimeException                                                                  + FullyQualifiedErrorId : TypeNotFound       
`
**Both Python.runtime.dll and clr.dll are exist.**
Did I forget something?

**Comment by lostmsu** [comment]
This does not look like Python.NET problem.
