### ISSUE TITLE
Adding thread state storage for embedders 

### ISSUE THREAD

**Issue by QuickWire** [pythonnet/pythonnet#1215]
### Environment

-   Pythonnet version: 3.0.0
-   Python version: 3.x
-   Operating System: Windows 10, + others

### Details

-   I need access to the **PyThreadState_GetDict** cpython call.

    I have embedded Python.Net in my app but since I have multiple threads (tasks) running scripts and calling back into C#, I require a way to store my thread context into the current Python thread.
    To to this I imported PyThreadState_GetDict myself (worked fine), but I also needed the other low level cpython calls that are set as internal in the Python.Runtime class.
 
   So here would be the new member exposed by Python.Runtime (or somewhere)
```	
public PyDict GetThreadStateDict()
{
	IntPtr dict = Runtime.PyThreadState_GetDict();
	Runtime.XIncref(dict); // borrowed ref
	return new PyDict(dict);
}
```

And, then we can get & set an object of some kind
```
protected ScriptContext GetContext()
{
	using (var tdict = GetThreadStateDict())
	{
		using (PyObject context_key = tdict.GetItem(_thread_cookie_name_s))
		{
			return (ScriptContext)context_key.AsManagedObject(typeof(ScriptContext));
		}
	}
}

protected void SetContext(ScriptContext context)
{
	using (var tdict = GetThreadStateDict())
	{
		tdict.SetItem(_thread_cookie_name_s, context.ToPython());
	}
}
```

That is, unless there's a better way to keep track of what original thread is calling back into the app.
Maybe the Python Thread Specific Storage (TSS) API would be better?

**Comment by lostmsu** [comment]
@QuickWire is there any reason you can not use .NET `ThreadLocal<T>`?
