### ISSUE TITLE
Multiple assertion failures for Python classes derived from System.Exception in debug builds

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1218]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.8
-   Operating System: Win 10 64

### Details

In debug build (`DebugWinPY3`) this test:
https://github.com/pythonnet/pythonnet/blob/61d1b7c22eb7cd68f991d35fcafbdf4dd90b7b19/src/tests/test_constructors.py#L41

fails this assertion:
https://github.com/pythonnet/pythonnet/blob/61d1b7c22eb7cd68f991d35fcafbdf4dd90b7b19/src/runtime/interop.cs#L92

Python type object for `Sub` class gets an unknown extra field of size `IntPtr.Size`, causing it to be larger than its base type object (reflected) `System.Exception`.

See also https://github.com/pythonnet/pythonnet/pull/1196#issuecomment-690750845 for previous discussion.

@koubaa @amos402

**Comment by lostmsu** [comment]
It seems that the reason is that `System.Exception` has no weak list associated with it:

> Marshal.ReadInt32(type, TypeOffset.tp_weaklistoffset) // type == Sub
> 80
> Marshal.ReadInt32(Marshal.ReadIntPtr(type, TypeOffset.tp_base), TypeOffset.tp_weaklistoffset)
> 0

**Comment by amos402** [comment]
Because it used tp_basicsize as the slot to save GCHandle, you can test it on soft-shutdown branch, it should be fine.
https://github.com/amos402/pythonnet/blob/12c0206b94173935864e0434ec22898753ffb6b5/src/runtime/interop.cs#L116-L117
I changed the slot.

**Comment by lostmsu** [comment]
@amos402 not exactly sure what you mean. The reflected `System.Exception` should already have a slot for `GCHandle`. If that would be the reason, size of `Sub` would be equal to size of `System.Exception`, but it is not.

**Comment by amos402** [comment]
![image](https://user-images.githubusercontent.com/3406561/92886288-1bd42f00-f446-11ea-86dd-af8662b1977e.png)
Trust me, it fixed. 
![image](https://user-images.githubusercontent.com/3406561/92887536-2511cb80-f447-11ea-80c1-d5f7cfc6ac51.png)

The reason is as I said. The size of `Sub` come from `type(System.Exception)->tp_basicsize`, they're not equal.

**Comment by koubaa** [comment]
@lostmsu @amos402 I just took Amos's interop changes from the soft shutdown branch and applied them to master, and this issue goes away.  I'll submit a PR soon with this change, even if it doesn't fix my PyType_FromSpec it could still make the soft shutdown branch easier to review without these changes

**Comment by koubaa** [comment]
Fixed in master
