### ISSUE TITLE
Usin System.Memory.Span fails

### ISSUE THREAD

**Issue by realgpasternak** [pythonnet/pythonnet#1221]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.8.5
-   Operating System: Windows 10

### Details

-   I have a csproj which targets .NET Framework 4.7.2. I was trying to run a C# method which uses Span<T> from python. Any function which uses Span<T> internally throws this exception, and other functions from the same class which don't - work correctly. System.Runtime.CompilerServices.Unsafe.dll is located in the same directory as my DLL, although of newer version (4.7.1).

```cs
    ...
    public class CsExportGate
    {
        public void CalculateSunset()
        {
            Span<double> x = new double[(int)100];
        }
    }
    ...
```

```python
    import sys
    import clr

    sys.path.append(r"d:\Code\cms\common\pytools\csexport\CsExport\bin\Debug")
    clr.AddReference("CsExport")
    from CsExport import CsExportGate
    gate = CsExportGate()
    gate.TrySpan()
```

-   If there was a crash, please include the traceback here.

```python
Traceback (most recent call last):
  File "c:\workspace\csexport\try_sv.py", line 9, in <module>
    gate.TrySpan()
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.Span`1..ctor(T[] array)
   at System.Span`1.op_Implicit(T[] array)
   at CsExport.CsExportGate.TrySpan() in D:\Code\cms\common\pytools\csexport\CsExport\CsExportGate.cs:line 62
```

Thanks ahead.

**Comment by filmor** [comment]
Please check here: https://github.com/pythonnet/pythonnet/issues/832

You need to use some mechanism to tell .NET about which DLL versions to use.
