### ISSUE TITLE
python setup.py install puts Python.Runtime.dll into wrong directory

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#123]
the python setup.py install builds and installs pythonnet as egg and puts Python.Runtime.dll into wrong directory. The wheel version is fine (python setup.py bdist_wheel).

**Comment by mx** [comment]
I also noticed this on Windows 10. Wheel via bdist_wheel worked fine as well.

**Comment by denfromufa** [comment]
related, apperantly the fix was partial @tonyroberts?

https://github.com/pythonnet/pythonnet/issues/44

**Comment by denfromufa** [comment]
also it was working at this point: https://github.com/pythonnet/pythonnet/issues/24

**Comment by tonyroberts** [comment]
it's only distributed as wheels now, so as this only applies to eggs this isn't an issue.
