### ISSUE TITLE
Load DLL issue on Shared Network

### ISSUE THREAD

**Issue by emrecpp** [pythonnet/pythonnet#1231]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.5
-   Operating System: windows 10

### Details

-   
Hi, I am build my python code with pyarmor + nuitka so i get exe. Sharing this exe with shared network.
But When exe tries to load dll (import clr) it gets 
`Unhandled Exception: System.IO.FileLoadException: Failed to load the file 'file: // \\ 192.168.1.251 \ MyFolder\ GameMenu \ Python.Runtime.dll' or its integrated code or one of its dependencies. Operation is not supported. (HRESULT returned exception: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an integrated code from a network location that would cause it to be sandboxed in previous .NET Framework versions. This .NET Framework version does not enable CAS policy by default, so the installation in question can be dangerous. If this installation is not intended to sandbox the integrated code, please enable the loadFromRemoteSources switch. For more information. http://go.microsoft.com/fwlink/?LinkId=155569`

But when i copy all folder to desktop, trying to run my exe, it works fine. The issiue is load dll from shared network.
Thank you!

**Comment by filmor** [comment]
The exception text contains everything you need. This has nothing to do with pythonnet, it would happen in a pure C# application as well.
