### ISSUE TITLE
requirement for x86 version nuget package

### ISSUE THREAD

**Issue by heartacker** [pythonnet/pythonnet#1236]
hi,  from nuget.org or VS NUGET-Managment, there is no x86 version pythonnet, and I have a WPF APP runing  within x86-netcore-runtime(invoke some x86 c++ dll,so have to  run within x86 runtime). so please publish an x86 version pythonnet. thanks

**Comment by filmor** [comment]
We are currently not providing Nuget packages at all. When we do, they will be arch-independent.
