### ISSUE TITLE
Class instance a derived Python class or pure C#?

### ISSUE THREAD

**Issue by C-SELLERS** [pythonnet/pythonnet#1239]
Hey everybody, I am trying to see if there is a way to determine if my instance of a class is a pure C# class or a derived from C#  Python class.

Here is an example:

Lets say I have a C# class `public class Parent`,
   -> in Python I create a subclass of it `class PyClass(Parent)`, 
   -> in C# I create a subclass of it `public class CSharpClass : Parent`

In both of these cases when I create the new objects it will use the Parent class constructor, but in that constructor I would like the behaviour to change if the instance is from a derived python class.

Is there a way to verify in the Parent class constructor that its being used in a derived Python class?

Thank you!

**Comment by C-SELLERS** [comment]
Just to follow up on this question, I have an example that might illustrate what I am asking a bit more clearly:

```
public class Parent
{
	public Parent()
	{
                var isPython = this.AmIPythonInstance();  <- How would this look? Is it possible?
		var pythonSelf = this.GetMyselfAsPython();  <- If the above is possible, can I take it further and get a copy of the Python self?
	}		
}

class PyClass(Parent):
	def DummyMethod():
		return "I don't matter"
```

**Comment by lostmsu** [comment]
`this.GetMyselfAsPython()` -> depending on your needs you can either call `this.ToPython()` (applies conversions) or `PyObject.FromManagedObject(this)` (no conversions).

As to the first part of your question, I suggest you to inspect the resulting object and check for any obvious differences (would be nice if you report your findings here).

**Comment by C-SELLERS** [comment]
Thanks Victor, 

I did give those a try the other day, and the resulting object was the C# instance and had none of the Python overrides or variables. I tested this by taking the resulting PyObject and attempting to get its overridden method and then calling it. It unfortunately routed to the superclasses C# method 😢 

As for comparing the resulting objects I did not find anything specific that would be able to identify the pure C# and python derived instances although there was lot to check. 🤔

**Comment by C-SELLERS** [comment]
Interesting find today,

Using Pythons Garbage Collector I can go find all the object instances that are my class or derived from my class. Here is the statement I'm using in C# to do it:

```            
                // Get all PyObjects that are instances of my object
                var instances = PythonEngine.ModuleFromString(
                    "getObject",
                    "import gc\n" +
                    "def get_instances(obj):\n" +
                    "   return [x for x in gc.get_objects() if isinstance(x, type(obj))]"
                ).InvokeMethod("get_instances", obj.ToPython());
```

Two interesting things with this:
- This cannot be used in the C# superclass constructor because the derived python class is not done initializing yet. So if I want to get my python instance I have to do it after construction. 😞 
- I tried to pass a type to get_instances so it would be simpler and I wouldn't have to get the type on the python side but for some reason passing the type to Python like `obj.GetType().ToPython()` doesn't seem to work with `isinstance(x, obj)`, it doesn't recognize obj as a type 🤔; looking into other issues I see #859 which seems to be the same problem I'm seeing where I can't send a type across to python and have it be the same type as if I imported it in Python.

**Comment by C-SELLERS** [comment]
Just a heads up, if anybody tries using the above, instances will also contain a copy of the object your originally passed in. I realize this probably isn't desired so I added one extra step that will go get the type first, then dispose of our converted Python obj.

```
        /// <summary>
        /// Method for getting Python instances of a given obj type.
        /// This includes all subclass instances of the obj type.
        /// </summary>
        /// <param name="obj">instance of the object type you want to collect</param>
        /// <returns>Python List of PyObjects</returns>
        private static PyObject GetPythonInstances(object obj)
        {
            using (Py.GIL())
            {
                // Passing Python a type, even when converted using ToPython(), does not actually convert to Python type
                // so we must go fetch the type from Python, then dispose of this object so we don't get it in our list of
                // instances.
                var PythonObject = PyObject.FromManagedObject(obj);
                var type = PythonEngine.ModuleFromString(
                    "getPyType",
                    "def get_type(obj):\n" +
                    "   return type(obj)"
                ).InvokeMethod("get_type", PythonObject);
                PythonObject.Dispose();

                // Get all PyObjects that are instances of the type determined
                var instances = PythonEngine.ModuleFromString(
                    "getObject",
                    "import gc\n" +
                    "def get_instances(objType):\n" +
                    "   return [x for x in gc.get_objects() if isinstance(x, objType)]"
                ).InvokeMethod("get_instances", type);

                return instances;
            }
        }
```

**Comment by lostmsu** [comment]
@C-SELLERS I was debugging some unrelated issue today, and came across `ClassDerivedObject`, that handles certain Python classes derived from C#.

First, is there a reason you don't want to define your class as a CLR-like class? To do that you'd need to set `__namespace__` like this:

```python
class MyClass(Prototype.IProcessControl):
    __namespace__ = "Axa.Core.Prototype"
```

I believe in this case the derived class will implement dummy `IPythonDerivedType`.
