### ISSUE TITLE
calling asp.net core 2.2 class library api from python using pythonet gives error as "module not found"

### ISSUE THREAD

**Issue by Nagarwal06** [pythonnet/pythonnet#1243]
**Code:-**
import sys
sys.path.append(r"C:\myfolderA\myfolderB")
print sys.path
 import clr
 clr.FindAssembly(r"AA.BB.CC")
 clr.AddReference(r"AA.BB.CC")
 from AA.BB.CC.Api.DDInterface import DDClient

**Error:-**
 **On the above line I am getting following error**
Traceback (most recent call last):
  File "C:\myfolderA\myfolderB\testAPI.py", line 7, in <module>
     from AA.BB.CC.Api.DDInterface import DDClient
 ImportError: No module named AA.BB.CC.Api.DDInterface

There is no other information available to exactly identify the issue.
Whereas, same approach working perfectly for dotnet framework. But only, issues are coming when I am running the scripts with python.
I am using Python 3.6.5

Your help is deeply appreciated.

Thanks,

**Comment by lostmsu** [comment]
AFAIK, currently Python.NET can not start .NET Core runtime from Python. When you import assemblies, you always do it using .NET Framework runtime on Windows.

**Comment by filmor** [comment]
The state is described in the pinned issue #984. Embedding .NET Core into Python will be in the 3.0 release. It has not landed in `master`, yet.

**Comment by Nagarwal06** [comment]
@filmor But i am able to call  asp.net core 2.0 class library api from python using pythonet. And it is working fine.
So, I dont think the issue is with Pythonnet. It might be the issue with the netstandard version.
