### ISSUE TITLE
Instantiating Arrays of types causes a segfault and crashes python

### ISSUE THREAD

**Issue by bneumann** [pythonnet/pythonnet#1244]
### Environment

-   Pythonnet version: 2.5.0
-   Python version: 3.7.6
-   Operating System: Ubuntu 18.04 / Windows 10

### Details

-   Describe what you were trying to get done.

I am trying to preallocate an Array of ILists of UInt32

```python
import clr
clr.AddReference("System.Runtime")
clr.AddReference("System.Collections")
import System

# This works
System.Array.CreateInstance(System.Collections.Generic.IList[System.UInt32], 100)
# This works too
System.Array.CreateInstance(System.Collections.Generic.IList[System.UInt32], 200)
# This simply crashes python
System.Array.CreateInstance(System.Collections.Generic.IList[System.UInt32], 300)

```

-   If there was a crash, please include the traceback here.

There is nothing really getting printed :(

**Comment by filmor** [comment]
1. Does this really happen on both Ubuntu and Windows?
2. Are you using .NET Framework or Mono on Windows?
3. Does this happen as well with 2.5.1 and the current master?
4. Can you please attach a debugger?

In my local installation on Windows with .NET Framework I can't reproduce this right now, will try on Linux later.

**Comment by bneumann** [comment]
> Does this really happen on both Ubuntu and Windows?

Yes we have an CI running inside a docker. We also experience it on 2 machines here.

> Are you using .NET Framework or Mono on Windows?

.NET Framework 7.4.2


> Does this happen as well with 2.5.1 and the current master?

It seems to work at least under windows. Will test under linux

> Can you please attach a debugger?

Did that and I am hanging at `return Array.InternalCreate((void*)runtimeType.TypeHandle.Value, 1, &length, null);`.

**Comment by bneumann** [comment]
Wonderful. It seems it was just our "old" version of pythonnet. Thanks I closing again
