### ISSUE TITLE
len function support to ICollection breaks Python - implicit object check

### ISSUE THREAD

**Issue by partha-srivi** [pythonnet/pythonnet#1249]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: Python 37
-   Operating System: Windows

### Details

-   This is to inform the __len__ support added to ICollections has broken our code where we performed implicit object checks.
We have fixed the issue by performing explicitly checking the object is not None.

```python
import clr 
import System
from System.Collections import ArrayList
obj = ArrayList()
if obj:
    print(obj.Count)  
```
- In Pythonnet 2.4.0 the print statement prints 0, where in pythonnet 2.5.1 the print statement is not executed.
- If the object is of type Disposable Collection instead of ArrayList and disposed already, then the if statement itself throws the exception _System.ObjectDisposedException: Cannot access a disposed object_, as the __len__ function tries to access Count property of the disposed object

**Comment by filmor** [comment]
To be honest, I think this is all working as intended. Sorry for breaking this within minor versions, though.
