### ISSUE TITLE
Distribute binaries w/ "Releases"?

### ISSUE THREAD

**Issue by bc3tech** [pythonnet/pythonnet#125]
@tonyroberts I'd love to consume the output of this w/o having to build it. In particular, I'm the maintainer of [the Chocolatey package](https://chocolatey.org/packages/pythonnet/1.02) so having release binaries is vastly preferred.
While I _could_ build the project from the source here, that's not quite what Chocolatey aims to distribute.

Any chance we could ship some bins when we do releases as well?

**Comment by tonyroberts** [comment]
Builds are already uploaded to pypi - see https://pypi.python.org/pypi/pythonnet/2.1.0.dev1

**Comment by denfromufa** [comment]
@bc3tech you can also download builds from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet which has even Python 3.5 builds

**Comment by bc3tech** [comment]
@denfromufa thanks, but for my purposes (creating a pkg for python.net on [chocolatey.org](http://chocolatey.org)) it needs to be located at the source of the project itself (for integrity's sake)
