### ISSUE TITLE
Status/plan of pythonnet for Python 3.9 support

### ISSUE THREAD

**Issue by m-rossi** [pythonnet/pythonnet#1262]
What's the status/plan for support for Python 3.9? The migration of the conda-forge-recipes for Python 3.9 started recently and the pipelines for Python 3.9 failed: https://github.com/conda-forge/pythonnet-feedstock/pull/6

**Comment by filmor** [comment]
Python 3.9 is not supported, yet. I have opened #1264 to see whether the tests pass, but neither Travis nor Appveyor has Python 3.9 available at this time. Once that is the case, we'll look into it for master. If the changes required are trivial, I'll backport them to the 2.5 branch.

**Comment by m-rossi** [comment]
Ok, thanks for the update!

**Comment by passariello** [comment]
Please, Do you have a time estimation for supporting the 3.9?

**Comment by m-rossi** [comment]
Looks like this can be closed. Looking forward for a new release of pythonnet with support for Python 3.9, thanks!

**Comment by m-rossi** [comment]
Officially not, see https://github.com/pythonnet/pythonnet/issues/1389 for example.

**Comment by Sshankar7** [comment]
When can we expect an official release of pythonnet available for Python 3.9.0? None of the solutions provided is working on my Windows 10.

**Comment by vipulpatel2103** [comment]
Hi @Sshankar7, Please try 2.5.2.0. I tried along with Python 3.9.5 and it's working.

**Comment by matthew1davis** [comment]
It's November 2021 and the pythonnet library still does not officially support 3.9 yet despite a commit in October that mentioned 3.10 compatibility... does this issue need to be reopened?

**Comment by dlc60** [comment]
> It's November 2021 and the pythonnet library still does not officially support 3.9 yet despite a commit in October that mentioned 3.10 compatibility... does this issue need to be reopened?

Not yet.  A pip install still errors out on Python 3.9.6.

**Comment by Richard944** [comment]
This looks like it needs to be reopened because there is no 3.9 support on pypi.org.

In an unsecure workaround people are using it by downloading a wheel file from an .edu site:
https://stackoverflow.com/questions/67418533/how-to-fix-error-during-pythonnet-installation

**Comment by lostmsu** [comment]
There's now 3.0.0a1 package available with 3.9 support

**Comment by Richard944** [comment]
> There's now 3.0.0a1 package available with 3.9 support

Not really? Looking on pypi.org it's the same 2.5.2 from Feb 5, 2021 (https://pypi.org/project/pythonnet/). Is there some disconnect in how this package gets released?

**Comment by lostmsu** [comment]
@Richard944  https://pypi.org/project/pythonnet/#history

BTW, @filmor , there's no alpha for 3.10. Do we have anything blocking it?

**Comment by m-rossi** [comment]
> > There's now 3.0.0a1 package available with 3.9 support
> 
> 
> 
> Not really? Looking on pypi.org it's the same 2.5.2 from Feb 5, 2021 (https://pypi.org/project/pythonnet/). Is there some disconnect in how this package gets released?

You can install pre releases with

```sh
pip install --pre pythonnet
```

See https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions

**Comment by Richard944** [comment]
> @Richard944 https://pypi.org/project/pythonnet/#history
> 
> BTW, @filmor , there's no alpha for 3.10. Do we have anything blocking it?



> 

"PRE-RELEASE" Thanks!

**Comment by filmor** [comment]
> @Richard944  https://pypi.org/project/pythonnet/#history
> 
> BTW, @filmor , there's no alpha for 3.10. Do we have anything blocking it?

No, this is just a mistake in the metadata. I'll fix it tomorrow.

**Comment by Richard944** [comment]
I'm finding that pythonnet 3.0.0a1 works and pythonnet 3.0.0a2 does not work. There must be some difference. I am running a 3.9.6 python virtual environment.

With both versions I see the dll in site-packages\pythonnet\runtime.

..\.venv_amd64_3.9.6\lib\site-packages\pythonnet\__init__.py:44: in load
    raise RuntimeError("Failed to initialize Python.Runtime.dll")
E   RuntimeError: Failed to initialize Python.Runtime.dll

I'm ok using 3.0.0a1 but I wanted to share what I saw.

**Comment by m-rossi** [comment]
> I'm finding that pythonnet 3.0.0a1 works and pythonnet 3.0.0a2 does not work. There must be some difference. I am running a 3.9.6 python virtual environment.
> 
> With both versions I see the dll in site-packages\pythonnet\runtime.
> 
> ...venv_amd64_3.9.6\lib\site-packages\pythonnet__init__.py:44: in load raise RuntimeError("Failed to initialize Python.Runtime.dll") E RuntimeError: Failed to initialize Python.Runtime.dll
> 
> I'm ok using 3.0.0a1 but I wanted to share what I saw.

@Richard944 I recommend opening a separate issue for this error.

**Comment by m-rossi** [comment]
The pre-release version can now also be installed via conda by executing
```sh
conda install -c conda-forge/label/pythonnet_dev -c conda-forge pythonnet
```
