### ISSUE TITLE
Importing Modules

### ISSUE THREAD

**Issue by kamrantekkit** [pythonnet/pythonnet#1263]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.8.6
-   Operating System: Windows 10

### Details

I am trying to import modules. Modules are imported as when i run it there is no errors however visual studio code is saying modules are not imported.

### Code
`import clr

clr.AddReference("System.Windows.Forms")

import System.Windows.Forms`

![image](https://user-images.githubusercontent.com/36983539/95866430-d0bc7d00-0d5f-11eb-81dd-976cc3036ef8.png)

**Comment by fuomag9** [comment]
That's due to runtime stuff that happens, vscode does not know that before the code executes and thus flags them

**Comment by kamrantekkit** [comment]
anyway to fix this?

**Comment by fuomag9** [comment]
I don't think there's an easy fix, you could try to suppress errors (I don't usually use vscode so I don't know how to suppress single lines)

**Comment by filmor** [comment]
This has to be fixed in the language server. PRs to improve the language-server/pythonnet interaction are welcome, but this is not really a bug.
