### ISSUE TITLE
version conflict when i call 1 dll and it have a dependency will another 2 dll (same dll but different version)

### ISSUE THREAD

**Issue by kailinghuang** [pythonnet/pythonnet#1266]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.6
-   Operating System: windows

### Details
the problem happen in
C# code:
```
var loggerFactory = LoggerFactory.Create(builder => {
                builder.AddApplicationInsights();
            }
```

loggerFactory.Create: need microsoft.extention.logging 3.1.0

AddApplicationInsights()`: need microsoft.extention.logging 2.1.0
FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

-   Describe what you were trying to get done.

i try import 2.0 reference also.
MissingMethodException: Method not found:
'Microsoft.Extensions.Logging.ILoggingBuilder Microsoft.Extensions.Logging.ApplicationInsightsLoggingBuilderExtensions.AddApplicationInsights(Microsoft.Extensions.Logging.ILoggingBuilder)

i guess this is becasue there are 2 verion. so it don't how to find the right path.

does any meet this problem? and how could you fix it!

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by filmor** [comment]
This is not a support forum. There is some information on Binding Redirects (which is the term to look for) in this ticket: https://github.com/pythonnet/pythonnet/issues/832
