### ISSUE TITLE
 Exception：<exception str() failed> 

### ISSUE THREAD

**Issue by longxinyun-security** [pythonnet/pythonnet#1270]
### Environment

-   Pythonnet version: 
- 2.5.1
-   Python version:
- Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
-   Operating System:
- Windows 10 10.0.18363.1016

### Details

-   Describe what you were trying to get done.

    What should i do,using windbg to find problems???

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    mLicenseKey = String("1111")
    input()
    xxxSDK(mLicenseKey)
    #public xxxSDK(string apiKey) C# 
```

-   If there was a crash, please include the traceback here.
![image](https://user-images.githubusercontent.com/70429515/97740172-d36af080-1b1b-11eb-9cf4-627fdfdd2b89.png)

```python
    print('TODO')
```

**Comment by filmor** [comment]
I'm sorry, but this is not a support forum and I don't understand what you are trying to report. For help with debugging, please ask on the mailing list.
