### ISSUE TITLE
Python.Runtime.dll Unable to load DLL 'python3.8' or one of its dependencies: The specified module could not be found. (0x8007007E)

### ISSUE THREAD

**Issue by ccistonery** [pythonnet/pythonnet#1273]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.7.7
-   Operating System: Windows 7 64-bits

### Details

- I am new in C# and want to use Pythonnet for running python code. After following page to install  and compile. 
Problem occur in Py.GIL()

Firstly, I got System.MissingMethodException and follow below link to fix
https://stackoverflow.com/questions/53628176/call-python-script-from-net-core-using-pythonnet/56085756#56085756

Then, Python.Runtime.dll unable to load. 

Python.Runtime.dll and clr.pyd are in Python37-32\Lib\site-packages

I follow below to try but no luck. 
https://www.nuget.org/packages/Python.Runtime.UnofficialNetStandard/3.0.0-b01
https://www.gitmemory.com/issue/pythonnet/pythonnet/871/495698289

Any advice would be appreciated.

**Comment by lostmsu** [comment]
@ccistonery `Python.Runtime.UnofficialNetStandard` requires you to set `Runtime.PythonDLL` to the full path to the actual python DLL (e.g. python37.dll on Windows) before invoking any other functions.

**Comment by ccistonery** [comment]
@lostmsu I added the path to set environment variable but still get same error.

- Runtime.PythonVersion and Runtime.PythonDLL cannot compile
- Properties -> Build -> Prefer 32 bits.

Any comment? 

class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

           string EnvPath = @"C:\Users\User\AppData\Local\Programs\Python\Python37-32\Scripts";
            string pythonPath = @"C:\Users\User\AppData\Local\Programs\Python\Python37-32\Lib;" + @"C:\Users\User\AppData\Local\Programs\Python\Python37-32\Lib\site-packages";

            Environment.SetEnvironmentVariable("PATH", EnvPath, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONHOME", EnvPath, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONPATH", pythonPath, EnvironmentVariableTarget.Process);

            
            PythonEngine.PythonHome = Environment.GetEnvironmentVariable("PYTHONHOME", EnvironmentVariableTarget.Process);
            PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH", EnvironmentVariableTarget.Process);

            //Runtime.PythonVersion = Version.Parse("3.7.7");
            //Runtime.PythonDLL = @"C:\Users\User\AppData\Local\Programs\Python\Python37-32\python37.dll";

            using (Py.GIL())
            {
                Console.WriteLine("Hello test!");
            }
            
         }

**Comment by ccistonery** [comment]
@lostmsu 
I installed python 3.8.5 and changed the path to use it but same error occur.
Running PythonEngine.PythonHome = Environment.GetEnvironmentVariable("PYTHONHOME", EnvironmentVariableTarget.Process);  

enter exception. Unable to load DLL 'python3.8' or one of its dependencies: The specified module could not be found. (0x8007007E)

**Comment by lostmsu** [comment]
@ccistonery my comment applies to the unofficial version of package only: https://www.nuget.org/packages/Python.Runtime.UnofficialNetStandard/

In it `Runtime` has `PythonDLL` and `PythonVersion` properties.

**Comment by ccistonery** [comment]
@lostmsu  Thx

I tried this unofficial version yesterday but not work.

Now, I download the 2.4.0 package and didcompilation again in src/runtime using
> dotnet build -c ReleaseWinPY3 -f netstandard2.0 Python.Runtime.15.csproj

The Python.Runtime.dll can work in Python 3.7.7 under src/runtime/bin/netstandard2.0

Not sure why latest 2.5.1 package not work.
Always I closed this issue first.

It may be compatible issue with latest Python 3.8.x

**Comment by venkatrv** [comment]
We are still having the above mentioned issue. Any resolutions for this?

**Comment by lostmsu** [comment]
The `PythonDLL` feature from unofficial package has since been made official. You can install `pythonnet` from NuGet, and set `Runtime.PythonDLL`.

**Comment by Jammooly1** [comment]
@lostmsu How do you set it the Runtime? Can you provide an example code?

**Comment by jrdnwrth** [comment]
![image](https://user-images.githubusercontent.com/8084345/164324021-3dc4a9d6-8a0c-419f-be1a-926a0336867e.png)

It is readonly.  How am I supposed to set it?

**Comment by lostmsu** [comment]
@jrdnwrth in the official 3.0.0 previews of pythonnet package is it settable.

**Comment by esteban2006** [comment]
> @lostmsu How do you set it the Runtime? Can you provide an example code?

python version 3.10
windows 10 

pythonnet installation :
pip install pythonnet

I have a python script that import clr, as soon as i run my code i get the error 

```

 import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\superMario\Documents\deoc310\deoc\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Users\superMario\Documents\deoc310\deoc\lib\site-packages\pythonnet\__init__.py", line 148, in load
    func = assembly.get_function("Python.Runtime.Loader.Initialize")
  File "C:\Users\superMario\Documents\deoc310\deoc\lib\site-packages\clr_loader\types.py", line 94, in get_function
    return ClrFunction(self._runtime, self._path, name, func)
  File "C:\Users\superMario\Documents\deoc310\deoc\lib\site-packages\clr_loader\types.py", line 58, in __init__
    self._callable = runtime._get_callable(assembly, typename, func_name)
  File "C:\Users\superMario\Documents\deoc310\deoc\lib\site-packages\clr_loader\netfx.py", line 47, in _get_callable
    raise RuntimeError(
RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\Users\superMario\AppData\Local\Programs\Python\Python310\python310.dll


```

I would like to know where to set Runtime.PythonDLL, please or howto get pythonnet to work on my environment
regards,

**Comment by kilbasar** [comment]
I had this same issue using `pyinstaller==6.3.0`. The resulting bundled exe would run fine on Windows Server 2019 and 2022, but would fail on 2016 and 2012r2 with these errors:

```
# Windows 2016
RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\Users\ADMINI~1\AppData\Local\Temp\1\_MEI49722\pythonnet\runtime\Python.Runtime.dll

# Windows 2012r2
Unhandled Exception: System.TypeLoadException: Could not load type 'System.ValueTuple`3' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at ClrLoader.DomainData..ctor(AppDomain domain)
   at ClrLoader.ClrLoader.Initialize()
```

Using Python 3.8.8.

For me, the fix was to pin `pythonnet` to version 2.5.2. I tried both `pythonnet` 3.0.2 and 3.0.1, both exhibited this behavior.

**Comment by pohuan** [comment]
Using 3.0.3, also not working

**Comment by pohuan** [comment]
Python.Runtime.Runtime.PythonDLL need to use this.
