### ISSUE TITLE
“ModuleNotFoundError : No module named '[module]'” only on successive runs of Python script

### ISSUE THREAD

**Issue by RoseberryPi** [pythonnet/pythonnet#1274]
### Environment

-   Pythonnet version: Nuget package: pythonnet_netstandard_py36_win v2.5.1
-   Python version: 3.6.8
-   Operating System: Win 10 Version 10.0.17134 Build 17134

### Details

Original StackOverflow Post
https://stackoverflow.com/questions/64704936/python-net-modulenotfounderror-no-module-named-module-only-on-successiv

I'm still not sure if the issue is my lack of understanding on importing modules in Python or if it's something to do with Python.net (though I lean to the latter because in my original python code this was not an issue until I started calling it from C# through Python.net).

Wanted to bring attention to the issue I was having here, in case it is actually a bug.

**Comment by filmor** [comment]
The nuget package you are using is not an official one. Feel free to reopen if the same thing happens on the current `master`, there have been some changes to the import system.
