### ISSUE TITLE
Action delegate - type overload resolution not implemented

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#128]
https://mail.python.org/pipermail/pythondotnet/2015-July/001663.html

**Comment by denfromufa** [comment]
http://stackoverflow.com/questions/30659933/python3-pythonnet-generic-delegates

**Comment by filmor** [comment]
Could you please formulate this issue out? This is btw the exact same issue as #157, the actual generic classes have a slightly different name as there doesn't seem to be a "type overload resolution" implemented in the same manner as it is done for methods. Just use

    Action = getattr(System, 'Action`1')

**Comment by tonyroberts** [comment]
Fixed in #164
