### ISSUE TITLE
Unable to install 64-bit wheel (whl) file on 64-bit Python.

### ISSUE THREAD

**Issue by kasajian** [pythonnet/pythonnet#1281]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.8 64-bit
-   Operating System: Windows 10

### Details

With only 64-bit version of Python installed, attempting to install the 64-bit pythonnet wheel file doesn't work.

32-bit version of python is not installed anywhere on this computer.

Typing `python` produces shows at the top:
`Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32`

Typing `where python` produces:
`C:\Users\kenneth.kasajian.CORP\AppData\Local\Programs\Python\Python38\Scripts\pip.exe`

So that's where it's installed, and confirms it's the 64-bit version.

Typing `pip --version` shows the correct path for the 64-bit version:
`pip 20.2.1 from c:\users\kenneth.kasajian.corp\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)`

Attempting to install the 64-bit version of the wheel file: `pip install pythonnet-2.5.1-cp38-cp38-win_amd64.whl` produces:
`ERROR: pythonnet-2.5.1-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.`

Attempting to install the 32-bit version of the wheel file: `pip install pythonnet-2.5.1-cp38-cp38-win32.whl` produces::
`Processing c:\users\kenneth.kasajian.corp\downloads\pythonnet-2.5.1-cp38-cp38-win32.whl`
`Successfully installed pythonnet-2.5.1`

This shows that the 32-bit wheel file can be installed into 64-bit version Python and the 64-bit version of the wheel file cannot.    **What's the purpose of the 64-bit wheel file, and why is it published?**

Interestingly enough, simply typing `pip install pythonnet` produces output:
`Collecting pythonnet`
`  Using cached pythonnet-2.5.1-cp38-cp38-win32.whl (81 kB)`

Why does 64-bit pip get the 32-bit wheel file?

**Comment by filmor** [comment]
I'm not quite sure what's going on here, but this looks to me like a pip problem, not a problem with this library. If the straight `pip install pythonnet` produces a broken installation, feel free to reopen.

**Comment by kasajian** [comment]
filmor, I have some additional information.
## Summary
- There is no way to use Python.NET with the latest Python 3.9
- There is no way to use Python.NET with the 64-bit version of Python 3.8.
- Only 32-bit version of Python 3.8 is supported.
- Today, if you want to use Python.NET, you have to go back to Python 3.7.

## Background

Python 3.8, 64 bit:
  - You cannot use Python.NET
  - You cannot `pip install pythonnet-2.5.1-cp38-cp38-win_amd64.whl`
  - You cannot `pip install pythonnet`.   **If you do this, it will attempt to install the 32-bit pythonnet-2.5.1-cp38-cp38-win32.whl**.  It'll say it's successful, but `import clr` will not work.   You will get: `ImportError: DLL load failed while importing clr: %1 is not a valid Win32 application.`
  - - And interestingly, you can do `pip install pythonnet-2.5.1-cp38-cp38-win32.whl`, it will install it, but will get the same `import clr` error.

Python 3.8, 32 bit
 - This works: `pip install pythonnet-2.5.1-cp38-cp38-win32.whl`
 - This works: `pip install pythonnet`

Python 3.7, 64 bit:
 - This works: `pip install pythonnet-2.5.1-cp37-cp37m-win_amd64.whl`
 - This works: `pip install pythonnet`

Python 3.7, 32 bit:
 - This works: `pip install pythonnet-2.5.1-cp37-cp37m-win32.whl`
 - This works: `pip install pythonnet`

**Comment by kasajian** [comment]
FYI.
There is no solution to using 64-bit Python 3.8 with Ptyhon.NET because of this problem
