### ISSUE TITLE
Add a more simple "demo" for less experienced users

### ISSUE THREAD

**Issue by eabase** [pythonnet/pythonnet#1283]
Please consider adding a far more simple *example* case where the use scenario does not involve all the complexities of Windows and graphics management . 

A much more helpful example would be something that uses a .NET *delegate* (listener) and how to convert this into something similar/equivalent in Python. Googling for "converting .NET/C# delegates into Python listeners" returns nearly nothing, while StackOverflow has hundreds of related questions, with nearly no practical or correct answers.

<details>
<summary>Full disclosure :wink: </summary>

<sub>PS. Yes, this was a tricky way by me to try to push some knowledge into this issue:  #1282. </sub> 
</details>

**Comment by eabase** [comment]
Your demo's are far too complicated and fooling beginners to think that all the extra classes etc are needed, when they are not. Thus exponentially increasing the possibility for impossible to resolve errors, due to lacking error messages.

For example, the most simple case would be:
```python
import clr
import yourDLL

def myEvent(source, *args) : 
     # handle & print args

# <code to connect to your DLL>

YourDotNETevent += myEvent

# run oo-loop waiting for events
while 1:
     time.sleep(0.1)
```

Absolutely no reason to make things more complicated than this.

**Comment by filmor** [comment]
You are very welcome to create a PR with simpler examples.

**Comment by eabase** [comment]
@filmor 
Well I just spent 2 weeks trying to get this to work and essentially know nothing about it, so really think I am the last person you would like to make PR, but thanks for the encouragement.

**Comment by filmor** [comment]
Fine by me as well. I've opened https://github.com/pythonnet/pythonnet/projects/11 to track this.
