### ISSUE TITLE
 Is there any way to replace scope.Set() scope.Get()?

### ISSUE THREAD

**Issue by maye1115** [pythonnet/pythonnet#1285]
### Details

-    I want to implement interaction with .Net variables in python code.
There may be multiple writes and reads to variables in a python runtime.Like:
```python
# int myint=1
a=NetCore.Get(myint)
b=a+2
NetCore.Set(myint,b)

# myint=3
a=NetCore.Get(myint)
c=a+1
NetCore.Set(myint,c)
# return myint=4
```
Thank you !

**Comment by filmor** [comment]
This is not a support forum. Please use the mailing list or StackOverflow for questions like this.
