### ISSUE TITLE
OpenFileDialog work in Debug mode but not in non-Debug mode

### ISSUE THREAD

**Issue by JS2018SJ** [pythonnet/pythonnet#1286]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.8.3
-   Operating System: Windows 10.0.19042.630

### Details

-   Describe what you were trying to get done.
    Python wrapper:
```python
    def showFileOpen(initdir=USERHOME, filter="txt files (*.txt)|*.txt|All files (*.*)|*.*", 
                 filterIndex=1, restoreDir=True):
        d = OpenFileDialog()
        d.InitialDirectory  = initdir
        d.Filter            = filter
        d.FilterIndex       = filterIndex
        d.RestoreDirectory  = restoreDir
        return (d, d.ShowDialog())
``` 
    In Eclispe PyDev, when run in debug mode, the dialog shows up and returns selected file name, absolutely fine. But when run in non-debug mode, it's blocked on the d.ShowDialog() but the dialog doesn't show up, have to kill it.   

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
```python
   d, r = showFileOpen()
   ...
```  
-   If there was a crash, please include the traceback here.
    no crash

**Comment by victorfreeman** [comment]
I have similar issue, also related with pythonnet and matplotlib with pyqt5 gui
When running app I get the following error in terminal:
QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"
and when trying to use QfileDialog or savfig icon in Matplotlib NavBar the app is crashing
Using console or terminal is fine, but regular mode gives this error and crashes the app.
I solved QFileDialog with option=dontusenativedialog but I have no solution for matlpotlib savfig icon

**Comment by lostmsu** [comment]
I think your problem is about single- vs multithread apartments for COM (which dialog libraries use). See [this SO thread](https://stackoverflow.com/questions/485086/single-threaded-apartments-vs-multi-threaded-apartments)

**Comment by victorfreeman** [comment]
Lostmsu : It happens when I us

> I think your problem is about single- vs multithread apartments for COM (which dialog libraries use). See [this SO thread](https://stackoverflow.com/questions/485086/single-threaded-apartments-vs-multi-threaded-apartments). The error is not directly related to Python.NET

Hi, first all of thanks. However I think it is related to pythonnet because when I disable the import of clr the issue dissapears. I 've looked into the thread you posted but there are no explanation how to fix the issue, only explaining it can happen.

**Comment by victorfreeman** [comment]
I've found this thread which was helpful for my issue:
https://stackoverflow.com/questions/49796024/python-tkinter-filedialog-askfolder-interfering-with-clr
