### ISSUE TITLE
StackOverflowException when creating a new Python class instance from .NET

### ISSUE THREAD

**Issue by gccollect** [pythonnet/pythonnet#1288]
### Environment

-   Pythonnet version: 2.5.1.0
-   Python version: 3.7.3
-   Operating System: Windows 7 64bit

### Details

I am calling a Python module from C#. When trying to create an instance of a Python class I get a System.StackOverflowException. Note that the same call works in other part of the .NET code. In particular if I move this call to be just one level up in the call stack then the call succeeds.

```C#
PythonEngine.Initialize()
dynamic myModule = PythonEngine.ImportModule("MyModule");
...
dynamic myInstance = myModule.MyClass();
```
All other calls to Python such as myModule.mySubModule or calling any other standard module also fail in this case.
I don't get a stacktrace in Visual Studio 2019 in this case only the System.StackOverflowException.
```
Process is terminated due to StackOverflowException.
An unhandled exception of type 'System.StackOverflowException' occurred in mscorlib.dll
```

I tried setting the PythonHome and moving the module to %PYTHONHOME%\Lib\site-packages as suggested in the discussion below but the exception persists.
https://stackoverflow.com/questions/45469726/pythonnet-stackoverflow-exception-in-python-runtime-dll-when-calling-py-import

**Comment by tminka** [comment]
You can try this trick to get a stack trace: https://stackoverflow.com/a/57229466/513835

```csharp
(new Thread(delegate ()
  {
      PythonEngine.ImportModule("MyModule");
  }, 256 * 1024)).Start();
```

**Comment by lostmsu** [comment]
@tminka nifty trick.

**Comment by filmor** [comment]
This issue lacks information to actually debug it (like, e.g., code). Please comment if this is still an issue and add more details.
