### ISSUE TITLE
PythonNET no longer works after installing Visual Studio for Mac which upgraded mono to 6.12.0

### ISSUE THREAD

**Issue by cnaccio** [pythonnet/pythonnet#1294]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.8
-   Operating System: OSX

### Details

Had a Python script that ran on a daily basis which relied on PythonNET, and suddenly today it stopped working after installing Visual Studio for Mac which upgraded Mono from 6.10.0 to 6.12.0. I ultimately solved the issue with a quick an dirty solution by creating a symlink as below. Any advice on a proper solution is much appreciated. Thanks!

```
cd /Library/Frameworks/Mono.framework/Versions/
ln -s 6.12.0 ./6.10.0
```

P.S. The error I was getting when trying to run the app basically said that it couldn't find `libmonosgen-2.0.1.dylib`

**Comment by filmor** [comment]
Reinstalling pythonnet should do the trick. Ideally, it would just link against the lib in `/Library/Framework/Mono.framework/Current`.

**Comment by filmor** [comment]
The version is decided on installation using the `PKG_CONFIG_PATH` environment variable, cf. https://github.com/pythonnet/pythonnet/issues/977#issuecomment-617463697. I'll try to adjust the `setup.py` such that it does this automatically, but that will only help on the current master.
