### ISSUE TITLE
Initialization error using VB

### ISSUE THREAD

**Issue by johnnyontheweb** [pythonnet/pythonnet#1301]
### Environment

-   Pythonnet version: 3.0.0
-   Python version: 3.8
-   Operating System: Windows 10 20H2

### Details

I'm trying to implement a Python shell into a vb.net Winform app. I recompiled Python.Runtime with flags PYTHON3;PYTHON38;WINDOWS, then I used this vb code to initialize the engine:

```vb        
        PythonEngine.PythonHome = "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\"
        PythonEngine.Initialize()
        PythonEngine.BeginAllowThreads()
        Using Py.GIL()
            PythonEngine.Exec(My.Application.Info.DirectoryPath & "\script.py")
        End Using
```
I got an error in `PythonEngine.Initialize()` like this:
`PythonEngine.PythonHome = 'PythonEngine.PythonHome' threw an exception of type 'System.TypeInitializationException'`

External code is present in the stack, hence I can't get any useful information on this. VS stopped at runtime.cs at line:
`internal static readonly int _UCS = PyUnicode_GetMax() <= 0xFFFF ? 2 : 4;`

ALTERNATIVE/OTHER ERROR
If I set `PythonEngine.PythonPath` instead of `PythonEngine.PythonHome` I get:
`System.DllNotFoundException: 'Unable to load the DLL 'python38': Cannot find specified path. (Exception from HRESULT: 0x8007007E).'`

Can you help on that? What is wrong in this code? thanks

**Comment by slide** [comment]
Does python38.dll live in the directory you specified for PythonHome?

**Comment by johnnyontheweb** [comment]
Yes, it is present.
Python version is 3.8.6 at 64bit - .net application is 64bit too.

**Comment by johnnyontheweb** [comment]
This gives the errors described (in CustomMarshaler.cs):
```c#
public static IntPtr Py3UnicodePy2StringtoPtr(string s)
        {
            return Instance.MarshalManagedToNative(s);
        }
```

**Comment by filmor** [comment]
I guess that just happens to be the first one getting called. The error is clearly that it can't find `python38.dll`. You can try adding that to your `PATH`.

**Comment by johnnyontheweb** [comment]
I think there's a more complex problem behing this - why can I set PythonHome property and I must have `python38.dll` in PATH?

**Comment by slide** [comment]
PythonHome doesn't set the path for DLL resolution. DLL resolution is a Windows thing and it looks in the PATH.

**Comment by filmor** [comment]
The reason why you are seeing those errors relatively late is that P/Invoke, which is used to call into arbitrary C functions, lazy-loads the specified DLL. The error is thrown when the first actual Pyhon C-API function is being called. There is no non-hacky way to specify the DLL name or location dynamically, so we set the DLL at compile-time to `python<version>.dll` and the DLL has to then reside in path.

There is work going on to improve this situation (by adjusting the P/Invoke'd DLL name in memory before loading the assembly, see https://github.com/pythonnet/pythonnet/pull/1109/commits/063d0f92476e0b5f6cd8bae65ce71604bf412559), but there are a few more steps that have to be done before we can merge this.

**Comment by johnnyontheweb** [comment]
I understand, thanks. To resolve my issue, I have set PYTHONPATH env. variable, and commented out any PythonHome or PythonPath assignment.

IMHO, a couple of words for this in the project readme.md could save a lot of time to anyone trying such things.
