### ISSUE TITLE
Can't create NDArray or DataFrame from C# array

### ISSUE THREAD

**Issue by zhimakaimen225xa** [pythonnet/pythonnet#1305]
![snap](https://user-images.githubusercontent.com/73700093/101093470-c5fec580-35f5-11eb-8c32-17b4d9997ad4.PNG)

By the way, I created same issue 1 hour ago, which was closed without any explanation, what's wrong?

**Comment by filmor** [comment]
Because it was just a screenshot. We have the issue template for a reason.
