### ISSUE TITLE
Investigate test-failure in TestFinalizer.CollectBasicObject

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#1309]
In #1209, the test `TestFinalizer.CollectBasicObject` fails consistently on Mono (works fine on .NET Core), I have thus disabled it for the time being.

This could be an issue with different behaviour of Mono's GC in newer versions. Since the GC wait is not implemented for Mono, this can't really be run deterministically.

**Comment by lostmsu** [comment]
Fixed in https://github.com/pythonnet/pythonnet/pull/1313
