### ISSUE TITLE
Access violation in tests in Python 3.9

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1327]
Examples: https://github.com/pythonnet/pythonnet/pull/1326/checks?check_run_id=1570565217 , https://ci.appveyor.com/project/pythonnet/pythonnet/builds/36803743

Looks like we screw memory up somewhere.

**Comment by christabella** [comment]
Looks like this should be closed since the fix was merged

**Comment by filmor** [comment]
This is not yet completely solved, see for example https://github.com/pythonnet/pythonnet/runs/1596110428?check_suite_focus=true

**Comment by ksrangarajan** [comment]
The similar issue replicate in Windows OS with Python 3.9 and .NET Framework 4.6.1 with the error that the 
"This thread tries to read or write Virtual address for which it doesnt have access"

This happens randomly and not always on the same script and not all our build machines when we run test case.
Any pointer will be appreaciated

**Comment by magnusjjj** [comment]
Having the same issue. It seems like it happens for me if there is still a running python thread when trying to do .shutdown, with or without EndAllowThreads

**Comment by magnusjjj** [comment]
Narrowed it down a bit further, actually. If a thread is marked as a *daemon* thread, and exists when shutting down, it crashes. If it's *not* a daemon thread, everything works as expected. Not sure what to do with this.

**Comment by magnusjjj** [comment]
No. Disregard my previous statement, didn't test it enough. It still only happens when there is a thread involved at all, but it doesn't require daemon.

**Comment by ksrangarajan** [comment]
In our case, the python39.dll  tries to deallocate by calling Py_Dealloc. The application is console project which uses the test project given in this repo
