### ISSUE TITLE
 clr.AddReference() loads an assembly multiple times

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#133]
```
>>> clr.AddReference("System")
<System.Reflection.RuntimeAssembly object at 0x02913550>
>>> clr.AddReference("System")
<System.Reflection.RuntimeAssembly object at 0x02860F10>
>>> clr.AddReference("System")
<System.Reflection.RuntimeAssembly object at 0x02860E50>
```
http://sourceforge.net/p/pythonnet/bugs/9/

**Comment by filmor** [comment]
What exactly is the problem here? Apparently, on each call you get a new `RuntimeAssembly` object, the assembly itself however is seemingly loaded only once (judging from the log viewer output and memory usage).

**Comment by denfromufa** [comment]
@filmor the issue is that this does not follow cpython and ironpython behavior, modules are supposed to be singletons

**Comment by filmor** [comment]
But the result of `clr.AddReference` is not a module. `clr.AddReference` is not the same as an `import`. IronPython doesn't even return anything for `clr.AddReference` (which is also a viable option IMO).

**Comment by denfromufa** [comment]
agreed, closing!
