### ISSUE TITLE
PythonEngine.Initialize() failed when anonymous type - patch not applied completely

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#134]
http://sourceforge.net/p/pythonnet/bugs/_discuss/thread/a8d46f2e/1c2c/attachment/genericutil.cs.patch

http://sourceforge.net/p/pythonnet/bugs/20/

**Comment by denfromufa** [comment]
related patch here:

http://sourceforge.net/p/pythonnet/bugs/23/

**Comment by filmor** [comment]
As I wrote in another issue: Please formulate this out. It's really tedious to click through 3 links to check whether I have this problem, too.

**Comment by filmor** [comment]
Since there have not been any updates in quite a while, I'll close this issue. Feel free to reopen and provide a information on the current state.
