### ISSUE TITLE
How to define one python?

### ISSUE THREAD

**Issue by huangyhg** [pythonnet/pythonnet#1350]
### Environment

-   Pythonnet version: master branch
-   Python version: 3.8
-   Operating System: win10
-   .NET Runtime:

### Details

I tried to build Python.Runtime.csproj using VS2019 &win10, but got the error as  'You must define one of PYTHON36 to PYTHON39'". How to define one python?
1>  Target CoreCompile:
1>    Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn
1>    D:\pythonnet\src\runtime\runtime.cs(34,8,34,51): error CS1029: #error: 'You must define one of PYTHON36 to PYTHON39'
1>  Done building target "CoreCompile" in project "Python.Runtime.csproj" -- FAILED.
1>
1>  Done building project "Python.Runtime.csproj" -- FAILED.
1>
1>Build FAILED.
1>
1>D:\pythonnet\src\runtime\runtime.cs(34,8,34,51): error CS1029: #error: 'You must define one of PYTHON36 to PYTHON39'
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:00.33
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by filmor** [comment]
This is not a support forum. For the time being, you have to run `python setup.py configure` once to set the project up.

**Comment by huangyhg** [comment]
@filmor thanks a lot.
