### ISSUE TITLE
Why does this parameter send an error？

### ISSUE THREAD

**Issue by chendingqi** [pythonnet/pythonnet#1358]
RunScript({"X":"3","Y":"4"})
![image](https://user-images.githubusercontent.com/37861405/104975316-57ef5000-5a35-11eb-9781-e24066e15d96.png)

**Comment by chendingqi** [comment]
anybody help,tks?

**Comment by lostmsu** [comment]
You must hold GIL to access any Python object with Python.NET

**Comment by chendingqi** [comment]
> 您必须持有GIL才能使用Python.NET访问任何Python对象

tks,is the clr uncontrol from net,so i must using cil,tks,it is allready finish
