### ISSUE TITLE
Importing clr module should prepare Python.Runtime

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1366]
This must be done after https://github.com/pythonnet/pythonnet/pull/1365

When clr module is loading `Python.Runtime.dll` for the first time, it must set `Runtime.PythonDLL` to the name (and preferably - full path to) the dynamic library, that provides Python C APIs (e.g. `PyDictProxy_New`).

This will allow to remove the workaround in `Python Tests` step of GitHub CI.

**Comment by filmor** [comment]
It actually must try hard to set it to `null`.
