### ISSUE TITLE
Internal error in the C# compiler and NoCopy05return. 'NewReference' is non-copyable in Python.Runtime 

### ISSUE THREAD

**Issue by Julian9620** [pythonnet/pythonnet#1372]
### Environment

-   Pythonnet version: newest master
-   Python version: Python 3.5 to Python 3.8
-   Operating System: Windows 10 1809
-   .NET Runtime: 4.7

### Details

 Since the last update i cannot build the solution because of the exceptions "Internal error in the C# compiler and NoCopy05return. 'NewReference' is non-copyable in Python.Runtime ". There 40 errors and they are all thrown by the delegates in the file of "runtime.cs".
 Did I miss some build options?

**Comment by lostmsu** [comment]
Can you share the build steps you are taking? We started requiring build with .NET SDK 5.

**Comment by Julian9620** [comment]
My VS 19 Version is 16.8.4. Than i have to wait until the version 16.9.0

**Comment by filmor** [comment]
If you build it on the command-line (using `dotnet build`), it should work as well.

**Comment by Julian9620** [comment]
Nice it works! :)

**Comment by lostmsu** [comment]
VS 16.9.* was released. Please, update.
