### ISSUE TITLE
No wheels published for 2.5.2 release

### ISSUE THREAD

**Issue by freakboy3742** [pythonnet/pythonnet#1376]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: All
-   Operating System: All

### Details

-   Describe what you were trying to get done.

Install Pythonnet 2.5.2 from PyPI from a wheel, on a machine that doesn't have Visual Studio installed.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

On a machine that doesn't have Visual Studio installed:

    > py -3.8 -m venv venv
    > venv\Scripts\Activate
    > python -m pip install pythonnet

will fail to install pythonnet with the error "option --single-version-externally-managed not recognised.

Alternatively, 

    > python -m pip install --only-binary :all: pythonnet==2.5.2

will report "no matching distribution for pythonnet==2.5.2"

-   If there was a crash, please include the traceback here.

As there's no wheels uploaded to PyPI for 2.5.2, it attempts to download and compile the source release, and fails due to the absence of Visual Studio.

I couldn't find any documentation describing that not publishing a wheel was a conscious decision; I presume it was an oversight during the publication process.

**Comment by filmor** [comment]
It was not an oversight, I just wanted to get some sleep :)

I'll hopefully be able to do this today.

**Comment by filmor** [comment]
I published wheels for 2.7 ... 3.8. The build for 3.9 crashes in CI, so I don't want to claim support for this on the 2.5 branch and will not publish wheels for now.
