### ISSUE TITLE
Neglected Python.NET in NuGet package

### ISSUE THREAD

**Issue by Livius90** [pythonnet/pythonnet#1379]
Hi!

As i see [NuGet package for Python.NET](https://www.nuget.org/packages/pythonnet/2.3.0-py35-dotnet) is really old, last updated was in 2017. Could you update NuGet package to the latest version and can you do more maintaining in your NuGet package to be able to download the newest version in all the time?

**Comment by filmor** [comment]
This is a very bold first contribution. Nuget package creation is already discussed in #165, #778, #1194, you are not the first one to notice this. With version 3.0 (and probably some dev versions inbetween) we will be able to automatically produce a unified Nuget package for all architectures and Python versions. The necessary code in the C# part is already there, you are welcome to contribute the required CI steps.

**Comment by lostmsu** [comment]
BTW, I like the idea of starting previews for 3.0. I think monthly release from `master` would make sense. @filmor what do you think?

**Comment by filmor** [comment]
Fine by me :)

Will you set this up? I don't have access to our nuget org.

**Comment by lostmsu** [comment]
@filmor I need to give you access then. What's you NuGet email (can mail me)?
