### ISSUE TITLE
Can't import namespace contaning a dot

### ISSUE THREAD

**Issue by brilhana** [pythonnet/pythonnet#1408]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.7.8
-   Operating System: Windows 10
-   .NET Runtime: 4.0

### Details

I'm trying to import a DLL whose name is `Foo-1.42, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`.

```python

import clr

dll = clr.AddReference("Foo-1.42.dll")

foo = __import__("Foo-1.42")
```

I know it crashes because Python expects whatever after `.` to be a submodule. Any workaround? I've also tried using `imp` and `importlib` without success.

-  Traceback:
```python
ModuleNotFoundError: No module named 'Foo-1'
```

**Comment by filmor** [comment]
This is not a support forum. I'm also almost 100% certain that .NET doesn't allow dots in namespace names. If you have a really messed up "top-level" namespace, you'll have to use reflection. If the top-level namespace is fine but levels below are messed up, you might be able to get away with `getattr(foo, "1messed-up-name")`.
