### ISSUE TITLE
Please help me with the question about Python torch，thank you

### ISSUE THREAD

**Issue by botao1995** [pythonnet/pythonnet#1415]
### Environment

-   Pythonnet version:netstandard_py38_win(2.5.1.1)
-   Python version:py38
-   Operating System:win10x64
-   .NET Runtime:
- anaconda
- pytorch 1.7.0
- cuda10.2
- cudnn
- gpu

### Details

-   I want to call torch in pythonnet.

    _TODO_

-   Torch is used in my Python project
But there are hints：PythonException: OSError : [WinError 126] 找不到指定的模块。 Error loading "C:\Users\botao\anaconda3\envs\mtscript\Lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
I check caffe2_ detectron_ ops_ gpu.dll The file exists in the torch directory

```python
    import torch
```
```c#
            var pathToVirtualEnv = @"C:\Users\botao\anaconda3\envs\mtscript";

            Environment.SetEnvironmentVariable("PATH", pathToVirtualEnv, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONHOME", $"{ pathToVirtualEnv}", EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONPATH", @$"{pathToVirtualEnv}\DLLs;{pathToVirtualEnv}\Lib;{pathToVirtualEnv}\Lib\site-packages", EnvironmentVariableTarget.Process);
            
            PythonEngine.PythonHome = Environment.GetEnvironmentVariable("PYTHONHOME", EnvironmentVariableTarget.Process);
            PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH", EnvironmentVariableTarget.Process);
            PythonEngine.Initialize();
            using (Py.GIL())
            {
               dynamic func = PythonEngine.ImportModule(@"torch");

            }
```

**Comment by filmor** [comment]
This is not a support forum.
