### ISSUE TITLE
cannot find class in module

### ISSUE THREAD

**Issue by baekhyunee7** [pythonnet/pythonnet#1417]
### Environment

-   Pythonnet version:3.0.0
-   Python version:3.8.3
-   Operating System:windows10
-   .NET Runtime:dotnet core 5.0

### Details

-   get error:
```
Traceback (most recent call last):
  File ".\test.py", line 15, in <module>
    from MyApp  import Class1
ImportError: cannot import name 'Class1' from 'MyApp' (unknown location)
```
-   my config file:
```
{
  "runtimeOptions": {
    "tfm": "netcoreapp5.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "5.0.2"
    }
  }
}
```

-   python code
```python
    from clr_loader import get_coreclr
    from pythonnet import set_runtime
    
    rt = get_coreclr("D:\\test\\BotTest\\test.runtimeconfig.json")
    set_runtime(rt)
    
    import clr
    import sys
    import System
    sys.path.append("D:\\test\\BotTest\\MyApp\\bin\\Debug\\net5.0")
    clr.FindAssembly("MyApp")
    
    clr.AddReference("MyApp")
    from System  import Console
    from MyApp  import Class1
```

-  c# code
```csharp
using System;

namespace MyApp
{
    public class Class1
    {
        public static void f(){
            Console.WriteLine("zzz");
        }
    }
}
```
-  It seems that latest version does not work well for dotnet core

**Comment by filmor** [comment]
What do `clr.FindAssembly` and `clr.AddReference` return? Is the code example complete?

**Comment by baekhyunee7** [comment]
> What do `clr.FindAssembly` and `clr.AddReference` return? Is the code example complete?

I print the result 
```
from pythonnet import set_runtime

rt = get_coreclr("D:\\test\\BotTest\\test.runtimeconfig.json")
set_runtime(rt)

import clr
import sys
import System
sys.path.append("D:\\test\\BotTest\\MyApp\\bin\\Debug\\net5.0")
findRes = clr.FindAssembly("MyApp")
print(findRes)

reference = clr.AddReference("MyApp")
print(reference)

from MyApp import * 
```
and get 
```
D:\test\BotTest\MyApp\bin\Debug\net5.0\MyApp.dll
MyApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

**Comment by bugaosuni59** [comment]
I also meet something similar with you. Pythonnet can work well in dotnet framework but dotnet core.

**Comment by Jong-uk-Kim** [comment]
i got same issue

**Comment by ocelikk** [comment]
Hello everyone, is there any news about this issue ?

**Comment by camer314** [comment]
I just got the same problem. Interestingly I have an identical class library, configuration wise, that works perfectly fine.

See attachment. ClassLibrary1.Class1 works perfectly fine while FittingModuleWrapper.DummyWrapper (which is literally a copy of the other project) gets this issue

![Capture](https://user-images.githubusercontent.com/25336982/128450639-c3240b0a-eb1b-457a-a454-580bebe82a85.PNG)

**Comment by filmor** [comment]
I have checked the initial example, and it works fine for me if publishing is used instead of trying to write the `runtimeconfig.json` yourself. So:

1. Ensure that the project file contains `<GenerateRuntimeConfigFiles>true</GenerateRuntimeConfigFiles>`
2. Publish with `dotnet publish -o out_path`
3. Use `out_path/MyApp.runtimeconfig.json` as the runtime config for `get_coreclr`
4. Just add `out_path` to `sys.path`

While in this particular case, it also works with the `bin` directory content, it would probably get nasty once dependencies are introduced.

One thing that is definitely wrong in your hand-written runtime config is the `tfm`: There is no `netcoreapp5.0`, for .NET 5 this was changed to a straight `net5.0`.

**Comment by camer314** [comment]
Let me try that initial example as well. For sure the steps your indicated are what I did for my 'FittingModuleWrapper' project which is the failing one.

**Comment by DareDevilDenis** [comment]
I'm joining this thread after it's gone to Closed state however I'm having the same issue. 

**Environment**

* Pythonnet version:3.0.0.dev1  (installed using `pip install git+https://github.com/pythonnet/pythonnet`)
* Python version:3.8.10 64 bit
* Operating System:windows10
* .NET Runtime:dotnet core 5.0


- Python code:
```python
import sys
import clr
from clr_loader import get_coreclr
from pythonnet import set_runtime

rt = get_coreclr(r"C:\Test\MyApp\out_path\MyApp.runtimeconfig.json")
set_runtime(rt)

sys.path.append(r"C:\Test\MyApp\out_path")
result = clr.FindAssembly("MyApp")
print('FindAssembly returned:', result)
result = clr.AddReference("MyApp")
print('AddReference returned:', result)

from MyApp import MyClass
```

C# code:
```C#
using System;

namespace MyApp
{
    public class MyClass
    {
        public int PrintToConsole(string message)
        {
            Console.WriteLine("C# .NET Core DLL says: " + message);
            return 123;
        }
    }
}
```



I followed the advice given above by @filmor:

> Ensure that the project file contains <GenerateRuntimeConfigFiles>true</GenerateRuntimeConfigFiles>
> Publish with dotnet publish -o out_path
> Use out_path/MyApp.runtimeconfig.json as the runtime config for get_coreclr
> Just add out_path to sys.path

But I still get:

```
FindAssembly returned: C:\Test\MyApp\out_path\MyApp.dll
AddReference returned: MyApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Traceback (most recent call last):
  File "my_python.py", line 16, in <module>
    from MyApp import MyClass
ImportError: cannot import name 'MyClass' from 'MyApp' (unknown location)
```

I've attached the code: [Test.zip](https://github.com/pythonnet/pythonnet/files/7137991/Test.zip)

**Comment by filmor** [comment]
You have to set the runtime *before* importing `clr`. I'll adjust the `set_runtime` function s.t. it bails out if `clr` has already been loaded.

**Comment by DareDevilDenis** [comment]
Hi @filmor,

I moved setting the runtime to before importing clr as you advised but still see the same `ImportError: cannot import name 'MyClass' from 'MyApp' (unknown location)`

Modified Python:

```python
from clr_loader import get_coreclr
from pythonnet import set_runtime

rt = get_coreclr(r"C:\Test\MyApp\out_path\MyApp.runtimeconfig.json")
set_runtime(rt)

import clr
import sys

sys.path.append(r"C:\Test\MyApp\out_path")
result = clr.FindAssembly("MyApp")
print('FindAssembly returned:', result)
result = clr.AddReference("MyApp")
print('AddReference returned:', result)

from MyApp import MyClass
```

Here's the complete code: [Test.zip](https://github.com/pythonnet/pythonnet/files/7142965/Test.zip)

**Comment by filmor** [comment]
Hmm... The issue is that Python just "imports" the `MyApp` directory as a "namespace package", not sure why. If you rename it or run your program from a different path, it works just fine.

**Comment by DareDevilDenis** [comment]
Thanks for the quick respond @filmor. That fixed it 👍. Thanks a lot for the help :)

**Comment by ramymagdy-rm** [comment]
Hi everyone, i was looking into this and found this post hope it helps
https://stackoverflow.com/a/63728744/12821529

**Comment by snoop2head** [comment]
@ramymagdy-rm 's suggestion resolved my issue at 3AM
