### ISSUE TITLE
Operator overloading doesn't appear to work.

### ISSUE THREAD

**Issue by ohtrobinson** [pythonnet/pythonnet#1418]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.9
-   Operating System: Windows 10 (64 bit)
-   .NET Runtime: .NET Framework 4.7.2

### Details

I'm trying to get operator overloading to work but I get the error `TypeError: unsupported operand type(s) for +`.

By the looks of things, the C# code & Python code appear to be correct, so I don't think this is an issue on my end.

#### C#
![image](https://user-images.githubusercontent.com/52220544/111515727-0a4c4680-874b-11eb-8bdd-98f766f8018e.png)

#### Python
![image](https://user-images.githubusercontent.com/52220544/111515752-120beb00-874b-11eb-80c2-8d58a1e245f7.png)

#### Traceback
![image](https://user-images.githubusercontent.com/52220544/111515790-1e904380-874b-11eb-9b6c-e09f1d8c88a2.png)

**Comment by filmor** [comment]
Operator overloading is only supported on master, not in the 2.5 branch.

**Comment by ohtrobinson** [comment]
Ah alright, is there a way to get that through PIP?

**Comment by lostmsu** [comment]
@ohtrobinson https://github.com/pythonnet/pythonnet/wiki/Installation#github-installation-from-master-branch
