### ISSUE TITLE
Task.Dispose() breaks infinite Event Loop

### ISSUE THREAD

**Issue by Maradonna90** [pythonnet/pythonnet#1419]
### Environment

-   Pythonnet version: unknown
-   Python version: Python 3.8
-   Operating System: Windows
-   .NET Runtime: unknown

### Details

-   We are trying to have an infinite event loop of tasks that listen for button presses

I was send by one of the beeware maintainers. Original issue is here: https://github.com/beeware/toga/issues/1166

This comment summarizes the core of the issue: https://github.com/beeware/toga/issues/1166#issuecomment-766083695 :
> Ok so I narrowed the issue down even more. It is very clear that the `Dispose` function frees the memory but also breaks the loop. 
>
>https://github.com/saroad2/toga/blob/77c8d8d962b75e3536488c9d6316f99ff634522d/src/winforms/toga_winforms/libs/proactor.py#L117-L119
>
>```
>if self.task:
>    self.task.Dispose()
>    del self.task
>```
>If we remove the Dispose line we have the memory leak back. This is most likely caused by the Timer that references the Task object it was attached to. 
>```
>    def enqueue_tick(self):
>        # Queue a call to tick in 5ms.
>        self.task = Action[Task](self.tick)
>        Task.Delay(5).ContinueWith(self.task)
>```
>
>Thus the GC doesn't collect it. Probably thats also why the `del self.task` statement isn't doing anything actually.
>
>I don't really have an idea how to solve this issue, maybe the whole construction of the proactor has to be reevaluated.

**Comment by lostmsu** [comment]
This issue appears to have nothing to do with pythonnet.
