### ISSUE TITLE
Python DLL missing dependencies on third party systems

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [pythonnet/pythonnet#1424]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.8
-   Operating System: Windows 10
-   .NET Runtime: 4.0

### Details

-   I tried to execute a python code embeded .NET binary on another system without python installed.

The following code was used:

```python
namespace PythonNet
{
    class Program
    {
        static void Main(string[] args)
        {
            using (Python.Runtime.Py.GIL())
            {
                dynamic np = Python.Runtime.Py.Import("os");
                
                Console.WriteLine(np.getcwd());

            }
        }
    }
}
```

The binary runs successfully on the system where it was build. However,  on other Windows systems, the Python DLL needs some python libraries, which I never imported.

![image](https://user-images.githubusercontent.com/27858067/112185875-e97b6980-8c00-11eb-944f-156008fd64ef.png)

By copying all libraries to the current working directory it works on the other systems. But that is not a good workaround. This could most likely also be a general python DLL Import problem, as I had the same with other tools. Does someone have an idea on how to:

1. Include the needed libraries in the .NET binary, so that it runs on systems without python installed?
2. Avoid the loading of those libraries, as they should not be needed at all?

I'll appreciate any ideas on how to solve this! :bowtie:

Greetings

**Comment by filmor** [comment]
This is usually because either `PYTHONHOME` or `PYTHONPATH` is set. Check some of the existing issues on this topic :)

The issue is actually not specific to Python.NET but happens in other embedding scenarios as well, with the same error message.

**Comment by S3cur3Th1sSh1t** [comment]
True, the error had this reason. But now I get another one:

![image](https://user-images.githubusercontent.com/27858067/112197558-82fc4880-8c0c-11eb-83f5-f20e40627b69.png)

I embeded the `Python.Runtime.dll` with Fody, so this should not be missing right?
