### ISSUE TITLE
Mono crashes when calling .NET dll from python3.6 linux docker container

### ISSUE THREAD

**Issue by boris-mtdv** [pythonnet/pythonnet#1428]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.6
-   Operating System: Debian 10.9
-   .NET Runtime: 4.8

### Details

-   Describe what you were trying to get done.

I have a docker container with a debian python3.6 base image, on which I'm trying to install mono in order to call a utility .dll ( a.NET Framework assembly that was compiled using visual studio ("release" option)) from my python code. I've installed mono because my python code needs to use pythonnet. 

-   What commands did you run to trigger this issue? If you can provide a
   
clr.AddReference(PATH_TO_DLL)
import Copy
copier = Copy()
copier .CopySomething(parameters)

 ## Imported at run time cause the .dll does not exist at the time of the build.
 from Utility import Copy
 copy = Copy()

My Dockerfile:

FROM python:3.6

    WORKDIR /opt

    # create a virtual environment and add it to PATH so that it is 
    applied for all future RUN and CMD calls
    ENV VIRTUAL_ENV=/opt/venv
    RUN python3 -m venv $VIRTUAL_ENV
    ENV PATH="$VIRTUAL_ENV/bin:$PATH"

    # install msodbcsql17
    RUN apt-get update \
        && apt-get install -y curl apt-transport-https gnupg2 \
        && curl https://packages.microsoft.com/keys/microsoft.asc | 
    apt-key add - \
        && curl 
       https://packages.microsoft.com/config/debian/9/prod.list > 
    /etc/apt/sources.list.d/mssql-release.list \
        && apt-get update \
        && ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools

    # Install Mono for pythonnet.
    RUN apt-get update \
    && apt-get install --yes \
        dirmngr \
        clang \
        gnupg \
        ca-certificates \
        # Dependency for pyodbc.
        unixodbc-dev \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
    && echo "deb http://download.mono-project.com/repo/debian 
    stretch/snapshots/5.20 main" | tee /etc/apt/sources.list.d/mono- 
       official-stable.list \
        && apt-get update \
        && apt-get install --yes \
        mono-devel=5.20\* \
        && rm -rf /var/lib/apt/lists/*

    RUN python3 -m venv $VIRTUAL_ENV \
    # From here on, use virtual env's python.
    && venv/bin/pip install --upgrade pip \
    && venv/bin/pip install --no-cache-dir --upgrade pip setuptools wheel \

    && venv/bin/pip install --no-cache-dir -r requirements.txt \
    # Dependency for pythonnet.
    && venv/bin/pip install --no-cache-dir pycparser \
    && venv/bin/pip install -U  --no-cache-dir "pythonnet==2.5.1" \
    "pythonnet==2.5.1"

-   If there was a crash, please include the traceback here.
 
| * Assertion at mono-threads.c:487, condition `result' not met
app_1            |
app_1            | /proc/self/maps:
app_1            | 4015f000-4016f000 rwxp 00000000 00:00 0
app_1            | 41523000-41563000 rwxp 00000000 00:00 0
app_1            | 41563000-415a3000 rwxp 00000000 00:00 0
app_1            | 5624b4719000-5624b471a000 r--p 00000000 08:01 3542387                    /usr/local/bin/python3.6
app_1            | 5624b471a000-5624b471b000 r-xp 00001000 08:01 3542387                    /usr/local/bin/python3.6
app_1            | 5624b471b000-5624b471c000 r--p 00002000 08:01 3542387                    /usr/local/bin/python3.6
app_1            | 5624b471c000-5624b471d000 r--p 00002000 08:01 3542387                    /usr/local/bin/python3.6
app_1            | 5624b471d000-5624b471e000 rw-p 00003000 08:01 3542387                    /usr/local/bin/python3.6
app_1            | 5624b5a1a000-5624b7bf7000 rw-p 00000000 00:00 0                          [heap]
app_1            | 5624b7bf7000-5624b7e7b000 rw-p 00000000 00:00 0                          [heap]
app_1            | 7f596315d000-7f59631aa000 r--p 00000000 08:01 803343                     /usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed75
6/Mono.Security.dll
app_1            | 7f59631aa000-7f59633b0000 r--p 00000000 08:01 917588                     /usr/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/
System.Data.dll
app_1            | 7f59633b0000-7f5963430000 rw-p 00000000 00:00 0
app_1            | 7f5963430000-7f596343b000 r--p 00000000 08:01 3147620                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
app_1            | 7f596343b000-7f596346d000 r-xp 0000b000 08:01 3147620                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
app_1            | 7f596346d000-7f5963479000 r--p 0003d000 08:01 3147620                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
app_1            | 7f5963479000-7f596347b000 r--p 00048000 08:01 3147620                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
app_1            | 7f596347b000-7f596347d000 rw-p 0004a000 08:01 3147620                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
app_1            | 7f596347d000-7f59634a1000 r--p 00000000 08:01 3147628                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
app_1            | 7f59634a1000-7f5963502000 r-xp 00024000 08:01 3147628                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
app_1            | 7f5963502000-7f596354b000 r--p 00085000 08:01 3147628                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
app_1            | 7f596354b000-7f596354c000 ---p 000ce000 08:01 3147628                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
app_1            | 7f596354c000-7f596355a000 r--p 000ce000 08:01 3147628                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
app_1            | 7f596355a000-7f596355d000 rw-p 000dc000 08:01 3147628                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
app_1            | 7f596355d000-7f5963574000 r-xp 00000000 08:01 3544577                    /usr/lib/x86_64-linux-gnu/libodbcinst.so.2.0.0
app_1            |
app_1            | =================================================================
app_1            |    Native Crash Reporting
app_1            | =================================================================
app_1            | Got a SIGABRT while executing native code. This usually indicates
app_1            | a fatal error in the mono runtime or one of the native libraries
app_1            | used by your application.
app_1            | =================================================================
app_1            |
app_1            | =================================================================
app_1            |    Basic Fault Adddress Reporting
app_1            | =================================================================
app_1            | Memory around native instruction pointer (0x7f598c00c7bb):0x7f598c00c7ab  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L....
..........
app_1            | 0x7f598c00c7bb  48 8b 8c 24 08 01 00 00 64 48 33 0c 25 28 00 00  H..$....dH3.%(..
app_1            | 0x7f598c00c7cb  00 44 89 c0 75 1d 48 81 c4 10 01 00 00 5b c3 66  .D..u.H......[.f
app_1            | 0x7f598c00c7db  0f 1f 44 00 00 48 8b 15 89 36 18 00 f7 d8 64 89  ..D..H...6....d.
app_1            |
app_1            | =================================================================
app_1            |    Native stacktrace:
app_1            | =================================================================
app_1            |    0x7f597a8d6c08 - /usr/lib/libmonosgen-2.0.so.1 : (null)
app_1            |    0x7f597a869091 - /usr/lib/libmonosgen-2.0.so.1 : (null)
app_1            |    0x7f598c335730 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
app_1            |    0x7f598c00c7bb - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
app_1            |    0x7f598bff7535 - /lib/x86_64-linux-gnu/libc.so.6 : abort
app_1            |    0x7f597aaaefd7 - /usr/lib/libmonosgen-2.0.so.1 : (null)
app_1            |    0x7f597aa94e81 - /usr/lib/libmonosgen-2.0.so.1 : (null)
app_1            |    0x7f597aaaeebb - /usr/lib/libmonosgen-2.0.so.1 : (null)
app_1            |    0x7f597aaaf47d - /usr/lib/libmonosgen-2.0.so.1 : monoeg_assertion_message
app_1            |    0x7f597aaa493f - /usr/lib/libmonosgen-2.0.so.1 : mono_thread_info_attach
app_1            |    0x7f597a9eaa15 - /usr/lib/libmonosgen-2.0.so.1 : (null)
app_1            |    0x7f598c32afa3 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
app_1            |    0x7f598c0ce4cf - /lib/x86_64-linux-gnu/libc.so.6 : clone
app_1            |
app_1            | =================================================================
app_1            |    Telemetry Dumper:
app_1            | =================================================================
app_1            | Pkilling 0x7f598bfd0740 from 0x7f597a697700
app_1            | Entering thread summarizer pause from 0x7f597a697700
app_1            | Finished thread summarizer pause from 0x7f597a697700.
app_1            | domain required for stack walk
app_1            | Waiting for dumping threads to resume
app_1            |
app_1            | Debug info from gdb:
app_1            |
app_1            |
app_1            | =================================================================
app_1            |    External Debugger Dump:
app_1            | =================================================================
app_1            | mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb

**Comment by boris-mtdv** [comment]
@lostmsu just edited the question to include the full stack trace.

**Comment by lostmsu** [comment]
@boris-mtdv can you try installing lldb? Sounds like it might give some extra information.

**Comment by boris-mtdv** [comment]
@lostmsu my apologies, it doesn't happen exactly at that line but after I import the library loaded from the dll, instantiate an object from it and call one of its methods. I've edited the question once more to include those lines of code.

**Comment by boris-mtdv** [comment]
@lostmu I tried apt get install lldb inside the docker container but it said the package wasn't found. Do you know if there's a specific version I have to go for?

**Comment by lostmsu** [comment]
@boris-mtdv according to https://packages.debian.org/buster/lldb , Debian 9 and 10 both have `lldb` package in their repository.

**Comment by filmor** [comment]
We don't support these old versions of Python and Python.NET anymore. Please check whether this is still an issue with the newest release candidate and comment if that's the case.
