### ISSUE TITLE
Trying to load custom C# assemblies in Python

### ISSUE THREAD

**Issue by csarinyamas** [pythonnet/pythonnet#1436]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.7
-   Operating System: Windows 10 Enterprise (latest updates installed)
-   .NET Runtime: 4.8.03752

### Details
I'm trying to load an assembly out of our assembly cache and while the initial assembly load seems to work (clr.AddReference doesn't throw an exception and returns an object), attempts to resolve external references fails. 

As background info - we establish our own assembly cache to avoid polluting the GAC with all of our libraries. We inject a class into all of our assemblies the AppDomain.AssemblyResolve event so that if the assembly resolution fails to find the reference locally and then in the GAC, we point it to our AC building the path based on env vars we have setup in our dev env and the expected location of our dlls. This has always worked for us when loading our assemblies through other scripting languages (like MaxScript or Powershell) as long as the calling script was run in our dev env (except in instances where the calling application handles the AssemblyResolve event and not forwarding it). 

So in my scenario, I'm trying to load one of our custom assemblies using Python 3.7 hosted in Houdini using pythonnet 2.5.2. The code is pretty straight forward:
```
import sys
import os
import clr

def main():
    cblib = clr.AddReference(os.path.join(assemblyPath, "ContentBrowserMetadataObjects"))

    if cblib == None:
        print("failed to load ContentBrowserMetadataObjects.dll from " + assemblyPath)
    else:
        print("Successfully loaded ContentBrowserMetadataObjects.dll from " + assemblyPath)
    print(cblib.ImageRuntimeVersion)
    for t in cblib.ExportedTypes:
        print(t)

```
I get the print from the else statement, the ImageRuntimeVersion prints as expected but then I run into an exception when trying to access the ExportedTypes.

Normally, I wouldn't bother with looping through  the ExportedTypes collection, but when I tried importing a class:

`
from MetadataObjects import TextureSourceMetadataFactory
`
I would receive the following error:

>Traceback (most recent call last):
> File "ForzaTextureExporter", line 10, in
> File "E:\Tools\Scripts\Houdini\python\hdi\TextureExporter.py", line 38, in main
> from MetaDataObjects import TextureSourceMetadataFactory
> ModuleNotFoundError: No module named 'MetaDataObjects'

I used ILSpy to open the assembly and confirmed that the MetadataObjects namespace existed and contained the TextureSourceMetadataFactory class and that I spelled them correctly.

So just to see what WAS available in this assembly, I decided to loop through and print all the ExportedTypes. That's when I ran into this error:

> for t in cblib.ExportedTypes:
> System.IO.FileNotFoundException: Could not load file or assembly 'Autofac, Version=4.0.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified.
> at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
> at System.Reflection.RuntimeAssembly.GetExportedTypes()

At this point, I try to copy all of the assemblies in our AC to the same directory as the python3.7.exe, the Houdini exe and the folder where the calling Python script lives (in turn, not at the same time) and re-run the script. I still get the same error.

What jumps out to me now is the assembly name that the resolver is looking for: 'Autofac, Version=4.0.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da'. We have an Autofac assembly in our AC, but its named 'Autofac.dll', not 'Autofac, Version=4.0.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da.dll'. So just curious as to what the assembly resolver is looking for, I used ProcMon to capture all events coming from Houdini and filtered down to events containing 'Autofac' and I see a bunch of NAME NOT FOUND events where the path looks something like this:

> E:\P4\FMBase_Main\tools\scripts\Houdini\python\Autofac, Version=4.0.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da.dll

The other entries only vary by the path being used to locate the assembly. Apparently, the resolver is looking in a whole host of places, none of which is our AC, but even if it was, its looking for that long name instead of 'Autofac.dll'. On a hunch I go to the Autofac.dll file that I copied to the Python script location and change its name from 'Autofac.dll' to 'Autofac, Version=4.0.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da.dll' and re-run the script. That works - well, it works in that the resolver gets past the Autofac reference and then borks on the next reference and do so in the same way. It looks in a bunch of places that isn't our AC and its looking for what appears to be the header info as a file name instead of the assembly file name.

So my questions are:
* does anyone know how pythonnet handles external assembly resolution? It seems like captures and tries to handle the AssemblyResolve event. Is there some flag or something I can set to forward that event or bypass Pythonnet's handling?
* does anyone know why the resolver would be looking for that long-form name instead of the expected assembly name? I checked in IL spy and the references listed are the expected short form:
![image](https://user-images.githubusercontent.com/42733537/113751855-365f4580-96c1-11eb-9a3f-24154281f3b7.png)

Sorry for the text-wall: I just didn't know how else to properly explain everything I was seeing and trying without typing all of this up!

**Comment by lostmsu** [comment]
Python.NET does not handle external assembly resolution. The regular .NET mechanism is used. On Windows you can debug it using [Fusion Log Viewer](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer).

On Windows this generally means that directory with DLLs must be in `PATH` or DLLs must be in GAC.

**Comment by csarinyamas** [comment]
Hi lostmsu - thanks for that info. That's curious. If Python.NET doens't handle external assembly reference, then our own solution handling the AssemblyResolve event should have done the trick. It has always done so in other situations as noted in my post above.

**Comment by lostmsu** [comment]
@csarinyamas if you have an `AssemblyResolve`-based solution, it must (obviously) be initialized before you try to add reference to any assembly, that requires it. Python.NET loads all assembly types at once just like you did it.

You can also debug it from Visual Studio.

**Comment by csarinyamas** [comment]
> Python.NET does not handle external assembly resolution. The regular .NET mechanism is used. On Windows you can debug it using [Fusion Log Viewer](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer).
> 
> On Windows this generally means that directory with DLLs must be in `PATH` or DLLs must be in GAC.

@lostmsu - this code appears to be handling the assembly resolve event:
https://github.com/pythonnet/pythonnet/blob/bd264cf003ca1f9727d7eaeb90ddf913e81fdad2/src/runtime/assemblymanager.cs

from that .cs file:
```
        /// <summary>
        /// Event handler for assembly resolve events. This is needed because
        /// we augment the assembly search path with the PYTHONPATH when we
        /// load an assembly from Python. Because of that, we need to listen
        /// for failed loads, because they might be dependencies of something
        /// we loaded from Python which also needs to be found on PYTHONPATH.
        /// </summary>
        private static Assembly ResolveHandler(object ob, ResolveEventArgs args)
        {
            string name = args.Name.ToLower();
            foreach (Assembly a in assemblies)
            {
                string full = a.FullName.ToLower();
                if (full.StartsWith(name))
                {
                    return a;
                }
            }
            return LoadAssemblyPath(args.Name);
        }

        /// <summary>
        /// Given an assembly name, try to find this assembly file using the
        /// PYTHONPATH. If not found, return null to indicate implicit load
        /// using standard load semantics (app base directory then GAC, etc.)
        /// </summary>
        public static string FindAssembly(string name)
        {
            char sep = Path.DirectorySeparatorChar;

            foreach (string head in pypath)
            {
                string path;
                if (head == null || head.Length == 0)
                {
                    path = name;
                }
                else
                {
                    path = head + sep + name;
                }

                string temp = path + ".dll";
                if (File.Exists(temp))
                {
                    return temp;
                }

                temp = path + ".exe";
                if (File.Exists(temp))
                {
                    return temp;
                }
            }
            return null;
        }

```
it also looks like this is where the long assembly name is used instead of the short one. I'm curious about that choice - is it common practice to name assemblies with version number etc in the name? I would think the short name would be much more common. Is there any other assembly resolution handling besides this?

Thanks!

**Comment by lostmsu** [comment]
@csarinyamas this function is only called when the regular mechanism to load assemblies fails to find a match. And if this function does not return a match of its own (which in your case it does not) the next one will be called, if you register it.
