### ISSUE TITLE
call python from Hangfire background job.

### ISSUE THREAD

**Issue by bingo619** [pythonnet/pythonnet#1438]
### Environment

-   Pythonnet version: latest
-   Python version: 3.7
-   Operating System: Mac
-   .NET Runtime: .net 5

### Details

-   Describe what you were trying to get done.

    Try to call python code from Hangfire background jobs, runs fine when there is only one job, always crashes when two jobs run simultaneously. Tried adding 

```python
                   if (!PythonEngine.IsInitialized)
                {
                    PythonEngine.Initialize();
                    PythonEngine.BeginAllowThreads();
                }

```

Didn't work. Thanks in advance.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
   
```

-   If there was a crash, please include the traceback here.

```python
    Fatal Python error: PyMUTEX_LOCK(gil->mutex) failed
```

**Comment by lostmsu** [comment]
1. Members of `PythonEngine` are not currently thread-safe. You need to add a lock around that `if`.
2. Once you call `BeginAllowThreads` any call into Python must be wrapped into `using var _ = Py.GIL()`

**Comment by bingo619** [comment]
@lostmsu  Thanks a lot, it is now working.
