### ISSUE TITLE
Cannot train model with Pytorch DataLoader (when num_workers>0) from C# 

### ISSUE THREAD

**Issue by murtazabasu** [pythonnet/pythonnet#1445]
### Environment

-   Pythonnet version: Runtim,e Version v4.0.30319
-   Python version: conda (3.7)
-   Operating System: Windows 10
-   .NET Runtime: 4.6.1

### Details

-   So I am trying to train a model here with Pytorch. I have a training file in Python where I change a parameter and the training takes place with RandomForest, XGBoost (ML Models) etc. Elsewise it uses neural network to train the model. I use Pytorch for training the model. 

What I notice is that when I train the with ML (from C#) the training takes place without any problem. But once I switch to NN things go a bit crazy. What exactly happens here is that, the code runs into a loop i.e. prints multiple times the same things but never actually trains the model. (There is no bug in the code write in Python it runs perfectly in python) 

The Python main.py

```
def main():
    .
    .
    .
    if args.nn_training:
        log_files(text_path, args, net=model_)
        
        net_, train_losses, valid_losses, data_loader = nn_executor(
            df, features, args, model_, TARGET_COLUMN
        )
        torch.save(
            net_.state_dict(), 
            model_path + 'model' + str(folder_number) + '.pt'
        )
        plot_images(train_losses, valid_losses, image_path, mode="loss")

    else:
        print("Training with Classic ML Models")

        log_files(text_path, args)
        model, true, preds = train_model(df, args.ml_model, features, args, TARGET_COLUMN)
        with open(model_path + 'model.pickle', 'wb') as f:
            pickle.dump(model, f, -1)
        plot_images(true, preds, image_path, mode="accuracy")

    print("\n------------------------------Training Completed------------------------------")

    if args.testing and args.nn_training:
       try:   
            tester(df, args, features, model_, model_path, image_path, TARGET_COLUMN)
        except IndexError:
            print("Select the right index")

if __name__ == '__main__':
    pass
```
The C# code :

```
static void Main(string[] args)
        {
            IPythonConnector python = new PythonConnector();
            python.EstablishConnection();
            try
            {
                dynamic mainFile;
                using (Py.GIL())
                {
                    mainFile = Py.Import("Main");
                }
                dynamic running = mainFile.main();
                Console.WriteLine("Exeution Finished");
               
            }
            finally
            {
                PythonEngine.Shutdown();
            }
            Console.ReadKey();
        }
```

Terminal Output1: (when training with NN)
![image](https://user-images.githubusercontent.com/54032524/115369187-26b72500-a1c8-11eb-82f8-aef90a3c8595.png)

![image](https://user-images.githubusercontent.com/54032524/115370544-734f3000-a1c9-11eb-9cab-9ee3fc47c231.png)

As you notice, the training is stuck at epoch 1 i.e. it never actually proceeds and this keeps repeating over and over again

Even after I close the stop the debug session, the terminal is stuck and keeps running until I manually close the terminal. 

Since I am using a Pytorch DataLoader. The DataLoader class has a num_workers that uses multiprocessing. If I set this argument to 0. The training works perfectly. However, setting a value > 0 results in the above problem.

```
train_dataset = RegressionClass(
        torch.from_numpy(X_train).float(),
        torch.from_numpy(Y_train).float()
    )
    valid_dataset = RegressionClass(
        torch.from_numpy(X_valid).float(),
        torch.from_numpy(Y_valid).float()
    )

    train_loader = DataLoader(
        dataset=train_dataset, 
        batch_size=args.train_batch_size,
        #num_workers=args.num_workers,  (default -> 0)
        shuffle=True
    )
    valid_loader = DataLoader(
        dataset=valid_dataset, 
        batch_size=args.valid_batch_size, 
        #num_workers=args.num_workers, (default -> 0)
        shuffle=True
    )
    criterion = RMSELoss()
```
When I don't use multiprocessing, I no longer see the above problem and the model trains without any issues as seen below.

![image](https://user-images.githubusercontent.com/54032524/115371843-a0501280-a1ca-11eb-9e96-61041d4c7131.png)

**Comment by filmor** [comment]
This is not a support forum.

Using Python.NET with `multiprocessing` on Windows is not going to work easily, as Windows doesn't have fork and starts new processes. These new processes are "derived" from the currently running one, so instead of running `python multiprocessing.spawn` or whatever it will call `your_exe.exe multiprocessing.spawn`. Since you don't handle this case in your executable, this leads to a sort-of fork-bomb (without fork :)), as your program will repeatedly start itself over and over.

More to the point: This is not an issue specific to Python.NET but will happen in any embedding scenario. You could handle the command-line arguments as Python would, then it would work, or use the embedding of .NET into Python instead.
