### ISSUE TITLE
System.AccessViolationException occurs when tried to run a python file multiple times.

### ISSUE THREAD

**Issue by murtazabasu** [pythonnet/pythonnet#1449]
### Environment

Environment
Pythonnet version: Runtime Version v4.0.30319
Python version: conda (3.7)
Operating System: Windows 10
.NET Runtime: 4.6.1

### Details

Hello, I need to run a python file multiple times . I have a server - client interface where multiple client should be able to execute run a python file. one after the other.

In the below code:

I try to execute a python file two times. I notice that the first time it runs perfectly but for the second time it throws an ```AccessViolationException``` saying it Attempted to read or write protected memory. This is often an indication that other memory is corrupt.  
 ```
class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i <= 2; i++)
            {
                connectPython();
                i += 1;
            }
            Console.ReadKey();
        }
        static void connectPython()
        {
            IPythonConnector python = new PythonConnector();
            python.EstablishConnection();
            try
            {
                dynamic mainFile;
                using (Py.GIL())
                {
                    mainFile = Py.Import("main");
                }
                dynamic running = mainFile.main();
            }
            finally
            {
                PythonEngine.Shutdown();
            }
        }
```

![image](https://user-images.githubusercontent.com/54032524/115682767-1339c480-a356-11eb-83f8-ef871bff5911.png)

**Comment by lostmsu** [comment]
This behavior is well-known if the file you're trying to run references certain libraries like `numpy`, that do not support Python engine restart. You might want to try not calling `PythonEngine.Shutdown()` at all.

**Comment by magnusjjj** [comment]
You were a little bit quick to close this one :P.
I don't have access to the code now. But I made a pure python one.

All you need to do is start a thread that has no exit, say, a while True: inside it, with, oh, a print statement for good measure.

Then restart the script. I'd say roughly half or a third of the time it will throw an access violation.
This is apparantly a limitation of the python runtime *itself*.
