### ISSUE TITLE
Console.ForegroundColor has no effect in a Python script

### ISSUE THREAD

**Issue by alexhiggins732** [pythonnet/pythonnet#1450]
### Environment

-   Pythonnet version: 3.0.0-preview2021-04-03
-   Python version: 3.7 (x64)
-   Operating System: Windows 10
-   .NET Runtime: 4.8 (x64)

### Details

-   Describe what you were trying to get done.

    Attempting to use the `Console.ForegroundColor` and `Console.ResetColor` results in no change while executing a python script.

-   What commands did you run to trigger this issue?

``` python
import clr
import System
from System import IO
from System import String
from System import DateTime
from System import Console
from System import ConsoleColor
now = DateTime.Now;
Console.ForegroundColor = ConsoleColor.Yellow
Console.WriteLine(String.Format("[{0}] Training started", now))
Console.ResetColor()
```

Executing the above python produces:

![image](https://user-images.githubusercontent.com/2246388/115944971-2f894e80-a487-11eb-8d2c-b1d6fcc52f2d.png)

The expected result is:
![image](https://user-images.githubusercontent.com/2246388/115944893-b38f0680-a486-11eb-9e56-c1268e69be75.png)

**Comment by alexhiggins732** [comment]
**_Update:_** Running the python script from the command line does work.

The above screen shots are produced while debugging from within Visual Studio. 

As such, I am willing to close this issue and reopen a ticket specific to Visual Studio (wherever that might be?) if that is deemed to the correct thing to do by the project maintainers

![image](https://user-images.githubusercontent.com/2246388/115945115-159c3b80-a488-11eb-9070-bbfd78d9febf.png)

**Comment by lostmsu** [comment]
Yeah, it might be that Visual Studio console is different in some way. Please, close unless you find the issue to be caused by Python.NET specifically.

**Comment by alexhiggins732** [comment]
Closing issue. This appears to be specify to the Visual Studio debugger and not Python .NET.
