### ISSUE TITLE
[Linux] Async code in Py.GIL() block throws "Fatal Python error: auto-releasing thread-state, but no thread-state for this thread"

### ISSUE THREAD

**Issue by Worble** [pythonnet/pythonnet#1454]
### Environment

-   Pythonnet version: 3.0.0-preview2021-05-03
-   Python version: 3.9
-   Operating System: Windows/Linux
-   .NET Runtime: 5

### Details

I recently tracked down an issue where when reaching the end of a Py.GIL() block, Windows worked perfectly, however Linux would crash every time with

```
Fatal Python error: auto-releasing thread-state, but no thread-state for this
thread
Python runtime state: initialized

Thread 0x00007f028e09c640 (most recent call first):
<no Python frame>

Thread 0x00007f0309caf740 (most recent call first):
<no Python frame>
```

Eventually it turns out it was due to the fact I was performing an async call in the middle of the Py.GIL() block, like so:

```c#
using Py.GILState? gilState = Py.GIL();
using PyScope? scope = Py.CreateScope();
scope.Import("package");
scope.Set("input", input);
var pyCode = await File.ReadAllTextAsync(Path.Join(AppDomain.CurrentDomain.BaseDirectory, "script.py"), cancellationToken);
scope.Exec(pyCode);
return scope.Get<string>("output");
```

Simply moving `var pyCode = await File.ReadAllTextAsync(Path.Join(AppDomain.CurrentDomain.BaseDirectory, "script.py"), cancellationToken);` above the scope fixed it. Hopefully this helps anyone who gets the same error, I didn't see any other issues where someone had raised this. I'd be happy to create a PR updating the "Embedding Python in .NET" section of the README.rst to advise against performing async blocks inside of the Py.GIL() block for Linux compatibility.

**Comment by lostmsu** [comment]
@Worble Linux has nothing to do with the issue. It could have happened on Windows or MacOS too.

You just must release GIL before doing an async .NET call, and then grab it back after it completes because GIL is bound to the current thread, and async continuations can happen on any other worker thread by default.
