### ISSUE TITLE
memoryleak for float

### ISSUE THREAD

**Issue by roarlarsen** [pythonnet/pythonnet#146]
detected memory leak in **converter.cs - ToPrimitive function**

missing **Runtime.Decref(op);** at line 581

**Comment by denfromufa** [comment]
@roarlarsen thank you for spotting this, so do you mean something like this:

https://github.com/pythonnet/pythonnet/pull/147

**Comment by roarlarsen** [comment]
hi,

I didn't check out the develop version, only the master, so I see the line
# 581 I refer to should have been
# ~688, the leak is for float type, the decref is missing.

But, the code you suggest is an possible memleak as well in case the char
value is out of range (rarely though)




Roar Larsen
--------------------------------------------------------------------------------------
TORDIVEL AS
Postboks 1209, Sluppen
N-7462 Trondheim, Norway
Tel : +47 9151 0203 Fax : + 47 2315 8701
E-mail : roar@tordivel.no Web : http://www.tordivel.no
--------------------------------------------------------------------------------------
...... THE VISION SOFTWARE HOUSE
--------------------------------------------------------------------------------------

**Comment by roarlarsen** [comment]
few more observations in develop version.....

there are several IFDEF's PYTHONnn where there seems to be a decref missing


line #653 - int err = Runtime.PyObject_Compare(check, op);

the op object is decref'ed at line #647 - small risk of GC deletion op
inbetween
line #647 and #653, but...



Roar Larsen
--------------------------------------------------------------------------------------
TORDIVEL AS
Postboks 1209, Sluppen
N-7462 Trondheim, Norway
Tel : +47 9151 0203 Fax : + 47 2315 8701
E-mail : roar@tordivel.no Web : http://www.tordivel.no
--------------------------------------------------------------------------------------
...... THE VISION SOFTWARE HOUSE
--------------------------------------------------------------------------------------

**Comment by denfromufa** [comment]
@roarlarsen @tonyroberts thanks again, do you agree with these changes:

https://github.com/pythonnet/pythonnet/pull/147

**Comment by roarlarsen** [comment]
Looks fine

What is current status of this project, don't see too many references to
pythonnet on
the web but I think it is great for embedding .net controls into our
application written in Delphi via the embedded pythonengine?

Roar Larsen
roar@tordivel.no

- by my Android
11. feb. 2016 23:11 skrev "denfromufa" <notifications@github.com>:

**Comment by denfromufa** [comment]
There is python.net tag on stackoverflow
http://stackoverflow.com/questions/tagged/python.net, mailing list at
https://mail.python.org/pipermail/pythondotnet/

What else do you think is missing?

can you share minimal with delphi, how is it related to .NET?

**Comment by denfromufa** [comment]
forgot to mention ironpython docs and even book which are mostly applicable
to python.net, but you can also use many other packages like numpy, scipy.

**Comment by roarlarsen** [comment]
I'm aware of the stackoverflow thread, but I miss some more python samples
for clr usage/tips/hints.

We have a native delphi application with an embedded python engine so we
can run python scripts within
the application. The application adds a module to the python
environment/room so you get access to the
inner kernel of the application, data, objects, resources etc. The user can
write project specific python code
inside the application, and in these scripts we imports clr and the .net
environment.

We are machine vision company, and we're using opencv, numpy, scipi and
many other python libraries in
addition to C/C++ and delphi libraries. Currently we are developing some
new image processing algorithms
based on .Net, so we use pythonnet to  embed .net C# classes into the
application.





Roar Larsen
--------------------------------------------------------------------------------------
TORDIVEL AS
Postboks 1209, Sluppen
N-7462 Trondheim, Norway
Tel : +47 9151 0203 Fax : + 47 2315 8701
E-mail : roar@tordivel.no Web : http://www.tordivel.no
--------------------------------------------------------------------------------------
...... THE VISION SOFTWARE HOUSE
--------------------------------------------------------------------------------------

**Comment by denfromufa** [comment]
@roarlarsen I assume you have seen this tutorial:

http://pythonnet.github.io/readme.html

also this ironpython tutorial:

http://ironpython.net/documentation/dotnet/

Perhaps someone can turn this into ipython notebook.
