### ISSUE TITLE
[DocBug] Getting Started on homepage should refer to wiki on github

### ISSUE THREAD

**Issue by charliearcuri** [pythonnet/pythonnet#1462]
### Environment

-   Pythonnet version: **2.5.2**
-   Python version: **3.8.10**
-   Operating System: **Windows 10**
-   .NET Runtime: .NET Core 3.1 or .NET 5.0

### Details

-   Describe what you were trying to get done.

    I'm taking my very first steps using Python.  I'm a C# developer who has built a .NET Class Library that runs in any .NET Core environment and some of my users prefer Python to PowerShell.
     I see the [homepage](https://pythonnet.github.io/) has a **Getting Started** section:
`A good way to start is to interactively explore .NET usage in python interpreter by following along with the examples in this document. If you get stuck, there are also a number of demos and unit tests located in the source directory of the distribution that can be helpful as examples.
`
  So, I spend some time looking at the rest of the homepage demos and [pythonnet/demo/helloform.py](https://github.com/pythonnet/pythonnet/blob/master/demo/helloform.py) but don't find anything related to the relatively new .NET Core Class Library support from Python.NET.  I really want to load my DLL and use some of the types in it.
     Eventually (after chasing my tail and wandering around), I come across the wiki and especially:
[Tutorial: How To Call A Dynamic Library](https://github.com/pythonnet/pythonnet/wiki/How-to-call-a-dynamic-library#tutorial-how-to-call-a-dynamic-library)

-   What commands did you run to trigger this issue? If you can provide a
    Read the [homepage](https://pythonnet.github.io/)'s Getting Started section.

-   If there was a crash, please include the traceback here.

```python
    Not applicable.
```

**Comment by filmor** [comment]
Merged. Just be aware, that integrating .NET Core in Python is currently only supported on `master` and is only "documented" in the respective pinned issue.
