### ISSUE TITLE
How to make pythonnet find the app.config?

### ISSUE THREAD

**Issue by cfrelet** [pythonnet/pythonnet#1464]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.8
-   Operating System: Windows 10
-   .NET Framework: 4.6 

### Details

I'm trying to run a WCF service in Python using pythonnet with the configuration being in app.config
If I just configure the biding in the code itself, the service works fine. But as soon as I require the C# code to access the config I will get an error like it cannot find the config file:

> Could not find default endpoint element that references contract 'HedgeConverterServiceProxy.IHedgeConverterService' in the ServiceModel client configuration section. This might be because no configuration file was found for your application, or because no endpoint element matching this contract could be found in the client element. at System.ServiceModel.Description.ConfigLoader.LoadChannelBehaviors

### Question:
How can I make pythonnet takes the project.Functions.dll.config into account? It doesn't seem to find it.

**Comment by filmor** [comment]
This is not really Python.NET-specific. The `app.config` is picked up by looking for `{executable\path}.config`, in this case this will be something like `c:\Python\python.exe.config`. If you are want to use .NET from within a normal Python environment, then you'll have to find another way to inject the required configuration (or just put the file there, but that's quite hacky).
