### ISSUE TITLE
How can I execute several scripts in different threads at the same time by using Python.Net

### ISSUE THREAD

**Issue by MarkHuang1996** [pythonnet/pythonnet#1468]
### Environment

-   Pythonnet version:3.00 -preview2021-04-05
-   Python version: 38
-   Operating System: win10
-   .NET Runtime: .net core 3.1

### Details

How can I execute several scripts in different threads at the same time by using Python.Net

I tried a couple of times, python always shows me the thread error.

**Comment by lostmsu** [comment]
https://github.com/pythonnet/pythonnet/wiki/Threading
