### ISSUE TITLE
Pythonnet installation problem

### ISSUE THREAD

**Issue by Frosterast2** [pythonnet/pythonnet#1472]
I was trying to install pywebview and the installation was errored out. I posted it in Issued in the pywebview repository and figured out its an issue in the installation of pythonnet. Can anyone please help me

Error: Collecting pythonnet==2.5.2
  Using cached pythonnet-2.5.2.tar.gz (1.9 MB)
Requirement already satisfied: pycparser in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from pythonnet==2.5.2) (2.20)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\saketh\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-fzeovuga\\pythonnet_ab1aa78f140b46f084935b06e438666b\\setup.py'"'"'; __file__='"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-fzeovuga\\pythonnet_ab1aa78f140b46f084935b06e438666b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\saketh\AppData\Local\Temp\pip-wheel-786pxffw'  
       cwd: C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\
  Complete output (39 lines):
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 5.9.1.
  Update successful.
  Cannot find the specified version of msbuild: '14'
  MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'.
  C:\Users\saketh\AppData\Local\Temp\NuGetScratch\eebovdzh.ozd.nugetrestore.targets(460,20): error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\src\runtime\Python.Runtime.csproj]
  C:\Users\saketh\AppData\Local\Temp\NuGetScratch\eebovdzh.ozd.nugetrestore.targets(460,20): error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\src\testing\Python.Test.csproj]
  C:\Users\saketh\AppData\Local\Temp\NuGetScratch\eebovdzh.ozd.nugetrestore.targets(460,20): error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\src\embed_tests\Python.EmbeddingTest.csproj]
  C:\Users\saketh\AppData\Local\Temp\NuGetScratch\eebovdzh.ozd.nugetrestore.targets(460,20): error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\src\console\Console.csproj]
  C:\Users\saketh\AppData\Local\Temp\NuGetScratch\eebovdzh.ozd.nugetrestore.targets(460,20): error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\src\clrmodule\clrmodule.csproj]

  WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
  Restoring NuGet package NUnit.3.12.0.
  Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package System.ValueTuple.4.5.0.
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\packages'
  Adding package 'System.ValueTuple.4.5.0' to folder 'C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\packages'
  Adding package 'NUnit.3.12.0' to folder 'C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\packages'
  Adding package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\packages'
  Added package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\packages'
  Added package 'System.ValueTuple.4.5.0' to folder 'C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\packages'
  Added package 'NUnit.3.12.0' to folder 'C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\packages'

  NuGet Config files used:
      C:\Users\saketh\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      C:\Users\saketh\.nuget\packages\
      https://api.nuget.org/v3/index.json

  Installed:
      4 package(s) to packages.config projects
  error: [WinError 2] The system cannot find the file specified
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saketh\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-fzeovuga\\pythonnet_ab1aa78f140b46f084935b06e438666b\\setup.py'"'"'; __file__='"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-fzeovuga\\pythonnet_ab1aa78f140b46f084935b06e438666b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\saketh\AppData\Local\Temp\pip-record-f3r3y56s\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\saketh\appdata\local\programs\python\python39\Include\pythonnet'
         cwd: C:\Users\saketh\AppData\Local\Temp\pip-install-fzeovuga\pythonnet_ab1aa78f140b46f084935b06e438666b\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\saketh\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-fzeovuga\\pythonnet_ab1aa78f140b46f084935b06e438666b\\setup.py'"'"'; __file__='"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-fzeovuga\\pythonnet_ab1aa78f140b46f084935b06e438666b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\saketh\AppData\Local\Temp\pip-record-f3r3y56s\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\saketh\appdata\local\programs\python\python39\Include\pythonnet' Check the logs for full command output.

**Comment by AsafAsher** [comment]
I have the same issue.
Unable to install pythonnet on PC but works fine for mac.

C:\Users\asafa>pip install pythonnet
Collecting pythonnet
  Using cached pythonnet-2.5.2.tar.gz (1.9 MB)
Requirement already satisfied: pycparser in c:\users\asafa\appdata\local\programs\python\python39\lib\site-packages (from pythonnet) (2.20)
Using legacy 'setup.py install' for pythonnet, since package 'wheel' is not installed.
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\asafa\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\asafa\\AppData\\Local\\Temp\\pip-install-06v_3t3e\\pythonnet_29af4c179f7546eabe08fc2e7b2b0608\\setup.py'"'"'; __file__='"'"'C:\\Users\\asafa\\AppData\\Local\\Temp\\pip-install-06v_3t3e\\pythonnet_29af4c179f7546eabe08fc2e7b2b0608\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\asafa\AppData\Local\Temp\pip-record-z0gpg_03\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\asafa\appdata\local\programs\python\python39\Include\pythonnet'
         cwd: C:\Users\asafa\AppData\Local\Temp\pip-install-06v_3t3e\pythonnet_29af4c179f7546eabe08fc2e7b2b0608\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\asafa\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\asafa\\AppData\\Local\\Temp\\pip-install-06v_3t3e\\pythonnet_29af4c179f7546eabe08fc2e7b2b0608\\setup.py'"'"'; __file__='"'"'C:\\Users\\asafa\\AppData\\Local\\Temp\\pip-install-06v_3t3e\\pythonnet_29af4c179f7546eabe08fc2e7b2b0608\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\asafa\AppData\Local\Temp\pip-record-z0gpg_03\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\asafa\appdata\local\programs\python\python39\Include\pythonnet' Check the logs for full command output.

**Comment by Frosterast2** [comment]
somethings wrong lol

**Comment by filmor** [comment]
We don't support Python 3.9 on Python.NET 2.5 (the current stable version), see #1327. That's why the installer will not pick up a wheel file from pypi and instead try to build it from source, which has a build-time requirements.

**Comment by Frosterast2** [comment]
Oh okay. Hope you guys release support for v.3.9 soon 😄 . I can't wait to use webview
