### ISSUE TITLE
Repeated calls of python script containing Process.Join method call.

### ISSUE THREAD

**Issue by Barrent** [pythonnet/pythonnet#1490]
### Environment

-   Pythonnet version: pythonnet_netstandard_py37_win 2.5.2 
-   Python version: 3.7
-   Operating System: 1909 x64
-   .NET Runtime: .Net Framework 4.6.1

### Details

-   Describe what you were trying to get done.
    Hi, 
    I want to deploy gRPC service with python. To achieve that, I need to run python script that spawns a process and joins it. Instead of running the script once, it's called in infinity loop. How can I make it be called just once?

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
import multiprocessing
import time

def _sleep():
    # code of gRPC service
    try:
        while True:
            time.sleep(86400)
    except KeyboardInterrupt:
        server.stop(0)

def Hello():
    print('Hello 1')
    worker = multiprocessing.Process(target=_sleep)
    worker.start()
    worker.join()  
    print('Hello 2')
```
```C#
static void Main(string[] args)
{
    using (Py.GIL())
    {
        ((dynamic)Py.Import("sys")).path.append(ScriptFolder);
        var module = Py.Import("ProcessTest");
        ((dynamic)module).Hello();
        module.Dispose();
    }
}
```
![image](https://user-images.githubusercontent.com/12222139/125765519-2aa643fa-5081-4dc6-b3b1-8113dc0e7748.png)

**Comment by filmor** [comment]
This is a general problem with embedding Python and `multiprocessing` on Windows. If you check (and maybe print) the `args`, you will notice that the multiprocessing `Process` actually just starts your executable directly, thinking it is `python.exe`, as Windows doesn't have a `fork` system call. I would suggest you don't use `multiprocessing` in this situation at all and just start subprocesses with `subprocess`.
