### ISSUE TITLE
Emit:DefineDynamicAssembly works in Unity Editor but not in Unity Standalone

### ISSUE THREAD

**Issue by mespino-cityzenith** [pythonnet/pythonnet#1492]
### Environment

-   Pythonnet version:3.0.0-preview2021-06-04 
-   Python version:3.9
-   Operating System: Windows 10
-   .NET Runtime: Standard 2.0

### Details

-   Describe what you were trying to get done.

I am integrating pythonnet into Unity and it seems to work pretty well.
But, when I build a standalone version, I got a PlatformNotSupportedException.
Taking a closer look, I have found that the exception is triggered by Emit.DefineDynamicAssembly.
How can it be working on Editor and not in standalone version?

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

It just begin with PythonEngine.Initialize
* Python.Runtime.PythonEngine:Initialize
  * Python.Runtime.DelegateManager
    * Python.Runtime.CodeGenerator
      * Python.Runtime.ReflectionPolyfills:DefineDynamicAssembly
        * System.Reflection.Emit.AssemblyBuilder:DefineDynamicAssembly
          * Working ok in Unity Editor
          * PlatformNotSupportedException in Build Standalone Version
          * https://github.com/pythonnet/pythonnet/blob/191bc89364ed14af4ce81a40082a1af41b9cb0d1/src/runtime/polyfill/ReflectionPolyfills.cs#L12

Addition information:

- Unity 2020.3.11
- Scripting Backend: Mono
- Api Compatibility Level: .Net Standard 2.0
- Target platform: Windows
- Architecture x86_64
- pythonnet 3.0
- It works in Unity Editor Net 4
- It works in Standalone Net 4
- It works in Unity Editor Net Standard 2
- It doesn't work in Standalone Net Standard 2.

Unfortunately, switching to .Net 4.x is not an option

Any clue or workarround? 
Thank you

**Comment by filmor** [comment]
We can't provide support in here, definitely not for Unity. Please ask in their respective support channels. There is also official support nowadays (https://docs.unity3d.com/Packages/com.unity.scripting.python@4.0/manual/index.html) that uses Python.NET under the hood.
