### ISSUE TITLE
Crash when _objQueue.TryDequeue(out obj)  is called

### ISSUE THREAD

**Issue by ksrangarajan** [pythonnet/pythonnet#1493]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.9
-   Operating System: Windows
-   .NET Runtime: 4.6.1

### Details

-   Describe what you were trying to get done.
We have console application which calls the Pythonruntime for execution.
In one of the scripts it throws errror in the Finalizer.cs DisposeAll method when the line _objQueue.TryDequeue(out obj) gets executed where the stack trace shows the following

Unhandled Exception: Access voilation reading the location
Native Call
Runtime.Runtime.XCDecRef
Runtime.Dispatcher.Dispatch()
Finalizer.DisposeAll() line 121

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by lostmsu** [comment]
Can you provide a script, that reproduces the issue?

**Comment by ksrangarajan** [comment]
I dont have script to replicate. But  it happens when we run test script(Python file) as specified in the console project in paralllel.
We leveraged the code without any customization.

**Comment by lostmsu** [comment]
@ksrangarajan do you hold GIL at that time? Have you followed https://github.com/pythonnet/pythonnet/wiki/Threading ?

**Comment by ksrangarajan** [comment]
@lostmsu we  didnt use GIL. We use the code what we have in https://github.com/pythonnet/pythonnet/blob/master/src/console/pythonconsole.cs. Also the involvement of C# is less in our implementation and Python is more.

**Comment by lostmsu** [comment]
I am sorry, but I do not see an issue with pythonnet. If you did not follow the manual on running with multiple threads, having access violation exceptions is expected.
