### ISSUE TITLE
how to execute within Entrance "if __name__ == "__main__":"

### ISSUE THREAD

**Issue by NiKeYiGuN** [pythonnet/pythonnet#1495]
Here is a simple python file and I would like to try to execute it like main file in my .Net application. But I didn't find a way. Is there any way to do this? thx a lot
`import sys
import clr

def func1():
    print('func1')

def func2(a, b):
    print(a+b)
    print('func2')
    return a+b

if  __name__ == "__main__":
    print(func2(1,2))
    sys.exit(0)
`

**Comment by filmor** [comment]
This is not a support forum. With https://github.com/pythonnet/pythonnet/pull/1447, you should be able to load this code into a module that you just call `__main__`, that should be very close to what you are expecting.
