### ISSUE TITLE
Assigning a non existing field doesn't throw an exception

### ISSUE THREAD

**Issue by mespino-cityzenith** [pythonnet/pythonnet#1498]
### Environment

-   Pythonnet version: 3.0.0-preview2021-07-23 
-   Python version: python 3.9
-   Operating System: Windows 10
-   .NET Runtime: .Net 4.x
-   Unity: 2020.3.11

### Details

-   Describe what you were trying to get done.

Pythonnet doesn't throws an exception when you try to assign a field that doesn't exits. 

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

See in the following example how Environment.ExitCod is incorrect  (the correct form is Environment.ExitCode). However, the code doesn't throw an exception

On the other hand, if you use name = Environment.MachineNam instead of name = Environment.MachineName, you get the exception: AttributeError : type object 'Environment' has no attribute 'MachineNam', so I suppose is a "set issue", because it is working in "get"

```python
    from System import Environment
    name = Environment.MachineName
    Environment.ExitCod = 1
```

### C# example
```csharp
using Python.Runtime;
using UnityEngine;

public class NonExistingField : MonoBehaviour
{
    private void Start()
    {
        Test();
    }

    void Test()
    {
        PythonEngine.Initialize(mode: ShutdownMode.Soft);

        string code =
            "from System import Environment\n" +
            "name = Environment.MachineName\n" + //if you change this to "name = Environment.MachineNam" it does throw an exception because MachineNam doesn't exist
            //"name = Environment.MachineNam\n" +
            "Environment.ExitCod = 1"; //it should throw an exception because ExitCod doesn't exist

        using (Py.GIL())
        {
            PythonEngine.Exec(code);
        }

        PythonEngine.Shutdown(mode: ShutdownMode.Soft);
    }
}
```

-   If there was a crash, please include the traceback here.

**Comment by lostmsu** [comment]
This is by design. Python allows that for most classes, except the ones that take steps to prevent it.

**Comment by mespino-cityzenith** [comment]
Oh I see,

Could you please tell me where is this design decision implemented in the pythonnet code?

You've commented that there is a way in python to prevent this. How could I do that?

Thanks

**Comment by lostmsu** [comment]
@mespino-cityzenith https://stackoverflow.com/questions/16281227/how-to-limit-properties-available-on-a-python-class
