### ISSUE TITLE
PythonEngine.ShutDown() does not return in certain instances of threading

### ISSUE THREAD

**Issue by magnusjjj** [pythonnet/pythonnet#1500]
### Environment

-   Pythonnet version:
-   Python version: 3.8
-   Operating System: Windows 10, 64 bit.
-   .NET Runtime: 4.8

### Details

-   When doing a simple threading thing, PythonEngine.ShutDown() does not return.

    _TODO_

-   I created a simple test program https://github.com/magnusjjj/cleanstress . It should show the problem if you put a breakpoint on PythonEngine.IsInitialized in Form1.cs. It should be buildable in like a minute with the only change you need to do is to PYTHONNET_PYDLL

**Comment by lostmsu** [comment]
I don't think this is a bug. You need to terminate the background thread, otherwise there's no way for the Python runtime to shut down. There are multiple ways to do that, that you can find online, but nothing specific to Python.NET. So I am going to close this.

**Comment by magnusjjj** [comment]
Except this isn't mentioned anywhere. Not in the examples, not in the wiki, and there are no clean ways when googling to do it either. If it's impossible for the python runtime to be shut down safely, then there is no way to use it as a generic scripting plugin? It would require the user scripts to cooperate.

**Comment by filmor** [comment]
It's not mentioned because this is not specific to Python.NET but a property of threading in CPython. A script like this shouldn't finish as a normal program either, definitely not in an embedding scenario. You can read a bit more about this here: https://docs.python.org/3/library/threading.html#thread-objects (if you'd use a daemon thread, it should work)

**Comment by magnusjjj** [comment]
So it's not possible to actually *kill* python without the script's cooperation? As in, from C#. Been looking all over, but if the user does something like blanket catching exceptions. The closest I have found to actually forcibly exiting a thread is injecting a trace into it, and that only works if it's not blocking.

**Comment by lostmsu** [comment]
No, it is possible to kill a Python script.

Here's one of the ways to do so: https://github.com/pythonnet/pythonnet/blob/7d8f754ff6c4787133427f707f58727d4ddc4981/src/runtime/pythonengine.cs#L567

But in general without thread cooperation killing a thread running Python code can cause a crash. The function above does not prevent that either.

**Comment by magnusjjj** [comment]
That code is the same as the rest. It sends a keyboardinterrupt that can be caught and ignored by a simple try: catch: pass which is simple to accidentally do.

But I gotcha. This along with even with thread cooperation restarting python leading to crashes means an hiatus for my current project :'). One day, subinterpreters~

**Comment by lostmsu** [comment]
I think subinterpreters won't give you this ability either.
