### ISSUE TITLE
How to get result of "print("XXXX") " ? 

### ISSUE THREAD

**Issue by GentlerMan** [pythonnet/pythonnet#1501]
### Environment

-   Pythonnet version:2.5.2
-   Python version:3.8
-   Operating System:windows 10
-   .NET Runtime:.net framework 4.7.2

### Details

-  How to get result of "print("XXXX") "  when I embedded Python in my .net program? 
- it's called redirect when I use Ironpython ,but I couldn't find the same option to set

**Comment by filmor** [comment]
There is no builtin functionality for this. You can do it (like you would in pure Python) by creating a stream-like object that has the right `write` method and assigning it to `sys.stdout`.
