### ISSUE TITLE
How to Import .py file in .net program?

### ISSUE THREAD

**Issue by GentlerMan** [pythonnet/pythonnet#1503]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.8
-   Operating System: win10
-   .NET Runtime: 4.7.2

### Details

I have read all the samples but still don’t know how to read .py file by API for exec,

The following code just demonstrate how to import string code for Exec:

Example on Homepage:
// the person object may now be used in Python
string code = "fullName = person.FirstName + ' ' + person.LastName";
scope.Exec(code);

**Comment by filmor** [comment]
This is not a support forum. Just read the file with .NET's built-in mechanisms.
