### ISSUE TITLE
3.8.10/3.9.5 Cannot import module

### ISSUE THREAD

**Issue by IamMusavaRibica** [pythonnet/pythonnet#1504]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.8.10 / 3.9.5
-   Operating System: Windows 10
-   .NET Runtime: 3.1 / 5.0 (tried both)

### Details

I have a very simple DLL which has only one method which returns an integer (and does nothing else at all, just returns int)
When I tried to `clr.AddReference()` it, it added without any errors, but I cannot import the namespace or any class.
I tried both Debug and Release versions of dll
I tried both NET Core 3.1 and NET 5.0
Everything had the same issue: module not found
The dll: https://drive.google.com/file/d/1PIrcxuvtKa10D25gK2_dfMG9gOL9wdkU/
I also tried using `sys.path.append` combined with `clr.AddReference`with no luck

I heard that pythonnet cannot be installed using pip if python is 3.9 , then I pip installed the git. When that didn't fix my issue I installed python 3.8.10 and then pythonnet using command `python -3.8 -m pip install pythonnet` which makes `import clr` not work in 3.9 but that's okay

```python
import clr
clr.AddReference(r"Path\To\DLL")
from ConsoleReader import Program #fails

# or
import clr, sys
sys.path.append(r"Path\To\DLL\Dir")
clr.AddReference("DLLName")
from ConsoleReader import Program #fails
```

-   If there was a crash, please include the traceback here.

```python
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    from ConsoleReader import Program
ModuleNotFoundError: No module named 'ConsoleReader'
```

**Comment by lostmsu** [comment]
2.5.2 does not support .NET Core DLLs. You need Python.NET 3.0 preview, or switch to .NET Framework.
