### ISSUE TITLE
"System.Reflection.Emit.TypeBuilder"  Error

### ISSUE THREAD

**Issue by GentlerMan** [pythonnet/pythonnet#1505]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.8
-   Operating System: win10
-   .NET Runtime: 4.7.2

### Details

I just test Delegates on Python.Net, But meet the Error "System.Reflection.Emit.TypeBuilder" 

Code on Homepage:
`import clr,sys,time,datetime
clr.AddReference("System")
import System

def my_handler(source, args):
    print('my_handler called!')

d = System.AssemblyLoadEventHandler(my_handler)
System.AppDomain.CurrentDomain.AssemblyLoad += d`

**Comment by filmor** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) and a stacktrace.
