### ISSUE TITLE
ERROR: No matching distribution found for dotnet

### ISSUE THREAD

**Issue by bluefin-dlefcoe** [pythonnet/pythonnet#1506]
### Environment

-   Pythonnet version: 
-   Python version: 3.9
-   Operating System: Windows 10
-   .NET Runtime:

### Details

-   Describe what you were trying to get done.

import dotnet
print('dotnet is imported')

posted here:
https://stackoverflow.com/questions/68624902/error-no-matching-distribution-found-for-dotnet/68658076#68658076

pip install dotnet

try to get dotnet running in python 3.9 following upgrade from 2.7

```python

pip install dotnet
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement dotnet (from versions: none)
ERROR: No matching distribution found for dotnet


```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by filmor** [comment]
1. This is not a support forum
2. Please don't guess package names, look it up on the respective project pages (this one is called `pythonnet`, not `dotnet`)
3. Don't cross-post, wait for people to answer on StackOverflow
4. The latest stable release of Python.NET (2.5.2) is not stable on Python 3.9, for that you have to use the current master branch
