### ISSUE TITLE
import 'Windows.Foundation'

### ISSUE THREAD

**Issue by hiaselhans** [pythonnet/pythonnet#1516]
### Environment

-   Pythonnet version: upstream
-   Python version: 3.9
-   Operating System: Windows
-   .NET Runtime: 5.0.103

### Details

I am trying to use bleak with upstream pythonnet.
It fails to import symbols from Windows.Foundation:

``` python
from Windows.Foundation import (
    AsyncOperationCompletedHandler,
    IAsyncOperation,
    AsyncStatus,
)

# -> ModuleNotFoundError: No module named 'Windows'
```

Am i missing something?

**Comment by lostmsu** [comment]
WinRT is not "real .NET". You have two options: native Python [WinRT package on PyPi](https://pypi.org/project/winrt/) (I recommend that one) or [CsWinRT](https://github.com/microsoft/CsWinRT/blob/master/docs/usage.md)
