### ISSUE TITLE
AccessViolationException Crash in debug when run python script from C# just second time

### ISSUE THREAD

**Issue by GentlerMan** [pythonnet/pythonnet#1518]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.8.10
-   Operating System: win10
-   .NET Runtime: 4.7.2

### Details

AccessViolationException Crash in debug when run python script from C# just second time
It's all OK Just running the first time,But when run the code by thread again,the program will meet AccessViolationException
the following C# code has referenced [the Wiki "Threading"](https://github.com/pythonnet/pythonnet/wiki/Threading)
    
Notice:
I have found if py code doesn't import 3rd lib files, it seems No problem

Track Message:
System.AccessViolationException
HResult=0x80004003
Message=Attempt to read or write to protected memory.This usually indicates that other memory is corrupted。

C# Code
```
PythonEngine.Initialize();
var point = PythonEngine.BeginAllowThreads();
using (Py.GIL())
{
    using (PyScope scope = Py.CreateScope())
    {
        var complie = PythonEngine.Compile("import numpy\nprint ("OK")\n");
        scope.Execute(complie);
    }
}
PythonEngine.EndAllowThreads(point);
PythonEngine.Shutdown();
```

**Comment by lostmsu** [comment]
This is not a bug in pythonnet. NumPy does not support restart of Python runtime.

You can try using `ShutdownMode.Soft`
