### ISSUE TITLE
Import pyd failed

### ISSUE THREAD

**Issue by kehehee1** [pythonnet/pythonnet#1519]
### Environment

-   Pythonnet version:2.5.2.0
-   Python version:3.8.5
-   Operating System:Win10
-   .NET Runtime:4.0

### Details

I want to import a pyd file which is compiled by myself in a C# dll using  Py.Import. I have tried this one week, but it always throwed an exception "ImportError : DLL load failed while importing _SME_BASIC"(my pyd module called _SME_BASIC).I have append all the path to the sys.path,PythonPath, but no difference happened. I also tried to import the pyd through the python terminal, it worked. Finaly I wrote a demo application with C, it also worked. I really really have no idea what's the matter. Any help appreciate sinserely! The test code is as below:

```C#
public void ImportPydTest()
{
    PythonEngine.Initialize();
    //string strPyHome = @"PathToThePython38";
    //string strPyLib = @"PathToThePyd";
    //Environment.SetEnvironmentVariable("PATH", $@"{strPyHome};" + Environment.GetEnvironmentVariable("PATH"));
    //Environment.SetEnvironmentVariable("PYTHONHOME", strPyHome);
    //Environment.SetEnvironmentVariable("PYTHON_LIB", strPyLib);
    using (Py.GIL())
    {
        try
        {
            //PythonEngine.PythonHome = strPyLib;
            //PythonEngine.PythonPath = strPyLib;
            dynamic sys, os;
            sys = Py.Import("sys");
            os = Py.Import("os");
            string strPath = Assembly.GetExecutingAssembly().Location;
            strPath = Directory.GetParent(strPath).FullName;
            sys.path.append(strPath);
            strPath += @"\SME\core";
            sys.path.append(strPath);
            strPath = @"PathToThePython38";
            sys.path.append(strPath);
            PythonEngine.PythonPath += strPath;
            dynamic sme = Py.Import("SME.core._SME_BASIC");		// This line throws the exception
            MessageBox.Show(sme.__file__.ToString());
        }
        catch (Exception e)
        {
            MessageBox.Show(e.Message);
        }
    }
}
```

**Comment by kehehee1** [comment]
There is one special thing is that I invoke the `ImportPydTest()` through anther application. It is not the python.exe. I don' know whether this is the cause.

**Comment by filmor** [comment]
At first glance, I would say that this is independent of Python.NET. The error you are getting indicates that Python indeed found the DLL and tried to load it, but failed doing so. What's the full error message? Usually, there is a bit more info after the ":" in the message. Assuming you are running this on Windows, there are multiple possibilities, e.g.:

1. Wrong bitness, as .NET Framework applications by default start as 32bit IIRC
2. Failed dependency lookup (`_SME_BASIC`'s dependencies have to be in `PATH`)

**Comment by kehehee1** [comment]
I found the cause of this error.My application depends on Qt5.4,whereas the _SME_BASIC depends on another version of Qt(Qt5.12).The Qt versions conflict each other.
