### ISSUE TITLE
Some scipy modules fail to import

### ISSUE THREAD

**Issue by tactevo** [pythonnet/pythonnet#152]
Some scipy modules fail to import and return null when calling Py.Import().

- modules that fail:  scipy.signal, scipy.stats
- modules that successfully load:  scipy, scipy.cluster, scipy.fftpack

I'm using the development branch of pythonnet, scipy 0.17.0 and Python 2.7.11 (Anaconda 2.5.0 64-bit) on Windows.

**Comment by tactevo** [comment]
I've narrowed it down to a module imported by the scipy modules that fail.  The module is FixTk and is imported as part of PIL (the Python Imaging Library).

After calling Py.Import("FixTk"), It appears that ctypes.windll.kernel32.CloseHandle(hdir) is trying to close an invalid handle and throws an exception.  (The python repl import doesn't throw an exception with import FixTk).


```
Traceback (most recent call last):
  File "C:\Users\charley\Anaconda2\lib\lib-tk\FixTk.py", line 59, in <module>
    prefix = convert_path(prefix)
  File "C:\Users\charley\Anaconda2\lib\lib-tk\FixTk.py", line 37, in convert_path
    ctypes.windll.kernel32.CloseHandle(hdir)
WindowsError: [Error -1073741816] Windows Error 0xC0000008
```


The hack to get around this problem is to patch PIL's Image.py by commenting out the FixTk import. (Apparently only required when using Tk with Scikit).

(Image.py)
```
#try:
    # give Tk a chance to set up the environment, in case we're
    # using an _imaging module linked against libtcl/libtk (use
    # __import__ to hide this from naive packagers; we don't really
    # depend on Tk unless ImageTk is used, and that module already
    # imports Tkinter)
#    __import__("FixTk")
#except ImportError:
#    pass
```

**Comment by denfromufa** [comment]
@tactevo here is troubleshooting FAQ:

https://github.com/denfromufa/pythonnet/wiki/Troubleshooting-FAQ

What is your OS: Win7 or Win10?

Something is wrong with your setup, I test on both python 2.7 32bit and 64bit:

```
C:\Python\Python27_64b>ConsoleApplication1.exe
imported pip
imported FixTk
imported scipy
imported scipy.stats
imported  scipy.signal
```

```csharp
using Python.Runtime;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            PythonEngine.PythonHome = @"C:\Python\Python27_64b";
            PythonEngine.Initialize();
            using (Py.GIL()) {
                dynamic pip = Py.Import("pip");
            }
            System.Console.WriteLine("imported pip");
            using (Py.GIL()) {
                dynamic tk = Py.Import("FixTk");
            }
            System.Console.WriteLine("imported FixTk");
            using (Py.GIL()) {
                dynamic scipy = Py.Import("scipy");
            }
            System.Console.WriteLine("imported scipy");
            using (Py.GIL()) {
                dynamic stats = Py.Import("scipy.stats");
            }
            System.Console.WriteLine("imported scipy.stats");
            using (Py.GIL()) {
                dynamic signals = Py.Import(" scipy.signal");
            }
            System.Console.WriteLine("imported  scipy.signal");

        }
    }
}

```

**Comment by tonyroberts** [comment]
Most likely you just need to set the TCL_LIBRARY environment variable.

regards,
Tony

**Comment by denfromufa** [comment]
@tactevo not reproducible, so closing this issue

**Comment by tomhunter-gh** [comment]
I had the same problem when running a Python algo in QuantConnect Lean, in Visual Studio 2015.  When I ran the thing without debugging I didn't get the error, but when I started with debugging I got:

> ERROR:: Algorithm.Initialize() Error: Loader.TryCreatePythonAlgorithm(): Unable to import python module ../../../Algorithm.Python/XYZ.py. WindowsError : [Error -1073741816] Windows Error 0xC0000008

The Python stack trace was as follows:


> File "D:\...\XYZ.py", line 28, in <module>
from sklearn.neighbors import KNeighborsClassifier
  File "C:\Users\tomhu\Anaconda2\lib\site-packages\sklearn\__init__.py", line 57, in <module>
from .base import clone
  File "C:\Users\tomhu\Anaconda2\lib\site-packages\sklearn\base.py", line 11, in <module>
from .utils.fixes import signature
  File "C:\Users\tomhu\Anaconda2\lib\site-packages\sklearn\utils\__init__.py", line 11, in <module>
from .validation import (as_float_array,
  File "C:\Users\tomhu\Anaconda2\lib\site-packages\sklearn\utils\validation.py", line 16, in <module>
from ..utils.fixes import signature
  File "C:\Users\tomhu\Anaconda2\lib\site-packages\sklearn\utils\fixes.py", line 324, in <module>
from scipy.sparse.linalg import lsqr as sparse_lsqr
  File "C:\Users\tomhu\Anaconda2\lib\site-packages\scipy\sparse\linalg\__init__.py", line 116, in <module>
from .matfuncs import *
  File "C:\Users\tomhu\Anaconda2\lib\site-packages\scipy\sparse\linalg\matfuncs.py", line 19, in <module>
import scipy.misc
  File "C:\Users\tomhu\Anaconda2\lib\site-packages\scipy\misc\__init__.py", line 62, in <module>
from .pilutil import *
  File "C:\Users\tomhu\Anaconda2\lib\site-packages\scipy\misc\pilutil.py", line 19, in <module>
from PIL import Image, ImageFilter
  File "C:\Users\tomhu\Anaconda2\lib\site-packages\PIL\Image.py", line 56, in <module>
\_\_import\_\_("FixTk")
  File "C:\Users\tomhu\Anaconda2\lib\lib-tk\FixTk.py", line 59, in <module>
prefix = convert_path(prefix)
  File "C:\Users\tomhu\Anaconda2\lib\lib-tk\FixTk.py", line 37, in convert_path
ctypes.windll.kernel32.CloseHandle(hdir)

Commenting out the FixTk import in Image.py fixes the issue - thanks @tactevo
