### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by michaelosthege** [pythonnet/pythonnet#1520]
Before upgrading 2.5.1→2.5.2 I looked at the `CHANGELOG.md` to for a list of changes.

The changelog was updated 8 days ago, but seems to be out-of-sync with the [releases](https://github.com/pythonnet/pythonnet/releases)?

**Comment by filmor** [comment]
The 2.5 releases are done from the backports-2.5 branch. The Changelog is correct.

**Comment by michaelosthege** [comment]
Thanks @filmor for that fast response & explanation!

Related PR to link that release in the changelog of the branch: https://github.com/pythonnet/pythonnet/pull/1521
