### ISSUE TITLE
pythonnet installation failed

### ISSUE THREAD

**Issue by corneliumrsn** [pythonnet/pythonnet#1528]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.9.6
-   Operating System: Windows 10
-   .NET Runtime: 5.0

### Details

-   Describe what you were trying to get done.

   I was trying to install the package.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
   
    py -m pip install pythonnet

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```
Microsoft Windows [version 10.0.19042.1052]
(c) Microsoft Corporation. Tous droits réservés.

C:\windows\system32>py -m pip install pythonnet
Collecting pythonnet
  Using cached pythonnet-2.5.2.tar.gz (1.9 MB)
Requirement already satisfied: pycparser in c:\tools\python\python39\lib\site-packages (from pythonnet) (2.20)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Tools\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\uidr6898\\AppData\\Local\\Temp\\pip-install-_cu8cnj9\\pythonnet_df36ecc3821447f291de24ed5bb8606b\\setup.py'"'"'; __file__='"'"'C:\\Users\\uidr6898\\AppData\\Local\\Temp\\pip-install-_cu8cnj9\\pythonnet_df36ecc3821447f291de24ed5bb8606b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\uidr6898\AppData\Local\Temp\pip-wheel-facmsunf'
       cwd: C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\
  Complete output (167 lines):
  running bdist_wheel
  running build
  running build_ext
  Recherche de mises … jour depuis https://www.nuget.org/api/v2/.
  NuGet.exe 4.1.0 en cours d'ex‚cution.
  Mise … jour de NuGet.exe vers 5.10.0.
  Mise … jour r‚ussie.
  MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin\amd64'.
  Restoring NuGet package System.ValueTuple.4.5.0.
  Restoring NuGet package NUnit.3.12.0.
  Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\packages'
  Adding package 'System.ValueTuple.4.5.0' to folder 'C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\packages'
  Adding package 'NUnit.3.12.0' to folder 'C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\packages'
  Adding package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\packages'
  Added package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\packages'
  Added package 'System.ValueTuple.4.5.0' to folder 'C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\packages'
  Added package 'NUnit.3.12.0' to folder 'C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\packages'

  NuGet Config files used:
      C:\Users\uidr6898\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      C:\Users\uidr6898\.nuget\packages\
      https://api.nuget.org/v3/index.json

  Installed:
      4 package(s) to packages.config projects
  Microsoft (R) Manifest Tool version 6.3.9600.17336

  Copyright (c) Microsoft Corporation 2012.

  All rights reserved.

  Microsoft (R) Build Engine version 14.0.23107.0
  Copyright (C) Microsoft Corporation. All rights reserved.

  Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Build started 8/25/2021 10:05:07 AM.
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" on node 1 (Clean target(s)).
  ValidateSolutionConfiguration:
    Building solution configuration "ReleaseWin|x64".
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (1) is building "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\clrmodule\clrmodule.csproj" (2) on node 1 (Clean target(s)).
  CoreClean:
    Creating directory "obj\x64\ReleaseWin\".
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\clrmodule\clrmodule.csproj" (Clean target(s)).
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (1) is building "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\console\Console.csproj" (3) on node 1 (Clean target(s)).
  CoreClean:
    Creating directory "obj\x64\ReleaseWin\".
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\console\Console.csproj" (3) is building "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\runtime\Python.Runtime.csproj" (4) on node 1 (Clean target(s)).
  CoreClean:
    Creating directory "obj\x64\ReleaseWin\".
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\runtime\Python.Runtime.csproj" (Clean target(s)).
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\console\Console.csproj" (Clean target(s)).
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (1) is building "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\embed_tests\Python.EmbeddingTest.csproj" (5) on node 1 (Clean target(s)).
  CoreClean:
    Creating directory "obj\x64\ReleaseWin\".
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\embed_tests\Python.EmbeddingTest.csproj" (Clean target(s)).
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (1) is building "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\testing\Python.Test.csproj" (6) on node 1 (Clean target(s)).
  CoreClean:
    Creating directory "obj\x64\ReleaseWin\".
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\testing\Python.Test.csproj" (Clean target(s)).
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (Clean target(s)).

  Build succeeded.
      0 Warning(s)
      0 Error(s)

  Time Elapsed 00:00:00.17
  Microsoft (R) Build Engine version 14.0.23107.0
  Copyright (C) Microsoft Corporation. All rights reserved.

  Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Build started 8/25/2021 10:05:07 AM.
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" on node 1 (Build target(s)).
  ValidateSolutionConfiguration:
    Building solution configuration "ReleaseWin|x64".
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (1) is building "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\runtime\Python.Runtime.csproj" (2) on node 1 (default targets).
  PrepareForBuild:
    Creating directory "bin\".
  GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
  CoreCompile:
    C:\Program Files (x86)\MSBuild\14.0\bin\amd64\csc.exe /noconfig /unsafe+ /nowarn:1591,1701,1702 /langversion:7.3 /nostdlib+ /doc:bin\Python.Runtime.xml /define:PYTHON39;PYTHON3;UCS2 /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" /debug:pdbonly /optimize+ /out:obj\x64\ReleaseWin\Python.Runtime.dll /resource:resources\clr.py,clr.py /target:library /utf8output Codecs\EncoderGroup.cs Codecs\DecoderGroup.cs Codecs\RawProxyEncoder.cs Codecs\TupleCodecs.cs converterextensions.cs finalizer.cs Properties\AssemblyInfo.cs ..\SharedAssemblyInfo.cs arrayobject.cs assemblymanager.cs BorrowedReference.cs classderived.cs classbase.cs classmanager.cs classobject.cs clrobject.cs codegenerator.cs constructorbinder.cs constructorbinding.cs converter.cs CustomMarshaler.cs debughelper.cs delegatemanager.cs delegateobject.cs eventbinding.cs eventobject.cs exceptions.cs extensiontype.cs fieldobject.cs generictype.cs genericutil.cs importhook.cs indexer.cs interfaceobject.cs interfaces.cs interop.cs iterator.cs managedtype.cs metatype.cs methodbinder.cs methodbinding.cs methodobject.cs methodwrapper.cs modulefunctionobject.cs moduleobject.cs modulepropertyobject.cs nativecall.cs NewReference.cs NonCopyableAttribute.cs overload.cs propertyobject.cs pyansistring.cs pydict.cs PyExportAttribute.cs pyfloat.cs pyint.cs pyiter.cs pylist.cs pylong.cs pynumber.cs pyobject.cs pyscope.cs pysequence.cs pystring.cs pythonengine.cs pythonexception.cs pytuple.cs ReferenceExtensions.cs runtime.cs typemanager.cs typemethod.cs Util.cs platform\Types.cs platform\LibraryLoader.cs polyfill\ReflectionPolifills.cs slots\mp_length.cs interop39.cs "C:\Users\uidr6898\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cs"
  CSC : error CS1617: Option non valide '7.3' pour /langversionÿ; doit avoir la valeur ISO-1, ISO-2, Default ou ˆtre un entier compris dans la plage 1-6. [C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\runtime\Python.Runtime.csproj]
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\runtime\Python.Runtime.csproj" (default targets) -- FAILED.
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (1) is building "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\testing\Python.Test.csproj" (3) on node 1 (default targets).
  PrepareForBuild:
    Creating directory "bin\".
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\testing\Python.Test.csproj" (default targets) -- FAILED.
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (1) is building "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\embed_tests\Python.EmbeddingTest.csproj" (4) on node 1 (default targets).
  PrepareForBuild:
    Creating directory "bin\".
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\embed_tests\Python.EmbeddingTest.csproj" (default targets) -- FAILED.
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (1) is building "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\console\Console.csproj" (5) on node 1 (default targets).
  PrepareForBuild:
    Creating directory "bin\".
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\console\Console.csproj" (default targets) -- FAILED.
  Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (1) is building "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\clrmodule\clrmodule.csproj" (6) on node 1 (default targets).
  PrepareForBuild:
    Creating directory "bin\".
  GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
  CoreCompile:
    C:\Program Files (x86)\MSBuild\14.0\bin\amd64\csc.exe /noconfig /nowarn:1591,1701,1702 /langversion:6 /nostdlib+ /platform:x64 /errorreport:prompt /doc:bin\clrmodule.xml /define:PYTHON39;PYTHON3;UCS2 /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" /reference:C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\packages\UnmanagedExports.1.2.7\lib\net\RGiesecke.DllExport.Metadata.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" /debug:pdbonly /optimize+ /out:obj\x64\ReleaseWin\clrmodule.dll /target:library /utf8output Properties\AssemblyInfo.cs ..\SharedAssemblyInfo.cs ClrModule.cs "C:\Users\uidr6898\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cs"
  CopyFilesToOutputDirectory:
    Copying file from "obj\x64\ReleaseWin\clrmodule.dll" to "bin\clrmodule.dll".
    clrmodule -> C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\clrmodule\bin\clrmodule.dll
    Copying file from "obj\x64\ReleaseWin\clrmodule.pdb" to "bin\clrmodule.pdb".
  RGieseckeDllExport:
    Found method: clrModule..method public hidebysig static native int 'PyInit_clr'() cil managed
        exporting as PyInit_clr and index 0
  AfterBuild:
    Copying file from "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\clrmodule\bin\clrmodule.dll" to "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\build\lib.win-amd64-3.9\clr.pyd".
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\clrmodule\clrmodule.csproj" (default targets).
  Done Building Project "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (Build target(s)) -- FAILED.

  Build FAILED.

  "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\pythonnet.sln" (Build target) (1) ->
  "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\runtime\Python.Runtime.csproj" (default target) (2) ->
  (CoreCompile target) ->
    CSC : error CS1617: Option non valide '7.3' pour /langversionÿ; doit avoir la valeur ISO-1, ISO-2, Default ou ˆtre un entier compris dans la plage 1-6. [C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\runtime\Python.Runtime.csproj]

      0 Warning(s)
      1 Error(s)

  Time Elapsed 00:00:01.84
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\setup.py", line 630, in <module>
      setup(
    File "C:\Tools\Python\Python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Tools\Python\Python39\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Tools\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Tools\Python\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "C:\Tools\Python\Python39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Tools\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Tools\Python\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Tools\Python\Python39\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Tools\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Tools\Python\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Tools\Python\Python39\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Tools\Python\Python39\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Tools\Python\Python39\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\setup.py", line 353, in build_extension
      subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "C:\Tools\Python\Python39\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '"C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild.exe" pythonnet.sln /p:Configuration=ReleaseWin /p:Platform=x64 /p:DefineConstants="PYTHON39%3BPYTHON3%3BUCS2" /p:PythonBuildDir="C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\build\lib.win-amd64-3.9" /p:PythonInteropFile="interop39.cs" /p:PackageId=pythonnet_py39_x64 /verbosity:normal /p:PythonManifest="C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\build\lib.win-amd64-3.9\app.manifest" /t:Build' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Tools\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\uidr6898\\AppData\\Local\\Temp\\pip-install-_cu8cnj9\\pythonnet_df36ecc3821447f291de24ed5bb8606b\\setup.py'"'"'; __file__='"'"'C:\\Users\\uidr6898\\AppData\\Local\\Temp\\pip-install-_cu8cnj9\\pythonnet_df36ecc3821447f291de24ed5bb8606b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\uidr6898\AppData\Local\Temp\pip-record-724bhykn\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Tools\Python\Python39\Include\pythonnet'
         cwd: C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Tools\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\uidr6898\\AppData\\Local\\Temp\\pip-install-_cu8cnj9\\pythonnet_df36ecc3821447f291de24ed5bb8606b\\setup.py'"'"'; __file__='"'"'C:\\Users\\uidr6898\\AppData\\Local\\Temp\\pip-install-_cu8cnj9\\pythonnet_df36ecc3821447f291de24ed5bb8606b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\uidr6898\AppData\Local\Temp\pip-record-724bhykn\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Tools\Python\Python39\Include\pythonnet' Check the logs for full command output.

C:\windows\system32>

**Comment by filmor** [comment]
It tells you the error:
```
CSC : error CS1617: Option non valide '7.3' pour /langversionÿ; doit avoir la valeur ISO-1, ISO-2, Default ou ˆtre un entier compris dans la plage 1-6. [C:\Users\uidr6898\AppData\Local\Temp\pip-install-_cu8cnj9\pythonnet_df36ecc3821447f291de24ed5bb8606b\src\runtime\Python.Runtime.csproj]
```

Please install a more recent version of Visual Studio.

**Comment by filmor** [comment]
Also, if you want to use .NET 5, you need to build from `master`, it's not supported on 2.5.

**Comment by corneliumrsn** [comment]
Thank you.
