### ISSUE TITLE
Can't load .NET 5.0 assemblies (ModuleNotFoundError)

### ISSUE THREAD

**Issue by lock9** [pythonnet/pythonnet#1536]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.8.9
-   Operating System: Windows 10
-   .NET Runtime: .NET 5.0

### Details

-   Describe what you were trying to get done.

    I'm trying to import a .NET 5.0 library into my Python project. It fails with ModuleNotFoundError error.

-   What commands did you run to trigger this issue? If you can provide a
    Here is my C# Code:

```C#
using System;

namespace MyNameSpace
{
    public class Test
    {
        public String PrintTest()
        {
            return "TEST";
        }
    }
}
```

Here is my Python code:

```python
import clr

clr.AddReference("neo-wrapper-library")
from MyNameSpace import Test

test = Test()
print(test.PrintTest())

```
It works fine if the class is packaged on a .NET Standard library. It fails with `ModuleNotFoundError: No module named 'MyNameSpace'` if packaged on a .NET 5 library application

**Comment by lostmsu** [comment]
Pythonnet 2.5 does not support .NET 5

**Comment by lock9** [comment]
Thanks @lostmsu . I read in a few issues mentions to .NET 5. Will this be supported in the future? (version 3 for example)

**Comment by lostmsu** [comment]
It is supported in v3 previews.

**Comment by lock9** [comment]
@lostmsu how can I install v3 previews? I was unable to find it

**Comment by lostmsu** [comment]
You can always [install from master](https://github.com/pythonnet/pythonnet/wiki/Installation#github-installation-from-master-branch)

**Comment by lock9** [comment]
Hi @lostmsu , sorry to bother you again, but I'm using pythonnet 3.0 and I'm facing the same problem.
Should I open an issue or just wait, since it has not been released?

**Comment by lostmsu** [comment]
I think we are missing some documentation for v3 on how to use specific .NET runtime. @filmor ?

**Comment by lostmsu** [comment]
@lock9 check https://github.com/pythonnet/pythonnet/issues/1473 it has some hints on how to use `runtimeconfig` to load specific .NET runtime

**Comment by lock9** [comment]
It worked! Thanks a lot @lostmsu!
