### ISSUE TITLE
Unable to use directly the Encoding class

### ISSUE THREAD

**Issue by fortwoone** [pythonnet/pythonnet#1542]
### Environment

-   Pythonnet version: 3.0.0
-   Python version: 3.8.6
-   Operating System: Windows 7
-   .NET Runtime:

### Details

-   For some reason we can't instantiate any Encoding object in a Python file using Python.NET. I don't know if this is the case in C#, but no matter which C# constructor I try to use, I get an error stating that I can't instantiate an abstract class. This also prohibits Python subclassing for Encoding.

    _TODO_

-   Just call an Encoding constructor.

```python
    Encoding(0)
```

-   If there was a crash, please include the traceback here.

```python
    Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: cannot instantiate abstract class
```

**Comment by filmor** [comment]
The class *is* abstract. This has nothing to do with Python.NET, it wouldn't work in C# either. Use instances like `Encoding.UTF8` instead.
