### ISSUE TITLE
Error on `import clr`

### ISSUE THREAD

**Issue by bd** [pythonnet/pythonnet#1551]
### Environment

-   Pythonnet version: `3.0.0.dev1`
-   Python version: `Python 3.7.3`
-   Operating System: `mcr.microsoft.com/dotnet/core/sdk:3.1-buster` docker image
-   .NET Runtime: `Microsoft.AspNetCore.App 3.1.18`

### Details

-   Describe what you were trying to get done.

    Import and invoke C# code in python.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
# first line fails (this is demo.py)
import clr
```

-   If there was a crash, please include the traceback here.

```python
root@99bcc6ac0f81:/home/demonstrate# python3 demo.py 
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    import clr
  File "/usr/local/lib/python3.7/dist-packages/clr.py", line 6, in <module>
    load()
  File "/usr/local/lib/python3.7/dist-packages/pythonnet/__init__.py", line 37, in load
    set_default_runtime()
  File "/usr/local/lib/python3.7/dist-packages/pythonnet/__init__.py", line 23, in set_default_runtime
    set_runtime(clr_loader.get_mono())
  File "/usr/local/lib/python3.7/dist-packages/clr_loader/__init__.py", line 19, in get_mono
    libmono = find_libmono(sgen)
  File "/usr/local/lib/python3.7/dist-packages/clr_loader/util/find.py", line 71, in find_libmono
    raise RuntimeError("Could not find libmono")
RuntimeError: Could not find libmono
```

**Comment by filmor** [comment]
It tells you what's going on. On Linux, we currently default to Mono (because that is what previous versions of Python.NET used to do). If you want to load .NET Core stuff, you can follow what I sketched here: https://github.com/pythonnet/pythonnet/issues/984#issuecomment-778786164

**Comment by bd** [comment]
Perhaps updating the documentation would be helpful. I have read all of it, and it is not at all clear that anything defaults to mono. 

In general, it would be extremely helpful to have documentation targeted at people who are not familiar with .NET. Any assumption that developers who want to call .NET assemblies from Python would be deeply familiar with .NET ecosystem would be unsound...

**Comment by filmor** [comment]
You are using an in-development version of the library. The documentation will be in place once we get closer to a release.

**Comment by bd** [comment]
thanks, I will bear that in mind.
