### ISSUE TITLE
Python Runtime being reloaded

### ISSUE THREAD

**Issue by Martin-Molinero** [pythonnet/pythonnet#1553]
### Details

- Embedding C# in python

Start a jupyter env:
```
1:
docker run -it -p 8888:8888 --entrypoint bash quantconnect/research:12867
./start.sh
```

In a python 3 jupyter notebook:
```
2:
import Python.Runtime
# this is True
Python.Runtime.PythonEngine.IsInitialized

# See https://github.com/QuantConnect/AlphaStreams/blob/master/QuantConnect.AlphaStream/AlphaStreamRestClient.cs#L224
# 'using (Py.GIL())' triggers a new python net initialization
from QuantConnect.AlphaStream import *

client = AlphaStreamRestClient(AlphaCredentials("clientId", "token"))
# BOOM
pepe = client.GetAlphaEquityCurve("alphaId")
```

![image](https://user-images.githubusercontent.com/18473240/132719733-2f4e5694-a555-4029-974d-f15ca55cfa44.png)

------

`PythonEngine.IsInitialized` is false in the context of `AlphaStreamRestClient` instance for some reason and triggers a reload of python net and blows up.
Probably related to the assembly being reloaded by pythonNet and static variable value being cleared out?

**Comment by Martin-Molinero** [comment]
Ah wanted to add that it doesn't happen when embedding python into C# 🤔

**Comment by filmor** [comment]
Please don't just drop the issue template. Which version of Python.NET are you using here? If this happens with your fork, does it happen with the upstream version as well? Only `Runtime.Shutdown` sets `initialized = false;`, so you should probably find out why that one is called...

**Comment by lostmsu** [comment]
If multithreading is involved, you might want to add memory barriers. If that solves the issue for you, we likely have a lot of work to do...

**Comment by Martin-Molinero** [comment]
> Which version of Python.NET are you using here? If this happens with your fork, does it happen with the upstream version as well?

Sorry about that, still need to test with upstream - its not an easy to reproduce issue. 

> Only Runtime.Shutdown sets initialized = false;, so you should probably find out why that one is called...

Believe reloading the assembly would have the same effect, or loading it into a new domain (?) - `PythonEngine.IsInitialized` is not getting set to `False` from what I see form the jupyter notebook

> If multithreading is involved

All single threaded, shouldn't be the case 👌

**Comment by lostmsu** [comment]
@Martin-Molinero hm, I just hit something very similar in CI: https://github.com/pythonnet/pythonnet/runs/3602819836

**Comment by lostmsu** [comment]
@Martin-Molinero need a stable repro

**Comment by filmor** [comment]
`Py.GIL` doesn't trigger init anymore. If this is still an issue, please comment again :)
