### ISSUE TITLE
 Stuck on Py.GIL()

### ISSUE THREAD

**Issue by MarkHuang1996** [pythonnet/pythonnet#1567]
### Environment

-   Pythonnet version: pythonnet 2.5.2.0
-   Python version: Python 38_64
-   Operating System:WIN 10
-   .NET Runtime: Net 4.6.1

### Details

-   Hello,Im using Pythonnet  on my project,I having a python script and i trying to run it in my class library, but at the first time,pythonnet it is working fine and i can get the result return back, but when i call it again , it is stuck on PY.GIL() and not doing  anything for long time.
- 
```c#
public bool Checker_zip(string zipPath) {
	using (Py.GIL()) {
    	dynamic Checker = Py.Import("checker");
        string cameraPath = Path.Combine(zipPath, "camera.zip");
        if (File.Exists(cameraPath)) {
                    var result = Checker.checker_zip(cameraPath);
                    return result;
                } else {
                    return false;
                }
            }
        }
```

**Comment by filmor** [comment]
This is not a support forum. If you are stuck on `Py.GIL()`, it means that you are still holding the GIL (global interpreter lock) somewhere else. That's a bug in any case and unrelated to Python.NET. Feel free to reopen if you can provide a [Minimal, Complete, and Verifiable Example](https://stackoverflow.com/help/minimal-reproducible-example) that indicates an issue in Python.NET itself.

**Comment by tangbinbinyes** [comment]
我遇到的问题和你的一模一样.....，第二次使用就一直卡在using(Py.GIL())

**Comment by MarkHuang1996** [comment]
> 我遇到的问题和你的一模一样.....，第二次使用就一直卡在using(Py.GIL())
已经解决了

**Comment by tangbinbinyes** [comment]
> > 我遇到的问题和你的一模一样.....，第二次使用就一直卡在使用(Py.GIL())
> > 已经解决了

您好，如果可以的话，我能请教下您是如何解决的吗，我的开发目的是将PaddlePaddle库引入winform软件中，使C#能调用Paddle训练的语义分割模型。
using (Py.GIL())
            {
                pdx = Py.Import("paddlex");
                scope = Py.CreateScope();
            }
上面这段代码是初次调用using (Py.GIL())的内容；
当我第二次调用using(Py.GIL())时，代码会停顿在这一行而不会进入到using内部执行；
非常期待您的答复，谢谢~

**Comment by MarkHuang1996** [comment]
> > > 我遇到的问题和你的一模一样.....，第二次使用就一直卡在使用(Py.GIL())
> > > 已经解决了
> 
> 您好，如果可以的话，我能请教下您是如何解决的吗，我的开发目的是将PaddlePaddle库引入winform软件中，使C#能调用Paddle训练的语义分割模型。 using (Py.GIL()) { pdx = Py.Import("paddlex"); scope = Py.CreateScope(); } 上面这段代码是初次调用using (Py.GIL())的内容； 当我第二次调用using(Py.GIL())时，代码会停顿在这一行而不会进入到using内部执行； 非常期待您的答复，谢谢~

我的项目直接就简单粗暴的调用了通过线程池的方法每次创建线程调用using(Py.GIL), its works

**Comment by tangbinbinyes** [comment]
> > > > 我遇到的问题和你的一模一样.....，第二次使用就一直卡在使用(Py.GIL())
> > > > 已经解决了
> > 
> > 
> > 你好，如果你说的话，我能请教下你是如何解决的吗，我的开发目的是将 PaddlePaddle 库引入winform软件中，使 C#能调用 Paddle 训练的可以选择模型。 using (Py.GIL()) { pdx = Py.Import("paddlex"); 范围 = Py.CreateScope(); 上面这段代码是开始调用using (Py.GIL())的内容；当我第二次调用using(Py.GIL())时，代码会停在这个行而不会进入到使用内部执行；非常期待您的答复，谢谢~
> 
> 我的项目直接就简单粗暴的调用了通过线程池的方法，每次创建线程调用using(Py.GIL)，它的作品

你的这个方法我也发现了的，每次都用Task.Run来执行就可以，但是我又发现了一个新的问题，那就是如果期间有几分钟没有执行这段Python代码，再执行还是会卡在using Py.GIL()这里，即使是用Task.Run来执行的也不行，非常的奇怪，请问您有遇到这个奇怪的问题吗

**Comment by filmor** [comment]
@tangbinbinyes @MarkHuang1996 Please keep discussions on the issues in English.

**Comment by tangbinbinyes** [comment]
> > > > 我遇到的问题和你的一模一样.....，第二次使用就一直卡在使用(Py.GIL())
> > > > 已经解决了
> > 
> > 
> > 您好，如果可以的话，我能请教下您是如何解决的吗，我的开发目的是将PaddlePaddle库引入winform软件中，使C#能调用Paddle训练的语义分割模型。 using (Py.GIL()) { pdx = Py.Import("paddlex"); scope = Py.CreateScope(); } 上面这段代码是初次调用using (Py.GIL())的内容； 当我第二次调用using(Py.GIL())时，代码会停顿在这一行而不会进入到using内部执行； 非常期待您的答复，谢谢~
> 
> 我的项目直接就简单粗暴的调用了通过线程池的方法每次创建线程调用using(Py.GIL), its works

I have also discovered this method of yours. It can be executed with Task.Run() every time, but I have discovered a new problem, that is, if this Python code is not executed for a few minutes during the period,  when be executed again It will still get stuck here using Py.GIL() , even if it is executed with Task.Run().It is very strange. Have you encountered this strange problem?

**Comment by MarkHuang1996** [comment]
its works

> > > > > 我遇到的问题和你的一模一样.....，第二次使用就一直卡在使用(Py.GIL())
> > > > > 已经解决了
> > > 
> > > 
> > > 您好，如果可以的话，我能请教下您是如何解决的吗，我的开发目的是将PaddlePaddle库引入winform软件中，使C#能调用Paddle训练的语义分割模型。 using (Py.GIL()) { pdx = Py.Import("paddlex"); scope = Py.CreateScope(); } 上面这段代码是初次调用using (Py.GIL())的内容； 当我第二次调用using(Py.GIL())时，代码会停顿在这一行而不会进入到using内部执行； 非常期待您的答复，谢谢~
> > 
> > 
> > 我的项目直接就简单粗暴的调用了通过线程池的方法每次创建线程调用using(Py.GIL), its works
> 
> I have also discovered this method of yours. It can be executed with Task.Run() every time, but I have discovered a new problem, that is, if this Python code is not executed for a few minutes during the period, when be executed again It will still get stuck here using Py.GIL() , even if it is executed with Task.Run().It is very strange. Have you encountered this strange problem?



Did you call **PythonEngine.BeginAllowThreads()** this method?
My solution is shown below:

```c#
  private IntPtr _threadState;         
  public dynamic Checker { get; set; }         
  public Pythonnet python { get; set; }         
  public CameraCheckService() {            
      string pathToVirtualEnv = Path.Combine(Environment.CurrentDirectory, "Python38_64");             
      Environment.SetEnvironmentVariable("PATH", pathToVirtualEnv, EnvironmentVariableTarget.Process);
      
      Environment.SetEnvironmentVariable("PYTHONHOME", pathToVirtualEnv, EnvironmentVariableTarget.Process);
      
      Environment.SetEnvironmentVariable("PYTHONPATH", $"{pathToVirtualEnv}\\Lib\\site-packages;{pathToVirtualEnv}\\Lib", EnvironmentVariableTarget.Process); 
      
      PythonEngine.PythonHome = pathToVirtualEnv; 
      
      PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH", EnvironmentVariableTarget.Process); 
      
      PythonEngine.Initialize();   
      
      _threadState = PythonEngine.BeginAllowThreads();  
      
      using (Py.GIL()) {                
          Checker = Py.Import("checker");           
      }                   
  }         
public bool Checker_zip(string zipPath) {                       
    string cameraPath = Path.Combine(zipPath, "camera.zip");            
    if (File.Exists(cameraPath)) {                
        bool result = false;                 
        Task.Factory.StartNew(() => {                     
            using (Py.GIL()) {                        
                result = Checker.checker_zip(cameraPath);                    
            }                
        }).Wait();                
        File.Delete(cameraPath);                
        return result;            
    } else 
    {                              
        return false;            
    }
```

**Comment by tangbinbinyes** [comment]
> 



> its works
> 
> > > > > > 我遇到的问题和你的一模一样.....，第二次使用就一直卡在使用(Py.GIL())
> > > > > > 已经解决了
> > > > 
> > > > 
> > > > 您好，如果可以的话，我能请教下您是如何解决的吗，我的开发目的是将PaddlePaddle库引入winform软件中，使C#能调用Paddle训练的语义分割模型。 using (Py.GIL()) { pdx = Py.Import("paddlex"); scope = Py.CreateScope(); } 上面这段代码是初次调用using (Py.GIL())的内容； 当我第二次调用using(Py.GIL())时，代码会停顿在这一行而不会进入到using内部执行； 非常期待您的答复，谢谢~
> > > 
> > > 
> > > 我的项目直接就简单粗暴的调用了通过线程池的方法每次创建线程调用using(Py.GIL), its works
> > 
> > 
> > I have also discovered this method of yours. It can be executed with Task.Run() every time, but I have discovered a new problem, that is, if this Python code is not executed for a few minutes during the period, when be executed again It will still get stuck here using Py.GIL() , even if it is executed with Task.Run().It is very strange. Have you encountered this strange problem?
> 
> Did you call **PythonEngine.BeginAllowThreads()** this method? My solution is shown below:
> 
> ```cs
>   private IntPtr _threadState;         
>   public dynamic Checker { get; set; }         
>   public Pythonnet python { get; set; }         
>   public CameraCheckService() {            
>       string pathToVirtualEnv = Path.Combine(Environment.CurrentDirectory, "Python38_64");             
>       Environment.SetEnvironmentVariable("PATH", pathToVirtualEnv, EnvironmentVariableTarget.Process);
>       
>       Environment.SetEnvironmentVariable("PYTHONHOME", pathToVirtualEnv, EnvironmentVariableTarget.Process);
>       
>       Environment.SetEnvironmentVariable("PYTHONPATH", $"{pathToVirtualEnv}\\Lib\\site-packages;{pathToVirtualEnv}\\Lib", EnvironmentVariableTarget.Process); 
>       
>       PythonEngine.PythonHome = pathToVirtualEnv; 
>       
>       PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH", EnvironmentVariableTarget.Process); 
>       
>       PythonEngine.Initialize();   
>       
>       _threadState = PythonEngine.BeginAllowThreads();  
>       
>       using (Py.GIL()) {                
>           Checker = Py.Import("checker");           
>       }                   
>   }         
> public bool Checker_zip(string zipPath) {                       
>     string cameraPath = Path.Combine(zipPath, "camera.zip");            
>     if (File.Exists(cameraPath)) {                
>         bool result = false;                 
>         Task.Factory.StartNew(() => {                     
>             using (Py.GIL()) {                        
>                 result = Checker.checker_zip(cameraPath);                    
>             }                
>         }).Wait();                
>         File.Delete(cameraPath);                
>         return result;            
>     } else 
>     {                              
>         return false;            
>     }
> ```

Thank you very much for your help, using PythonEngine.BeginAllowThreads() perfectly solved my problem

**Comment by tangbinbinyes** [comment]
> 其作品
> 
> > > > > > 我遇到的问题和你的一模一样.....，第二次使用就一直卡在使用(Py.GIL())
> > > > > > 已经解决了
> > > > 
> > > > 
> > > > 你好，如果你说的话，我能请教下你是如何解决的吗，我的开发目的是将 PaddlePaddle 库引入winform软件中，使 C#能调用 Paddle 训练的可以选择模型。 using (Py.GIL()) { pdx = Py.Import("paddlex"); 范围 = Py.CreateScope(); 上面这段代码是开始调用using (Py.GIL())的内容；当我第二次调用using(Py.GIL())时，代码会停在这个行而不会进入到使用内部执行；非常期待您的答复，谢谢~
> > > 
> > > 
> > > 我的项目直接就简单粗暴的调用了通过线程池的方法，每次创建线程调用using(Py.GIL)，它的作品
> > 
> > 
> > 我也发现了你的这个方法。每次都可以用Task.Run()执行，但是我发现了一个新问题，就是这段Python代码如果在这期间有几分钟没有执行，再次执行的时候还是会卡在这里使用Py.GIL() ，就算是用Task.Run()来执行的。也是很奇怪的。你遇到过这个奇怪的问题吗？
> 
> 你有没有调用**PythonEngine.BeginAllowThreads()**这个方法？ 我的解决方案如下所示：
> 
> ```cs
>   私有 IntPtr  _threadState ;         
>   公共 动态 检查器{获取；设置; }         
>   公共 Pythonnet 蟒{得到; 设置; }         
>    public  CameraCheckService () {            
>        string  pathToVirtualEnv  =  Path。结合（环境。currentDirectory所，“ Python38_64 ”）;             
>       环境。设置环境变量(“路径”、 pathToVirtualEnv、 EnvironmentVariableTarget。过程);
>       
>       环境。SetEnvironmentVariable（“ PYTHONHOME ”，pathToVirtualEnv，EnvironmentVariableTarget。过程）；
>       
>       环境。SetEnvironmentVariable ( " PYTHONPATH " , $" { pathToVirtualEnv } \\ Lib \\ site-packages;{ pathToVirtualEnv } \\ Lib " , EnvironmentVariableTarget . Process );
>       
>       Python引擎。PythonHome  =  pathToVirtualEnv ;
>       
>       Python引擎。PythonPath  = 环境。GetEnvironmentVariable（“ PYTHONPATH ”，EnvironmentVariableTarget。过程）;
>       
>       Python引擎。初始化();   
>       
>       _threadState  =  PythonEngine。开始允许线程();  
>       
>       使用( Py . GIL ()) {                
>            Checker  =  Py . 导入（“检查器”）；           
>       }                   
>   }         
> public  bool  Checker_zip ( string  zipPath ) {                       
>      string  cameraPath  =  Path . 结合( zipPath , " camera.zip " );            
>     if ( File . Exists ( cameraPath )) {                
>          bool  result  =  false ;                 
>         任务。工厂。StartNew (() => {                     
>             使用( Py . GIL ()) {                        
>                  result  =  Checker . checker_zip ( cameraPath );                    
>             }                
>         })。等待();                
>         文件. 删除（相机路径）；                
>         返回 结果；            
>     }其他 
>     {                              
>         返回 假；            
>     }
> ```

Hello, during the test, I found another problem: System.AccessViolationException: "Trying to read or write protected memory. This usually indicates that other memory is corrupted."
`public void ExecuteSegmentation(Mat _matImage,string saveImagePath = null)
        {
            Cv2.Resize(_matImage, _matImage,new OpenCvSharp.Size(640,480));
            Task.Factory.StartNew(() => {
                try
                {
                    Stopwatch sw = new Stopwatch();
                    sw.Start();
                    using (Py.GIL())
                    {
                        #region convert image to memory buffer
                        byte[] img_csharp_to_python;
                        if (!Cv2.ImEncode(".png", _matImage, out img_csharp_to_python))
                            throw new Exception("C#创建图像内存流失败！");
                        #endregion
                        FormLogBar.Instance.ShowLog("image memory buffer length: " + img_csharp_to_python.Length.ToString());
                        List<byte> list_img_csharp_to_python = img_csharp_to_python.ToList();
                        dynamic array_img_csharp_to_python = np.array(list_img_csharp_to_python, np.uint8);
                        var img = cv2.imdecode(array_img_csharp_to_python, cv2.IMREAD_COLOR);
                        if (img == null)
                            throw new Exception("从内存流读取图像失败");
                        var result = model.predict(img);
                    }
                }
                catch (System.Exception s)
                {
                    LogHelper.SaveErrorInfo(s);
                }
            });
        }`
In this line of code, there is a chance that an error will be reported: var result = model.predict(img); System.AccessViolationException
