### ISSUE TITLE
time.sleep() is invalid in Python3.8 and above

### ISSUE THREAD

**Issue by rsdte** [pythonnet/pythonnet#1572]
### Environment

-   Pythonnet version: 3.0.0-preview all
-   Python version: 3.7.9, 3.8.0 and 3.9.0
-   Operating System: win11 21H2 (22000.194)
-   .NET Runtime:  .net 5

### Details

-   Describe
In order to test whether `sleep()` works, I tried to initialize the pythonnet environment with different versions of python and ran the same code. The result is only effective in Python 3.7, and invalid in 3.8 and 3.9. The following is the sample code.

```c#
static void Main(string[] args) {
	var code = @"
import time
time.sleep(8)
";

	Runtime.PythonDLL = @"D:\Programs\Python3\Python37\python37.dll";
	PythonEngine.PythonHome = @"D:\Programs\Python3\Python37\";
	PythonEngine.PythonPath = @"D:\Programs\Python3\Python37\Lib\";

	//Runtime.PythonDLL = @"D:\Programs\Python3\Python39\python39.dll";
	//PythonEngine.PythonHome = @"D:\Programs\Python3\Python39\";
	//PythonEngine.PythonPath = @"D:\Programs\Python3\Python39\Lib\";

	//Runtime.PythonDLL = @"D:\Programs\Python3\Python38\python38.dll";
	//PythonEngine.PythonHome = @"D:\Programs\Python3\Python38\";
	//PythonEngine.PythonPath = @"D:\Programs\Python3\Python38\Lib\";

	PythonEngine.Initialize();
	Stopwatch stopwatch = new Stopwatch();
	using (Py.GIL()) {
		using (var scope = Py.CreateScope()) {
			var script = PythonEngine.Compile(code);
			stopwatch.Start();
			scope.Exec(code);
			stopwatch.Stop();
			Console.WriteLine($"time elapsed: {stopwatch.ElapsedMilliseconds}");
		}
	}
	PythonEngine.Shutdown();
}
```

Screenshot of Python3.7 results:

![3 7](https://user-images.githubusercontent.com/39526920/134879770-8d4d9284-db62-4d85-b7e5-4ce9606d503c.jpg)

Screenshot of Python3.8 results:
![3 8](https://user-images.githubusercontent.com/39526920/134879920-2c4669c6-fd69-4039-a31e-ae71f7d1172c.jpg)

Screenshot of Python3.9 results:

![3 9](https://user-images.githubusercontent.com/39526920/134879824-aed87070-af5e-4fd0-bffb-792d08e35970.jpg)

**Comment by lostmsu** [comment]
https://bugs.python.org/issue41686
