### ISSUE TITLE
Can’t run C# code for preview version of this repo.

### ISSUE THREAD

**Issue by zydjohnHotmail** [pythonnet/pythonnet#1575]
### Environment

-   Pythonnet version: 3.0.0-preview2021-09-03
-   Python version: 3.9.7
-   Operating System: Windows 10
-   .NET Runtime: .Net 5.0

### Details

-   Describe what you were trying to get done.
     Run some C# code to call Python code.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
    To install pythonnet from Windows 10:
    C:\WINDOWS\system32>python -m pip install pythonnet
```python
```

-   If there was a crash, please include the traceback here.

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Delegates' threw an exception.
  Source=Python.Runtime
  StackTrace:
   at Python.Runtime.Runtime.Delegates.get_Py_IsInitialized()
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.Initialize()
   at Python.Runtime.Py.GIL()
   at Pythonnet3Test.Program.Main() in C:\SoccerVideos\Helper\Pythonnet3Test\Pythonnet3Test\Program.cs:line 11

Inner Exception 1:
MissingMethodException: Did you forget to set Runtime.PythonDLL? See https://github.com/pythonnet/pythonnet#embedding-python-in-net

Inner Exception 2:
MissingMethodException: Failed to load symbol PyDictProxy_New

Inner Exception 3:
Win32Exception: The specified procedure could not be found.

Hello:
I found this repo, which is very interesting. I have some python code, I want to convert to C#, but it is not easy, so I want to see if I can use this repo to simply run my python code.
I have done the following:
1. Create one Console Project (C# using Visual Studio 2019 Version 16.11.3, target .NET 5.0 on Windows 10)
2. Install the following Nuget package:
PM> Install-Package pythonnet -Version 3.0.0-preview2021-09-03

The following is my C# code:

`
using Python.Runtime;
using System;
using System.Collections.Generic;

namespace Pythonnet3Test
{
    class Program
    {
        static void Main()
        {
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                Console.WriteLine(np.cos(np.pi * 2));

                dynamic sin = np.sin;
                Console.WriteLine(sin(5));

                double c = np.cos(5) + sin(5);
                Console.WriteLine(c);

                dynamic a = np.array(new List<float> { 1, 2, 3 });
                Console.WriteLine(a.dtype);

                dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
                Console.WriteLine(b.dtype);

                Console.WriteLine(a * b);
                Console.WriteLine("Done");
            }
        }
    }
}
`

When I run my C# code, I got the above error.
I have tried to do the same as described in issue #1528
https://github.com/pythonnet/pythonnet/issues/1528
But I got the same error, the only difference is that I am using Python version 3.9.7, and I have no idea on which version of pythonnet I am installing. I run this command as Administrator in Windows 10:
C:\WINDOWS\system32>python -m pip install pythonnet

Please let me know if I have to install pythonnet first before I run my C# code, but if the python install pythonnet command is not correct, then which command I can use to install a new version of pythonnet, like the version: Version 3.0.0-preview2021-09-03
Thanks,

**Comment by lostmsu** [comment]
Read the error.
