### ISSUE TITLE
How to use this repo to call Python code for playing video?

### ISSUE THREAD

**Issue by zydjohnHotmail** [pythonnet/pythonnet#1576]
### Environment

-   Pythonnet version: 3.0.0-preview2021-09-03
-   Python version: 3.9.7
-   Operating System: Windows 10
-   .NET Runtime: .NET 5.0

### Details

-   Describe what you were trying to get done.

   Use python code to play a MP4 video.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
    
```python
    ret, frame = cap.read()
```

-   If there was a crash, please include the traceback here.
Python.Runtime.PythonException
  HResult=0x80131500
  Message=OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - mat is not a numerical tuple
>  - Expected Ptr<cv::cuda::GpuMat> for argument 'mat'
>  - Expected Ptr<cv::UMat> for argument 'mat'

  Source=Python.Runtime
  StackTrace:
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at PythoPlayVideo.Program.Python_Play_Video() in C:\PythonNet\PythoPlayVideo\PythoPlayVideo\Program.cs:line 17
   at PyReturnTransit1Result.Program.Main() in C:\PythonNet\PythoPlayVideo\PythoPlayVideo\Program.cs:line 26

Hello:
I have a simple python code to play video:

`import numpy as np
import cv2

cap = cv2.VideoCapture('C:Videos/1.mp4')

while(cap.isOpened()):
    ret, frame = cap.read()
    cv2.imshow('frame',frame)

cap.release()
cv2.destroyAllWindows()
`

But I can’t figure out how to use it in C#, I have the following C# code:
I installed pythonnet nuget verion: 3.0.0-preview2021-09-03
PM> Install-Package pythonnet -Version 3.0.0-preview2021-09-03 
The following is my C# code:

`using Python.Runtime;
using System;

namespace PythoPlayVideo
{
    class Program
    {
        private static void Python_Play_Video()
        {
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                dynamic cv2 = Py.Import("cv2");
                dynamic cap = cv2.VideoCapture("C:/Videos/1.mp4");
                while (cap.isOpened())
                {
                    var video_frame = cap.read();
                    cv2.imshow("frame", video_frame);
                }
                cap.release();
                cv2.destroyAllWindows();
            }
        }

        static void Main()
        {
            Python_Play_Video();
        }
    }
}
`

But when I run my C# code, I got the above errors.
I can understand that in Python, the code: cap.read() return a tuple, but in C#.  Visual Studio 2019 didn’t give you the option to return a tuple.
How I can fix this issue?
Thanks,

**Comment by filmor** [comment]
This is not a support forum.
