### ISSUE TITLE
Get Value Of An Enum

### ISSUE THREAD

**Issue by saroad2** [pythonnet/pythonnet#1585]
### Environment

-   Pythonnet version: latest
-   Python version: 3.9.4
-   Operating System: Windows
-   .NET Runtime:

### Details

-   Describe what you were trying to get done.

I would like to have the ability to extract the value of a .Net `Enum` via python. One can do that using `MyEnum.value__`, however it seems logical that you should do it using `int(MyEnum)`.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
import clr

clr.AddReference("System.Windows.Forms")

import System.Windows.Forms as WinForms

enum_value = WinForms.Keys.Control
print(f"{enum_value=}")
print(f"{enum_value.value__=}")
```

That prints:
```
enum_value=<System.Windows.Forms.Keys object at 0x000001C053E07580>
enum_value.value__=131072
```

-   If there was a crash, please include the traceback here.

No crash.

**Comment by filmor** [comment]
This is possible using codecs, though they are /really/ unergonomic so far when using them from Python:

     import Python.Runtime
     Python.Runtime.PyObjectConversions.RegisterEncoder(Python.Runtime.Codecs.EnumPyIntCodec.Instance)
     Python.Runtime.PyObjectConversions.RegisterDecoder(Python.Runtime.Codecs.EnumPyIntCodec.Instance)

The decoder is buggy right now (fix in #1621).

@lostmsu Do you have a proposal for a nice ergonomic Python API for this? Should we enable some encoders/decoders by default unless told otherwise?

**Comment by lostmsu** [comment]
I don't think enabling codecs by default is a good idea, unless they are 1:1 exact rountrippable mappings.

As for the more ergonomic Python APIs, somebody more proficient with Python should propose those.

**Comment by lostmsu** [comment]
As for the issue at hand, .NET enums should implement `__int__` or its C API alternative for `int(Keys.Control)` to work.

**Comment by filmor** [comment]
Isn't that something that we explicitly removed?

**Comment by lostmsu** [comment]
If I remember correctly, we removed the code, that converted any enum value to an integer when passed to Python by default. You could never previously get raw enum value in Python. So the corresponding type never had `__int__` implementation.

**Comment by saroad2** [comment]
So if I understand you correctly, we all agree that adding a default `__int__` method is a wise idea?

I would have implemented this ability myself, but I have zero knowledge in C#. Let me know if I can help you somehow make this ability happen.
