### ISSUE TITLE
Cannot create custom class that inherits from PyObject

### ISSUE THREAD

**Issue by rdaniels5** [pythonnet/pythonnet#1588]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.6
-   Operating System: Windows
-   .NET Runtime: 4.6

### Details

-   Describe what you were trying to get done.

    Create a custom class that inherits from Python.Runtime.PyObject

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```C#
    public MyClass : PyObject
    {
            public MyClass(PyObject pyObj) :
            base(pyObj.Handle)
        {
            InputObject = pyObj;
        }
    }
```

-   If there was a crash, please include the traceback here.

ERROR:   PluginManager: Exception.Message: 		Could not load file or assembly 'Python.Runtime, Version=2.5.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

I only get this error when I inherit from PyObject. If I inherit from object, it is fine.

**Comment by lostmsu** [comment]
Does not seem to be the problem of Python.NET
