### ISSUE TITLE
When encountering an uninstalled module, using the command ImportModule fails to return Null or throws an exception and has been waiting for a long time

### ISSUE THREAD

**Issue by AtlantisDe** [pythonnet/pythonnet#1612]
### Environment

-   Pythonnet version: pythonnet_netstandard_py37_win -Version 2.5.1
-   Python version:3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
-   Operating System:WIn 10
-   .NET Runtime:>net 4.8

### ImportModule

-   When encountering an uninstalled module, using the command ImportModule fails to return Null or throws an exception and has been waiting for a long time

```C#

  dynamic psutil = Python.Runtime.PythonEngine.ImportModule("sys");/*Module installed OK*/


  //here should return null or throw Exception, but it have not do it.
  dynamic uninstall = Python.Runtime.PythonEngine.ImportModule("uninstall"); /*still wait.....*/


```

-   that 's a bug ?

```python
   
```

**Comment by filmor** [comment]
The Python.NET version you are using is from a fork and not this project. Please see if you can reproduce the issue on the current master and provide a *complete* example.
