### ISSUE TITLE
Different result for `IEnumerable` between 2.5.2 and 3.0.0a1

### ISSUE THREAD

**Issue by LeeDongGeon1996** [pythonnet/pythonnet#1622]
### Environment

-   Pythonnet version: 2.5.2 and 3.0.0a1
-   Python version: 3.8
-   Operating System: MacOS Monterey
-   .NET Runtime: mono

### Details

There is a C# method which returns IEnumerable<MyClass>.

For example:
```python
import clr
clr.AddReference("mydll.dll")

from My.Mynamespace import MyMain

# GetEnumerable() returns IEnumerable<MyClass> from C#
result = MyMain.GetEnumerable()

print(type(result))
```

In pythonnet 2.5.2, the resuls was:
```
<class 'list'>
```

But, in pythonnet  3.0.0a1, the result is:
```python
<class 'System.Collections.Generic.IEnumerable[MyClass]'>
```

I don't know this is intended or not.
Can you let me know which way should I follow for the future version?

**Comment by filmor** [comment]
This is intended. We have removed the automatic conversion to lists because it create a lot of problems. The `IEnumerable` is still iterable, so you can just run `list(result)` to get a Python list back.

**Comment by lostmsu** [comment]
To be more specific, IEnumerable now implements `collections.abc.Iterable`, .NET lists implement `collections.abc.MutableSequence` etc

**Comment by LeeDongGeon1996** [comment]
Thank you both :)
