### ISSUE TITLE
Add Archlinux Dependencies

### ISSUE THREAD

**Issue by fischer-felix** [pythonnet/pythonnet#1625]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.9.9
-   Operating System: Arch Linux

### Details

I would suggest adding the arch packages `dotnet-host` and `dotnet-sdk` to the dependency list or inform the user if these are missing, as this was the case for me and it took me quite a long time to figure it out.

**Comment by filmor** [comment]
The need of `dotnet-sdk` for compiling is documented now. That you need a runtime (which should include `dotnet-host`) is not something that I think needs to be specifically documented.
