### ISSUE TITLE
Public classes are not importable from a DLL in a jupyter notebook

### ISSUE THREAD

**Issue by jamesdsmith99** [pythonnet/pythonnet#1626]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.8.12
-   Operating System: Windows 10 (Using Conda)
-   .NET Runtime: Core 4.8

### Details

Load in my class inside a jupyter notebook. However my classes are not accessible. These classes show up when i decompile my dll and they are importable when running the same code in command prompt.

```python
import clr
import sys

sys.path.append('D:\development\pythonnet')

clr.AddReference("MyDll")

from MyNamespace import MyClass # gives an import error

import MyNamespace

MyNamespace.__dict__
```

The `__dict__` for the namespace doesnt have any classes in its keys not even the `__class__` key that usally maps to the `CLR.ModuleObject` . The keys that are present are:

- `__name__`
- `__doc__`
- `__package__`
- `__loader__`
- `__spec__`
- `__file__`
- `__path__`

When i run the above code in command prompt i do not get an import error and the `__dict__` has the following keys:

- `__name__`
- `__file__`
- `__doc__`
- `__class__`
- `MyClass`

**Comment by jamesdsmith99** [comment]
Could this be due to the fact that `MyClass` does not explicitley implement a constructor?

**Comment by jamesdsmith99** [comment]
The `.csproj` file for the class library has the following settings:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

</Project>

```

**Comment by filmor** [comment]
Could you upload your whole test project somewhere?

**Comment by jamesdsmith99** [comment]
[ClassLibrary1.zip](https://github.com/pythonnet/pythonnet/files/7723443/ClassLibrary1.zip)

@filmor I have included my class library solution above.

**Comment by filmor** [comment]
This works just fine with the current master/alpha.

**Comment by jamesdsmith99** [comment]
It still is not working for me. Could i please ask for more information on your set up / how you are compiling the project, to see if i still get any issues?

**Comment by filmor** [comment]
You can install the current alpha with `pip install -U --pre pythonnet`.

**Comment by jamesdsmith99** [comment]
> You can install the current alpha with `pip install -U --pre pythonnet`.

@filmor I tried with alpha and it works when using standard Jupyter Notebook or Jupyter Lab. However I am still experiencing this behaviour from jupyter notebooks in Visual Studio Code.
