### ISSUE TITLE
CS0428 fasttext get word vector 

### ISSUE THREAD

**Issue by hobbitkrd** [pythonnet/pythonnet#1627]
### Environment

-   Pythonnet version: pythonnet_py39_win.2.5.2
-   Python version: 3.9
-   Operating System: Windows 10
-   .NET Runtime: VS19

### Details

-  I'm using the trained fasttext model and trying to get the vector values ​​for the sentence with the command WV.

  dynamic vecLoadSent  = model.wv(“my sent”);

-  When going through this stage, I get the following error in VisualStudio:

CS0428 C# Cannot convert method group to non-delegate type 'object'

**Comment by filmor** [comment]
This is not a support forum, in particular not for the concrete package you are using and also not for C# problems.
