### ISSUE TITLE
module clr has no attribute AddReferece

### ISSUE THREAD

**Issue by aden-collector** [pythonnet/pythonnet#1632]
### Environment

-   Pythonnet version: 3.0.0a1
-   Python version: 3.9.7
-   Operating System: Windows 11
-   .NET Runtime: 4.0.30319

### Details

-   When I run the following Python script:
import clr
print("imported pythonnet")
clr.AddReference("C:\\CallNetDllFromPython\\TestVBDll.dll")

I get the error:
module clr has no attribute AddReference

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by filmor** [comment]
This is not even close to being reproducible, sorry.

**Comment by sebgur** [comment]
Same problem.
* pythonnet=3.0.3
* Win11

Error generated just with code below

import clr

clr.AddReference("System.Windows.Forms")

**Comment by sebgur** [comment]
Resolved. For me it was happening when I was calling clr.AddReference from deeper in the tree of my python project. When I put the call at the root of the tree, it works.
