### ISSUE TITLE
src-folder missing in source archive on PyPI

### ISSUE THREAD

**Issue by m-rossi** [pythonnet/pythonnet#1633]
### Environment

-   Pythonnet version: 3.0.0a1
-   Python version: 3.8.12
-   Operating System: Windows/macOS/Linux
-   .NET Runtime: 5.0.12

### Details

I made some progress today with building [clr-loader](https://github.com/pythonnet/clr-loader) for conda-forge: https://github.com/conda-forge/staged-recipes/pull/17031 Although the recipe is not merged yet I tried to build pythonnet with it and failed quite early.  It seems like the [`src`](https://github.com/pythonnet/pythonnet/tree/master/src)-folder is not inside the source archive. Can you add it to the source archive for the next pre-release?

**Comment by filmor** [comment]
I have committed the missing file, could you verify locally whether this works for you? The `sdist` created with this file in place worked for me.

**Comment by m-rossi** [comment]
Yes, I created the `sdist` and the conda-package afterwards, thanks!
