### ISSUE TITLE
using String.format crashes in python

### ISSUE THREAD

**Issue by sekkit** [pythonnet/pythonnet#1641]
### Environment

-   Pythonnet version: 3.x
-   Python version: 3.8
-   Operating System:
-   .NET Runtime:

### Details
using 
`String.Format("x,y = {0},{1}", Screen.width, Screen.height)`

in python, this line crashes

**Comment by filmor** [comment]
Please provide a reproducible example and fill out the required environment information. Feel free to reopen once that's done.
