### ISSUE TITLE
Cannot convert 10 to System.Int32[] in Array[int](10)

### ISSUE THREAD

**Issue by retsyo** [pythonnet/pythonnet#1644]
### Environment

-   Pythonnet version:  2.5.1
-   Python version:  3.6.10
-   Operating System:  windows 10 64bits

### Details
[doc](http://pythonnet.github.io/) says
```python
from System import Array

myarray = Array[int](10))
```
can create Array. However
```python
>>> import clr
>>> clr.__version__
'2.5.1'
>>> from System import Array
>>> myarray = Array[int](10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot convert 10 to System.Int32[]
```

**Comment by retsyo** [comment]
well, https://stackoverflow.com/a/27990589/4692635 says "the expected argument isn't the size, but a Python list", so we should use
```python
myarray = Array[int]([10])
```

so
1. the docment on http://pythonnet.github.io/ should be revised
2. what is the way to create an array with given length?

thanks

**Comment by filmor** [comment]
This automatic conversion is not the case any more in the current master/alpha, please try to use the newer version. We will update the documentation as we get closer to the release.
