### ISSUE TITLE
NuGet package creation

### ISSUE THREAD

**Issue by AlexCatarino** [pythonnet/pythonnet#165]
In order to use Python for .NET in a .NET app, we need to put Python.Runtime.dll in the references of the Visual Studio project. Unfortunately, this task has to be done manually, because we get this dll via pip (or downloading and compiling from this GitHub repository).

It would be very helpful to [create and publish a NuGet package](https://docs.nuget.org/create/creating-and-publishing-a-package) for pythonnet. If a NuGet package is generated at the end of a successful build (as suggested in the previous link), it would be quite easy to maintain a updated NuGet package for pythonnet.

**Comment by denfromufa** [comment]
How about python version?

**Comment by AlexCatarino** [comment]
A NuGet package for every supported version like pip/wheels.

**Comment by denfromufa** [comment]
Where would the flag be set which version of pythonnet to get from Nuget?
Automagically detect system python or build flag like in pythonnet?

Note that there is limited chocolatey package for pythonnet.

How about clr.pyd?

**Comment by denfromufa** [comment]
It is possible to push to nuget directly from appveyor. @tonyroberts are you willing to set this up in virtual machine settings?

**Comment by tonyroberts** [comment]
@denfromufa the clr.pyd file is not needed for embedding python, only for calling .net from python, so no need for it to be in nuget. I don't know enough about how packages should be uploaded to nuget wrt different variants of the same version (eg pythonnet 2.1 would have different packages for each different python version). If you want to investigate further and make suggestions about how the appveyor build should be set up I'm happy to make the changes.

**Comment by dmitriyse** [comment]
Please check my alpha binary release. It can be packed as nuget in future. (https://github.com/dmitriyse/pythonnet/releases)

**Comment by denfromufa** [comment]
@dmitriyse IMO your bundle could be useful to @bc3tech for his chocolatey package, which is currently only limited to 32 bit python 2.7.

**Comment by denfromufa** [comment]
https://chocolatey.org/packages/pythonnet

**Comment by dmitriyse** [comment]
I released better implementation of Python.Runtime.dll loader. Feel free to check and use.
https://github.com/dmitriyse/pythonnet/releases/tag/v2.2.0-bin-beta

**Comment by dmitriyse** [comment]
Hi everybody. I started work that allows to separate  Python.Runtime.dll from python specific interop methods. This efforts will finally allows to load appropriate Python.Runtime.Interop-PyXX-UCS-X.dll by simply Assembly.LoadFromFile without any AssemblyResolve handling magic.
Please check this approach and advice me in any points (until is not too late).
https://github.com/dmitriyse/pythonnet/commit/c55f655d8217d3eaf59d8f9b99c34869b5f39098

**Comment by dmitriyse** [comment]
Separation completed! You can inspect how it's finally looks.  https://github.com/dmitriyse/pythonnet/commit/1ea3773a0433c142a1a955d28b95b9d098fa5e79

**Comment by vmuriart** [comment]
@dmitriyse did you mean only those specific commits are needed or all the commits upto those commits?

**Comment by dmitriyse** [comment]
This branch contains two significant changes: 1) Port to DotNetCore (with ability to build Mono compatible version through dotnet core compiler) 2) and then separation of logic and Python/Platform specific interops methods.

**Comment by dmitriyse** [comment]
I plat to debug dotnet core port for linux in the next month and some new build scripts that will helps to build nuget package. I can even built it with wide variety of Python/Platform support but have no environment and time to test it. If somebody spend time to adopt current (setup.py) build system for my new features, we will finally get cool nuget package that will works in any environment and in mono and dotnet core.

**Comment by dmitriyse** [comment]
I will merge soon environment detector from my previous binary distribution to this branch.

**Comment by vmuriart** [comment]
Looks like Dotnetcore is [migrating](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) back to `csproj` files from `xproj`. You have some code changes embedded with folder structure changes, making it a bit harder to see what all changed.

**Comment by denfromufa** [comment]
@vmuriart in nuget it is possible to provide `-version` flag to install specific version of the package. Here are the CPython 3.5+ versions provided by @zooba:

https://www.nuget.org/packages/python/3.5.2

So we can create the following pythonnet versions to match PyPI:

2.2.2-cp27-cp27m-win32.whl
2.2.2-cp27-cp27m-win_amd64
2.2.2-cp34-cp34m-win32
2.2.2-cp34-cp34m-win_amd64
2.2.2-cp35-cp35m-win32
2.2.2-cp35-cp35m-win_amd64
2.2.2-cp36-cp36m-win32
2.2.2-cp36-cp36m-win_amd64

**Comment by denfromufa** [comment]
@vmuriart I created a nuget package for Python.Runtime.csproj using the command-line tool:

`nuget pack Python.Runtime.csproj`

Here is the the output:

[pythonnet.2.3.0.nupkg.zip](https://github.com/pythonnet/pythonnet/files/837206/pythonnet.2.3.0.nupkg.zip)

I uploaded it to https://www.nuget.org/packages/pythonnet

Next step is figuring out multiple versions or tags like I suggested above.

**Comment by denfromufa** [comment]
ok, looks like nuget does not support building different versions of nuget packages for all build configurations that pythonnet has:

http://stackoverflow.com/questions/35895601/how-to-specify-different-nuget-package-versions-for-different-build-configuratio

So we have to keep 5*2*2=20 `.nuspec` files for all possible combinations of build configurations.

**Comment by vmuriart** [comment]
Nuget also enforces a certain version scheme so we couldn't (rather shouldn't) use the aforementioned versioning scheme. One of its pitfalls (look at the nuget python package as an example) is that it will always say there is an update version available if you are using `python27`. 

Another thing to consider is how the libraries that would use this nuget package expect it to work. Do they want to only work with a specific python version, or do they want them to work on whichever the end-user has installed. 

I like how `nunit` packages their nuget solution. Each version is compiled against multiple Net frameworks and all of them are included in the nuget package. Which version is to be used is specified on the project file.

**Comment by denfromufa** [comment]
@vmuriart nunit uses the standard mechanism in nuget for selecting the correct .NET Framework:

https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

This does apply to pythonnet and cannot be re-used. I'm open to alternative solutions, but if nothing comes, then I'll go ahead with the approach that MS did for Python installers in nuget - using versions. I'm fine with update notifications, since the user of nuget package is responsible for picking the correct version of pythonnet. It is nearly impossible to analyze the system for available python versions and pick the correct one from nuget, especially when multiple python version are installed.

We can experiment with a unified runtime approach in a package "pythonnetbin" later.

**Comment by dmitriyse** [comment]
> It is nearly impossible to analyze the system for available python versions and pick the correct one from nuget, especially when multiple python version are installed.

Actually we can rely on current Environment. Even if multiple pythons installed, only one is active from a command line.
I already have some implementation.
```CSharp
        private static string DetectRequiredPythonRuntimDll(out string os, out List<string> librariesPathElements)
        {
            string stdOut;
            string pythonInfoFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "python-info.tmp");

            if (0
                == Stdlib.system(
                    $@"python -c ""import sys; print(sys.version_info.major); print(sys.version_info.minor); import array; print(array.array('u').itemsize); import platform; print(platform.architecture()[0]); print(platform.architecture()[1]); import sysconfig; print(sysconfig.get_config_vars('WITH_PYMALLOC')); print(sysconfig.get_config_var('LIBPL'));print(sysconfig.get_config_var('LIBDIR'))"" > {pythonInfoFile}"))
            {
                if (File.Exists(pythonInfoFile))
                {
                    stdOut = File.ReadAllText(pythonInfoFile);

                    File.Delete(pythonInfoFile);
                }
                else
                {
                    throw new InvalidOperationException("Failed to execute python");
                }
            }
            else
            {
                throw new InvalidOperationException("Failed to execute python");
            }
            
            var result = NormalizeOutput(stdOut).Split('\n');
            int majorVersion;
            int minorVersion;
            int charSize;
            bool pyMalloc = false;

            if (result.Length >= 8)
            {
                if (int.TryParse(result[0], out majorVersion) && int.TryParse(result[1], out minorVersion)
                    && int.TryParse(result[2], out charSize))
                {
                }
                else
                {
                    throw new InvalidOperationException("Failed to extract information about python.");
                }

                if (result[3].Trim().Length != 5)
                {
                    throw new InvalidOperationException("Failed to extract information about python.");
                }
            }
            else
            {
                throw new InvalidOperationException("Failed to extract information about python.");
            }

            os = "elf";
            result[4] = result[4].Trim();

            if (result[4] == "WindowsPE")
            {
                os = "win";
            }
            else if (result[4] == "ELF")
            {
                os = "elf";
            }
            else if (result[4] == string.Empty)
            {
                os = "osx";
            }

            if (result[5] == "[1]")
            {
                pyMalloc = true;
            }

            string options = string.Empty;

            if (pyMalloc)
            {
                options += "m";
            }

            librariesPathElements = new List<string>();
            for (int i = 6; i < 8; i++)
            {
                var libPathElement = result[i].Trim();
                if (libPathElement != "None" && libPathElement != string.Empty)
                {
                    librariesPathElements.Add(libPathElement);
                }
            }

            string dllName = "Python.Runtime";
            dllName += "-" + os;
            dllName += "-" + result[3].Substring(0, 2);
            dllName += "-ucs" + charSize;

            dllName += "-" + result[0] + result[1] + options;

            dllName += ".dll";
            return dllName;
        }
```

**Comment by dmitriyse** [comment]
Full solution can be inspected here https://github.com/dmitriyse/pythonnet/tree/v2.2.0-bin-RC2

**Comment by dmitriyse** [comment]
This is dead-end branch. New code should not rely on AssemblyResolve+= ... solutions.
If we need dynamic loading, than we needs to choose  interop code splitting approach

**Comment by vmuriart** [comment]
I prefer the interop splitting method, as it would also make it easy to allow `pypy` to be supported. For now, we could release multiple packages each named for the python version they support and then the version number is pythonnet's actual version number.

**Comment by denfromufa** [comment]
@vmuriart now I agree with you, e.g. boost python uses similar convention:

https://www.nuget.org/packages?q=boost_python

**Comment by denfromufa** [comment]
Ok, I removed previous package pythonnet and updated packages both ways, the binaries include x64 & x86:

https://www.nuget.org/packages/pythonnet/2.3.0-py27-dotnet
https://www.nuget.org/packages/pythonnet/2.3.0-py35-dotnet

https://www.nuget.org/packages/pythonnet_py27_dotnet/
https://www.nuget.org/packages/pythonnet_py35_dotnet/

**Comment by mphielipp** [comment]
Hi, I install this package. But when I run the project I get a runtime error . I have a Anaconda Python 3.5.2 64 bits install. I use the Nuget PAckage 3.5. I have tried to run it with x86, Any CPU, amd x64. Any suggestions?

Now I'm running x86. Crash in this line Py.GIL().
There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Python.Runtime, Version=2.3.0.0, Culture=neutral, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	PythonNet2

**Comment by mphielipp** [comment]
I installed it using the "MAnage Nuget Package" option in Visual Studio 2005.

**Comment by mphielipp** [comment]
I changed the "Target Platform Option" in project settings to x86. But I still get this runtime error in the same line:

An unhandled exception of type 'System.BadImageFormatException' occurred in Python.Runtime.dll

Additional information: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

**Comment by denfromufa** [comment]
@mphielipp i deleted your 4 messages here and moved them to a separate issue:

https://github.com/pythonnet/pythonnet/issues/472

**Comment by denfromufa** [comment]
Apparently there is outstanding issue in nuget with not handling architectures, hence this has to be handled manually in the next release:

https://github.com/pythonnet/pythonnet/issues/472#issuecomment-304121261

**Comment by HarelM** [comment]
Any chance to integrate #875 PR? It would be extremely useful to be able to download a NuGet package from appveyor and use it on our local NuGet repository, whether you choose to place it in the global NuGet or not.
