### ISSUE TITLE
Import Mathplotlib fails

### ISSUE THREAD

**Issue by AndBurns** [pythonnet/pythonnet#1675]
### Environment

-   Pythonnet version: 3.0.0-preview2022-01-3
-   Python version: Anaconda 3.9
-   Operating System: Windows 10
-   .NET Runtime:.net 5.0

### Details

-   Describe what you were trying to get done.
Developing a vb dotnet frontend for a python project.
Import of mathplotlib fails with message 'DLL load failed while importing _imaging: The specified module could not be found.'

Occurs with 
Py.import("matplotlib")
and running a script that includes 

import matplotlib

Load Mathplotlib
    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

vb.net
```
Private Sub Test_Click(sender As Object, e As EventArgs) Handles BtnModelFlow.Click
        Using (Py.GIL())
            Dim scope = Py.CreateScope
            TB_Output.Text += vbCrLf + "Solving model"

            Dim plt = Py.Import("matplotlib")  'Fails here
            TB_Output.Text += vbCrLf + "Modelflow test completed with Status=" + sVar

        End Using
    End Sub
```
Also fails when calling a script that include import matplotlib
```
Private Sub Test2_Click(sender As Object, e As EventArgs) Handles BtnModelFlow.Click
        Using (Py.GIL())
            Dim scope = Py.CreateScope
            TB_Output.Text += vbCrLf + "Solving model"
            Dim sCode as string = File.ReadAllText("a:\modelflow\py\TestMatPlotlib.py")
            Dim res As PyObject = scope.Exec(sCode)
            TB_Output.Text += vbCrLf + "Finished"
            Dim sVar As String = scope.Get("Status").ToString
            TB_Output.Text += vbCrLf + "Modelflow test completed with Status=" + sVar

        End Using
    End Sub
```
Error returned: : 'DLL load failed while importing _imaging: The specified module could not be found.'

***python***
**Body of TestMatplotlib.py**
```
import matplotlib
Status="Completed"
print(Status)
```

Runs fine from Spyder

```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by filmor** [comment]
This is not a support forum. The error shows very clearly that something could not be loaded from within Python (probably because `PATH` is not set correctly). You'd see the same error if you were embedding in C.

**Comment by AndBurns** [comment]
Thanks for your response.  Two follow ups: 1) is there a support forum; and 2) how could someone contribute to the documentation for this project, which at least as concerns embedding pythonnet in c# or vb programs seems to be quite sparse.

**Comment by filmor** [comment]
There is a mailing list and stackoverflow, you can contribute documentation by editing the Wiki or creating a documentation PR directly on the project.

**Comment by disouzam** [comment]
@filmor : How can I get access to the mailing list?

**Comment by disouzam** [comment]
@filmor : Don't mind! I managed to find the link in README.
