### ISSUE TITLE
Multiple Python interpreters within a process?

### ISSUE THREAD

**Issue by ashelemba** [pythonnet/pythonnet#1676]
Because of GIL the python interpreter always works single-threaded (only 1 CPU core at a time). But is it possible to operate several instances of interpretators to be able to parallelize work and utilize all CPU cores? Maybe there are already some code implementations in c# which we can use?

**Comment by filmor** [comment]
CPython supports multiple interpreters in a limited fashion via https://docs.python.org/3/c-api/init.html#sub-interpreter-support. There is no implementation of this so far in Python.NET, https://github.com/pythonnet/pythonnet/pull/1673 is apparently exploring this, though.

**Comment by lostmsu** [comment]
@filmor @ashelemba  I am actually not sure that subinterpreters have separate GIL, so even if we used Python C API linked above it would still have the global lock.
