### ISSUE TITLE
`foreach` over dynamic `PyObject`

### ISSUE THREAD

**Issue by Shpendicus** [pythonnet/pythonnet#1680]
### Environment

-   Pythonnet version: 3.0.0
-   Python version: 3.9.5
-   Operating System: windows 10
-   .NET Runtime: .NET 6

### Details

-   Describe what you were trying to get done.
-   foreach  a tuple at runtime via "dynamic" keyword 

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example] (http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
  `
    dynamic sys = Py.Import("sys");
    dynamic path2 = sys.path;
    
    foreach (PyObject item in path2)
    {
        Console.WriteLine(item);
    }
`

-   If there was a crash, please include the traceback here.

**Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: "Cannot implicitly convert type 'Python.Runtime.PyObject' to 'System.Collections.IEnumerable'. An explicit conversion exists (are you missing a cast?)"**

**Comment by lostmsu** [comment]
You can do `item in new PyTuple(path2)`, or `item in PyIter.GetIter(path2)`.

**Comment by Shpendicus** [comment]
@lostmsu 
thx for the quick response :)

I have to add tho, that the 1.) approach works good!  (item in new PyTuple(path2))
The 2.) approach fails aswell, with the same exception as in this thread! (PyIter.GetIter(path2))
