### ISSUE TITLE
Python debugging in multithreaded C# application 

### ISSUE THREAD

**Issue by jaqueamo** [pythonnet/pythonnet#1681]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.8.10
-   Operating System: Windows 10
-   .NET Runtime: 4.8

### Details

I have used the methods 2 and 3 using Visual Studio Code to debug a python file as described here:
[Various debugging scenarios of embedded CPython](https://github.com/pythonnet/pythonnet/wiki/Various-debugging-scenarios-of-embedded-CPython)
This is working fine as long as I run the Python script in the C# main thread. 
If I start the script from an other thread the breakpoints are only hit the first time. 
If the script is run the second time the breakpoints are not hit anymore but console outputs in VS Code are still working. 

```
var t = new Thread(Run);
t.Start();

private static void Run()
{
    // Breakpoints working
    ExecuteScript();

    // Breakpoints not working
    ExecuteScript();
}

private static void ExecuteScript()
{
    using (Py.GIL())
    {
        PyScope scope = Py.CreateScope();
        dynamic pym = scope.Import("mixedmode");
        pym.pyfunc();
    }
}
```

Any idea what to do to resolve the problem ?

**Comment by filmor** [comment]
This is not a support forum.

Python caches imports, so most of the script will not run a second time and only `pyfunc` will be executed. It could be that this results in the debugger losing connection. I'm not sure why it would make a difference depending on what thread you run on.

**Comment by jaqueamo** [comment]
Just in case someone else has the same problem. 
To make it work you have to import debugpy and call 

```
scope.Exec("debugpy.debug_this_thread()");
```

everytime you enter `Py.GIL()` on a other thread than the main thead.
