### ISSUE TITLE
Install on Python 3.4

### ISSUE THREAD

**Issue by arita291** [pythonnet/pythonnet#173]
Hi,

Tried to install from Develop / Release version on WinPython 3.4 (Python 3.4) and I had this message:

!pip install pythonnet
Collecting pythonnet
  Downloading pythonnet-2.0.0.tar.gz (647kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "F:\usertemp\pip-build-og_pcuji\pythonnet\setup.py", line 79, in <module>
        _xbuild = "\"%s\"" % _find_msbuild_tool("msbuild.exe")
      File "F:\usertemp\pip-build-og_pcuji\pythonnet\setup.py", line 27, in _find_msbuild_tool
        import _winreg
    ImportError: No module named '_winreg'

Is it a way to install on Python 3.4 ?
(without doing the renaming of winreg manually) ?

Thanks very much.

**Comment by denfromufa** [comment]
Can you try `pip install pythonnet --pre`?

Also have a look at this wiki:

https://github.com/denfromufa/pythonnet/wiki/Troubleshooting-FAQ

**Comment by arita291** [comment]
Yes, it worked.
Thank you very much.


On 01 Mar 2016, at 05:53, denfromufa <notifications@github.com> wrote:

Can you try `pip install pythonnet --pre`?

Also have a look at this wiki:

https://github.com/denfromufa/pythonnet/wiki/Troubleshooting-FAQ


On Monday, February 29, 2016, arita291 <notifications@github.com> wrote:

> Hi,
>
> Tried to install from Develop / Release version on WinPython 3.4 (Python
> 3.4) and I had this message:
>
> !pip install pythonnet
> Collecting pythonnet
> Downloading pythonnet-2.0.0.tar.gz (647kB)
> Complete output from command python setup.py egg_info:
> Traceback (most recent call last):
> File "", line 20, in
> File "F:\usertemp\pip-build-og_pcuji\pythonnet\setup.py", line 79, in
> _xbuild = "\"%s\"" % _find_msbuild_tool("msbuild.exe")
> File "F:\usertemp\pip-build-og_pcuji\pythonnet\setup.py", line 27, in
> _find_msbuild_tool
> import _winreg
> ImportError: No module named '_winreg'
>
> Is it a way to install on Python 3.4 ?
>
> ―
> Reply to this email directly or view it on GitHub
> <https://github.com/pythonnet/pythonnet/issues/173>.
>
―

**Comment by stonebig** [comment]
would it be possible to release/tag a dev2 soon ?

**Comment by denfromufa** [comment]
@stonebig this is totally up to @tonyroberts when to release on pypi.

But you get now wheels built on appveyor for every commit, see artifacts
tab.

**Comment by stonebig** [comment]
hi @denfromufa,

Thanks, that's an option I didn't know.

**Comment by vmuriart** [comment]
appveyor does the Windows builds and keeps the wheels under artifacts. Travis-CI could do the same thing, but it needs a destination to upload the Linux wheels to. 
I'm not very familiar with the compatibility between different linux versions, but I feel the linux wheel wouldn't be as effective.

**Comment by vmuriart** [comment]
@arita291 can this be closed?

**Comment by arita291** [comment]
Yes, thank you.
M

On 12 Mar 2016, at 14:04, Vik <notifications@github.com> wrote:

@arita291 can this be closed?

―
