### ISSUE TITLE
System.AccessViolationException for latest verion (3.0.0-preview2022-04-03)

### ISSUE THREAD

**Issue by zydjohnHotmail** [pythonnet/pythonnet#1748]
### Environment

-   Pythonnet version: 3.0.0-preview2022-04-03
-   Python version: 3.9.7
-   Operating System: Windows 10 (version 21H2)
-   .NET Runtime: 5.0

### Details

-   Describe what you were trying to get done.

    Run the example C# program.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```csharp
using Python.Runtime;
using System;
using System.Collections.Generic;

namespace PythonCondaEnvironment
{
    internal class Program
    {
        static void Main(string[] args)
        { 
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                Console.WriteLine(np.cos(np.pi * 2));

                dynamic sin = np.sin;
                Console.WriteLine(sin(5));

                double c = (double)(np.cos(5) + sin(5));
                Console.WriteLine(c);

                dynamic a = np.array(new List<float> { 1, 2, 3 });
                Console.WriteLine(a.dtype);

                dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
                Console.WriteLine(b.dtype);

                Console.WriteLine(a * b);
                Console.ReadKey();
            }
        }
    }
}
```

-   If there was a crash, please include the traceback here.

```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

Note: the above code works for last version: 3.0.0-preview2022-03-03, but for this version: 3.0.0-preview2022-04-03, it is not working any more!

**Comment by 731315163** [comment]
win10 
python 3.10
version 3.0.0-preview2022-04-03
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.PyGILState_Ensure()
   at Python.Runtime.PythonEngine.AcquireLock()
   at Python.Runtime.Py+GILState..ctor()
   at Python.Runtime.Py.GIL()
   at Program.<<Main>$>g__main|0_0()
   at Program.<Main>$(System.String[])

**Comment by filmor** [comment]
@zydjohnHotmail You do no initialisation at all. Please add a `PythonEngine.Initialize()` (as documented).

**Comment by zydjohnHotmail** [comment]
Hello:
From the readme part of the repo, I can't find document for this: PythonEngine.Initialize(), give me the link for document this.
By the way, there is no issue for last version: 3.0.0-preview2022-03-03, but this latest version: 3.0.0-preview2022-04-03 has issue.
Is there any difference between the two?

**Comment by 731315163** [comment]
@zydjohnHotmail `/https://stackoverflow.com/questions/69339974/python-net-pythonengine-initialize-crashes-application-without-throwing-except
using Python.Runtime;
using System.Text;
using Serilog;
public class PythonEngineInit
{
    public string PythonHome = @"C:\Program Files\Python310";
    public string PythonDLL = "python310.dll";
    public string? ScriptsDir = @"C:\project\python\CreateFontPage\src\Lib\site-packages";
    public string[] PythonPath ={
        "DLLs",
        "libs",
        "Lib\\site-packages",
        "Lib/site-packages/win32",
        "Lib/site-packages/win32/lib",
        "Lib/site-packages/Pythonwin"
    };

    public string ProgramName = "zt";

    public string GetPythonHome() { return PythonHome; }
    public string GetPythonDLL() { return Path.Combine(PythonHome, PythonDLL); }
    public string GetPythonPath()
    {
        var sb = new StringBuilder();
        foreach (var p in PythonPath)
        {
            var lib = Path.Combine(GetPythonHome(), p);
            if (Directory.Exists(lib))
            {
                sb.Append(lib);
                sb.Append(';');
            }
        }
        if (!String.IsNullOrEmpty(ScriptsDir))
        {
            sb.Append(ScriptsDir);
            sb.Append(';');
        }
        return sb.ToString();
    }

    public string GetProgramName() { return ProgramName; }
    public void Initialize(ILogger logger)
    {

        // will be different on linux/mac


        try
        {
            Runtime.PythonDLL = GetPythonDLL();
            PythonEngine.PythonHome = GetPythonHome();

            PythonEngine.PythonPath = GetPythonPath();

            PythonEngine.ProgramName = GetProgramName();
            PythonEngine.Initialize();
            //   PythonEngine.BeginAllowThreads();

            logger.Information("Python Version: {v}, {dll}", PythonEngine.Version.Trim(), Runtime.PythonDLL);
            logger.Information("Python Home: {home}", PythonEngine.PythonHome);
            logger.Information("Python Path: {path}", PythonEngine.PythonPath);

        }
        catch (System.TypeInitializationException e)
        {
            throw new Exception($"Unable to load Python, dll={Runtime.PythonDLL}", e);
        }
        catch (Exception e)
        {
            throw new Exception($"Python initialization Exception, {e.Message}", e);
        }
    }
}`

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply.  
I figured it out:
Add PYTHONHOME in user variable, and Add PYTHONPATH to system variable.
Then add: PythonEngine.Initialize();
Before this statment:
using (Py.GIL())
Then run my code, it works with latest version: 
3.0.0-preview2022-04-03.
I think the document is not well written for this issue.
By the way, I didn't try to use Python 3.10 yet.  As far as I know, there are many package not working in Python 3.10 yet, so using the latest version of Python, you may have risk not able to run many programs.
But thanks for your help.

**Comment by Xentric925** [comment]
> Hello: Thanks for your reply. I figured it out: Add PYTHONHOME in user variable, and Add PYTHONPATH to system variable. Then add: PythonEngine.Initialize(); Before this statment: using (Py.GIL()) Then run my code, it works with latest version: 3.0.0-preview2022-04-03. I think the document is not well written for this issue. By the way, I didn't try to use Python 3.10 yet. As far as I know, there are many package not working in Python 3.10 yet, so using the latest version of Python, you may have risk not able to run many programs. But thanks for your help.

what should the variable value be for PYTHONHOME and PYTHONPATH?

**Comment by AncientTree** [comment]
> You must set Runtime.PythonDLL property or PYTHONNET_PYDLL environment variable starting with version 3.0, otherwise you will receive BadPythonDllException (internal, derived from MissingMethodException) upon calling Initialize. Typical values are python38.dll (Windows), libpython3.8.dylib (Mac), libpython3.8.so (most other Unix-like operating systems).
Then call PythonEngine.Initialize(). If you plan to use Python objects from multiple threads, also call PythonEngine.BeginAllowThreads().

I have done everything described above, but program always exit without any visible error message when call `PythonEngine.Initialize();` 

If I remove `PythonEngine.Initialize();` It tell `Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

When I change `PYTHONNET_PYDLL ` value form `E:\ProgramData\Anaconda3\python38.dll` to `python38.dll`, nothing diferent.

Any idea from expert? @filmor

**Comment by AncientTree** [comment]
Why doesn't the documentation clearly state whether the environment variable requires the full absolute path to the DLL file or the file name? Of course, this question only matters if neither is available to someone
