### ISSUE TITLE
DeprecationWarning when importing `clr`

### ISSUE THREAD

**Issue by freakboy3742** [pythonnet/pythonnet#1752]
### Environment

-   Pythonnet version: 3.0.0alpha2
-   Python version: 3.10
-   Operating System: Windows10
-   .NET Runtime: 6.0.201

### Details

Running non-trivial projects that use python.NET raises a DeprecationWarning on the first import of the `clr` module:

```
C:\Users\brendan\AppData\Local\Programs\Python\Python39\lib\site-packages\clr_loader\wrappers.py:20: DeprecationWarning:
 builtin type GC Offset Base has no __module__ attribute
  return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
```

I'm seeing this using the Winforms backend of [Toga](https://github.com/beeware/toga); it's 100% reproducible on any project using toga 0.3.0.dev32. 

It's only a warning, and it doesn't actually prevent anything from working - the app continues to operate as expected . However, this message:
1) suggests that there is something that might break in the future, and
2) has been reported multiple times by users who are deeply concerned that they've done something wrong.

To reproduce:

In a clean VM, `pip install --pre toga`, then put the following in `app.py`:
```python
import toga

def build(app):
    return toga.Box()

if __name__ == '__main__':
    toga.App('First App', 'org.beeware.helloworld', startup=build).main_loop()
```

then run `python app.py`.

I haven't been able to reproduce the issue with a "purely Python.NET" script (e.g., one of the demos in the Python.NET repo). The reference to GC suggests that it might require a larger program to trigger the problem; a bare-bones Toga app appears to hit that threshold. 

I have been able to confirm that the warning is emitted when `import clr` is executed for the first time (src/winforms/toga_winforms/libs/winforms.py).

**Comment by filmor** [comment]
This should be fixed on master since https://github.com/pythonnet/pythonnet/commit/dfeb354de6c396afe3b44d4905c10fbc6445531e, can you try that?

**Comment by freakboy3742** [comment]
Can confirm the message is gone as of dfeb354.
