### ISSUE TITLE
Allow configuring the clr-loader runtime to use via environment variables

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#1759]
Configuring the runtime has essentially three common cases:

1. .NET Framework
2. Mono with a globally accessible `libmono.so`
3. .NET Core

To make this easier to use (and hide `clr_loader` a bit), I propose that we introduce a new environment variable `PYTHONNET_RUNTIME` that configures what happens if one just imports `clr`, and a corresponding `pythonnet.configure` function with some simple parameters.

**Comment by lostmsu** [comment]
Since this is not a breaking change, does 3.0.0 need to depend on it?

**Comment by filmor** [comment]
It's not something that should prevent us from releasing RC1. I'll try to prepare a PR for today.
