### ISSUE TITLE
Embedding tests randomly hang in MacOS

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1766]
Example: https://github.com/pythonnet/pythonnet/runs/5978191426?check_suite_focus=true

Appears to have started with https://github.com/pythonnet/pythonnet/pull/1712

**Comment by filmor** [comment]
Seems to always hang after the `TestEval` or `TestExec` tests.

**Comment by lostmsu** [comment]
@filmor do you have a MacOS machine to investigate this?
