### ISSUE TITLE
decimal default parameter not being taken into account

### ISSUE THREAD

**Issue by sensokame** [pythonnet/pythonnet#1769]
### Environment

-   Pythonnet version: 3.0.0a2
-   Python version: 3.10.4
-   Operating System: Windows
-   .NET Runtime: 5.0.1

### Details

-   use a method with default decimal parameter from python. I created a method with optional parameters, one of which is a decimal parameter "decimal sampling_time = 1", then in python I tried using this method with the default parameter, however, the value of the default parameter was 0 instead of the 1 that I set.
Note: the other default parameters worked fine (uint, and int parameters)

**Comment by filmor** [comment]
I can reproduce this, will have a look.
