### ISSUE TITLE
how to release already loaded C# dll file?

### ISSUE THREAD

**Issue by zhenghan008** [pythonnet/pythonnet#177]
Hi!
  I use  clr.FindAssembly('ClassLibrary1.dll') already loaded the C# dll. but when I remove the  already loaded C# dll file just like ClassLibrary1.dll and rebuild the dll file(named ClassLibrary1.dll but the method is different).then I reload the dll file clr.FindAssembly('ClassLibrary1.dll'),but I can't read the method in the rebuild dll,the method is in the  dll file that I  already remove.so how to release already loaded C# dll file and I can reload the new c# dll?

**Comment by denfromufa** [comment]
Can you just restart your python interpreter?

**Comment by zhenghan008** [comment]
@denfromufa  thank you! but  it is no effect that I restart the computer ,I can load the C# dll that I already remove it.

**Comment by denfromufa** [comment]
Can you check whether dll is loaded from another location, maybe even GAC?

Try clr.FindAssembly(your_assembly_name)

BTW, you do NOT need to restart your computer for this.

**Comment by zhenghan008** [comment]
@denfromufa ,thank you ! I Put all the dll files in the same folder and use sys.path.append(the folder) to load the dll file.

**Comment by zhenghan008** [comment]
the clr has  no method to release already loaded C# dll file? @denfromufa

**Comment by denfromufa** [comment]
Even if it had, this would be very fragile world.

**Comment by zhenghan008** [comment]
@denfromufa ，oh！no.I dont know how to solve the problem ?

**Comment by filmor** [comment]
Just to get this straight, yes, Python.NET does currently not allow you to unload an Assembly that was imported as module. However, if restarting the interpreter is viable for you then this is not your problem. Have you checked where the Assembly was loaded from? Should be something like this:

   asm = clr.AddReference("ClassBase1.dll")
   print(asm.Location)

**Comment by zhenghan008** [comment]
@filmor thank you!but I  can't use clr.AddReference("ClassBase1.dll"),it raise  FileNotFoundException.can you show me how to let it work?does it has the attribute of Location?

**Comment by zhenghan008** [comment]
thank you! @denfromufa  @filmor I solve the problem!!

**Comment by denfromufa** [comment]
@zhenghan008 please close this issue if everything is working
