### ISSUE TITLE
Automatically convert python decimal to System.Decimal

### ISSUE THREAD

**Issue by sensokame** [pythonnet/pythonnet#1775]
### Environment

-   Pythonnet version: 3.0.0a2
-   Python version: 3.10.4
-   Operating System: Windows
-   .NET Runtime: 5.0.1

Details

-   use a method with decimal parameter from python. pass a python decimal to the parameter. an exception would raise (Cannot Convert from decimal to System.Decimal)
-    It would be nice to automatically convert between python decimal and system decimal (it would be nice to automatically convert between python numbers to system decimal as well, but starting with python decimal is enough)

**Comment by filmor** [comment]
This is not going to happen in the core. There is the codec system that allows users to implement this themselves, and I think we'd be open to accepting a PR for a decimal codec that does what you are suggesting, but it won't be active by default.

**Comment by lostmsu** [comment]
@sensokame to clarify a bit more: it can't be converted by default because it might cause data loss.

**Comment by kayoub5** [comment]
@lostmsu both python Decimal and C# Decimal are lossless
From .NET https://docs.microsoft.com/en-us/dotnet/api/system.decimal?view=net-6.0
> The [Decimal](https://docs.microsoft.com/en-us/dotnet/api/system.decimal?view=net-6.0) value type represents decimal numbers ranging from positive 79,228,162,514,264,337,593,543,950,335 to negative 79,228,162,514,264,337,593,543,950,335. The default value of a Decimal is 0. The [Decimal](https://docs.microsoft.com/en-us/dotnet/api/system.decimal?view=net-6.0) value type is appropriate for financial calculations that require **large numbers of significant integral and fractional digits and no round-off errors.**

From Python 
> The decimal module was designed to support “without prejudice, both exact unrounded decimal arithmetic (sometimes called fixed-point arithmetic) and rounded floating-point arithmetic.”

So I don't get what precision loss you are talking about, could you elaborate?

**Comment by lostmsu** [comment]
@kayoub5 C# decimal has a limited precision while Python decimal precision is unlimited. Therefore casting a Python decimal to .NET decimal is a potential loss of data.

**Comment by kayoub5** [comment]
> @kayoub5 C# decimal has a limited precision while Python decimal precision is unlimited. Therefore casting a Python decimal to .NET decimal is a potential loss of data.

The same logic should apply to Python `int`  and .NET `Int64`, what's the current behavior for that?

**Comment by lostmsu** [comment]
@kayoub5 `OverflowException` (I believe) is raised when Python `int` is outside of the target .NET integer type. So you either get precise conversion or an error.

**Comment by kayoub5** [comment]
@lostmsu Can we apply the same logic for decimal types as well?

**Comment by filmor** [comment]
A PR for this (adding a codec) would be appreciated, but we are not going to enable any conversion by default that requires an `import` of anything but `sys` and `builtins`.

**Comment by lostmsu** [comment]
It is not as simple, as the issue is not about the max value `System.Decimal` can represent, but about the highest precision it can handle without losing significant digits.
