### ISSUE TITLE
During run demo example, some error occured.

### ISSUE THREAD

**Issue by kelvinwang139** [pythonnet/pythonnet#1784]
### Environment

-   Pythonnet version: 3.0.0.dev1
-   Python version:3.9.12
-   Operating System:Windows 10
-   .NET Runtime:vs2015_runtime:14.27.29016

### Details

-   Describe what you were trying to get done.

    During try demo example error occured.

**D:\program\Anaconda3\envs\pythonnet\python.exe D:/workspace/ai/pythonnet/demo/helloform.py**
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
Traceback (most recent call last):
  File "D:\workspace\ai\pythonnet\demo\helloform.py", line 63, in <module>
    main()
  File "D:\workspace\ai\pythonnet\demo\helloform.py", line 55, in main
    form = HelloApp()
  File "D:\workspace\ai\pythonnet\demo\helloform.py", line 17, in __init__
    self.Text = "Hello World From Python"
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 System.Windows.Forms.Control.get_CacheTextInternal()
   在 System.Windows.Forms.Control.get_Text()
   在 System.Windows.Forms.Control.set_Text(String value)

Process finished with exit code 1

D:\program\Anaconda3\envs\pythonnet\python.exe D:/workspace/ai/pythonnet/demo/splitter.py
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
Traceback (most recent call last):
  File "D:\workspace\ai\pythonnet\demo\splitter.py", line 93, in <module>
    main()
  File "D:\workspace\ai\pythonnet\demo\splitter.py", line 87, in main
    app = Splitter()
  File "D:\workspace\ai\pythonnet\demo\splitter.py", line 77, in __init__
    self.Controls.Add(item)
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 System.Windows.Forms.Control.get_Controls()

Process finished with exit code 1

D:\program\Anaconda3\envs\pythonnet\python.exe D:/workspace/ai/pythonnet/demo/wordpad.py

δ��������쳣:  Python.Runtime.PythonException: 'int' value cannot be converted to System.Boolean
   �� Python.Runtime.PythonException.ThrowLastAsClrException()
   �� Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   �� Python.Runtime.Dispatcher.Dispatch(Object[] args)
   �� __System_Threading_ThreadStartDispatcher.Invoke()
   �� System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   �� System.Threading.ThreadHelper.ThreadStart()

Process finished with exit code -532462766

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by filmor** [comment]
Demo scripts should be fixed now.

**Comment by zhang-xuting** [comment]
@kelvinwang139 hi, have you solved this problem？ How to solve it? 我遇到和您一样的问题了，救命啊，大哥
