### ISSUE TITLE
Incorrect marshalling of string in Py_SetPythonHome

### ISSUE THREAD

**Issue by leomeuk** [pythonnet/pythonnet#179]
I noticed that when `PythonEngine.PythonHome` was set and a subsequent `Initialize()` call was made my .Net application would close unexpectedly.

It looks like the call to `Py_SetPythonHome` made in runtime.cs is implicitly marshalling the string to a char array for the unmanaged code. My suspicion is that the Python sourcecode is keeping a record of the pointer rather than making a copy of the data. The managed runtime will free the memory allocated to char array as soon as the function finishes executing leaving a dangling pointer. This then leads to the unexpected `Initialize()` behaviour.

```
[DllImport(Runtime.dll, CallingConvention = CallingConvention.Cdecl,
    ExactSpelling = true, CharSet = CharSet.Ansi)]
internal unsafe static extern void
Py_SetPythonHome(string home);
```

The solution appears to be to explicitly marshal the string and hang onto the pointer until it is no longer needed, i.e.

```
[DllImport(Runtime.dll, CallingConvention = CallingConvention.Cdecl,
     ExactSpelling = true, CharSet = CharSet.Ansi)]
internal unsafe static extern void
Py_SetPythonHome(IntPtr home);
```

```
IntPtr str = Marshal.StringToHGlobalAnsi(@"C:\Python27");
Py_SetPythonHome(str);
// do stuff
Marshal.FreeHGlobal(str);
```

Running Win7, .Net4.5 and Python 2.7.11.

**Comment by denfromufa** [comment]
@leomeuk looks like you are correct - I tested this crash in `csi`:

```
Microsoft (R) Roslyn C# Compiler version 1.1.0.51204
Loading context from 'CSharpInteractive.rsp'.
Type "#help" for more information.
> #r "C:\Python\Python27\Lib\site-packages\Python.Runtime.dll"
> using Python.Runtime;
> PythonEngine.PythonHome = @"C:\Python\Python27";
> PythonEngine.Initialize();
> PythonEngine.PythonHome
Hosting process exited with exit code -1073740940.
Loading context from 'CSharpInteractive.rsp'.
```

**Comment by denfromufa** [comment]
@leomeuk can you submit a patch and corresponding unit test?

**Comment by leomeuk** [comment]
@denfromufa I'll look at doing so this weekend.
