### ISSUE TITLE
AccessViolationException Py.GIL() on Windows .NET 6 

### ISSUE THREAD

**Issue by jonaumann** [pythonnet/pythonnet#1806]
### Environment

-   Pythonnet version: 3.0.0-preview2022-04-11
-   Python version: 3.10.4
-   Operating System: Windows 10 or 11
-   .NET Runtime: 6.0

### Details

-   Describe what you were trying to get done.

   Try the simplest form of running python in .net described in pythonnet readme

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```
   Runtime.PythonDLL = "C:/Programs/Python/Python310/python310.dll";
   using (Py.GIL())
    {
      Console.ReadKey();
    }
```

-   If there was a crash, please include the traceback here.

``` 
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.PyGILState_Ensure()
   at Python.Runtime.PythonEngine.AcquireLock()
   at Python.Runtime.Py+GILState..ctor()
   at Python.Runtime.Py.GIL()
```

**Comment by jonaumann** [comment]
I could fix the AccessViolationException by adding: 
````
PythonEngine.Initialize();
````
This was not documented in the README. 
Now I get the error: Python.Runtime.PythonException: "No module named 'numpy'"
when using the code: 
````
dynamic np = Py.Import("numpy");
````
But numpy is installed and I can import it from python. 
The PythonEngine.PythonPath seems to point to the correct Path.

**Comment by superichmann** [comment]
FYI: This is still happening (installed prealpha pythonnet from nuget on new console application in vs2022 .net6)
`PythonEngine.Initialize();` solved it
