### ISSUE TITLE
Crash on shutdown when embedding Python in C#

### ISSUE THREAD

**Issue by BadSingleton** [pythonnet/pythonnet#1831]
### Environment

-   Pythonnet version: a80c685d197d47e959d65f82941068286c481276
-   Python version: 3.9.10
-   Operating System: Windows (probably others too)
-   .NET Runtime: mono/Unity

### Details

Using the Python for Unity package with at a commit hash later or equal to the one above, pythonnet causes a crash on Shutdown. I've traced the issue to this PR: https://github.com/pythonnet/pythonnet/pull/1780 which is cause by checking a Python internal without holding the GIL; which the shutdown process isn't doing (or at least not at this point).

**Comment by filmor** [comment]
Is the `Exceptions.ErrorOccurred()` the culprit? Does it work if that whole section is put in a `using (Py.GIL)` scope?

**Comment by Martin-Molinero** [comment]
Just adding to this: we are seeing a similar segmentation fault while shutting down, only while debugging for same reason. Manually shutting down seems to avoid the seg fault https://github.com/QuantConnect/Lean/pull/6439
