### ISSUE TITLE
Can't add project to existing solution

### ISSUE THREAD

**Issue by matthiasburger** [pythonnet/pythonnet#1853]
### Environment

-   Pythonnet version: latest (05.07.22)
-   Python version: 3.10
-   Operating System: Mac OS 12.4
-   .NET Runtime: .net 6

### Details

I wanted to add the `Python.Runtime.csproj` into my existing solution but I get following exception:

> Unable to load project and obtain project information from MsBuild. Try to change MsBuild version in 'Settings | Build, Execution, Deployment | Toolset and Build'. Probably this project is incompatible with the current MsBuild.  MsBuild error details: The expression "[System.IO.File]::ReadAllText(version.txt)" cannot be evaluated. Could not find file '/private/var/folders/qt/cqy7_g9x3j14tcrwf5w_kfj80000gn/T/version.txt'.

**Comment by matthiasburger** [comment]
`<FullVersion>$([System.IO.File]::ReadAllText("version.txt"))</FullVersion>` doesn't work on Mac. You cannot even open the solution-

**Comment by filmor** [comment]
This is not a supported use case. Please use a nuget package.

**Comment by filmor** [comment]
To elaborate, now that I have a bit more time: This file is part of the repo and the respective code expects that to be the root of the build process. It should be possible to adjust the build props to use its own directory as the source of the lookup, but this will still not be a supported scenario.

**Comment by lostmsu** [comment]
@matthiasburger TL;DR; you can completely remove that line and later add your own versioning if needed.

**Comment by filmor** [comment]
This should be fixed now.

**Comment by matthiasburger** [comment]
@filmor thanks for fixing it :) 

just to clarify, of course this scenario is not supported. But as long as I don't want to make custom changes on your code it's much easier to clone and pull changes instead of creating a fork and merge your changes every time :D
