### ISSUE TITLE
throw TypeLoadException while load and execute net 6 dll  function

### ISSUE THREAD

**Issue by heartacker** [pythonnet/pythonnet#1858]
### Environment

-   Pythonnet version: 3.0.0rc2
-   Python version: 3.9.10
-   Operating System: win 11 x64
-   .NET Runtime: 6.0.301

### Details

-   Describe what you were trying to get done.

    using python to load net6 dll and execute fail.

-   What commands did you run to trigger this issue? 

load dll success
and invoke c# function but throw exception

-   If there was a crash, please include the traceback here.
```log
System.TypeLoadException: 未能从程序集“System.Runtime, Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a”中加载类型“System.Runtime.CompilerServices.DefaultInterpolatedStringHandler”。
```
![image](https://user-images.githubusercontent.com/1876302/177828035-8764ae69-e6ea-4637-b0fc-072c70c44d98.png)

**Comment by filmor** [comment]
@heartacker This is not your first report, you should know by now that this is not actionable.

1. We need English error messages, I can't read Chinese
2. We need the exact code that you are using to call the .NET code
3. We might need the .NET code as well

Errors in `System.Runtime` suggest that you are not actually using .NET 6 but just the (default) .NET Framework runtime. What does the following print if you add it after your initialisation?

    from pythonnet import _RUNTIME
    print(_RUNTIME._impl)

**Comment by heartacker** [comment]
.NET Framework runtime. What does the following print if you add it after your initialisation?
> 
> ```
> from pythonnet import _RUNTIME
> print(_RUNTIME._impl)
> ```

@filmor there is the var, and could you pleas take a look what the problems?
![image](https://user-images.githubusercontent.com/1876302/181697630-f7f0933b-d302-473a-984c-74a8a4e6f33b.png)
![image](https://user-images.githubusercontent.com/1876302/181698391-53b715f8-b9a6-4735-83a4-b96bc6abd62e.png)

- output:
```
<clr_loader.netfx.NetFx object at 0x0000028ABCFB1370>
```

**Comment by filmor** [comment]
The NetFx runtime is the old .NET Framework. Please check the existing notes on the discussion board thread of the RC on how to load a .NET 6 runtime.
