### ISSUE TITLE
`import clr` with no .NET runtime should give a helpful message

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1868]
Currently we get

> RuntimeError: Could not find libmono

While it is mostly obvious, it would not hurt to expand it to something like

> A compatible .NET runtime could not be found. Install a compatible runtime or load one explicitly using `set_runtime` or `set_runtime_from_env`.

**Comment by roberto-lopardo-aimen** [comment]
I'm also getting this error. How do you tell pythonnet to use the official .NET environment instead of mono?
