### ISSUE TITLE
Cannot change Python version in runtime

### ISSUE THREAD

**Issue by Tiehong** [pythonnet/pythonnet#1905]
### Environment

-   Pythonnet version: 3.0.0 rc4
-   Python version: 3.8, 3.10
-   Operating System: Windows11
-   .NET Runtime: .NET Framework4.8

### Details

In runtime, I can change Runtime.PythonDLL, but PythonNet still uses the first Python version.

For example, I first set Runtime.PythonDLL="python38.dll", print(sys.version) outputs 3.8.10. That is correct. If I change Runtime.PythonDLL to "python310.dll", it still outputs 3.8.10. I expect 3.10.6.

**Comment by filmor** [comment]
This not supported.
