### ISSUE TITLE
setup failing with AttributeError

### ISSUE THREAD

**Issue by rico-chet** [pythonnet/pythonnet#191]
During setup of current develop branch, I get this error message:
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\z001edxb\AppData\Local\Temp\pip-clrr6blj-build\setup.py", line 99, in <module>
    _xbuild = "\"%s\"" % _find_msbuild_tool("msbuild.exe")
  File "C:\Users\z001edxb\AppData\Local\Temp\pip-clrr6blj-build\setup.py", line 77, in _find_msbuild_tool
    hkey.Close()
AttributeError: 'NoneType' object has no attribute 'Close'

I have a WDK installed, not all of those mentioned in setup.py/_find_msbuild_tool()
using WinPython 32bit-3.5.1.2 on Win7
pull request #192

**Comment by swinstanley** [comment]
I think its likely that #194 would resolve this. Not exactly a duplicate issue but the function is called multiple times and it very environment sensitive.

**Comment by denfromufa** [comment]
both of these pull requests have been cheery-picked by @tonyroberts, hence closing this issue. let us know if you still get issues @rico-chet @swinstanley
