### ISSUE TITLE
AccessViolationException occure when I embedding anaconda python

### ISSUE THREAD

**Issue by MainForm** [pythonnet/pythonnet#1925]
### Environment

-   Pythonnet version: 3.0.0
-   Python version: 3.8.13
-   Operating System: window10 
-   .NET Runtime: .NET 6

### Details

-   Describe what you were trying to get done.

I already have embedded with python installed in window.
And this time, I want to embedding python that is in anaconda.
But, It dosen't work with AccessViolationException error.

here is my code

`
    using Python.Runtime;
    
    string pythonHome = @"C:\Users\bkgr4\anaconda3\envs\pytorch";
    string pythonPath = Path.Combine(pythonHome, "Lib");
    
    string path = pythonHome + ";" + Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.Machine);
    Environment.SetEnvironmentVariable("PATH", path, EnvironmentVariableTarget.Process);
    Environment.SetEnvironmentVariable("PYTHONNET_PYDLL", "python38.dll", EnvironmentVariableTarget.Process);
    Environment.SetEnvironmentVariable("PYTHONHOME", pythonHome, EnvironmentVariableTarget.Process);
    Environment.SetEnvironmentVariable("PYTHONPATH", pythonPath, EnvironmentVariableTarget.Process);
    
    PythonEngine.PythonHome = pythonHome;
    
    PythonEngine.Initialize();
    
    using (Py.GIL())
    {
        dynamic np = Py.Import("numpy");
        Console.WriteLine(np.cos(np.pi * 2));
    
        dynamic sin = np.sin;
        Console.WriteLine(sin(5));
    
        double c = (double)(np.cos(5) + sin(5));
        Console.WriteLine(c);
    
        dynamic a = np.array(new List<float> { 1, 2, 3 });
        Console.WriteLine(a.dtype);
    
        dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
        Console.WriteLine(b.dtype);
    
        Console.WriteLine(a * b);
        Console.ReadKey();
    }
    
    PythonEngine.Shutdown();

`

![image](https://user-images.githubusercontent.com/16147782/187068717-c7de8af5-5745-40e9-89c3-7ad3bc88bfb6.png)

-   If there was a crash, please include the traceback here.
![image](https://user-images.githubusercontent.com/16147782/187068870-ba8a5bff-d226-4684-9f74-d93bb7187531.png)

**Comment by lostmsu** [comment]
Can you share your conda environment packages and their versions?
Can you check that `Runtime.PyVersion` matches your Python version (it is an internal property, should be evaluatable in debugger)?

**Comment by filmor** [comment]
Without a reproducible example, we can't debug this. I'll reopen the issue once you provide one.
