### ISSUE TITLE
Release date 3.0

### ISSUE THREAD

**Issue by ksrangarajan** [pythonnet/pythonnet#1938]
### Environment

-   Pythonnet version: 3.0
-   Python version: 3.10
-   Operating System: windows 10
-   .NET Runtime: 4.6.1
-  Details

1. We are excited to see 3.0 is in release state. Kindly let us know probable release date of it

2. We see that  3.0 requires minimum of .net. Framework 4.6.2. kindly confirm

**Comment by filmor** [comment]
The process is tracked in https://github.com/pythonnet/pythonnet/issues/1860. Depending on my (free time) availability, I'd like to release in October.

3.0 requires minimum 4.7.2, that's the first proper .NET Standard 2.0 version of .NET Framework.
