### ISSUE TITLE
We need upper limit on clr_loader package in requirements

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#1944]
Publishing a new major version broke CI. This should only ever happen when a minor version gets published. Ideally, CI should use fixed version, and the package itself should set an upper bound.

https://github.com/pythonnet/pythonnet/actions/runs/3071323910/jobs/4961898263

**Comment by filmor** [comment]
Good point, I added this in #1942. If that PR finally goes through, I'll cut an rc5.
