### ISSUE TITLE
__init__ method called twice on subclassed managed type in Python

### ISSUE THREAD

**Issue by colbyj** [pythonnet/pythonnet#195]
When playing around with subclassing C# classes, I came across some odd behavior where the **init** method gets called multiple times upon creation of an object that has a C# class as a superclass.

For example,

```
import clr
clr.AddReference("System.Windows.Forms")
from System.Windows.Forms import Form


class TestForm(Form):
    __namespace__ = "App"

    def __init__(self):
        print "TestForm init"


if __name__ == "__main__":
    frm = TestForm()
```

results in "TestForm init" being printed twice.

**Comment by colbyj** [comment]
I just discovered that removing __namespace__ results in "TestForm init" being printed only once, as expected.

**Comment by denfromufa** [comment]
@colbyj this was mentioned before by @tonyroberts when he implemented this feature in 2013:

https://mail.python.org/pipermail/pythondotnet/2013-October/001424.html

**Comment by filmor** [comment]
This seems to have been fixed on `master`, no idea when :)
