### ISSUE TITLE
TypeError: 'Assembly' object is not subscriptable

### ISSUE THREAD

**Issue by jonahwoods95** [pythonnet/pythonnet#1950]
### Environment

-   Pythonnet version: 3.0.0a2
-   Python version: 3.9.13
-   Operating System: Windows 10 Enterprise
-   .NET Runtime: v4.0.30319

### Details

-   Simply importing clr (the original issue popped up during an import of pyadomd, but this error is generated during import of clr as well).

```python
    import clr
```

<img width="602" alt="image" src="https://user-images.githubusercontent.com/24378609/191155370-f5a9c894-9d53-45e5-bb3c-f961ace9ebd1.png">

**Comment by filmor** [comment]
Please either update pythonnet to the newest release candidate (5), or downgrade clr-loader to 0.1.7. I accidentally left the dependency version unbounded and made a change recently that broke the api slightly.

**Comment by lostmsu** [comment]
@filmor can we fix 2.5.3?

**Comment by filmor** [comment]
Huh? 2.5 never used `clr-loader`, there is nothing to do there. This only concerns the 3.0 alphas and release candidates, and frankly, I'd like people to update those to the latest one anyhow. That's the whole point of release candidates :)

**Comment by lostmsu** [comment]
@filmor sorry, I though the report said 2.5 and I did not pay attention.
