### ISSUE TITLE
Question: Has the way Python imports a .NET6 library changed?

### ISSUE THREAD

**Issue by DareDevilDenis** [pythonnet/pythonnet#1951]
To import a .NET6 library, my understanding is that the steps in Python.Net 3.0 are:

```python
from clr_loader import get_coreclr
from pythonnet import set_runtime

runtime = get_coreclr('MyApplication.runtimeconfig.json')
set_runtime(runtime)
```

However, with clr-loader 0.2.3 (released 5 days ago), the call to get_coreclr with one argument fails with exception:
`TypeError: get_coreclr() takes 0 positional arguments but 1 was given`

I've raised this issue in clr-loader: https://github.com/pythonnet/clr-loader/issues/35

However, I was wondering if the change to the get_coreclr() API might be intentional, meaning that the recommended steps to import a .NET6 library has changed. Can anyone please confirm?

**Comment by filmor** [comment]
1. This is already answered
2. Please don't post in three places at the same time

**Comment by DareDevilDenis** [comment]
Thanks for the quick response @filmor. Sorry for posting in three places - after raising as a bug I then wondered if it was an API change so I raised the question here. To be honest, I wasn't expecting breaking changes at this stage of release candidates. I guess these sometimes happen though - maybe breaking changes could be pinned at the top of the issues/discussion pages...
