### ISSUE TITLE
Pythonnet 3.0.0 is missing python_requires metadata, installs on 3.6

### ISSUE THREAD

**Issue by pkolbus** [pythonnet/pythonnet#1956]
### Environment

-   Pythonnet version: 3.0.0
-   Python version: 3.6.8
-   Operating System: Windows 10

### Details

-   Describe what you were trying to get done.

Pythonnet 3.0.0 is missing `python_requires` metadata (https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires) which means that pip will choose this version even with python versions that are not supported.

This creates challenges for owners and users of Python packages that use pythonnet, and still need to support/use Python 3.6.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

The following should install pythonnet 2.x but it installs 3.0.0.

```
$ python3.6 -m pip install pythonnet
```

-   If there was a crash, please include the traceback here.

```
$ python3.6 -c "import pythonnet"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python36\lib\site-packages\pythonnet\__init__.py", line 6, in <module>
    import clr_loader
  File "C:\Python36\lib\site-packages\clr_loader\__init__.py", line 5, in <module>
    from .types import Assembly, Runtime, RuntimeInfo
  File "C:\Python36\lib\site-packages\clr_loader\types.py", line 2, in <module>
    from dataclasses import dataclass, field
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by lostmsu** [comment]
There's an obvious workaround: `pip install pythonnet==2.*`

**Comment by filmor** [comment]
I'll yank the existing version and cut a 3.0.1 from master. This will also break for Python 3.11, as the current version doesn't work with it.

**Comment by filmor** [comment]
I pushed it as a `post` release to keep the version (no code change required).

**Comment by filmor** [comment]
@pkolbus Thanks for the report, by the way :)

**Comment by pkolbus** [comment]
Verified. Thanks for the quick fix!
