### ISSUE TITLE
pythonnet works normally in 3.6. In 3.10 I get an error.

### ISSUE THREAD

**Issue by zeroche72** [pythonnet/pythonnet#1963]
### Environment

-   Pythonnet version:  3.0.0.post1
-   Python version:  3.10
-   Operating System: windows10 
-   .NET Runtime: ??   .net framework 4.6.1 ??

### Details
When the following code is python36, it is normally executed.
However, when it is python310, the following error occurs:

The difference seems to be that the installation location of Python.Runtime.dll is different..
Python36    >>>    \\Python36\\Lib\\site-packes\\Python.Runtime.dll
Python310  >>>    \\Python310\\Lib\\site-packes\\pythonnet\\runtime\\Python.Runtime.dll

help me..

using System;
using System.Collections.Generic;
using Python.Runtime;

static void Main(string[] args)
{
    PythonEngine.Initialize();  >>>> error  MissingMethodException: Failed to load symbol Py_IncRef.
    using (Py.GIL())
    {
        dynamic np = Py.Import("numpy");
        Console.WriteLine(np.cos(np.pi * 2));
   }
}

**Comment by filmor** [comment]
This is not a supported way of getting the DLL for .NET. Use the nuget package or sort the path out yourself, we are not going to commit to the placement of individual files.

**Comment by zeroche72** [comment]
But why does version 3.6 succeed?
I did the same thing...
