### ISSUE TITLE
Error loading Python DLL in Apple M1 chip

### ISSUE THREAD

**Issue by barbarian1803** [pythonnet/pythonnet#1974]
### Environment

-   Pythonnet version: 3
-   Python version: 3.10
-   Operating System: MacOS Monterey
-   .NET Runtime: dotnetcore 3.1

### Details

I got this error when running in dotnet: 

`---> System.DllNotFoundException: Could not load /opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/config-3.10-darwin/libpython3.10.dylib with flags RTLD_NOW | RTLD_GLOBAL: dlopen(/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/config-3.10-darwin/libpython3.10.dylib, 0x000A): tried: '/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/config-3.10-darwin/libpython3.10.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/Python' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file)`

Is M1 architecture not supported yet?

**Comment by filmor** [comment]
You are using a (rosetta) x86-64 dotnet with an arm64 Python. This won't work, you can't mix architectures. Getting either an x86-64 Python or an arm64 .NET should work.
