### ISSUE TITLE
Python.Runtime.PythonException: No module named 'numpy'

### ISSUE THREAD

**Issue by guimar86** [pythonnet/pythonnet#1997]
### Environment

-   Pythonnet version: (downloaded zip from master and built the project to get the needed .dll file)
-   Python version: 3.8-64
-   Operating System: Windows
-   .NET Runtime: Microsoft.AspNetCore.App 3.1.25

### Details

-   Describe what you were trying to get done. 
I require using python code from c# but the command **Py.Import("numpy");** simply gives the following error: 

```
Python.Runtime.PythonException: No module named 'numpy'
```

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

I followed the instructions from the official documentation link:

https://pythonnet.github.io/pythonnet/dotnet.html

You can see the whole code I used, it's a simple console app: 

```
using System;
using System.Collections.Generic;
using Python.Runtime;

namespace Python2CSharp2
{
    class Program
    {
        static void Main(string[] args)
        {
            //Console.WriteLine("Hello World!");
            //RunPythonCode("print('Hello Python')");
            RunPythonScript();
        }
        
        public static void Initialize()
        {
            string pythonDll = @"C:\Users\RenatoMartins\AppData\Local\Programs\Python\Python38\python38.dll";
            Environment.SetEnvironmentVariable("PYTHONNET_PYDLL", pythonDll);
            PythonEngine.Initialize();
            
        }
        
        public static void RunPythonCode(string pycode)
        {
            Initialize();
            using (Py.GIL())
            {
                PythonEngine.RunSimpleString(pycode);
            }
        }

        public static void RunPythonScript()
        {
            Initialize();
            //PythonEngine.Initialize();
            dynamic np;
            using (Py.GIL())
            {
                np = Py.Import("numpy");
                Console.WriteLine(np.cos(np.pi * 2));

                dynamic sin = np.sin;
                Console.WriteLine(sin(5));

                double c = (double)(np.cos(5) + sin(5));
                Console.WriteLine(c);

                dynamic a = np.array(new List<float> { 1, 2, 3 });
                Console.WriteLine(a.dtype);

                dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
                Console.WriteLine(b.dtype);

                Console.WriteLine(a * b);
                Console.ReadKey();
            }
        }
    }
}
```

-   If there was a crash, please include the traceback here.
```
Python.Runtime.PythonException: No module named 'numpy'
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.NewReferenceExtensions.BorrowOrThrow(NewReference& reference)
   at Python.Runtime.PyModule.Import(String name)
   at Python.Runtime.Py.Import(String name)
```

**Comment by guimar86** [comment]
I would like to read out the solution for Python38.dll but for those who had this issue I managed to get it done with python310.dll. So simply, I changed the version of Python and got it to work!!!

**Comment by filmor** [comment]
This is not a Python.NET issue.

**Comment by guimar86** [comment]
> This is not a Python.NET issue.

I understand, but perhaps updating the error messages would help understand it better, because all I did was update the version of Python, where most of the tutorials out there suggest Python3.8.
