### ISSUE TITLE
No way to call .net core 6.0 dll from python 

### ISSUE THREAD

**Issue by StefanoOcchetti** [pythonnet/pythonnet#2018]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.11.0
-   Operating System: Debian GNU/Linux 11 (bullseye)
-   .NET Runtime: .net core 6.0

### Details

Goal: attempt to call a simple static function in a .net core dll from a python script

The C# project contains only one file:

```c#
namespace Math
{
	public class Calculator
	{
		public static int Factorial(int number)
		{
			int i;
			int fact = 1;
			for (i = 1; i <= number; i++)
			{
				fact *= i;
			}
			return fact;
		}
	}
}

```
The python script is the following:

```python
from pythonnet import load

load("coreclr")
import clr

reference = clr.AddReference('./Math/bin/Debug/net6.0/publish/Math')
print(reference)
from Math import Calculator

factorial = Calculator.Factorial(6)
print(factorial)
```

-   If there was a crash, please include the traceback here.

```shell
# python factorial.py 
Math, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Traceback (most recent call last):
  File "factorial.py", line 8, in <module>
    from Math import Calculator
ImportError: cannot import name 'Calculator' from 'Math' (unknown location)
```

To reproduce the environment, here's a dockerfile:

```
FROM python:3.11.0-slim-bullseye
    
# Install .Net	
RUN apt-get update
RUN apt-get -y install wget

RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb

RUN apt-get update && \
    apt-get install -y dotnet-sdk-6.0

RUN pip install pythonnet

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
```

**Comment by filmor** [comment]
I'm not sure what exactly is failing for you, but I just ran pretty much this locally and it works without any problem:

    dotnet new classlib --name Math
    cd Math
    # ... put your C# code into Calculator.cs
    dotnet publish -o out .
    # ... run your Python code with `clr.AddReference("out/Math")`

**Comment by StefanoOcchetti** [comment]
Thanks for your reply.

I ran exactly the steps you suggested, but it definitely doesn't work.

The following code:

```python
reference = clr.AddReference('out/Math')
print(reference)
from Math import Calculator
```

seems to correctly load the assembly, as it prints:

```
Math, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

but an error occurs at the next step, in `from Math import Calculator`:

```
Exception has occurred: ImportError
cannot import name 'Calculator' from 'Math' (unknown location)
  File "factorial.py", line 8, in <module>
    from Math import Calculator
```

**Comment by StefanoOcchetti** [comment]
I provided a pre-configured development environment in docker here:

https://github.com/starnutoditopo/CallNetFromPythonExample.git

**Comment by filmor** [comment]
The issue is that you have a `Math` sub folder in the directory that you run `factorial.py` from. Python's namespace package loader will take precedence over ours and the respective namespace package is of course empty. Rename the `Math` directory to something else and it will work:

![image](https://user-images.githubusercontent.com/30848/203516736-6f1dedc7-ed74-46b3-805a-111506d49c00.png)

**Comment by 0x78f1935** [comment]
I hate name collisions 😅 , thanks for saving me a headache!
