### ISSUE TITLE
PythonNET now throws exception when comparing `int` and `DateTimeOffset.MaxValue`, `TimeSpan.MaxValue` and `TimeSpan.MinValue`

### ISSUE THREAD

**Issue by mrwizard82d1** [pythonnet/pythonnet#2022]
### Environment

-   Pythonnet version: 3.0.0.post1
-   Python version: 3.8.10
-   Operating System: Windows 10
-   .NET Runtime: .NET Framework 4.8

### Details

-   I was running a parameterized unit test that converted a number of different .NET types to Python types. Our application has specific rules for converting `DateTimeOffset.MaxValue`, `TimeSpan.MaxValue` and `TimeSpan.MinValue` and so I tested to see if the .NET value (in this case, an `Int32`/Python `int`) equaled these "special" .NET values.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python .\op_equality_change.py
108 == DateTimeOffset.MaxValue
No method matches given arguments for DateTimeOffset.op_Equality: (<class 'int'>)
108 == TimeSpan.MaxValue
No method matches given arguments for TimeSpan.op_Equality: (<class 'int'>)
108 == TimeSpan.MinValue
No method matches given arguments for TimeSpan.op_Equality: (<class 'int'>)python

```

-   If there was a crash, please include the traceback here.

```python .\op_equality_change.py
108 == DateTimeOffset.MaxValue
Python.Runtime.PythonException: 'int' value cannot be converted to System.DateTimeOffset

The above exception was the direct cause of the following exception:

System.ArgumentException: 'int' value cannot be converted to System.DateTimeOffset in method Boolean op_Equality(System.DateTimeOffset, System.DateTimeOffset) ---> Python.Runtime.PythonException: 'int' value cannot be converted to System.DateTimeOffset
   --- End of inner exception stack trace ---

The above exception was the direct cause of the following exception:

System.AggregateException: One or more errors occurred. ---> System.ArgumentException: 'int' value cannot be converted to System.DateTimeOffset in method Boolean op_Equality(System.DateTimeOffset, System.DateTimeOffset) ---> Python.Runtime.PythonException: 'int' value cannot be converted to System.DateTimeOffset
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: 'int' value cannot be converted to System.DateTimeOffset in method Boolean op_Equality(System.DateTimeOffset, System.DateTimeOffset) ---> Python.Runtime.PythonException: 'int' value cannot be converted to System.DateTimeOffset
   --- End of inner exception stack trace ---<---


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\op_equality_change.py", line 8, in <module>
    108 == DateTimeOffset.MaxValue
TypeError: No method matches given arguments for DateTimeOffset.op_Equality: (<class 'int'>)
```
I believe the stack traces for TimeSpan.MaxValue and TimeSpan.MinValue are similar.

[op_equality_change.zip](https://github.com/pythonnet/pythonnet/files/10069094/op_equality_change.zip)

**Comment by mrwizard82d1** [comment]
Sorry. I raised this issue because similar code **did not** raise an exception in `pythonnet-2.5.2`. 

I'm open to the idea that the `pythonnet-2.5.2` was _broke_ in this area, but it seems that Pythonic equality would include the type tests before the value test.

**Comment by filmor** [comment]
Yes, we tried to limit the "implicit" conversions to a minimum. I don't even know, which change in particular is responsible for the behavioural ~~change~~ fix that you are observing here, but you are only able to compare things to a .NET object that are directly convertible to it. If you'd really require this for `DateTimeOffset` and `TimeSpan`, you could make them convertible via a [Codec](https://pythonnet.github.io/pythonnet/codecs.html). Otherwise, I'd suggest you just generate the respective comparison values using `.FromTicks`.
