### ISSUE TITLE
Pythonnet  package problem

### ISSUE THREAD

**Issue by FearlessBao** [pythonnet/pythonnet#2024]
### Environment

-   Pythonnet version:3.0.1
-   Python version:3.8.10
-   Operating System:win10
-   .NET Runtime:v4.0.30319

### Details

The clr module is normal before packaging, and an error is reported after packaging
use PyInstaller and auto-py-to-exe
Thank you in advance

code:
"""
import sys
import pythonnet
IdeaOptics1=pythonnet.get_runtime_info()
print(IdeaOptics1)

import clr
……
"""

error:
 Traceback (most recent call last):
  File "python demo.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "clr.py", line 6, in <module>
    load()
  File "pythonnet\__init__.py", line 143, in load
    if func(b"") != 0:
  File "clr_loader\types.py", line 64, in __call__
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
[3240] Failed to execute script 'python demo' due to unhandled exception!

![image](https://user-images.githubusercontent.com/109445478/204131428-7d5a40f1-0e6a-485e-a5e9-320748a61876.png)

![image](https://user-images.githubusercontent.com/109445478/204131455-4e08650f-6e14-4a1b-9998-86b5181b43c2.png)

**Comment by filmor** [comment]
This is not a supported use case. You are probably missing the DLL that is used by `clr_loader` for initializing the .NET Framework runtime.

**Comment by FearlessBao** [comment]
> This is not a supported use case. You are probably missing the DLL that is used by `clr_loader` for initializing the .NET Framework runtime.

Thank you. It's the first time to use this module. I'll try it later

**Comment by jackcode996** [comment]
@FearlessBao How to resolve this issue, I met the same problem, code can run correctly in pycharm, but after packaged by pyinstaller to exe, the exe will report runtime error, 
`import clr
clr.AddReference("demo")
from demo import *`
method in demo can be called correctly

**Comment by FearlessBao** [comment]
1. The packaging problem is not solved. I extract this part, install python on the target computer, and run this part directly. The part is started using the os.system (" xxx.py ")&nbsp; from packaged program instruction and loops through an np file to determine when to close.&nbsp;
2. The dll provider says it may be a 32-bit or 64-bit python problem. (I'm using 64-bit python.)(Too lazy to try)



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 22, 2023 22:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pythonnet/pythonnet] Pythonnet  package problem (Issue #2024)




 
@FearlessBao How to resolve this issue, I met the same problem, code can run correctly in pycharm, but after packaged by pyinstaller to exe, the exe will report runtime error,
 import clr clr.AddReference("demo") from demo import *
 method in demo can be called correctly
