### ISSUE TITLE
Unable to convert object typed as `IComparable` down to concrete (actual) `DateTimeOffset` class

### ISSUE THREAD

**Issue by mrwizard82d1** [pythonnet/pythonnet#2034]
### Environment

-   Pythonnet version: 3.0.0.post1
-   Python version: 3.8
-   Operating System: Windows 10
-   .NET Runtime: .NET Framework 4.8

### Details

-   Print a `DateTimeOffset` using the format string 'o'. However, the type of the object returned from a .NET interface was `IComparable` instead of `DateTimeOffset` (printing, for example, 'net_range_start.GetType().FullName` prints "DateTimeOffset").
- Similar code worked as expected using `pythonnet-2.5.2`.
- I understand that `pythonnet-3` has reduced many implicit conversions, but the inability, from Python, to downcast this interface to its concrete type (as far as I can tell) means that my "C# intuition" utterly fails me in this situation.
- I actually have access to the original C# code and could write a utility method to perform this downcast, but that solution seems very heavyweight.
- Writing a codec for this conversion seems very heavyweight also.

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

- The C# library created an interface for a generic range that returned its `Start` and `Stop` members as `IComparable` instances instead of the concrete parameter for the generic range. Python code queries an instance of the interface for it's `Start` and `Stop` members. Invoking `ToString('o')` then causes the exception described later.

-   If there was a crash, please include the traceback here.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [59], line 1
----> 1 net_range_start.ToString('o')

TypeError: No method matches given arguments for Object.ToString: (<class 'str'>)

**Comment by mrwizard82d1** [comment]
What I find most confusing (frustrating?) is that the expression `type(net_range_start)` returns `System.IComparable` but `net_range_start.GetType().FullName returns 'System.DateTimeOffset'.

**Comment by lostmsu** [comment]
You can access `__implementation__` (codecs applied) or `__raw_implementaion__` (codecs not applied).

**Comment by mrwizard82d1** [comment]
Thanks for the idea, lostmsu. 

I'll try this tomorrow.

**Comment by mrwizard82d1** [comment]
It worked! Thanks for your help and for all your hard work on Python.NET.

Next time, I'll do a better job of reviewing the documentation before posting an issue.
