### ISSUE TITLE
Memory not freed, call python in C#

### ISSUE THREAD

**Issue by nocomplain** [pythonnet/pythonnet#2036]
### Environment

-   Pythonnet version: 3.0.0
-   Python version: 3.8.10
-   Operating System: Windows 11, IIS 10 and Debian 11 docker container
-   .NET Runtime: .NET 6

### Details
Hi, I use this to call python script in C#, here is my code:
`public class CallPyService: ICallPyService
    {
        /// <summary>
        /// 
        /// </summary>
        public CallPyService()
        {
            if (!App.GetOptions<PythonInfoOptions>().IsLinux)
            {
                string pathToVirtualEnv = Path.Combine(Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location), Path.Combine("Python", "Python3.8"));
                Environment.SetEnvironmentVariable("PATH", pathToVirtualEnv, EnvironmentVariableTarget.Process);
                Environment.SetEnvironmentVariable("PYTHONHOME", pathToVirtualEnv, EnvironmentVariableTarget.Process);
                Environment.SetEnvironmentVariable("PYTHONPATH", $"{Path.Combine(pathToVirtualEnv, "Lib", "site-packages")};{Path.Combine(pathToVirtualEnv, "Lib")}", EnvironmentVariableTarget.Process);
                Environment.SetEnvironmentVariable("PYTHONNET_PYDLL", $"{Path.Combine(pathToVirtualEnv, "python38.dll")}", EnvironmentVariableTarget.Process);

                PythonEngine.PythonHome = pathToVirtualEnv;
                PythonEngine.PythonPath = PythonEngine.PythonPath + ";" + Environment.GetEnvironmentVariable("PYTHONPATH", EnvironmentVariableTarget.Process);
                PythonEngine.Initialize();
                PythonEngine.BeginAllowThreads();
            }
            else
            {
                Runtime.PythonDLL = App.GetOptions<PythonInfoOptions>().LinuxPythonDLL;
                PythonEngine.Initialize();
                PythonEngine.BeginAllowThreads();
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns>PyObject</returns>
        public PyObject Exec(ModuleInfoModel model)
        {
            PyObject result;
            using (var gil = Py.GIL())
            {
                PyObject func = Py.Import(model.ModuleName);
                dynamic json = Py.Import("orjson");
                PyObject[] pyParams = model.Params.OrderBy(o => o.Sort).Select(o => (PyObject)EvalObject(o.Value, json)).ToArray();
                result = func.InvokeMethod(model.MethodName, pyParams);
                result = json.dumps(result, option: json.OPT_SERIALIZE_NUMPY).decode();
            }
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="value">object</param>
        /// <param name="orjson">orjson</param>
        /// <returns>PyObject</returns>
        private PyObject EvalObject(object value, dynamic orjson)
        {
            if (value == null || value.ToString() == "None")
            {
                return PyObject.None;
            }
            return orjson.loads(JsonConvert.SerializeObject(value));
        }`

everytime after I called **Exec** method, the memory will be increased, not freed. I used singleton in my app.
`services.AddSingleton<ICallPyService, CallPyService>();`
`public interface ICallPyService
    {
        public PyObject Exec(ModuleInfoModel model);
    }`
-   Describe what you were trying to get done.
I don't know why, I tried:
1. Call ShutDown(), an exception throwed, **BinaryFormatter serialization and deserialization are disabled within this application**
2. Put Exec into a thread, does not work.
3. Modify python script to call gc.collect(), does not work.
4. del locals(), does not work.
5. Call Dispose(), does not work.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```
So I wonder if anybody has the same issue, please help and thanks very much!

**Comment by nocomplain** [comment]
I added <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization> to my .csprj, then ShutDown() works, but the memory still high usage.

**Comment by nocomplain** [comment]
ShutDown() works. Close issue.

**Comment by filmor** [comment]
.NET has its own (non-reference-counted) garbage, so to release memory before shutdown, you will have to call both garbage collectors explicitly.

**Comment by nocomplain** [comment]
Thanks for your response, I will try this.
