### ISSUE TITLE
The value of __overloads__ is unclear when, seemingly, no overloads exist

### ISSUE THREAD

**Issue by mrwizard82d1** [pythonnet/pythonnet#2037]
### Environment

-   Pythonnet version: 3.0.0.post1
-   Python version: 3.8
-   Operating System: Windows 10
-   .NET Runtime: .NET Framework 4.8

### Details

-   I was trying to determine the overloads of the `DateTime` constructor

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    import pythonnet
    pythonnet.load('netfx')
    from System import DateTime
    DateTime.__overloads__
```

If overloads exist, I expected an Python `list` identifying the overloads. If no overloads are present, I expected an empty list.

What was printed by the REPL was:
`<unbound method '__init__'>`

-   If there was a crash, please include the traceback here.

No crash occurred.

**Comment by filmor** [comment]
Please read the docs. `__overloads__` is an accessor that allows you to use a particular overload, not a list of overloads. You can get those by simply checking the docstring of the function.

**Comment by mrwizard82d1** [comment]
I'm sorry to waste your time. 

I was mislead by the 2.5.2 behavior which returned an array of overloads using the `Overloads` attribute. I did not realize that `__overloads__` and `Overloads` no longer return an array of available overloads.
