### ISSUE TITLE
Cannot get the project to compile 

### ISSUE THREAD

**Issue by Ouakil** [pythonnet/pythonnet#2039]
### Environment

-   Pythonnet version:
![pythonnet](https://user-images.githubusercontent.com/4854943/205413703-a4c115b5-658f-4b4d-a06a-ff47334c3abd.JPG)

-   Python version:
-   Operating System:
-   .NET Runtime:

### Details

-   Describe what you were trying to get done.

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by Ouakil** [comment]
I do not understand why you closed this without providing any explanation, 
![image](https://user-images.githubusercontent.com/4854943/205434652-2c470293-6276-435d-98f3-c58ad9e06ecf.png)

**Comment by filmor** [comment]
Because you didn't ask a proper question. This is a bug tracker, not a support forum, and you come in here, drop a screenshot and don't even bother to fill out /any/ of the fields in the template.

**Comment by Ouakil** [comment]
Thank you, I will repost with all info properly filled out.
My fault, I thought an image was worth 1000 words.
