### ISSUE TITLE
Steps to create PIP package of Pythonnet

### ISSUE THREAD

**Issue by ksrangarajan** [pythonnet/pythonnet#2040]
### Environment

-   Pythonnet version: 3.0.0 
-   Python version: 3.10
-   Operating System: Windows 10
-   .NET Runtime: 4.7.2

### Details

-   Describe what you were trying to get done.

   Steps to Create pip package for the pythonnet 3.0 from the source code.  Currently using Windows 10 OS.
Want to create local build to test instead of using Py Module directly

-

**Comment by filmor** [comment]
`python -m build`
