### ISSUE TITLE
Using python 2.x?

### ISSUE THREAD

**Issue by bojanv55** [pythonnet/pythonnet#2058]
I cannot find anywhere if python 2.x version is supported?

Tried setting this using instructions for virtual env, but I get

`An unhandled exception of type 'Python.Runtime.BadPythonDllException' occurred in Python.Runtime.dll
Runtime.PythonDLL was not set or does not point to a supported Python runtime DLL. See https://github.com/pythonnet/pythonnet#embedding-python-in-net`

**Comment by filmor** [comment]
It is not supported, last version with Python 2 support is 2.5.2.
