### ISSUE TITLE
Passing byte[] from python to C# is very slow!

### ISSUE THREAD

**Issue by wf-soft** [pythonnet/pythonnet#2069]
I pass a 30MB python byte[] to a C# method, which takes 10 seconds

```
byteRes = bytearray()
for block in entry.get_blocks(entry.size):
      byteRes.extend(block)
bs = bytes(byteRes)
CSharpTest.Read(bs)
```

**Comment by filmor** [comment]
1. Please don't delete the issue template, it's there for a reason
2. This is not a reproducible example
3. You are not actually passing `byte[]` around here (which would be very fast) but instead a (Python) `bytes` object, which requires conversion. There is an existing issue on implementing this conversion in a fast manner: https://github.com/pythonnet/pythonnet/issues/1838
