### ISSUE TITLE
Tell the exception line: Python.Runtime.PythonException:“division by zero”

### ISSUE THREAD

**Issue by bnuzhouwei** [pythonnet/pythonnet#2076]
```python
using (Py.GIL())
{
    using (var scope = Py.CreateScope())
    {        
        dynamic module = scope.Exec("def add(x,y):return 1/0+x+y");
        var x = module.add(1, 2);
        Console.WriteLine(x);
    }
}
```

Only can get the exception as :

```python
Python.Runtime.PythonException:“division by zero”
```

Could the PythonException class contains the error line?

**Comment by lostmsu** [comment]
This is no a correctly submitted report. You need to add what you see, and what you expect to see.

**Comment by filmor** [comment]
You can get this information either using `exc.Format()` or (more specifically) using `exc.StackTrace`.
