### ISSUE TITLE
exceptions must derive from BaseException   Source=Python.Runtime 

### ISSUE THREAD

**Issue by bnuzhouwei** [pythonnet/pythonnet#2082]
```python
raise("some error")
```

But in csharp, got 

```python
exceptions must derive from BaseException
```

In Csharp, we can't get the exception details, is any conversation between python Exception and .net BaseException

**Comment by lostmsu** [comment]
This is by design in Python.
![image](https://user-images.githubusercontent.com/239520/213072126-2d046e74-d1fd-43e2-802d-2822885468b0.png)
