### ISSUE TITLE
PythonEngine.AcquireLock and ReleaseLock are marked "internal", but are mentioned in the documentation

### ISSUE THREAD

**Issue by koubaa** [pythonnet/pythonnet#2091]
### Environment

-   Pythonnet version: 3.x

### Details
This [document](https://github.com/pythonnet/pythonnet/blob/master/doc/source/dotnet.rst) refers to the internal implementation details `AcquireLock` & `ReleaseLock`.

If these are meant to be used from C# code, these should be made public again.  If not - they should be removed from the document (imho).

FWIW I use them in my code (but I can directly call into python3.x.dll for PyGILState_Ensure if they are not meant to be exposed by pythonnet)

**Comment by lostmsu** [comment]
You should be using `Py.GIL` and its `Dispose` instead.

**Comment by koubaa** [comment]
That's what I was thinking right after I sent this - they are a safer way to do the same thing.. in any case the document should be updated
