### ISSUE TITLE
System.Dynamic.ExpandoObject and IDynamicMetaObjectProvider support

### ISSUE THREAD

**Issue by bnuzhouwei** [pythonnet/pythonnet#2096]
Dyamic object can't be used in CPython

```bash
Python.Runtime.PythonException:“'ExpandoObject' object has no attribute 'a'”
```

```csharp
using (Py.GIL())
{
    using (var scope = Py.CreateScope())
    {
        dynamic obj = new System.Dynamic.ExpandoObject();
        obj.a = "a";
        scope.Set("p", Math.Pow);
        scope.Set("obj", obj);
        scope.Eval("obj.a");
    }
}
```

**Comment by filmor** [comment]
This is not a support channel.

1. Only report bugs (or suspected bugs) in here
2. Search the existing issues before posting, there is already a longstanding open issue on this subject: https://github.com/pythonnet/pythonnet/issues/72
3. If you have questions, open a Discussion in the Q&A section
