### ISSUE TITLE
Create a conda-forge recipe - Windows [done], Linux and OSX [WIP]

### ISSUE THREAD

**Issue by tonyroberts** [pythonnet/pythonnet#210]
Create a recipe for conda-forge to make it easier for users to get pre-built binaries - see https://conda-forge.github.io/

**Comment by denfromufa** [comment]
https://github.com/JanSchulz/conda-build-wheel to build PyPi wheels using
conda-forge

**Comment by denfromufa** [comment]
https://www.appneta.com/blog/pypi-deployment-with-travis-ci/

**Comment by denfromufa** [comment]
https://anaconda.org/pythonnet/pythonnet

**Comment by denfromufa** [comment]
linux and osx builds:

https://anaconda.org/bioconda/pythonnet

**Comment by filmor** [comment]
There is a conda-forge recipe nowadays at https://github.com/conda-forge/pythonnet-feedstock with packages at https://anaconda.org/conda-forge/pythonnet.
