### ISSUE TITLE
Incorrect type for CLR objects that implement an interface extending another interface

### ISSUE THREAD

**Issue by crnh** [pythonnet/pythonnet#2105]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.10
-   Operating System: Windows 10 Enterprise 21H2
-   .NET Runtime: .NET Framework 4.8.9105.0

### Details

-   Describe what you were trying to get done.

    We are using Python.NET in [ZOSPy](https://github.com/MREYE-LUMC/ZOSPy), a library that allows to communicate with Ansys Zemax OpticStudio using Python. This library works with Python 3.8 and Pythonnet 2.5.2, but not with Pythonnet 3.0.x. Under Pythonnet 3.0.x, we experience problems with objects implementing an interface that extends another interface. In Python, these objects only implement the parent interface, making all functionality provided by the child interface unavailable. At first sight, this seems related to https://github.com/pythonnet/pythonnet/issues/1783, but [this comment](https://github.com/pythonnet/pythonnet/issues/1783#issuecomment-1125343034) suggests that it also didn't work in Pythonnet 2.5.x, which isn't true for our case.

    The ZOS-API library provided by Zemax OpticStudio [is a .NET Framework 4.8 library](https://community.zemax.com/zos-api-12/pythonnet-3-0-not-recommended-to-use-for-zosapi-python-3474). As far as I know, this .NET Framework version should be supported by Pythonnet.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

    I ran the example below in Python 3.10 using Pythonnet 3.0.1, and in Python 3.8 using Pythonnet 2.5.2. In this example, I am configuring an analysis for an optical system. All analyses in OpticStudio implement their own specific interface, which in turn implements the base analysis interface `IA_`; for example, the `ZernikeStandardCoefficients` analysis implements `IA_ZernikeStandardCoefficients`, which in turn implements `IA_`. Similarly, every analysis has a settings object that implements an analysis-specific interface (e.g. `IAS_ZernikeStandardCoefficients`), which implements the base settings interface `IAS_`. `MaximumNumberOfTerms` is a member of the analysis-specific interface.

    ```python
    import sys
    import clr

    # Load Zemax OpticStudio API DLLs
    sys.path.append("<path/to/OpticStudio/>")
    clr.AddReference("ZOSAPI_NetHelper")
    clr.AddReference("ZOSAPI")
    clr.AddReference("ZOSAPI_Interfaces")

    # Import API libraries
    import ZOSAPI_NetHelper
    import ZOSAPI

    # Initialize communication
    ZOSAPI_NetHelper.ZOSAPI_Initializer.Initialize()

    # Connect to a Zemax instance
    connection = ZOSAPI.ZOSAPI_Connection()
    connection.ConnectAsExtension(0)

    # Get the primary OpticStudio system
    application = connection.ConnectToApplication()
    oss = application.PrimarySystem

    # Create a new Analysis
    analysis = oss.Analyses.New_Analysis_SettingsFirst(ZOSAPI.Analysis.AnalysisIDM.ZernikeStandardCoefficients)

    # Get the Settings object for the Analysis (should implement IAS_ZernikeStandardCoefficients)
    analysis_settings = analysis.GetSettings()

    print(type(analysis))
    print(type(analysis_settings))
    print(analysis_settings.MaximumNumberOfTerms)
    ```

    When running this code with Pythonnet 2.5.2, everything works:

    ```shell
    <class 'ZemaxUI.ZOSAPI.Analysis.Aberrations.A_ZernikeStandardCoefficients'> # Correct type of the analysis object
    <class 'ZemaxUI.ZOSAPI.Analysis.Aberrations.AS_ZernikeStandardCoefficients'> # Correct type of the analysis settings object
    37
    ```

    When running this code with Pythonnet 3.0.1, the analysis and settings objects only implement the base interfaces, and some functionality is unavailable:

    ```shell
    <class 'ZOSAPI.Analysis.IA_'> # Wrong type of the analysis object
    <class 'ZOSAPI.Analysis.Settings.IAS_'> # Wrong type of the analysis settings object
    Traceback (most recent call last):
    File "D:\code\zemax\netframework_version_test\main.py", line 33, in <module>
        print(analysis_settings.MaximumNumberOfTerms)
    AttributeError: 'IAS_' object has no attribute 'MaximumNumberOfTerms'
    ```

-   If there was a crash, please include the traceback here.

    ```python
    Traceback (most recent call last):
    File "D:\code\zemax\netframework_version_test\main.py", line 36, in <module>
        print(analysis_settings.MaximumNumberOfTerms)
    AttributeError: 'IAS_' object has no attribute 'MaximumNumberOfTerms'
    ```

**Comment by lostmsu** [comment]
This is not a **minimal** reproducible example, since it includes a third-party dependency.

**Comment by crnh** [comment]
I'm sorry for that. I also tried to create an MWE, which only caused me to wonder why this has ever worked before. Anyways, thank you for pointing me to the changelog. I expect the `__implementation__` or `__raw_implementation__` method will work in our case. Thanks!
