### ISSUE TITLE
Unable to find Microsoft.Extension.Logger.Abstraction nuget file.

### ISSUE THREAD

**Issue by Sellebjergen** [pythonnet/pythonnet#2109]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.9.6
-   Operating System: windows 10 enterprise
-   .NET Runtime: dotnet 6

#### Describe what you were trying to get done.

I am trying to utilize the pythonnet package to include some classes from a dotnet 6 project in such a way that I can load test the function by using the locust framework. It's part of a larger process to have a complete overview over the performance of my system.

#### What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example (http://stackoverflow.com/help/mcve) this will help us understand the issue.

Based on the tutorial in the wiki [How to call a dynamic library](https://github.com/pythonnet/pythonnet/wiki/How-to-call-a-dynamic-library) I created the following small example csharp code, running on dotnet 6.

```csharp
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace CalcTestNS
{
	public class calculate
	{
		public int Add(int a, int b)
		{
			var logger = NullLogger.Instance;
			logger.LogInformation("shit happens");
			return a + b;
		}

		public int Sub(int a, int b)
		{
			return a - b;
		}
	}
}
```

building and compiling this I got the dll file.
I have the following python script

```python
from pythonnet import load

load("coreclr")

import clr
import sys

calctest_path = r"C:\test-lab\CalcTest\CalcTest\bin\Debug\net6.0"
sys.path.append(calctest_path)
clr.AddReference("CalcTest")
from CalcTestNS import calculate

ct = calculate()
print(ct.Add(1, 1))
params = [1, 2]
print(ct.Sub(*params))
```

Which on a run gives me the error:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at CalcTestNS.calculate.Add(Int32 a, Int32 b)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Removing the usage of the nuget packages results in the program running perfectly. Thus the following csharp

```csharp
namespace CalcTestNS
{
	public class calculate
	{
		public int Add(int a, int b)
		{
			return a + b;
		}

		public int Sub(int a, int b)
		{
			return a - b;
		}
	}
}
```

will compile and run perfectly, giving the output

```
2
-1
```

**Comment by filmor** [comment]
Please use `dotnet publish -o your_out_path` to ensure that all DLLs are put there.
