### ISSUE TITLE
Method overloading syntax

### ISSUE THREAD

**Issue by mozey** [pythonnet/pythonnet#211]
When calling this function 
   
    sdk.DatabaseContext.SetBranchContext(0)

I get the error message below, which makes me think method overloading might be at play here

    No method matches given arguments

From reading the docs for the "sdk", I can see that the method expects an int. Using the following syntax

    sdk.DatabaseContext.SetBranchContext[int](0)

I get a different error message

    No match found for given type params

Using iPython I can confirm that `sdk.DatabaseContext.SetBranchContext` does exist.

Bit stuck at this point, is there anything else I could try?

**Comment by denfromufa** [comment]
1. What do you see under `sdk.DatabaseContext.SetBranchContext.__overloads__`? This should show you the list of available overloaded methods.
2. sdk.DatabaseContext.SetBranchContext[int] does not seem to be a valid thing because .NET has only Int16/In32/Int64 (int is just sugar syntax for int32 when used in C#).
3. You can try passing Int16(0), Int32(0), Int64(0) dependeng on what what you get from 1.
4. Can you report your cpython, pythonnet, .NET, Windows, bitness versions?

**Comment by mozey** [comment]
1. Result of dir(sdk.DatabaseContext.SetBranchContext.__overloads__) attached. I'm not sure if this is useful, looks like a default list of methods.

![screen shot 2016-05-09 at 10 53 21 am](https://cloud.githubusercontent.com/assets/152196/15108409/06af4874-15d6-11e6-98d7-aac01193f0a3.png)

3. Where do I get the different int types from, like this maybe? 

    from ctypes import c_int64

4. Versions are as follows:
python 3.3.5
cpython 6.2.9200
pythonnet 2.0.0
.NET v4.0.30319
x86 application running on Windows 8 64bit OS

**Comment by denfromufa** [comment]
For CLR integers use:
```
import clr
from System import Int32, Int64
```
Do not use c-types integers for CLR methods.

Calling `dir()` on `__overloads__` is the wrong thing to do. Just show what
`__overloads__` displays.

Where did you get CPython and pythonnet versions?
Anyway try upgrading pythonnet to 2.1 from PYPI.

**Comment by mozey** [comment]
> Where did you get CPython and pythonnet versions?

Installed python 3.3.5 from the MSI installer available on the website. For pythonnet I used a binary that was available [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet)

> Anyway try upgrading pythonnet to 2.1 from PYPI.

This worked

    pip install pythonnet --upgrade

    pip list

![screen shot 2016-05-09 at 1 00 04 pm](https://cloud.githubusercontent.com/assets/152196/15111230/0634d0f2-15e6-11e6-8c26-260adfbb183f.png)

> Do not use c-types integers for CLR methods.

Ok. I tried with clr.System.Int16, Int32 and Int64. I still get the same message:
    
![screen shot 2016-05-09 at 1 02 43 pm](https://cloud.githubusercontent.com/assets/152196/15111287/6bd1ae76-15e6-11e6-8906-782e4828b889.png)

**Comment by denfromufa** [comment]
Since pythonnet is upgraded now, did you try `setBranchContext(Int32(0))`
or `setBranchContext(0)`?

**Comment by tonyroberts** [comment]
Try sdk.DatabaseContext.SetBranchContext(Int32(0)).

@denfromufa sounds like another bug with the changes to method overload selector code to me.

**Comment by mozey** [comment]
> Since pythonnet is upgraded now, did you try `setBranchContext(Int32(0))`
or `setBranchContext(0)`?

Both of these work after upgrading to pythonnet 2.1.0. Thanks for the help!
