### ISSUE TITLE
Unable to catch exceptions in python from C# Tasks

### ISSUE THREAD

**Issue by drache42** [pythonnet/pythonnet#2112]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.10.10
-   Operating System: Windows
-   .NET Runtime: 7.0.x

### Details

Unable to catch exceptions in python from C# Tasks

C# looks something like this

```
public async Task<PrintResult> AsyncPrintWillThrow()
{
    await Task.Delay(500);
    
    throw new System.Exception("Throwing an exception in a Task");
}
```

calling this from python
```python
  try:
      t = StringPrinter.AsyncPrintWillThrow()     // <---- this throws
      a = t.GetAwaiter()
      r = a.GetResult()

      return r
  except System.Exception as e:
      print(f"caught the exception we expected. {e.Message}")
  except TypeError as e:
      print(f"caught the exception we did not expected. {e}")
```

End result is that a "TypeError" with message "not enough arguments" is thrown.
I believe it is this line of code: https://github.com/pythonnet/pythonnet/blob/37f12359e0ccc925468ec49cda04330f46e1e981/src/runtime/Types/MethodBinding.cs#L202

**Comment by filmor** [comment]
What is the exact code you are running and what is the exact exception (with stack trace)? My guess is that you are actually just calling a function with the wrong parameters. Note also, that extension methods are not supported so far.

**Comment by drache42** [comment]
Here is all the code: https://github.com/drache42/pythonnetsandbox

README has simple instructions on how to run it, essentially just run `dotnet publish -o dist` and then the python code picks up the C# bins. Note: You must run dotnet 7.0.201 because 7.0.200 has a publish bug

This catches: https://github.com/drache42/pythonnetsandbox/blob/main/src/PythonProgram/PythonProgram.py#L158 as expected, but it's not catching the correct exception which is thrown here: https://github.com/drache42/pythonnetsandbox/blob/main/src/StringPrinterSDK/StringPrinter.cs#L77

Exception Details
```

  Message=not enough arguments
  Source=C:\Users\sfroehlich\Code\pythonnetsandbox\src\PythonProgram\PythonProgram.py
  StackTrace:
  File "C:\Users\sfroehlich\Code\pythonnetsandbox\src\PythonProgram\PythonProgram.py", line 158, in PrintSync
    t = StringPrinterSDK.StringPrinter.AsyncPrintWillThrow()
  File "C:\Users\sfroehlich\Code\pythonnetsandbox\src\PythonProgram\PythonProgram.py", line 208, in <module>
    pyStringPrinter.PrintSync()     # calls async wrapped function with try/except
TypeError: not enough arguments

```

**Comment by filmor** [comment]
You are trying to call a method on a class, Python expects a `self` there. `StringPrinter().AsyncPrintWillThrow()` should work.

**Comment by drache42** [comment]
Ahhh I see now. Thank you for your quick responses. It helped this python noob a lot!
