### ISSUE TITLE
Unable to check PythonException type.

### ISSUE THREAD

**Issue by cjm1905** [pythonnet/pythonnet#2113]
### Environment

-   Pythonnet version: 3.01
-   Python version: 3.7+
-   Operating System: Windows 10
-   .NET Runtime: any

### Details
We use embedded PythonNet for application automation, image and video processing. We are upgrading to PythonNet 3.01 from 2.5 and found it is not possible to check for a PythonException type. Previously this code worked:

```C#
if( exc is PythonException pExc ) {
    if( pExc.PyType == Python.Runtime.Exceptions.SystemExit ) {
        // exception raised from calling exit()
        return;
    }
}
```

Now Exceptions is no longer a public class, even though it has the public methods for the exceptions types. I have not found any other way of testing for a particular exception type. I think Exceptions should still be a public class.

**Comment by lostmsu** [comment]
You can obtain these exceptions yourself from `builtins` Python module. E.g. `Py.Import("builtins").GetAttr("SystemExit").Equals(pExc.PyType)`
