### ISSUE TITLE
PythonEngine.AcquireLock not public

### ISSUE THREAD

**Issue by cjm1905** [pythonnet/pythonnet#2114]
### Environment

-   Pythonnet version: 3.01
-   Python version: 3.7+
-   Operating System: Windows 10
-   .NET Runtime: any

### Details

We use embedded PythonNet for application automation, image and video processing. We are upgrading to PythonNet 3.01 from 2.5 and find that `PythonEngine.AcquireLock` is no longer a public method. Of course `Py.Gil()` can be used but we need to acquire and release the GIL on every video frame so `PyGil()` means creating and disposing an object on every frame. Although the extra overhead is small relative to the image processing it seems unnecessary. Can `PythonEngine.AcquireLock` or similar be made public again? Our existing code is:

```C#
            IntPtr gil = PythonEngine.AcquireLock();
            try {
                m_vidProcess.Invoke();
            } catch( Exception exc ) {
                throw new InvalidProgramException( exc.Message );
            } finally {
                PythonEngine.ReleaseLock( gil );
            }
```

**Comment by filmor** [comment]
I will consider this if you can show that this actually makes a difference. From my PoV, your code should lead to the exact same JITted machine code as using `Py.GIL`.
