### ISSUE TITLE
PythonException is not serialisable

### ISSUE THREAD

**Issue by cjm1905** [pythonnet/pythonnet#2115]
### Environment

-   Pythonnet version: 3.01
-   Python version: 3.7+
-   Operating System: Windows 10
-   .NET Runtime: any

### Details

The PythonException class is not serialisable so in embedded applications Python exceptions cannot be passed across AppDomains. This means that it is necessary to create a new System Exception of some kind to wrap the Python exception. It would be more convenient to just pass the original exception. This is a small issue which has always been present in PythonNet AFAIK.

**Comment by filmor** [comment]
`PythonException` instances (as all Python objects from .NETs point of view) are inherently not serializable.

Just to be clear: This issue tracker is a pure bug tracker. If you want to suggest a feature, do it as a PR or ask about it in a discussion.
