### ISSUE TITLE
Load assemblies into own AppDomain

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#213]
I would like to be able to control the AppDomain that is used by Python.NET.

My use case is that I want to be able to
- Use shadow copies
- Control the binding redirects

Since this is quite a significant change, I'd like some comments on how to approach this.

As far as I can tell, I'll have to delay the initialisation in `clr.pyd` such that users can set the properties of the to-be AppDomain themselves:

```
import clr
clr.set_shadow_copies(True)
clr.set_config_file("some_path.config")
clr.initialize()
```

The default behaviour could still be that the `CurrentDomain` is used if `initialize` was not called before the first import.

Does this make sense or do we want this even more general like

```
import clr
clr.new_domain("my_domain", shadow_copies=True, ...)
from clr.my_domain import System
```

?

**Comment by tonyroberts** [comment]
Personally I prefer the first approach. Adding an extra component to the import path seems a bit fiddly and if everything will always be added to the same domain I can't see it adds anything.

One alternative you could consider, which could be less disruptive, would be to add some settings to the sys module. This is the approach pythoncom takes (see sys.co_initflags). That would allow you to set some options before importing clr, which you could check for when the clr module is imported. It smells like a bit of a hack, but thought I'd point it out in case it would make your life a bit easier!

**Comment by denfromufa** [comment]
looking into the future appdomains are not supported by .NET Core:

http://stackoverflow.com/questions/27266907/no-appdomains-in-net-core-5-why

**Comment by filmor** [comment]
I guess that makes the first approach even more valid. I'll try to keep things simple such that we can disable all of this via the preprocessor.

**Comment by denfromufa** [comment]
@filmor did you find out how to load pythonnet into separate appdomain? There is one question on stackoverflow about required permissions on restricted appdomain:


http://stackoverflow.com/questions/39363211/c-sharp-how-to-find-out-which-permission-an-app-domain-needs

**Comment by TheCollegedude** [comment]
> clr.set_config_file("some_path.config")
This would be so useful! Currently I can only copy my DLL's config right next to Python.exe as Python.exe.config - The only reason I need the config is the binding redirects that one of my dependencies requires (Npgsql)

**Comment by filmor** [comment]
This is supported nowadays using `clr-loader`'s `config_file` parameter, see https://github.com/pythonnet/pythonnet/issues/1754#issuecomment-1212798790.
