### ISSUE TITLE
how to pass a reference parameter to c# function in python

### ISSUE THREAD

**Issue by zhusihan-python** [pythonnet/pythonnet#2133]
i have a function in c# like this:
```
public void add(ref int x, ref int y)
{
    x = a.x;
    y = a.y;
}
```
how can i call the function add by clr, can not find related message in docs or issues
![image](https://user-images.githubusercontent.com/23504604/227135302-541f9fe5-4a33-493f-8521-a0027d56ab5d.png)

**Comment by filmor** [comment]
The documentation is here: https://pythonnet.github.io/pythonnet/python.html
