### ISSUE TITLE
Strong-name sign Python.Runtime.dll

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#214]
why python.runtime.dll is not strong-name signed, even if pythonnet.snk key file is provided in the repository. This prevents referencing this DLL from other strong-named assemblies and also silently fails when registering in GAC.

**Comment by denfromufa** [comment]
this may require particular key file

**Comment by vmuriart** [comment]
@denfromufa can you write a test for this? The references to the `snk` file seem to be broken so we can probably fix this.

**Comment by vmuriart** [comment]
`StrongNameSigning` works but has issues with `ExposeInternalsTo` that we use for embedded tests. I've completed setting it up, but disabled it for now.

**Comment by denfromufa** [comment]
This is what I use to sign Python.Runtime.DLL with strong custom key:

https://github.com/brutaldev/StrongNameSigner

**Comment by denfromufa** [comment]
Some things that need to be documented due to latest changes:

1. When compiling from VS providing the key to Python.Runtime project is not enough anymore. 

[assembly: InternalsVisibleTo("Python.EmbeddingTest")] requires public key

Friend assembly reference 'Python.EmbeddingTest' is invalid. Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations

2. Since version of Python.Runtime changed, hence all projects referencing it have to be re-compiled depending on the properties of referenced Python.Runtime DLL/project.
