### ISSUE TITLE
PythonEngine.Shutdown() issue

### ISSUE THREAD

**Issue by hakanozdmr** [pythonnet/pythonnet#2140]
### Environment

-   Pythonnet version:3.0.1
-   Python version:3.9.10
-   Operating System:Windows10
-   .NET Runtime:6.0.1

### Details

I'd like to call this function in my controller and i had a took System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. If i would't add PythonEngine.Shutdown(); it is working but only works one times and i tried to request one more time the controller does nothing

  ` using Newtonsoft.Json;
   using Python.Runtime;
   using System;
   using System.Collections.Generic;
   using System.Linq;
   using System.Runtime.Serialization;
   using System.Text;
  
   using System.Threading.Tasks;
  
   namespace AvukatProjectCore.Model
   {
       public class MyMachineLearningModel
       {
         
           public MyMachineLearningModel()
           {
             
           }
           public  void Initialize()
           {
               string pythonDll = @"C:\Users\0meng\AppData\Local\Programs\Python\Python39\python39.dll";
               string EnvPath = @"C:\Users\0meng\AppData\Local\Programs\Python\Python39";
               string pythonPath = @"C:\Users\0meng\AppData\Local\Programs\Python\Python39\Lib\site-packages\pythonnet";
               Environment.SetEnvironmentVariable("PYTHONNET_PYDLL", pythonDll);
               Environment.SetEnvironmentVariable("PATH", EnvPath, EnvironmentVariableTarget.Process);
               Environment.SetEnvironmentVariable("PYTHONHOME", EnvPath, EnvironmentVariableTarget.Process);
               Environment.SetEnvironmentVariable("PYTHONPATH", pythonPath, EnvironmentVariableTarget.Process);
   
               PythonEngine.Initialize();
              
           }
           public string CallPythonFunction(string question, string[] questions)
           {
               string result;
               
               Initialize();
               
   
               using (Py.GIL())
               {
                   Py.CreateScope();
                   // Vectorize the questions using TfidfVectorizer
                   dynamic sklearn = Py.Import("sklearn");
                   dynamic a = Py.Import("sklearn.feature_extraction.text");
                   dynamic b = Py.Import("sklearn.metrics.pairwise");
                   dynamic vectorizer = a.TfidfVectorizer();
                   dynamic vectors = vectorizer.fit_transform(questions);
   
                   // Vectorize the query
                   dynamic query_vector = vectorizer.transform(new[] { question });
   
                   // Calculate cosine similarity between the query and all questions
   
                   dynamic similarities = b.cosine_similarity(query_vector, vectors);
   
                   // Get similar questions with similarity score above a threshold
                   var threshold = 0.1;
                   var similarQuestions = new Dictionary<string, double>();
                   for (int i = 0; i < similarities.shape[1].As<int>(); i++)
                   {
                       if (similarities[0][i] > threshold)
                       {
                           similarQuestions[questions[i]] = similarities[0][i];
                       }
                   }
   
                   // Serialize and return the result
                   result = JsonConvert.SerializeObject(similarQuestions);
                   
               }
               PythonEngine.Shutdown();
               return result;
           }
      } 
  } 
` 
 
` [HttpGet]
         public async Task<IActionResult> All([FromQuery] string question)
         {
             var questions = (await _service.GetAllAsync()).Select(q => q.Question).ToArray();
             MyMachineLearningModel model = new MyMachineLearningModel();
             var result = model.CallPythonFunction(question,questions);
             
         }
`

**Comment by lostmsu** [comment]
Similar issue https://github.com/pythonnet/pythonnet/issues/2149
