### ISSUE TITLE
`import clr` throw error when python path contain Chinese chars

### ISSUE THREAD

**Issue by link89** [pythonnet/pythonnet#2141]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.8.10
-   Operating System: Windows 11
-   .NET Runtime: 

### Details
I find that everything just works fine if Python path doesn't contains any Chinese characters. But if the path contain some Chinese chars, let's said, start a python interactive shell via the following command:
```bash
D:\中文测试\CCInsight\python-3.8.10-embed-amd64\python.exe
```
And then when I run `import clr`, the following error will be raised.
```
>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\中文测试\CCInsight\python-3.8.10-embed-amd64\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "D:\中文测试\CCInsight\python-3.8.10-embed-amd64\lib\site-packages\pythonnet\__init__.py", line 143, in load
    if func(b"") != 0:
  File "D:\中文测试\CCInsight\python-3.8.10-embed-amd64\lib\site-packages\clr_loader\types.py", line 64, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```
I delivery a software that provide a GUI depends on pythonnet, this become an annoy bug as user may choose their own installation location, which may contain Chinese chars. Hope to find a fix or a work around. 

Update: 

I try to narrow down the scope of code to 

https://github.com/pythonnet/clr-loader/blob/master/clr_loader/netfx.py#L36-L44 

It looks to me like the `_get_callable` failed to get the right callabe object by the following args
```
assembly_path:  d:\中文测试\CCInsight\python-3.8.10-embed-amd64\lib\site-packages\pythonnet\runtime\Python.Runtime.dll
typename:          Python.Runtime.Loader
funcname:          Initialize
```

**Comment by filmor** [comment]
This is fixed in clr-loader 0.2.6

**Comment by 522247020** [comment]
Environment
Pythonnet version: 3.0.1
Python version: 3.10.9
pyinstaller version: 5.12.0
Operating System: Windows 10

使用 `pyinstaller` 打包时，如果路径出现中文，打包后打开也会报这个错误！
修改路径不包含中文就可以打开。

---
When using `pyinstaller` to package, if the path appears Chinese, the error will also be reported after the package is opened!
If the path does not contain Chinese, you can open it.


ok:

![image](https://github.com/pythonnet/pythonnet/assets/38172233/1479dd92-7804-4a27-979e-b5f7610fff75)

ng:

![image](https://github.com/pythonnet/pythonnet/assets/38172233/69161c62-8426-4c51-9fac-d5f1232e25b6)


@filmor

**Comment by link89** [comment]
@522247020 I think ` pip install clr-loader==0.2.6` should fix your problem.
