### ISSUE TITLE
Memory leakage during import clr

### ISSUE THREAD

**Issue by AnnaSummer** [pythonnet/pythonnet#2144]
`###` Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.10.9
-   Operating System: Debian 11
-   .NET Runtime:  Microsoft.NETCore.App 7.0.5

### Details

-   Hello, I'm trying to run to run python application with C# functions at docker container. 
-  The base image is debian 11 with python3.10.9. Then I installed dotnet-sdk-7.0 based on instructions in https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian. Then I installed pycparser, pythonnet and other modules (such as flask and so on).

-   The code lines:
```python
from clr_loader import get_coreclr
from pythonnet import set_runtime
os.environ["DOTNET_ROOT"] = "/usr/share/dotnet"
rt = get_coreclr(runtime_config="runtimeconfig.json")
import clr
```
First lines of code works perfectly, but 'import clr' line causes memory leakage. There is not error, just it works as endless cycle.

**Comment by filmor** [comment]
A second `import clr` is a no-op.

**Comment by AnnaSummer** [comment]
Excuse me, but I don't understand. What does "second" mean?
I need to import dll: clr.AddReference('System.Management.Automation')
So how it should be done without "import clr"?
