### ISSUE TITLE
i have a solution for "ModuleNotFoundError: No module named" but i don't know if it is a bug

### ISSUE THREAD

**Issue by andreabisello** [pythonnet/pythonnet#2148]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.11
-   Operating System: windows 11 full updated
-   .NET Runtime:  4.7.1

### Details

-   Describe what you were trying to get done.

    I'm trying to load a class definition from a .dll but even if the loading of the dll looks fine the namespace and class definition is not loaded.

This is the dll

![image](https://user-images.githubusercontent.com/2149815/233605369-22d161c1-151e-409a-86f1-70c5d1d4f786.png)

and this is what happens after the loading of the dll: namespace is not loaded even if there are no exception

![image](https://user-images.githubusercontent.com/2149815/233606879-5f1f9c12-e598-4655-8707-70a0986680e2.png)

but this is related with some missing dependencies, because if i take all the dll and other file related with the project and i try the same, then the namespace is loaded and the class definition appears.

![image](https://user-images.githubusercontent.com/2149815/233607587-fd2c02ee-8c79-47c0-bb1b-3f557aaf1ec2.png)

in another project, the framework was complaining for a missing dll, but in this case no. everything looks working, but instead there is something missing.

i think this is a bug.

is this a bug?

thanks

**Comment by Balnian** [comment]
I'm having the same problem. 
Python: 3.7
I can load the assembly when there is no dependency to the project and it's a relatively trivial library (ex: just returning a string from a method).
As soon as I add dependencies and dotnet publish next to my python script I get:
```
Exception has occurred: ModuleNotFoundError
No module named 'EARipper'
```
![image](https://user-images.githubusercontent.com/7544338/233765258-6ade784e-7093-47c7-9079-1d44e3c3b30e.png)

**Comment by andreabisello** [comment]
@Balnian yeah but i don't know why, in another project, pythonnet was suggesting me that a dll (Newtonsoft.Json) was not loaded, so i added and it worked.

**Comment by Balnian** [comment]
I ended up solving my problem by doing the following before the `import clr`
```python
from pythonnet import load
load("coreclr")
```
This changes the runtime for windows from the `netfx` to `coreclr` since I'm targeting `net7.0`

**Comment by lostmsu** [comment]
There's no minimal repro, so this is not a valid issue. There's no way for us to know if the head post followed proper configuration steps.

**Comment by andreabisello** [comment]
Hi,
To reproduce simply two line of code are required.
I'm going to ask to the developers If I can share the DLL. 
Thanks

**Comment by LeoLTM** [comment]
> I ended up solving my problem by doing the following before the `import clr`
> 
> from pythonnet import load
> load("coreclr")
> 
> This changes the runtime for windows from the `netfx` to `coreclr` since I'm targeting `net7.0`

I have the same problem you had where pythonnet won't find the module if it includes any depencies...
Unfortunately, your fix doesn't work for me :/
