### ISSUE TITLE
Why is there a `.gitignore` file included in the binary distribution?

### ISSUE THREAD

**Issue by siegfriedpammer** [pythonnet/pythonnet#2150]
We have unit tests that fail if there are unexpected files in the binary distribution of our project. A `.gitignore` does not seems necessary for the function of `pythonnet`.

Proposed fix: https://github.com/pythonnet/pythonnet/commit/3b5a24890021b6c748fddd95024257cfefec12e5 (entirely untested)

NOTE: Unfortunately, I cannot provide a PR, because I don't have the time to jump through the hoops of the .net fdn to get CLA signed for a one-line meta-change. Also **the link to the CLA in the PR template is not working** for me.

If it is possible to submit a pull request by simply stating that I forfeit all rights or similar in the PR comment, then I will gladly do so.

**Comment by filmor** [comment]
I'll just cherry-picked your commit onto `master`, thanks :)
