### ISSUE TITLE
Multiple namespaces does not load

### ISSUE THREAD

**Issue by adahox** [pythonnet/pythonnet#2151]
### Environment

-   Pythonnet version:  3.0.1
-   Python version:  3.11
-   Operating System: Windows 11 64 bits
-   .NET Runtime:
   - Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
   - Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
   - Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
   - Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
   - Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
   - Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
### Details

-   Trying to load a DLL with cascaded namespaces like "Namespace1.Namespace2"

    _TODO_

-   I've created a small python script to load the dll but its fails like description above.
 
the dll:
```C#
namespace OwlLibrary.HereWeHaveChoice
{
    public class InterfaceIntegration
    {
        public InterfaceIntegration() {
            Console.WriteLine("Loaded Library");
        }

        public string getClient()
        {
            return "1.0.0.0";
        }
    }
}
```

the python script:
```python
import sys
import clr

class DLLoader:
    def __init__(self, dllName: str, dllPath: str):
        self.dllName = dllName
        self.dllPath = dllPath
        self.__load_library__()

    def __load_library__(self):
        sys.path.append(self.dllPath)
        clr.AddReference(self.dllName)

dlloader = DLLoader('OwlLibrary','c:/dev/dll/lib')


from OwlLibrary.HereWeHaveChoice import InterfaceIntegration

client = InterfaceIntegration()
```

the result:
`ModuleNotFoundError: No module named 'OwlLibrary' `

but the module its almost there.

**Comment by lostmsu** [comment]
> `sys.path.append(self.dllPath)`

That's not how .NET searches DLLs on Windows.

**Comment by adahox** [comment]
how thats not how .NET  searches DLLs on Windows ?

i just followed the example on the wiki: 

https://github.com/pythonnet/pythonnet/wiki/How-to-call-a-dynamic-library

**Comment by felixb-croesus** [comment]
I am having the exact same problem. Did you find a solution?
