### ISSUE TITLE
Support calling objects extensions from an object rather than class

### ISSUE THREAD

**Issue by piszczu4** [pythonnet/pythonnet#2152]
Are there any plans to support object extensions called from an object rather than a class? I mean if in C# I have an `ObjectExtensions` class with method `DoSth(this MyClass obj)`, then I can't call it in Python via `myObj.DoSth()` and I have to use `ObjectExtensions.DoSth(myObj)`.

**Comment by filmor** [comment]
There is already a ticket for this, #55. PRs are (very) welcome, but there is to my knowledge no one working on this.
