### ISSUE TITLE
Error loading Python DLL with PythonEngine

### ISSUE THREAD

**Issue by Thyssen1** [pythonnet/pythonnet#2155]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.10.9
-   Operating System: Windows
-   .NET Runtime: 7.0.100

### Details

I set the Runtime.PythonDLL to the path to the python DLL and then ran PythonEngine.Initialize() followed by the code from the MNIST example on the Keras.NET GitHub.
However, I get an MissingMethodException: Failed to load symbol Py_IncRef even though the DLL does exist.

See MNIST code on Github (scroll down): https://github.com/SciSharp/Keras.NET

**Comment by filmor** [comment]
Keras.NET uses a fork of Python.NET, please ask there.
