### ISSUE TITLE
Misunderstood the issue.

### ISSUE THREAD

**Issue by ItamarIn** [pythonnet/pythonnet#2161]
About the issue: [https://github.com/pythonnet/pythonnet/issues/2160](https://github.com/pythonnet/pythonnet/issues/2160)

The issue is the missing support for python 3.12, the pythonnet version is not relevant here.

**Comment by filmor** [comment]
I understand the issue perfectly well. PRs are welcome, I will not woek on this before the release candidates of Python 3.12.
