### ISSUE TITLE
TypeError: '__ComObject' object is not iterable

### ISSUE THREAD

**Issue by Skyapip** [pythonnet/pythonnet#2163]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.6, 3.8 & 3.10
-   Operating System: Windows
-   .NET Runtime:

### Details
- I'm upgrading my project to python 3.10 and while doing that I had to update pythonnet version from 2.5.2 to latest (3.0.1). After upgrading pythonnet version I'm facing the issue while iterating system.__ComObject in python. With 2.5.2 it was working fine but now it is not working. I'm not sure what can I do to resolve this issue as I've tried casting, used iterable methods but didn't work. I checked with python 3.6, 3.8, 3.10, they all had same issue after upgrading pythonnet to 3.0.1. I tried 3.0.0 versions as well but same results. 

I have this InvokeProperty method which is being called in python. This method may return data in string/int/object type.
C#:
```c#
public static object InvokeProperty(string name, object arg, object o, Type t)
    {
        ...
        var value = type.InvokeMember(name, binding, null, o, args);
        return value;
        ...
    }
```
Python:
```python
    data = Component.InvokeMethod(name, args, object, type)
    for item in data  # while convert: C# -> Python --> TypeError: '__ComObject' object is not iterable
        print(item)
```

- So, whenever returned data from c# is in string/int format I don't need to iterate over so I can print them directly without any issue. But in case it is object then I'm facing issue of not iterable object.

**Comment by filmor** [comment]
You'll have to cast it explicitly to the correct interface. That is the only relevant change between Python.NET 2 and 3 that applies here. `System.__ComObject` is a bit magic in the sense that it just implements "all" interfaces that the underlying concrete type supports.

**Comment by Skyapip** [comment]
okay, I have a question about casting. Could you please let me know if casting is done in Python or C#? It would be really helpful if you could provide an example. Also, it is working in 2.5.2 but not in >=3.0.0. So, I'm curious can't pythonnet provide supports for it.
