### ISSUE TITLE
Add Pythonnet __version__ variable

### ISSUE THREAD

**Issue by vmuriart** [pythonnet/pythonnet#218]
It may be user error, but I was troubleshooting of my co-worker's machines and couldn't figure out how to send him a script that would return the version number of `Pythonnet` they were using from within Python. 

Im thinking something in the lines of

```python
import clr
print(clr.__version__)
```

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/issues/67

**Comment by vmuriart** [comment]
closing to avoid repetition.
