### ISSUE TITLE
Update "Embedding python into .NET" documentation to reflect new way to import modules

### ISSUE THREAD

**Issue by sanzoghenzo** [pythonnet/pythonnet#2187]
### Environment

-   Pythonnet version: 3.0.1

### Details

I'm trying to upgrade [pyRevit](https://github.com/eirannejad/pyRevit) to use the latest pythonnet version, since it is still using version 2.5.2 which causes many problems for those who wants to run cpython scripts.

After updating the dependency, the compiler complains about the missing `PythonEngine.ImportModule` method, even if this is still what the [documentation](https://pythonnet.github.io/pythonnet/dotnet.html) says to use.

Only after an extensive search in the commit history I saw that that method was deprecated in favor of `PyModule.Import`, but the deprecation is already removed (too soon if you ask me).

Please update the documentation to reflect this (and maybe more breaking changes that I didn't catch yet?)

**Comment by filmor** [comment]
Fixed in https://github.com/pythonnet/pythonnet/commit/dddadbe78ef0fba3e8ffde30c466f224dbbc9aea.
