### ISSUE TITLE
[feature request] Bindings to Roslyn csc.dll or example in docs of using Roslyn to compile a C# file or a code snippet in a string

### ISSUE THREAD

**Issue by vadimkantorov** [pythonnet/pythonnet#2196]
For .NET Core embedding into Python, it is useful in educational/hack scenarios to allow the user to allow the user to not compile the C# code beforehand. E.g. a solution would be a Python binding (or docs example) to Roslyn/csc.dll of calling it from python to compile a C# code file or code snippet (without saving it to a file). An alternative would be binding to CSharpScript technology of Roslyn.

Originally discussed at https://github.com/pythonnet/pythonnet/discussions/2195

In my example there https://gist.github.com/vadimkantorov/c9ab97aff995ea01ea7f6248ddc733bc I first prepare the compilation string, then compile the csharp code in `csharpfrompython.sh`, and only then call clr.AddReference in the python code. It would be great to call the compiler directly from the python code and have nice bindings to even maybe not store the assembly on disk and add it to clr.AddReference directly.

Maybe the API could be `clr.CompileAndAddAssembly(code files, code snippets, compiler options, reference assemblies and other csc options)` or sth similar

**Comment by filmor** [comment]
This is out of scope for Python.NET.

**Comment by vadimkantorov** [comment]
An example in docs would be nice though.

For instance, as you can see in https://gist.github.com/vadimkantorov/c9ab97aff995ea01ea7f6248ddc733bc#file-csharpfrompython-sh the path discovery is a beast:

```shell
DOTNETSDKVER=$("$DOTNET_ROOT/dotnet" --version)
DOTNETFWKVER=$("$DOTNET_ROOT/dotnet" --list-runtimes | grep Microsoft.NETCore.App | tail -n 1 | cut -d' ' -f2)
DOTNETLIBDIR="$DOTNET_ROOT/shared/Microsoft.NETCore.App/$DOTNETFWKVER"
"$DOTNET_ROOT/dotnet" "$DOTNET_ROOT/sdk/$DOTNETSDKVER/Roslyn/bincore/csc.dll" $(find "$DOTNETLIBDIR" -name "*.dll" -printf '-r:"%p" ')  -target:library -out:csharpfrompython.dll csharpfrompython.cs
```

If these paths are available somewhere under the `clr` module, calling the Roslyn compiler from `pythonnet` would be much simpler
