### ISSUE TITLE
`import clr` not working on Windows 7

### ISSUE THREAD

**Issue by lgmventura** [pythonnet/pythonnet#2200]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.8
-   Operating System: Windows 7
-   .NET Runtime: 4.6.2

### Details

-   trying to import `clr`

```python
    import clr
```

```python
    Traceback (most recent call last):

Cell In[1], line 1
    import clr

File ~\Documents\envs\py38\lib\site-packages\clr.py:6
    load()

File ~\Documents\envs\py38\lib\site-packages\pythonnet\__init__.py:143 in load
    if func(b"") != 0:

File File ~\Documents\envs\py38\lib\site-packages\clr_loader\types.py:64 in __call__
    return self._callable(ffi.cast("void*", buf_arr), Len(buf_arr))

RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

This environment was created on a Windows 10 machine and transferred onto this Windows 7 one. The import was working on the win 10 machine.

**Comment by filmor** [comment]
.NET Runtime 4.6 is not supported anymore.

**Comment by lgmventura** [comment]
@filmor could you please document somewhere what versions of .NET runtime, core and framework are supported by which versions of pythonnet? It is not clear for the user.
