### ISSUE TITLE
PythonEngine.Initialize() crash

### ISSUE THREAD

**Issue by ekicyou** [pythonnet/pythonnet#2201]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.11.1
-   Operating System: Windows 10
-   .NET Runtime: net6.0-windows

### Details
`PythonEngine.Initialize()` crash the app without throwing any exceptions. What should I do to get support?

-   last visual studio debug output.

```
'xxxx.exe' (CoreCLR: clrhost): '__Python_Runtime_Generated_Assembly0' が読み込まれました。
プログラム '[26812] xxxx.exe' はコード 1 (0x1) で終了しました。
```

**Comment by filmor** [comment]
This is not a support forum. You can ask questions in the "Discussions" Q&A section, but you will have to provide a *lot* more information for anyone to actually be able to help you.

**Comment by ekicyou** [comment]
Thank you @filmor.

Unfortunately, the phenomenon does not occur enough to provide more information. Die silently. Isn't it an issue that `PythonEngine.Initialize()` exits 1 without throwing an exception or printing a debug message?
