### ISSUE TITLE
Unload behaving strangely with `del` keyword

### ISSUE THREAD

**Issue by Miepee** [pythonnet/pythonnet#2202]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.11.3
-   Operating System: Arch Linux
-   .NET Runtime: Microsoft.NETCore.App 7.0.9 

### Details

-   Describe what you were trying to get done.

    I was trying to use a c# wrapper and clean up all imported resources after using them. After loading, unloading, and then loading again, pythonnet segfaults or spews out `System.AccessViolationException`'s. Not that familiar with python, so maybe this isn't supposed to be done, but figured a segfault from python code shouldn't even happen.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
from pythonnet import load, unload

# first load
try:
  load("coreclr")
  import clr
  from System import String as foo
# first unload
finally:
  del foo
  unload()
  del clr

# second load
try:
  load("coreclr")
  import clr
  from System import String as foo
  bar = foo()
  print(bar)
# second unload
finally:
  del foo
  unload()
  del clr
```

-   If there was a crash, please include the traceback here.

```python
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt64(IntPtr, Int32)
   at System.Runtime.InteropServices.Marshal.ReadIntPtr(IntPtr, Int32)
   at Python.Runtime.Util.ReadIntPtr(Python.Runtime.BorrowedReference, Int32)
   at Python.Runtime.ManagedType.TryFreeGCHandle(Python.Runtime.BorrowedReference, Python.Runtime.BorrowedReference)
   at Python.Runtime.ManagedType.TryFreeGCHandle(Python.Runtime.BorrowedReference)
   at Python.Runtime.Runtime.NullGCHandles(System.Collections.Generic.IEnumerable`1<IntPtr>)
   at Python.Runtime.Runtime.Shutdown()
   at Python.Runtime.PythonEngine.Shutdown()
   at Python.Runtime.Loader.Shutdown(IntPtr, Int32)

zsh: IOT instruction (core dumped)  python
```

Trying to get a backtrace with gdb wasn't successfull to me.

**Comment by Miepee** [comment]
Not sure if the same/related, but sometimes the backtrace also looks like this:
![grafik](https://github.com/pythonnet/pythonnet/assets/38186597/1c486b00-e21c-4395-8af9-107a2c9b47bb)

**Comment by filmor** [comment]
Reloading is not supported (and I think this is also caught in `master`, we have to cut a release).

**Comment by Miepee** [comment]
Is there a reason stated somewhere, as to why it's unsupported?
My use case is that a rarely used action in a python program, needs to execute a c# program. So my thought process was "when button pressed -> load clr -> execute c# progam -> unload clr and everything that was loaded in". is the only solution there to just always keep it in memory? because i was trying to avoid that.
