### ISSUE TITLE
Initialize() crash from .NET Framework application

### ISSUE THREAD

**Issue by anovik** [pythonnet/pythonnet#2205]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.10
-   Operating System: windows 11/10
-   .NET Runtime: NET Framework 4.6.1

### Details

I am trying to call Python code from .NET Framework app but on some machines PythonEngine.Initialize() crashes.

```
Runtime.PythonDLL = "C:\\Python\\Python310\\python310.dll";
PythonEngine.Initialize();
```

Exception:

System.TypeInitializationException: 'The type initializer for 'Delegates' threw an exception.'

There are two inner exceptions:

DllNotFoundException: Could not load C:\Python\Python310\python310.dll.
Win32Exception: %1 is not a valid Win32 application

The path is correct and the dll exists.

![image](https://github.com/pythonnet/pythonnet/assets/8667411/76731411-e0ee-4975-b868-1a4e597cb8f7)

**Comment by filmor** [comment]
.NET Framework 4.6 is not supported, use at least 4.7.2, please. Even if it was, the issue hints that your .NET Framework application is compiled for a different bitness (.NET defaults to 32bit).
