### ISSUE TITLE
python cann't connect to the database when use the method from dll.

### ISSUE THREAD

**Issue by Wuhaotiandl** [pythonnet/pythonnet#2207]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.7 (64bit)
-   Operating System: win10 
-   .NET Runtime: 4.7.2

### Details

I got an error calling a method from dll in a python project.  
Here is my C# code
```
namespace TestConnect_2
{
    public class myTestConnect
    {
        public QA_DeliveryExamination LetTest()
        {
            Console.WriteLine("This is a Test2！");
            try
            {
                using (SecVerificationContext dbContext = new SecVerificationContext())
                {
                    var deliveryExamination = dbContext.DeliveryExaminations.FirstOrDefault();
                    return deliveryExamination;
                }
            }
            catch (Exception ex) { Console.WriteLine($"{ex.ToString()}"); return null; }
        }
    }
}
```

Here is my python code 
```python
import clr
clr.AddReference("TestConnect_2")
from TestConnect_2 import myTestConnect

_myConnect = myTestConnect()
cat =  _myConnect.LetTest() 
```

When I run the python code , I got an error. It seems that  when I initialized the SecVerificationContext , it cann't connect to the database?   but I have the App.config file in my project.

```python
 System.InvalidOperationException: No connection string named 'ConnSecVerification' could be found in the application config file.
   �� System.Data.Entity.Internal.LazyInternalConnection.get_ConnectionHasModel()
   �� System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   �� System.Data.Entity.Internal.InternalContext.Initialize()
   �� System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   �� System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   �� System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   �� System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   �� System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
```

**Comment by filmor** [comment]
`app.config` files only work if they are next to your executable, which in this case is `python.exe`. The planned mechanism for this was to allow .NET Framework to be initialised with a separate AppDomain, but the respective code is currently buggy (see pythonnet/clr-loader).

This should give you some insight in how to load the `app.config` from a different location:
https://stackoverflow.com/questions/6150644/change-default-app-config-at-runtime

**Comment by Wuhaotiandl** [comment]
can

**Comment by Wuhaotiandl** [comment]
I have put the App.config next to python.exe.  However it dosen't work ..
