### ISSUE TITLE
Working with DLLs on Windows

### ISSUE THREAD

**Issue by kuraga** [pythonnet/pythonnet#221]
Good day!

I have a C# dll. Seems like it is `x86 .NET Framework 4.6` type.

I can import it via `clr.System.Reflection.Assembly.LoadFile` on x86 Windows **but** have an Exception on x64 Windows.

Do you know how to use it on x64 Windows?

Thanks.

**Comment by denfromufa** [comment]
Good day,


Can you have a look at this wiki and let me know if it does not help:


https://github.com/denfromufa/pythonnet/wiki/Troubleshooting-FAQ


In your case make sure that bitness of python matches .NET dll bitness.


Have not come across x86 Windows (7?) for long-time! BTW, your last 2
sentences seem contradictory.


Please report your exception here, especially from assembly binding log
viewer.

**Comment by kuraga** [comment]
@denfromufa 

> In your case make sure that bitness of python matches .NET dll bitness.

So clever, so simple... I'm a donkey. Thanks very much! :smile:

**Comment by kuraga** [comment]
@denfromufa sorry, one more question, please!

.Net DLL (say `main.dll`) I spoke about also imports some other DLL `second.dll`. Decompiler (DotPeek) informs about code: `[DllImport('second.dll', ...)]` and says that `second.dll` is not .Net DLL.

But I get `System.DllNotFoundException` if I call method which imports `second.dll`. But `second.dll` exists in current directory...

What to do?.. Thanks :cry:

**Comment by denfromufa** [comment]
@kuraga is it possible that managed dll is AnyCPU, but unmanaged (native) DLL does not match python bitness? Anyway use assembly binding log viewer.

**Comment by kuraga** [comment]
@denfromufa thought about bitness and tried on x64 an on x86 - the same.

> Anyway use assembly binding log viewer.

How can I do it?

**Comment by denfromufa** [comment]
https://www.google.com/search?q=assembly+binding+log+viewer&oq=assembly+binding+log+viewer&sourceid=chrome&ie=UTF-8

On Wed, Jun 1, 2016 at 12:41 PM, Alexander Kurakin <notifications@github.com

**Comment by kuraga** [comment]
Yes, sorry thought that it's Python.NET special. Sorry.

**Comment by denfromufa** [comment]
can you use the methods from this native (unmanaged) DLL from C#, when no
pythonnet is involved?

On Wed, Jun 1, 2016 at 12:44 PM, Alexander Kurakin <notifications@github.com

**Comment by kuraga** [comment]
It's difficult to understand - it's closed source library and I'm just Python (not .Net) programmer :smile: Seems like `second.dll` is "private API" DLL...

**Comment by kuraga** [comment]
Ah, without Python... Yes seems like I have to try. Have no other option.

**Comment by denfromufa** [comment]
you can use csi (in VS 2015 Update 1 or 2, only 32bit!) or scriptcs REPL to
do this interactively like in python.

On Wed, Jun 1, 2016 at 12:53 PM, Alexander Kurakin <notifications@github.com

**Comment by kuraga** [comment]
Seems like it was that DLL problem: C# causes the same error. Interesting that logs don't contain `"second.dll"` substring...
