### ISSUE TITLE
PythonEngine.Initialize() fails

### ISSUE THREAD

**Issue by hbmartinez** [pythonnet/pythonnet#2229]
### Discussed in https://github.com/pythonnet/pythonnet/discussions/2228

<div type='discussions-op-text'>

<sup>Originally posted by **hbmartinez** August 31, 2023</sup>
Python interpreters persist their previously cached modules. 

After one successful initialization and run of a module I am trying to reinitialize/restart the PythonEngine. 

Reloading the module is not an option because it causes side effects. 

Reinitialization is the only path forward but I am getting a metaclass conflict exception when PythonEngine.Initialize() is called a second time.

Is it even possible to reinitialize the PythonEngine (PythonEngine.Initialize()) after its been initialized once?

example code below... exception attached. I'm using Python.Net with Python 3.11

            Runtime.PythonDLL = "dll location here";

            for (var i = 0; i < 2; i++)
            {
                PythonEngine.Initialize();
                var allowThreads_ = PythonEngine.BeginAllowThreads();

                using (Py.GIL())
                {
                    using (var scope = Py.CreateScope())
                    {
                        try
                        {
                            // Invoke python module here
                        }
                        catch (Exception e)
                        {
                            throw new Exception(e.Message);
                        }
                        finally
                        {
                            Debug.WriteLine(string.Format("Run {0} of {1}", i, 2));
                        }
                    }
                }
                PythonEngine.Shutdown();
                PythonEngine.EndAllowThreads(allowThreads_);
            }

![pythonNet exception](https://github.com/pythonnet/pythonnet/assets/90009974/9dcb2e06-7cbf-4797-929b-ef6d67998607)

</div>

**Comment by filmor** [comment]
I don't think that this is case that we can or want to support without major refactoring. Additionally, you are not providing a reproducible example which makes everything guess-work. The metaclass is *created* (each time) when we run `Initialize`. There is also a lot of additional code in `Initialize` and `Shutdown` that would need to be checked for "re-entry".

I would not be against a PR that does this (provided it's handled in a safe fashion), but I will not do the work myself.
