### ISSUE TITLE
Make exc.__cause__ return InnerException in Python 3

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#223]
Python 3 has a direct(?) match of the `InnerException` property from .NET, namely the `__cause__` property, which results in much nicer and more informative tracebacks.

**Comment by filmor** [comment]
I'll add this as soon as #286 is merged. We are setting a slot there anyhow (`args`), we might as well extend this.

**Comment by denfromufa** [comment]
@filmor I merged #286

**Comment by filmor** [comment]
Closed by #287.
