### ISSUE TITLE
Pythonnet does not work on Raspberry Pi

### ISSUE THREAD

**Issue by crazyoutlook** [pythonnet/pythonnet#2235]
### Environment

-   Pythonnet version: 3.9
-   Python version: 3.9
-   Operating System: Debian Buster
-   .NET Runtime: 6.0

### Details

-   Trying to run Pythnnet 3.9 for Linux. I have a Dot Net core 6.0 solution which is using Pythonnet 3.9 for Linux. 
- 
- Getting error "Could not load file or assembly 'Python.Runtime, Version=2.5.2.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format "

    _TODO_

-   Tried to run a dot net core 6.0 solution which used pythonnet 3.9 for linux.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

- Getting error "Could not load file or assembly 'Python.Runtime, Version=2.5.2.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format "
- 
```python
    print('TODO')
```

**Comment by filmor** [comment]
You're using an old version, try pythonnet 3. Only ARM64 is tested, though.

**Comment by crazyoutlook** [comment]
Hi,

Thank you for your response. We are testing it on ARM64. Also - will this DLL also work on Linux based systems for Intel/AMD processors?

**Comment by filmor** [comment]
Yes, the DLL is platform-independent.
