### ISSUE TITLE
Python virtual environment is not accessible getting error when setup pythonpath.

### ISSUE THREAD

**Issue by yogeshGovindaraj** [pythonnet/pythonnet#2241]
### Environment

-   Pythonnet version: 3.0.2
-   Python version:3.11
-   Operating System: Any(Windows/Linux)
-   .NET Runtime: 6.0

### Details

-   Try to setup multiple virtual environments in python which can be accessible from pythonnet in my dotnet application. 

    _TODO_

-   Added latest pythonnet from nuget package in my dotnet application.
-   Created virtual environment in python version 3.11.
-   Activated the python version.
-  Below is code to access the virtual environment from my dotnet application .

            Runtime.PythonDLL = deviceDetails.PythonVersion;
            Environment.SetEnvironmentVariable("path", pathToVirtualEnv, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("pythonhome", pathToVirtualEnv, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("pythonpath", $"{pathToVirtualEnv}\\Lib\\site-packages;{pathToVirtualEnv}\\Lib", EnvironmentVariableTarget.Process); 
            PythonEngine.PythonPath =  Environment.GetEnvironmentVariable("pythonpath", EnvironmentVariableTarget.Process);
            PythonEngine.PythonHome = pathToVirtualEnv;
            PythonEngine.Initialize();
            PythonEngine.BeginAllowThreads();

- Getting the below error:
- 
-   Python path configuration:
  PYTHONHOME = 'Local Python home path'
  PYTHONPATH = (not set)
  program name = 'python'
.......
..................
......................
..........
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

"Checked encodings package in already import in the virtual environment but getting the above error"

**Comment by filmor** [comment]
This has nothing to do with Python.NET itself.
