### ISSUE TITLE
Setting Multiple Virtual Environment with Python in C#

### ISSUE THREAD

**Issue by yogeshGovindaraj** [pythonnet/pythonnet#2242]
### Environment

-   Pythonnet version: 3.02
-   Python version:3.11
-   Operating System: Any(Windows 11/Linux)
-   .NET Runtime: 6.0

### Details

-   P.S: I have created a virtual environment for python version 3.11 and installed numpy package using pip install.
-    Need to run python code from my dotnet project by setting up local python 3.11 virtual environment.
-   I have taken the reference code for creating virtual environment from [(https://github.com/pythonnet/pythonnet/wiki/Using-Python.NET-with-Virtual-Environments)] and created  a sample dotnet project to refer the local python virtual environment and import library from there.
-  Written the below code
          ..............
-         Runtime.PythonDLL = [path of pythonversion dll]
            var path = Environment.GetEnvironmentVariable("PATH").TrimEnd(';');
           path = string.IsNullOrEmpty(path) ? pathToVirtualEnv : path + ";" + pathToVirtualEnv;
            Environment.SetEnvironmentVariable("PATH", path, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONHOME", pathToVirtualEnv, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONPATH", $"{pathToVirtualEnv}\\Lib\\site-packages;{pathToVirtualEnv}\\Lib", 
           EnvironmentVariableTarget.Process);
             PythonEngine.Initialize();
           PythonEngine.PythonHome = pathToVirtualEnv;
            PythonEngine.PythonPath = PythonEngine.PythonPath + ";" +Environment.GetEnvironmentVariable("PYTHONPATH", EnvironmentVariableTarget.Process);
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                 ...
             }
-  the  library is imported from base location instead of virtual environment location. Any suggestions why pythonnet is not importing files from base location.

**Comment by filmor** [comment]
This has nothing to do with Python.NET, please consult the Python embedding documentation on how to use the environment variables.
