### ISSUE TITLE
pyhtonnet eating arguments from interfaces 

### ISSUE THREAD

**Issue by dk00001101** [pythonnet/pythonnet#2244]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.10.0
-   Operating System: win10 enterprise 64bit Version 10.0.19045 Build 19045

-   .NET Runtime:
- 
Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App
7.0.304 [C:\Program Files\dotnet\sdk]

I have got an C# dll, which i cannot change or adapt. I have to use it as it comes. I want to use some parts of the C# code in python. 
This were the first tests to import it into my python code. 
Actually i was just loading the dll and importing the classes and methods from the dll.

I have found this:
https://pythondotnet.python.narkive.com/rM4AvGnc/python-net-issue-disambiguating-overloaded-method-that-takes-an-array
and it seems to be on point. It exactly describes what the problem is, but how can I fix it?

So here is the C# Code from the DLL. I have made a minimal example: 

```csharp

using System;
using System.Collections.Generic;

namespace MachinePilotAPI
{
    /// <summary>
    /// Called when a Machine Pilot button is added to the list of buttons that can be pressed.
    /// </summary>
    public delegate void SomeRemovedHandler(string name);

    public interface SomeMachine
    {
        event SomeRemovedHandler ButtonRemoved;

        void Connect(string ipAdress, string password);

        List<string> DiscoverMachines();

        ///and so on..... 

    }
}

```
Here is the Python Example: 

```python
import clr
from pathlib import Path


clr.AddReference(r'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.dll')

dll_folder = Path(r'path to dll')

    
def import_all_dlls(to_dlls:Path):
    
    for dll_item in to_dlls.glob('*.dll'):
        
        clr.AddReference(str(dll_item))
        print(f'Imported {dll_item}')

# import all dlls
import_all_dlls(dll_folder)


import MachinePilotAPI as tpsdk
from System import String

        
class PyTrackerPilot(tpsdk.SomeMachine):
    __namespace__ = "MachinePilotAPI" ## Without this the inheritance wont work. 
    
    def __init__(self):
        super().__init__()
        print("PyTrackerPilot Object was created")
      
    def connect(self, ip, pw):
        self.Connect(ip, pw)  

if __name__ == '__main__':
    ip_address = "someIP"
    password = "somePW"

    
    tp_obj = PyTrackerPilot()
    
    # call try 1:
    tp_obj.connect(ip_address, password)
    
    # call try 2:
    
    tpsdk.SomeMachine.Connect(ip_address, password)
    
    # call try 3:
    
    tpsdk.SomeMachine.Connect(String(ip_address), String(password))

```

Traceback for call try 1:

Exception: NotImplementedException
Python object does not have a 'Connect' method
   bei Python.Runtime.PythonDerivedType.InvokeMethodVoid(IPythonDerivedType obj, String methodName, String origMethodName, Object[] args, RuntimeMethodHandle methodHandle, RuntimeTypeHandle declaringTypeHandle)
   bei MachinePilotAPI.PyTrackerPilot.Connect(String , String )
  File "XXXX", line 45, in connect
    self.Connect(ip, pw)
  File "XXXX", line 53, in <module>
    tp_obj.connect(ip_address, password)
System.NotImplementedException: Python object does not have a 'Connect' method
   bei Python.Runtime.PythonDerivedType.InvokeMethodVoid(IPythonDerivedType obj, String methodName, String origMethodName, Object[] args, RuntimeMethodHandle methodHandle, RuntimeTypeHandle declaringTypeHandle)
   bei MachinePilotAPI.PyTrackerPilot.Connect(String , String )

Traceback for call try 2:

Exception: TypeError
No method matches given arguments for SomeMachine.Connect: (<class 'str'>)
  File "XXXX", line 54, in <module>
    tp_obj_1 = tpsdk.SomeMachine.Connect(ip_address, password)
TypeError: No method matches given arguments for SomeMachine.Connect: (<class 'str'>)

Traceback for call try 3:
Exception: TypeError
No method matches given arguments for SomeMachine.Connect: (<class 'System.String'>)
  File "XXXX", line 55, in <module>
    tp_obj_1 = tpsdk.SomeMachine.Connect(String(ip_address), String(password))
TypeError: No method matches given arguments for SomeMachine.Connect: (<class 'System.String'>)

Ifi we have a look into the connect _doc_ via python we see:

```python
__doc__:
'Void Connect(System.String, System.String)'
```

Im really frustrated at the moment. Can someone help me please to fix this?

**Comment by filmor** [comment]
This wouldn't work in C# either. If you derive from an interface you have to implement all methods.

**Comment by dk00001101** [comment]
> This wouldn't work in C# either. If you derive from an interface you have to implement all methods.

But how can I use the C# Interface via the DLL in Python?

**Comment by dk00001101** [comment]
```python
obj_machine = tpsdk.SomeMachine()
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: interface takes exactly one argument

So if I call it like here, im getting this error.
