### ISSUE TITLE
multiple processes of program opening at specific point

### ISSUE THREAD

**Issue by mysticrain32** [pythonnet/pythonnet#2246]
### Environment

-   Pythonnet version: 3.1.0
-   Python version: 3.11.5
-   Operating System: Windows 10
-   .NET Runtime: 6.0

### Details

-  I am trying to implement YOLOv8 detection in Visual Basic by using pythonnet. However when I get to the line where I go to run the prediction, around 30-40 seperate processes open in my task manager (I can only see one window though). This makes it take way longer than it should to return by prediction result and it also opens that same amount of windows with results for each finished process. I cannot figure out what is causing this as whether I implement directly or simply call the python file from pythonnet, it always does the same thing. It runs just fine and within 1 second in standard python. 

    _TODO_

```
Imports System
Imports Python.Runtime

Public Class SimplePredict

    Public Shared Sub Main()

        ' Set the Python DLL path
        Runtime.PythonDLL = "-pathtodll-Local\Programs\Python\Python311\python311.dll"

        ' Initialize Python Engine
        PythonEngine.Initialize()

        ' Using the Python GIL (Global Interpreter Lock)
        Using Py.GIL()
            ' Import necessary libraries
            Dim ultralytics = Py.Import("ultralytics")
            Dim YOLO = ultralytics.GetAttr("YOLO")

            ' Load model
            Dim modelName As String = "path-to-model.pt"
            Dim model = YOLO.Invoke(modelName.ToPython())

            ' Predict on an image
            Dim loadedImage As String = "-path-to-image"
            Dim predictMethod = model.GetAttr("predict")
            Dim results = predictMethod.Invoke(New PyObject() {loadedImage.ToPython()})

        End Using

        ' Shutdown the Python Engine
        PythonEngine.Shutdown()
    End Sub
End Class
```
The issue arises as soon as the following line is called: Dim results = predictMethod.Invoke(New PyObject() {loadedImage.ToPython()})
Any help here is greatly appreciated, thanks!

**Comment by lostmsu** [comment]
This is not a bug related to Python.NET. You are using a 3rd party library - take it with them.
