### ISSUE TITLE
plt cause error when call from .net

### ISSUE THREAD

**Issue by zj2050** [pythonnet/pythonnet#2267]
### Environment

-   Pythonnet version: 3.1.0
-   Python version:3.11.3
-   Operating System:window
-   .NET Runtime:.core 6

### Details

defined a function in python must call plt to get hist feedback data , it's right in vs code , but call it from c#.net will take crash.

if delete code about plt, it's work ok

```python

        binlist = [i for i in range(450,1200,50)]
        f, ax = plt.subplots()
        n, bins, patches = ax.hist(rrData, bins = binlist)

```

-   If there was a crash, please include the traceback here.

![捕获1](https://github.com/pythonnet/pythonnet/assets/4464947/1ba6ffb9-0a01-4f29-a223-129a1533b366)

**Comment by filmor** [comment]
It's telling you exactly what happens, get your Python installation and paths in order and it will work.
