### ISSUE TITLE
PythonEngine.Shutdown doesn't get rid of a handle

### ISSUE THREAD

**Issue by Toemsel** [pythonnet/pythonnet#2271]
### Environment

-   Pythonnet version: [latest](https://github.com/pythonnet/pythonnet/commit/8e8c3f3c921720076b6eb7ee217a14d115240d9c)
-   Python version: 311
-   Operating System: Windows 11 10.0.22621
-   .NET Runtime: .NET 6

### Details

-   Describe what you were trying to get done.

   1. Navigate into a folder
   2. Shutdown pythonnet
   3. Delete the folder pythonnet did previously navigate into

-   What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example] http://stackoverflow.com/help/mcve) this will help us understand the issue.
   
```csharp
using Python.Runtime;
using System.Reflection;

string execPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
string envPath = Path.Combine(execPath, "IwantToDeleteThis");
string pyDll = Path.Combine(execPath, "python311.dll");

ExecutePyFile(pyDll, envPath);

Directory.Delete(envPath, true);

void ExecutePyFile(string dll, string env) 
{
	Runtime.PythonDLL = Environment.ExpandEnvironmentVariables(dll);

	PythonEngine.Initialize();

	try
	{
		using Py.GILState interpretationLock = Py.GIL();
		using PyModule pyScope = Py.CreateScope();
		pyScope.Exec("import os");
		pyScope.Exec($"os.chdir(r'{env}')");
	}
	catch
	{
		throw;
	}
	finally
	{
		PythonEngine.Shutdown();
	}
}

```

![image](https://github.com/pythonnet/pythonnet/assets/6334140/1329c989-9227-4883-88a1-ff2bb2b60d81)

-   If there was a crash, please include the traceback here.

`The process cannot access the file 'C:\Dev\TestProjects\PyHandle\PyHandle\bin\Debug\net6.0\IwantToDeleteThis' because it is being used by another process.`

**Comment by filmor** [comment]
That's just how `chdir` works. It changes the current working directory for the whole process.
