### ISSUE TITLE
Installation instructions for .NET not included

### ISSUE THREAD

**Issue by Ashvio** [pythonnet/pythonnet#2274]
Hi, it took me a while to figure out how to setup the C#=>Python calling pipeline because the Installation section only includes installing it into python. I found this link which helped, perhaps we can include those instructions in the README and Wiki too?
Thanks
https://www.nuget.org/packages/pythonnet

**Comment by filmor** [comment]
The nuget package is linked in the Readme, if you want it to be more prominent, please make a concrete proposal and submit it as a pull request :)
