### ISSUE TITLE
Python 3.11 not working bu Python 3.8 works fine (using "PYTHONNET_PYDLL")

### ISSUE THREAD

**Issue by websterek** [pythonnet/pythonnet#2278]
### Environment

-   Pythonnet version: 3.03
-   Python version: 3.11
-   Operating System: Windows
-   .NET Runtime: net8.0

### Details

-   Describe what you were trying to get done.

	I'm trying to use Python.NET with Python 3.11 interpreter created using Conda.
	Everything works fine in Python 3.8 (also created by Conda) but with 3.11 dll it's not.

-   What commands did you run to trigger this issue? If you can provide a

```C#
// Working one:
System.Environment.SetEnvironmentVariable("PYTHONHOME", @"D:\Test\CondaTest8");
System.Environment.SetEnvironmentVariable("PYTHONNET_PYDLL", @"D:\Test\CondaTest8\python38.dll");
PythonEngine.Initialize();
using (Py.GIL())
{
    dynamic np = Py.Import("numpy");
    Console.WriteLine(np.cos(np.pi * 2));
}
PythonEngine.Shutdown();
```
	
```C#
// Not working:
System.Environment.SetEnvironmentVariable("PYTHONHOME", @"D:\Test\CondaTest");
System.Environment.SetEnvironmentVariable("PYTHONNET_PYDLL", @"D:\Test\CondaTest\python311.dll");
PythonEngine.Initialize();
using (Py.GIL())
{
    dynamic np = Py.Import("numpy");
    Console.WriteLine(np.cos(np.pi * 2));
}
PythonEngine.Shutdown();
```

-   If there was a crash, please include the traceback here.

```
System.TypeInitializationException: The type initializer for 'Delegates' threw an exception. ---> System.DllNotFoundException: Could not load D:\Test\CondaTest\python311.dll. ---> System.ComponentModel.Win32Exception: The specified module could not be found.
```

Greetings!

**Comment by filmor** [comment]
Well, it's telling you what's wrong, it cannot find the DLL or one of its dependencies. You can try to debug this with the Fusion Log Viewer or you can try properly activating the Python environment to get `PATH` updated with potential additional dependency paths. This is not a Python.NET issue, though.

**Comment by doobiedoo81** [comment]
i also facing this problem :(

**Comment by hongzhi2022** [comment]
string dllPath = @"C:\Program Files\Python38\python38.dll";            
            string pythonHomePath = @"C:\Program Files\Python38";
          
            // 对应python内的重要路径
            string[] py_paths = {"DLLs", "lib", "lib\\site-packages", "lib\\site-packages\\win32"
                , "lib\\site-packages\\win32/lib", "lib\\site-packages\\Pythonwin" };
            string pySearchPath = $"{pythonHomePath};";
            foreach (string p in py_paths)
            {
                pySearchPath += $"{pythonHomePath}\\{p};";
            }
 
            // 此处解决BadPythonDllException报错
            Runtime.PythonDLL = dllPath;
            Environment.SetEnvironmentVariable("PYTHONNET_PYDLL", dllPath);
            // 配置python环境搜索路径解决PythonEngine.Initialize() 崩溃
            PythonEngine.PythonHome = pythonHomePath;
            PythonEngine.PythonPath = pySearchPath;
 
            PythonEngine.Initialize();
