### ISSUE TITLE
PythonEngine does not contain a definition for ModuleFromString

### ISSUE THREAD

**Issue by PaoloG1980** [pythonnet/pythonnet#2283]
I'm trying to run a python script from a C# application with this code:

```
PythonEngine.Initialize();
dynamic multiplyNumbersModule = PythonEngine.ModuleFromString("multiply_numbers", File.ReadAllText("multiply_numbers.py"));
dynamic output = multiplyNumbersModule.multiply_numbers(1, 2, 3);
Console.WriteLine(output);
```

When I compile it gives me this error
_**PythonEngine does not contain a definition for ModuleFromString_**

Can anyone help me?
Thanks

**Comment by Yael-ST** [comment]
I have his problem too
Anyone have an idea?

**Comment by syaifulnizamyahya** [comment]
No such thing as ModuleFromString.
Use Py.Import
```
dynamic sys = Py.Import("sys");
```
