### ISSUE TITLE
Netstandard 2.0 should not be the only target option

### ISSUE THREAD

**Issue by masonwheeler** [pythonnet/pythonnet#2284]
### Environment

-   Pythonnet version: 3.0.3
-   .NET Runtime: .NET 8

### Details

-   Describe what you were trying to get done.

Installed Pythonnet from Nuget.  It dragged 11 transitive dependencies into the project, most of which are older, outdated versions of system libraries that are already available to my .NET 8 project "for free."

Would it be possible to add some more runtimes to NuGet so that this doesn't happen to developers using modern .NET Core runtimes?

**Comment by lostmsu** [comment]
I don't think any old libraries get used in this case. The dependencies you see are probably just reference assemblies.
