### ISSUE TITLE
Failed to scan Bluetooth Low Energy (BLE) devices through Python.NET package

### ISSUE THREAD

**Issue by snowuyl** [pythonnet/pythonnet#2300]
### Environment

-   Pythonnet version: v3.0.3
-   Python version: v3.11.7
-   Operating System: Windows 11
-   .NET Runtime:  .NET Core 4.6.31331.01

### Details
 I would like to call C# DLL function from Python program through Python.NET package. But it failed to scan BLE device. How to enable Bluetooth capability of Python program?

The following is source code of my Python program.
But scanner.ScanStart()
import clr

clr.AddReference("D:\workspace_Python\bletest\Ble.dll")

from Ble import Scanner

scanner = Scanner()

scan_list = scanner.ScanStart()

And the following is source code of my C# UWP DLL.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;
using Windows.Devices.Bluetooth;
using Windows.Devices.Bluetooth.GenericAttributeProfile;
using Windows.Devices.Enumeration;

namespace Ble
{
    public class Scanner
    {
        private List<DeviceInformation> deviceInfoList = new   List<DeviceInformation>();
        private DeviceWatcher deviceWatcher;
        private async void DeviceWatcherAdded(DeviceWatcher sender, DeviceInformation deviceInfo)
        {
            var device = await BluetoothLEDevice.FromIdAsync(deviceInfo.Id);
            if (device != null)
            {
                var services = await device.GetGattServicesAsync();
                foreach(var service in services.Services)
                {
                    if (service.Uuid.ToString() == Uuid.UUID_NUS_SERVICE)
                    {
                        deviceInfoList.Add(deviceInfo);
                    }
                }
            }
        }

        private void DeviceWatcherRemoved(DeviceWatcher sender, DeviceInformationUpdate infoUpdate)
        {
        }

        public List<string> ScanStart()
        {
            string aqsFilter                            = "(System.Devices.Aep.ProtocolId:=\"{bb7bb05e-5972-42b5-94fc-76eaa7084d49}\")"; // BLE
            string[] additionalProperties               = { "System.Devices.Aep.DeviceAddress", "System.Devices.Aep.IsConnected", "System.Devices.Aep.Bluetooth.Le.IsConnectable" };
            DeviceInformationKind deviceInformationKind = DeviceInformationKind.AssociationEndpoint;
            deviceWatcher = DeviceInformation.CreateWatcher(aqsFilter,
                                                            additionalProperties,
                                                            deviceInformationKind);
            deviceWatcher.Added   += DeviceWatcherAdded;
            deviceWatcher.Removed += DeviceWatcherRemoved;
            deviceWatcher.Start();
            Thread.Sleep(10000); // 10 seconds
            List<string> deviceList = new List<string>();
            Console.WriteLine(deviceInfoList.Count);
            foreach (var deviceInfo in deviceInfoList)
            {
                string macStr = Mac.GetFromId(deviceInfo.Id);
                string deviceStr = Device.Concat(deviceInfo.Name, macStr);
                deviceList.Add(deviceStr);
                Console.WriteLine(deviceStr);
            }
            Console.WriteLine(deviceList.Count);
            return deviceList;
        }
    }
}

**Comment by filmor** [comment]
This is not a support forum. Please stop opening issues like this one.
