### ISSUE TITLE
What would it take to implement built-in conversion to and from System.Decimal?

### ISSUE THREAD

**Issue by siegfriedpammer** [pythonnet/pythonnet#2319]
### Environment

-   Pythonnet version: 3.0.3
-   Python version: 3.8.1+
-   Operating System: Windows 10
-   .NET Runtime: .NET 6

### Details

-   Describe what you were trying to get done.

    I implemented a pythonnet codec for System.Decimal:

```csharp
internal class DecimalCodec : IPyObjectDecoder, IPyObjectEncoder
{
    public bool CanDecode(PyType objectType, Type targetType)
    {
        return targetType == typeof(decimal);
    }

    public bool CanEncode(Type type)
    {
        return type == typeof(decimal)
            || type == typeof(object); // this is necessary to get support for boxed decimals
    }

    public bool TryDecode<T>(PyObject pyObj, out T? value)
    {
        if (decimal.TryParse(pyObj.ToString(CultureInfo.InvariantCulture), out decimal val))
        {
            value = (T)(object)val;
            return true;
        }
        else
        {
            value = default;
            return false;
        }
    }

    public PyObject? TryEncode(object value)
    {
        if (value is not decimal d)
        {
            return null;
        }
        return new PyFloat(d.ToString(CultureInfo.InvariantCulture));
    }
}
```

Basically I am trying to do things like the following:
 
```python
num: int or float
is_equal_to_num = someObject.DecimalFieldOrProperty == num # works with my codec
s_equal_to_num = someObject.BoxedDecimalFieldOrProperty == num # works with my codec
SomeObject.SomeMethodAcceptingDecimal(num) # does not work, because Python class 'int' is not convertible to System.Decimal

>>> SomeObject.SomeMethodAcceptingDecimal(num)
Python.Runtime.PythonException: 'int' value cannot be converted to System.Decimal

The above exception was the direct cause of the following exception:

System.ArgumentException: 'int' value cannot be converted to System.Decimal in method Void SomeMethodAcceptingDecimal(System.Decimal)
 ---> Python.Runtime.PythonException: 'int' value cannot be converted to System.Decimal
   --- End of inner exception stack trace ---

The above exception was the direct cause of the following exception:

System.AggregateException: One or more errors occurred. ('int' value cannot be converted to System.Decimal in method Void SomeMethodAcceptingDecimal(System.Decimal))
 ---> System.ArgumentException: 'int' value cannot be converted to System.Decimal in method Void SomeMethodAcceptingDecimal(System.Decimal)
 ---> Python.Runtime.PythonException: 'int' value cannot be converted to System.Decimal
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: No method matches given arguments for SomeObject.SomeMethodAcceptingDecimal: (<class 'int'>)
```
 I see a few issues with this approach:

* It's not working (well) with overload resolution
* It relies on strings to do the conversion, which is expensive. There must be a way to do it faster by accessing raw bits and python internals.
* Support for boxed decimals is hacky, because the Codec gets called for every object. This could be solved by adding a `object value` parameter to `CanEncode` so it has access to the same information as `Python.Runtime.Converter.ToPython`, which uses the actual `TypeCode` of the value to handle boxed primitive types.

Note: I am willing to contribute and work with the pythonnet team to get this feature added to the pythonnet runtime.

**Comment by lostmsu** [comment]
Generally misguided idea. You should use https://docs.python.org/3/library/decimal.html

Also not a bug. For questions please use discussions.

**Comment by siegfriedpammer** [comment]
This was not a question, but rather a feature request. Also, why is the idea misguided? If the idea of automatic conversions of built-in types is so wrong, why do they exist for strings, integers, floats and all other built-in types EXCEPT decimal?

In my case I cannot even circumvent the problem by using the `Equals` method. `x.Decimal.Equals(42)` would work, because System.Decimal stays System.Decimal in Python. However, `x.Int,Equals(42)` does not work, because System.Int32 is marshalled to Python int and therefore has no Equals method. This causes interesting surprises when working with boxed primitive types. `x.Boxed.Equals` works with decimal, but fails with int.

Would be nice if guidance could be provided somehow. Thanks!

If you don't want to answer the questions here, I will be glad to open a discussion in a few days.

**Comment by lostmsu** [comment]
The particular idea is misguided because `System.Decimal` does not map neither to `int` - because it has fractions, nor to `float` - because floats can not precisely represent decimals, and precise calculations are the whole point of decimals.

You need a compelling use case. Your last example is not very compelling either because `x.Int == 42` is more idiomatic in Python, and if you want C# semantics you can use `System.Object.Equals(a, b)`.

**Comment by siegfriedpammer** [comment]
Thanks I already implemented a decoder that maps System.Decimal to decimal.Decimal,which solved most of the issues. However, I would welcome a change that adds a value parameter to the CanEncode/CanDecode methods, so the callee has all information available.

**Comment by lostmsu** [comment]
What scenario do you need this for? `CanEncode`/`CanDecode` are only there to quickly filter out types the codec does not support. Without them Python.NET would have to go through all codecs for every single attempt to convert anything, which would kill performance.

**Comment by siegfriedpammer** [comment]
Sorry for taking so long to reply. I have missed the notification.

A value parameter would enable the following:

    public bool CanEncode(Type type, object value)
    {
        return type == typeof(decimal)
            || (type == typeof(object) && Type.GetTypeCode(value?.GetType()) == TypeCode.Decimal);
    }

Then it would be possible to handle boxed decimals without calling `TryEncode` for all objects.
