### ISSUE TITLE
Update License - MIT

### ISSUE THREAD

**Issue by vmuriart** [pythonnet/pythonnet#234]
I'm not sure about the entire history of the license, but it looks to have been chosen when the project originally was hosted on the zope.org community site. 
As the project as grown, I think its time to update the license to one that provides the [same rights and protections](https://tldrlegal.com/license/zope-public-license-2.0-%28zpl-2.0%29#summary) but its more commonly known [BSD 3-clause](https://tldrlegal.com/license/bsd-3-clause-license-%28revised%29)

~~As very minimum I would like to update the license from the current [zope 2.0](https://tldrlegal.com/license/zope-public-license-2.0-%28zpl-2.0%29#fulltext) to its more friendly written revision [zope 2.1](https://tldrlegal.com/license/zope-public-license-2.1-%28zpl-2.1%29#fulltext)~~

The license proposed is MIT License. 

---

MIT license - list of contributors and status on approval:
- [ ] @tiran
- [x] @ArvidJB
- [x] @BartonCline
- [x] @bltribble
- [x] @brianlloyd
- [x] @davidanthoff
- [x] @denfromufa 
- [x] @dgsantana
- [x] @dlech
- [x] @dmitriyse
- [x] @fdanny 
- [x] @filmor
- [x] @hsoft (github) #hardcoded (sourceforge)
- [x] @jfrayne (Joe Frayne from sourceforge)
- [x] @jreback
- [x] @johnburnett 
- [x] @leith-bartrich
- [x] @lstratman
- [x] @matthid
- [x] @omnicognate
- [x] @patstew
- [x] @rico-chet 
- [x] @rmadsen-ks 
- [x] @rnestler
- [x] @sdpython
- [x] @stonebig 
- [x] @sweinst
- [x] @swinstanley
- [x] @t3476
- [x] @tonyroberts
- [x] @vmuriart
- [x] @zanedp

**Comment by filmor** [comment]
Hmm, the current copyright (attributing the library to the zope project) notice is a bit tricky then, isn't it? We should at least for new contributions have something like "the Python.NET project" instead.

**Comment by vmuriart** [comment]
it seems that back in the day (~2001) zope required any project hosted by it to have it's license. Reading through their [pages](http://old.zope.org/Resources/License.1) the intent of the zope license was for it to apply for any software extensions to the `zope` software. 
I think it's safe to say that python.net isn't particularly an extension to `zope` :smiley:

**Comment by denfromufa** [comment]
re-licensing normally requires permission from all past contributors:

https://github.com/jelmer/dulwich/issues/153

**Comment by vmuriart** [comment]
yup, sadly I'm familiar with the process. Thats why I offered updating to `zope 2.1` as an alternative since it atleast is a step in the right direction.

**Comment by vmuriart** [comment]
note that my gripe with the zope 2.0 license is this line 
> This software is Copyright (c) Zope Corporation (tm) and Contributors. All rights reserved. 

which was updated to 

> A copyright notice accompanies this license document that identifies the copyright holders. 

and doesn't require Zope to be named on it as [state by](http://old.zope.org/Resources/License.1) 

>The 2.1 version of the license is reusable. It supports having a consistent license for Zope and third-party products without requiring 3rd-party developers to assign copyright to Zope Corporation.

Zope 2.0 can give the wrong impression about the open-sourceness of the project

**Comment by filmor** [comment]
Yeah, I'm with you on all of that, but "officially" the copyright lies with the zope project currently, doesn't it? So we would need their approval for a licence change.

Since the 2.0 version doesn't specify an upgrade path, it shouldn't matter much to which new licence we switch, does it?

**Comment by denfromufa** [comment]
Note that zope corporation looks shut down since 2015. Zope foundation may
still be active. If we spend the effort to upgrade by getting permission
from past contributors and Zope, then we may just go with more adopted
licenses such as BSD simplified or MIT?! It took me about an hour to
analyze ZPL when first introduced to pythonnet for legal reasons.

**Comment by vmuriart** [comment]
> It took me about an hour to analyze ZPL when first introduced to pythonnet for legal reasons.

I had the same experience/concern when first starting to use `pythonnet`

**Comment by matthid** [comment]
I can +1 this. A switch to Apache 2 or MIT makes a lot of sense considering the latest developments in the .NET community...

**Comment by denfromufa** [comment]
I'm +1 on MIT license, it is top on github and openhub, also most permissive:

https://github.com/blog/1964-open-source-license-usage-on-github-com
https://www.blackducksoftware.com/top-open-source-licenses
http://choosealicense.com/licenses/

do @BartonCline @brianlloyd @davidanthoff @filmor @matthid @tonyroberts @vmuriart all agree before we ask permission from previous contributors?

**Comment by brianlloyd** [comment]
I'd be fine with MIT.

**Comment by davidanthoff** [comment]
Same here, not that there are many commits from my side in any case.

**Comment by tonyroberts** [comment]
Fine with me

**Comment by denfromufa** [comment]
@vmuriart @matthid @filmor I see you commented above, but can you please confirm your agreement on MIT license here? Others - sorry for the noise, but we need to get approval from everyone. Feel free to un-subscribe from this thread.

I'm updating checklist on the top of this issue:

https://github.com/pythonnet/pythonnet/issues/234#issue-162281698

**Comment by lstratman** [comment]
Sounds good to me.

**Comment by dgsantana** [comment]
I'm fine with MIT license.

**Comment by hsoft** [comment]
I agree with the licensing change

**Comment by patstew** [comment]
My contributions can be MIT licensed.

**Comment by omnicognate** [comment]
I'm happy for my minute contribution to be MIT licensed.

**Comment by leith-bartrich** [comment]
I'm fine with the proposed license change

**Comment by stonebig** [comment]
oups! I agree with the change of the licence (didn't remember I contributed)

**Comment by rnestler** [comment]
I'm fine with the proposed license change.

**Comment by vmuriart** [comment]
I'm fine with the proposed changes

**Comment by fdanny** [comment]
I'd be fine with MIT.

**Comment by jfrayne** [comment]
I'm fine with the proposed change.

**Comment by matthid** [comment]
Yeah sure, I'm fine with the switch to MIT.

**Comment by zanedp** [comment]
I'm fine with MIT.

**Comment by johnburnett** [comment]
Sounds good.

**Comment by filmor** [comment]
Fine with MIT, too.

**Comment by bltribble** [comment]
I think a few characters of code I wrote may have trickled through email/forums and made it into the codebase. Regardless, MIT license is fine.

**Comment by denfromufa** [comment]
@bltribble can you please point to this code that you contributed? i wonder
if I missed others like that?

**Comment by bltribble** [comment]
I'd be hard pressed to locate it and we're literally talking about a few characters. There were a few parallel email threads that got rolled into a single individual's patch. I can't even find the email thread anymore, but it was something to do with UCS settings and .NET versions...?

Don't worry about attribution etc. I was really just chiming in to support the move to MIT. The Zope license did cause our legal folks to say, "The what license?"

**Comment by denfromufa** [comment]
20 out of 28 responded! But we have 2 important contributors not responding. If anyone has contact with them, then please get in touch:

@BartonCline
@tiran (Christian Heimes)

**Comment by rico-chet** [comment]
I'm fine with the proposed changes

**Comment by sdpython** [comment]
I'm fine with the changes.

@sdpython

Envoyé à partir de mon Windows Phone

-----Message d'origine-----
De : "rico-chet" <notifications@github.com>
Envoyé : ‎03/‎08/‎2016 12:13
À : "pythonnet/pythonnet" <pythonnet@noreply.github.com>
Cc : "xavier dupré" <xavier.dupre@gmail.com>; "Mention" <mention@noreply.github.com>
Objet : Re: [pythonnet/pythonnet] Update License (#234)

I'm fine with the proposed changes

**Comment by dlech** [comment]
OK with me.

**Comment by denfromufa** [comment]
These 5 people out of 28 still have not responded. If anyone can contact them directly, please do this.

@BartonCline
@hardcoded (sourceforge)
@sweinst
@swinstanley
@tiran

**Comment by swinstanley** [comment]
It is absolutely fine with the license update. @samwinstanley

**Comment by BartonCline** [comment]
Yes, please. I'd prefer MIT over hope.

**Comment by denfromufa** [comment]
So we have only @tiran (Christian Heimes) and @sweinst (Serge Weinstock) left who are not responding to this request. Recently I found the history of pythonnet before hosting on sourceforge, originally in cvs zope repository. This short 2003-2004 history confirms that @brianlloyd was the only contributor and author of pythonnet:

http://old.zope.org/Members/Brian/PythonNet/
https://mail.zope.org/pipermail/zope-cvs/2004-January/004044.html

**Comment by sweinst** [comment]
It is absolutely fine with me for the license update
Serge Weinstock

**Comment by denfromufa** [comment]
Can anyone contact Christian Heimes (@tiran) in person or over phone? I sent him tweet, github mention, emails to @python.org and @redhat.com, sourceforge message over period of few weeks and no reply! He is the only contributor left, who has not replied.

**Comment by freakboy3742** [comment]
@denfromufa I've just poked him as well.

**Comment by denfromufa** [comment]
@freakboy3742 thank you for this! I guess you meant that you poked @tiran?

Let me introduce 3 more contributors since August, who also agreed to MIT license:

@ArvidJB
@t3476
@dmitriyse

To all contributors, please reply to my offer about advanced Python book for pythonnet, if you are interested:

https://mail.python.org/pipermail/pythondotnet/2016-October/001828.html

**Comment by bltribble** [comment]
Do we know what changes were added by @tiran? We could always fork from before his additions and them re-patch with everyone else's changes if his weren't significant.

It's a huge headache though...

**Comment by freakboy3742** [comment]
@denfromufa Correct - I poked @tiran. I may know some people that can perform a poke on his physical person, too... I'll see what I can arrange :-)

**Comment by filmor** [comment]
@bltribble A quick blame shows that none of his changes to the actual code are still "at the surface". The only ones left are changes to text files (`TODO.txt`, `VS_README.txt`, `changes.txt`) and entries for old python versions in the `Python.Runtime.dll.config`. The `changes.txt` (heavily outdated, should likely just be removed) contains the following with his tag:

- First work on Python 2.5 compatibility. The destination version can be
      set by defining PYTHON24 or PYTHON25. Python 2.6 compatibility is in
      work.
    
- Added VS 2005 solution and project files including a UnitTest configuration which runs the unit test suite.
      
- Enhanced unit test suite. All test cases are combined in a single test suite now.
    
- Fixed bugs in generics support for all Python versions.
    
- Fixed exception bugs for Python 2.5+. When compiled for Python 2.5+ all managed exceptions are based on Python's exceptions.Exception class.
    
- Added deprecation warnings for importing from CLR.* and the CLR module.

- Implemented support for methods with variable arguments `spam(params object[] egg)`

- Fixed Mono support by adding a custom marshaler for UCS-4 unicode, fixing a some ref counter bugs and creating a new makefile.mono.

- Added a standard python extension to load the clr environment. The src/monoclr/ directory contains additional sample code like a Python binary linked against libpython2.x.so and some example code how to embed Mono and PythonNet in a C application.

- Added yet another python prompt. This time it's a C application that embedds both Python and Mono. It may be useful as an example app for others and I need it to debug a nasty bug.

- Implemented ModuleFunctionAttribute and added ForbidPythonThreadsAttribute.
      The latter is required for module functions which invoke Python methods.

- Added clr.setPreload(), clr.getPreload(), clr.AddReference("assembly name"),
      clr.FindAssembly("name") and clr.ListAssemblies(verbose). Automatic
      preloading can be enabled with clr.setPreload/True). Preloading is
      automatically enabled for interactive Python shells and disabled in all
      other cases.
      
- New Makefile that works for Windows and Mono and autodetects the Python
      version and UCS 2/4 setting.

- Added code for Python 2.3. PythonNet can be build for Python 2.3 again
      but it is not fully supported.

- Changed the PythonException.Message value so it displays the name of 
      the exception class ("Exception") instead of its representation
      ("<type 'exceptions.Exception'>").

- Added Python.Runtime.dll.config

**Comment by denfromufa** [comment]
@freakboy3742 please don't poke him too hard :)

**Comment by swinstanley** [comment]
In the interests of a sensible rate of future development, is there some way I can transfer all rights and claims I might have to Harambe the gorilla?

**Comment by bltribble** [comment]
@filmor That seems far too deep to attempt an exorcism...

**Comment by vmuriart** [comment]
@filmor blame might be skewed and hide alot of the surviving changes he made since there's a commit in which the code was formatted to get rid of all those pesky whitespace/formatting issues we were having.

**Comment by filmor** [comment]
I'm well aware of that, just wanted to find out, whether all of this tiran-poking was even worth the effort as his last contribution is from 8 years ago or so.

Some of the features have been removed already or only relate to the build system, so we have a realistic chance of solving this ;)

**Comment by denfromufa** [comment]
if any of contributors needs a license to full JetBrains Product suite (Resharper, PyCharm, Rider, CLion, Intellij Idea), which can only be used for non-commercial development, then please let me know here or at my email address at denis(dot)akhiyarov(at)gmail(dot)com

We have total of 15 licenses on first come first serve basis until filled out.

**Comment by vmuriart** [comment]
@freakboy3742 did you have any luck daisy-chain poking @tiran ?

**Comment by freakboy3742** [comment]
@vmuriart Unfortunately not. I'll try again.

**Comment by vmuriart** [comment]
I did some research on [precedents](https://dolphin-emu.org/blog/2015/05/25/relicensing-dolphin/) and found:

> In 2003, Free Software lawyers consulted for Mozilla's relicensing project and stated that relicensing with the permission of just 95% of contributors was fine, as long as there were no objections in the remaining 5%.

We're at 31/32 approved (96.8%) and had no objections from @tiran in the time we've tried to contact him. Looks like we are good to go with the re-licensing without having to rewrite @tiran's contributions.
