### ISSUE TITLE
Is Pythonnet compatible running within a .pyz (zipapp)?

### ISSUE THREAD

**Issue by jcriddle-nci** [pythonnet/pythonnet#2342]
### Environment

-   Pythonnet version: 3.0.3
-   Python version: 3.8
-   Operating System: Windows 10
-   .NET Runtime: .NET 7

### Details

-   Hello, I have successfully gotten the pythonnet to use my dll when I run my application locally. However when zip my application up using zipapp into a .pyz file and run the pyz file, I am getting 
   clr_loader.util.clr_error.ClrError: 0x80131509: COR_E_INVALIDOPERATION => An operation is not legal in the current state.
   
  
Looking through some other issues, I was able to find [this ](https://github.com/pythonnet/pythonnet/issues/1924#issuecomment-1242107790) where someone was asking how to get this working within cx_freeze and one of the members' said they dont support cx_freeze. 

This got me thinking, is pythonnet supported to run within zipapp?

**Comment by filmor** [comment]
No. All packers that don't unpack into a temporary directory make it impossible for the runtime to find the "glue"-dll that is central to Python.NET.
