### ISSUE TITLE
nested namespaces - wrong DeprecationWarning

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#235]
when using nested namespaces:

```
clr.AddReference("namespace1.namespace2.namespace3")
```

and then

```
import namespace1.namespace2.namespace3
```

getting incorrectly this warning:

```
DeprecationWarning: 
The module was found, but not in a referenced namespace.
Implicit loading is deprecated. Please use clr.AddReference("namespace1.namespace2").
```

**Comment by filmor** [comment]
Why exactly is implicit loading deprecated anyhow? What was the rationale for this?

**Comment by denfromufa** [comment]
here is original proposal here:

https://mail.python.org/pipermail/pythondotnet/2006-April/000483.html

On Mon, Jun 27, 2016 at 9:57 AM, Benedikt Reinartz <notifications@github.com

**Comment by vmuriart** [comment]
there go my thoughts on dropping that on for pythonnet 2.3.0

**Comment by vmuriart** [comment]
@denfromufa do you have a concrete example we can use for testing?

**Comment by filmor** [comment]
I still don't understand why implicit loading is deprecated.

**Comment by lostmsu** [comment]
This seems like it was proposed to make Python.NET compatible with IronPython. Given the later is more or less dead (IP2 gets fixes, but Python 2 is deprecated now, IP3 is far from being released, and not actively worked on), I suggest we drop this for now.
