### ISSUE TITLE
clr is not being imported properly

### ISSUE THREAD

**Issue by commanderh** [pythonnet/pythonnet#2350]
### Environment

- Pythonnet version: 3.0.3
- Python version: 3.8.10
- OS version: Win 11
- .NET Runtime: 8.0.203

### Details

Describe what you were trying to get done:
1. create a hello world in c#. build it into a DLL
2. import the DLL into python script using pythonnet library. use the clr module
3. call the hello world method from the DLL file within python script

Theoretically, it should print out "hello world" when I call the method from the DLL file, but for some reason I'm getting an ImportError despite the path being correct. I also used absolute path if that makes it any better.  Afterwards, I started to wonder if the clr module was even being imported. But, it seems that it's not working either? I'm trying to print out the module, but it's showing that clr path is unknown. Another thing I've tried was adding `.dll` at the end of the path and removing it. Neither work. 

Below is a screenshot when I run it normally: 
![image](https://github.com/pythonnet/pythonnet/assets/32400396/04a94fb8-ad8d-419b-ac2f-2c9c63b2d5db)

Below is a screenshot to show that clr import is not working and using numpy as an example of a library that is working:
![image](https://github.com/pythonnet/pythonnet/assets/32400396/2faa9022-e024-4346-bd6f-5eac88e1ea72)

Screenshot of running `pip list` command:
![image](https://github.com/pythonnet/pythonnet/assets/32400396/2c542ac1-7be8-491a-8d00-51f92194826f)

Screenshot of my C# script, which I ran the command `dotnet build` which then built the DLL file.:
![image](https://github.com/pythonnet/pythonnet/assets/32400396/9cebcec7-40c4-452f-8298-473549cfd672)

If you would like to sandbox the code I have above. I'll paste it below.
hello_world.py file:
```
import clr
import numpy
print(numpy)
print(clr)
dll_full_path = r"C:\Users\YourUserName\Documents\Robotics\rf_dll_helloworld\HelloWorldLibrary\bin\Debug\net8.0\HelloWorldLibrary"
clr.AddReference(dll_full_path)

from HelloWorldLibrary import HelloWorld

def print_hello_world():
    # print("hello world")
    return "hello world"

def print_hello_world_from_csharp():
    return HelloWorld.SayHello()

# print_hello_world()
# print_hello_world_from_csharp()
```

C# file:
```
namespace HelloWorldLibrary
{
    public class HelloWorld
    {
        public static void SayHello()
        {
            Console.WriteLine("hello world");
        }
    }
}
```

Guys, please help. I've never failed a hello world tutorial in my life :(

**Comment by filmor** [comment]
1. This is not a support forum
2. As documented, if you want to run non-Framework .NET (was called .NET Core until 5.0) you have to explicitly load coreclr, ideally with a runtimeconfig that was created usinf `dotnet publish`

**Comment by commanderh** [comment]
> 1. This is not a support forum
> 2. As documented, if you want to run non-Framework .NET (was called .NET Core until 5.0) you have to explicitly load coreclr, ideally with a runtimeconfig that was created usinf `dotnet publish`

Hey there. Thanks for the response!
1. Where could I find a or the support forum? Could you point me to where I could get some support?
2.  I'm actually trying to load in a .NET Framework dll. I've gone ahead and re-created the project via Visual Studio as a Class Library in .NET Framework, set it within my project folder where the python file lives. And then within my python code, I've followed the docs and used `from pythonnet import load` , `netfx` 

The picture below shows my file tree. And my more up to date python script. 
![image](https://github.com/pythonnet/pythonnet/assets/32400396/5ce04cdd-f554-476e-b21b-45d7d3af471d)
