### ISSUE TITLE
Cannot import win32api from pywin32 when running pythonnet in a c#/.NET runtime

### ISSUE THREAD

**Issue by tebjan** [pythonnet/pythonnet#2357]
### Environment

-   Pythonnet version: pythonnet.3.1.0-preview2024-03-03 nuget
-   Python version: 3.10
-   Operating System: win11 pro
-   .NET Runtime: .NET8

### Details

Calling a simple script like:

import win32api

```python
def test():
    win32api.MessageBox(0, "TestPyWin32: test()", "TestPyWin32", 0)
    print("TestPyWin32: test()")

if __name__ == "__main__":
    test()    
```

results in "No module named 'win32api'" error. 
When running the script in a venv directly from Powershell it works fine.

Any help, workaround or hack is appreciated.

**Comment by filmor** [comment]
1. Crossposting is very bad style, please read up on general netiquette. The correct place is the Discussions section (or the chat) not three channels within 24 hours
2. You have to make sure that the PATH and PYTHONPATH settings are correct.

**Comment by tebjan** [comment]
Thanks for the hint, there was low activity in the channels and I wasn't sure which one would catch attention, if any. So sorry for the cross-posting.

> 2\. You have to make sure that the PATH and PYTHONPATH settings are correct.
Thanks for this tip, could you maybe help me find the right paths to add there? It was one of the first things I tried. I'll continue in the discussion. #2356
