### ISSUE TITLE
Possible bug in reading zero width no-break space character

### ISSUE THREAD

**Issue by AviParikh** [pythonnet/pythonnet#2369]
### Environment

-   Pythonnet version: 3.0.3
-   Python version: 3.10
-   Operating System: Windows 11
-   .NET Runtime: 8.0.4

### Details

-   Describe what you were trying to get done.

I want to read a file that may contain zero width no-break space characters anywhere in the file. If I read a file using C# into Python using Python.NET, these characters get dropped if they are at the start of a line.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
from pythonnet import load
load("coreclr")
import clr
clr.AddReference('System')
clr.AddReference('System.Runtime')
clr.AddReference('System.IO')

import System
file_path = r"path\to\zwnbsp_test_data.txt"

result = System.IO.File.ReadAllLines(file_path)
print(str(result[1][0]))
```

Native C# code does not seem to have this problem:
```
C#
String[] lines = File.ReadAllLines(@"path\to\zwnbsp_test_data.txt");

int firstChar = char.ConvertToUtf32(lines[1], 0);
int secondChar = char.ConvertToUtf32(lines[1], 1);
Console.WriteLine(firstChar);
Console.WriteLine(secondChar);
```

[zwnbsp_test_data.txt](https://github.com/pythonnet/pythonnet/files/15194162/zwnbsp_test_data.txt)

Some screenshots to help illustrate: 
![image](https://github.com/pythonnet/pythonnet/assets/31862438/c98a81eb-32cc-4e2f-84f9-737b042613bb)
![image](https://github.com/pythonnet/pythonnet/assets/31862438/ee3f73cc-3500-4d19-996a-4f3d9377d6f8)

-   If there was a crash, please include the traceback here.
No crash

**Comment by filmor** [comment]
This is indeed a bug, but an easily fixable one. The encoding we use in `UcsMarshaler` by default swallows the BOM, which is not the correct behaviour for it. I'll try to push a fix tomottow, thank you for the report! :)
