### ISSUE TITLE
docker images for mono + pythonnet on docker hub

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#240]
python images:
https://hub.docker.com/_/python/

mono images:
https://github.com/mono/docker

Run win32 Python in Docker on Linux, with .NET support using Wine:
https://github.com/benley/docker-wine-python-dotnet

.net core:
https://github.com/dotnet/dotnet-docker

**Comment by vmuriart** [comment]
Closing. Issue being worked on on #322.
