### ISSUE TITLE
why `import clr` does not work after user imports?

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#242]
`ImportError: dynamic module does not define module export function (PyInit_clr)`

**Comment by denfromufa** [comment]
https://mail.python.org/pipermail/pythondotnet/2016-July/001794.html

**Comment by denfromufa** [comment]
@fdanny reported this

**Comment by filmor** [comment]
I can't reproduce this. Either give a concrete example or close the issue.

**Comment by denfromufa** [comment]
i cannot reproduce either
