### ISSUE TITLE
Add to the docs that runtimeconfig.json from a self-contained project is not supported

### ISSUE THREAD

**Issue by mardukbp** [pythonnet/pythonnet#2427]
In the section [Constructing a Runtime instance](https://github.com/pythonnet/pythonnet/blob/master/doc/source/python.rst#constructing-a-runtime-instance) it should be noted that self-contained projects are currently not supported. I kept getting an error saying that the config file is invalid until I learned in some old issue that self-contained projects are not supported.

**Comment by filmor** [comment]
It is noted:
https://github.com/pythonnet/pythonnet/blob/master/doc/source/python.rst#loading-a-runtime
