### ISSUE TITLE
Support for .NET Core?

### ISSUE THREAD

**Issue by rogersachan** [pythonnet/pythonnet#243]

**Comment by denfromufa** [comment]
.NET Core (CoreCLR) does not provide reverse pinvoke like .NET Framework on
Windows, neither C++/CLI. Hence the only way to get this working is to
embed .NET Core using C-API, like this is done for Mono. The problem is
that C-API for CoreCLR looks quite different from Mono.

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/issues/96

**Comment by denfromufa** [comment]
@rogersachan closing this issue in favor of linked above, please see more detailed path to implementation there.
