### ISSUE TITLE
can we have a new release?

### ISSUE THREAD

**Issue by morotti** [pythonnet/pythonnet#2438]
Hello,

the last release was 10 months ago, pythonnet 3.0.3.
there have been 20 fixes in the main branch since then, including critical fixes to address crashes, but they have not been released.

would it be possible to make a new release?

Thank you.

**Comment by TheJanzap** [comment]
3.1.0 preview releases are available on [NuGet](https://www.nuget.org/packages/pythonnet/3.0.3#versions-body-tab).

**Comment by filmor** [comment]
Done.
