### ISSUE TITLE
PythonNet on .NET CORE crashes in IIS

### ISSUE THREAD

**Issue by EmanueleUniroma2** [pythonnet/pythonnet#2447]
### Environment

-   Pythonnet version: 3.0.3 (also happens with v3.1.0-preview2024-09-06)
-   Python version: 3.9.5
-   Operating System: Win 10
-   .NET Runtime: 8.0.11

### Details

-   Describe what you were trying to get done.

    I am trying to run a .NET Core project with PythonNet while in IIS.
    NOTE: the same project works fine ran from visual studio
    
    I already gave the IIS pool permissions to read/write to the Python Home folder.
    I already have verified the correct bitness of python, .net and IIS pool.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

this line crashes IIS with no error output of any kind:
PythonEngine.Initialize();

![image](https://github.com/user-attachments/assets/8b568f4f-a7b8-4900-a1a8-ec631ce22ef9)

-   If there was a crash, please include the traceback here.

No error log is produced

**Comment by filmor** [comment]
No error message => no way to do anything about this. For IIS in particular, sometimes crash logs appear in the Windows Event Log.

**Comment by EmanueleUniroma2** [comment]
> No error message => no way to do anything about this. For IIS in particular, sometimes crash logs appear in the Windows Event Log.

No error log appears in the IIS log, i already tried for days.
Also, solving this should be in the scope of the project as many enterprise .NET servers are ran on IIS?
