### ISSUE TITLE
Error with pythonnet just trying to import clr

### ISSUE THREAD

**Issue by nstarrchg** [pythonnet/pythonnet#2459]
### Environment

-   Pythonnet version: 3.0.4
-   Python version: 3.12.4
-   Operating System: Windows Server 2016 Datacenter
-   .NET Runtime: 4.5.1

### Details

I have been using pythonnet in a script to interact with an SSAS cube on a test server. Everything was working fine. Today I moved it to the prod server, and I'm getting this error:

`Traceback (most recent call last): File "c:\Python\refresh_ssas_cubes_nightly.py", line 2, in <module> load('netfx') File "C:\Program Files\Python312\Lib\site-packages\pythonnet\__init__.py", line 143, in load func = assembly.get_function("Python.Runtime.Loader.Initialize") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python312\Lib\site-packages\clr_loader\types.py", line 94, in get_function return ClrFunction(self._runtime, self._path, name, func) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python312\Lib\site-packages\clr_loader\types.py", line 58, in __init__ self._callable = runtime._get_callable(assembly, typename, func_name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\Python312\Lib\site-packages\clr_loader\netfx.py", line 47, in _get_callable raise RuntimeError( RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\Program Files\Python312\Lib\site-packages\pythonnet\runtime\Python.Runtime.dll`

Even if I have just a very basic script with only "import clr", I get this error. I've checked that Python.Runtime.dll is there in the directory.

I did a fresh install of Python 3.12.4 and pythonnet 3.0.4. This server didn't even have Python on it prior to this. I've tried other versions of python and pythonnet (2.5.2 and 3.0.3). I've tried adding path variables, etc. as suggested in other answers, but I'm still getting the error.

**Comment by filmor** [comment]
.NET 4.5 is extremely outdated. We require at least 4.7.2.

**Comment by LuisAlejandro** [comment]
I'm having this error on .NET 9.0, although mine just crashes
![image](https://github.com/user-attachments/assets/b8325559-6055-4a24-a81c-22667811925e)
