### ISSUE TITLE
Type conversion does not work if method is called with Invoke

### ISSUE THREAD

**Issue by TTSPhilipp** [pythonnet/pythonnet#2468]
### Environment

- Pythonnet version: 3.0.4
- Python version: 3.11.9
- Operating System: Windows 10 (22H2)
- .NET Runtime: 6.0.425

### Details

I am trying to call methods of a .NET class dynamically with Python. To do this, I query the method names and associated parameters from the .NET class.

The call to the method itself is then done later.

#### Example:

C#

```csharp
public class Dummy
{
    public int Echo(int i)
    {
        return i;
    }
}
```

Python

```python
# CreateDummy imports clr, loads the assembly and creates an object of the dummy class
dummy = CreateDummy()

# the normal method call works
result = dummy.Echo(1)
print(f'dummy.Echo(1) -> {result}')  # output: dummy.Echo(1) -> 1

# the dynamic call fails
echo = dummy.GetType().GetMethod('Echo')
result = echo.Invoke(dummy, [1])  # -> System.ArgumentException: Object of type 'Python.Runtime.PyInt' cannot be converted to type 'System.Int32'.
```

It would be no problem for me to convert the parameter:

```python
from System import Convert, Type

echo = dummy.GetType().GetMethod('Echo')
p1 = Convert.ChangeType(1, Type.GetType(echo.GetParameters()[0].ParameterType.AssemblyQualifiedName))
result = echo.Invoke(dummy, [p1])  # -> System.ArgumentException: Object of type 'Python.Runtime.PyInt' cannot be converted to type 'System.Int32'.
```

I would expect that `p1` is no longer a Python `int`, but a `System.Int32` object.

But the error still occurs because the result of the conversion is converted back to a Python `int`.

Can anyone help me here?

**Comment by filmor** [comment]
We special-case the constructors of the basic types, so doing `p1 = System.Int32(1)` should do the trick.

**Comment by TTSPhilipp** [comment]
Thank you very much for the quick answer. Calling the constructor directly at least ensures that it is no longer automatically converted to a Python `int`.

Is there maybe a "nicer" solution? I only have the name of the type available. The only thing I can think of at the moment is to query the class using `getattr` from `System` and then call the constructor.
That feels a bit hacky.

**Comment by filmor** [comment]
It *is* hacky, but I don't think there is another simple solution, right now.

A better overall solution might be to completely ditch automatic conversions of return values and rely on duck-typing or explicit conversions instead.

**Comment by TTSPhilipp** [comment]
All right. Thank you very much!
