### ISSUE TITLE
document C# 6.0 usage and nuget package for C# compiler on older VS

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#248]
https://github.com/pythonnet/pythonnet/issues/247#issuecomment-238975304

**Comment by electronicpatterns** [comment]
I came across this issue when trying to compile pythonnet and subsequently realized I needed to install C# 6 for my VS 2013. I don't mind contributing documentation for this issue, if you'd like to pass it off to someone else.

**Comment by denfromufa** [comment]
@electronicpatterns feel free to contribute this! the alternative would be to include this nuget dependency to the VS project file:

https://www.nuget.org/packages/Microsoft.Net.Compilers/

**Comment by denfromufa** [comment]
@electronicpatterns also please note that we are switching to MIT license

**Comment by denfromufa** [comment]
this looks obsolete now
