### ISSUE TITLE
Can i using .net runtime v2.0.50727

### ISSUE THREAD

**Issue by nminhdangit** [pythonnet/pythonnet#2482]
### Environment

-   Pythonnet version: 3.0.4
-   Python version: 3.11
-   Operating System: Windows 11 x64
-   .NET Runtime: v4.0.30319

### Details

-   Can I use the .NET runtime v2.0.50727 in Python.NET? My project runs on .NET Framework 2.0, and when I run it on the .NET runtime v4.0.30319, there are some changes that cause my project to behave incorrectly.

**Comment by filmor** [comment]
No, as stated in the documentation.
