### ISSUE TITLE
Python.net crashes with Python 3.13 and 3.14

### ISSUE THREAD

**Issue by gusmanb** [pythonnet/pythonnet#2489]
### Environment

-   Pythonnet version: 3.0.4
-   Python version: 3.13 and 3.14 alpha
-   Operating System: Windows 11 64 bits
-   .NET Runtime: .net 8.0

### Details

Trying to initialize pythonnet with Python 3.13 or higher crashes with `MissingMethodException: Failed to load symbol _PyThreadState_UncheckedGet`

```c#
void Initialize()
{
    Runtime.PythonDLL = "path_to_dll";
    PythonEngine.Initialize(); //crash
}
```

-   StackTrace:

```c#
 en Python.Runtime.Runtime.Delegates.get_Py_IsInitialized()
   en Python.Runtime.Runtime.Py_IsInitialized()
   en Python.Runtime.Runtime.<>c.<Initialize>b__32_0()
   en Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   en Python.Runtime.Runtime.Initialize(Boolean initSigs)
   en Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   en Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   en Python.Runtime.PythonEngine.Initialize()
```

**Comment by filmor** [comment]
Neither of those are supported, as documented.

**Comment by gusmanb** [comment]
> Neither of those are supported, as documented.

Sorry but, where is it documented? I can't find it in the wiki.

Also, are there any plans to support them?

**Comment by chaojian-zhang** [comment]
I found it - Per https://pythonnet.github.io/: "Python.NET is currently compatible and tested with Python releases 3.7 - 3.11"

**Comment by filmor** [comment]
Actually, 3.12 is supported, I have adjusted the homepage. The PR for 3.13 is #2454 but it's crashing on init right now.

**Comment by gusmanb** [comment]
> Actually, 3.12 is supported, I have adjusted the homepage. The PR for 3.13 is #2454 but it's crashing on init right now.

Thanks for the info.

**Comment by jpactor** [comment]
Now over one year later: is 3.14 supported yet?

**Comment by SciDaa** [comment]
> Now over one year later: is 3.14 supported yet?

Not yet. According to the meta info [https://pypi.org/project/pythonnet/](https://github.com/pythonnet/pythonnet/issues/url). Currently requires: Python <3.14, >=3.7.
I try on 3.14, it either fail at import step or addReference step in different Win11 machines.
3.13 works fine.
