### ISSUE TITLE
Follow the tutorial to directly assign the code and get an error, which is why：：：Python.Runtime.BadPythonDllException:“Runtime.PythonDLL was not set or does not p

### ISSUE THREAD

**Issue by vc815** [pythonnet/pythonnet#2508]
### Environment

win11 python3.9.20  netframwork4.8

error::
Python.Runtime.BadPythonDllException:“Runtime.PythonDLL was not set or does not point to a supported Python runtime DLL. See https://github.com/pythonnet/pythonnet#embedding-python-in-net”

var pathToVirtualEnv1 = @"D:\ProgramData\miniconda3\envs\bio";
 
var path = Environment.GetEnvironmentVariable("PATH").TrimEnd(';');
path = string.IsNullOrEmpty(path) ? pathToVirtualEnv1 : path + ";" + pathToVirtualEnv1;
Environment.SetEnvironmentVariable("PATH", path, EnvironmentVariableTarget.Process);
Environment.SetEnvironmentVariable("PATH", pathToVirtualEnv1, EnvironmentVariableTarget.Process);
Environment.SetEnvironmentVariable("PYTHONHOME", pathToVirtualEnv1, EnvironmentVariableTarget.Process);
Environment.SetEnvironmentVariable("PYTHONPATH", $"{pathToVirtualEnv1}\\Lib\\site-packages;{pathToVirtualEnv1}\\Lib", EnvironmentVariableTarget.Process);

PythonEngine.PythonHome = pathToVirtualEnv1;
PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH", EnvironmentVariableTarget.Process);
PythonEngine.Initialize();

**Comment by filmor** [comment]
The error is very explicit and this is not a support forum.
