### ISSUE TITLE
Python ABI v3.11.2 is not supported

### ISSUE THREAD

**Issue by buzz13** [pythonnet/pythonnet#2519]
### Environment

-   Pythonnet version: 3.1.0-preview(any)
-   Python version: 3.11.2
-   Operating System: Raspberry Pi OS
-   .NET Runtime: 8.0

### Details

Cannot run python script from Avalonia.
Error: Python ABI v3.11.2 is not supported: Searching for Python.Runtime.TypeOffset311, found TypeOffset.

Found same issue here but for Python 3.6 where answer was 3.6 is not supported anymore. By compatibility list 3.11 is supported. Is there anything I can do?

Thanks

**Comment by filmor** [comment]
3.11 is supported. The error message indicates that something in your build process messed up Python.NET's assembly as the list at the end (only `TypeOffset` in your case) should contain multiple individual `TypeOffset<version>` types that are statically compiled into the library. Maybe some kind of tree-shaking?
