### ISSUE TITLE
mt.exe could not be found using Visual Studio 2015

### ISSUE THREAD

**Issue by Thraka** [pythonnet/pythonnet#254]
I'm trying to use Visual Studio 2015 python support but I cannot install through pip. I get this error

>File "C:\Users\adegeo\AppData\Local\Temp\pip-build-qas0tfba\pythonnet\setup.py", line 95, in _find_msbuild_tool
>raise RuntimeError("%s could not be found" % tool)
>RuntimeError: mt.exe could not be found

How can I fix this?

**Comment by denfromufa** [comment]
can't you pip install from wheel (.whl)? mt.exe is only used when it is
compiling it locally. if you are intentionally building from source, then
do you even have mt.exe on your machine? what is the path to mt.exe? if
not, then you can get it with WinSDK or C++ build tools for VS.

if you are still getting issues, then what is your python version?

**Comment by Thraka** [comment]
So I created a new Python project in visual studio. Created a new venv for the project and then right-click > install package > pythonnet and it fails to install via pip. 

Do you mean to suggest that I should download the .whl file and install it through pip directly instead of just using `pip install pythonnet`?

**Comment by Thraka** [comment]
Interesting.. I ran upgrade pip in visual studio and it went from version 7 to 8, tried to install and it worked fine. Odd. Closing.

**Comment by AlexCatarino** [comment]
@denfromufa, mt.exe is used to create the manifest in Windows. Is it really necessary? If I want to install pythonnet locally, do I need to install "Visual C++ for Python"?
I made this change in setup.py to avoid this requirement:
https://github.com/AlexCatarino/pythonnet/commit/dbfcf73abab0c819b7651378c7896ce2c8c8657b

**Comment by denfromufa** [comment]
@AlexCatarino manifest is needed to avoid CPython runtime crash due to incompatibility in MSVC runtime version:

https://github.com/pythonnet/pythonnet/pull/45

So pythonnet will work normally but fail very badly in other cases due to subtle issues with MSVC runtime WITHOUT manifest. This is quite common with Anaconda.

**Comment by AlexCatarino** [comment]
Thank you, @denfromufa!
