### ISSUE TITLE
Cannot access indexer from .NET derived class

### ISSUE THREAD

**Issue by Thraka** [pythonnet/pythonnet#256]
If you create a .NET base class that has an indexer, and then create a .NET derived class, that derived class used in Python cannot access the indexer. You can access existing properties though just fine.

``` python
import clr

clr.AddReference("PythonTest")

import PythonTest

a = PythonTest.IndexerBase()
b = PythonTest.Indexer()

print("count of items from base class: %i" % a.Count)
print("count of items from derived class: %i" % b.Count)
print("printing base class value: %s" % a[1])
print("printing derived class value: %s" % b[1]) #ERROR HERE
```

[PythonTest Library.zip](https://github.com/pythonnet/pythonnet/files/448914/PythonTest.Library.zip)

**Comment by denfromufa** [comment]
This was brought up 2 times before but never resolved. There is mention of special syntax `.get_Item` that may be available.

https://mail.python.org/pipermail/pythondotnet/2011-September/001173.html

https://mail.python.org/pipermail/pythondotnet/2016-February/001720.html

There are some tests for indexers, not sure why your case and others above are not covered.

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/blob/master/src/tests/test_indexer.py
https://github.com/pythonnet/pythonnet/blob/master/src/testing/indexertest.cs

**Comment by denfromufa** [comment]
Oh, I just noticed the key word here - "in .NET derived class".

**Comment by Thraka** [comment]
Yes, I tried to make sure I specified where the classes come from, otherwise it would be confusing 😄. The python code I specified above is the entire test using the library in the zip file.

**Comment by abab987789** [comment]
For this bug I wonder if there is a good solution?

**Comment by denfromufa** [comment]
@abab987789 this place needs to be modified in classmanager.cs to look for parent classes:
```
private static void InitClassBase(Type type, ClassBase impl)
        {
            // First, we introspect the managed type and build some class
            // information, including generating the member descriptors
            // that we'll be putting in the Python class __dict__.

            ClassInfo info = GetClassInfo(type);

            impl.indexer = info.indexer;
```

**Comment by denfromufa** [comment]
@Thraka @abab987789 as a workaround you can cast to base class to access the indexer for now. For example:

```
PythonTest.IndexerBase(b)[1]
u'test2'
```

**Comment by abab987789** [comment]
@denfromufa Now I solved the problem in a way,Check all property indexer
`// Loop through once to find out which names are declared
            for (i = 0; i < info.Length; i++)
            {
                m = info[i];
                if (m.DeclaringType == type)
                {
                    local[m.Name] = 1;
                }
                #region Check all property indexer

                if (m.MemberType==MemberTypes.Property)
                {
                    var pi = (PropertyInfo)m;

                    MethodInfo mm = null;
                    try
                    {
                        mm = pi.GetGetMethod(true);
                        if (mm == null)
                        {
                            mm = pi.GetSetMethod(true);
                        }
                    }
                    catch (SecurityException)
                    {
                        // GetGetMethod may try to get a method protected by
                        // StrongNameIdentityPermission - effectively private.
                        continue;
                    }

                    if (mm == null)
                    {
                        continue;
                    }

                    if (!(mm.IsPublic || mm.IsFamily || mm.IsFamilyOrAssembly))
                    {
                        continue;
                    }

                    // Check for indexer
                    ParameterInfo[] args = pi.GetIndexParameters();
                    if (args.GetLength(0) > 0)
                    {
                        Indexer idx = ci.indexer;
                        if (idx == null)
                        {
                            ci.indexer = new Indexer();
                            idx = ci.indexer;
                        }
                        idx.AddProperty(pi);
                        continue;
                    }
                }
                #endregion
            }`

**Comment by denfromufa** [comment]
First part of your snippet is not formatted properly.

**Comment by abab987789** [comment]
sorry
I don't know how to use it

**Comment by denfromufa** [comment]
fixed, this document is helpful for working with markdown on github:

https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by abab987789** [comment]
Get it.Thank you
```
private static ClassInfo GetClassInfo(Type type)
        {
            var ci = new ClassInfo(type);
            var methods = new Hashtable();
            ArrayList list;
            MethodInfo meth;
            ManagedType ob;
            string name;
            object item;
            Type tp;
            int i, n;

            // This is complicated because inheritance in Python is name
            // based. We can't just find DeclaredOnly members, because we
            // could have a base class A that defines two overloads of a
            // method and a class B that defines two more. The name-based
            // descriptor Python will find needs to know about inherited
            // overloads as well as those declared on the sub class.
            BindingFlags flags = BindingFlags.Static |
                                 BindingFlags.Instance |
                                 BindingFlags.Public |
                                 BindingFlags.NonPublic;

            MemberInfo[] info = type.GetMembers(flags);
            var local = new Hashtable();
            var items = new ArrayList();
            MemberInfo m;

            // Loop through once to find out which names are declared
            for (i = 0; i < info.Length; i++)
            {
                m = info[i];
                if (m.DeclaringType == type)
                {
                    local[m.Name] = 1;
                }
                #region Check all property indexer

                if (m.MemberType==MemberTypes.Property)
                {
                    var pi = (PropertyInfo)m;

                    MethodInfo mm = null;
                    try
                    {
                        mm = pi.GetGetMethod(true);
                        if (mm == null)
                        {
                            mm = pi.GetSetMethod(true);
                        }
                    }
                    catch (SecurityException)
                    {
                        // GetGetMethod may try to get a method protected by
                        // StrongNameIdentityPermission - effectively private.
                        continue;
                    }

                    if (mm == null)
                    {
                        continue;
                    }

                    if (!(mm.IsPublic || mm.IsFamily || mm.IsFamilyOrAssembly))
                    {
                        continue;
                    }

                    // Check for indexer
                    ParameterInfo[] args = pi.GetIndexParameters();
                    if (args.GetLength(0) > 0)
                    {
                        Indexer idx = ci.indexer;
                        if (idx == null)
                        {
                            ci.indexer = new Indexer();
                            idx = ci.indexer;
                        }
                        idx.AddProperty(pi);
                        continue;
                    }
                }
                #endregion
            }

```

**Comment by denfromufa** [comment]
@abab987789 would you like to contribute this with a pull request?

**Comment by abab987789** [comment]
Yes,I'm interested

**Comment by denfromufa** [comment]
Go for it! ;)

**Comment by koliyo** [comment]
This seem to still be an issue?

**Comment by christabella** [comment]
Is this already fixed by https://github.com/pythonnet/pythonnet/pull/1248?
