### ISSUE TITLE
manylinux wheels - feasible?

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#258]
The main problem I see is the ability to support various Mono runtimes. Does Mono even have a stable ABI? Mono C-API is pretty unstable based on the number of issues that get reported.

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/issues/616

**Comment by filmor** [comment]
We are going to drop the only platform-dependent loader (Mono) for the 3.0 release.
