### ISSUE TITLE
com interop

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#260]
https://gist.github.com/denfromufa/ec559b5af41060c5ac318f7f59d8b415#file-excel_interop_vsto-ipynb

**Comment by filmor** [comment]
If we implement proper DLR support this follows automatically, doesn't it?

**Comment by denfromufa** [comment]
I agree, proper DLR support will give us com interop for free. But there
were 2 questions on SO about pythonnet that required some immediate
solution. I'm going to link these questions later. And also I was using com
objects from pythonnet at work and found it painful because almost no
reflection works on combject.

**Comment by denfromufa** [comment]
http://stackoverflow.com/questions/28050902/print-excel-files-with-microsoft-office-interop-excel-and-clr-in-python

**Comment by denfromufa** [comment]
http://stackoverflow.com/questions/38569229/cant-access-functions-in-excel-application-workbooks-from-python-2-7-3-5

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/issues/72
