### ISSUE TITLE
Give more explicit ImportErrors

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#261]
Currently, an `ImportError` raised from Python.NET does not include information on the actual dependency that failed to load.

**Comment by denfromufa** [comment]
related? https://github.com/pythonnet/pythonnet/issues/111

**Comment by filmor** [comment]
Could be. I just recognised this today as a problem, when I (again) had to do an `clr.AddReference ... .GetDependentAssemblies`-dance to find out which library could not be loaded.

**Comment by denfromufa** [comment]
@filmor the problem is that some third-party packages try to import some libraries and have backup logic if no success. So how would we distinguish between package -handled and -unhandled imports?

**Comment by filmor** [comment]
We should still raise an import error, we should just add information to the message, which assembly could not be loaded and why, basically the information that the.NET exception contains.

**Comment by denfromufa** [comment]
what I meant is actually cases like this and we would bug down the user with optional imports failing:

https://github.com/pydata/pandas/blob/master/pandas/computation/__init__.py

**Comment by filmor** [comment]
That's not what I'm saying, I'm suggesting keeping the `ImportError` and just extending the information it carries, i.e. you get `ImportError: No module named 'bla', tried to import bla.dll but failed loading the dependency blubb.dll because of reasons`.

**Comment by denfromufa** [comment]
@filmor agreed! we need to extend the passed information.

**Comment by lostmsu** [comment]
@filmor the right way to do it is to enable Fusion Log on Windows or set Mono debug environment variables for Mono.
