### ISSUE TITLE
is pythonnet working with pyrfa?

### ISSUE THREAD

**Issue by laurentbeaumer** [pythonnet/pythonnet#266]
Hi

I am using Python .NET to access pyrfa.

It returns a (not null) dynamic object (PyObject), however the methods are missing:

Message: "'Python.Runtime.PyObject' does not contain a definition for 'createConfigDb'"

Code:
            using (Py.GIL())
            {
                dynamic p = Py.Import("pyrfa");
                p.createConfigDb("./pyrfa.cfg");
            }

Alternatively, is there a way to list all the methods of the (PyObject) dynamic object? I would check if there are any method at all, or if they have different names.

Thanks

**Comment by denfromufa** [comment]
Hi, try this:

p.__dir__()

**Comment by denfromufa** [comment]
@laurentbeaumer you need to first instantiate p:
```
import pyrfa
p = pyrfa.Pyrfa()
p.createConfigDb("./pyrfa.cfg")
```

http://devcartel.com/pyrfa

**Comment by laurentbeaumer** [comment]
Thanks, I forgot to call the constructor:

            using (Py.GIL())
            {
                dynamic np = Py.Import("pyrfa");
                var p = np.Pyrfa();
                p.createConfigDb("./pyrfa.cfg");
            }

Now, I have this exception when calling _any_ method:

Exception thrown: 'System.AccessViolationException' in Python.Runtime.dll

Thanks

**Comment by denfromufa** [comment]
@laurentbeaumer can you do the same things from CPython interpreter (or IPython kernel) without errors?

**Comment by laurentbeaumer** [comment]
@denfromufa yes it works in the interpreter:

import pyrfa
p = pyrfa.Pyrfa()
p.createConfigDb("./pyrfa.cfg")
p.acquireSession("Session1")
p.createOMMConsumer()

Interestingly, the method "p.isLoggedIn();" works fine in .NET

**Comment by laurentbeaumer** [comment]
I am using:
pyrfa7.6.2.2-win32-x86-py27
python-2.7.12
Windows 7 Pro

I'll try 3.5 and PyRFA 8.

**Comment by denfromufa** [comment]
I confirmed that this is working under CPython interpreter but not in
pythonnet. It looks like the problem comes from C++ or Boost.Python code
written in Pyrfa that does implicit conversion and only accepts non-unicode
python string. But I did not find yet a reliable way to pass non-unicode
string from C# - at the interface everything is unicode.

**Comment by denfromufa** [comment]
ok, I got this to work!

1. Create python encoding converter function:

strconv.py

def strconv(struni, encoding="utf8"):
return struni.encode(encoding)

2. Import it in .NET:

dynamic strconv;  using (Py.GIL()) { strconv = Py.Import("strconv"); }


3. Now createConfigDb works!

using (Py.GIL()) {
    pp.createConfigDb(strconv.strconv(@".\pyrfa.cfg"));
}

**Comment by laurentbeaumer** [comment]
It is working. You are amazing!

**Comment by denfromufa** [comment]
BTW, setdebugmode crashes even in python interpreter. This is likely bug in
pyrfa. I had the same setup as yours.

**Comment by wiwat-tharateeraparb** [comment]
If you call `setDebugMode` before calling `createConfigDb,` PyRFA will crash. We will need to fix this.

**Comment by wiwat-tharateeraparb** [comment]
The new PyRFA 8.0.2 supports unicode strings now. As always you can download it from https://github.com/devcartel/pyrfa.
