### ISSUE TITLE
add Python 3.6

### ISSUE THREAD

**Issue by stonebig** [pythonnet/pythonnet#272]
Would it be possible to get Python 3.6 on AppVeyor ?

**Comment by denfromufa** [comment]
there is no official support for python 3.6 on appveyor yet. pandas, numpy,
matplotlib are not testing py3.6 yet.

**Comment by stonebig** [comment]
cgohlke did

**Comment by denfromufa** [comment]
that is great! But I cannot see @cgohlke build configuration in the open, since only binaries for download are available from his website.

**Comment by denfromufa** [comment]
Is there WinPython on Appveyor? E.g. they support Miniconda:

https://www.appveyor.com/docs/installed-software/#python

**Comment by stonebig** [comment]
The answer is in your link, isn't it ?

**Comment by stonebig** [comment]
but maybe you can download a WinPythonZero from github, then unzip somewhere and you're all set in AppVeyor ?

**Comment by stonebig** [comment]
winpython-2.6.0.0Preview is out, in case it can help

**Comment by stonebig** [comment]
python-3.6 final is out
