### ISSUE TITLE
Some formatters for ipython

### ISSUE THREAD

**Issue by schuster-rainer** [pythonnet/pythonnet#278]
I've seen you creating the cellmagic. I also did this 1 to 2 years ago. But I didn't use it a lot. I added extra functionality to the magic with argparse. But besides that I created some formatters.

Have a look at my gist.

https://gist.github.com/schuster-rainer/54516a463c6dfedb96c6

**Comment by denfromufa** [comment]
Can you rename your file to have the extension .ipynb? Otherwise it is not rendered on github as a jupyter notebook.

**Comment by schuster-rainer** [comment]
Done

**Comment by denfromufa** [comment]
Have you tried hooking up formatters for tables and plots?

Here is discussion we had on how this was implemented in rpy2 magic:

https://groups.google.com/forum/m/#!topic/jupyter/Wy7LnDF4O_Q

**Comment by filmor** [comment]
I would say that this is out of scope. PRs are still welcome, formatters could be added to the `pythonnet` module.
