### ISSUE TITLE
add requirements.txt and requirements-dev.txt

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#282]

**Comment by denfromufa** [comment]
here is best way to setup this:

http://stackoverflow.com/a/20720019/2230844

**Comment by filmor** [comment]
We don't have any requirements besides `setuptools`. Is it okay to close this issue until we have?

**Comment by denfromufa** [comment]
Actually we have also `six`, `wheel`.

**Comment by vmuriart** [comment]
Not six anymore 😄 but yes on `pypandoc` for releases. Though maybe wait for `pipfile` instead?

**Comment by denfromufa** [comment]
I was actually looking at bridge - bridge between doxygen and Sphinx. Does pypandoc has the same purpose?

**Comment by vmuriart** [comment]
pypandoc converts `.md` to `.rst` to upload to `pypi`. I was doing it offline on the last 2 releases so that we would have a nice page on `pypi`. It sounds you are talking about documentation which `pypandoc` doesn't do. 
We don't use much sphinx syntax other than the 1 `clr.py` module.

**Comment by denfromufa** [comment]
i was thinking that input is xml comments from c# code and docstrings from python test code, then doxygen parses this, and sphinx outputs in nice format and hosted on readthedocs:

https://breathe.readthedocs.io/en/latest/

**Comment by vmuriart** [comment]
Correct, thats what i meant, `pypandoc` has a different purpose. Its only for updating the `pypi` page.
