### ISSUE TITLE
acquire GIL by default when making PyObject calls

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#285]
Right now the GIL has to be acquired for each call to PyObject functions or methods. Maybe these should be with GIL acquired by default? We can include context manager to force releasing of GIL by explicit request.

**Comment by denfromufa** [comment]
here is how this was done by @matthid in F#:

https://yaaf.de/blog/post/2016-05-28/Having%20Fun%20with%20Computation%20Expressions

**Comment by filmor** [comment]
Can you give an example? Do you think this is actually feasible for the next release? If not, please remove the milestone.
