### ISSUE TITLE
import exceptions need to be reported when using .NET dlls from Python

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#290]
reported by @ZhukovGreen:

http://stackoverflow.com/questions/40037684/adding-reference-to-net-assembly-which-has-dots-in-name-and-namespace

**Comment by filmor** [comment]
This is a duplicate of #261.

**Comment by denfromufa** [comment]
That issue is for c# side, this issue is for Python side.

**Comment by filmor** [comment]
It isn't. I know that very well because I opened the other issue :)

**Comment by denfromufa** [comment]
closing, I agree that this is duplicate. Needs to report import errors on both sides of the interop bridge.
