### ISSUE TITLE
Adding new attributes to .Net classes is unstable

### ISSUE THREAD

**Issue by oyse** [pythonnet/pythonnet#292]
I have a problem with adding attributes to .Net classes being unstable. E.g.

```
from System import TimeSpan

TimeSpan.my_method = lambda self: self.TotalMinutes
ts = TimeSpan.FromHours(1)
ts.my_method()
```

This code will sometimes work and other times fail with the exception 'TimeSpan' object has no attribute 'my_method'.

The failure rate is variable and for some scripts/program it will work all the time while for others it will not work at all. It seems to fail a lot more often on Python 3.5 than on Python 3.4.

If I look at either `dir(ts)` or `ts.__class__.__dict__` the method is there even when the call to my_method fails.

I have tried to look into the PythonNet code for clues, but as far as I can see the new attribute is registered by MetaType. tp_setattro without error, but the method is still not found.

**Comment by filmor** [comment]
Closed by #293
