### ISSUE TITLE
Python.Runtime.Converter support for converting from/to PyObject

### ISSUE THREAD

**Issue by rmadsen-ks** [pythonnet/pythonnet#296]
I have a C# class, lets call it MyCSClass, that I intend to be inherited from a Python class and used like this:
```py
class MyPythonClass(MyCSClass):
   def __init__(self):
      self.MyAttribute = 5
      self.Callback(self)
```
When an instance of MyPythonClass gets passed to C#, it gets converted to a MyCSClass and is stripped of all the attributes. Even if the method called in CS takes it as a dynamic or PyObject. An example of this could be the __init__ method above calling into the following C# code:
```cs
public class MyCSClass {
   protected void Callback(dynamic self){
       Console.WriteLine("A dynamic attribute: {0}", self.MyAttribute);
   }
}
```

However, the instance assigned to 'self' is an MyCSClass and not a dynamic MyPythonClass. Replace ```dynamic``` with ```PyObject``` and you get an exception. If suggest the the converter should support PyObject, so that callbacks like these are made possible.

Then I would have to do this instead, which is OK for me:
```cs
public class MyCSClass {
   protected void Callback(PyObject self){
       Console.WriteLine("A dynamic attribute: {0}", ((dynamic)self).MyAttribute);
   }
}
```

Python Version: ```Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32```
OS: Windows 7 Enterprise

**Comment by denfromufa** [comment]
Did you instantiate your Python class MyPythonClass in C#, before accessing
its members?

**Comment by rmadsen-ks** [comment]
In the specific case, ```__init__``` is setting a (non-virtual) property of the base class, but I can confirm that it also happens outside of ```__init__```.

I do this:
```py
class MyPythonClass(MyCSClass):
   def __init__(self):
      self.MyAttribute = 5
   def run(self):
      self.Callback(self)
```
I get the converted MyCSClass instance inside self.Callback, if the argument is dynamic. If I instead choose PyObject as the type of the argument I just get the following error:

'TypeError : No method matches given arguments'.

**Comment by rmadsen-ks** [comment]
Note pull request #297

**Comment by denfromufa** [comment]
here is related issue with some tips from @tonyroberts:

https://github.com/pythonnet/pythonnet/issues/94

https://github.com/pythonnet/pythonnet/issues/94#issuecomment-136975931
