### ISSUE TITLE
Py.Import returns null when importing tensorflow 

### ISSUE THREAD

**Issue by snarb** [pythonnet/pythonnet#299]
Py.Import returns null when importing tensorflow at the same time python from command line or from IDE works with that import without any problems.

**Comment by denfromufa** [comment]
Can you share your environment and exact code?

**Comment by filmor** [comment]
It could help debugging to do a `throw new PythonException()` immediately after the `Py.Import`. In fact, I think this should be done in any case, instead of returning `null` here.

**Comment by pkonovalov-softheme** [comment]
That is anaconda with python 3.5 + tensorflow. I can give remote access with team viewer to that env with installed VS and pythonnet sources. I can debug and see that looks like Py.Import return some error. But it structure is very unclear for new guy in this topic, like me.

**Comment by denfromufa** [comment]
Using importlib I found the exception thrown in `tensorflow.python.platform.flags`
```

using System;
using Python.Runtime;

namespace tensorflowinclr
{
    class Program
    {
        static void Main(string[] args)
        {
            dynamic tf;
            dynamic gpb;
            dynamic np;
            using (Py.GIL()) {
                np = Py.Import("numpy");
                gpb = Py.Import("google.protobuf");
                tf = Py.Import("tensorflow");
                //tf = Py.Import("tensorflow.python.platform.flags");
                tf = Py.Import("importlib");
                tf = tf.import_module("tensorflow");
                if (tf == null) {
                    Console.WriteLine("bad import");
                }
            }
        }
    }
}
```

```
Unhandled Exception: Python.Runtime.PythonException: AttributeError : module 'sys' has no attribute 'argv'
   at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw) in C:\Users\denfromufa\Documents\pythonnet\src\runtime\pyobject.cs:line 688
   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw) in C:\Users\denfromufa\Documents\pythonnet\src\runtime\pyobject.cs:line 756
   at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result) in C:\Users\denfromufa\Documents\pythonnet\src\runtime\pyobject.cs:line 1002
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at tensorflowinclr.Program.Main(String[] args) in c:\users\denfromufa\documents\visual studio 2015\Projects\tensorflowinclr\tensorflowinclr\Program.cs:line 24
Press any key to continue . . .
```

I think the problem is that in pythonnet we are not setting `sys.argv`, like suggested in this question.

http://stackoverflow.com/questions/12230210/attributeerror-module-object-has-no-attribute-argv-when-using-python-h

@filmor what do you think?

**Comment by denfromufa** [comment]
@pkonovalov-softheme I'm able to import tensorflow in pythonnet with this temp fix.

make a file `setsysargv.py` and save it in site-packages folder:

```
import sys
setattr(sys,"argv",[""])
```
import it before tensorflow:

```
using System;
using Python.Runtime;

namespace tensorflowinclr
{
    class Program
    {
        static void Main(string[] args)
        {
            dynamic tf;
            dynamic gpb;
            dynamic np;
            dynamic sys;
            using (Py.GIL()) {
                np = Py.Import("numpy");
                gpb = Py.Import("google.protobuf");
                sys = Py.Import("setsysargv");
                tf = Py.Import("tensorflow");
                if (tf == null) {
                    Console.WriteLine("bad import");
                }
            }
        }
    }
}
```

**Comment by filmor** [comment]
Maybe we could expose a `SetArgv` function on `Py`?

**Comment by denfromufa** [comment]
@filmor it is already is, but it is not used in initialize:

https://github.com/pythonnet/pythonnet/blob/e4b91d7ea934eedf9e14b66c8e806889dc2b7728/src/runtime/runtime.cs#L2119

**Comment by denfromufa** [comment]
I put together a pull request to resolve this issue:

https://github.com/pythonnet/pythonnet/pull/301

**Comment by pkonovalov-softheme** [comment]
Can be closed. Works. Thank you!

**Comment by denfromufa** [comment]
Should we do another release with tensorflow example?

**Comment by vmuriart** [comment]
idk about another release, though I'm getting the hang of them and should be less painful now that the long description gets written from the `readme.md`.

**Comment by denfromufa** [comment]
here is example how to call into tensorflow from C# using pythonnet: github.com/pythonnet/pythonnet/issues/473
