### ISSUE TITLE
How to load different version of a loaded assembly (by AddReference)

### ISSUE THREAD

**Issue by constructor-igor** [pythonnet/pythonnet#302]
I execute tests for different versions of our SW and part of tests load version1 of 'production' assembly, other tests load version2 of the 'production' assembly.
But actually, according to ```print('net_assembly:', net_assembly)``` tests work with first loaded assembly file.

```py
net_assembly = clr.AddReference('production')
print('net_assembly:', net_assembly)
 ```

Seems, the issue related to #177.

**Comment by denfromufa** [comment]
You can try with Reflection:

http://stackoverflow.com/questions/31408391/python-for-net-using-same-net-assembly-in-multiple-versions

**Comment by denfromufa** [comment]
Just an idea, not sure if this works - you can load assembly into separate AppDomain:

https://github.com/pythonnet/pythonnet/issues/213

**Comment by filmor** [comment]
To me this doesn't seem to be in scope of the project (as it's something that you have to discuss with your .NET virtual machine directly), so I'll close this issue. If you object, please feel free to reopen :)
