### ISSUE TITLE
build python net on mac OS X el capitan

### ISSUE THREAD

**Issue by nikhil003** [pythonnet/pythonnet#305]
I am trying to build python net on mac osx el capitan, i think i have completed all the dependency, 
however i am still unable to build the library.

I am using python2.7 from miniconda, and installed mono 4.6.2
steps:

1. i cloned the master branch from python net github repo.
2. using python setup.py build_ext --inplace gives me [Error 2]

can anyone here give me idea on how to build python net on mac

**Comment by denfromufa** [comment]
Here is a patch that needs to be applied on OSX, it hasn't been integrated yet:

https://github.com/pythonnet/pythonnet/issues/120


Also I suggest to use Mono 4.2.4.4.

Your error does not include the full traceback, so it is hard to tell the exact cause.

**Comment by nikhil003** [comment]
Thanks for the tip, i tried those patches with 4.6.2 but they didn't work.

Now i removed and installed 4.2.4.4 version with xamarin studio 5.10.3.27-0 and tried to compile it, 

with just a addition of mono-2.pc to PKG_CONFIG_PATH, it started to work.
