### ISSUE TITLE
populate the __dict__ for an imported namespace - different behaviour in python / ipython

### ISSUE THREAD

**Issue by hagrid67** [pythonnet/pythonnet#308]
After an import in __ipython__, the `__dict__` for the imported namespace is automatically populated, but this does not happen in plain python.  

http://stackoverflow.com/questions/41388118/pythonnet-how-to-populate-dict-ipython-does-python-doesnt

    python -c "import clr; clr.AddReference('System.Windows.Forms'); import System.Windows.Forms; print len(System.Windows.Forms.__dict__)"
    3

    ipython -c "import clr; clr.AddReference('System.Windows.Forms'); import System.Windows.Forms; print len(System.Windows.Forms.__dict__)"
    714

It looks like a workaround for me might be to use the assembly.ExportedTypes, which does appear to be populated, but it's not clear how to invoke the cast into an interface extracted this way.  Using the `__dict__`,  the object which is the "value" in the dict, is the casting function.

I'm trying to get a list of interfaces implemented by an Interop COM object.  I got something working in ipython / jupyter notebook, but found that it didn't work in plain python.

Many thanks.

**Comment by denfromufa** [comment]
this has been answered on SO, hence closing:

http://stackoverflow.com/a/41452764/2230844
