### ISSUE TITLE
Replace CLRModule.preload code with ModulePropertyAttribute specific code.

### ISSUE THREAD

**Issue by vmuriart** [pythonnet/pythonnet#317]
Copying from [TODO](https://github.com/pythonnet/pythonnet/blob/573f90367137b30519a6b204bed7fafc7b6877ef/doc/TODO.txt#L9)

**Comment by denfromufa** [comment]
What is the benefit of this change and what problem does this solve?

**Comment by vmuriart** [comment]
@denfromufa I'm doing some cleaning on the [project](https://github.com/vmuriart/pythonnet/tree/cleanup-files) and needed somewhere to put the items from the `TODO.txt` list.
