### ISSUE TITLE
Automate version update

### ISSUE THREAD

**Issue by vmuriart** [pythonnet/pythonnet#319]
Add `bumpversion` or similar tool

**Comment by denfromufa** [comment]
so this discussion started originally here:

https://github.com/pythonnet/pythonnet/pull/312#issuecomment-271178252

I looked briefly and versioneer seems more supported:

https://github.com/warner/python-versioneer
Also versionner is supported by multibuild, which maybe required to get the OSX builds working.

Things that need to be updated automatically based on new tags added in git/github:

__version__
setup.py
conda recipe (already done)
