### ISSUE TITLE
Can't seem to compare DateTime 

### ISSUE THREAD

**Issue by Thraka** [pythonnet/pythonnet#323]
This code throws an exception:

```python
lastUpdate = DateTime.Now

if (lastUpdate < DateTime.Now):
    pass
```

The error is

>TypeError: unorderable types: DateTime() < DateTime()

**Comment by vmuriart** [comment]
Could you provide a bit more information?

Pythonnet version? 

Python version? 

os?

**Comment by Thraka** [comment]
Pythonnet 2.1.0
Python 3.5
Windows 10 x64

**Comment by vmuriart** [comment]
Possibly related to https://github.com/pythonnet/pythonnet/pull/294

If you want you could try running the latest dev from the [ci](https://ci.appveyor.com/project/vmuriart/pythonnet-olooj/build/job/26d6l1wnh6mw8s7p/artifacts)

**Comment by vmuriart** [comment]
@Thraka replicated your issue on [2.1.0](https://travis-ci.org/vmuriart/pythonnet/jobs/191201515) and tested it under [latest commit](https://travis-ci.org/vmuriart/pythonnet/jobs/191202272) and its good.

**Comment by Thraka** [comment]
Good to hear!
