### ISSUE TITLE
Best way to distribute a python app that calls out to custom DLLs?

### ISSUE THREAD

**Issue by Thraka** [pythonnet/pythonnet#325]
I finished porting a small game to Python using Python.Net and I wanted to distribute it. Can I have some guidance on how to package this up for others to use? I'm not familiar with anything around this and barely understand how python works with paths and an env. I'm not sure what I should read or where to go to know what I'm doing is correct for something with .NET.

**Comment by matthid** [comment]
I don't know if it's the best way but I came up with https://github.com/matthid/googleMusicAllAccess/blob/develop/readme.md just take a look.  Basically I'd recommend to copy a working python installation when deploying...

**Comment by denfromufa** [comment]
@Thraka you have few options:

1. Use pyinstaller (some have used cx_freeze):

https://github.com/pyinstaller/pyinstaller/issues/1801

2. Use nuitka:

http://stackoverflow.com/a/39952006/2230844

3. Build an installer using constructor from conda or pynsist:

http://pynsist.readthedocs.io/en/latest/faq.html#alternatives

**Comment by denfromufa** [comment]
@Thraka are you trying to package this?

https://www.reddit.com/r/sadconsole/comments/5nlwfn/sadconsole_running_in_python/

**Comment by Thraka** [comment]
Correct

**Comment by denfromufa** [comment]
@Thraka here is one-file version of your game packaged with pyinstaller:

[SadConsole-Python-Pyinstaller.zip](https://github.com/pythonnet/pythonnet/files/753782/SadConsole-Python-Pyinstaller.zip)

**Comment by Thraka** [comment]
Thanks a bunch!!!!

**Comment by denfromufa** [comment]
@Thraka there is also auto-update functionality for pyinstaller (like clickonce for .NET):

https://github.com/JMSwag/PyUpdater

**Comment by Thraka** [comment]
Thanks!!
