### ISSUE TITLE
Is it possible to debug imported .net module (ie from pycharm)?

### ISSUE THREAD

**Issue by tarpista** [pythonnet/pythonnet#328]
Hello Guys,

I wonder if is there any way to debug my imported .net module? Running my program in visual studio does not rise the error, only when I am trying to use it from python (in pycharm).

I already enabled JIT debugging on my computer and in my .net application. JIT debugging works fine if I run the exe file and make some error for testing.

But when I import my module in python (pycharm) and an error rises the visual studio debugger does not start - only the usual error dialog box pops up, explaining how to enable jit debugging...

**Comment by denfromufa** [comment]
What are you trying to debug: python code which is using .NET dlls or .NET code called from python? Can you provide minimal reproducible example that can be tested in Visual Studio or PyCharm?

PyCharm cannot debug .NET code.
PTVS can do mixed-mode cross-language debugging.

**Comment by tarpista** [comment]
Hello,
Thanks for the information! Is there anything I should set in Visual Studio (PTVS) to make the debugger to start upon error? Now the same thing happens in VS:  only the usual error dialog box pops up.

 I would like to debug my .net code (dll) called from python. 

Maybe I am missing something... Is it possible to use/add my C# code to python as a source instead of the compiled dll/exe  in PTVS? Now I am importing the exe file.

**Comment by denfromufa** [comment]
@tarpista can you provide your VS solution with C# and Python projects? Otherwise it is hard to see where your problem is coming from. Also report Python, .NET, Windows, VS and PTVS versions.

**Comment by tarpista** [comment]
My question was rather general then actually solving some very recent errors in my code. I was asking that is it possible in any way to debug my .NET dll which I import in python?

I think it is not possible (at this moment). The cross-language debugging you are referring is related to simultaneous debugging of native and managed code, ie. python and C. I did not find possibility for C# and python combo.

I overcame the issue by making a tiny C# console app (similar to my python code) which imports my C# gui (windows form). Running the C# console app it is possible to debug the gui as well. Though it is important to put them in one solution and make the reference to the gui project, instead of the compiled exe/dll. Once the errors are gone I could go back to python and use my gui..

**Comment by rmadsen-ks** [comment]
@denfromufa, @tarpista,

I have some similar issues. I am not using pycharm though. I am able to use the debugger in PTVS when the application starts as a python application, calls into C# code, which calls Python code, but not when the python code is embedded in a C# application. So:

- Python -> C# -> Python  : Debugging works.
- C# -> Python : Debugging does not work.

I have tried many different things, including remote debugging PTVS, PyCharm, PyDev, but all with very mixed results. What I found works best is Python -> C# -> Python with PTVS or VSCode. Other configurations than that I could not get to work.

I have made an example project that demonstrates the issues here:

https://github.com/rmadsen-ks/EmbeddedPythonDebugging

**Comment by JimSEOW** [comment]
I have similar issue with C# -> python 
I compile the above example, change the preload library path. I tested import clr with the path and it works. 

`       
public static void Main(string[] args) 
{  
    LoadLibrary(@"C:\python35\python35.dll"); // preload python35 so we are sure it is found.
    PythonEngine.Initialize();
    string modulePath = args[0];  
    using (Py.GIL())  
    {  
        PythonEngine.ImportModule(modulePath);  
    }  
} 
 `

However, I am not sure what went wrong with the error below.

`Additional information: Could not load file or assembly 'Python.Runtime, Version=4.0.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.`

**Comment by tarpista** [comment]
Thank you for the example. That sounds interesting! Though I could not realy get the point. Why do you need the C# in between if you end up with python code also? Can you put a break point in the C# code as well?

I could not set up C# -> Python direction properly (I am having some error with the Python.Runtime.dll I guess), so I ended up using Python -> C# direction instead. (In which debug does not work either)

https://github.com/pythonnet/pythonnet/issues/318

**Comment by JimSEOW** [comment]
Finally, I am able to get the example to work ONLY from python -> c# -> embeded code as discussed above. 

`
using (Py.GIL()) 
{
  dynamic np = Py.Import("numpy");
  dynamic sin = np.sin;
  Console.WriteLine(np.cos(np.pi*2));
  Console.WriteLine(sin(5));
  double c = np.cos(5) + sin(5);
  Console.WriteLine(c);
  Console.ReadKey();
}
`

Direclty running c#-> embeded code lead to 

`Additional information: Could not load file or assembly 'Python.Runtime, Version=4.0.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.`

**Comment by rmadsen-ks** [comment]
@JimSEOW, thanks for trying it out. Probably it did not find Python.Runtime either, since you are using python35.

Seems to be a problem with the hint path, I have made a modification that should fix this.

@tarpista, sorry, I might have misunderstood your issue. The system I'm working uses a plugin based architecture. Currently you can write plugins in C#, but we want to extend to make it possible to also write plugins in Python. This is why we need C# calling into Python.

You wont be able to do mixed mode debugging between Python and C#, but in visual studio you should be able to attach the debugger to the python.exe program. This was easy enough for me. I disabled anything but managed debugging and attached to python.exe. This the made it possible for me to break the execution:
![image](https://cloud.githubusercontent.com/assets/24250062/22331019/6c2a24f0-e3c9-11e6-9b35-3d2c8cd349e6.png)

You can then enable "break on exception thrown" for all .NET exceptions and make it pause when your .NET code throws a NullReferenceException.

**Comment by rmadsen-ks** [comment]
@JimSEOW, as I figured out my issue is actually different, I have started a new issue here #332

**Comment by JimSEOW** [comment]
@rmadsen-ks  

> Probably it did not find Python.Runtime

Python.Runtime.dll is in the same path as the console.exe or EmbeddedPythonDebugging.exe application.

Using the python35 environment, 
 "Python.Runtime.dll" in the [python35 directory](https://github.com/pythonnet/pythonnet/wiki/How-to-embed-python-scripts-in-your-.Net-project-use-pythonnet%3F).

I have followed everything according to this [window troubleshoot guide](https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows-and-Linux)

=> Still not sure why I have this error
`Additional information: Could not load file or assembly 'Python.Runtime, Version=4.0.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.`

Anyone has suggestion?

**Comment by tarpista** [comment]
@rmadsen-ks 

Ahha, great!! I did not know about this attaching capability of the vs debugger. It sounds nice. I try to attach as described here

https://msdn.microsoft.com/en-us/library/3s68z0b3.aspx

 but the attach button for python.exe is greyed out for for me. Am I missing something?

@JimSEOW 

Same error for me.  

```
An unhandled exception of type 'System.BadImageFormatException' occurred in Unknown Module.

Additional information: Could not load file or assembly 'Python.Runtime, Version=4.0.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```

Though I do not have more time to look for the fix, but would be also interested in the solution.

**Comment by rmadsen-ks** [comment]
@tarpista, that is probably because another debugger is already attached. Only one debugger can be attached at a time. You should run your python project without debugging and then attach from your C# project.

**Comment by tarpista** [comment]
Half way done. What do you mean by attaching "from C# project"? Regardless of what is the startup project I right click on bootstrap.py -> run without debugging. After that I go to Debug\Attach to Process... and search for python.exe and click on attach. The following error pops up:

![image](https://cloud.githubusercontent.com/assets/23481162/22336347/39633d40-e3e2-11e6-8b2a-90649cc8cf14.png)

**Comment by rmadsen-ks** [comment]
@tarpista , I am assuming you want to attach to a C# process running embedded in a python project, to catch that NullReferenceException. According to the dialog you have attached to the managed part of the process, but not the python process, so you actually succeeded, but it is still complaining that it could not attach to Python. If you just need to debug the .NET project this is not a problem.

To avoid confusion, manually select which kind of code type to debug:
![image](https://cloud.githubusercontent.com/assets/24250062/22336706/6a2eb75a-e3e3-11e6-81c6-ac99ad361a2d.png)

**Comment by tarpista** [comment]
I see. But how did you make your debugger to stop at line 18 of Program.cs as the picture shows? For me the debugger does not stop, the hello world app just keeps running and asking for input.

**Comment by tarpista** [comment]
@rmadsen-ks :100: great workaround! Finaly I understand that using the same analogy it should be possible to debug .NET projects called from python. Just simply start from C# the same way you did it from python...:
C# -> Python -> C# [module to be debugged]

**Comment by denfromufa** [comment]
here is full tutorial on how to debug pythonnet with PTVS in mixed-mode, remote (ptvsd), and attach:

https://github.com/pythonnet/pythonnet/wiki/Various-debugging-scenarios-of-embedded-CPython
