### ISSUE TITLE
Calling 'params' method with single argument fails

### ISSUE THREAD

**Issue by limdaepl** [pythonnet/pythonnet#331]
### Environment

-   Pythonnet version: 2.1.0
-   Python version: 2.7.10
-   Operating System: Microsoft Windows 7 Professional 6.1.7601 Service Pack 1 Build 7601

### Details

When calling a method with the [params](https://msdn.microsoft.com/en-us/library/w5zay9db.aspx) keyword with a single argument I get

>  TypeError: No method matches given arguments

To reproduce:

C#:
```C#
public class Foo
{
    public void Bar(params int[] values)
    {
        foreach (var value in values)
        {
            Console.WriteLine(value);
        }
    }
}
```

Python:
```python
foo = Foo()

foo.Bar([2,3,5,7]) # works
foo.Bar(2,3,5,7) # works

foo.Bar([5]) # works
foo.Bar(5) # TypeError: No method matches given arguments
```

This is probably related to the meta-issue #265.

**Comment by filmor** [comment]
This should be solved by the referenced PR.
