### ISSUE TITLE
Debugging embedded python code

### ISSUE THREAD

**Issue by rmadsen-ks** [pythonnet/pythonnet#332]
Discussion started here #328, but the issue is actually not related. Hence I have copied a bit of what I wrote there 
I have some issues debugging embedded python code. I am able to use the debugger in PTVS when the application starts as a python application (starts with python.exe), calls into C# code, which then calls Python code, but not when the python code is embedded in a C# application. To simplify:

    Python -> C# -> Python : Debugging works.
    C# -> Python : Debugging does not work.

I have tried many different things, including remote debugging PTVS, PyCharm, PyDev, but all with very mixed results. What I found works best is Python -> C# -> Python with PTVS or VSCode. Other configurations than that I could not get to work.

I have made an example project that demonstrates the issues here:

https://github.com/rmadsen-ks/EmbeddedPythonDebugging

For now my only issue is to bootstrap the application, but I have not had so much luck doing that with a full WPF application.

**Comment by JimSEOW** [comment]
@rmadsen-ks  can you get c# -> embeded python example to work?

**Comment by rmadsen-ks** [comment]
Yes, that is not a problem for me, but im running Python27. Are you using 32 bit python and debugging as a 32 bit application? Should also work with 64bit but you have to be using the same architecture for both.

**Comment by JimSEOW** [comment]
@rmadsen-ks  Finally, I checked through the compilation. Yes, Python35 64bit works.

**Comment by denfromufa** [comment]
related:

https://github.com/pythonnet/pythonnet/issues/101
https://github.com/Microsoft/PTVS/issues/552

**Comment by rmadsen-ks** [comment]
@denfromufa, do you think this is not a Python.NET problem, but a problem related to PTVS attaching to any application running embedded python code?

**Comment by denfromufa** [comment]
It is possible, I recall they had a lot of issues fixed for attaching to
embedding Python code in apps such Maya or blender.

But the difference here is that now 3 debugger engines have to cooperate
nicely - managed, native and Python.

At one point I was able to do mixed mode debugging of embedded Python code
in pythonnet. The trick is to have CPython symbols in PTVS and manually
select all 3 engines.

Remote debugging is completely different story, it is using ptvsd engine.

**Comment by rmadsen-ks** [comment]
@denfromufa, 
For my application it is OK with just python debugging working. I don't need managed, native, and python debugging at the same time, although it would be quite cool to have.

```
At one point I was able to do mixed mode debugging of embedded Python code in pythonnet. The trick is to have CPython symbols in PTVS and manually select all 3 engines.
```

Was by attaching to a running process?

Have you gotten this to work on other IDE's like PyCharm or PyDev?

**Comment by denfromufa** [comment]
Cross-language debugging in IDE is unique to VS. Yes, exactly - by attaching to a process. For me to start the debugging of the project in VS without attaching is much harder because C# code is called from another app.

If just want to debug Python code by attaching to pythonnet process without remote debugger, then try this:

https://github.com/Microsoft/PTVS/issues/1347

**Comment by tomhunter-gh** [comment]
Hi @rmadsen-ks, were you able to get anywhere with this issue?  I am trying to run a C# application which executes some Python scripts but I am not hitting any breakpoints in the Python code.  

I have tried your example project and I get the same results - no breakpoints hit in Python when I start the C# project, and no breakpoints hit in C# when I start the Python project..

Were you able to get remote Python debugging working?  If so, what were the steps?  Thanks

**Comment by denfromufa** [comment]
@tomhunter-gh I just tested and this is working without remote debugging and without mixed-mode debugging:

```python
DEBUG=True

if DEBUG:
    import sys
    import time
    while not sys.gettrace():
        time.sleep(0.1)

def pyfunc(args=None):
    if args:
        return args
    else:
        return "testing"
```

```CSHARP
using System;
using Python.Runtime;

namespace debug_embedded_python
{
    class Program
    {
        static void Main(string[] args)
        {
            dynamic res;
            using (Py.GIL()) {
                dynamic sys = Py.Import("sys");
                sys.path.append(@"path_to_pymod.py");
                dynamic pymod = Py.Import("pymod");
                res = pymod.pyfunc();
            }
            Console.WriteLine(res);
        }
    }
}
```

Note that you need to attach only Python debugging engine:

![image](https://cloud.githubusercontent.com/assets/7870949/23345950/2787e99a-fc5b-11e6-967f-1f0ad8fff15a.png)

**Comment by rmadsen-ks** [comment]
@tomhunter-gh, I think this is not as much a problem with Python.NET, but a problem with the PTVS and the debuggers out there. If you try PTVS, you might be able to do something like this. If you use PyCharm or VSCode, it might be a different story.

Last time I checked I was able to attach the debugger in some situations, for example if I call the python code and it starts with sleeping 20sec, so that I have time to attach the debugger. But, after coming back into the .NET code, it would forget the breakpoint the next time the py code was called. Maybe it is different with the way @denfromufa does it. I might have been using the ptvs.waitforattach function.

**Comment by tomhunter-gh** [comment]
Hi @denfromufa, apologies - I'm still not getting it.  I am assuming you have a C# console application and a Python application in your solution and you started debugging the C# application.  Did you then detach from this application and re-attach?  If I try that then, in the Attach to Process dialog under the Available Processes, the C# process is listed with type 'Managed (v4.6, v4.5, v4.0)' but it looks like you have it listed as 'Python'.

![image](https://cloud.githubusercontent.com/assets/1420946/23356325/50f0a06c-fcd1-11e6-9422-bc04d9074ff3.png)

I can re-attach, but I am still not hitting breakpoints in Python code.

**Comment by denfromufa** [comment]
I just start c# console app without debugging. Then attach to this process
to debug only the Python code. See the while loop which waits for debugger
to attach by checking sys.gettrace.

**Comment by tomhunter-gh** [comment]
I think I'm doing exactly the same as you, but for some reason I never hit Python breakpoints..

![image](https://cloud.githubusercontent.com/assets/1420946/23364121/9d2345a6-fcf5-11e6-897c-91d0b1786adc.png)

**Comment by tomhunter-gh** [comment]
@denfromufa, any chance you could share your test project and I'll try to see if there is some difference in project configuration or such like?

**Comment by denfromufa** [comment]
[pythonnet.zip](https://github.com/pythonnet/pythonnet/files/804356/pythonnet.zip)

**Comment by denfromufa** [comment]
![2017-02-27_10-44-11](https://cloud.githubusercontent.com/assets/7870949/23370419/3969a110-fcda-11e6-9283-ccddcd98a1ba.gif)

**Comment by tomhunter-gh** [comment]
Thanks @denfromufa.  Now I'm getting this:

![image](https://cloud.githubusercontent.com/assets/1420946/23382487/422eb6c2-fd3a-11e6-882f-f71543d8d10e.png)

I think this may be related to 64bit vs 32bit.  I have Anaconda3 64-bit installed so I changed all the project outputs to x64.

**Comment by denfromufa** [comment]
you also may need to switch from AnyCPU for x64. Also make sure that these flags are set correctly (setup.py takes care of this during installation).

PYTHON2/PYTHON3
PYTHON27/PYTHON34/PYTHON35/PYTHON36
UCS2/UCS4

**Comment by denfromufa** [comment]
Since my suggestion is working, I'm closing this issue. There are few issues open in PTVS regarding remote debugging problems with ptvsd and slowness of mixed-mode debugging.

https://github.com/Microsoft/PTVS/issues/552
https://github.com/Microsoft/PTVS/issues/578

Upvote these issues if you would like them to be resolved.

**Comment by denfromufa** [comment]
ok, all 3 major pythonnet debugging scenarios are working with Python 3.5 64-bit and VS 2017!

Here is a wiki article I'm working on:

https://github.com/pythonnet/pythonnet/wiki/Various-debugging-scenarios-of-embedded-CPython
