### ISSUE TITLE
MONO_GC_PARAMS does not appear to be respected

### ISSUE THREAD

**Issue by cowboygneox** [pythonnet/pythonnet#333]
### Environment

-   Pythonnet version: 2.1
-   Python version: 3.5
-   Operating System: Docker Linux

### Details

-   Describe what you were trying to get done.

Setting an environment variable does not seem to be curbing memory usage: `MONO_GC_PARAMS: "major=marksweep-fixed,major-heap-size=256m"`.

-   What commands did you run to trigger this issue?

Running a mono intense calculation with the env var in place shows that the env var is not respected.

**Comment by cowboygneox** [comment]
I followed the Mono docs here: http://www.mono-project.com/docs/advanced/garbage-collector/sgen/working-with-sgen/

**Comment by denfromufa** [comment]
@cowboygneox embedding Mono is different from running it as an "independent" runtime. This environment variable is set in C/C++ code, which we could also do in pythonnet:

https://github.com/mono/mono/search?utf8=%E2%9C%93&q=MONO_GC_PARAMS&type=Code 

https://github.com/pythonnet/pythonnet/blob/master/src/monoclr/pynetinit.c

**Comment by cowboygneox** [comment]
@denfromufa this came up because I was trying to see if I could get Pythonnet to run with a smaller ram footprint. Is there any advice for how to do that?

**Comment by denfromufa** [comment]
@cowboygneox as a starting point follow this suggestion without embedding mono, just invoke mono from command-line:

http://stackoverflow.com/a/19375857/2230844

Are you calling Mono from Python or vice verse?

**Comment by denfromufa** [comment]
another thing to make sure is that you are using sgen, not boehm

**Comment by cowboygneox** [comment]
I'll close this because I have a misunderstanding of how this bridge works.
