### ISSUE TITLE
pythonnet on cygwin or msys2 or bash on win10

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#340]
Should we support and test pythonnet on cygwin or msys2 and Mono?

Looks like there is some interest:

https://sourceforge.net/p/cygwin-ports/pythonnet/ci/master/tree/
https://mail.python.org/pipermail/pythondotnet/2014-December/001623.html
http://stackoverflow.com/questions/38828604/python-for-net-import-error

Appveyor supports both msys and cygwin:

https://www.appveyor.com/docs/installed-software/#mingw-msys-cygwin

**Comment by filmor** [comment]
Those are from 2010, 2014, and the last one could well be just a misconfiguration. If there is actual community interest we could go for it, but I don't have any use for this at all.

**Comment by vmuriart** [comment]
Second @filmor

**Comment by denfromufa** [comment]
https://github.com/Microsoft/BashOnWindows/issues/1212

**Comment by denfromufa** [comment]
https://github.com/Microsoft/BashOnWindows/issues/1265

**Comment by denfromufa** [comment]
@vmuriart @filmor @GERMANOCARELLA pythonnet now works on Windows Linux Subsystem:

https://github.com/Microsoft/BashOnWindows/issues/1265#issuecomment-296032849
