### ISSUE TITLE
github page status icons broken

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#344]
https://goo.gl/photos/CtLg5fhDzfJzbwQNA

**Comment by denfromufa** [comment]
@vmuriart @filmor any idea?

**Comment by filmor** [comment]
Works for me now, maybe just a fluke? Try a hard-refresh (Ctrl-F5).

**Comment by denfromufa** [comment]
Yes, a fluke indeed, which is gone. I tried on multiple devices before!

**Comment by vmuriart** [comment]
Its a fluke from `shields.io` recently i've noticed their servers gotten overloaded.
