### ISSUE TITLE
Is it possible to define and call a function equivalent to how C# DllImport works?

### ISSUE THREAD

**Issue by davidkhess** [pythonnet/pythonnet#351]
### Environment

-   Pythonnet version: 2.2.2
-   Python version: 3.4
-   Operating System: Windows 10

### Details

-   Describe what you were trying to get done.

Process a [DllImport...] statement.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

There's no documented way to accomplish this.

The problem is I have a .NET assembly that exports a function that is the official way to interact with it and it takes a .NET StringBuilder as an argument. Therefore, I cannot use cffi or ctypes - I have to use pythonnet.

However, I cannot determine how to get pythonnet to process and call a [DllImport...] defined function.

Is it possible? If not, is there a way to get a reference to an underlying .NET StringBuilder object and pass it to this function via cffi?

Thanks!

**Comment by denfromufa** [comment]
Can you provide a code sample of what you are trying to achieve?

**Comment by davidkhess** [comment]
I've been given this C# definition:

```
[DllImport(DtxAPI, CharSet = CharSet.Ansi, CallingConvention =
CallingConvention.StdCall)]
internal static extern void
DENTRIXAPI_GetConnectionString([MarshalAs(UnmanagedType.LPStr)]string szUserId,
[MarshalAs(UnmanagedType.LPStr)]string szPassword, StringBuilder szConnectionsString, int
ConnectionStringSize); 
```

Can I call it from pythonnet?

**Comment by denfromufa** [comment]
I don't see why you need pythonnet in this case? Also
it is hard to tell if possible call without minimal implementation of that
DENTRIXAPI_GetConnectionString.

**Comment by davidkhess** [comment]
Because the third argument to DENTRIXAPI_GetConnectionString requires a .NET StringBuilder.

And yes, I don't think what they did makes any sense. Exported a function from a DLL for seemingly none .NET use that requires one of the arguments to be a .NET object.

**Comment by denfromufa** [comment]
StringBuilder can be passed from Native to Managed code, you find more
about passing strings here:

https://msdn.microsoft.com/en-us/library/s9ts558h(v=vs.110).aspx

This is not pythonnet related.

If your end goal is using from Python, then you can use ctypes, cffi to
avoid .NET runtime completely. If you have already managed to wrap this DLL
successfully in C#, then you can still use pythonnet as a wrapper for this
function. But then you are dealing with 2 runtimes.

**Comment by davidkhess** [comment]
I had no idea a StingBuffer had automatic marshaling to native types.

I will definitely use cffi. Thanks!

**Comment by denfromufa** [comment]
OK, I'm closing this issue. But let us know what you find.

**Comment by davidkhess** [comment]
So yes, turns out pythonnet was not needed because it turns out that StringBuilder is automatically marshaled as a char * buffer in and out of .NET. So, this basic pattern with cffi works:

```
from cffi import FFI

ffi = FFI()
lib = ffi.dlopen(r"c:\Program Files (x86)\Dentrix\Dentrix.API.dll")
ffi.cdef("""
int DENTRIXAPI_GetConnectionString(LPSTR, LPSTR, LPSTR, int);
""") 
n = 512
result = ffi.new("char[]", n)
lib.DENTRIXAPI_GetConnectionString(b"username", b"password", result, n)
connection_string = ffi.string(result)
```

Thanks again for the help!

**Comment by rahulaasendiya** [comment]
Hello there,

I am getting the same error while getting the connection string by the DENTRIXAPI_GetConnectionString function. nothing return from the ffi.string(result)

**Comment by hansonec** [comment]
You must call DENTRIXAPI_RegisterUser() before getting the connection string, and you must code sign your executable for it to work.

Also, I achieved the same thing using ctypes instead of cffi, so I don't need to define the functions with `ffi.cdef()`.
```
import ctypes

dtxapi = ctypes.CDLL('path/to/Dentrix.API.dll')

key_file_path = 'path/to/key_file.dtxkey'
dtxapi.DENTRIXAPI_RegisterUser(key_file_path)

result_buffer = ctypes.c_buffer(512)
dtxapi.DENTRIXAPI_GetConnectionString(username, password, result_buffer, 512)
connection_string = result_buffer.value.decode('ascii')

# and if you want
dentrix_version = round(dtxapi.DENTRIXAPI_GetDentrixVersion(), 1)
```
I used winreg to get the ExePath from the registry to use for the path to Dentrix.API.dll.

Thanks for the work on pythonnet.
Thanks for the pointer to cffi and ctypes.

**Comment by denfromufa** [comment]
5 year old suggestions and still relevant 👍

cffi was mentioned because it works in pypy too.
