### ISSUE TITLE
Older pythonnet repositories found

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#354]
https://sourceforge.net/projects/peachfuzz/files/OldFiles/

http://old.zope.org/Members/Brian/PythonNet/Releases/folder_contents

https://mail.zope.org/pipermail/zope-cvs/2003-October/003761.html

**Comment by vmuriart** [comment]
What's this about?

**Comment by denfromufa** [comment]
The project started in 2003, but github history is since 2006. This may
help when finding why particular code is written.

**Comment by filmor** [comment]
I created a [Wiki page](https://github.com/pythonnet/pythonnet/wiki/Older-Project-Repositories). Not really an issue.

**Comment by denfromufa** [comment]
can we append this history to git?

**Comment by filmor** [comment]
I don't think that would be a good idea. It would invalidate all forks.

**Comment by vmuriart** [comment]
You'll end up rewriting the entire history. Best you can do is migrate them to `git` and upload them as a separate repo that ends when the history of this one starts.
