### ISSUE TITLE
How to call Python functions from C#

### ISSUE THREAD

**Issue by tarpista** [pythonnet/pythonnet#356]
There are very few examples actually showing how to call a python function from C#.

Assume I have the following file called `clsTest.py`:

```
class clsMyTest:
    """clsTest.clsMyTest class"""

    @staticmethod
    def Test03():
        return 42

    def Test04():
        return 42

def Test01():
    return 42

@staticmethod
def Test02():
    return 42
```

I try to make calls from C# as follows:
```
using (Py.GIL())
{
    dynamic test = Py.Import("clsTest");
    dynamic r1 = test.Test01(); //OK
    dynamic r2 = test.Test02(); //<--- Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in System.Core.dll
    dynamic r3 = test.clsMyTest.Test03(); //OK
    dynamic r4 = test.clsMyTest().Test04(); //<--- Exception thrown: 'Python.Runtime.PythonException' in Python.Runtime.dll
}
```

What is wrong with `Test02()` and `Test04()`?

**Comment by filmor** [comment]
### Test02:

`@staticmethod` is only sensible inside of classes

### Test04:

You are missing a `self` parameter in the signature. The `PythonException` will likely be something like `expected 0 parameters, got 1`,


Please ask stuff like this on StackOverflow. This is an issue tracker, not a support forum.

**Comment by denfromufa** [comment]
use this tag on SO http://stackoverflow.com/questions/tagged/python.net?sort=votes

or post on mailing list:

pythondotnet@python.org

**Comment by tarpista** [comment]
Ok, thanks.

**Comment by 751797916** [comment]
Hello, can you help me? I have a problem here. When I use Python.Runtime, I throw an exception.
"DLL" python2.7m "cannot be loaded: no specified module can be found. (the exception comes from HRESULT:0X8007007E). "
As a problem with a rookie. Thank you.
```
using Python.Runtime;
using System;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                dynamic sin = np.sin;
                Console.WriteLine(np.cos(np.pi * 2));
                Console.WriteLine(sin(5));
                double c = np.cos(5) + sin(5);
                Console.WriteLine(c);
                Console.ReadKey();
            }
        }
    }
}
```

**Comment by tarpista** [comment]
Just one tip, that caused me lot of head-ache until I realized. When you use pythonnet you need to be sure that all three things, the installed _python version_, _pythonnet version_ and _your program_ are the same cpu version (x64 or x86).

If you are using visual studio check the solution and projects configuration, because it is possible to mess these up. I mean you could think you are building into x64 version, though some of your projects are building into x86 or vica versa.

**Comment by tarpista** [comment]
To install the proper version of pythonnet just go into your python environment directory\Scripts and type "pip install pythonnet". That will install the correct version. There is no need to build it from the source code I think.

**Comment by denfromufa** [comment]
@tarpista both of your points are good, if you think that wiki needs to be updated, feel free to make the edits:

https://github.com/pythonnet/pythonnet/wiki

**Comment by selmeczi** [comment]
I see, thanks. One more important thing for the C# -> Python direction is that the direcory (/-ies?) of the python environment must be included in the system PATH variable. Ie I set all of these below and it worked (maybe not all of them are neccessary):

```
C:\Anaconda3;
C:\Anaconda3\Scripts;
C:\Anaconda3\Library\bin; 
```

**Comment by Backup-eric645** [comment]
`scope.Exec(code)`
