### ISSUE TITLE
Update npython.exe/Console app docs

### ISSUE THREAD

**Issue by vmuriart** [pythonnet/pythonnet#358]
Is there any purpose or use left for `npython.exe` aka Console? From @tonyroberts comment on https://github.com/pythonnet/pythonnet/commit/9b2d6f266c46e59600016509187018218f6a0aa1 it seems that it no longer serves a purpose. Personally I never used it

**Comment by denfromufa** [comment]
i guess it shows an example how to embed python in .net and I quick check for new users if this works? @cgohlke why do you still ship nPython.exe in your wheels?

http://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet

**Comment by denfromufa** [comment]
it is also mentioned in 22 issues mostly during troubleshooting:

https://github.com/pythonnet/pythonnet/search?q=npython&type=Issues&utf8=%E2%9C%93

**Comment by denfromufa** [comment]
@vmuriart which comment in https://github.com/pythonnet/pythonnet/commit/9b2d6f266c46e59600016509187018218f6a0aa1 exactly do you mean?

**Comment by vmuriart** [comment]
> The npython binary was a workaround to be able to use pythonnet on Linux. This is no longer necessary as the clr module can be imported directly from the standard Python interpreter.

Seems almost analogous to starting up python and doing `import clr`.

Though has an example its understandable. Maybe then it could be moved to `demo/samples`

**Comment by filmor** [comment]
It's almost analogous, yes. But it's not quite the same, as the `import clr` bootstraps the CLR inside of a running Python interpreter, while `npython` does it the other way round, it's a .NET program that starts up Python.

I personally use it as my debugging entrypoint for those pesky segfaults, as only that way I can convince VS to let me step into the CPython code, so I'm definitely in favour of keeping it around in some way :)

**Comment by JimSEOW** [comment]
It will be a good idea to has a **small wiki** to track this discussion. The purpose of nPython.exe  Many of us simply are not aware of the purpose and how to take advantage as some of you do.

**Comment by vmuriart** [comment]
@filmor awesome, sounds like a solid reason to keep it. @JimSEOW I'll document the class with some of the info here and reference this issue as a backup reference.

**Comment by vmuriart** [comment]
I'll close the issue once I commit the documentation.

**Comment by denfromufa** [comment]
@vmuriart @JimSEOW  we mention npython.exe briefly in docs:

http://pythonnet.github.io/readme.html

**Comment by denfromufa** [comment]
I updated the wiki:

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows-and-Linux
