### ISSUE TITLE
What is the equivalent of "copy resources" in Pythonnet?

### ISSUE THREAD

**Issue by cowboygneox** [pythonnet/pythonnet#363]
In a library I'm using, the *.dll depends on a *.xml existing in the build directory. I'm not quite sure how to instruct Pythonnet to do that. Is there a location the *.xml should live, or is there a way to tell the library to add it somehow?

**Comment by denfromufa** [comment]
This question is more suited for SO, I do not see any issue with pythonnet.
Unless you can provide any reproducible issue.

**Comment by cowboygneox** [comment]
I figured this out anyway. You just have to put them inside of a "Resources" directory next to the *.dll and it works.

**Comment by cowboygneox** [comment]
This would be nice to put into documentation.

**Comment by cowboygneox** [comment]
Feature Request.

**Comment by vmuriart** [comment]
This doesn't sound like a `pythonnet` issue.

**Comment by denfromufa** [comment]
@cowboygneox i'm glad that you found the problem. i agree with @vmuriart, so closing this one.
