### ISSUE TITLE
consider updating from unmanaged exports to dllexport friendly fork

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#366]
https://github.com/3F/DllExport

Note that this may resolve one issue for us:

https://github.com/3F/DllExport/issues/7

**Comment by vmuriart** [comment]
I tried it yesterday, albeit for all of 5 minutes, and it didn't work as plug and play. It required some configuration to setup correctly i guess (and i gave up). 

It probably needs some fiddling around to get right, but I agree, if we can move to it we should since its oss.

**Comment by filmor** [comment]
This is not relevant anymore.
