### ISSUE TITLE
xUnit test runner fails to find module dictionary

### ISSUE THREAD

**Issue by vmuriart** [pythonnet/pythonnet#372]
### Environment

-   Pythonnet version: `v2.2.2`
-   Python version: `all`
-   Operating System: `Windows`

### Details

-   Describe what you were trying to get done.

Replace `nUnit` to `xUnit` framework.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

Below is one of the tests rewritten for `xUnit`

```csharp

using System.Collections.Generic;
using Xunit;
using Python.Runtime;

namespace Python.EmbeddingTest
{
    public class PyIterTest
    {
        [Fact]
        public void TestOnPyList()
        {
            using (Py.GIL())
            {
                var list = new PyList();
                list.Append(new PyString("foo"));
                list.Append(new PyString("bar"));
                list.Append(new PyString("baz"));
                var result = new List<string>();
                foreach (PyObject item in list)
                {
                    result.Add(item.ToString());
                }
                Assert.Equal(3, result.Count);
                Assert.Equal("foo", result[0]);
                Assert.Equal("bar", result[1]);
                Assert.Equal("baz", result[2]);
            }
        }
    }
}
```

-   If there was a crash, please include the traceback here.

```
Error msg: Fatal Python error: PyImport_GetModuleDict: no module dictionary!
```

**Comment by vmuriart** [comment]
Submitting this since this is a completely different issue that the ones we saw with `nUnit` and `mstests`. I was testing it as an alternative for #371 and found a different slew of issues.

The goal of this issue is to understand why `pythonnet` is behaving this way when being run from `xUnit`.

**Comment by denfromufa** [comment]
Don't you need to shutdown the interpreter in the teardown?

**Comment by vmuriart** [comment]
failed with and without it. I converted and rewrote the entire test suite and tried it multiple ways, none of them worked. This was just one of the simplest ways to reproduce it

**Comment by denfromufa** [comment]
@vmuriart did you try xunit locally? with debugger?

**Comment by denfromufa** [comment]
According to this SO answer, it is likely that some CPython threads are killed during process exit, that's why we get these errors:

http://stackoverflow.com/questions/17679715/fatal-python-error-pyimport-getmoduledict-no-module-dictionary

**Comment by vmuriart** [comment]
Nice find! We still have pending issues w our finalizers. This & the NUnit App unloading are related to it most likely

**Comment by denfromufa** [comment]
@vmuriart yep, one of my comments in finalizer pull request was ignored (i hope it does not cause deadlocks):

https://github.com/pythonnet/pythonnet/pull/365/files/c954442c3f2ae594ca318f298ebd4607ea7fab3d#r99997577

**Comment by vmuriart** [comment]
Did you hit submit on the review? I don't see any comment, and I been having issues w the review holding them all until i submit my review

**Comment by denfromufa** [comment]
Yes, I submitted the review. But since two team members approved, I did not
complain about the pending review.

**Comment by vmuriart** [comment]
![image](https://cloud.githubusercontent.com/assets/13303020/22814880/6f4cb570-ef14-11e6-8013-bf2699ddc357.png)

It doesn't show a review or comment from you. Didn't ignore it on purpose. 
The commit actually is preventing the lockup that was causing the previous crash. But there is still more work need to properly fix the issue.

**Comment by vmuriart** [comment]
This looks to be yet another issue w `gc`. If only 1 test is run, test will run, pass but xUnit will not exit, just hang. If two tests are run, then xUnit will crash and/or hang. This can be similarly reproduced on NUnit by using `--dispose-runners` option.

**Comment by filmor** [comment]
We don't use xUnit (anymore).
