### ISSUE TITLE
Add a class to manage the context of a interaction with Python and simplify the variable exchanging

### ISSUE THREAD

**Issue by yagweb** [pythonnet/pythonnet#380]
"eval" and "exec" are the most frequently used methods when interacting with Python.  However, this two methods implemented [here](https://github.com/pythonnet/pythonnet/pull/389) are hard to use because maintain the global variable dictionary and local variable dictionary is a tedious and repeated work.

The nature of the problem lies in the variable exchanging between .NET and Python.

I think a scope class can be added to manage the context of a interaction with Python and simplify the variable exchanging.
A Scope should act like a Python Module in .NET. In the Scope class, many python functions can be wrapped to operate with the locals and globals for easy-to-use and speeding up. 

For example, the eval example provided in that PR,
```
dynamic sys = Py.Import("sys");
sys.attr1 = 100;
PyDict locals = new PyDict();
locals.SetItem("sys", sys);
locals.SetItem("a", new PyInt(10));
 
PythonEngine.Exec("c = sys.attr1 + a + 1", null, locals.Handle);
var c = locals.GetItem("c").AsManagedObject(typeof(Int32));

Console.WriteLine("c= {0}", c);
```

can be written as,

```
var ps = Py.Session('test')
sys = ps.Import("sys");
sys.attr1 = 100;
ps.SetLocal("a", 10);
ps.Exec("c = sys.attr1 + a + 1");   //pass
var c = ps.Get<System.Int32>("c");  //get the local variable and convert it to .NET type.

ps.Dispose(); 
or
ps.Suspend(); //use it later. Py.Session('test') will return it.
```

I implement a prototype of this proposal [here](https://github.com/pythonnet/pythonnet/pull/381) to help discussion.

**Comment by yagweb** [comment]
I think It's a better practice to avoid using RunString with one or two python statements in .NET code, because it is low runtime efficiency. This proposal and [the proposal](https://github.com/pythonnet/pythonnet/pull/373) can help to achieve this goal.

**Comment by vmuriart** [comment]
Do you still need to `initialize` and `finalize` the engine? From your proposal it doesn't sound like it but looking at the tests you are [initializing and finalizing it.](https://github.com/yagweb/pythonnet/blob/5634ccb8a2a40851b332fee9c60b3e241677ef6a/src/embed_tests/pyscope.cs#L12-L18)

**Comment by yagweb** [comment]
@vmuriart Thank you for your remind. I updated the unit test and removed the initialize and finalize methods.

I squashed the PyScope and PySession class. Now it can do this,
```
var ps = Py.Session();  //no need to use using statement.
ps.SetGlobal("bb", 100);
ps.SetLocal("cc", 10);
ps.Suspend(); //Suspend the Session
 //if the Py.GILState is singleton and provide the methods of PyScope.GILState. 
//ps.Suspend() can be done automatically.

using (Py.GIL())  
{
    PythonEngine.RunSimpleString("import sys;");
 }

//Continue to use the session
ps.ExecIn("aa=bb+cc+3");
int result = ps.Get<System.Int32>("aa");
Assert.AreEqual(result, 113);
```
