### ISSUE TITLE
document how to run tests locally without coverage and CI tools

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#385]
```
C:\Python\pythonnet>python src\tests\runtests.py
Traceback (most recent call last):
  File "src\tests\runtests.py", line 11, in <module>
    from ._compat import input
SystemError: Parent module '' not loaded, cannot perform relative import
```

This used to work before.

**Comment by vmuriart** [comment]
run `pytest`

**Comment by vmuriart** [comment]
or `python -m pytest`

**Comment by denfromufa** [comment]
nice format from pytest:

![image](https://cloud.githubusercontent.com/assets/7870949/23023868/2574d492-f41d-11e6-9f18-32f9c314dea0.png)

**Comment by denfromufa** [comment]
ok, I documented here:

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows-and-Linux

**Comment by vmuriart** [comment]
Strange that `run_tests` didn't work though. I thought I had updated it to run `pytest` as well. Though from the looks of the error its a PY2/PY3 compatibility issue wrt relative/absolute imports.

If you remove the `import` and the call to `input` it should work.
