### ISSUE TITLE
Add Coverity Scan

### ISSUE THREAD

**Issue by vmuriart** [pythonnet/pythonnet#390]
### Environment

-   Pythonnet version: Develop
-   Python version: All
-   Operating System: Windows (no Mono support)

### Details

-   Describe what you were trying to get done.

Add [`Coverity Scan`](https://scan.coverity.com/) to identify possible defects.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

Here's an example from my fork. https://scan.coverity.com/projects/vmuriart-pythonnet?tab=overview

Common practice is to run `Coverity Scan` as a scheduled CI run against the `master branch` in a period basis (weekly usually). The review process can take a few hours/days so it can't be part of `CI`. 

We would add it to `Appveyor` to upload on a weekly basis. 

- [x] Register Project
- [x] Submit first build
- [x] Add badge
- [x] Update `.gitignore` for build folder
- [x] Configure components
- [ ] Solve name clash due to double registering
- [ ] Integrate to AppVeyor as scheduled task

command to build `cov-build --dir cov-int python setup.py bdist_wheel`

**Comment by vmuriart** [comment]
Just submitted the registration application.

**Comment by denfromufa** [comment]
I actually registered pythonnet in coverity. Let me check!

**Comment by vmuriart** [comment]
Heres the project link i got

https://scan.coverity.com/projects/pythonnet-pythonnet?tab=project_settings

**Comment by denfromufa** [comment]
https://scan.coverity.com/projects/pythonnet

**Comment by denfromufa** [comment]
@vmuriart @tonyroberts @filmor i added you to coverity profile

**Comment by vmuriart** [comment]
Weird, your link gives me an error even though its now on my dashboard too and I got your invitation.

**Comment by denfromufa** [comment]
Can you send me your alternative email to try something else?

**Comment by denfromufa** [comment]
@vmuriart can you unregister your pythonnet integration to github, it complains now on mine:

![image](https://cloud.githubusercontent.com/assets/7870949/23071337/9d23876e-f4f3-11e6-8b2b-c99036fac39a.png)

**Comment by vmuriart** [comment]
I just deleted my project to release the link. Still getting that error. May need to email Coverity to get that resolved.

**Comment by vmuriart** [comment]
Just submitted a locally run version for analysis. @denfromufa would you be able to email `Coverity` to try solve the nameclash issue?

**Comment by vmuriart** [comment]
Cool, analysis finished. We could potentially bump it up to build nightly. For some reason I remember mine taking a few days from beginning to end.

**Comment by denfromufa** [comment]
![image](https://cloud.githubusercontent.com/assets/7870949/23073514/7866c104-f4fb-11e6-9034-e4c8ce850a98.png)

**Comment by vmuriart** [comment]
@denfromufa thats why i remembered it taking a couple days.

**Comment by vmuriart** [comment]
The review process is complete and the defects can be seen now.
![image](https://cloud.githubusercontent.com/assets/13303020/23187330/a2b5ba06-f847-11e6-82c0-dc030ab65aee.png)

**Comment by denfromufa** [comment]
@vmuriart I also checked warnings from VS 2015 code analysis and it shows over 100 issues. Some of them were from recent PRs.

**Comment by denfromufa** [comment]
[pythonnet_VS_warnings.xlsx](https://github.com/pythonnet/pythonnet/files/798435/pythonnet_VS_warnings.xlsx)

**Comment by vmuriart** [comment]
Take some of VS's warning with a grain of salt. (https://www.slideshare.net/Coverity/finding-defects-in-c-01-2014)

Looks like `CA1060` can be filtered out though. A couple other issues in that list I've commented in the code already. The list actually looks like its missing more warnings though, there should be a few about variables being declared and not used.
