### ISSUE TITLE
wiki article - remove or improve?

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#402]
https://github.com/pythonnet/pythonnet/wiki/How-to-embed-python-scripts-in-your-.Net-project-use-pythonnet%3F

**Comment by denfromufa** [comment]
@LinJianping

**Comment by denfromufa** [comment]
deleted this page, since formatting is broken

**Comment by JimSEOW** [comment]
It would help new users to locate working tutorial on how to embed by including a Wiki Page that points to example project like 
http://kozyarchuk.blogspot.com/2015/03/winforms-with-python-by-kozyarchuk.html

**Comment by denfromufa** [comment]
@JimSEOW do you mean embedding CPython in .NET or vice verse? Feel free to add wiki tutorials and I can link them properly.

Can you point out what is available in 2 blog posts from @kozyarchuk, that is not in demo applications of pythonnet? I already linked his blog post in wiki.

http://kozyarchuk.blogspot.com/2015/03/testing-winforms-with-python.html

http://kozyarchuk.blogspot.com/2015/03/winforms-with-python-by-kozyarchuk.html

He also has a video from PyGotham 2015:

http://pyvideo.org/pygotham-2015/writing-winforms-and-wpf-applications-in-python.html
