### ISSUE TITLE
in C#, PythonEngine.RunString don't work.

### ISSUE THREAD

**Issue by whaozl** [pythonnet/pythonnet#409]
http://stackoverflow.com/questions/15749028/would-you-share-your-idea-how-to-call-python-command-from-embedded-python-net

**Comment by denfromufa** [comment]
@whaozl we are thinking about deprecating RunString, see the thread here:

https://github.com/pythonnet/pythonnet/issues/401

Any reason why RunSimpleString is not fine?

**Comment by whaozl** [comment]
I want to return values for the command.

**Comment by vmuriart** [comment]
we recently added that feature thanks to @yagweb on #389. You can try those commands. The tests he added have examples on how to use them.

**Comment by whaozl** [comment]
but, in the release pythonnet 2.2.2, I don't find the  ```PythonEngine.Eval```. and, will you release a new version?

**Comment by vmuriart** [comment]
#355 is where we'll probably be discussing when the next release will be. There's still a couple open items left before we can release though.

**Comment by vmuriart** [comment]
If you just want to get a copy of the latest `whl` without having to build them, you can get them from [AppVeyor](https://ci.appveyor.com/project/pythonnet/pythonnet/branch/master)

Click on your version, then click on `artifacts` and download the wheel. 
You can then install it with `pip install --no-index --find-links=.\dist\ pythonnet`

**Comment by whaozl** [comment]
Thank you very much!
