### ISSUE TITLE
Casting a .NET object to a COM interface

### ISSUE THREAD

**Issue by r0x0r** [pythonnet/pythonnet#421]
Is it possible to cast a .NET object to a COM interface in python.net? Eg. in C# you would do ICustomDoc customDoc = (ICustomDoc)this.webBrowser.Document.
The only information I could find on the web is this post from 2007 https://mail.python.org/pipermail/pythondotnet/2007-December/000753.html, but since ICustomDoc is defined in Python ([like this](https://github.com/r0x0r/pywebview/blob/master/webview/win32_gen.py#L30)) without a constructor it does not work.
Sorry if this is a wrong place to ask, I have run out of options trying to solve this issue.

**Comment by vmuriart** [comment]
Are you trying to use both `ctypes` and `pythonnet` and cast from one to the other? Have you tried defining ICustomDoc using `pythonnet` instead?

**Comment by r0x0r** [comment]
Thanks for a quick response. I haven't tried defining ICustomDoc using pythonnet. Could you point me to documentation on how to do this?

**Comment by vmuriart** [comment]
For the c# example, looks like you have to wrap [`ICustomDoc`](http://www.pinvoke.net/default.aspx/Interfaces.ICustomDoc) there as well right?

**Comment by r0x0r** [comment]
Yes, this is correct. The pythonnet documentation mentions using tlbimp.exe
to generate wrappers for COM components. Is this the only way or could you
do without relying on external files?

**Comment by denfromufa** [comment]
Did you try this?

http://stackoverflow.com/a/3941684/2230844

**Comment by r0x0r** [comment]
Thanks for the link. It looks Marshal.GetIUnknownForObject and
Marshal.QueryInterface would do the job.
Now only to figure out how to pass the out parameter of QueryInterface in
pythonnet.

**Comment by vmuriart** [comment]
Never used the feature myself, but seems to be possible. #228's description might help.

**Comment by denfromufa** [comment]
@r0x0r you can always use reflection like this even if overloading fails:

http://stackoverflow.com/a/2304799/2230844

**Comment by denfromufa** [comment]
so the original issue is here:

https://github.com/r0x0r/pywebview/issues/87

**Comment by r0x0r** [comment]
According to this http://stackoverflow.com/questions/19600315/how-to-use-
a-net-method-which-modifies-in-place-in-python function parameters are
returned as a function return value in python.net. I have tested it and it
is indeed seems to be the case. However I have not managed to get a correct
IntPtr, zero is returned instead. Here is the code I am using
```
                p_unknown =
Marshal.GetIUnknownForObject(self.web_browser.Document)
                p_out = IntPtr.op_Explicit(Int32(32))
                _, _, p_customdoc = Marshal.QueryInterface(p_unknown,
Guid('{3050F3F0-98B5-11CF-BB82-00AA00BDCE0B}'), p_out)
                # p_customdoc is 0
```

All this investigation made me thinking how backward it is. Trying to solve
a C issue via C# in Python. Software development in its finest form.

**Comment by denfromufa** [comment]
@r0x0r can you check the result? maybe the call failed? this is a sample c# code:

```
public static T QueryInterfaceOrNull<T>(IntPtr comPointer) where T : ComObject
        {
            if (comPointer == IntPtr.Zero)
            {
                return null;
            }

            var guid = Utilities.GetGuidFromType(typeof(T));
            IntPtr pointerT;
            var result = (Result)Marshal.QueryInterface(comPointer, ref guid, out pointerT);
            return (result.Failure) ? null : FromPointerUnsafe<T>(pointerT);
        }
```

**Comment by denfromufa** [comment]
can you also provide full code sample, e.g. how `self` is instantiated?

**Comment by denfromufa** [comment]
also there are 3 options to get iunknown, not sure about differences:

https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.marshal.queryinterface(v=vs.110).aspx

**Comment by r0x0r** [comment]
Here is the code https://github.com/r0x0r/pywebview/blob/winforms-dpi-fix/webview/winforms.py#L83

**Comment by denfromufa** [comment]
@r0x0r I just debugged your code from C# side in pythonnet and everything looks ok in pythonnet handling of this method. But when I decoded the `HRESULT` from `QueryInterface`, it corresponds to "no such interface" COM error:

```
0x80004002
E_NOINTERFACE
No such interface supported.
```

https://msdn.microsoft.com/en-us/library/cc704587.aspx

http://stackoverflow.com/a/22493569/2230844

**Comment by r0x0r** [comment]
Thanks for devoting your time to the investigation of this issue. Interface casting indeed works, but the problem seems that WebBrowser.Document cannot be casted to ICustomDoc for some reason. Anyhow, this issue can be closed now here.

**Comment by r0x0r** [comment]
The original problem was to do with passing a wrong object to the GetIUnknownForObject method. Document.DomDocument is a correct object, unlike the Visual Studio docs state. Anyhow after solving this issue I realized that I was back at the square one. It works as long as I cast the obtained GetObjectForIUnknown object to ICustomDoc. Otherwise it cannot find the SetUIHandler method on the resulting object. Here is the C# code 

```
            IntPtr pointer = Marshal.GetIUnknownForObject(webBrowser1.Document.DomDocument);
            IntPtr pOut;
            Guid guid = new Guid("{3050F3F0-98B5-11CF-BB82-00AA00BDCE0B}");
            Marshal.QueryInterface(pointer, ref guid, out pOut);
            object customDoc = Marshal.GetObjectForIUnknown(pOut); //customDoc is mshtml.HTMLDocumentClass
            ICustomDoc doc = (ICustomDoc)customDoc; // doc is iCustomDoc and has SetUIHandler
```
The question is how would you do the `ICustomDoc doc = (ICustomDoc)customDoc` line in pythonnet?

**Comment by denfromufa** [comment]
@r0x0r have you tried doc = ICustomDoc(customDoc)? this should work according to tests:

https://github.com/pythonnet/pythonnet/blob/13e2a8754f0509a5f87792617fd371706a74c44b/src/tests/test_interface.py#L51

**Comment by denfromufa** [comment]
@r0x0r closing since no feedback was provided.
