### ISSUE TITLE
Fix PyAnsiString and PyString definitions

### ISSUE THREAD

**Issue by vmuriart** [pythonnet/pythonnet#423]
### Environment

-   Pythonnet version: All
-   Python version: All
-   Operating System: All

### Details

-   Describe what you were trying to get done.

Behavior between `PyAnsiString` and `PyString` partly overlap eachother. This is due to `PyString` being partially remapped to unicode objects, but still being compared to a psudo `PyString` in PY3 and actual `PyString` on PY2 yet the actual object being Unicode.

**Comment by filmor** [comment]
I don't think this is relevant anymore, especially since we are dropping Python 2 now.
