### ISSUE TITLE
Passing an Array (or it's pointer) to a .NET function

### ISSUE THREAD

**Issue by aloter** [pythonnet/pythonnet#424]
### Environment

-   Pythonnet version: 2.2.2
-   Python version: 3.5.2 |Anaconda 4.3.0 (64-bit)
-   Operating System: Windows 7 x64

### Details

I'd like to communicate with a camera (from Xenics) using their supplied C# wrapper.
From their documentation it seems I need to send the following to grab a frame:

XCamera::GetFrame (FrameType type, unsigned long ulFlags, void * buffer, unsigned int size)

In their C# example they create the buffer by:
```python
UInt32 frameSize = camera.FrameSize;  # camera is XCamera object.
frameBuffer = new ushort[frameSize / 2];

#and call the function:
GetFrame(FrameType.Native, XGetFrameFlags.Blocking, frameBuffer, frameSize);
```

I've tried to emulate it by creating the buffer in python (thanks to Brian and Denis):

```python
type(FrameType.Native) # return: int
type(XGetFrameFlags.Blocking) # return: int
# Try with numpy:
frameSize = np.uint32(camera.FrameSize)
frameBuffer = np.empty([int(frameSize/2), 1], dtype=np.ushort)

# OR using GCHandle and also explicitly casting camera.FrameSize as UInt32:

a = Array.CreateInstance(Int16, FrameSize/2)
handle = GCHandle.Alloc(a, GCHandleType.Pinned)
frameSize = UInt32(camera.FrameSize)
camera.GetFrame(FrameType.Native, XGetFrameFlags.Blocking, handle.AddrOfPinnedObject(), frameSize)
# Tried also sending just the array a with no luck
```
I get an error for not sending the right inputs
```python
TypeError: No method matches given arguments
```

Any leads will be appreciated. Thank you!

**Comment by filmor** [comment]
This is not a general support forum, please ask this question on StackOverflow.

**Comment by denfromufa** [comment]
@filmor I suggested to ask the question here, it was originally posted in
the mailing list.

@aloter sorry about confusion!

Did you try an array with type of UInt16?
`a = Array.CreateInstance(UInt16, FrameSize/2)`

Also can you show the output of `GetFrame.__overloads__` or
`GetFrame.Overloads`?

**Comment by aloter** [comment]
@filmor Apologies, didn't know what I'm doing.

@denfromufa thank you for following up.
frameSize is UInt32 (at least in the example: UInt32 frameSize = camera.FrameSize;) and CreateInstance doesn't support it (length is frameSize/2 so buffer should be UInt16, from what I could understand):
```
a = Array.CreateInstance(Int16, frameSize/2)
TypeError: unsupported operand type(s) for /: 'UInt32' and 'int'
```

The overloads:

```
camera.GetFrame.Overloads
# returns:

Void GetFrame(Xenics.Xeneth.FrameType, Xenics.Xeneth.XGetFrameFlags, UInt32[], UInt32)
Void GetFrame(Xenics.Xeneth.FrameType, Xenics.Xeneth.XGetFrameFlags, Int32[], UInt32)
Void GetFrame(Xenics.Xeneth.FrameType, Xenics.Xeneth.XGetFrameFlags, IntPtr, UInt32)
Void GetFrame(Xenics.Xeneth.FrameType, Xenics.Xeneth.XGetFrameFlags, UInt16[], UInt32)
```

Last line means it can get the UInt16 array, maybe it's the FrameType and XGetFrameFlags?
```
type(FrameType.Native) # returns int
type(XGetFrameFlags.Blocking) # returns int
```

**Comment by filmor** [comment]
@aloter No worries, I didn't know that you were directed here.

Regarding your problem: The problem you are being reported is because of the `frameSize / 2` part. Try `frameSize / UInt32(2)`, but still, for the future, direct questions like this to StackOverflow if you don't suspect a bug.

**Comment by aloter** [comment]
Understood, will do next time.
FrameSize / UInt32(2) doesn't accept UInt32.
Going back to @denfromufa, UInt16 didn't work either:

```
a = Array.CreateInstance(UInt16, Int32(camera.FrameSize/2))
print(a.Length)
# returns: 327680
handle = GCHandle.Alloc(a, GCHandleType.Pinned)
frameSize = UInt32(camera.FrameSize)
camera.GetFrame(FrameType.Native, XGetFrameFlags.Blocking, handle.AddrOfPinnedObject(), frameSize)
Traceback (most recent call last):
    camera.GetFrame(FrameType.Native, XGetFrameFlags.Blocking, handle.AddrOfPinnedObject(), frameSize)
TypeError: No method matches given arguments
```

Sending the array itself didn't work also.
```
camera.GetFrame(FrameType.Native, XGetFrameFlags.Blocking, a, frameSize)
Traceback (most recent call last):
    camera.GetFrame(FrameType.Native, XGetFrameFlags.Blocking, a, frameSize)
TypeError: No method matches given arguments
```

Thank you again.

**Comment by denfromufa** [comment]
@aloter try forcing the specific overloaded method by passing arguments to Overloads, more details here:

documentation:
http://pythonnet.github.io/

examples in tests:
https://github.com/pythonnet/pythonnet/search?utf8=%E2%9C%93&q=overloads

What are the types of these first 2 arguments - `Xenics.Xeneth.FrameType, Xenics.Xeneth.XGetFrameFlags`?

You are trying to pass `int`, but at least the second argument is `unsigned long` in C++ signature.
