### ISSUE TITLE
Cleanup typecode switch - IEnumerable and object cases

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#428]
https://github.com/pythonnet/pythonnet/pull/427#discussion_r105551178

**Comment by filmor** [comment]
Reopen with description, please.

**Comment by denfromufa** [comment]
2 options suggested by @vmuriart:

1. Delete that section of code `IEnumerable` altogether  or 
2. Delete typecode.Object. 

The remaining typecodes are Empty, DBNull, Decimal and DateTime and i don't think any of those should be converted to PyList.
Also, I can't think of a situation in which the default branch of the switch would be hit because we have Typecode.Object defined; It would always be called instead of the default. This example is probably closer to how it should be written.
