### ISSUE TITLE
Building C# cpython extension modules.

### ISSUE THREAD

**Issue by AraHaan** [pythonnet/pythonnet#429]
### Environment

-   Pythonnet version: None yet installed (Unsure if it would allow me to build .net code as an pyd file on windows similar to how the rust cpython bindings let me to be able to).
-   Python version: 3.5.2 & 3.6.1
-   Operating System: Windows 7 SP1 Ultimate x64 Build 7601

### Details

-   Describe what you were trying to get done.

    Build an cpython extension module using C# using this library. This is so I can use the extension module with perferable the official implementation of python (python.exe) just like how the rust cpython bindings are.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

None

-   If there was a crash, please include the traceback here.

No crash. I do not want to embed python in .Net yet. Instead I want to use .Net in an cpython extension module that I can import just like C/C++ compiled python extension modules that uses the C Python API.

If this part is not supported yet to make an extension module that wraps actual C# code to be used in the official cpython builds I would love that to be added so that way I do not have to embed it.
Also if possible I would like an example module that wraps actual C# code that could then be used in the official build of python without embedding python code itself.

Note: After python v3.4 all pyd files must have before the pyd extension this:

32 bit pyd:
```
[module name].cp3[version minor]-win32.pyd
```

64 bit pyd:

```
[module name].cp3[version minor]-win_amd64.pyd
```

the same ``.cp3[version minor]-`` tag also applies on linux ``.so`` files on python extension modules. Just so you know so you can separate python 3.5 from 3.6 correctly on the solution and project files.

**Comment by denfromufa** [comment]
pythonnet allows to import any .NET DLL after `import clr` statement without a need to write a custom `.pyd` extensions. This is because `clr.pyd` embeds .NET or Mono runtimes in CPython.

I have not seen examples of pythonnet used for writing CPython C-API extensions in C#, because pythonnet is itself a C-API extension.

Perhaps if you can suggest what are the current limitations, then it would make sense to continue this discussion. Otherwise all support is already there:

http://pythonnet.github.io/

**Comment by AraHaan** [comment]
ah I see. So I can make an normal .NET dll or .NET so file on linux and import them.

**Comment by denfromufa** [comment]
Yes, that is correct. Feel free to report any other issues, but this one looks resolved.
