### ISSUE TITLE
space in clrmetatype or digits in namespace

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#436]
Why does pythonnet have a space in clrmetatype? Looks very confusing:

```
In [1]: import clr
In [2]: from System import IComparable
In [3]: type(IComparable)
Out[3]: CLR.CLR Metatype
In [4]: str(type(IComparable))
Out[4]: "<class 'CLR.CLR Metatype'>"
```

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/blob/423407a4e7ff783d8f4d9498eaa51bf8a12382ce/src/runtime/typemanager.cs#L298

**Comment by filmor** [comment]
The class is private to pythonnet and can not be sensibly used by other libraries, so a name that indicates non-importability is fine by me. The `CLR.` prefix is a bit weird, though :)

**Comment by denfromufa** [comment]
apparently pythonnet also fails to import members from .NET namespaces that contain digits.

**Comment by Cronan** [comment]
Is it OK to break the digit problem out into another issue?

**Comment by denfromufa** [comment]
Yes, the digits can be a separate issue.
We should start with a reproducible example or better with a failing test.

**Comment by filmor** [comment]
The meta type does not have a space anymore.
