### ISSUE TITLE
why msbuild added to %path% in bld.bat for conda build?

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#438]
https://github.com/pythonnet/pythonnet/pull/435#issuecomment-288606262

**Comment by filmor** [comment]
Nice description :stuck_out_tongue_winking_eye: 

I had problems in the past with using the `script` element in the conda recipe, which can in theory look like
    
    script: "python setup.py install",

So: "yes".

I'm not sure, why `$PATH` is overridden in there, though.

**Comment by denfromufa** [comment]
@filmor I update the title: why msbuild added to %path% in bld.bat for conda build?

**Comment by vmuriart** [comment]
I think `msbuild` was added there since alot of packages have issues detecting the presence of msbuild. The recipe was copied from another example probably that used it. In our case its most likely not needed, though I havent tested it yet.

**Comment by vmuriart** [comment]
bah. build [fails](https://ci.appveyor.com/project/vmuriart/pythonnet/build/dev-2142/job/ilykywtvctxmw2ir#L417) without path. Atleast in AppVeyor it looks like the wrong `msbuild` is being selected.

**Comment by denfromufa** [comment]
@vmuriart so we can close this issue?

**Comment by vmuriart** [comment]
Sure
