### ISSUE TITLE
pip uninstall leaves Python.Runtime.dll behind

### ISSUE THREAD

**Issue by davidanthoff** [pythonnet/pythonnet#44]
Install via

    pip install git+https://github.com/pythonnet/pythonnet#egg=pythonnet

then uninstall via

    pip uninstall pythonnet

This leaves Python.Runtime.dll behind in the site-packages directory, which it shouldn't.

PS: if the initial install is from a wheel, everything gets uninstalled correctly.

**Comment by tonyroberts** [comment]
Fixed in 4a53380edcf7e420c62a7a2d8cb48f63ada14ddb
