### ISSUE TITLE
Improve debugging experience - implement dynamic view on PyObject

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#443]
I watched this Dynamic C# course from pluralsight and found that implementing getdynamicmembernames gives a nice "dynamic view" option in the debugger.

Right now dynamic objects from Python to C# are black-box in the debugger.

https://www.pluralsight.com/courses/c-sharp-dynamic-fundamentals

https://msdn.microsoft.com/en-us/library/system.dynamic.dynamicobject.getdynamicmembernames(v=vs.110).aspx

**Comment by filmor** [comment]
Yes please. You could just forward to Python's `dir` function.

**Comment by denfromufa** [comment]
closed by #690
