### ISSUE TITLE
importing Class from python scripts

### ISSUE THREAD

**Issue by Prakash19921206** [pythonnet/pythonnet#447]
### Environment 

-   Pythonnet version: 2.4
-   Python version: 3.5
-   Operating System: Windows 7 64bit

how to import some method from python script file?
Lets says below is my python code
assuming there is a folder named _dir_ ,file named _demo.py_, in demo.py there's a class _test_
```
import os
import sys
import tensorflow

from dir.demo import test
dict= {key1: "value1", key2: "value2"}
obj = test(dict)
```
my C# code will be?
```
dynamic tf,os,sys;
dynamic test,obj,dict,;

using (Py.GIL())
{
    try
    {
        sys= Py.Import("sys"); os = Py.Import("os"); tf = Py.Import("tensorflow");
        Console.WriteLine("Location of import is {0}",sys.__file__);
       //how to import class & pass dictionary ?
    }
    catch (Exception ex)
    {
        Console.WriteLine( ex.Message);
    }
}
```

**Comment by denfromufa** [comment]
You can just call Python methods (in fact access any Python objects) from
modules imported as `dynamic` objects in c#, e.g. like in short tutorial in
readme file:

```
dynamic np = Py.Import("numpy"); Console.WriteLine(np.cos(np.pi * 2));
```

**Comment by filmor** [comment]
@Prakash19921206 Please stop abusing the issue tracker as a support forum. Questions like this belong to something like StackOverflow.
