### ISSUE TITLE
PythonEngine.Initialize() error

### ISSUE THREAD

**Issue by jwlc76** [pythonnet/pythonnet#448]
### Environment

-   Pythonnet version:2.4
-   Python version:2.7.13 32bit
-   Operating System: Win7 sp1 64bit

### Details

Pythonnet compiled under VS2015. Demo packages work fine (wordpad.py etc) but I get an error trying to call python from .net using the Python.Runtime.dll. 

When calling PythonEngine.Initialize(); the following error occurs in runtime.cs Line 188.

"A call to PInvoke function 'Python.Runtime!Python.Runtime.Runtime::PyDict_GetItemString' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature."

I have confirmed that the version being compiled is for windows 32bit and Python 2.7. Any suggestion much appreciated.

**Comment by filmor** [comment]
Which version (i.e. commit) are you using exactly? Can you bisect the error?

**Comment by jwlc76** [comment]
Tested with the latest commit as of a the 31-01-2017.  I will try and replicate with an earlier version.

**Comment by jwlc76** [comment]
The issues first occurs in c7b4c212407168c9c2246536aa16e57a36c2acaa (commit on the 1 march 2017)

**Comment by denfromufa** [comment]
@jwlc76 thank you for reporting this issue!

@vmuriart do you see anything suspicious in that commit? It looks like only refactoring to me.

**Comment by jwlc76** [comment]
OK Ive checked further and Ive traced it to f1aa89bb4620c98b8c6eeeb6431a0ca83add7602 (sorry I was  incorrect earlier). 
The issue is the removal of the calling convention in [DllImport(Runtime.dll, CallingConvention = CallingConvention.Cdecl)].

When googleing the error message earlier this is one of the thing that came up as a possible cause. So looks like this is the problem. Added the CallingConvention back in on the latest commit should resovle the issue.

**Comment by denfromufa** [comment]
@vmuriart well, I did this mention this before, not sure why you ended up removing calling convention anyway?

https://github.com/pythonnet/pythonnet/pull/403#issuecomment-282931584

**Comment by jwlc76** [comment]
Just to confirm adding back in the CallingConvention to the DllImports in runtime.cs on the master commit works for me.

**Comment by denfromufa** [comment]
@jwlc76 feel free to submit a pull request to add cdecl back! Let us know, thanks again.

**Comment by vmuriart** [comment]
The issue was with some of the other arguments (especially `charset`). I'll take care of re-adding the `callingconv` this weekend.
