### ISSUE TITLE
fiddler - mscorlib recursive resource lookup bug

### ISSUE THREAD

**Issue by aaronchn** [pythonnet/pythonnet#452]
### Environment

-   Pythonnet version:2.3.0
-   Python version:2.7.13
-   Operating System: Win7_32bit

### Details

Try to use pythonnet to call FiddlerCore‘s dll ( https://fars.ee/2Uk1.zip ) ,but get nothing. 
What is the correct way to use this dll ( add reference and  import namespace)？

```
>>> import clr
>>> import sys
>>>
>>> sys.path.append("C:\\FiddlerCoreAPI")
>>>
>>> print clr.FindAssembly("FiddlerCore4")
C:\FiddlerCoreAPI\FiddlerCore4.dll
>>>
>>>clr.AddReference("FiddlerCore4")
>>>for i in clr.ListAssemblies(False): print i
mscorlib
clrmodule
Python.Runtime
System.Security
System.Xml
System.Configuration
System.Data.SqlXml
System.Core
System
__CodeGenerator_Assembly
e__NativeCall_Assembly
FiddlerCore4
System.Windows.Forms
Accessibility
System.Drawing
>>>
>>>from FiddlerCore4 import Fiddler
Traceback (most recent call last):
  Python Shell, prompt 5, line 1
ImportError: No module named FiddlerCore4
>>>
>>>from FiddlerCore4 import *
Traceback (most recent call last):
  Python Shell, prompt 6, line 1
ImportError: No module named FiddlerCore4
>>>
>>>import FiddlerCore4
Traceback (most recent call last):
  Python Shell, prompt 8, line 1
ImportError: No module named FiddlerCore4
>>>
>>>import FiddlerCore
Traceback (most recent call last):
  Python Shell, prompt 7, line 1
ImportError: No module named FiddlerCore

```
I tried another way:

```
>>>myf = clr.AddReference("FiddlerCore4")
>>>dir(myf)
['CodeBase', 'CreateInstance', 'CreateQualifiedName', 'CustomAttributes', 'DefinedTypes', 'EntryPoint', 'Equals', 'EscapedCodeBase', 'Evidence', 'ExportedTypes', 'Finalize', 'FullName', 'GetAssembly', 'GetCallingAssembly', 'GetCustomAttributes', 'GetCustomAttributesData', 'GetEntryAssembly', 'GetExecutingAssembly', 'GetExportedTypes', 'GetFile', 'GetFiles', 'GetHashCode', 'GetLoadedModules', 'GetManifestResourceInfo', 'GetManifestResourceNames', 'GetManifestResourceStream', 'GetModule', 'GetModules', 'GetName', 'GetObjectData', 'GetReferencedAssemblies', 'GetSatelliteAssembly', 'GetType', 'GetTypes', 'GlobalAssemblyCache', 'HostContext', 'ImageRuntimeVersion', 'IsDefined', 'IsDynamic', 'IsFullyTrusted', 'Load', 'LoadFile', 'LoadFrom', 'LoadModule', 'LoadWithPartialName', 'Location', 'ManifestModule', 'MemberwiseClone', 'ModuleResolve', 'Modules', 'Overloads', 'PermissionSet', 'ReferenceEquals', 'ReflectionOnly', 'ReflectionOnlyLoad', 'ReflectionOnlyLoadFrom', 'SecurityRuleSet', 'ToString', 'UnsafeLoadFrom',
...]
```
Any help?

**Comment by denfromufa** [comment]
@aaronchn when you do clr.AddReference - it is assembly name, when you do `import namespace.class`, it is namespaces and classes in the assembly, which can be completely different from assembly name.

But fiddlecore has other issues with pythonnet. Let us know if you reproduce any of this:

http://stackoverflow.com/questions/41485231/fiddlercore-with-python-for-net

**Comment by aaronchn** [comment]
@denfromufa 
I geuss missed a “s” with “def printReq(sesion)” in line 7 caused that warning “mscorlib recursive resource lookup bug” 

Turn on my situation，put the flowing code （copy totally and paste at once or input one line by one  ）in to the Python interactive shell，-

```
import clr
import System
import sys

sys.path.append(r"C:\FiddlerCoreAPI")

clr.FindAssembly("FiddlerCore4")
clr.AddReference("FiddlerCore4")

import Fiddler

def printReq(session):
    print(session)

Fiddler.CONFIG.IgnoreServerCertErrors = False
Fiddler.FiddlerApplication.BeforeRequest += printReq
Fiddler.FiddlerApplication.Startup(8877, Fiddler.FiddlerCoreStartupFlags.Default)
```
every thing seems like correctly：

![correct](https://cloud.githubusercontent.com/assets/6897149/24969558/c3541014-1fe3-11e7-80b9-8ffed145ddb6.png)

But when I saved these code as a xx.py file and run it with “C:\xxx>python xx.py”, it will be fire a bug like this:

![failure](https://cloud.githubusercontent.com/assets/6897149/24969723/43fdee9c-1fe4-11e7-83f5-ccee3cd65ab3.png)

BTW. attache a little preview of FiddlerCore4.dll:

![ilspy](https://cloud.githubusercontent.com/assets/6897149/24969795/9302bfc2-1fe4-11e7-87e0-59af0556ab1f.png)

**Comment by denfromufa** [comment]
Not reproduced, can you try switching your locale to US-English?

**Comment by aaronchn** [comment]
@denfromufa 
Will be test this bug with US-English locale and other PC in recent days, the give you feedback.

**Comment by aaronchn** [comment]
After some testing, my conclusion is : 
In some win7 edition, setting display language to Chinese Simple will fires this warning.
In some win7 edition, setting locale to Chinese-Simple or US-English will not affect the code running.

**Comment by denfromufa** [comment]
@aaronchn thank you for checking. This is probably related to issue with underlying library UnmanagedExports. I'm going to try upgrading to DllExport, which seems to have fixed the problem:

https://github.com/3F/DllExport/issues/7

**Comment by aaronchn** [comment]
Thank you for your contribution on pythonnet.

**Comment by aaronchn** [comment]
May I ask for some help to you of pythonnet about my pyfiddler? if
you can ,please send an email to me "aaronchn@live.com" to help me get your email and post my question. Thanks.

**Comment by denfromufa** [comment]
@aaronchn i have not much experience with fiddler, but @dmitriyse seems very knowledge about it :+1:

**Comment by aaronchn** [comment]
@denfromufa  @dmitriyse
I’m trying to make a little toolkit for someone in Github (pyfiddler)，until now，my major goal is done.
But there still some ugly of the code.One is just putting CertMaker.dll and BCMakeCert.dll to python bin directory can be work with fiddler and any other path will not.  I tried to reference theme like FiddlerCore4.dll，seems dose not work。After search google，the answer may be .net’s “BASE DIR”, but i cant cover it from C# to python。 Is there simple way can allow put theme to any where and call it in code?
 
Another is when i try to use win32api，seems can not to [DllImport("xxx.dll")] like C#‘s way。Is there any ’shortcut‘ to do this?

Sorry for my poor English language and tyro of python.

**Comment by filmor** [comment]
This looks done, please open a new issue if you have any more problems.
