### ISSUE TITLE
Conda/Bioconda - TrustFailure error Travis

### ISSUE THREAD

**Issue by RJMW** [pythonnet/pythonnet#455]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 2.7 and 3.4
-   Operating System: Unix
-   Mono: 4.8.1 (conda)

### Details

@bgruening and I are trying to make pythonnet available for unix via Conda/Bioconda. Conda/Bioconda is used as a dependency resolver for Galaxy (galaxy.org). There is a recipe available for windows but not for Unix. Is there any particular reason as to why there is no Conda recipe for unix?

We have tried to write a recipe for bioconda (conda), but we run into a TrustFailure error. See Travis logs for the specific error: https://travis-ci.org/RJMW/bioconda-recipes/jobs/224956891#L993 Locally I can build the (bio) conda package without problems.

Please, do you have any idea what the issue is?

**Comment by denfromufa** [comment]
@RJMW this looks like very common issue with nuget and Mono, the certificates need to be installed.
Have you tried this? I can't see your full conda build scripts for pythonnet. What nuget version are you using?

**Comment by bgruening** [comment]
@denfromufa we are using this mono package: https://github.com/conda-forge/mono-feedstock
No extra nuget package, so I assume it is installing nuget on it's own? Sorry no mono expert :(
Do you know where I get the certificates? Can I simply download them?

**Comment by denfromufa** [comment]
@bgruening you are building mono from source, that maybe the issue. I have never done this before. See our configuration for Mono on travis ci:

https://github.com/pythonnet/pythonnet/blob/master/.travis.yml#L23

@vmuriart has more experience with this.

**Comment by denfromufa** [comment]
your nuget is up to date - version 3.5 (recommended)

**Comment by RJMW** [comment]
@akoeplinger suggested to try this: http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync

**Comment by bgruening** [comment]
@denfromufa we got a step further. Have you seen this error before?
https://travis-ci.org/bioconda/bioconda-recipes/jobs/225699894#L2080

**Comment by denfromufa** [comment]
@bgruening you are probably missing xbuild or one of its dependencies. They get installed with mono-complete:

http://www.mono-project.com/docs/getting-started/install/linux/#usage

**Comment by bgruening** [comment]
@denfromufa we have xbuild and the entire stack even cert-sync and so on.
We can not install these packages you recommend as we need this on HPC environments. There you don't have these package managers. So we try to get this running - we are more or less creating such packages now.
Any other idea what can cause such an error or what it means?

**Comment by akoeplinger** [comment]
@bgruening the error in your case is this:

```
Error executing tool '/opt/conda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/mono/4.5/mcs.exe': 
ApplicationName='/opt/conda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/mono/4.5/mcs.exe', CommandLine='/noconfig @/tmp/tmp1a0a5f0d.tmp', CurrentDirectory='/opt/conda/conda-bld/work/pythonnet-2.3.0/src/runtime', Native error= Cannot find the specified file
```

looks like your packages are wrong.

**Comment by bgruening** [comment]
@akoeplinger probably, but why. This looks really strange.

```
(mono) [root@d95f44af178c /]# file /opt/conda/envs/mono/bin/mono-sgen
/opt/conda/envs/mono/bin/mono-sgen: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, not stripped
(mono) [root@d95f44af178c /]# file /opt/conda/envs/mono/lib/mono/4.5/mcs.exe 
/opt/conda/envs/mono/lib/mono/4.5/mcs.exe: PE32 executable for MS Windows (console) Intel 80386 32-bit Mono/.Net assembly
(mono) [root@d95f44af178c /]# cat /opt/conda/envs/mono/bin/mcs 
#!/bin/sh
exec /opt/conda/envs/mono/bin/mono $MONO_OPTIONS /opt/conda/envs/mono/lib/mono/4.5/mcs.exe "$@"
(mono) [root@d95f44af178c /]# /opt/conda/envs/mono/bin/mcs --version
Mono C# compiler version 4.8.1.0
(mono) [root@d95f44af178c /]# /opt/conda/envs/mono/lib/mono/4.5/mcs.exe --version
bash: /opt/conda/envs/mono/lib/mono/4.5/mcs.exe: No such file or directory
(mono) [root@d95f44af178c /]# 
```

Is this what you should get if you simply compile mono? A mixed 64bit and 32bit build?

**Comment by akoeplinger** [comment]
@bgruening yes that's expected. `mono-sgen` is the native binary for Mono, `mcs.exe` is a managed .NET assembly so the architecture isn't relevant there (ignore the `32-bit` part that `file` reports). 

You can't run mcs.exe directly, you need to do what the wrapper script in `/opt/conda/envs/mono/bin/mcs` does, i.e. run it via the mono binary (except if you use e.g. the Process.Start() .NET API because that one knows how to run .NET assemblies internally).

My earlier comment above was that it tried to run `/opt/conda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/mono/4.5/mcs.exe` which clearly doesn't exist.

**Comment by bgruening** [comment]
@akoeplinger why does this not exists? It really exists, promised, the `file nor found error` comes from calling this 32bit binary directly in a 64bit system. I can reproduce this here:

```
(mono) [root@d95f44af178c /]# /opt/conda/envs/mono/lib/mono/4.5/mcs.exe --version
bash: /opt/conda/envs/mono/lib/mono/4.5/mcs.exe: No such file or directory
```

**Comment by akoeplinger** [comment]
@bgruening as I said, you can't do it like this on the shell. You'd need to do `mono /opt/conda/envs/mono/lib/mono/4.5/mcs.exe --version`

And `/opt/conda/envs/mono/lib/mono/4.5/mcs.exe` is not the same as `/opt/conda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/mono/4.5/mcs.exe` which the error was about.

**Comment by bgruening** [comment]
This I got, but the pythonnet installer is calling `/opt/conda/conda-bld/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/mono/4.5/mcs.exe` as it seems and this is why it crashes. Or maybe I get something really wrong here, but the initial error from https://travis-ci.org/bioconda/bioconda-recipes/jobs/225699894#L2080 suggests that the installer is calling this mcs.exe in this strange way, isn't it?

**Comment by akoeplinger** [comment]
Yeah, something is wrong with the package.

**Comment by bgruening** [comment]
With pacjage you mean the pytonnet? Sorry to bother you so much, just want to make sure that we did everything like expected.

**Comment by akoeplinger** [comment]
wherever Mono and xbuild come from, I have no idea how you're packaging it :)

**Comment by bgruening** [comment]
;) This I can show you. Simply compiled package: https://github.com/conda-forge/mono-feedstock/blob/master/recipe/build.sh

No seriously, if the pythonnet installer is calling this script `/whatever/lib/mono/4.5/mcs.exe` without the prefix, how can this work? Or the other question what can cause the pythonnet installed to not use the prefix thingy?

**Comment by akoeplinger** [comment]
no idea, I'm not familiar with pythonnet at all unfortunately :)

though it looks like it just calls `xbuild` so it's more likely the Mono package is wrong, i.e. the value passed to `--prefix=` doesn't match with where it's installed on the machine.

**Comment by bgruening** [comment]
@akoeplinger ok, thanks for you help. I keep poking! Greetings to Austria!

**Comment by denfromufa** [comment]
@bgruening sorry can't help much with your customized environment, but one quick thing you can do is to flip verbosity up higher in setup.py to troubleshoot this weird path issue.

https://github.com/pythonnet/pythonnet/blob/master/setup.py#L24

**Comment by denfromufa** [comment]
@RJMW @bgruening looks like this been resolved? i see now you have conda binaries for pythonnet:

https://anaconda.org/bioconda/pythonnet
