### ISSUE TITLE
import .net assembly with unmanaged code

### ISSUE THREAD

**Issue by yiwsun** [pythonnet/pythonnet#459]
### Environment

-   Pythonnet version:2.3
-   Python version:3.5
-   Operating System: Windows Server 2016

### Details

I was trying to install a .net dll using pythonnet, but it depends on caffe.managed.dll, So I want to import caffe dll (in the same folder) using:
    *clr.AddReference("C:\\demo\\caffe.managed.dll")*
which returns an error: FileNotFoundException: Unable to find assembly 'C:\demo\caffe.managed.dll'.
   at Python.Runtime.CLRModule.AddReference(String name)
I also tried:
    *print(clr.FindAssembly("C:\\demo\\caffe.managed.dll"))*
    which returns: None

Then I used ILSpy to check this caffe.managed.dll, which shows:
// Global type: <Module>
// Architecture: x64
// This assembly contains unmanaged code.
// Runtime: .NET 4.0

I am guessing because this caffe dll has "unmanaged code" which makes it not supported by pythonnet. Is there any way to import it?

**Comment by filmor** [comment]
Are you sure that you are running a x64 version of Python? You cannot mix different binaries in a single process, but as long as the DLL and Python bitness match you shouldn't have a problem.

**Comment by denfromufa** [comment]
@yiwsun AddReference looks for assembly name WITHOUT ".DLL":

https://github.com/pythonnet/pythonnet/search?utf8=%E2%9C%93&q=AddReference&type=

I updated troubleshooting wiki, since this is asked very often:

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows-and-Linux

**Comment by yiwsun** [comment]
Here is the updated code:
import clr,sys
dlldir = "C:\\demo"
sys.path.append(dlldir)
dllname = clr.FindAssembly("caffe.managed")
print(dllname)
clr.AddReference("caffe.managed")

Now clr.FindAssembly() can get the correct path, e.g. "C:\demo\caffe.managed.dll", but AddReference() still 
reports error: 
FileNotFoundException: Unable to find assembly 'caffe.managed'.
   at Python.Runtime.CLRModule.AddReference(String name)

**Comment by yiwsun** [comment]
@filmor, I used the below script to test Python bit
import sys,platform; 
print(platform.architecture()[0])
print(sys.maxsize > 2**32)

import struct;
print(struct.calcsize("P") * 8)

The output:
64bit
True
64

**Comment by denfromufa** [comment]
@yiwsun are you able to load this DLL from C# (e.g. using scriptcs)?

Also you can inspect the loading process using this:

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows-and-Linux#assembly-binding-errors

**Comment by yiwsun** [comment]
@denfromufa the dll works fine in my c# sample code

**Comment by denfromufa** [comment]
@yiwsun so where is your caffe.managed? Is is this DLL:

https://github.com/Microsoft/caffe/tree/master/windows/caffe.managed

If yes, then it looks completely unmanaged.

**Comment by yiwsun** [comment]
@denfromufa I didn't build the dll, it came with the other packages, I uploaded it here for your reference:
https://yiwtmp.blob.core.windows.net/tempblob/pythonnet/caffe.managed.dll

According to some online discussion if GetAssemblyName() on it doesn't generate error, it would be a managed dll. This one passed so I was assuming it is a managed dll.

**Comment by denfromufa** [comment]
@yiwsun no, i can't load this even in c#:

```
>scriptcs
scriptcs (ctrl-c to exit or :help for help)

> #r "C:\caffe.managed.dll"
AssemblyLoader failed to load assembly caffe.managed, Version=1.0.6095.17351, Cu
lture=neutral, PublicKeyToken=null
```

**Comment by yiwsun** [comment]
@denfromufa Do you know if an unmanaged dll, which is loaded using ctypes in Python, will be able to work with other dlls loaded using clr?

**Comment by denfromufa** [comment]
your question is too broad. it looks like this dll has some issues. so I think we should close this issue @filmor @yiwsun

**Comment by denfromufa** [comment]
@yiwsun if you have more info (e.g. working C# solution), then let us know. But otherwise this DLL looks very special, such that even scriptcs cannot handle it. So I'm closing this issue for now.
