### ISSUE TITLE
mono 5.0 - xbuild deprecated, C# 7.0,  concurrent garbage collector

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#464]
http://www.mono-project.com/docs/about-mono/releases/5.0.0/

**Comment by vmuriart** [comment]
I've frozen the language to C# 6.0 when C# 7.0 features were rolling out. I don't want to upgrade the language (atleast not now).

GC... I still have nightmares about our current GC setup, I don't think we want to further complicate it.

The only actionable item I see here is the `xbuild` deprecation (i assume this will affect our Travis CI eventually) We'll have to play around w it to see how to set it up.

**Comment by denfromufa** [comment]
I agree on C# 6.0 and xbuild, not sure about GC. Together with C#6.0 and xbuild, also underlying compiler is updated from "mcs" to "csc" (roslyn).

**Comment by wesnerm** [comment]
Is it possible to add the C# 7.0 support, since competitive programming sites aren't using the csc build because it takes too much memory and the compiler is killed by the OS?

**Comment by denfromufa** [comment]
can you give example of your problem, this does not make sense to me. so you need to use alternative to csc (mcs?) and support C# 7.0 in a code-base that calls into pythonnet?
