### ISSUE TITLE
Using dll assembly in python on Windows 7 

### ISSUE THREAD

**Issue by riccardodelutio** [pythonnet/pythonnet#466]
### Environment

-   Pythonnet version: 2.3
-   Python version: 2.7
-   Operating System: Windows 7

### Details

Following the installation process and the steps detailed in the wiki I have 
```
>>>import clr 
>>>clr.AddReference("SUDS")
<System.Reflection.RuntimeAssembly> object at 0x0000000001FDD780
>>>import SUDS
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
ImportError: No module named SUDS
```

I have successfully run this on a Windows 10 VM proceeding exactly in the same way so I first tough it had something to do with the `sys.path` I tried adding the assembly's path to the `sys.path` before importing `clr` but it's also unsuccesful.

Thank you

**Comment by denfromufa** [comment]
this is weird, which .NET version and architecture does SUDS target? Can
you share this assembly? 32-bit or 64-bit Python? Does SUDS have any
dependencies?

On Mon, May 15, 2017 at 8:49 AM, Riccardo de Lutio <notifications@github.com

**Comment by riccardodelutio** [comment]
Unfortunately I haven't written the source C# code myself so I'm not sure about all the details and unfortunately I can't share it online. I don't think it depends on anything. And I would guess it targets 64-bit architectures as it works on my Windows 10 VM on 64-bit. And the pyhton I'm using on Windows 7 is 64-bits

**Comment by riccardodelutio** [comment]
I also tough it could have something to do with the path that had a non ASCII character in it because of the username so I change to a different user so that the path has all ASCII characters and I still have the problem.

**Comment by riccardodelutio** [comment]
I tried it once by installing Python and everything myself and then by downloading Anaconda but both methods have failed in the same way

**Comment by denfromufa** [comment]
Can you confirm that you are using 64-bit Python 2.7 on both Windows 7 and
Windows 10?

Here is email address where you can share the DLL privately with me: my
github handle at gmail dot com

Please try the steps from troubleshooting wiki, particularly inspect the
contents of assembly with ILSPY and review the binding log with
Fuslogvw.exe:
https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows-
and-Linux

Also try to add the reference to this DLL with scriptcs (
http://scriptcs.net/):

`#r "SUDS.dll"`



On Mon, May 15, 2017 at 9:29 AM, Riccardo de Lutio <notifications@github.com

**Comment by riccardodelutio** [comment]
Hello,

Yes I'm using Python 2.7 on both Windows 7 and 10. Unfortunately I can't share it as it is property of a company I'm working with. 

And thank you I will try the steps from the troubleshooting and keep you updated

**Comment by riccardodelutio** [comment]
Using ILSPy I can see that SUDS is for
Architecture : AnyCPU (64-bit preferred)
and it uses .NET Framework 4 version 4.5

**Comment by riccardodelutio** [comment]
Trying to install .NET version 4.5 I don't know if that has something to do with it, this is the first time I come across .NET and DLL 's

**Comment by denfromufa** [comment]
Do you have .NET 4.5 on your Windows 7? I have never seen 64-bit preferred
AnyCPU compilation.
Anyway you still have not confirmed if you have 64-bit Python on both
machines (python --version).

On Mon, May 15, 2017 at 9:59 AM, Riccardo de Lutio <notifications@github.com

**Comment by riccardodelutio** [comment]
I'm installing .NET 4.5 right now 
Yes I have python 2.7 on both my windows 7 and windows 10

**Comment by riccardodelutio** [comment]
It's working since I have installed .NET 4.5 and rebooted.

Thanks for the advice!
