### ISSUE TITLE
Running Embedded Python.NET Application on Environment without Python Installed?

### ISSUE THREAD

**Issue by rionmonster** [pythonnet/pythonnet#467]
### Environment

-   Pythonnet version: 2.2.2
-   Python version: 2.7
-   Operating System: Windows 10

### Details

I haven't worked _too_ extensively with Python previously, but I've been experimenting with the idea of writing some utilities using it and embedding them within a .NET application (e.g. Windows Forms, Console, WPF, etc.). Is it possible to embed Python itself within the assembly using Python.NET or is it required that Python be installed on the executing machine?

Any attempts that I made to run outside of my development environment (with Python 2.7 installed), resulted in an error about a missing `python27.dll`, which I couldn't seem to figure out how to include, and I may just be missing something.

Ideally, I'd like to be able to package this up as an executable, distribute it to users, who will likely not have Python installed on their machine. I know that the documentation mentions the need for an interpreter and I was wondering if the one available with [IronPython](http://ironpython.net/) would suffice?

Any advice would be appreciated. I understand that this _may_ not be plausible, but I'd love to take advantage of using Python.NET for this if possible.

**Comment by denfromufa** [comment]
That is exactly what I'm doing with pythonnet, but I install CPython as part of larger installation.

@rionmonster one option would be to use the nuget packages for CPython and pythonnet:

https://www.nuget.org/packages/python2/
https://www.nuget.org/packages/pythonnet_py27_dotnet/

When embedding this nuget package in .NET app, you will need to set PYTHONHOME environment variable or this property `PythonEngine.PythonHome` in pythonnet so that CPython can be located at runtime.

**Comment by rionmonster** [comment]
Thanks for the insights @denfromufa 

I eventually elected to go another route for the time being, but I was able to play around with the use of `PythonHome` along with the aforementioned NuGet packages. That's certainly an option I'll consider should the need arise again.

I appreciate it.

**Comment by willdrob** [comment]
@denfromufa @rionmonster I'm attempting to do the same thing. I installed pythonnet_py27_dotnet & python2 via nuget and then I'm setting `PythonEngine.PythonHome` to the location of the python2 folder. `Python.Runtime` is giving me an error: "Unable to load DLL 'python27': The specified module could not be found." even though the DLL is in the PythonHome folder.

If I drop the DLL in the appropriate Windows\System location everything works as expected but that's what I'm trying to avoid. Any ideas on how to get pythonnet to find the python27 DLL?

**Comment by denfromufa** [comment]
@willdrob you may need to append this python path to `%path%` env. var. too.

Also there is outstanding issue with explicitly picking the 64-bit binary if you have Python 64-bit:

https://github.com/pythonnet/pythonnet/issues/472#issuecomment-304121261

**Comment by willdrob** [comment]
@denfromufa you are correct, I needed to append the python path to %path%.
`var path = $"{Environment.GetEnvironmentVariable("Path", EnvironmentVariableTarget.Machine)};{pythonPath}";`
`Environment.SetEnvironmentVariable("Path", path, EnvironmentVariableTarget.Process);`
It's working now, thanks for the help!

**Comment by denfromufa** [comment]
@ryan-rogowski just hide %PYTHONHOME% in your app before loading Python runtime.

**Comment by ryan-rogowski** [comment]
> @ryan-rogowski just hide %PYTHONHOME% in your app before loading Python runtime.

Thanks @denfromufa ! Do you mean to set PYTHONHOME to an empty string prior to loading Python runtime? or how would I go about hiding the environment variable from my app?

            //Check if python environment variable is set
            string path = Environment.GetEnvironmentVariable("PYTHONHOME", EnvironmentVariableTarget.Machine);
            if (path != null) {
                Environment.SetEnvironmentVariable("PYTHONHOME", "");
            }

**Comment by Maghil** [comment]
@wdrobinson HI I'm new so bare with me,My code looks like this
`private string path = Environment.CurrentDirectory+"\\packages\\Python35\\";`
`PythonEngine.PythonHome=path;`
`PythonEngine.Initialize();`

But your's is
`var path = $"{Environment.GetEnvironmentVariable("Path", EnvironmentVariableTarget.Machine)};`
`{pythonPath}";`
`Environment.SetEnvironmentVariable("Path", path, EnvironmentVariableTarget.Process);`

I need explanation of how you're setting path without using
`PythonEngine.PythonHome=path;` 
and what is %path%

**Comment by gerneio** [comment]
Wanted to add some notes about embedding the latest version of python (3+) while using pythonnet. As mentioned previously, there is a [python nuget package](https://www.nuget.org/packages/python) that contains all the python runtime. It supports current python version `3.12.1` as of today (I'm using `3.9.0` below). To utilize this package and the embedded python runtime, here are the steps I've followed:

Add `PackageReference`'s to csproj:

```csproj
  <ItemGroup>
    <PackageReference Include="pythonnet" Version="3.0.3" />
    <PackageReference Include="python" Version="3.9.0" />
  </ItemGroup>
```

Add an item in csproj to include the python nuget package's `tools` folder (which contains the python runtime) in the build output folder:

```csproj
  <ItemGroup>
    <None Include="$(Pkgpython)\tools\**\*" LinkBase="python" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
```

Update `PythonDLL` and `PythonHome` accordingly:

```csharp
using Python.Runtime;

var pythonDir = Path.Combine(Environment.CurrentDirectory, @"python");

// hardcoded for now, but can probably be made to a bit more dynamic if we search through the `python` output directory
Runtime.PythonDLL = Path.Combine(pythonDir, "python39.dll"); 
PythonEngine.PythonHome = pythonDir;

PythonEngine.Initialize();
```

I suspect when copying the files from the python nuget package's `tools` folder, we could probably cut out some chunks that aren't required to limit our app build size (haven't messed with this yet). Also, right now I'm hardcoding the `python39.dll` part, but I suspect it wouldn't be too difficult to make this a little more dynamic, so you can update the python nuget package version w/o updating the hardcoded variable, but I figured this works to demonstrate the point for now.

Credit to above posters for paving the way, as well as this [SO post](https://stackoverflow.com/a/75732372/10388359) which shed some light on how to copy the python nuget package's contents to the build output folder.

Btw, if you want to browse the full contents of the python nuget package's directory, you can view it under this folder `%UserProfile%\.nuget\packages\python` on windows or presumably `~/.nuget/packages/python` on Mac/Linux (untested).

Hope this helps get someone on the ground a bit quicker. Now I'm trying to figure out how to install python modules at build time to the output directory...

**Comment by gerneio** [comment]
As for installing python modules, here's a really simple example target after build that accomplishes this:

```csproj
    <Target Name="InstallPyModules" AfterTargets="Build">
        <PropertyGroup>
          <PyModules>cryptography pyasyncore boto3 prompt_toolkit google-auth requests</PyModules>
        </PropertyGroup>
        <Message Text="Installing python modules: $(PyModules)" Importance="High" />
        <Exec Command="$(OutputPath)python\python.exe -m pip install $(PyModules) --quiet --disable-pip-version-check" />
    </Target>
```
