### ISSUE TITLE
Unable to create a subclass of System type with a different number of input arguments

### ISSUE THREAD

**Issue by klasma** [pythonnet/pythonnet#469]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 2.7.13
-   Operating System: Windows 10

### Details

I am trying to create a subclass of a System type. The System type takes zero input arguments, and the subclass should take one input argument. The constructor does not seem to be created correctly.

The following example reproduces the error:

```
import clr
import System

class Test(System.Object):
    __namespace__ = "PyTest"
    def __init__(self, x):
        self.X = x

t = Test(1)
```

The following error message is given:

TypeError: __init__() takes exactly 2 arguments (1 given)

I would be very grateful if you could fix this or explain what I'm doing wrong.

**Comment by denfromufa** [comment]
This works without `__namespace__`:

```
In [4]: import clr
   ...: import System
   ...:
   ...: class Test(System.Object):
   ...:     #__namespace__ = "PyTest"
   ...:     def __init__(self, x):
   ...:         self.X = x
   ...:
   ...: t = Test(1)


In [5]: t
Out[5]: <__main__.Test at 0x3f8bb20>


In [6]: t.X
Out[6]: 1
```

**Comment by klasma** [comment]
Thank you for getting back to me so quickly!

That does not seem to work when the class is used outside python. In the following example

```
from System.Collections.Generic import List
testList = List[Test]()
testList.Add(Test(1))
testList[0].X
```
I get the error

AttributeError: 'Object' object has no attribute 'X'

And if I run

`t.GetType().FullName`

I get that t is a System.Object and not a Test as it was before. (Previously it was a PyTest.Test)

**Comment by denfromufa** [comment]
The .Add method of List expects System.Object as argument in this case. So
the Test object gets converted to System.Object.

**Comment by klasma** [comment]
Is there a way to make the code below (or something similar) work? Or are we limited to using constructors with 0 input arguments for objects that we use outside python? We are trying to replace IronPython with pythonnet in an existing application, so we would need a lot of existing code to work with minimal changes.

```
import clr
import System
from System.Collections.Generic import List

class Test(System.Object):
    def __init__(self, x):
        self.X = x

testList = List[Test]()
testList.Add(Test(1))
testList[0].X
```

If this is a known and intended limitation, I am happy to close the bug and submit this as a feature request instead.

**Comment by filmor** [comment]
The code example given here works on the current master.
