### ISSUE TITLE
RunSimpleString variarible not visible in Eval

### ISSUE THREAD

**Issue by grig27** [pythonnet/pythonnet#474]
### Environment

-   Pythonnet version: 2.3.0.0
-   Python version: 2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]
-   Operating System: Windows 7

### Details

How to use Eval() variarible after RunSimpleString()

### Details

PythonEngine initialize very good.

After PythonEngine.RunSimpleString("a=1") code PythonEngine.RunSimpleString("print(a)") printing char "1".
On PythonEngine.Eval this command run this exception "name "a" is not defined".

**Comment by denfromufa** [comment]
Have a look at this additional embedding API in this pull request:

https://github.com/pythonnet/pythonnet/pull/381

**Comment by denfromufa** [comment]
Here is how eval supposed to be used with local variables:

https://github.com/pythonnet/pythonnet/blob/8ce4e0e78ba6028cfb1447ce6c0d06950afd23aa/src/embed_tests/pyrunstring.cs#L34

I'm going to keep this issue open, so that the corresponding docs can be added.

**Comment by filmor** [comment]
Since `RunSimpleString` is obsolete now and `PyScope` provides a much nicer interface, I'll close this.
