### ISSUE TITLE
Py.GIL  System.BadImageFormatException: An attempt was made to load a program with an incorrect format

### ISSUE THREAD

**Issue by EnjoyLeole** [pythonnet/pythonnet#476]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.5.2
-   Operating System: win10 64bit
vs2017 community (15.2)
.net  framework 4.5.2

### Details

try to call python script from c#, following your introduction, in both x86 & x64 platform

using(Py.GIL()){}

Then got following error:

System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (HRESULT:0x8007000B)'

**Comment by denfromufa** [comment]
How did you install pythonnet?

**Comment by denfromufa** [comment]
@EnjoyLeole you likely used nuget to install pythonnet and we found last week that VS does not switch architecture for Nuget installed package. You have to do it manually:

https://github.com/pythonnet/pythonnet/issues/472

**Comment by denfromufa** [comment]
Feel free to report back if this is not nuget.
