### ISSUE TITLE
Two differnt exceptions on x64 and x86 in VS calling python script

### ISSUE THREAD

**Issue by keowang** [pythonnet/pythonnet#478]
### Environment

-   Pythonnet version: 2.3.0 installed through nugget pythonnet_py35_dotnet
-   Python version: 3.5.3
-   Operating System: Win10

### Details
Running Embedding Python in .NET on x86 Py.GIL() triggers the following:
An unhandled exception of type 'System.DllNotFoundException' occurred in Python.Runtime.dll

Additional information: Unable to load DLL 'python35': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

on x64 a different one: 
An unhandled exception of type 'System.BadImageFormatException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'Python.Runtime, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Searched for the similar issues some are pointing to the Nuget error in switching platforms but if that's the case one of the two should work right?

where python: C:\Users\XXX\AppData\Local\Programs\Python\Python35\python.exe
python --version: Python 3.5.3

%PYTHON_HOME%: C:\Users\XXX\AppData\Local\Programs\Python\Python35
%PYTHONPATH%: C:\Users\XXXX\AppData\Local\Programs\Python\Python35\Lib

The only thing I want to do is to call Python scripts from C# application. It would be great if there is a simple short cut.

**Comment by keowang** [comment]
default key in InstallPath: C:\Users\XXXX\AppData\Local\Programs\Python\Python35\python.exe
default key in PythonPath: C:\Users\XXXX\AppData\Local\Programs\Python\Python35\DLLs\

**Comment by denfromufa** [comment]
we found last week that VS does not switch architecture for Nuget installed package. You have to do it manually:

#472

**Comment by keowang** [comment]
#472 I saw that one and it was not clear to me how to update manually would you please elaborate a bit more? Thanks!

**Comment by denfromufa** [comment]
Go to nuget package location and select x86 or x64 folder and add this
reference manually to the project as assembly (not nuget package).

**Comment by keowang** [comment]
Here is what I did you can correct me whenever I am wrong:
1. save the Python.Runtime.dll from x64
2. uninstall the pythonnet nugget package completely from my application 
3. add Python.Runtime.dll into my application by right-clicking reference and add reference
4. run example code again same error.
Where I got wrong? Thanks!

**Comment by keowang** [comment]
Also you are not answering my question why is it two different errors if it were for the architecture compatibility issue one of the two should be working shouldn't it?

**Comment by denfromufa** [comment]
I just checked and it is working fine with 64-bit Python 3.5. You can only use x64 or x86 corresponding to Python architecture, so can you show full output of `python --version`?

**Comment by keowang** [comment]
C:\Users\XXXX>python --version
Python 3.5.3

I installed the 64 bit python which did not work with either x64 or x86

**Comment by keowang** [comment]
Specifically on x64 it's complaining 

An unhandled exception of type 'System.DllNotFoundException' occurred in Python.Runtime.dll

Additional information: Unable to load DLL 'python35': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by denfromufa** [comment]
Can you install with pip instead of nuget?

**Comment by keowang** [comment]
like this:
pip install git+https://github.com/pythonnet/pythonnet
?

**Comment by denfromufa** [comment]
pip install pythonnet

**Comment by keowang** [comment]
Hay, this thing is killing me I would appreciate if you bear with me.
1. pip install pythonnet-2.3.0-cp35-cp35m-win_amd64.whl
2. add Python.Runtime.dll from C:\Users\XXX\AppData\Local\Programs\Python\Python35\Lib\site-packages to my C# application 
3. run example again. Exactly same error.

**Comment by denfromufa** [comment]
Did you add your python to path?

%Python_home% is wrong environment variable, it should be without
underscore.

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows-and-Linux

**Comment by keowang** [comment]
"Installed CPython is reachable by %PATH% or %PYTHONHOME% environment variables."

Maybe change the or to and since PYTHON_HOME is added to PATH? It worked, thanks very much!

**Comment by denfromufa** [comment]
Pythonhome is needed for embedding python, while python in path is only when starting the Python interpreter.

**Comment by keowang** [comment]
last question, would python3.6 work with pythonnet-2.3.0-cp35?

**Comment by denfromufa** [comment]
You can install for python 3.6 with pip from PyPi:

https://pypi.python.org/pypi/pythonnet/2.3.0

Another thing about pythonhome is that it is only required for python
installation, that is not registered globally on the machine or when
multiple python versions are installed.

**Comment by keowang** [comment]
thanks!
