### ISSUE TITLE
Interoperability between pythonnet and tensorflowSharp while porting tensorflow python code to .NET 

### ISSUE THREAD

**Issue by JimSEOW** [pythonnet/pythonnet#479]
Tensorflowsharp community is currently working to[ port tensorflow python code to .NET](https://github.com/migueldeicaza/TensorFlowSharp/issues/77)

One of the example include a display of chart that is simple to do in python environment but still extra work to do in both TensorflowSharp in Xamarin Notebook or pythonnet in juypter (CSharp).

=> tensorflow code in juypter Python
![applicationframehost_2017-05-31_00-08-14](https://cloud.githubusercontent.com/assets/8244633/26607247/dcfa986c-4595-11e7-9730-1fb6aadfa1af.png)

=> tensorflowSharp code in Xamarin Workbook (Csharp)
![xamarin workbooks_2017-05-31_00-14-59](https://cloud.githubusercontent.com/assets/8244633/26607349/6067d138-4596-11e7-95db-fd9e9447f75b.png)

![xamarin workbooks_2017-05-31_00-15-18](https://cloud.githubusercontent.com/assets/8244633/26607352/64146a76-4596-11e7-9047-113625a02535.png)

**# Question !**
[1] Is pythonnet helpful in supporting the porting of tensorflow python code to .NET using tensorflowSharp?

[a1] Could the [MatplotLib (CS)](https://github.com/pythonnet/pythonnet/issues/442) be used in Xamarin Workbook to provide an inline chart? 
[a2] Alternatively, [Mathplotlib (CS) ](https://github.com/pythonnet/pythonnet/issues/442)can be used in Jupyter for Csharp for the inline chart?

[2] More importantly.
[b1] How ready is pythonNET to support porting tensorflow python code to .NET through pythonNET?
[b2] _Is there **an **intermediary** role for pythonNET** to play supporting challenging porting issues faced by tensorflowSHARP (e.g. something that can be done easily in python, still not too straightforwards to port to c# using tensorflowSharp. Could pythonNET serve as temporarily solution while more features are being added into tensorflowSharp to make tensorflowSharp more robust in porting the tensorflow python code???_

**Comment by filmor** [comment]
What exactly are you expecting to come out of this issue? The TensorFlowSharp repository is run by Miguel de Icaza who knows heaps more than we do about .NET (being the one who started Mono). He'll probably be aware of the possibility of using Python.NET as an intermediate solution for parts of TensorFlow.

**Comment by denfromufa** [comment]
I would add that pythonnet can be used (and is used!) with tensorflow
without tensorflowsharp and the projects are totally unrelated.

**Comment by JimSEOW** [comment]
Tensorflowsharp can run in mobile devices without phython installation.

**Comment by denfromufa** [comment]
Tensorflow can run on mobile devices even without C# :)

Generally the model is build, trained and serialized into binary on desktop
and then can be deployed on mobile device. So I have no idea why you need
extensive C# API on mobile device.

Pythonnet should be helpful for using Tensorflow and Keras API not exposed
in tensorflowsharp.

**Comment by JimSEOW** [comment]
@denfromufa I follow regularly the different challenges and need to bring more intuitive .NET binding for python in this forum.  The same challenges are faced also in tensorflowSharp. I created the issue here TO RECOGNIZE the hard and excellent work done here. Lots of good experience in overcoming the challenges posed by porting/binding python, building on years of experience from e.g. ironpython etc. 

Thanks for your feedback, now I know what else and how much I do not know :-)

**Comment by JimSEOW** [comment]
@denfromufa  It seems there are more users pushing[ .NET Deep learning as first class citizen](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050) through CNTK

The pythonnet community will play an increasing role as we port more python deep learning codes to .NET
