### ISSUE TITLE
Invalid method binding with specified .NET parameters

### ISSUE THREAD

**Issue by Konstantin-Posudevskiy** [pythonnet/pythonnet#486]
### Environment

-   Pythonnet version: 2.3.0.0
-   Python version: 3.5.3
-   Operating System: Windows 10.

### Details

-   Call to .NET method fails with passed arguments (Double.NegativeInfinity, Double.PositiveInfinity, Single.NegativeInfinity, Single.PositiveInfinity).
There is an example, how you can reproduce this bug.

C# code

```csharp
namespace Bugs
{
    public class InvalidMethodBinding
    {
        public static void WriteDouble(System.Double value)
        {
            System.Console.WriteLine(value);
        }
    }
}
```
Python code:

```python
import clr

clr.AddReference('PathToDll')

from System import Double
from Bugs import *

InvalidMethodBinding.WriteDouble(0.01)
InvalidMethodBinding.WriteDouble(Double.NegativeInfinity)
```

-   Traceback:

```python
Traceback (most recent call last):
0.01
  File "X", line Y, in <module>
    Program.WriteDouble(Double.NegativeInfinity)
TypeError: No method matches given arguments
```

**Comment by denfromufa** [comment]
related: https://github.com/pythonnet/pythonnet/issues/100
