### ISSUE TITLE
“TypeError: Cannot get managed object” due to getting wrong type info from .NET structs

### ISSUE THREAD

**Issue by DfM7** [pythonnet/pythonnet#488]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: Python 3.6.1 64-bit
-   Operating System: Windows 10 1703 64-bit

### Details

pythonnet fails to get the right type from the struct.

C# code:

```csharp
namespace PyNetFails
{
    public struct A
    {
        public int X;
        public int Y;
        public uint V;
    }
}
```

Then compile it as class library named `PyNetFails` and run the following Python code:

```python
import clr
clr.AddReference('PyNetFails.dll')
from PyNetFails import A
a = A()
print(type(a.V))
```

It produces: `<class 'int'>`, although the type should be `System.UInt32`.
Then try to run afterwards the following code:

```python
from System import UInt32
v = UInt32(42)
print(v >= a.V)
```

-   Traceback:

```python
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    print(v >= a.V)
TypeError: Cannot get managed object
```

**Comment by Konstantin-Posudevskiy** [comment]
@DfM7 
## Firstly, 
Lets discuss the next snippet:

``` python
from PyNetFails import A
a = A()
print(type(a.V))
```

It really produces `<class 'int'>`, as **it must be.** But not the `System.UInt32`.
As said from pythonnet `documentation:

> Type conversion under Python for .NET is fairly straightforward - most elemental Python types (string, int, long, etc.) convert automatically to compatible managed equivalents (String, Int32, etc.) and vice-versa.

You can read more information on [official pythonnet documentatition](https://pythonnet.github.io/). Take a look at paragraph **Type conversion**.

## Secondly,
Lets take into account the first notice (result of `a.V` is converted from `System.UInt32` directly to the Python type  `<class 'int'>`) and take a look at the next Python code:

``` python
from System import UInt32
v = UInt32(42)
print(v >= a.V)
```

In the 3-rd line `print(v >= a.V)`, as result of `a.V` is converted to the Python type, we are trying to compare CLR object `v` of type `System.UInt32` with the Python object, which returned in a result of `a.V`. As a result of this comparision, we receive `TypeError: Cannot get managed object`.

So, this action fails, as pythonnet cannot compare Python objects with CLR and vice versa.
In this case, you can fix it, for example, by comparing CLR objects (requires add explicit cast to CLR object):

``` python
from System import UInt32
v = UInt32(42)
print(v >= UInt32(a.V))
```

or fix problem, by comparing Python objects:

``` python
v = 42
print(v >= a.V)
```

**Comment by Konstantin-Posudevskiy** [comment]
@denfromufa I am convinced it is not a bug. It is a documented behaviour.

**Comment by denfromufa** [comment]
@Konstantin-Posudevskiy yes, that's what I originally suggested to @DfM7. But I'm thinking that this is annoyance and unexpected behavior.

https://stackoverflow.com/questions/44491159

**Comment by filmor** [comment]
IMHO, the first step doesn't qualify as a bug, like @Konstantin-Posudevskiy said, it's documented (and sensible) behaviour. Regarding the comparison, I think we could add special cases for the conversion operators that detect mapped Python types and convert them back to their .NET counterpart.

**Comment by Konstantin-Posudevskiy** [comment]
Seems to be related with #94

**Comment by DfM7** [comment]
@Konstantin-Posudevskiy 
Thank you for your clarification.

I had read all of the paragraphs in the official documentation before I've posted the question on SO.
I've just interpreted the "Type Conversion" paragraph in another way, as I got that, for example, `System.Int32` and and `int` are logically equivalent, but not `System.UInt32` and `int`.

**Comment by denfromufa** [comment]
originally reported here: https://stackoverflow.com/questions/44491159

**Comment by lostmsu** [comment]
As discussed above, this is not a bug.
