### ISSUE TITLE
Setting of nested struct doesn't change value

### ISSUE THREAD

**Issue by limdaepl** [pythonnet/pythonnet#491]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.5.2
-   Operating System: Win7

### Details

C#:
```C#
namespace Library
{
    public class Outer
    {
        public Struct Field;
    }

    public struct Struct
    {
        public int Field;
    }
}
```

Python:
```python
import clr
from Library import Outer, Struct

outer = Outer()
outer.Field = Struct()

outer.Field.Field = 42

print(outer.Field.Field)
```

Expected Output:
```
42
```

Actual Output:
```
0
```

The equivalent code in C# has the expected output:
```C#
var outer = new Outer
{
    Field = new Struct()
};

outer.Field.Field = 42;

Console.WriteLine(outer.Field.Field); // 42
````

**Comment by denfromufa** [comment]
This is documented behavior of boxing and unboxing:

http://pythonnet.github.io

Use intermediate variables, don't use "nested" assignment.

**Comment by denfromufa** [comment]
closing due to documented behavior and no updates. thank you for trying pythonnet!
