### ISSUE TITLE
Entering the slack chat

### ISSUE THREAD

**Issue by scj643** [pythonnet/pythonnet#498]
How can one get into the slack chat?

**Comment by denfromufa** [comment]
Hi! Currently the slack chat is intended for developers of pythonnet and is only by invitation. Do you have any plans for contributing? If yes, please send me your email address to my nickname at gmail got com.

Otherwise please use SO, mailing list, and GitHub issues.

**Comment by denfromufa** [comment]
public gitter channel added https://gitter.im/pythonnet/pythonnet
