### ISSUE TITLE
Memory leak when PythonEngine.Initialize/Shutdown is called in a loop

### ISSUE THREAD

**Issue by RomzMcGriess** [pythonnet/pythonnet#499]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6.0
-   Operating System: Win7 x64

### Details

Hello all together,
i started to use pythonnet for my application. I discovered a memory leak. I reduced my code to this to identify the leak. It appears that Python.Shutdown() does not clear all references and memory. Here is a picture of my memory diagnostics. Do i miss something? Maybe someone of you has some info.

[Memory diagnostics picture](https://picload.org/image/riwidglr/memory.png)

Here is my c# code:

        static void Main(string[] args)
        {
            for (int i = 0; i < 10000; i++)
            {
                Console.WriteLine($"Cycle: {i}");

                Console.WriteLine($"Status: {PythonEngine.IsInitialized}");

                if (!PythonEngine.IsInitialized)
                {
                    Console.WriteLine("Initialize");
                    PythonEngine.Initialize();
                }

                Console.WriteLine($"Status: {PythonEngine.IsInitialized}");

                if (PythonEngine.IsInitialized)
                {
                    Console.WriteLine("Shutdown");
                    PythonEngine.Shutdown();
                }

                Console.WriteLine($"Status: {PythonEngine.IsInitialized}");
            }

            Console.ReadLine();
        }

**Comment by filmor** [comment]
Can you check this against `master`?

**Comment by dmitriyse** [comment]
Flat Py_Initialize/ Py_Finalize call cylce will produce memory leak, it's directly described in the Python C Api documentation.
For example each run of all Python.EmbeddingTest, eats 5mb of memory. It's more python itself. Nothing to do with this.

If you have larger memory leak, please try this branch https://github.com/pythonnet/pythonnet/pull/532
This PR reduces memory leaks of a working Python.Engine.
