### ISSUE TITLE
Release 2.4.0

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#509]
I think it's time for a new release, are there any particular bugs that we have to look into before?

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.4.0

**Comment by denfromufa** [comment]
I think we can move other issues to next version, but this one needs to be cleared out before releasing next version:

https://github.com/pythonnet/pythonnet/issues?q=is%3Aopen+is%3Aissue+label%3Arelease-blocking

**Comment by filmor** [comment]
I currently don't have the time to work on integrating the big PRs #538 and #692 (or #532), so after fixing issue #802 I'd like to release a first release candidate for 2.4.0. After this one is out, we have to make a decision on whether to include the PRs.

**Comment by filmor** [comment]
Release 2.4.0rc2 has been published to Pypi now, if there are no major complaints in the next week, this will become 2.4.0.

**Comment by inna-w** [comment]
Please publish a NuGet package for 2.4.0 as well. Will be greatly appreciated.

**Comment by filmor** [comment]
It's quite cumbersome right now, as we have different DLLs per platform/python version/kind of .NET, so I don't know whether I'll have time to do this. Certainly not before the tagging and release of the "final" 2.4.0.

**Comment by filmor** [comment]
Released to Pypi, I'll look into Nuget packages now.

**Comment by inna-w** [comment]
I have submitted a pull request for automatic NuGet package generation in Appveyor builds: [#875](https://github.com/pythonnet/pythonnet/pull/875) . 
But I still prefer to get pythonnet 2.4.0 NuGet from official channel.
