### ISSUE TITLE
can not make calls to Python on a separate thread 

### ISSUE THREAD

**Issue by keowang** [pythonnet/pythonnet#511]
The following (copies from Example) worked fine
    using (Py.GIL())
    {
          dynamic test = Py.Import("programs.test_program");
          Console.WriteLine(test.func(args));
    }

However, the below ends up hanging forever even though it's the same one line program as above. Without the ability to run on a separate thread how can I kill an execution if it takes too long. We deal with massive amount of python scripts at runtime it's gonna be a pain to modify them to terminated the costly computation.

    using (Py.GIL())
    {
          dynamic test = Py.Import("programs.test_program");

          Thread t = new Thread(delegate () {
                  Console.WriteLine(test.func(args));
        });
    }

**Comment by denfromufa** [comment]
what happens if thread is launched outside of Py.GIL() block?

**Comment by keowang** [comment]
This is what happens:

An unhandled exception of type 'System.AccessViolationException' occurred in Python.Runtime.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by keowang** [comment]
Try to do something inside the python script by following https://stackoverflow.com/questions/492519/timeout-on-a-function-call. It's running fine in python but once again pythonnet hangs forever. I wonder what is the solution.

    import sys
    import threading
    import _thread as thread 

    def quit_function(fn_name):
        print('{0} took too long'.format(fn_name), file=sys.stderr)
        sys.stderr.flush()
        thread.interrupt_main() # raises KeyboardInterrupt

    def exit_after(s):
        def outer(fn):
            def inner(*args, **kwargs):
                timer = threading.Timer(s, quit_function, args=[fn.__name__])
                timer.start()
                try:
                    result = fn(*args, **kwargs)
                finally:
                    timer.cancel()
                return result
            return inner
        return outer

    @exit_after(.00001)
    def testWrapper():
        while True : 
            i = 0

**Comment by keowang** [comment]
Hi can I get an update, It's a blocker on our end. I would appreciate if you can advice. Thanks a lot!

**Comment by denfromufa** [comment]
The reason why interrupt does not work in pythonnet is due to this issue and corresponding WIP pull request:

https://github.com/pythonnet/pythonnet/issues/449
https://github.com/pythonnet/pythonnet/pull/450

**Comment by denfromufa** [comment]
The code in pull request is actually OK, but the tests for it are not good.

**Comment by keowang** [comment]
so what's the fix?

**Comment by denfromufa** [comment]
The fix is in the pull request, just look at the diff:

https://github.com/pythonnet/pythonnet/pull/450/files

In short pythonnet should call Py_InitializeEx() instead of  Py_Initialize().

**Comment by keowang** [comment]
Thanks for the pointers. Does this mean I have to get the source (after the fix) and then build it myself is there a binary I can just directly embed in my .Net application.

**Comment by keowang** [comment]
Or if this is easier. Would you mind advising me how to create a infinity loop detection when I am calling python code.

**Comment by denfromufa** [comment]
@keowang I tried with master branch and I don't any issue:

```
scriptcs (ctrl-c to exit or :help for help)

> #r "C:\Python\Python35_64b\Lib\site-packages\Python.Runtime.dll"
> using Python.Runtime;
> dynamic intr;
> dynamic sys;
> using (Py.GIL()) {sys=Py.Import("sys");}
> sys.path.ToString()
['C:\\Python\\Python35_64b\\python35.zip', 'C:\\Python\\Python35_64b\\Lib', 'C:\\Python\\Python35_64b\\DLLs', 'C:\\ProgramData\\chocolatey\\lib\\ScriptCs\\tools', 'C:\\Python\\Python35_64b', 'C:\\Python\\Python35_64b\\lib\\site-packages', 'C:\\Python\\Python35_64b\\lib\\site-packages\\win32', 'C:\\Python\\Python35_64b\\lib\\site-packages\\win32\\lib', 'C:\\Python\\Python35_64b\\lib\\site-packages\\Pythonwin', 'C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\']
> sys.path.append(@"C:\Users\denis\Dropbox\coding\pythonnet\issue511");
> using (Py.GIL()) {intr=Py.Import("interrupt_main");}
> intr.testWrapper()
start inf loop
testWrapper took too long
KeyboardInterrupt :
```

**Comment by denfromufa** [comment]
@rmadsen-ks do you see any issue?

**Comment by keowang** [comment]
This is my code running the python script above and it hangs every time.           
            using (Py.GIL())
            {
                  dynamic testModule = Py.Import("programs.test_program");
                  output = testModule.testWrapper();
            }

Pythonnet installed using following wheel:
pythonnet-2.3.0-cp36-cp36m-win_amd64.whl

Python:3.6 64-bit

Would you please let me know if you can run this code

**Comment by denfromufa** [comment]
@keowang ok, i did some testing with pythonnet 2.3.0, but I still don't see your exact issue here. Show me the problem again. Here is my testing:

```csharp
//#r "C:\Python\Python35_64b\Lib\site-packages\Python.Runtime.dll"
using Python.Runtime;
using System;

namespace interrupt
{
    class Program
    {
        static void Main(string[] args)
        {
            dynamic intr;
            dynamic sys;
            PythonEngine.Initialize(true); //, true); second argument if for @rmadsen-ks branch
            using (Py.GIL()) {sys=Py.Import("sys");}
            sys.path.append(System.AppDomain.CurrentDomain.BaseDirectory);
            using (Py.GIL()) 
            {
                intr=Py.Import("interrupt_main");
            }
            using (Py.GIL()) 
            {
                try 
                {
                	intr.testWrapper();
            	}
            	catch {
            		Console.WriteLine("some exception here");
            	}
            }
        }
    }
}
```

```python
import sys
import threading
import _thread as thread 

def quit_function(fn_name):
    print('{0} took too long'.format(fn_name), file=sys.stderr)
    sys.stderr.flush()
    thread.interrupt_main() # raises KeyboardInterrupt

def exit_after(s):
    def outer(fn):
        def inner(*args, **kwargs):
            timer = threading.Timer(s, quit_function, args=[fn.__name__])
            timer.start()
            try:
                result = fn(*args, **kwargs)
            finally:
                timer.cancel()
            return result
        return inner
    return outer

@exit_after(0.1)
def testWrapper():
    print('start inf loop')
    while True : 
        i = 0

if __name__=="__main__":
    print('before threads launched')
    try:
        testWrapper()
    except KeyboardInterrupt:
        print("forced to interrupt")

```

Then if I call from python:

```
python interrupt_main.py
before threads launched
start inf loop
testWrapper took too long
forced to interrupt
```

If I call from C# compiled app:

```
interrupt.exe
start inf loop
testWrapper took too long
some exception here
```

**Comment by keowang** [comment]
@denfromufa I appreciate your response. The issues is you are running the binary and surprisingly it worked. However, in Visual Studio debug mode `intr.testWrapper()` will hang every time. There is no way we can get around this by skipping the debug mode and directly monitoring the program behavior via logs which is hugely inconvenient. Would you mind looking into that see if there is some solution that we can have the consistent behavior in both debug and release mode. Thanks

**Comment by denfromufa** [comment]
By debug mode do you mean debug build of the binary and pythonnet or
debugging (stepping) through this code in VS?

**Comment by keowang** [comment]
stepping through the code in VS

**Comment by denfromufa** [comment]
Do you debug with attach mode or start the debugger with F5? Is the debugger engine only "Managed"?

**Comment by denfromufa** [comment]
Also what Exception Settings in VS have you enabled for debugging session?

**Comment by keowang** [comment]
I hit F5 and it's a managed only. The exception setting is by default you want to list them all? I am not sure how to answer your question

**Comment by keowang** [comment]
@denfromufa  Hello, can I get an update?

**Comment by denfromufa** [comment]
can you show your exceptions settings:

https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger

**Comment by denfromufa** [comment]
i can debug in vs 2017 with no problems:

![image](https://user-images.githubusercontent.com/7870949/28348674-db7fd77e-6c03-11e7-98a9-08f897b45af8.png)

**Comment by keowang** [comment]
![c](https://user-images.githubusercontent.com/27976559/28348698-339c19a6-6bf3-11e7-9906-6871525c6de9.png)
![clr](https://user-images.githubusercontent.com/27976559/28348699-339c40c0-6bf3-11e7-868d-60cc6b0e9783.png)
![javascript](https://user-images.githubusercontent.com/27976559/28348701-339cb096-6bf3-11e7-8eb5-92f60f2265e7.png)
![mda](https://user-images.githubusercontent.com/27976559/28348702-339cfede-6bf3-11e7-92e4-f763aa5161fb.png)
![win32](https://user-images.githubusercontent.com/27976559/28348700-339c8da0-6bf3-11e7-83ca-4ce061c0777a.png)

**Comment by keowang** [comment]
That's all

**Comment by keowang** [comment]
![scre](https://user-images.githubusercontent.com/27976559/28348748-799573bc-6bf3-11e7-95eb-80058a4d4e4f.png)

**Comment by keowang** [comment]
This is how it hangs

**Comment by keowang** [comment]
Can I please ask what's your exception setting? Thanks!

**Comment by denfromufa** [comment]
you can see my exception settings in my screenshot

**Comment by keowang** [comment]
yes I tried and it's the same thing

**Comment by denfromufa** [comment]
did you try break all: ctrl+alt+break

**Comment by keowang** [comment]
press the key manually?

**Comment by denfromufa** [comment]
no, break in the debugger

**Comment by keowang** [comment]
how do I do that?

**Comment by denfromufa** [comment]
debug -> break all

**Comment by keowang** [comment]
![break](https://user-images.githubusercontent.com/27976559/28349229-579971b6-6bf6-11e7-90f6-d71a329eb2ff.png)

**Comment by keowang** [comment]
I do not see it here

**Comment by keowang** [comment]
Hey I fixed it by enabling the native code which makes the debugging very slow. Can I do it without the native code?

**Comment by denfromufa** [comment]
"break all" has to be triggered during debugging. i do not have native code debugger enabled. please contact vs team as msft about debugger issues.
