### ISSUE TITLE
Importing nested namespaces from proprietary dll throws error

### ISSUE THREAD

**Issue by Kamforka** [pythonnet/pythonnet#516]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6.0 (64bit)
-   Operating System: Win10

### Details

I added a dll using pythonnet to my Python script like this:

```python
import os
import clr
clr.AddReference(os.path.join(os.path.abspath('.'), 'dlls', 'Supplier.Bundle.dll'))
import Supplier.Bundle
```
It works just fine, I can call methods or instantiate classes right from the `Supplier.Bundle` namespace, but when I want to call a method from a nested namespace like `Supplier.Bundle.Features` I got the error:

```python
AttributeError: Features
```
I also tried the following:

```python
import Supplier.Bundle.Features
```
Which throws:

```python
ModuleNotFoundError: No module named 'Supplier.Bundle.Features'; 'Supplier.Bundle' is not a package
```
While importing only the namespace from the package:
```python
from Supplier.Bundle import Features
```
Throws:
```python
ImportError: cannot import name 'Features'
```

However, using the same dll in C# while accessing the same nested namespace works just fine:

```c#
using Supplier.Bundle.Features
```

So my question is: how to access classes and methods of nested namespaces of a C# dll within Python3.x using pythonnet?

**Comment by denfromufa** [comment]
I see your question on SO:

https://stackoverflow.com/q/45277129/2230844

This works for me totally fine, so minimal reproducible example is necessary @Kamforka 

Also `.dll` is not needed at the end of assembly reference.

**Comment by Kamforka** [comment]
What do you mean by a minimal reproducible example?
Do you need the proprietary dll? (I'm not sure whether I can distribute it or not though.)

By the way if a trim off the .dll extension when I want to add it as reference I get the following:

```python
System.IO.FileNotFoundException: Unable to find assembly 'path\to\dll\Supplier.Bundle'.
   at Python.Runtime.CLRModule.AddReference(String name)
```

**Comment by denfromufa** [comment]
I usually append the directory of the dll that I want to reference to
sys.path and then I can just do clr.AddReference(assembly_name). But your
method of loading assemblies also looks valid.

For reproducible example what I meant is that you can just extract the
skeleton of the existing namespaces without actually putting the custom
logic in those classes and methods and that way we can test it out.

ILSPY is your friend for this.

**Comment by Kamforka** [comment]
Then I'm going to give a shot to ILSpy.
Actually I should create an empty skeleton from the dll and then try importing it the same way as before?
Can you give me more instructions, or if it's an option for you I can send you the dlls by mail, so you can also take a look at the issue.

**Comment by denfromufa** [comment]
yes, try importing the empty skeletons of your classes/methods/namespaces. my email is my github nickname at gmail dot com if you can send the original assembly.

**Comment by Kamforka** [comment]
Okay I sent you the dlls. And again thank you very much for your help!

**Comment by Kamforka** [comment]
Issue is solved, as the dll needed other dependencies, after they were copied to the project directory the import was working without any problems!

**Comment by filmor** [comment]
Yeah, I've seen this before. It's exactly what #261 is about.

**Comment by denfromufa** [comment]
@filmor the problem here is even more severe, than just silently failing on import. From C# the Namespace1.Namespace2.Namespace3 can be  imported without referencing those additional assemblies (checked in scriptcs), but not from pythonnet. pythonnet requires all references even if they are not used during import. some more testing and debugging is necessary here.

**Comment by Kamforka** [comment]
@denfromufa it's true. Additionally some meaningful error messages would be also useful in such cases.
