### ISSUE TITLE
Calling generic method in Python returns incorrect value

### ISSUE THREAD

**Issue by Kamforka** [pythonnet/pythonnet#517]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6.0
-   Operating System: Win10

### Details

I'm trying to call a generic method from Python. So far it seems it's executing but the result is not the same when calling it from C#.

So the actual method looks like:
```c#
public T GetService<T>() where T : class, IEngineeringService;
```

The method call in C# is:
```c#
SoftwareContainer softwareContainer = deviceItem.GetService<SoftwareContainer>();
```
And as expected it returns an object of type `SoftwareContainer`.

Calling it from python like:
```python
software_container = device_item.GetService[SoftwareContainer]()
```
While it seems like the method is called as expected the returned value is `None`.

>Note: I have an engineering project and I'm accessing it via a C# API. Both snippets act on the same project, so I guess the results should be the same for both cases.

Why does the Python code return an incorrect value?

**Comment by filmor** [comment]
And you are sure that this doesn't return a `(SoftwareContainer)null`?

**Comment by denfromufa** [comment]
also can you show the results of `deviceItem.GetService.Overloads`?

**Comment by Kamforka** [comment]
@filmor when printing the returned value as `Console.WriteLine(softwareContainer);` I get `Engineering.HW.Features.SoftwareContainer` which is valid, and I also have an if statement which checks the content of the `softwareContainer` like `if (softwareContainer != null)...` and the instructions within the if branch are being executed.

**Comment by Kamforka** [comment]
@denfromufa well, in .NET I cannot access `deviceItem.GetService.Overloads` as I get the following error message: `'deviceItem.GetService<T>()' is a method which is not valid in the given context`.

At the same time in Python `device_item.GetService.Overloads` gives `T GetService[T]()`.

**Comment by denfromufa** [comment]
@Kamforka I have all of your dlls, but your example is not reproducible, because you did not show how device_item was constructed. Please provide complete reproducible example.

```
In [9]: device_item = DeviceItem()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-2a9297e4359b> in <module>()
----> 1 device_item = DeviceItem()

TypeError: cannot instantiate abstract class
```

**Comment by Kamforka** [comment]
@denfromufa I guess you don't have TIA Portal v14 SP1 from Siemens, do you?

If you need a complete reproducible example I gather the files for you and send it via email, because it will be an exhaustive collection.
Other than that you still need a TIA Portal copy to make it work as the API is used to communicate with the engineering portal.

**Comment by Kamforka** [comment]
Did you manage to take a look at this issue?

**Comment by denfromufa** [comment]
@Kamforka there is too much setup for your example, can you isolate the problem?

**Comment by Kamforka** [comment]
@denfromufa unfortunately the setup is necessary to reproduce the problem. 
But with the provided dlls you can peak into and take a look at the `GetService` implementation.
Also I can show you what's going on via remote desktop if it's feasible from your side, I guess that's the best option.

**Comment by denfromufa** [comment]
In that case please install latest ptvsd from PYPI and follow the instructions for remote debugging in this tutorial, then send me the keys to my email for remote attach:

https://github.com/pythonnet/pythonnet/wiki/Various-debugging-scenarios-of-embedded-CPython

**Comment by Kamforka** [comment]
@denfromufa I installed `ptvsd` and also imported it, then called its `enable_attach` method with a secret key. I have my python application running in a virtual machine and also my computer is behind a proxy. So what else is needed to be able to establish remote connection with you?

**Comment by denfromufa** [comment]
@Kamforka you need very long timeout like 1-2 days, and also test it out from another machine yourself. I'm not sure if proxy matters, check with PTVS team if it does not work.

**Comment by Kamforka** [comment]
@denfromufa what do you mean by timeout? Is it related to `ptvsd` or only a `time.sleep` at the beginning of the script to spare some time until you attach to the process?

**Comment by denfromufa** [comment]
@Kamforka sorry about timeout, I confused that with C# remote debugger. There is no timeout in ptvsd by default. It should wait indefinitely for attach event.

**Comment by NOP0** [comment]
Struggling with the same problem. How do I input a SoftwareContainer to GetService? My IDE doesn't seem to recognize the type, does it need to be imported?

**Comment by denfromufa** [comment]
@NOP0  IDEs do not support pythonnet intellisense

**Comment by denfromufa** [comment]
closed due to inactivity @Kamforka
