### ISSUE TITLE
PInvokeStackImbalance when set PythonEngine.PythonHome = @"C:/Users/Peter/AppData/Local/Programs/Python/Python36-32"

### ISSUE THREAD

**Issue by peter----** [pythonnet/pythonnet#536]
### Environment

-   Pythonnet version: pythonnet-2.3.0-cp36-cp36m-win32
-   Python version: Python36-32
-   Operating System: WIN7

### Details

-   Describe what you were trying to get done.
    When set PythonEngine.PythonHome = @"C:/Users/Peter/AppData/Local/Programs/Python/Python36-32"

     it complains PInvokeStackImbalance.

     I already copy the Python.RunTime.dll and clr.pyd into Python36-32\Lib\site-packages.
    I alreasy set the PATH has C:/Users/Peter/AppData/Local/Programs/Python/Python36-32
    and C:\Users\Peter\AppData\Local\Programs\Python\Python36-32\Lib\site-packages.

    Any ideas?

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by denfromufa** [comment]
@peter----  see this issue for resolution: https://github.com/pythonnet/pythonnet/issues/485

**Comment by peter----** [comment]
I tried to follow the #485. 
However I still have the issue.
    I already copy the Python.RunTime.dll and clr.pyd into Python36-32\Lib\site-packages.
    I already set the PATH has C:/Users/Peter/AppData/Local/Programs/Python/Python36-32
        and C:\Users\Peter\AppData\Local\Programs\Python\Python36-32\Lib\site-packages.
    I already set reference to Python.RunTime.dll from Python.RunTime.dll.

Anything missed?
Thanks!

**Comment by denfromufa** [comment]
Uninstall your current version of pythonnet and install latest version from
master:

´pip install git+https://github.com/pythonnet/pythonnet´

Then reference this Python.Runtime.DLL in your project.
