### ISSUE TITLE
memory leak - simple function call in a loop

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#541]
I'm getting a memory leak with simple calls from .NET to Python function. The issue is reproducible on all pythonnet versions that I tested. When I test Python calls to .NET, then the memory leak is less obvious, since all resources are released when calling the CPython `gc.collect()`. Calling the same function from .NET does not release any resources, but calling the CLR `GC.WaitForPendingFinalizers()` blocks the execution.

[memoryleakpykw.zip](https://github.com/pythonnet/pythonnet/files/1293771/memoryleakpykw.zip)

```python
>>> import clr
>>> import System
>>> for i in range(20000000):
...   a=System.Double(i)
...
>>> import gc
>>> gc.collect()
```

`pyinclr.py`
```python
def testmethod():
	return "abc"*3
```

```csharp
using System;
using Python.Runtime;

namespace memoryleakpykw
{
    class Program
    {
        static void Main(string[] args)
        {
            PyObject pymodule;
            PyObject gc;
            PyObject testmethod;

            PythonEngine.Initialize();

            IntPtr pylock = PythonEngine.AcquireLock();
            {
                PyObject sys = PythonEngine.ImportModule("sys");// Py.Import("sys");
                gc = PythonEngine.ImportModule("gc");// Py.Import("sys");
                sys.GetAttr("path").InvokeMethod("append",
                    new PyString(@"C:\Users\denis.akhiyarov\source\repos\memoryleakpykw\pyinclr"));
                pymodule = PythonEngine.ImportModule("pyinclr");
                testmethod = pymodule.GetAttr("testmethod");
            }

            PythonEngine.ReleaseLock(pylock);

            Console.WriteLine("starting test for memory leak, press any key");
            Console.ReadKey();

            pylock = PythonEngine.AcquireLock();

            {
                for (int i=1; i<=1000000; i++)
                {
                    testmethod.Invoke();
                }
            }

            gc.InvokeMethod("collect"); 

            PythonEngine.ReleaseLock(pylock);
            
            GC.Collect();
            //GC.WaitForPendingFinalizers(); // this blocks execution
            GC.Collect();

            Console.WriteLine("finished test for memory leak, press any key");
            Console.ReadKey();
        }

    }
}
```

**Comment by denfromufa** [comment]
Actually `GC.WaitForPendingFinalizers();` is blocking, not `gc.collect`!

**Comment by dmitriyse** [comment]
Please try this version of your code:
```CSharp
using System;
using Python.Runtime;

namespace memoryleakpykw
{
    class Program
    {
        static void Main(string[] args)
        {
            PyObject pymodule;
            PyObject gc;
            PyObject testmethod;

            PythonEngine.Initialize();
            var ts = PythonEngine.BeginAllowThread();

            IntPtr pylock = PythonEngine.AcquireLock();
            {
                PyObject sys = PythonEngine.ImportModule("sys");// Py.Import("sys");
                gc = PythonEngine.ImportModule("gc");// Py.Import("sys");
                sys.GetAttr("path").InvokeMethod("append",
                    new PyString(@"C:\Users\denis.akhiyarov\source\repos\memoryleakpykw\pyinclr"));
                pymodule = PythonEngine.ImportModule("pyinclr");
                testmethod = pymodule.GetAttr("testmethod");
            }

            PythonEngine.ReleaseLock(pylock);

            Console.WriteLine("starting test for memory leak, press any key");
            Console.ReadKey();

            pylock = PythonEngine.AcquireLock();

            {
                for (int i=1; i<=1000000; i++)
                {
                    testmethod.Invoke();
                }
            }

            gc.InvokeMethod("collect"); 

            PythonEngine.ReleaseLock(pylock);
            
            PythonEngine.EndAllowThread(ts);

            GC.Collect();
            GC.WaitForPendingFinalizers(); // this blocks execution
            GC.Collect();

            Console.WriteLine("finished test for memory leak, press any key");
            Console.ReadKey();
        }

    }
}
```

**Comment by denfromufa** [comment]
@dmitriyse I'm not sure how is that supposed to help with the memory leak, but the leak is still there and not released from both GC. `WaitForPendingFinalizers` still blocks.

**Comment by denfromufa** [comment]
I got rid of this memory leak by using the following inconvenient disposal code:

```
PyObject res = testmethod.Invoke();
res.Dispose();
```

Not sure why `res` cannot be disposed by either GC?!

**Comment by denfromufa** [comment]
I still don't understand why managed GC from CLR is not calling the finalizer of `PyObject` for the results of calls into pythonnet:

```csharp
        ~PyObject()
        {
            Dispose();
        }
```

What is holding the reference to these objects or why GC is not activated? 

Thanks for the edit @dmitriyse, now when `EndAllowThreads` is after `WaitForPendingFinalizers`, then some of resources are released, but not all:

```
            PythonEngine.ReleaseLock(pylock);

            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();

            PythonEngine.EndAllowThreads(ts);
```

![image](https://user-images.githubusercontent.com/7870949/30333280-6aee5e90-9791-11e7-91a4-4c3d2b8d69c2.png)


I read these Q&A and nothing looks wrong in PyObject:

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern

https://stackoverflow.com/questions/3038571/whats-the-purpose-of-gc-suppressfinalizethis-in-dispose-method

https://stackoverflow.com/questions/45036/will-the-garbage-collector-call-idisposable-dispose-for-me

https://stackoverflow.com/questions/3038571/whats-the-purpose-of-gc-suppressfinalizethis-in-dispose-method

https://stackoverflow.com/questions/538060/proper-use-of-the-idisposable-interface

https://stackoverflow.com/questions/898828/finalize-dispose-pattern-in-c-sharp

**Comment by dmitriyse** [comment]
I tested this code in the branch https://github.com/pythonnet/pythonnet/pull/532.
And no any memory leaks occurred. 
![image](https://user-images.githubusercontent.com/10322215/30335769-4454584e-97f4-11e7-82c3-0128fc414771.png)

When I debugged this branch I faced with unpredictable C# GC behavior, after some amount of valid "Dispose" calls, GC does not generate enough finalizer calls. Looks like some unmanaged actions are not allowed inside GC thread.

**Comment by denfromufa** [comment]
@dmitriyse I tested your branch for finalizer with .NET Framework 4.6.1 and it looks great!

![image](https://user-images.githubusercontent.com/7870949/30403213-2fc88a5a-98a6-11e7-8891-2a6342666d46.png)

**Comment by denfromufa** [comment]
Interestingly .NET 4.0 garbage collector behaves much nicer:

![image](https://user-images.githubusercontent.com/7870949/30403313-a558ee22-98a6-11e7-9cf5-542099538d93.png)

**Comment by denfromufa** [comment]
Here is the testing for .NET Core 2.0, also looks very solid!

![image](https://user-images.githubusercontent.com/7870949/30443137-2a5081ec-9944-11e7-8a7c-289671928f55.png)

**Comment by denfromufa** [comment]
@dmitriyse here is another leak, even with your valid finalizer. This is when raising exception in Python and catching it in C#:

```csharp
using System;
using System.ComponentModel;
using Python.Runtime;

namespace memoryleakpykw
{
    class Program
    {
        static void Main(string[] args)
        {
            dynamic pymodule;
            PyObject gc;
            dynamic testmethod;
            PythonEngine.Initialize();
            var ts = PythonEngine.BeginAllowThreads();
            IntPtr pylock = PythonEngine.AcquireLock();
            {
                PyObject sys = PythonEngine.ImportModule("sys");// Py.Import("sys");
                gc = PythonEngine.ImportModule("gc");// Py.Import("sys");
                sys.GetAttr("path").InvokeMethod("append",
                    new PyString(@"C:\Users\denis.akhiyarov\source\repos\memoryleakpykw\pyinclr"));
                pymodule = PythonEngine.ImportModule("pyinclr");
                testmethod = pymodule.testmethod; //.GetAttr("testmethod");
            }
            PythonEngine.ReleaseLock(pylock);
            Console.WriteLine("starting test for memory leak, press any key");
            Console.ReadKey();
            double floatarg1 = 5.1f;
            dynamic res = null;
            {
                for (int i = 1; i <= 1000000; i++)
                {
                    using (Py.GIL())
                    {
                        try { 
                            res = testmethod(Py.kw("number", floatarg1), Py.kw("astring", "bbc"));
                        }
                        catch (Exception e)
                        {
                            if (i % 1000 == 0)
                            {
                                Console.WriteLine(e.Message);
                            }
                        }
                    }
                }
            }
            Console.WriteLine(res);           
            PythonEngine.EndAllowThreads(ts);
            Console.WriteLine("finished test for memory leak, press any key");
            Console.ReadKey();
        }
    }
}


```python
def testmethod(number=3, astring='abc'):
    raise ValueError("testing for memory leak")
    return astring * int(number)
```

**Comment by dmitriyse** [comment]
Memory leak example with an exception is not so good. I tried the same example but without exception raising and it still produces memory leak (iterations count should be increased).

**Comment by dmitriyse** [comment]
I fixed exception related memory fix. See latest update to PR #532

**Comment by dmitriyse** [comment]
We needs to close this issue after PR #532 merge to master
