### ISSUE TITLE
Cannot compile example from tutorial in VS2015 because of named argument

### ISSUE THREAD

**Issue by UNdedss** [pythonnet/pythonnet#543]
### Environment

- Pythonnet 2.3.0:
- Python 3.5:
- Operating System : Windows 7 SP1
- Visual Studio 2015 Update 3 with latest Resharper

### Details

I'm trying to run the first c# example from tutorial, but it looks like my VS2015 doesn't recognize named arguments for for dynamic objects. 
Looks like it is the problem of environment, but its resolution will also be useful for other users.

### Screenshots

code snippet with compile error:

![image](https://user-images.githubusercontent.com/15870831/30469602-b03f0304-99f9-11e7-87b1-81d99983fa78.png)

console output with another issue (possibly related), where dtype of numpy array is printed as "object" instead of "int", printing an array also results in "object":

![image](https://user-images.githubusercontent.com/15870831/30469759-85966cf4-99fa-11e7-8b00-35320ed91e06.png)

**Comment by denfromufa** [comment]
For this syntax to work you need to use pythonnet from the master. Note that we are planning to adopt slightly different syntax for calling into numpy arrays:

https://github.com/pythonnet/pythonnet/issues/514

**Comment by UNdedss** [comment]
I installed managed assembly via nuget as described in "[installation](https://github.com/pythonnet/pythonnet/wiki/Installation)" section of wiki. So what do you mean by "to use pythonnet from the master".

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/wiki/Installation

`pip install git+https://github.com/pythonnet/pythonnet`

**Comment by UNdedss** [comment]
I installed pythonnet with given cmd params. But the problem still exists.  Are you sure that c# cyntax isn't violated with named params for dynamics? Or maybe problem is with VS version or resharper?

![image](https://user-images.githubusercontent.com/15870831/30487562-78f61656-9a3c-11e7-9ade-c52addaad3ac.png)

**Comment by denfromufa** [comment]
@UNdedss that is my bad! The syntax on C# side for keyword arguments is colon sign `:`, not equal sign `=`, unlike Python:

https://github.com/pythonnet/pythonnet/blob/master/src/embed_tests/TestNamedArguments.cs

I fixed this in readme now:

https://github.com/pythonnet/pythonnet/commit/4bac6941d461656dd828a09e3774c9e7e30e0d4c

More details about this feature in this pull request:

https://github.com/pythonnet/pythonnet/pull/461

**Comment by denfromufa** [comment]
This looks fixed, so I'm closing this issue.
