### ISSUE TITLE
Python grandchild of .NET class is not created correctly if "__namespace__" attribute is set

### ISSUE THREAD

**Issue by testrunner123** [pythonnet/pythonnet#544]
### Environment

-   Pythonnet version: 2.3 with #503 applied
-   Python version: 3.4 64-bit
-   Operating System: Ubuntu 14.04

### Details

-   Describe what you were trying to get done.

I am trying to use python child of .NET class in python grandchild.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
Following pure python code 
```python
class A:
  def __init__(self):
      self.foo()
  def foo(self): print('A.foo')

class B(A):
  def foo(self): print('B.foo')

a = A()
b = B()
```
works like expected and prints:
> A.foo
> B.foo

Consider Python classes constructed with pythonnet:
```python
import clr
import System.Windows.Forms as WinForms

class PythonGroupBox(WinForms.GroupBox):
    def __init__(self):
        print("PythonGroupBox.__init__")
        self.MyInit()

    def MyInit(self):
        print("PythonGroupBox MyInit")

class PythonGroupBoxDerived(PythonGroupBox):
    def MyInit(self):
        print("PythonGroupBoxDerived MyInit")

grp1 = PythonGroupBox()
grp2 = PythonGroupBoxDerived()
```
works fine and prints:
> PythonGroupBox.__init__
> PythonGroupBox MyInit
> PPythonGroupBox.__init__
> PythonGroupBoxDerived MyInit

Now the same with "__namespace__":
```python
import clr
import System.Windows.Forms as WinForms

class PythonGroupBox(WinForms.GroupBox):
    __namespace__ = "System.Windows.Forms"
    def __init__(self):
        print("PythonGroupBox.__init__")
        self.MyInit()

    def MyInit(self):
        print("PythonGroupBox MyInit")

class PythonGroupBoxDerived(PythonGroupBox):
    def MyInit(self):
        print("PythonGroupBoxDerived MyInit")

grp1 = PythonGroupBox()
grp2 = PythonGroupBoxDerived()
```
The output is:
> PythonGroupBox.__init__
> PythonGroupBox MyInit
> PythonGroupBox.__init__
> PythonGroupBox MyInit

Error (1), because MyInit Method didn't get overloaded !!!

One more try:
```python
import clr
import System.Windows.Forms as WinForms

class PythonGroupBox(WinForms.GroupBox):
    __namespace__ = "System.Windows.Forms"
    def __init__(self):
        print("PythonGroupBox.__init__")
        self.MyInit()

    def MyInit(self):
        print("PythonGroupBox MyInit")

class PythonGroupBoxDerived(PythonGroupBox):
    __namespace__ = "System.Windows.Forms"
    def MyInit(self):
        print("PythonGroupBoxDerived MyInit")

grp1 = PythonGroupBox()
grp2 = PythonGroupBoxDerived()
```
Output gets really weird:
> PythonGroupBox.__init__
> PythonGroupBox MyInit

Error (2): during construction of PythonGroupBoxDerived the __init__() method was not called at all !!!

Important: this issue has nothing to do with issue #503: if I undo that fix than constructors get called twice, but errors described here persist.

**Comment by testrunner123** [comment]
I have made a unit test for this on a branch. Does some one knows how it is designed to work?

**Comment by lostmsu** [comment]
This works as expected:

```python
import System.Windows.Forms as WinForms

class PythonGroupBox(WinForms.GroupBox):
    __namespace__ = "System.Windows.Forms"
    def __init__(self):
        super().__init__()
        print("PythonGroupBox.__init__")
        self.MyInit()
    def MyInit(self):
        print("PythonGroupBox MyInit")

class PythonGroupBoxDerived(PythonGroupBox):
    __namespace__ = "System.Windows.Forms"
    def __init__(self):
        super().__init__()
    def MyInit(self):
        print("PythonGroupBoxDerived MyInit")

grp1 = PythonGroupBox()
grp2 = PythonGroupBoxDerived()
```

> / grp1 = PythonGroupBox()
> PythonGroupBox.__init__
> PythonGroupBox MyInit
> / grp2 = PythonGroupBoxDerived()
> PythonGroupBox.__init__
> PythonGroupBoxDerived MyInit

However, without explicitly redeclared `__init__` in the `PythonGroupBoxDerived` base constructor is not called, for which I opened a separate issue: https://github.com/pythonnet/pythonnet/issues/1945
