### ISSUE TITLE
import clr causes a core dump inside raspbian jessie docker container

### ISSUE THREAD

**Issue by kwmlodozeniec** [pythonnet/pythonnet#551]
### Environment

-   Pythonnet version: 2.4.0.dev0
-   Python version: 2.7.13
-   Operating System: Raspbian Jessie docker container running on RPi3

### Details

Installed mono using the official repo, installed pythonnet using:

```pip install --egg git+https://github.com/pythonnet/pythonnet```

It all install without obvious issues but when I try to import clr in python it throws a core dump.

Any ideas?  Tried different versions of mono without luck.  Executing the same commands on the host system does not cause any issues and my apps run without problems.

**Comment by denfromufa** [comment]
@kwmlodozeniec related:

https://github.com/pythonnet/pythonnet/issues/327

**Comment by denfromufa** [comment]
@kwmlodozeniec @mdk73 you can talk to mono developers here:

https://gitter.im/mono/mono

**Comment by kwmlodozeniec** [comment]
Resolved by following this:

[https://stackoverflow.com/a/36003017/6355660](url)

**Comment by denfromufa** [comment]
@kwmlodozeniec so you can run pythonnet on RPi with Mono now? did you check if it passes the tests?

**Comment by kwmlodozeniec** [comment]
my mono app seems to be running fine, although I have not run any tests. If it helps I can run some, which specific ones are you interested in?

**Comment by denfromufa** [comment]
so is the docker container a proper linux or it is raspbian inside, where do you pull it from? I'm not interested in any particular test, but I'm going to check my RPi at home. you can run embedding and extending tests, if you look at travis.yml for our CI.

**Comment by kwmlodozeniec** [comment]
the container is a raspbian image from resin.io, the actual repo I use is:

`resin/raspberrypi3-python:2.7.13`

**Comment by kwmlodozeniec** [comment]
I'm back to square one on this issue, but this time after adding bluetooth support to the RPi. Before BT installation I could import clr in python without a core dump and mono apps were working, now mono still works but pythonnet crashes when I import clr.

**Comment by denfromufa** [comment]
@kwmlodozeniec so does this issue resolve if you remove whatever was installed for bluetooth support?

**Comment by kwmlodozeniec** [comment]
Yes, in fact, I resolved it now by going through each package one by one and reducing it down to the bare minimum.
