### ISSUE TITLE
Add cache of MethodWrapper instances and cache to NativeCall for .Net Standard 2.0. Should improve performance.

### ISSUE THREAD

**Issue by dmitriyse** [pythonnet/pythonnet#553]
### Environment

-   Pythonnet version: Any
-   Python version: Any
-   Operating System: Any

### Details

-   Describe what you were trying to get done.

     + new MethodWrapper instanced are created multiple times for the same .Net delegates.
     + also Marshal.GetDelegateForFunctionPointer can be cached to improve performance on .NetStandard 
     2.0
     + with those two caches it's possible to gracefully overcome .net restriction described here 
         https://github.com/dotnet/coreclr/issues/14362

**Comment by lostmsu** [comment]
The referenced .NET restriction should no longer apply.

For the performance issue we need a performance test that shows the problem before we can even consider doing something about it.
