### ISSUE TITLE
TypeError when running ReadMe example 

### ISSUE THREAD

**Issue by fgiaret** [pythonnet/pythonnet#554]
Hi, I'm trying to embed Python in a C# project with Visual Studio (I'm very new both to C# and GitHub) and I started running the numpy example from the Readme file. After the lines:

"dynamic a = np.array(new List<float> { 1, 2, 3 }); 
dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);"

I get the following error:
{"TypeError : int() argument must be a string, a bytes-like object or a number, not '0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'"}.

I have the following settings:
-   Pythonnet version: 2.3.0 for Python 3.6 (64 bit), installed with pip;
-   Python version: 3.6.1 (64 bit) with Anaconda 3;
-   Visual Studio 2015; 
-   Operating System: Windows 7

I've seen issue #249 reporting the same error, but still wasn't able to fix this. It would be great if someone could help me,

Thank you!

**Comment by denfromufa** [comment]
@fgiaert this has not been released yet, so you need to install pythonnet from master. Download the zip of master branch, unpack it, and then run this commands:

`python setup.py bdist_wheel --xplat`
`pip install dist\pythonnet-2.4.0.dev0-cp36-cp36m-win64.whl`

This is simpler with pip+git, but someone broke this recently: #555

**Comment by denfromufa** [comment]
just checked and the master branch works great, but the `dtype` cannot be extracted:

```
> #r C:\\Python\\Python35_64b\\lib\\site-packages\\Python.Runtime.DLL
> using Python.Runtime;
> dynamic np; using (Py.GIL()) { np = Py.Import("numpy");};
> using System.Collections.Generic;
> using System.Collections;
> dynamic a = np.array(new List<float> { 1, 2, 3 });
> dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
> Console.WriteLine(a.dtype);
Cannot implicitly convert type 'void' to 'object'
> a.ToString()
[ 1.  2.  3.]
> b.ToString()
[6 5 4]
```

**Comment by fgiaret** [comment]
It works, great! Thank you!

**Comment by denfromufa** [comment]
@fgiaret I see you edited your response with additional question. In future please try to add this as another comment, because no one will get this update in email due to github limitations.

Regarding your question - this is possible, have a look at this directory with tests:

https://github.com/pythonnet/pythonnet/blob/master/src/embed_tests/TestPyScope.cs

**Comment by fgiaret** [comment]
Ok, thank you very much!

**Comment by denfromufa** [comment]
@fgiaret I'm closing this issue, but for type conversion error I opened a separate issue:

https://github.com/pythonnet/pythonnet/issues/563

**Comment by denfromufa** [comment]
@fgiaret don't forget to start the repo!

**Comment by denfromufa** [comment]
@fgiaret don't forget to star the repo!

**Comment by STREETKILLER007** [comment]
I am facing almost the same issue.

"dynamic a = np.array(new List { 1, 2, 3 });
dynamic b = np.array(new List { 6, 5, 4 }, dtype: np.int32);"

I get the following error:
`Python.Runtime.PythonException: 'TypeError : int() argument must be a string, a bytes-like object or a number, not '0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]''`

stack trace :  

```
Python.Runtime.PythonException
  HResult=0x80131500
  Message=TypeError : int() argument must be a string, a bytes-like object or a number, not '0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
  Source=Python.Runtime
  StackTrace:
```

I have the following settings:

Pythonnet version: 2.3.0, installed with pip in Amaconda3
Python version: 3.6.6 using with Anaconda 3;
Visual Studio 2017 Community
Operating System: Windows 7\

referred #249 and tried to run following : 
```
python setup.py bdist_wheel --xplat
pip install dist\pythonnet-2.4.0.dev0-cp36-cp36m-win64.whl
```

but still cannot solve this issue.

Would like to know what's wrong and how to solve this issue. Thank You.
