### ISSUE TITLE
ModuleNotFoundError: No module named 'XYZ' - but the module exists

### ISSUE THREAD

**Issue by yellow-submarine-on-tour** [pythonnet/pythonnet#558]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6.2 64bit
-   Operating System: Win7

### Details

Hey, 

I want to use a few third party .NET DLLs (that controls a physical device) within Python. 

The import works with a class from one DLL, so the setup in general works, but fails at another. The exception is a ModuleNotFoundError, but this module exists for sure

Here is the code:

```python
import sys
import os
import clr

sys.path.append(os.path.dirname(__file__)+ "\\ApiBinaries\\")

# works with TcioWrapper.dll
clr_iow = clr.AddReference("TcioWrapper")
from TopCon import FnTimeData
td = FnTimeData(0, 1.1, 2.2, 3.3)
td.Amplitude = 4.4
print("The amplitude is {0:.3f}".format(td.Amplitude))

# works not with TopConAPI.dll
clr_api = clr.AddReference("TopConAPI")
from CH.Regatron.HPPS.TFE import CurveContainer
'''
from CH.Regatron.HPPS.TFE import CurveContainer
    ModuleNotFoundError: No module named 'CH'

But there is a model with this name for sure one...
'''

Console output with the traceback:
```python
The amplitude is 4.400
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pydev\pydevd.py", line 1578, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/_CodeRepos/LabLinkRegatron/TRUNK/python playground/api_tests.py", line 16, in <module>
    from CH.Regatron.HPPS.TFE import CurveContainer
ModuleNotFoundError: No module named 'CH'
[minExample.zip](https://github.com/pythonnet/pythonnet/files/1390541/minExample.zip)

```

What I found out so far:
- In the DLL there are some classes whose names cannot be resolved. Visual Studio shows this: http://666kb.com/i/dnlgz2892tyeg57tg.png
- This classes won't be instanced by me, but by classes I wanna use in Python.
- It seems that the `from CH.Regatron.HPPS.TFE import CurveContainer` command tries to load also all the references within the DLL and cannot resolve then.
- a pure C# project which uses the DLL works perfectly

Here is an archive with the python code and the DLLs: 
[regatron_pythonet.zip](https://github.com/pythonnet/pythonnet/files/1391014/regatron_pythonet.zip)

The DLLs can be found here: https://www.regatron.com/en/products-topcon/software-products/topcontrol/download-topcontrol at "TopCon API  V1.0.0.370". In their archive is also a doxygen export of the classes as documentation of namesspaces and classes.

Thanks in advance for the help!

Best
Christian

**Comment by chrPlusSomeChars** [comment]
@denfromufa: It seems that your next to last comment in #516 is related to my problem

**Comment by denfromufa** [comment]
@chrPlusSomeChars try opening your assembly in ILSPY, unlike VS it may reveal some hidden implicit dependencies not necessary in C#, but searched for in pythonnet. I have a day job and a class today - so I will not be able to look at this in the next ~24 hours. If you can send me the reproducible example with all dependencies in a stand-alone folder, that maybe another story. My email is my github nickname at gmail dot com.

**Comment by chrPlusSomeChars** [comment]
Thanks for your fast response!

Sorry, I thought I added the file in the first way. Here it is: 
[regatron_pythonet.zip](https://github.com/pythonnet/pythonnet/files/1391003/regatron_pythonet.zip)

ILSPY shows some references: http://666kb.com/i/dnlomhjdxtaegjys4.png and also some "namespaces without a name"

```C
// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Ch.Regatron.APPBase, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// TcioWrapper, Version=1.0.6470.13780, Culture=neutral, PublicKeyToken=null
// Ch.Regatron.APPComponentTopConDataCollector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// Ch.Regatron.APPComponentBatSim, Version=0.2.15.1835, Culture=neutral, PublicKeyToken=null
// APPComponentTopConDevice, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// Ch.Regatron.APPComponentSequencer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// Ch.Regatron.EnergyStorageCore, Version=1.0.0.570, Culture=neutral, PublicKeyToken=null
// Ch.Regatron.APPComponentFunctions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// Ch.Regatron.APPComponentFileReporter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// Ch.Regatron.APPComponentFileReader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Ch.Regatron.EnergyStoragePlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// kernel32
````

**Comment by tinix84** [comment]
hi any news on this issue?

**Comment by chrPlusSomeChars** [comment]
Hi,

in my case the proprietary DLL I wanted to embed uses some code obfuscation methods to hide the vendors IP ("smartassembly"). This also crashed loading with pythonnet.

I found two workarounds:
- Create a simple .NET DLL wrapper that is basically just a 1:1 copy of the methods of the DLL. And then load this wrapper DLL with pythonnet
- Unpack the smartassembly-packed DLL with https://github.com/0xd4d/de4dot and import the unpacked DLLs.

/chr

**Comment by tinix84** [comment]
thanks for the suggestion, i tried also with the dll from tcio but without any success, can you share your workaround please?

**Comment by chrPlusSomeChars** [comment]
Hi,

sorry, for legal reasons, I'm not allowed to share the code. But it is really just like :
`       
public bool is_connected()
{
    return tc.IsConnected();
}`

with a `tc = new CH.Regatron.HPPS.Device.TopCon();` in the constructor

If you refer to the tcio.dll from Regatron, this DLL is a plain C/C++ DLL. So use `ctypes`.
For specific Regatron questions, please ask directly the Regatron support. When I asked them more than 1.5 years ago, they had no idea about python/using their .NET DLL in other programming languages/tools. But I recently contacted them and since then they change the API, updated their DLL, gained experience...

A tip for pythonnet-users:
Instead of `from abc.def import xyz` with `abc.def` is the .NET namespace and 'xyz' is the class, try
`clr_ref = clr.AddReference('TopConAPI')`
using reflections (https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.createinstance)

/chr

**Comment by tinix84** [comment]
thanks for the suggestions
the tcio.dll seem to have strange behavior with the double *pointer I receive really strange values instead in C++ is not an issue I tried different methods to return the double pointer:
`import ctypes as C`
`voltage = C.c_double
        result = self.tcio_dll_obj.TC4GetQ4LimitCurrent(C.byref(voltage ))`
`voltage =C.create_string_buffer(8)
        result = self.tcio_dll_obj.TC4GetVoltageRef(voltage )`
but each of them return a value in 64bit different than the value from C#

[x64.zip](https://github.com/pythonnet/pythonnet/files/3241513/x64.zip)

**Comment by sleepyhollo** [comment]
I am suffering from a similar problem... :(

**Comment by lostmsu** [comment]
Python.NET 3.0 should correctly raise an exception on `AddReference` if the assembly is not loaded. The reasons for assemblies not loading are generally outside of this project scope, and have to be debugged the same way as any other .NET assembly load failures.
