### ISSUE TITLE
Building Python Runtime in Visual Studio 2017

### ISSUE THREAD

**Issue by bobred** [pythonnet/pythonnet#560]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.6 (anaconda)
-   Operating System: Windows 7 (x86)

### Details

How do I compile on Visual Studio 2017. Having just downloaded the latest version and trying to build I get numerous errors, like 

Error	CS0115	'PyObject.Equals(object)': no suitable method found to override	Python.Runtime.15(netstandard2.0)	E:\pythonnet-master\src\runtime\pyobject.cs

Error	CS0246	The type or namespace name 'BinaryOperationBinder' could not be found (are you missing a using directive or an assembly reference?)	Python.Runtime.15(netstandard2.0)	E:\pythonnet-master\src\runtime\pyobject.cs	1094

Error	CS0234	The type or namespace name 'Dynamic' does not exist in the namespace 'System' (are you missing an assembly reference?)	Python.Runtime.15(netstandard2.0)	E:\pythonnet-master\src\runtime\pyobject.cs	3	

I have set the the Config to DebugWin|x86.
Thanks

**Comment by denfromufa** [comment]
@bobred the best way to build is using `setup.py`. Building from VS interface is intended for developers of pythonnet. Are you on .NET Framework or .NET Core?

**Comment by bobred** [comment]
Thanks, that worked.

**Comment by denfromufa** [comment]
@bobred don't forget to star this project! 

If you think that we can improve installation and troubleshooting wiki, then please let us know!

https://github.com/pythonnet/pythonnet/wiki/Installation
https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX
