### ISSUE TITLE
PInvokeStackImbalance 

### ISSUE THREAD

**Issue by bobred** [pythonnet/pythonnet#561]
### Environment

-   Pythonnet version: 2.3.0.o
-   Python version: 3.6 (anconda)
-   Operating System: Win 7 (x86)

### Details
With the code below I'm getting the following error at PythonEngine.PythonHome = @"C:\Anaconda3";, without this I get The program '[8320] Test.exe' has exited with code 3 (0x3).

> Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'Python.Runtime!Python.Runtime.Runtime::Py_SetPythonHome' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

I installed pythonnet by pip install -i https://pypi.anaconda.org/pythonnet/simple pythonnet

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Python.Runtime;
using System.Runtime.InteropServices;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {

            PythonEngine.PythonHome = @"C:\Anaconda3";

            using (Py.GIL())
            {
                try
                {
                    dynamic np = Py.Import("numpy");
                    Console.WriteLine(np.cos(np.pi * 2));

                    dynamic sin = np.sin;
                    Console.WriteLine(sin(5));

                    double c = np.cos(5) + sin(5);
                    Console.WriteLine(c);

                    dynamic a = np.array(new List<float> { 1, 2, 3 });
                    Console.WriteLine(a.dtype);

                    dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
                    Console.WriteLine(b.dtype);

                    Console.WriteLine(a * b);
                    Console.ReadLine();
                }
                catch (InvalidCastException e)
                {
                    Console.WriteLine(e);
                    Console.ReadLine();
                }
            }
        }
    }
}

I have added a reference to Python.Runtime.dll in C:\Anaconda3\Libs\site-packages, any ideas

**Comment by denfromufa** [comment]
Install from master, search issue tracker for this issue

**Comment by bobred** [comment]
Do you mean compile from latest source?

**Comment by denfromufa** [comment]
Yes, https://github.com/pythonnet/pythonnet/wiki/Installation

**Comment by denfromufa** [comment]
@bobred were you able to install from master or grab the wheels from appveyor? I'm closing this for now, but if you get any issues, feel free to comment.

**Comment by bobred** [comment]
I installed via Conda but had to disable PinvokeStakeImbalance exception in VS 2017. Runs fine outside of VS2017.
