### ISSUE TITLE
Python 3.6 Nuget

### ISSUE THREAD

**Issue by adamcai** [pythonnet/pythonnet#568]
-   The master branch already defines Python36 but the dll is not available in nuget.

**Comment by denfromufa** [comment]
@adamcai contributions are welcome, at least I plan to release this next version of pythonnet:

https://github.com/pythonnet/pythonnet/issues/165

Let me know if you would like to add Python 3.6 support, then I can add you on nuget.

**Comment by Cronan** [comment]
I'm happy to take a look at this, let me know what needs to be done. I've created nugget packages directly, and via Appveyor on [another project](https://www.nuget.org/packages/ManAhl.NArctic/).

**Comment by denfromufa** [comment]
i like nugget :) i added you @Cronan to package owners. feel free to add Python 3.6 version. We should probably start adding pythonnet 2.4.0.dev versions in all distributions channels (nuget, pypi. conda, docker).

for remaining issues with nuget please review the linked issue #165.

**Comment by Cronan** [comment]
Have all the current packages been built "by hand", or do you have some appveyor integration?

**Comment by denfromufa** [comment]
By hand, building and pushing  from Appveyor should be fine.

**Comment by Cronan** [comment]
I'll investigate doing it from Appveyor

**Comment by chrisjbremner** [comment]
@Cronan any update on this? I only see 2.7 and 3.5 on Nuget at the moment.

**Comment by denfromufa** [comment]
@chrisjbremner would you like to make these nuget builds?

**Comment by chrisjbremner** [comment]
I was able to build the DLL from the solution file provided in the repo (didn't realize it was there when I made the comment), which worked for my purposes

**Comment by Gaspa79** [comment]
Same here, a 3.6 nuget package would be nice

**Comment by denfromufa** [comment]
@gaspa79 would you like to make this contribution?

**Comment by inna-w** [comment]
I am willing to make this contribution. :)
You are welcome to examine the build artifacts of my fork in Appveyor: https://ci.appveyor.com/project/inna-w/pythonnet/builds/24890622.
Only --xplat builds produce the nuget package, since I am utilizing MSBuild 15 capability to generate package as part of the solution build process.
If we are happy, I will submit a pull request.
