### ISSUE TITLE
Failing tests in Windows

### ISSUE THREAD

**Issue by Cronan** [pythonnet/pythonnet#569]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 2.7.13
-   Operating System: Windows 7 Enterprise SP 1 (64-bit)

### Details

-   I was trying to run the tests after building from the command line. Build worked fine, tests failed

-   I used the following commands to create the issue:

```python
    pip install wheel
    pip install pytest
    git clone https://github.com/Cronan/pythonnet.git
    cd pythonnet
    pip install --no-index --find-links=.\dist\ pythonnet
    python setup.py bdist_wheel
    python -m pytest
```

-   Details of the error below:

```python
D:\git\pythonnet>python -m pytest
============================= test session starts =============================
platform win32 -- Python 2.7.13, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: D:\git\pythonnet, inifile: setup.cfg
collected 0 items / 1 errors

=================================== ERRORS ====================================
______________________________ ERROR collecting  ______________________________
D:\python27\lib\site-packages\py\_path\common.py:372: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
D:\python27\lib\site-packages\py\_path\common.py:421: in gen
    for p in self.gen(subdir):
D:\python27\lib\site-packages\py\_path\common.py:411: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
D:\python27\lib\site-packages\_pytest\main.py:728: in _recurse
    ihook = self.gethookproxy(path)
D:\python27\lib\site-packages\_pytest\main.py:632: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
D:\python27\lib\site-packages\_pytest\config.py:356: in _getconftestmodules
    mod = self._importconftest(conftestpath)
D:\python27\lib\site-packages\_pytest\config.py:381: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: ImportError('No module named clr',)
E     File "D:\python27\lib\site-packages\_pytest\assertion\rewrite.py", line 212, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "D:\python27\lib\site-packages\py\_builtin.py", line 221, in exec_
E       exec2(obj, globals, locals)
E     File "<string>", line 7, in exec2
E     File "D:\git\pythonnet\src\tests\conftest.py", line 13, in <module>
E       import clr
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.36 seconds ===========================
```

**Comment by denfromufa** [comment]
@Cronan maybe you forgot to install this wheel package?

`pip install --no-index --find-links=.\dist\ pythonnet`

**Comment by Cronan** [comment]
I don't believe so:

```
D:\git\pythonnet>pip install --no-index --find-links=.\dist\ pythonnet
Requirement already satisfied: pythonnet in d:\python27\lib\site-packages
```

Then re-running the tests just gives the same error.

**Comment by denfromufa** [comment]
@Cronan something is goofy with your setup, I just tried on both Python 2.7 and 3.5 without any issues. Try first uninstalling pythonnet from your environment, maybe you have leftover somewhere in your path. Also the order `setup.py` step comes before `pip install` step.

```
C:\Python\Python27_32b\pythonnet>..\python -m pytest
============================= test session starts =============================
platform win32 -- Python 2.7.0, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: C:\Python\Python27_32b\pythonnet, inifile: setup.cfg
collected 376 items

src\tests\test_array.py ........................................
src\tests\test_callback.py ..
src\tests\test_class.py ..................
src\tests\test_clrmethod.py .....
src\tests\test_compat.py ................
src\tests\test_constructors.py ....
src\tests\test_conversion.py ....................
src\tests\test_delegate.py .................
src\tests\test_docstring.py ...
src\tests\test_engine.py .ss
src\tests\test_enum.py ...............
src\tests\test_event.py ............................
src\tests\test_exceptions.py ........................s
src\tests\test_field.py ..............................
src\tests\test_generic.py .................
src\tests\test_import.py .
src\tests\test_indexer.py .............................
src\tests\test_interface.py ....
src\tests\test_method.py ..............................................
src\tests\test_module.py ............................
src\tests\test_property.py ..........
src\tests\test_recursive_types.py .
src\tests\test_subclass.py ..........
src\tests\test_sysargv.py .
src\tests\test_thread.py ...
=========================== short test summary info ===========================
SKIP [1] src\tests\test_engine.py:22: FIXME: test crashes
SKIP [1] src\tests\test_exceptions.py:332: __cause__ isn't implemented in PY2
SKIP [1] src\tests\test_engine.py:30: FIXME: test freezes

========================== slowest 5 test durations ===========================
1.19s call     src/tests/test_thread.py::test_python_thread_calls_to_clr
0.29s call     src/tests/test_module.py::test_preload_var
0.20s call     src/tests/test_module.py::test_implicit_assembly_load
0.19s call     src/tests/test_callback.py::test_default_for_null
0.18s call     src/tests/test_sysargv.py::test_sys_argv_state
==================== 373 passed, 3 skipped in 5.35 seconds ====================
```

**Comment by Cronan** [comment]
OK, starting again, after clearing everything down:

`env | grep pythonnet` - nothing found
`pip list | grep -e wheel -e pytest -e pythonnet`
> pytest (3.2.3)
> wheel (0.30.0)

`git clone https://github.com/pythonnet/pythonnet.git`
`cd pythonnet`
`python setup.py bdist_wheel` - a couple of warnings but nothing serious

> delegatemanager.cs(204,13): warning CS0162: Unreachable code detected [D:\git\pythonnet\src\runtime\Python.Runtime.csproj]
> pyobject.cs(50,13): warning CS0162: Unreachable code detected [D:\git\pythonnet\src\runtime\Python.Runtime.csproj]
> pythonexception.cs(64,13): warning CS0162: Unreachable code detected [D:\git\pythonnet\src\runtime\Python.Runtime.csproj]
> pyscope.cs(534,13): warning CS0162: Unreachable code detected [D:\git\pythonnet\src\runtime\Python.Runtime.csproj]
>   Python.Runtime -> D:\git\pythonnet\src\runtime\bin\Python.Runtime.dll
>   Python.Test -> D:\git\pythonnet\src\testing\bin\Python.Test.dll
> dynamic.cs(121,28): warning CS0618: 'PythonEngine.RunString(string, IntPtr?, IntPtr?)' is obsolete: 'RunString is deprecated and will be removed. Use Exec/Eval/RunSimpleString instead.' [D:\git\pythonnet\src\embed_tests\Python.EmbeddingTest.csproj]

`pip install --no-index --find-links=.\dist\ pythonnet`
> Collecting pythonnet
> Installing collected packages: pythonnet
> Successfully installed pythonnet-2.4.0.dev0

Checking envs again:
`env | grep pythonnet`
> !D:=D:\git\pythonnet

`pip list | grep pythonnet`
> pythonnet (2.4.0.dev0)

`python -m pytest`
>============================= test session starts=============================
platform win32 -- Python 2.7.13, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: D:\git\pythonnet, inifile: setup.cfg
collected 0 items / 1 errors
===================================ERRORS====================================
______________________________ ERROR collecting  ______________________________
D:\python27\lib\site-packages\py\_path\common.py:372: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
D:\python27\lib\site-packages\py\_path\common.py:421: in gen
    for p in self.gen(subdir):
D:\python27\lib\site-packages\py\_path\common.py:411: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
D:\python27\lib\site-packages\_pytest\main.py:728: in _recurse
    ihook = self.gethookproxy(path)
D:\python27\lib\site-packages\_pytest\main.py:632: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
D:\python27\lib\site-packages\_pytest\config.py:356: in _getconftestmodules
    mod = self._importconftest(conftestpath)
D:\python27\lib\site-packages\_pytest\config.py:381: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: FileNotFoundException(u"Unable to find assembly 'Python.Test'.",)
E     File "D:\python27\lib\site-packages\_pytest\assertion\rewrite.py", line 212, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "D:\python27\lib\site-packages\py\_builtin.py", line 221, in exec_
E       exec2(obj, globals, locals)
E     File "<string>", line 7, in exec2
E     File "D:\git\pythonnet\src\tests\conftest.py", line 21, in <module>
E       clr.AddReference("Python.Test")
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.70 seconds===========================

**Comment by Cronan** [comment]
Can you think of anything else I can check in my environment?

**Comment by denfromufa** [comment]
@Cronan now the error is different, you need to add the testing dependencies (e.g. Python.Test) to your path according to this:

https://github.com/pythonnet/pythonnet/blob/master/ci/appveyor_run_tests.ps1

**Comment by Cronan** [comment]
Your link is to a ps script, I'm not sure what I'm supposed to do

**Comment by denfromufa** [comment]
@Cronan you can just copy Python.Test.dll to your site-packages folder or add it to Python sys.path. I'm not sure how to simplify your setup any further.

**Comment by denfromufa** [comment]
here is Python.Test.dll locations after the build, not sure how it looks on your build:

![image](https://user-images.githubusercontent.com/7870949/32669964-e3861c4a-c607-11e7-8f62-6ead54694382.png)

**Comment by Cronan** [comment]
Mine looks as follows after building:
![python test locations](https://user-images.githubusercontent.com/777435/32717138-7bb213da-c850-11e7-9e0a-82c1c6aeae6f.png)
It seems I'm missing the one in tests and testing, maybe?

**Comment by Cronan** [comment]
I had an older version of the dll in site-packages, all solved when I replaced it:
**373 passed, 3 skipped in 6.55 seconds**

Thanks for all your help @denfromufa
