### ISSUE TITLE
Calling .NET function taking PyObject using reflection

### ISSUE THREAD

**Issue by stevehv** [pythonnet/pythonnet#576]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.5.3
-   Operating System: Windows 10
-   F# 4.4.1.0, .NET Framework 4.7
### Details

I need to call a F# function which takes a PyObject. Usually this is trivial, but I must do the function call using reflection (because there is currently no other way to release the dll afterwards). This results in a TypeError.
- F#:
```Fs
let test (x: PyObject) = 
    "Hello, World"
``` 
- Python:
```Python
dll.GetType("MyModule").GetMethod("test").Invoke(None, [object()])
# TypeError: No method matches given arguments
```

The problem only happens with PyObject. The following code works fine, since it does not use PyObject:
- F#:
```Fs
let test (x: string) = 
    "Hello, World"
```
- Python:
```Python
dll.GetType("MyModule").GetMethod("test").Invoke(None, ["asdf"])
# "Hello, World"
```

How can I pass a PyObject to .NET when using reflection?

**Comment by denfromufa** [comment]
Is PyObject from Python.Runtime.dll?
Try passing PyObject in Python as argument instead of object.
You need to import PyObject in Python from Python.Runtime.dll

**Comment by stevehv** [comment]
Yes, it is Python.Runtime.PyObject. How can I create a PyObject in python since the constructor takes an IntPtr?

**Comment by denfromufa** [comment]
@stevehv that is a good point! so you need to get a pointer of Python object for IntPtr constructor. Now this maybe really a very bad idea, since I have not done this is in practice. I based my code below on this blog post:

http://www.xavierdupre.fr/app/pymyinstall/helpsphinx/blog/2016/2016-01-03_pythonnet.html

```
>>> from Python.Runtime import PyObject
>>> PyObject(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: no constructor matches given arguments
>>> PyObject.Overloads
Python.Runtime.PyObject(IntPtr)
>>> from System import IntPtr
>>> IntPtr.Overloads
System.IntPtr(Void*)
System.IntPtr(Int64)
System.IntPtr(Int32)
>>> import numpy as np
>>> arr = np.ones((2,2))
>>> arr.__array_interface__
{'descr': [('', '<f8')], 'strides': None, 'shape': (2L, 2L), 'version': 3, 'type
str': '<f8', 'data': (33167280L, False)}
>>> arr.__array_interface__['data'][0]
33167280L
>>> IntPtr(arr.__array_interface__['data'][0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'long' value cannot be converted to System.IntPtr
>>> IntPtr.Overloads[Int64](arr.__array_interface__['data'][0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Int64' is not defined
>>> from System import Int64
>>> IntPtr.Overloads[Int64](arr.__array_interface__['data'][0])
<System.IntPtr object at 0x00000000027B2D30>
>>> PyObject(IntPtr.Overloads[Int64](arr.__array_interface__['data'][0]))
<Python.Runtime.PyObject object at 0x00000000027B2898>
>>>
```

**Comment by lostmsu** [comment]
This is actually the default behavior now.
