### ISSUE TITLE
Will pythonnet support Unity2017?

### ISSUE THREAD

**Issue by sekkit** [pythonnet/pythonnet#578]
As the title indicates.
thx.

**Comment by denfromufa** [comment]
Not unless someone commits the code and testing for this. None of pythonnet core developers work with Unity as far as I know.

At one point Unity used to have Python scripting API, which was dropped due to performance issues. This is according to Xamarin founder.

**Comment by denfromufa** [comment]
Is this you who posted originally on mailing list?

https://mail.python.org/pipermail/pythondotnet/2017-November/001924.html

**Comment by sekkit** [comment]
Nope. I am unable to find any mail relating to this repo.

Python & lua for game programming is widely used in some countries like china. Performance issue is not the key, for many small to mid projects it worked.
The benefits are that u can shared server codebase with client. Also you can do patching or hot reloading on iOS.
Companies like Netease they use Python for client&server, all the game logic, and with proper optimisation, games like 3d MMO can run at acceptable frames, the drawbacks are though, your device's gonna consume battery much faster than native C++ games.

Again, it can be the third option for developers. To use Unity with Bigword or KBEngine, a unified script language is efficient.

for many mobile games, pure performance is not the key to success.

**Comment by filmor** [comment]
The question should be whether Python.NET runs on the .NET runtime that is shipped with Unity 2017. There is documentation on which versions of Mono we support, compare the versions or just try it out :)

**Comment by denfromufa** [comment]
Looks like Unity does not support `dynamic` keyword yet, but I have tried this myself:

https://answers.unity.com/questions/1413144/c-dynamic-variables-as-of-2017.html

**Comment by denfromufa** [comment]
Looks like Unity does not support dynamic keyword yet, but I have NOT tried this myself:

https://answers.unity.com/questions/1413144/c-dynamic-variables-as-of-2017.html

**Comment by sekkit** [comment]
dynamic works on Mono runtime not il2cpp，thus iOS wont compile. Ironpython works for Unity but also wont compile for iOS due to some dynamic DLR methods being unable to be recognized by il2cpp compiler. dynamic keyword is not neccessary, u can reference lua’s impl like cstolua, tolua#, ulua etc

**Comment by denfromufa** [comment]
@amos402 is experimenting with unity and pythonnet:

https://github.com/pythonnet/pythonnet/pull/687
