### ISSUE TITLE
Basic questions about this project

### ISSUE THREAD

**Issue by guilhermecgs** [pythonnet/pythonnet#579]
### Environment

-   Pythonnet version:  latest
-   Python version: latest 2.x.x
-   Operating System:  Windows

### Details
Hi Folks, 

I´m trying to use some LabView DLL in a python code. [( link )](https://forums.ni.com/t5/LabVIEW/Calling-a-LabVIEW-NET-Interop-Assembly-from-IronPython/td-p/3176382)

My first try was to use IronPython with a clr.AddReference  command.

But since IronPython is not the normal CPython implementation, I was having problems installing 3rd party libraries like Numpy, Pandas, etc etc...

So, I did some research and found this project... And I have some basic questions:

1. It is not clear what is the difference to IronPython. I know that this is just a wheel package on top of CPython, while IronPython is a whole new interpleter. But under the hood, what am I really doing?

**Comment by filmor** [comment]
General questions like this don't belong into our issue tracker, please use the chat for this: https://gitter.im/pythonnet/pythonnet

The main difference is, like you already recognised, that IronPython is an independent implementation of the Python 2.7 language written in C# and running on the CLR, while Python.NET is a library to interface the original Python interpreter with .NET.
