### ISSUE TITLE
Integers not working as expected with 32bit Python 3.x

### ISSUE THREAD

**Issue by npezolano** [pythonnet/pythonnet#58]
The simplest way to reproduce this issue,

```python
from System import Array
myarray = Array[int]([10]) #OverflowError: value too large to convert
```

**Comment by denfromufa** [comment]
not confirmed on Python 2.7, 32-bit, Python.NET from http://www.lfd.uci.edu/~gohlke/pythonlibs/

```
from System import Array
myarray = Array[int]([10])

print len(myarray)  # 1
print myarray[0]  # 10
```

**Comment by denfromufa** [comment]
For Python 3 use:
* source:
https://github.com/renshawbay/pythonnet

** wheels:
http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by npezolano** [comment]
I just tried the pythonnet‑2.0.0.dev1‑cp34‑none‑win32.whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/ and I get the same error.

**Comment by denfromufa** [comment]
just to confirm which python/windows/.net version/bitness are you using?

**Comment by denfromufa** [comment]
ok confirmed:

```
c:\Python\Python34\Scripts>pip.exe install ..\pythonnet-2.0.0.dev1-cp34-none-win
32.whl
Unpacking c:\python\python34\pythonnet-2.0.0.dev1-cp34-none-win32.whl
Installing collected packages: pythonnet
Successfully installed pythonnet
Cleaning up...

c:\Python\Python34\Scripts>cd..
c:\Python\Python34>python
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
Attempting to load Python.Runtime using standard binding rules...
Attempting to load Python.Runtime from: 'c:\Python\Python34\lib\site-packages\Py
thon.Runtime.dll'...
>>> from System import Array
>>> myarray = Array[int]([10])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: value too large to convert
>>>
```

**Comment by tonyroberts** [comment]
Use the latest code from https://github.com/renshawbay/pythonnet and it works.

In [1]: import clr
In [2]: from System import Array
In [3]: myarray = Array[int]([10])
In [4]: myarray
Out[4]: <System.Int32[] at 0x7453e10>

Those wheels are not official releases. Before reporting any issues/bugs please it's best to checl you are using the latest code.

Please check and close this issue if it works for you.

thanks,
Tony

**Comment by npezolano** [comment]
closing fixed with using the branch above
