### ISSUE TITLE
PythonEngine.Exec scope between classes

### ISSUE THREAD

**Issue by evandavey** [pythonnet/pythonnet#591]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6
-   Operating System:  Windows 10        

### Details

I am embedding Python using PythonEngine.Exec to run code read from a file which seems to be losing global scope.

```csharp
string code;
using (var streamReader = new StreamReader(scriptFile, Encoding.UTF8)) {
   code = streamReader.ReadToEnd();
}
 
using (Py.GIL()) {
    PythonEngine.Exec(code)
}
```
The python code contains two classes:

```python

class Test1():
   pass

class Test2():
   def __init__(self):
       Test1()

Test2()
```

Error:

```
NameError: name 'Test1' is not defined
```

**Comment by yagweb** [comment]
It's a bug of the Exec method. I just submit a [PR](https://github.com/pythonnet/pythonnet/pull/594) to fix it.

Another method is using the PyScope class,
```
string code;
using (var streamReader = new StreamReader(scriptFile, Encoding.UTF8)) {
   code = streamReader.ReadToEnd();
}
 
using (Py.GIL()) {
    var scope = Py.CreateScope();
    scope.Exec(code);
    var t1 = (scope as dynamic).Test1();
    var t2 = scope.Get<dynamic>("Test2")();
}
```

**Comment by evandavey** [comment]
Thanks.  I also had some success using `PythonEngine.ModuleFromString(...)`.

**Comment by denfromufa** [comment]
@evandavey @yagweb thanks for this bug report and pull request!
