### ISSUE TITLE
Update Required for dotnet core 2

### ISSUE THREAD

**Issue by hasanOryx** [pythonnet/pythonnet#592]
Hi..
Apparently no update done since a while, can you pls update it to compatible with the latest edition of `.NET CORE` I just got the below:
   
> not compatible with netcoreapp2.0

**Comment by denfromufa** [comment]
.NET Core support is still partial. Contributions are welcome!

**Comment by weixu02** [comment]
By the way, could you please confirm whether it is fully compatible with .net framework 4.7.1? Thanks!

**Comment by denfromufa** [comment]
@weixu02 .net framework 4.7.1 should work as-is, there is nothing special about it.

@hasanOryx i'm closing this issue in favor of this one below where we track the progress on .NET Core (CoreCLR):

https://github.com/pythonnet/pythonnet/issues/96
