### ISSUE TITLE
How to call python scrip file from F# script file

### ISSUE THREAD

**Issue by hasanOryx** [pythonnet/pythonnet#593]
Hi..

I'm new for both python and F#, and trying to work interactively with both of them, I've the below `Script.py`:

```
glob = 1

from anotherpython import boo   # Connecting to anothre python file `anotherpython.py`

boo()   # Executing function from anotherpython file

def foo():
    loc = 5
    print('loc in foo():', 'loc' in locals())

foo()
print('loc in global:', 'loc' in globals())    
```

And have the below `Script.fsx` file:
```

#load "anotherfile.fsx"    // This is correct for loading another fsx file
#load "Script.py"  //=> Is this the correct way to load a py file?


open System
open pythonnet  //=> Is this correct to load the package?
open Karkar.EvenOdd   // this is correct to call from anotherfile.fsx
open glob.foo    //=> Is this the correct way to call from script.py? 

printf "Welcome from F#, print any key to continue ..."
Console.ReadKey()

printf "%i is %s\n" 2 (isEven 2)    // here I'm correctly calling iEven from Karkar.EvenOdd in the anotherfile.fsx
printf "print the value of loc in the script.py file, it is %i" loc     //=> Is this correct
```
I've 4 statements in my last code with comments start `//=>` these are my question :)

**Comment by denfromufa** [comment]
F# support is unofficial and not tested. Generally CLR/C# compliant code should work without issues. Search the issue tracker and see wiki for partial F# demos.

**Comment by hasanOryx** [comment]
There is no F# demo :(
Well what about C#, how can I import `.py` file into `C#` file?

**Comment by denfromufa** [comment]
For F# see 2 articles in wiki:

https://github.com/pythonnet/pythonnet/wiki

For C# here is tutorial and readme:

http://pythonnet.github.io

https://github.com/pythonnet/pythonnet/blob/master/README.md

For questions like this please don't use the issue tracker, instead we have a gitter chat:

https://gitter.im/pythonnet/pythonnet
