### ISSUE TITLE
PythonEngine.Initialize slow

### ISSUE THREAD

**Issue by goerch** [pythonnet/pythonnet#598]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6
-   Operating System: Windows 7

### Details

When embedding Python in an ASP.NET MVC 5 web application, PythonEngine.Initialize needs a couple of seconds to eagerly load the names of around 50 module namespaces in ModuleObject.LoadNames. If I replace the implementation of LoadNames with a NOP, time spent in PythonEngine.Initialize drops to below 100 ms and the web application still seems to work.

**Comment by dmitriyse** [comment]
We already have PR for that problem.  See https://github.com/pythonnet/pythonnet/pull/528

Also try to build python.net from the branch https://github.com/pythonnet/pythonnet/tree/featured
This branch contains muptiple not yet merged fixes to the master branch.

**Comment by goerch** [comment]
I don't fully understand the idea of *eager* initialization of the cache in ModuleObject.LoadNames when other members of ModuleObject use *lazy* caching. At least in my use case (using only a couple of methods of the 50+ module namespaces) this seems to be a bad tradeoff.

Are there any benchmarks to justify this design?

**Comment by goerch** [comment]
Just tested the branch https://github.com/pythonnet/pythonnet/tree/featured. Response time is down to 200 ms with eager initialization of 50+ module namespaces. Thanks for your help!

**Comment by pierce-martin** [comment]
When will this fix be incorporated into a release? The branch https://github.com/pythonnet/pythonnet/tree/featured seems to work great, but it doesn't appear that master has these changes. Thanks.

**Comment by denfromufa** [comment]
this is now in master branch: https://github.com/pythonnet/pythonnet/pull/723
