### ISSUE TITLE
pythonnet not working

### ISSUE THREAD

**Issue by inoureddine** [pythonnet/pythonnet#599]
### Environment

-   Pythonnet version:
-   Python version:
-   Operating System:windows 10

I am trying to use pythonnet to run a python script from a .Net application , i installed pip , python and the project on git hub , also i did all the installation steps mentioned on https://github.com/pythonnet/pythonnet/wiki/Installation and the troubleshooting steps on https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX

when i created a windows application to run a python script, the project was built successfully , however when i click the button to execute a python script the application will exit showing the following output :

The program '[30236] WindowsFormsApplication1.vshost.exe: Program Trace' has exited with code 0 (0x0). The program '[30236] WindowsFormsApplication1.vshost.exe' has exited with code 1 (0x1).

the code i am using to execute the python file :

```
 try
            {
                using (Py.GIL())
                {
                    var test1 = "";

                    dynamic np = Py.Import("sum");
                    Console.WriteLine(np.cos(np.pi * 2));
                }

            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
```
when i tried to check where exactly the project stops , it was in the Python.RunTime project => runtime.cs =? Initialize() .

I found the code
```
#if PYTHON27
        public const string pyversion = "2.7";
        public const string pyver = "27";
```
in the runtime block , and this if condition is always true , how to specify the version of the python i want to use ? and should i add any more reference to my project to work fine ?

thank you,

**Comment by denfromufa** [comment]
Are you sure about this code:

`dynamic np = Py.Import("sum");`

Can you format your issue according to GitHub markdown syntax?

**Comment by inoureddine** [comment]
Hi denfromufa , the problem is not 
`dynamic np = Py.Import("sum")`
referring to [](https://github.com/pythonnet/pythonnet/blob/master/README.md) , it is the way to import a python file , the code stops before entering the using {} , it stops when entering Py.GIL()) .
Do i have to add any references or external file to the solution published on GitHub ?

**Comment by denfromufa** [comment]
What is your installed Python version?

**Comment by denfromufa** [comment]
I'm closing this issue, since there is no bug report or feature request. Please continue discussion in pythonnet gitter channel:

https://gitter.im/pythonnet/pythonnet
