### ISSUE TITLE
 A call to PInvoke function 'Python.Runtime!Python.Runtime.Runtime::PyImport_ImportModule' has unbalanced the stack.

### ISSUE THREAD

**Issue by inoureddine** [pythonnet/pythonnet#600]
### Environment

-   Pythonnet version: pythonnet_py35_dotnet.2.3.0
-   Python version: 3.5
-   Operating System: windows 10

### Details

My problem was that the code exit when it enters py_initialize() however t was w python version problem , i just changed the compilation symbol to 3.5 the issue was solved . however another issue occured 
 

> A call to PInvoke function 'Python.Runtime!Python.Runtime.Runtime::PyImport_ImportModule' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.

on the line 182 of the class runtime.cs : 
`op = PyImport_ImportModule("builtins");`

I tried to add the reference "python.runtime.dll" from the python35 version , another error occurs.

> Managed Debugging Assistant 'PInvokeStackImbalance'

I reviewed similar issue , installed nuget packages pythonnet_py35_dotnet.2.3.0 and pythonnet.2.3.0-py35-dotnet , and added the python35 path to the path in the environment variables , but the issue in not solved.
anything else i should do ? i am using VS2015

**Comment by denfromufa** [comment]
@inoureddine this is just a warning during debugging and should not be harmful, but this was fixed in the latest master branch, in case you really need this. please search the issue tracker before posting similar issues:

https://github.com/pythonnet/pythonnet/search?q=unbalanced+stack&type=Issues&utf8=%E2%9C%93

**Comment by inoureddine** [comment]
Thanks for the reply , you're right it was a warning , however when i tried to import a python file an unreadable message exception occurred as shown below . Where should i add my python file to be able to execute it ? and is there any code snippet on how can i read the output of my python file ?

![pythonexe](https://user-images.githubusercontent.com/35490598/35099841-289e81b0-fc62-11e7-874f-d45f1cd5f33c.png)
