### ISSUE TITLE
Converter works for IList<T> but not for T[]

### ISSUE THREAD

**Issue by jjaskulowski** [pythonnet/pythonnet#601]
### Environment

-   Pythonnet version: 
-   Python version: all
-   Operating System: all

### Details

I lost hours on this.
converter.ToPython() does not enter condition "if (value is IList && value.GetType().IsGenericType)" for arrays so arrays that could be converted to python lists are not being converted.

I think it should also work for any generic and not generic ICollection and any Array.

Instead, it currently treats it as a generic PyObject.

Otherwise, great job!

**Comment by denfromufa** [comment]
@jjaskulowski .NET arrays are not the same as Python lists, even .NET lists are not the same as Python lists.
So technically even what is currently done is not ideal. So what should you do for now? I suggest converting arrays between Python and .NET using some of techniques you can find in this issue tracker.
