### ISSUE TITLE
Infinite loop/crash in root.LoadNames()

### ISSUE THREAD

**Issue by barrybriggs** [pythonnet/pythonnet#603]
### Environment

-   Pythonnet version: 2.3
-   Python version: 3.6
-   Operating System: Windows

### Details

(Pythonnet newbie). Trying to embed Pythonnet in a simple WPF app. Built Python.Runtime from source setting PYTHON3 and PYTHON36 on x64. Gets to GetCLRModule in importhook.cs and gets in infinite loop in root.LoadNames() line 98, ultimately crashes.

**Comment by denfromufa** [comment]
@barrybriggs how can someone reproduce this issue? Did you look at troubleshooting and installation wikis? Does this happen without WPF (in console)?

**Comment by barrybriggs** [comment]
Thanks for the quick response. The code is very, very simple -- click on a WPF menu and the click handler calls `PythonEngine.Initialize()`. When I trace into `root.LoadNames()`  there is the following code:

```      public void LoadNames()
        {
            ManagedType m = null;
            foreach (string name in AssemblyManager.GetNames(_namespace))
            {
                cache.TryGetValue(name, out m);
                if (m == null)
                {
                    ManagedType attr = GetAttribute(name, true);
                }
            }
        }
```

The 'names' that it loads are: "FXAssembly", "ThisAssembly", "AssemblyRef", "<PrivateImplementationDetails>", and then it starts trying to load what seems like types "_StaticArrayInitTypeSize=6" and then 8, and so on. It does this forever. 

I have a feeling this may be because there is some required assembly or .py file or something like that it's looking for, but I can't find it.

**Comment by denfromufa** [comment]
Do the demo apps work for you? Your example is still not reproducible.

**Comment by barrybriggs** [comment]
`npython` loads. However, the demo apps do not run (assuming I typed the command correctly, which, as a Python newbie, I may not have): 
```
>>> exec(open("Z:\demo\helloform.py").read())
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 8, in <module>
ModuleNotFoundError: No module named 'System'
```
`PATH` and `PYTHONHOME` are set correctly.

**Comment by dmitriyse** [comment]
Please try "featured" branch. At least problems with "_StaticArrayInitTypeSize=6" types are eliminated.

**Comment by barrybriggs** [comment]
@dmitriyse That seems to have cured the problem. Thanks!!

**Comment by denfromufa** [comment]
@dmitriyse what is the corresponding commit that fixes this "_StaticArrayInitTypeSize=6". I have not seen this issue before.

**Comment by dmitriyse** [comment]
This is the corresponding PR https://github.com/pythonnet/pythonnet/pull/528

**Comment by denfromufa** [comment]
closed by https://github.com/pythonnet/pythonnet/pull/723
