### ISSUE TITLE
make links to issues and PR in changelog working

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#608]
https://github.com/pythonnet/pythonnet/blob/master/CHANGELOG.md

**Comment by civilx64** [comment]
I'm currently working on this, as I was surprised that the issues and PR are not rendered as links by default on github.  The solution I'm employing uses Markdown reference-style links.  While this is somewhat verbose, a side benefit is that the links will still work if the changelog is rendered outside of github.

**Comment by denfromufa** [comment]
@civilx64 PRs are welcome!

**Comment by civilx64** [comment]
@denfromufa PR submitted (#695).

**Comment by denfromufa** [comment]
@civilx64 thanks for this!
