### ISSUE TITLE
SystemError: dynamic module not initialized properly since update to.NET 4.5.2

### ISSUE THREAD

**Issue by ThiefMaster** [pythonnet/pythonnet#61]
I've just installed .NET framework 4.5.2 via Windows Update. Apparently this broke Python for .NET:

> SystemError: dynamic module not initialized properly

whenever I try to `import clr`

**Comment by denfromufa** [comment]
Which Python/Windows version and bitness?

Maybe this is related:

http://grokbase.com/t/python/pythondotnet/13b689d6f9/python-net-python-net-on-windows-8-1
https://mail.python.org/pipermail/pythondotnet/2013-November/001434.html

**Comment by ThiefMaster** [comment]
Python 2.7.7 32bit, Windows 7 x64, most likely the latest released binary of pythonnet.

**Comment by denfromufa** [comment]
can you provide the link to the binary (or source which compiled) used?

**Comment by ThiefMaster** [comment]
Honestly, I have no idea which one I used. It was over a year ago.

**Comment by denfromufa** [comment]
your binary may need to be recompiled as x86 instead of AnyCPU.
https://mail.python.org/pipermail/pythondotnet/2011-February/001080.html

or this could be the problem:
http://sourceforge.net/p/pythonnet/support-requests/5/

**Comment by ThiefMaster** [comment]
Recompiling the current source from Git fixed the problem. All I changed was selecting ReleaseWin/x86 in the build options.

**Comment by FredChauviere** [comment]
Hi ThiefMaster,

Same problem here. Could you please deposit your recompiled bin on any public repository of your choice ? Not sure if I have all the right tools to recompiled it by myself...

**Comment by denfromufa** [comment]
just get installers from here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet

**Comment by ThiefMaster** [comment]
What about making them available as releases here on GitHub instead of the outdated one from 2006?

**Comment by FredChauviere** [comment]
That would be great @ThiefMaster ! Thkx !
@denfromufa : I've downloaded the package pythonnet-2.0.0.dev1-cp27-none-win32.whl but it doesn't seem to do the trick : now i've got a major crash of QGIS during the "import clr"...

![sans titre](https://cloud.githubusercontent.com/assets/10686956/5901113/b8b319ac-a53d-11e4-89b9-00c802ebe3bb.png)

**Comment by denfromufa** [comment]
1. I do not see outdated binaries from 2006 in this branch on github.
Please give me a link. At least you can get from the link that I provided
or compile with VS locally.
2. What version/bitness Python, Windows, and .NET do you get this error
with QGIS?
3. Does QGIS come with a special version of CPython?
4. Did you try logging your assembly binding:

http://stackoverflow.com/questions/27725122/python-for-net-error-importerror-no-module-named

**Comment by ThiefMaster** [comment]
Ah ok, it was just a [release](https://github.com/pythonnet/pythonnet/releases), without attached binaries.

**Comment by FredChauviere** [comment]
I finally succeed to recompile the Git source with VS2010 - the trickiest part was to obtain the NuGet packages (Rgiesecke.DllExport), but I manage to follow the tutorial (https://www.nuget.org/packages/UnmanagedExports) - : and it works definitely better! Thanks for all your advice @ThiefMaster!

**Comment by FredChauviere** [comment]
@denfromufa : 
We're using Windows 7 32 and 64 bits (depending on the machine), and NET Framework 4.5.1 (and we were trying to update to .NET Framework 4.5.2). We're using QGIS Valmiera 2.2.0 that comes with Python 2.7.8 : it seems to be a standard Python 2.7.8, but I've never ckecked actually...

**Comment by denfromufa** [comment]
what do you see when you type in "python" in command line assuming your
QGIS python is in path?

**Comment by FredChauviere** [comment]
"Python 2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)] on win32"

So my mistake, it doesn't use the Python 2.7.8 installation in C:\Python27, it uses it's own 2.7.4 copy in "C:\Program Files (x86)\QGIS Valmiera\bin" : but it seems to be a genuine unmodified 2.7.4 Python by Python Software Foundation

**Comment by denfromufa** [comment]
are you sure that you installed pythonnet to python in QGIS site-packages,
not python in c:\python27?

Anyway try first appending your sys.path with pythonnet assemblies folder
(clr.pyd and Python.Runtime.dll) if you did not install them.

finally this maybe actually easiest: check you pythonnet folder and run
this executable after building it: nPython.exe

and see if you can "import clr" from this app nPython.exe:

Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32
bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
>>>

**Comment by curzona** [comment]
I got the same error `SystemError: dynamic module not initialized properly` after upgrading from 2.0.18 (internal) to 2.1.0.dev1. 

To fix it, I deleted all the old Python.Runtime.dll and clr.dll from C:\Python27\DLLs and C:\Python27\Lib\site-packages and reinstalled python.NET

**Comment by karbon62** [comment]
Hi, 

I am trying to install pythonnet using the following commands: 
pip install pythonnet==2.1.0.dev1 - and with not luck since I am getting an error: Failed building wheel for pythonnet. 

Can anyone help with this?
