### ISSUE TITLE
PR reviews: reduce requirements

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#610]
I would like to reduce requirements for PR reviews to merge faster the existing and new pull requests:

1. If the pull request is a small bug fix with tests (if applicable), then only **one** (1) core developer review is necessary.
2. If the pull request is a feature or significant change then at least **two** (2) core developers should review.
3. If the pull request is from core developers only **another** (1) core developer review is required unless that reviewer suggests more reviewers.
4. If the pull request is a small bug fix with tests, then this core developer (author of this fix) can merge this without any reviews.
5. In the case of conflicts voting is going to be performed.
6. More PR reviewers without commit rights should be added!
7. Each release is going to have one release manager to manage which PRs should be included.

@filmor @vmuriart @dmitriyse @tonyroberts @brianlloyd @yagweb @Cronan @AlexCatarino @jaredbroad

**Comment by dmitriyse** [comment]
Lets try this new rules!

**Comment by Cronan** [comment]
Sounds good

**Comment by denfromufa** [comment]
I'm going forward with these new rules, since no negative is received!

**Comment by denfromufa** [comment]
Updated in wiki:

https://github.com/pythonnet/pythonnet/wiki/Development-Guidelines

**Comment by denfromufa** [comment]
@lostmsu see requirements above for PRs and commits

**Comment by filmor** [comment]
No idea why you reopened this :)
