### ISSUE TITLE
event.Control as foo in ironpython

### ISSUE THREAD

**Issue by faststare** [pythonnet/pythonnet#611]
### Environment

-   Pythonnet version: latest
-   Python version: 3.6.4
-   Operating System: WinOS

### Details

I like to have an autocomplete textbox in datagridview with editingshowing event handler. in c# event argument in function event.Control can be morph to a textbox with that event. as e.Control as Textbox but in ironpython I received a invalid because I use as keyword in winform expression and not in import expression.
how can I achieve the same functionality of this?
    _TODO_

-   What commands did you run?

python dgv.py
```

-   If there was a crash, please include the traceback here.

file dgv.py line 70
autotext = e.Control as Textbox
SystaxError: unexpected token 'as'
```

**Comment by denfromufa** [comment]
For `as` keyword we need to support this ironpython syntax:

https://stackoverflow.com/a/1440427/2230844

This is part of a bigger meta-issue:

https://github.com/pythonnet/pythonnet/issues/437
