### ISSUE TITLE
readme file argument is incorrect

### ISSUE THREAD

**Issue by bmigette** [pythonnet/pythonnet#618]
Hi,

Readme file is incorrect
mod.func(args, keywordargname=keywordargvalue)
Should be replaced by
mod.func(args, keywordargname: keywordargvalue)

**Comment by denfromufa** [comment]
@bmigette thanks for noticing this! would you like to submit a pull request?

**Comment by bmigette** [comment]
I don't know how to do that exactly, that's why I posted it here :)

**Comment by denfromufa** [comment]
@bmigette you can follow these steps and do this right from github web interface:

https://github.com/WGBH/pbucore/wiki/Contributing-to-the-project-through-Github-web-interface

**Comment by bmigette** [comment]
Ok I think I managed to do it by clicking edit right from the readme file :)

**Comment by denfromufa** [comment]
@bmigette thanks!
