### ISSUE TITLE
Visual Studio 2017: pythonnet 2.3.0-dot is no compatible with new PackageReference in nuget

### ISSUE THREAD

**Issue by msedi** [pythonnet/pythonnet#630]
### Environment

-   Pythonnet version: 35
-   Operating System: Windows 10

### Details

-   When trying to install pythonnet 3.5 using the nuget package manager console or the UI, doesn't  matter which, the package manager tells me the the current version is not comptaible with the .NET framework 4.6.2. I tried it on Visual Studio 2017 and Visual Studio 2017 Preview (both don't work)

Following .NET command line was used in the package manager console and the output is attached.

```
PM> Install-Package pythonnet -Version 2.3.0-py35-dotnet
2017\Projects\ConsoleApp17\ConsoleApp17\ConsoleApp17.csproj...
Install-Package : Package pythonnet 2.3.0-py35-dotnet is not compatible with net462 (.NETFramework,Version=v4.6.2). Package pythonnet 2.3.0-py35-dotnet does not support any target frameworks.At 
line:1 char:1
+ Install-Package pythonnet -Version 2.3.0-py35-dotnet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package pythonnet 2.3.0-py35-dotnet is not compatible with net462 (.NETFramework,Version=v4.6.2) / win. Package pythonnet 2.3.0-py35-dotnet does not support any target 
frameworks.At line:1 char:1
+ Install-Package pythonnet -Version 2.3.0-py35-dotnet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package pythonnet 2.3.0-py35-dotnet is not compatible with net462 (.NETFramework,Version=v4.6.2) / win-x64. Package pythonnet 2.3.0-py35-dotnet does not support any target 
frameworks.At line:1 char:1
+ Install-Package pythonnet -Version 2.3.0-py35-dotnet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package pythonnet 2.3.0-py35-dotnet is not compatible with net462 (.NETFramework,Version=v4.6.2) / win-x86. Package pythonnet 2.3.0-py35-dotnet does not support any target 
frameworks.At line:1 char:1
+ Install-Package pythonnet -Version 2.3.0-py35-dotnet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'ConsoleApp17'.At line:1 char:1
+ Install-Package pythonnet -Version 2.3.0-py35-dotnet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by denfromufa** [comment]
@msedi can you properly format your code according to markdown syntax? the error is not clear. there is nothing special on .net 4.6.2. e.g. still installing with `pip install pythonnet` and see if it makes any difference?

**Comment by msedi** [comment]
@denfromufa enfromufa.

Thanks for telling. I have used mark-up and I hope you can read it better now? I tried pip install pythonnet (some timeout problem), but it seems it doesn't go through our firewall. Nuget in general works on our side and the described error above comes without waiting for anything. If I can help with debugging, just tell me.

**Comment by denfromufa** [comment]
@msedi you can go to pypi and download the wheel package for pythonnet and install it using pip

**Comment by denfromufa** [comment]
https://pypi.python.org/pypi/pythonnet

**Comment by msedi** [comment]
@denfromufa The problem is that there are lot of people working on the project, relying that the nuget package manager does the things for them. Having all the people installing the things manually would make it cumbersome. So it would be nice to find what's causing the problem.

**Comment by denfromufa** [comment]
@msedi this is an open source project, provided free of cost. nuget is secondary source of distribution and already has some other issues. Working with Python and not having access to PyPI seems unreasonable. 

Have you verified that pythonnet installs on older .NET versions and the issue is only with .NET 4.6.2?

**Comment by msedi** [comment]
Yes, I have tried (at least in VS2017) to switched from framework 2.0 up to framework 4.7.1 all of them tell me that it's not compatible. So obviously some people have brought it to work, but I cannot see what's the problem in my case.

And yes, I understand that's an open source project, I was using IronPython before and thought it might beneficial to switch to python.net.

**Comment by denfromufa** [comment]
@msedi this works for me in VS 2017 15.5.7, nuget 4.5.0, so probably the issue is with your project. Are you on x86, x64, or AnyCPU? You should share a demo VS project/solution where this does not work.

```
PM> Install-Package pythonnet -Version 2.3.0-py35-dotnet


Attempting to gather dependency information for package 'pythonnet.2.3.0-py35-dotnet' with respect to project 'ConsoleApp1', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 563.33 ms
Attempting to resolve dependencies for package 'pythonnet.2.3.0-py35-dotnet' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'pythonnet.2.3.0-py35-dotnet'
Resolved actions to install package 'pythonnet.2.3.0-py35-dotnet'
Retrieving package 'pythonnet 2.3.0-py35-dotnet' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/pythonnet/2.3.0-py35-dotnet/pythonnet.2.3.0-py35-dotnet.nupkg
  OK https://api.nuget.org/v3-flatcontainer/pythonnet/2.3.0-py35-dotnet/pythonnet.2.3.0-py35-dotnet.nupkg 215ms
Installing pythonnet 2.3.0-py35-dotnet.
Adding package 'pythonnet.2.3.0-py35-dotnet' to folder 'C:\Users\denis.akhiyarov\source\repos\ConsoleApp1\packages'
Added package 'pythonnet.2.3.0-py35-dotnet' to folder 'C:\Users\denis.akhiyarov\source\repos\ConsoleApp1\packages'
Added package 'pythonnet.2.3.0-py35-dotnet' to 'packages.config'
Successfully installed 'pythonnet 2.3.0-py35-dotnet' to ConsoleApp1
Executing nuget actions took 1.68 sec
Time Elapsed: 00:00:02.4175867
```

**Comment by msedi** [comment]
@denfromufa: Thank you for your help. I have solved it myself, VS2017 has now two possibilities for using either the new PackageReference directly in the project or by using the packages.config. Somehow the new PackageReference does not work, but the packages.config does.

**Comment by denfromufa** [comment]
@msedi great, don't forget to star this project! i edited the title of this issue, in case anyone else hits this problem.

**Comment by lostmsu** [comment]
@denfromufa can we please reopen the issue? The new format for package references is the default one, and is not supported with the new .NET Core SDK.

**Comment by denfromufa** [comment]
@lostmsu we have a separate solution file and setup.py build option for .NET Core. Are you still getting errors with these settings?

**Comment by lostmsu** [comment]
@denfromufa I have not tried referencing from source. Only NuGet version.

**Comment by denfromufa** [comment]
Nuget version is only .NET Framework compatible. .NET Core support for embedding Python is available in the master branch of pythonnet. You can take a look at Appveyor CI and Travis CI for details.
There is no action item here for now.
