### ISSUE TITLE
no module called numpy

### ISSUE THREAD

**Issue by Pipsy100** [pythonnet/pythonnet#633]
I am trying to run the sample code but I am getting the error "No module called Numpy". Where am I going wrong?

using System;
using System.Collections.Generic;
using Python.Runtime;

namespace PythonNet
{
    class Program
    {
        static void Main(string[] args)
        {

            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                dynamic sin = np.sin;
                Console.WriteLine(np.cos(np.pi * 2));
                Console.WriteLine(sin(5));
                double c = np.cos(5) + sin(5);
                Console.WriteLine(c);
                 dynamic a = np.array(new List<float> { 1, 2, 3 });
                // dynamic b = np.array(new List<float> { 6, 5, 4 }, Py.kw("dtype", np.int32));
                 Console.WriteLine(a.dtype);
               //  Console.WriteLine(b.dtype);
               //  Console.WriteLine(a * b);
                dynamic pd = Py.Import("pandas");
                dynamic plt = Py.Import("matplotlib");
            }
                Console.ReadKey();
        }
    }        
 }

**Comment by denfromufa** [comment]
@Pipsy100 did you install numpy?

**Comment by Pipsy100** [comment]
set te Variable but still the problem remains

**Comment by denfromufa** [comment]
Is your Anaconda environment registered in %path% environment variable? Is it the root the environment? What do you have in sys.path?

**Comment by Pipsy100** [comment]
![image](https://user-images.githubusercontent.com/11199750/36667553-88b27340-1aee-11e8-8c1a-e6eb253cb84f.png)

![image](https://user-images.githubusercontent.com/11199750/36667600-acd639c8-1aee-11e8-8bc7-9d433777c273.png)

**Comment by dmitriyse** [comment]
not PYTHON_HOME, but PYTHONHOME="Path\To\Your\Python.exe"

**Comment by Pipsy100** [comment]
![image](https://user-images.githubusercontent.com/11199750/36667829-87c2b6ce-1aef-11e8-8a62-f4fd7ce294e8.png)
![image](https://user-images.githubusercontent.com/11199750/36667846-9a8cf4f4-1aef-11e8-8271-8bb9e1499523.png)
Changed it but same result.

**Comment by denfromufa** [comment]
Are you able to import any package or this is specific to numpy?

**Comment by Pipsy100** [comment]
It is working. Do not know why but suddenly it is.
Thanks very much. Much appreciated

**Comment by denfromufa** [comment]
@Pipsy100 your environment variables probably refreshed upon new app/console session.
