### ISSUE TITLE
Pythonnet in vs 2017

### ISSUE THREAD

**Issue by neurochen** [pythonnet/pythonnet#636]
### Environment

-   Pythonnet version: 2.3
-   Python version: 3.6
-   Operating System: windows 10

### Details
It's my first time using pythonnet. All the tests in python works fine. What I want to achieve is embedding python in c# in visual studio 2017. Could anyone share a basic example for this?

I got the following error: Error	CS0103	The name 'Py' does not exist in the current context	ConsoleApp1. Adding the dll into sys.path, adding into reference are already tested. They didn't help. Thanks.

See code below: 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                Console.WriteLine(np.cos(np.pi * 2));

                dynamic sin = np.sin;
                Console.WriteLine(sin(5));

                double c = np.cos(5) + sin(5);
                Console.WriteLine(c);

                dynamic a = np.array(new List<float> { 1, 2, 3 });
                Console.WriteLine(a.dtype);

                dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
                Console.WriteLine(b.dtype);

                Console.WriteLine(a * b);
                Console.ReadKey();
            }
        }
    }
}

**Comment by denfromufa** [comment]
You need to add reference to Python.Runtime.dll. See example in pythonnet solution called Console project.

**Comment by denfromufa** [comment]
Search the issue tracker or Google for usage with pythonnet of both matplotlib and pyqt. It generally works if you know how the threading works.

**Comment by neurochen** [comment]
Could you please elaborate a bit more? Do you mean GIL status? I googled and searched issue tracker already, but did not find the answer. In my case, I want to embed python in C#. When I use pyqt or matplotlib, it always gave me the error:
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".
Reinstalling the application may fix this problem.
Fatal Python error: auto-releasing thread-state, but no thread-state for this thread

Also, I am wondering if multiprocessing is supported as well. I tested it in embedded python in C#. If I start a child process, it will basically make my c# program looping, with more and more nPython.exe spawned. If you do not start it, everything works fine (like the code below).
    for i in range(2):
        p = Process(target=f, args=('bob' +str(i),));
        #p.start();
        #p.join()

Thank you so much!

**Comment by denfromufa** [comment]
Please open a separate issue with full reproducible example.

**Comment by neurochen** [comment]
For my project, what I need are the following packages: pyqt, matplotlib, pydaqmx, multiprocessing, pyglet. If you could let me know any news related to their compatibility, that would be awesome.

Will open another issue asap. thanks.
