### ISSUE TITLE
comaptibility of multiprocessing in windows 

### ISSUE THREAD

**Issue by neurochen** [pythonnet/pythonnet#639]
### Environment

-   Pythonnet version: 2.3
-   Python version: 3.6 minoconda
-   Operating System: windows 10

### Details

-   Describe what you were trying to get done.

    I used the console example code in the pythonnet, and modified it a little bit to test the capabilities. Please see the code below:
```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Python.Runtime;

namespace Python.Runtime
{
    public sealed class PythonConsole
    {
        static void Main(string[] args)
        {
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                Console.WriteLine(np.cos(np.pi * 2));

                dynamic mp = Py.Import("ProcessIDTest");
                Console.WriteLine(2);
                mp.main();

                Console.WriteLine(3);
            }
        }
    }
}
```
Also the python code named ProcessIDTest.py: 
```python
from multiprocessing import Process
import os, time
def f(name):
	print('Inside f.')

def main():
    for i in range(2):
        p = Process(target=f, args=('bob' +str(i),));
        p.start();
        p.join()
    print('Main function executed.')
    
if __name__ == '__main__':
    main();
```
-   What commands did you run to trigger this issue? If you can provide a
It basically make my c# program looping, with more and more nPython.exe spawned. Commenting p.start() let the program run through, but it's clearly meaningless. 

THANK YOU SO MUCH!

**Comment by denfromufa** [comment]
It appears there may be some issues with multiprocessing for embedded Python. For example try setting sys.argv like suggested here:

https://stackoverflow.com/a/15636687/2230844

**Comment by denfromufa** [comment]
Similar issues with Python embedded in Blender:

https://blender.stackexchange.com/q/8530/53252

**Comment by denfromufa** [comment]
I guess another thing to make sure is that `__name__` is not redefined in child processes, which would cause recursive calls like you experienced:

https://pymotw.com/3/multiprocessing/basics.html

**Comment by neurochen** [comment]
Thanks. Will check it soon.

**Comment by filmor** [comment]
I don't think that this is something we can or should solve inside of Python.NET. Running `multiprocessing` from an embedded Python instance is always tricky business (especially on Windows) and workarounds were given. Thanks for bringing this to our attention, though :)

**Comment by Yasirsmb** [comment]
Hi, anyone has found the solution to this problem? Please help me too. I have winform application and calling python code which uses multiprocessing. when this code execute it creates multiple child windows of winform
