### ISSUE TITLE
comaptibility of pyqt and its derivatives in windows 

### ISSUE THREAD

**Issue by neurochen** [pythonnet/pythonnet#640]
### Environment

-   Pythonnet version: 2.3
-   Python version: 3.6 minoconda
-   Operating System: windows 10

### Details

-   Describe what you were trying to get done.
    I used the console example code in the pythonnet, and modified it a little bit to test the capabilities. Please see the code below:
```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Python.Runtime;

namespace Python.Runtime
{
    public sealed class PythonConsole
    {
        static void Main(string[] args)
        {
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                dynamic plt = Py.Import("matplotlib.pyplot");
                dynamic exp = Py.Import("pyqtgraph.examples");
                Console.WriteLine(np.cos(np.pi * 2));
                plt.plot(np.cos(np.pi * 2));
                exp.run();

                Console.WriteLine(3);
            }
        }
    }
}
```
-   What commands did you run to trigger this issue? If you can provide a
    If you run the code directly in vs2017, the following error was given, which is related to pyqt.
```
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "". Reinstalling the application may fix this problem. 
Fatal Python error: auto-releasing thread-state, but no thread-state for this thread. 
```
I already tried reinstall my python and it's still the same problem. Also I tested all the matplotlib backends, with only TkAgg working fine. Pyqt, tested with pyqtgraph, aslo didn't work in PythonEngine as well. The same error was produced.

THANK YOU SO MUCH!

**Comment by constructor-igor** [comment]
@neurochen I have a same problem.
Do you have any solution or workaround?

**Comment by denfromufa** [comment]
Has anyone tried without conda/miniconda/anaconda, just using vanilla cpython and wheels from pypi? Anaconda is not really a good target for embedding with pythonnet.

**Comment by filmor** [comment]
This could be because of the old way how we hooked into Python's import system. With the new system, this should not be an issue anymore. Please comment if the issue persists on the current master version.
