### ISSUE TITLE
Crash of frozen application that imports another compiled module

### ISSUE THREAD

**Issue by vashek** [pythonnet/pythonnet#645]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
-   cx-Freeze version: 5.1.1
-   Operating System: Windows 10 64bit

### Details

Trying to freeze a Python program using cx_Freeze. Program works when run from source but crashes with "SystemError: initialization of clr did not return an extension module" when run as .exe file.
I found this happens when the program imports another C Python extension (.pyd file) in addition to clr.

If I remove the "import psycopg2" line from the minimal example below, there is no crash. If I replace it with "import re", there is no crash. If I replace it with "import servicemanager, win32serviceutil, win32service" (modules from win32all - that was my original intention before starting to investigate what causes the issue), I get the same crash.

-   What commands did you run to trigger this issue?

pynettest.py:
```
import clr
import psycopg2

if __name__ == "__main__":
    print("imported")
```

setup.py:
```
import glob
import os
import os.path
import sys
from cx_Freeze import setup, Executable

foundDlls = [glob.glob(os.path.join(x, "Python.Runtime.dll")) for x in sys.path]
firstFoundDll = [x for x in foundDlls if x][0][0]


PACKAGE_NAME = "pynettest"

setup(  name = PACKAGE_NAME,
        version = "1.0",
        options = {"build_exe": {"include_msvcr": True,  # "packages": ["idna"],
            "include_files": [(firstFoundDll, os.path.join("lib", os.path.basename(firstFoundDll)))],
            "zip_include_packages": "*", "zip_exclude_packages": "", "excludes": ["tkinter"]}},
        executables = [Executable("pynettest.py")],
        requires=["cx_Freeze", "pywin32", "pythonnet"],
        py_modules=("pynettest",),
        )
```

Build by:
```
py -3 setup.py bdist
```

-   If there was a crash, please include the traceback here.
Result of running pynettest.exe:
```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Program Files\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "pynettest.py", line 1, in <module>
SystemError: initialization of clr did not return an extension module
```

**Comment by denfromufa** [comment]
@vashek have you tried pyinstaller instead of cx_freeze?

this is an error from cpython interpreter:

https://github.com/python/cpython/blob/9974e1bcf3d0cec9b38b39b39b7ec8a1ebd9ef54/Python/importdl.c#L210

**Comment by vashek** [comment]
No. If you think it might help, I'll try it eventually. You think it might be a bug in cx_Freeze? (I've never seen such issues with other modules, but I suppose anything's possible.)

**Comment by karthikeyanPalanisamy** [comment]
@vashek have you tried with pyinstaller? as suggested by @denfromufa .

i'm getting the same error for my application with pyinstaller 3.3.1.

**Comment by denfromufa** [comment]
With pyinstaller you can pass a flag to get a detailed initialization logging:

http://pyinstaller.readthedocs.io/en/stable/spec-files.html#giving-run-time-python-options

**Comment by vashek** [comment]
Oh, yes, sorry, I fixed it by switching to pyinstaller as well.

**Comment by denfromufa** [comment]
ok, great, so closing this issue!
