### ISSUE TITLE
Indexers not working

### ISSUE THREAD

**Issue by pl6306** [pythonnet/pythonnet#646]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:21:59) [MSC v.1900 32 bit (Intel)]
-   Operating System: Windows 7

### Details

-   Describe what you were trying to get done.

    Access Excel via Runtime Wrapper through the CLR. Looks like Indexed properties don't work because it doesn't show up. Any property that has an indexer doesn't get bound properly. However all the other properties and methods seem to work. Is there a work around?

-   What commands did you run to trigger this issue? If you can provide a

     import Microsoft.Office.Interop.Excel as Excel
     app = Excel._Application(PyAddin.CurrentInstance.ExcelApp)

     app.Range
     AttributeError: '_Application' object has no attribute 'Range'

**Comment by denfromufa** [comment]
There is an open issue on github for COM interop with pythonnet. This is
because COM interop has a special handling in .NET dynamically at runtime.

There is also an ugly workaround using reflection:

https://github.com/pythonnet/pythonnet/issues/72

**Comment by denfromufa** [comment]
closing, since this is duplicate
