### ISSUE TITLE
nuget package embedding issue

### ISSUE THREAD

**Issue by user015** [pythonnet/pythonnet#647]
nuget packages 
a) 2.3.0-py35-dotnet
b) python 3.5.4  (64 bit).

I was able to get install both nuget packages. This pythondotnet package seems to look for a python35.dll, So I had to install 3.5.4.  This is a 64 bit project targetting .NET 4.5

I set the path variables both PythonHome and PythonPath.

The code just abruptly exits at the Py.GIL() line, I tried looking at nuget issues here but no luck.

Code Snipped below

            PythonEngine.PythonHome = @"..\..\..\..\packages\Python.3.6.2\tools\";
            PythonEngine.PythonPath = @"..\..\..\..\packages\Python.3.6.2\tools\";
           
            using (Py.GIL())   ----> code Exits here with error code 3.

If I debug the PythonEngine variable, I see that it has the correct path and picks up the correct version and there is a error message under delegatemanager, which says delegate manager has not been initialized.  
I tried to use the PythonEngine.Initialize() method  and the progam Exits.  
What could the issue be here ?

Thanks

**Comment by denfromufa** [comment]
@user015 you need to pick 64-bit of python.runtime.dll from nuget installation manually:

https://github.com/pythonnet/pythonnet/issues/472

**Comment by user015** [comment]
I did that already. it was initially 32 bit but I picked up 64 bit manually.

**Comment by denfromufa** [comment]
In one place you show python 3.5, in another it is python 3.6

**Comment by user015** [comment]
my bad,  I pasted a older copy.  I am using 3.5.4 as shown below.

              PythonEngine.PythonHome = @"..\..\..\..\packages\Python.3.5.4\tools";
            PythonEngine.PythonPath = @"..\..\..\..\packages\Python.3.5.4\tools";

As I wrote earlier, the error I see when I debug PythonEngine is this 

base {System.SystemException} = {"DelegateManager has not yet been initialized using Python.Runtime.PythonEngine.Initialize()."}

**Comment by user015** [comment]
![image](https://user-images.githubusercontent.com/11019208/37685508-bcaed4d4-2c61-11e8-8903-b27505e9614d.png)

**Comment by denfromufa** [comment]
Can you try regular CPython installation, not the nuget package for it?

I don't think anyone tested this nuget CPython package with pythonnet.

**Comment by user015** [comment]
OK nuget package does not seem like a good option now. Also the nuget package for pythonnet seems to look for older version of python3.5.5 (python35.dll)  as well.  I was looking at this for distribution purposes, will go back to the regular setup. Thanks for all your help @denfromufa.

**Comment by lostmsu** [comment]
The latest versions of NuGet package now work with any supported Python version.
