### ISSUE TITLE
clr interfering with filedialog.askdirectory

### ISSUE THREAD

**Issue by mmsturgill** [pythonnet/pythonnet#648]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6 ( Anaconda)
-   Operating System: Win 10 1703

### Details

after importing clr filedialog.askdirectory hangs unless it was run before the import. Here is a code that can triggers this:
```python
import sys
import tkinter.filedialog
#path1 = tkinter.filedialog.askdirectory()
import clr
path2 = tkinter.filedialog.askdirectory()
```

if the line 3 is commented out ( the one with path1 ) then  then the askdirectory on line 5 hangs. if the line 3 is uncommented then the ask directory on line 5 does not hang. 

Interestingly enough other file dialogs do not hang, only the directory one.

**Comment by denfromufa** [comment]
Tk is python code, so you may be able to debug where the hanging/deadlock
occurs.

https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Lib/tkinter/filedialog.py#L426

**Comment by mmsturgill** [comment]
I have tried chasing it in the debugger. Unfortunately the issue occurs in tkinter\commondialog.py line 43 where the tkinter drops to tk interpreter. That's where the deadlock seems to occur.

**Comment by constructor-igor** [comment]
Next code works under PyCharm 2018.1 and stuck when it run from python command line (Windows 7).
Without ```import clr``` the code works as expected.
Could you suggest a work-a-round or possible ways to investigate/fix the issue?
What possible conflict ```import clr``` with ```askdirectory```?

```python
import clr #pythonnet 2.3.0
import tkinter as tk
from tkinter.filedialog import (askdirectory, askopenfilename)

print("start")

root = tk.Tk()
root.withdraw()
selected_path = askdirectory(title="Please select your installation folder location", initialdir=r"C:\Program Files\\")
print("selected path: ", selected_path)

print("finish")
```

**Comment by Bacon-Tech** [comment]
I have tested this on python 3.6.2 and the code works as exspected from my IDE (Eclipse) and from windows 7 pro cmd.

**Comment by denfromufa** [comment]
@constructor-igor it appears this answer in SO is satisfactory, feel fee to comment back if there is any remaining problem in pythonnet:

https://stackoverflow.com/a/50446803/2230844
