### ISSUE TITLE
Pythonnet output strings become garbled

### ISSUE THREAD

**Issue by AlexanderHuang** [pythonnet/pythonnet#650]
### Environment

-   Pythonnet version: V2.3.0
-   Python version: Python36_64 
-   Operating System: Windows 10 Pro ( English version )

### Details

-   Describe what you were trying to get done.

    I build a simple example to use Python.Runtime library. The code is from pythonnet GitHub site. so it should be no problem. However, the output strings become garbled. At first I thought it could be because my OS is Traditional Chinese Windows. But I setup  an English version Windows, the output is still the same. Here is my code and output screenshot. I will be grateful if there is some clue so i can fix this. 

![screen shot 2018-03-27 at 2 55 51 pm](https://user-images.githubusercontent.com/5988310/37951712-fbc1cb18-31cf-11e8-94fd-1d8c3affad2b.png)

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by denfromufa** [comment]
Where did you get pythonnet installation from?

**Comment by AlexanderHuang** [comment]
I use GitHub Desktop to download it.

**Comment by denfromufa** [comment]
How did you install/build pythonnet?

See the troubleshooting wiki:

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX

**Comment by AlexanderHuang** [comment]
i  use DebugMonoPY3 configuration to build the project successfully, is it right?
![screen shot 2018-03-28 at 10 59 03 am](https://user-images.githubusercontent.com/5988310/38006393-6ad7abd8-3277-11e8-8936-04fe49b270b4.png)

**Comment by denfromufa** [comment]
Read the installation and troubleshooting wiki, you are doing it wrong.
Building in VS is for expert users, just install the pythonnet wheel with
pip.

**Comment by AlexanderHuang** [comment]
got it. Thank you.

**Comment by denfromufa** [comment]
@AlexanderHuang i presume your issue got resolved. closing this issue.
