### ISSUE TITLE
It doesn't work with Stackless-Python

### ISSUE THREAD

**Issue by NikitinAlexandr** [pythonnet/pythonnet#651]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6.4 Stackless (64 bit)
-   Operating System: MS Windows 7 Pro (Russian)

### Details

-   When I try to do anything (add reference, for example), then "unhandled exception" rise:

![error](https://user-images.githubusercontent.com/15609359/37974766-5c715256-31e6-11e8-96bb-c220a4e57711.png)

Without Stackless all works well.

**Comment by NikitinAlexandr** [comment]
I see. Thanks

**Comment by denfromufa** [comment]
closing since this is likely not feasible
