### ISSUE TITLE
best way to convert ndarray to a .net 

### ISSUE THREAD

**Issue by user015** [pythonnet/pythonnet#652]
Is there a efficient way to convert numpy.ndarray to a .net object (array/list) ? I have a 2D ndarray that is pretty massive 1500 *2000, is there a efficient way to convert to .net 

Also this pythonnet package has helped me greatly, thanks for all your efforts in developing and maintaining it!

**Comment by denfromufa** [comment]
@user015 see suggestions here: https://github.com/pythonnet/pythonnet/issues/514

**Comment by dmitriyse** [comment]
In CoreCLR 2.1 we have Span API so I think is could be many times faster approach.

**Comment by denfromufa** [comment]
@dmitriyse that's what I was thinking too, but the suggestion i linked above was good enough for me.

**Comment by user015** [comment]
I tried a couple of the approaches in that link and they didn't work for me. I am guessing I have a ndarray(2D) vs a single D array is the issue.  I haven't tried the pure python solution at the very end, but either way I think I can get around this. Thanks!

**Comment by Kemsekov** [comment]
I've added answer alongside with Robert McLeod for c# side

https://github.com/pythonnet/pythonnet/issues/514#issuecomment-1877440282
