### ISSUE TITLE
sklearn model 

### ISSUE THREAD

**Issue by sam0458** [pythonnet/pythonnet#656]
### Environment

-   Pythonnet version: 2.4.0.dev0
-   Python version: 3.5.4
-   Operating System: Windows 10

### Details
#I would like to use sklearn library from C# and started with the following example of linear regression
# in sklearn
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)

# in pythonnet and C#
#using  Py.GIL() and Python.Runtime
#When I ran 

dynamic sk1 = Py.Import("sklearn.linear_model");
sk1.LinearRegression.fit(X_train, Y_train);

#I had the following error:  Python.Runtime.PythonException: 'TypeError : fit() missing 1 required positional argument: 'y''
#It seems that I did not run the constructor of the class LinearRegression()
#How to do this?

**Comment by denfromufa** [comment]
try `sk1.LinearRegression().fit(X_train, Y_train)`

**Comment by sam0458** [comment]
Thanks. It works.
