### ISSUE TITLE
Compiled project crashes when frozen with cx_freeze

### ISSUE THREAD

**Issue by kelvinomolumo** [pythonnet/pythonnet#66]
Machine specs:
Windows 7 64bit
Python 2.7 32bit
.Net Framework 4.5.2

I download the repo for pythonnet and built the project using ReleaseWin on platform x86 using visual studio 2012.
pythonnet works fine but once i freeze the app using cx_freeze the app crashes.

It worked well with the source forge version but fails on windows 8 and 8.1.

After googling around i found that building the repo using x86 solves the problem.

Please anyone knows a fix ?

**Comment by jfbramboll** [comment]
I'm getting the exact same error as here: http://stackoverflow.com/questions/26110026/pyinstaller-and-pythonnet-clr

I've tried cx_freeze, py2exe and pyinstaller. I'm using Python 2.7 64bit, Windows 7 64bit. and I have a bunch of .Net frameworks installed, including 4 and 4.5.

Is it at all possible to create an exe that using python.net?

**Comment by denfromufa** [comment]
@jfbramboll @kelvinomolumo PyInstaller should provide a hook to include pythonnet:

https://github.com/pyinstaller/pyinstaller/issues/637

it is reported working for people here:
https://groups.google.com/forum/#!topic/pyinstaller/juS48yx3XyE

I am not sure about cx_freeze

**Comment by denfromufa** [comment]
pyinstaller has been updated to include proper clr (pythonnet) hook:

https://github.com/pyinstaller/pyinstaller/issues/1801

**Comment by konstantin-popov** [comment]
In order to stop crashing with cx_freeze you need to manually add `Python.Runtime.dll` file from `pythonnet` package to your binary directory.

**Comment by denfromufa** [comment]
@konstantin-popov does cx_freeze allow configuring hooks for various packages so that this works by default?

**Comment by konstantin-popov** [comment]
Not sure, but I think it does, looking at this: https://github.com/anthony-tuininga/cx_Freeze/blob/master/cx_Freeze/hooks.py

**Comment by denfromufa** [comment]
@konstantin-popov feel free to submit a pull request to cx_freeze to implement this hook based on pyinstaller implementation. We cannot do anything about this in pythonnet without breaking a lot of code.

https://github.com/anthony-tuininga/cx_Freeze/issues/249

**Comment by konstantin-popov** [comment]
>We cannot do anything about this in pythonnet without breaking a lot of code.

Sure. My reply was not a call to action, only a recipe how to deal with this specific problem - actually not with patching cx_freeze, but with adding a file to build using configuration options ([option 'include_files'](http://cx-freeze.readthedocs.io/en/latest/distutils.html#build-exe)).

The ticket you mentioned is actually about a different problem - failing to import custom .NET libraries in frozen app.

**Comment by denfromufa** [comment]
@konstantin-popov you need to update sys.path in order to custom load your .NET assemblies. See fairly complicated example here:

https://github.com/pythonnet/pythonnet/issues/325

**Comment by konstantin-popov** [comment]
I do update sys.path and `clr.AddReference('customlib')` throws no exceptions - the problem appears later in code when importing the assembly.
I guess pythonnet hooks into python import system to load .NET assemblies, but after freezing the app with cx_freeze in doesn't work for some reason.

**Comment by vmuriart** [comment]
Is there a traceback available?

**Comment by denfromufa** [comment]
@konstantin-popov minimum reproducible example would be handy. Also make sure that your library does not reference other custom assemblies, maybe even during runtime.

**Comment by konstantin-popov** [comment]
> Also make sure that your library does not reference other custom assemblies, maybe even during runtime.

That was exactly the thing. The library was external so I didn't guess it referenced somethine else. Thanks @denfromufa!

P.S.  [PR with a hook for pythonnet in cx_freeze](https://github.com/anthony-tuininga/cx_Freeze/pull/251)

**Comment by anthony-tuininga** [comment]
Pull request merged.

**Comment by denfromufa** [comment]
@jfbramboll @kelvinomolumo can you please verify that the pythonnet hook is now working in cx_freeze? @anthony-tuininga @konstantin-popov thanks for implementing this!

Anyway if any issues come up we can reopen this issue.
