### ISSUE TITLE
Pythonnet - Help interacting with new virtual environments (pyvenv)

### ISSUE THREAD

**Issue by anto0ine** [pythonnet/pythonnet#661]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.5 
-   Operating System: Win 10 

### Details

Hi, 

I have created a virtual environment (using pyvenv) with only the packages required for my python code to run. 

I've removed some of the packages from the root python environment to make sure that my python codes run in the new virtual environment but not in the root python environment. 

All of these i can do from the command prompt without issues. 

My issue is that i can't seem to find a way to make pythonnet to use and activate my new virtual environment so it can load all packages but instead it seems that it uses the root environment and fails to run my python code. 

The reason i am doing this is because i could have a number of python scripts which use different versions of the same dependency so i am creating virtual environments which i would like to make pythonnet to load before i run the various python scripts and have them side by side. 

All the above in the scenario that i am embedding pythonnet within C# code.

Is that feasible? Has anyone faced a similar scenario?

Thanks, Antonis.

**Comment by denfromufa** [comment]
Search the issue tracker, there are multiple solutions. For example, set
path and pythonhome environment variables to point to your virtualenv. Also
you should take care yourself the activation of this virtualenv.

Note that some packages such as ctypes use registry keys to locate python
version and then this breaks really badly if your environments have
different python runtimes. I found this the hard way.

**Comment by denfromufa** [comment]
closing for now, report back if any issue
