### ISSUE TITLE
memory de-allocation

### ISSUE THREAD

**Issue by user015** [pythonnet/pythonnet#663]
I am embedding pythonnet in my .NET application.  This is a multi-Threaded application. I am processing some data in a loop, the calculation results in big 2D arrays...something along 1500 x 2000 double arrays. 

At the end of each loop once I am done with the array I delete the array using PythonScope.Remove("varname") method. However I see that memory is never released and very soon I am running into multiple Gig of RAM consumed.  I tried invoking the gc in python using gc.collect(), that didnt help either. 

I am using the same scope variable for the entire loop duration. Found this after doing some profiling, multiple instances of Python.Runtime.CLRObject, keep the references alive, thus prohibiting GC.

What am I missing ?
```

**Comment by user015** [comment]
Thank a lot @denfromufa  calling dispose method did the magic.  Was pointing a dynamic variable (python object) to null  after I was done with it and GC was not collecting it, but calling dispose on the dynamic variable made all the difference!!

**Comment by denfromufa** [comment]
closing, since we already have the linked open issue
