### ISSUE TITLE
str() failure when C# ToString() return unicode character

### ISSUE THREAD

**Issue by EcmaXp** [pythonnet/pythonnet#666]
### Environment

-   Pythonnet version: 2.4.0.dev0 (master; #19d854c)
-   Python version: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
-   Operating System: Windows 10 Pro 64 Bit (1803; 17134.5)

### Details

-   Describe what you were trying to get done.

1. Just call `str` python built-in function with C# class
2. Raise UnicodeDecodeError if value is `안녕`
3. Return `안녕PADD` if value is `안녕PADDINGX"

It seems like failure str convert with ToString() function only.
(Another method, nor read value does not problem)

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```c#
namespace Hello
{
    public class World
    {
        public string value = "안녕";

        public string GetString()
        {
            return value;
        }

        public override string ToString()
        {
            return value;
        }
    }
}
```

```python
import clr
clr.AddReference("hello")
from Hello import World
world = World()
print(1, str(world.value))
print(2, str(world.GetString()))
print(3, str(world))
```

-   If there was a crash, please include the traceback here.

```python
1 안녕
2 안녕
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    str(hello)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: unexpected end of data
```

**Comment by yagweb** [comment]
It's a bug of the PyString_FromString method in runtime.cs, refer to #662

**Comment by EcmaXp** [comment]
https://github.com/EcmaXp/execlib/blob/master/gen_lib/PyExcelLibrary/Excel.cs#L14-L33

Because, `PyString_FromStringAndSize` python c api accept the bytes length, not string length.

**Comment by denfromufa** [comment]
@EcmaXp pull requests are welcome!

**Comment by EcmaXp** [comment]
@denfromufa I can't build this repo, how can i build?

**Comment by filmor** [comment]
The fix for this has been merged to master, so I'll close this. Feel free to reopen if the version in the master branch doesn't solve the issue.
