### ISSUE TITLE
Pythonnet version: 2.3.0.0   .Net Windows service  (Py.GIL())  crash

### ISSUE THREAD

**Issue by lucasnaidero** [pythonnet/pythonnet#667]
### Environment

-   Pythonnet version: 2.3.0.0
-   Python version: 3.6.4
-   Operating System: Windows 10

### Details

I wrote the following code that  initialize the execution of Python code in a library written in c#:
 
    dynamic ailFile = null;
    dynamic aoProcessor = null;

     public int InitPython() 
     {
         try
         {
             if (aoProcessor == null)
             {
                 using (Py.GIL())
                 {
                     // path import
                     dynamic oSYS = Py.Import("sys");
                     oSYS.path.insert(0, processParams.py_script_path);
                     ailFile = Py.Import(processParams.py_script_name);
                     aoProcessor = ailFile.ModelUser(processParams.py_model_name);
                  }
                 if (!PythonEngine.IsInitialized)
                 {
                     PythonEngine.Initialize();
                 }
             }
         }
         catch (Exception ex) {
             return -1;
         }
         return 0;
     }

If I use the library in a .NET Form the execution terminate correctly and all the works are done 
If I Use the library in a .Net Windows service the windows service crash tring to execute the following line:

     using (Py.GIL())

In the event viewer I have the following error message:

```
Faulting application name: VsProcessorIscSvc.exe, version: 1.0.0.840, time stamp: 0x5af2a99e
Faulting module name: ucrtbase.dll, version: 10.0.17134.1, time stamp: 0x587decd7
Exception code: 0xc0000409
Fault offset: 0x000000000006e75e
Faulting process id: 0x3af0
Faulting application start time: 0x01d3e7adec575ce6
Faulting application path: E:\CommesseLocali\2013\13072 New\VsServices_brench\VsProcessorIscSvc\VsProcessorIscSvc\bin\x64\Debug\VsProcessorIscSvc.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: f2d2b68c-3df7-49a5-aa9b-488c1d34a0fa
Faulting package full name: 
Faulting package-relative application ID: 
```

What is wrong?
Thanks

**Comment by denfromufa** [comment]
@lucasnaidero how are you running ".Net Windows service"? I suggest to create a memory dump for this crash and load/debug it in Visual Studio.

**Comment by filmor** [comment]
This has been open without any new information for quite a while, one thing that is quite obviously wrong is that you try to get the GIL before calling `PythonEngine.Initialize`. Try doing the initialisation first, if it doesn't work out, reopen the issue.

**Comment by denfromufa** [comment]
@filmor Py.GIL syntactic sugar should call initialize if the PythonEngine is not initialized

**Comment by filmor** [comment]
I don't think so. It's perfectly valid to require explicit initialisation, also, if we add it to `Py.GIL`, we'd need to add the check everywhere.

**Comment by denfromufa** [comment]
@filmor here is what I meant:

**Comment by denfromufa** [comment]
@filmor here is what I meant:

https://github.com/pythonnet/pythonnet/blob/3eb7e58f94881fe1118e510b8ec2faf2ecdb3f5f/src/runtime/pythonengine.cs#L536
