### ISSUE TITLE
Pythonnet for Linux sles11

### ISSUE THREAD

**Issue by wjobran** [pythonnet/pythonnet#668]
### Environment

-   Pythonnet version: latest master
-   Python version:
-   Operating System:

### Details

-   Is there a PythonNet version compatible with Linux SLES11, when trying to work with lates branch Im getting   import clr
ImportError: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by .Anaconda/lib/libglib-2.0.so.0)

-   I downloaded latest anaconda, installed pythonnet latest branch with pip , succeeded to run at sles12, but failing with sles11.

-   Crash : getting   import clr
ImportError: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by .Anaconda/lib/libglib-2.0.so.0)

**Comment by denfromufa** [comment]
@wjobran you should either contact/search Anaconda or SLES forums/support. This does not seem to be related to pythonnet. glibc is not controlled by pythonnet.

**Comment by denfromufa** [comment]
For anyone looking at this issue, please use vanilla Python or Linux distributions that come with newer glibc.

Upgrading glibc may break a lot of things.
