### ISSUE TITLE
Call C# polymorphic functions

### ISSUE THREAD

**Issue by seagochen** [pythonnet/pythonnet#669]
### Environment

-   Pythonnet version: 2.3
-   Python version: 3.6.5
-   Operating System: Windows 10 Pro x64

### Details

-  Describe what you were trying to get done.

I have a C# class file it contains a lot of Polymorphic functions, here a piece of code of C# side for example.

```csharp
	public static class Logger
	{
		public static void Message(Priority priority, string title, string message, Exception e);
		public static void Message(Priority priority, string title, string message);
		public static void Message(Priority priority, string message, Exception e);
		public static void Message(Priority priority, string message);
	}
```

Now I've implemented a function and let my python code can refer those function. 

```python

	def message(priority = None, title = None, message = None, exception = None): # line 59
	    logger = loadExt.get_csharp_logger()                                      # line 60
	    if priority is None:                                                      # line 61
	        pass                                                                  # line 62
	    if title is None and exception is None:                                   # line 63
	        logger.Message(priority, message)                                     # line 64
	        pass                                                                  # line 65
	    if title is None and exception is not None:                               # line 66
	        logger.Message(priority, message, exception)                          # line 67
	        pass                                                                  # line 68
	    if title is not None and exception is None:                               # line 69
	        logger.Message(priority, title, message)                              # line 70
	        pass                                                                  # line 71
	    logger.Message(priority, title, message, exception)                       # line 72

```

So I've wrote another code to test this function, and hope works well. And Oops...

```
	PS C:\Users\Orlando Chen\Desktop\PythonTester> python .\polygon_test.py
	Traceback (most recent call last):
	  File ".\polygon_test.py", line 5, in <module>
	    logger.message(priority = Priority.INFO, message = "test message" )
	  File "C:\Users\Orlando Chen\Desktop\PythonTester\Polygon\Basics\Logger.py", line 64, in message
	    logger.Message(priority, message)
	TypeError: No method matches given arguments
	PS C:\Users\Orlando Chen\Desktop\PythonTester>
```

I guess, this is so called function polymorphism causes this problem, because Python does not support this feature as far as I know. 

Is there any idea or solution to handle it?

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by seagochen** [comment]
Yes, Priority is a enum type, it seems that enum type in Python has some differences to C# and not properly works, so I've used integer instead and works well. However, when calling the polymorphic functions  it still occurs that TypeError. Thanks for your reply, and I will continue narrow down this error.

**Comment by nitinkumar29** [comment]
Hi,
Any updates on the issue above.

**Comment by heartacker** [comment]
my two functions can not be recognizabled by python？
        Byte[] ReadBytes(UInt16 addr, UInt16 count); 
        Byte[] ReadBytes(UInt16[] addrs);
Is there any good way to solve this problem?
thx

**Comment by lostmsu** [comment]
The enums bug have been solved. We also improved "No method matches given arguments" to include more information.

For anything else, please open a new issue.
