### ISSUE TITLE
COM not working as expected

### ISSUE THREAD

**Issue by tymokvo** [pythonnet/pythonnet#675]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6
-   Operating System: Win10

### Details

-   Trying to get access to a `dynamic` typed `System.__ComObject`
-   This is also specifically with the application Rhinoceros 6 which is using a C++ app that is hosted on .NET so it is a very specific use case
-   However, it does work in IronPython and in C#

```python
import clr
import System
apptype = System.Type.GetTypeFromProgID("Rhino.Application")
rhino = System.Activator.CreateInstance(apptype)
rhino.Visible = 1
plugin = rhino.RunScript("_-SampleCsRhinoCommand", 0)
```

![iron_vs_dotnet](https://user-images.githubusercontent.com/12144028/40387628-2341c486-5dc2-11e8-922c-2316b8134187.PNG)

Also seems odd that `rhino.Visible = 1` does not throw an `AttributeError`, but also doesn't make the application visible.

Thanks!

**Comment by denfromufa** [comment]
this is tracked here:

https://github.com/pythonnet/pythonnet/issues/260
