### ISSUE TITLE
PyObject.GetHashCode overflow bug

### ISSUE THREAD

**Issue by GSPP** [pythonnet/pythonnet#676]
`PyObject.GetHashCode()` can throw an OverflowException because `IntPtr.ToInt32()` does throw. See https://github.com/pythonnet/pythonnet/blob/b8cb6c498ff48bc45643751e05eeddf1b97f8b06/src/runtime/pyobject.cs#L912. I suggest fixing this by xoring the high and low parts of that IntPtr together. Like this:

    var ulongVal = (ulong)ptr;
    return (int)((uint)ulongVal ^ (uint)(ulongVal >> 32));

This happened to me when inserting into a dictionary using tensorflow objects as keys:

    new Dictionary<dynamic, dynamic>() { { x, 1.0 }, { y, 1.0 }, }

### Environment

-   Pythonnet version: 2.3
-   Python version: 3.5
-   Operating System: Windows 7

**Comment by filmor** [comment]
Yes, please, can you prepare a PR for this?

**Comment by GSPP** [comment]
I don't have the project set up. I can submit a blind untested PR if that helps.

**Comment by filmor** [comment]
Sure, go ahead. It's anyways tricky to write tests for this as you need both a 64bit system and reliably force allocation above 2^32 for this patch to make a difference.

**Comment by GSPP** [comment]
The PR is there. Some build stuff failed. I have no idea what it means. I compiled and ran tests locally.
