### ISSUE TITLE
Can not use 'importlib.import_module("dotNetDll")' to dynamically import .net DLL (module)

### ISSUE THREAD

**Issue by yangbo** [pythonnet/pythonnet#678]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6.2
-   Operating System: Windows 10 Home Edition 64bit
-   .Net Framework: 4.5

Pyhtonnet was installed by 'conda install -c pythonnet pythonnet '

### Details

-   I am try to dynamically load a .net dll as module in python3.6.
    I have a .net DLL file in 'd:/dll/DotNetDLL.dll', which has a namespace 'DotNetDLL', under that is a class named 'FileHelper'.
    I want to load the DLL and use class FileHelper in python.
    I can successfully import the DLL like below snippet.

```python
    import clr
    sys.path.insert(0, 'd:/dll/')
    clr.AddReference('DotNetDLL')
    from DotNetDLL import FileHelper
    obj = FileHelper()
```

    But I want to dynamically import the DLL (module), so I use `importlib.import_module` as below.

```python
    import clr
    sys.path.insert(0, 'd:/dll/')
    dll_name = 'DotNetDLL'
    clr.AddReference(dll_name)
    func_module = importlib.import_module(dll_name)
    the_class = getattr(func_module, 'FileHelper')
    obj = the_class()
```

    Python run failed and report : 

```python
Traceback (most recent call last):
  File "D:/projects/integrate/code/jc_exe/bin/cit.py", line 101, in <module>
    main(args)
  File "D:/projects/integrate/code/jc_exe/bin/cit.py", line 51, in main
    ret = call_func(args)
  File "D:/projects/integrate/code/jc_exe/bin/cit.py", line 31, in call_func
    func_module = importlib.import_module(dll_name)
  File "F:\anaconda3\envs\jcpt\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'DotNetDLL'
```

How can I fix the issue? Any idea, thanks!

**Comment by filmor** [comment]
This is because currently (until someone has the time to rewrite it), importing .NET modules is realised by hooking into `__import__` directly. If you use that function it should work.

**Comment by filmor** [comment]
This should be fixed now.

**Comment by PinkShnack** [comment]
Thanks for replying, will do! And looking forward the new version :)
