### ISSUE TITLE
.ToString() compatability with IronPython

### ISSUE THREAD

**Issue by yuvval** [pythonnet/pythonnet#68]
Hi,

I tried to run an IronPython code with python for .Net

the place it failes is demonstrated with:

x = 22
x.ToString()

on IronPython the results is
'22'

on python for .net, an exception is raised:
AttributeError: 'int' object has no attribute 'ToString'

Any way to solve this issue? (importing clr doesn't help)

Thanks!

**Comment by tonyroberts** [comment]
Python integers don't have a ToString method. Python for .NET allows you to import .NET assemblies into cPython, it doesn't do anything to the native Python types.

The nPython interpreter is a cPython interpreter, it is not running Python code in the CLR. The int in your example is a plain python int, not a .net integer. In Python to convert an int to a string you can use the 'str' function.

**Comment by yuvval** [comment]
Thanks.
That what I thought, but I was hoping I to be wrong.

**Comment by tonyroberts** [comment]
You can construct .net integer types using python for .net, if you need to:

import clr
import System

x = System.Int32(22)
x.ToString()

Maybe that helps?

**Comment by yuvval** [comment]
Thanks.

I just manually updated the code to use '{}'.format(x).

My question was in order to understand the compatibility between iPython
and nPython.
