### ISSUE TITLE
How to implement __repr__ for a C# class to be used in python.net?

### ISSUE THREAD

**Issue by AlexArcPy** [pythonnet/pythonnet#680]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 2.7
-   Operating System: Windows 10

### Details

I have a C# class library which I use in Python. I have a `Point` class (a code snippet):

    public Point(double x, double y)
    {
    	this.x = x;
    	this.y = y;
    }
    
    public override string ToString()
    {
    	return $"Point({x}, {y})";
    }

When I work with this class library in Python (in Python shell):

    >>> p1 = Point(10,15)
    >>> p1
    <Geometry.Point object at 0x000000000558F828>
    >>> str(p1)
    'Point(10, 15)'

Because I override the `ToString()`, when I run `str(p1)` I see my custom view of the object. However, when I just access a variable `p1`, then it goes to the `__repr__()` method under the hood which gives me ugly `<Geometry.Point object at 0x000000000558F828>`.

Is there a method in C# class that is possible to override so that `pythonnet` would use that method when getting the `__repr__`?

**Comment by denfromufa** [comment]
@AlexArcPy have you tried implementing `Repr()` on your C# class, it should be available here:

https://github.com/pythonnet/pythonnet/blob/master/src/runtime/pyobject.cs#L851

https://github.com/pythonnet/pythonnet/blob/master/src/runtime/pyobject.cs#L867

**Comment by AlexArcPy** [comment]
@denfromufa , thanks for the comment. I've just tried, but to no effect.

		public string Repr()
		{
			return $"Point({x}, {y})";
		}

```
p1
<Geometry.Point object at 0x00000000056A1550>
>>> p1.Repr()
u'Point(10, 15)'
```

Should I be implementing this method in any kind of special way?

**Comment by denfromufa** [comment]
@AlexArcPy looks like i was wrong, i'm not sure how this is possible to implement.

**Comment by denfromufa** [comment]
@AlexArcPy ok, i took a second look and the first step is to find out which `tp_repr` method is called in your case using VS C# debugger:

https://github.com/pythonnet/pythonnet/search?p=1&q=tp_repr&unscoped_q=tp_repr

After that we can tell if it is possible to implement `__repr__` on managed types without modifying pythonnet source code.

**Comment by denfromufa** [comment]
https://stackoverflow.com/questions/50664853/how-to-implement-repr-for-a-c-sharp-class-to-be-used-in-python-net

**Comment by AlexArcPy** [comment]
@denfromufa , thanks a lot for digging into. This is definitely not a top priority feature to work on, so no stress! Should you find something more - please post! Thanks!

**Comment by koubaa** [comment]
I've got a working implementation (it uses reflection to call __repr__ if one is defined)  but I don't know how to fallback to the default if a __repr__ is not defined. 

In standard CPython its done via object.__repr__(inst) but I'm not familiar enough with pythonnet to know how to get a reference to "class object"

Also, the behavior according to python documentation is this:
_The return value must be a string object. If a class defines __repr__() but not __str__(), then __repr__() is also used when an “informal” string representation of instances of that class is required._

Do we want this in pythonnet too?

**Comment by koubaa** [comment]
I was able to figure it out.  I'll make a pull request with my changes (including the behavior from the python doc I mentioned above).

**Comment by koubaa** [comment]
https://github.com/pythonnet/pythonnet/pull/808

**Comment by denfromufa** [comment]
@koubaa thanks for this PR, let's get the CI tests passed.
