### ISSUE TITLE
add circleci builds?

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#683]
Apparently @sdpython successfully added circleci builds of pythonnet in his branch.

Should we have this as an optional build CI to pythonnet master branch?

One benefit is definitely faster builds.

http://www.xavierdupre.fr/app/pymyinstall/helpsphinx/blog/2018/2018-05-20_pythonnet.html

cc @filmor @vmuriart @dmitriyse

**Comment by filmor** [comment]
Go ahead :)

Though this is faster builds on Linux, if I got that correctly, the thing using up far more time is AppVeyor for Windows builds.

**Comment by vmuriart** [comment]
IRT the slow AppVeyor builds, I was thinking the other day that maybe we should reduce the tests that run on it to 4 python versions. 
- PY27 x32
- PY27 x64
- PY36 x32 (or whatever the latest is)
- PY36 x64 (or whatever the latest is)

If (and when) we drop 2.7 support, we can change the testing to lowest python version we support and higher python version we support.

On Linux (Travis or Circle), we would still test all versions though

**Comment by denfromufa** [comment]
@vmuriart I'm against dropping PY34/35 in testing for Appveyor, e.g. see this issue with Python C-API differences between python 3.4 & 3.5. Who knows if this is platform-dependent?

https://github.com/pythonnet/pythonnet/issues/530 

Also VSTS now offers free resources for open-source projects:

https://groups.google.com/forum/#!topic/dev-python/zr80U4vtCCU

**Comment by vmuriart** [comment]
If the problem can be reduced to a simple Unit Test that Linux can detect, then it should still be ok to reduce the amount of testing.
