### ISSUE TITLE
Master does not build because of missing file

### ISSUE THREAD

**Issue by jbw3** [pythonnet/pythonnet#688]
Master does not build. Visual Studio is looking for the file "interop33.cs", but it is not there. It looks like this file was removed in the previous commit but was not removed from the Visual Studio project.

**Comment by denfromufa** [comment]
Weird that it builds in CI. Can you please submit a PR to fix?

**Comment by jbw3** [comment]
That is weird. Maybe it's because I'm building it from the IDE. Anyhow, I've opened PR #689 to fix it.
