### ISSUE TITLE
How do I embed Python in C# code (Unity3D project)?

### ISSUE THREAD

**Issue by off99555** [pythonnet/pythonnet#699]
### Environment

-   Pythonnet version: 2.3.0-py35-dotnet
-   Python version: 3.5.4
-   Operating System: Windows 10
-   .NET version: 4.x (Unity3D project)
-   Visual Studio 2017

### Details

I want to embed python in C# code of Unity3D project. And I also want to ship `python` and `pythonnet` with the project instead of installing it on my OS.

_I tried embedding `IronPython` before. It works but it couldn't read `.pyd` file which is important for my project. As I need to import `dlib.pyd` package for machine learning function._

Here's what I've tried so far:
I installed `pythonnet` and `python` via `NuGet` package manager in Visual Studio 2017.
Here's the command I used:
```
Install-Package python -Version 3.5.4
Install-Package pythonnet -Version 2.3.0-py35-dotnet
```

Here's the code I'm trying to run:
```cs
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using UnityEngine;

public class TestLib : MonoBehaviour {

    // Use this for initialization
    void Start () {
        using (Py.GIL())
        {
            dynamic np = Py.Import("numpy");
            Debug.Log(np.cos(np.pi * 2));

            dynamic sin = np.sin;
            Debug.Log(sin(5));

            double c = np.cos(5) + sin(5);
            Debug.Log(c);

            dynamic a = np.array(new List<float> { 1, 2, 3 });
            Debug.Log(a.dtype);

            dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
            Debug.Log(b.dtype);

            Debug.Log(a * b);
        }
    }
}
```
The error is that it doesn't know `Py`. I don't know what to import. I tried `using Python.Runtime;` and it didn't work.
I'm suspecting that it's because I didn't provide the path to the `Python.Runtime.dll` yet.
I have a folder named `Packages/` inside my project that contains the installation of `python` and `pythonnet`.
My question is **How do I import python and pythonnet from this Packages/ folder?**

**Comment by off99555** [comment]
I got it now. I just need to move `Packages/` folder into `Assets/` of my Unity project.

**Comment by AdamBebko** [comment]
I experimenced the same error. But when I follow you instructions, Unity crashes when entering playmode. 

In VS 2017, used your commands to install the packages.
Moved entire packages folder into Assets folder
Added Monobehaviour to scene
Press play,
Unity crashed

Any details you left out by any chance?

**Comment by khseob0715** [comment]
@AdamBebko I'm having the same issue. Have you solved it?

**Comment by off99555** [comment]
Sorry. I don't remember anything. It's been a long time. Good luck with your error.

**Comment by HuangJunye** [comment]
Any solution to this problem? I found a related tutorial on using pythonnet in Unity, but it gives the same error as mentioned here: https://pandacoredata.readthedocs.io/en/latest/tutorial/unity.html

**Comment by AdamBebko** [comment]
No, I wasn't able to fix it. I was trying to read .NPZ in unity, I ended up
just writing a script to convert to JSON in python, and then read the JSON
in Unity.

**Comment by AdamLabecki** [comment]
I am experiencing the same problem.

**Comment by prene112** [comment]
@off99555 Hi i have been trying to do the same thing that you have done in unity however i have gotten this error:
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name Python.Runtime.dll included for the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: Assets/Plugins/Python.Runtime.dll, Assets/Python.Runtime.NETStandard.3.7.1/lib/netstandard2.0/Python.Runtime.dll

Also did you only import the nuget package for pythonnet (Python.Runtime.NETStandard) or did you import other packages as well. 
Thank you

**Comment by OliverLai** [comment]
> ### Environment
> * Pythonnet version: 2.3.0-py35-dotnet
> * Python version: 3.5.4
> * Operating System: Windows 10
> * .NET version: 4.x (Unity3D project)
> * Visual Studio 2017
> 
> ### Details
> I want to embed python in C# code of Unity3D project. And I also want to ship `python` and `pythonnet` with the project instead of installing it on my OS.
> 
> _I tried embedding `IronPython` before. It works but it couldn't read `.pyd` file which is important for my project. As I need to import `dlib.pyd` package for machine learning function._
> 
> Here's what I've tried so far: I installed `pythonnet` and `python` via `NuGet` package manager in Visual Studio 2017. Here's the command I used:
> 
> ```
> Install-Package python -Version 3.5.4
> Install-Package pythonnet -Version 2.3.0-py35-dotnet
> ```
> 
> Here's the code I'm trying to run:
> 
> ```cs
> using System.Collections;
> using System.Collections.Generic;
> using System.Runtime.InteropServices;
> using UnityEngine;
> 
> public class TestLib : MonoBehaviour {
> 
>     // Use this for initialization
>     void Start () {
>         using (Py.GIL())
>         {
>             dynamic np = Py.Import("numpy");
>             Debug.Log(np.cos(np.pi * 2));
> 
>             dynamic sin = np.sin;
>             Debug.Log(sin(5));
> 
>             double c = np.cos(5) + sin(5);
>             Debug.Log(c);
> 
>             dynamic a = np.array(new List<float> { 1, 2, 3 });
>             Debug.Log(a.dtype);
> 
>             dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
>             Debug.Log(b.dtype);
> 
>             Debug.Log(a * b);
>         }
>     }
> }
> ```
> 
> The error is that it doesn't know `Py`. I don't know what to import. I tried `using Python.Runtime;` and it didn't work. I'm suspecting that it's because I didn't provide the path to the `Python.Runtime.dll` yet. I have a folder named `Packages/` inside my project that contains the installation of `python` and `pythonnet`. My question is **How do I import python and pythonnet from this Packages/ folder?**

Would you mind telling me where the python and pythonnet under package/ in your project come from or what they are? I tried putting python.dll and pythonnet folders in but something went wrong.

**Comment by OliverLai** [comment]
> ### Environment
> * Pythonnet version: 2.3.0-py35-dotnet
> * Python version: 3.5.4
> * Operating System: Windows 10
> * .NET version: 4.x (Unity3D project)
> * Visual Studio 2017
> 
> ### Details
> I want to embed python in C# code of Unity3D project. And I also want to ship `python` and `pythonnet` with the project instead of installing it on my OS.
> 
> _I tried embedding `IronPython` before. It works but it couldn't read `.pyd` file which is important for my project. As I need to import `dlib.pyd` package for machine learning function._
> 
> Here's what I've tried so far: I installed `pythonnet` and `python` via `NuGet` package manager in Visual Studio 2017. Here's the command I used:
> 
> ```
> Install-Package python -Version 3.5.4
> Install-Package pythonnet -Version 2.3.0-py35-dotnet
> ```
> 
> Here's the code I'm trying to run:
> 
> ```cs
> using System.Collections;
> using System.Collections.Generic;
> using System.Runtime.InteropServices;
> using UnityEngine;
> 
> public class TestLib : MonoBehaviour {
> 
>     // Use this for initialization
>     void Start () {
>         using (Py.GIL())
>         {
>             dynamic np = Py.Import("numpy");
>             Debug.Log(np.cos(np.pi * 2));
> 
>             dynamic sin = np.sin;
>             Debug.Log(sin(5));
> 
>             double c = np.cos(5) + sin(5);
>             Debug.Log(c);
> 
>             dynamic a = np.array(new List<float> { 1, 2, 3 });
>             Debug.Log(a.dtype);
> 
>             dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
>             Debug.Log(b.dtype);
> 
>             Debug.Log(a * b);
>         }
>     }
> }
> ```
> 
> The error is that it doesn't know `Py`. I don't know what to import. I tried `using Python.Runtime;` and it didn't work. I'm suspecting that it's because I didn't provide the path to the `Python.Runtime.dll` yet. I have a folder named `Packages/` inside my project that contains the installation of `python` and `pythonnet`. My question is **How do I import python and pythonnet from this Packages/ folder?**

Hello, I encountered the following problem when I followed your steps, how can I solve it?
<img width="469" alt="image" src="https://user-images.githubusercontent.com/33652272/166677102-ef9215a4-04d3-456c-9faa-47de31bf445c.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/33652272/166677228-6ddd15ad-566c-48f9-9c9f-4805d0f9588e.png">
<img width="609" alt="image" src="https://user-images.githubusercontent.com/33652272/166677313-bd245c24-f7ae-428b-90ca-0e4867690f9a.png">

**Comment by filmor** [comment]
This is not a support forum.
