### ISSUE TITLE
Pythonnet can not call a member function in a generic obj, while the generic obj is returned from the function call. 

### ISSUE THREAD

**Issue by laomagege** [pythonnet/pythonnet#70]
1. call the interface ICompositeImage.RenderedImages.
public interface ICompositeImage
{
  IEnumerable<IRenderedImage> RenderedImages { get; }
}

2. need call a RenderedImages.FirstOrDefault() to get an IRenderedImage obj from the IEnumerable, report Error "AttributeError: 'MethodBinding' object has no attribute 'FirstOrDefault'"

Is this because the pythonnet not support the generic return type?

**Comment by filmor** [comment]
This is equivalent to issue #55, Python.NET does not support extension methods. You can, however, use `IEnumerable.FirstOrDefault(compImg.RenderedImages)` explicitly, as extension methods are just fancy static methods.

**Comment by laomagege** [comment]
Appreciated your reply Filmor. So I have to change in the .Net side, and change the interface, right? Can I make a explicit call at python side?

**Comment by filmor** [comment]
Not really. `FirstOrDefault` is implemented in `Enumerable`, so the following should

    from System.Linq import Enumerable
    
    # Create ICompositeImage object compImg

    res = Enumerable.FirstOrDefault(compImg.RenderedImages)

**Comment by tonyroberts** [comment]
Looks like this was resolved. Please re-open if not.
