### ISSUE TITLE
How do I install python package?

### ISSUE THREAD

**Issue by off99555** [pythonnet/pythonnet#700]
For example, in normal environment, I would run `pip install dlib` to install `dlib`.
Can it be this simple for embedded python which is supposed to be shipped to clients?
If I can do it like that then I just need to go into python's directory installed by `NuGet` and run `pip install dlib` there.

**Comment by off99555** [comment]
I just saw that `python` is not even necessary to use `pythonnet`. So why do we need to install it? And where is `numpy` located?

**Comment by filmor** [comment]
Hello and welcome :)

Please note that this issue tracker is used exclusively for tracking bugs and (concrete) improvement activities. We can't provide user support here. This is also the reason for the issue template that you erased.

Please direct questions to channels like Unity forums, Stackoverflow etc.
