### ISSUE TITLE
c# calling python module via pythonnet in debug mode is very slow

### ISSUE THREAD

**Issue by treasuring** [pythonnet/pythonnet#702]
### Environment

-   Pythonnet version:2.3.0
-   Python version:3.6.6
-   Operating System: Windows 2008R2
-   Development Tool: VS2017

### Details

-   Describe what you were trying to get done.

How to speed up the use of c in the vs2017 debug mode to call the python module loading speed through pythonnet? Or disable python debug mode, making it the same as the release mode?

```python
    PythonEngine.Initialize();

            using (Py.GIL())
            {
                dynamic sys = Py.Import("sys");
                dynamic pd = Py.Import("pandas");
                sys.path.append(scriptPath);
                dynamic com = Py.Import("common");
                dynamic curvefit = Py.Import("CurveFitFun");
                dynamic tkytm = JsonHelper.ObjList2Json<T>(ktmList);
                dynamic dataframe = pd.read_json(tkytm);
                dynamic kpdf = curvefit.adjkp(dataframe);
                string kpjson = com.df2json(kpdf);
            }
```
-   The above code runs very fast in release mode, but it is very slow in debug mode.
-   How can I fix the issue? Any idea, thanks!

**Comment by denfromufa** [comment]
Did you profile which line is the causing the slowdown? Also not clear what you mean by debug mode?

**Comment by denfromufa** [comment]
@treasuring there is probably a lot of ways, e.g. in scriptcs:

```
> #r "C:\Python\Anaconda3\lib\site-packages\Python.Runtime.dll"
> using Python.Runtime;
> dynamic dir;
> using (Py.GIL()) { using (PyScope scope = Py.CreateScope()) {
* { dir = scope.Eval("dir()");}}
*
* }
> dir.ToString()
['__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__']
>
```

**Comment by denfromufa** [comment]
@treasuring I used the wrong thread!

**Comment by filmor** [comment]
Since there have not been any updates in quite a while, I'll close this issue. Feel free to reopen and provide a information on the current state.

**Comment by jbrownkramer** [comment]
I have the same problem.  Any insight into this?
