### ISSUE TITLE
Very Slow Python Initialize

### ISSUE THREAD

**Issue by williamrubens** [pythonnet/pythonnet#703]
### Environment

Pythonnet version: 2.3.0
Python version: Python 3.5 (conda environment)
Operating System: Windows 10 64bit
VS 2017

### Details

Hi guys, thanks for the great work building a super useful library. One question, and this could be expected behavior, I'm not sure. When I initialize the python interpreter on the .Net side, with this call:

`using (Py.GIL())
{`

I've timed it and it takes about 2 mins to complete the call. Further calls to grab python lock return immediately. I've also noticed that in visual studio my output window I see thousands of messages of this form:

> Exception thrown at 0x00007FFE37F73C58 in RSUser.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x000000314CBFB8F0.
> Exception thrown at 0x00007FFE37F73C58 in RSUser.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
> Exception thrown at 0x00007FFE37F73C58 in RSUser.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x000000314CBFB8F0.
> Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
> Exception thrown at 0x00007FFE37F73C58 in RSUser.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x000000314CBFB8F0.
> Exception thrown at 0x00007FFE37F73C58 in RSUser.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.

**Comment by filmor** [comment]
I have never observed this, can you disclose your test sample?

**Comment by denfromufa** [comment]
Did you mean that initialize takes 2 minutes under VS debugger? If yes,
then this could be due to VS or PTVS settings.

**Comment by williamrubens** [comment]
I switched to running under release and it's much faster, takes around 40 seconds now, though I can still thousands of exceptions in the output window. Sounds like it could be some VS settings... any ideas which ones to play with?

**Comment by inna-w** [comment]
This issue was discussed before: [#598](https://github.com/pythonnet/pythonnet/issues/598).
The solution proposed by @dmitriyse there worked for me - we are using build from [featured](https://github.com/pythonnet/pythonnet/tree/featured) branch. This also solved crashes on obfuscated types names in 3rd party assemblies.

**Comment by williamrubens** [comment]
Switching to using the featured branch has solved the thousands of exceptions problem. It's also now quite speedy in release mode. It still takes forever in debug mode.

**Comment by denfromufa** [comment]
closed by https://github.com/pythonnet/pythonnet/pull/723

**Comment by simonbuehler** [comment]
I'm still having the very same issue with those exceptions beeing thrown and a very slow startup behaviour, is this normal or how can i debug this?
