### ISSUE TITLE
Embedding python runtime vs path to the python dll

### ISSUE THREAD

**Issue by fandrei** [pythonnet/pythonnet#707]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6
-   Operating System: Windows 7 x64

### Details

Trying to run this C# program:
```
			using (Py.GIL())
			{
				dynamic np = Py.Import("numpy");
				Console.WriteLine(np.cos(np.pi * 2));
			}
```
and getting this exception:
```
System.DllNotFoundException: 'Unable to load DLL 'python35': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'
```

Q: How do I specify the path to the python dll and runtime version explicitly?

**Comment by denfromufa** [comment]
Please read the troubleshooting wiki and report back if you still have issues:

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX

**Comment by fandrei** [comment]
@denfromufa this wiki doesn't answer the question, which was: how to set Python DLL version in **runtime**?

**Comment by denfromufa** [comment]
@fandrei your issue is explained in that wiki with exactly the same error message.
Read about how to set Python paths.
