### ISSUE TITLE
PythonEngine.PythonHome doesn't work

### ISSUE THREAD

**Issue by fandrei** [pythonnet/pythonnet#708]
Environment

    Pythonnet version: 2.3.0
    Python version: 3.6
    Operating System: Windows 7 x64

Details

Trying to run this C# program:

```
			var pythonPath = @"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\";

			PythonEngine.PythonHome = pythonPath;

			using (Py.GIL())
			{
				dynamic np = Py.Import("numpy");
				Console.WriteLine(np.cos(np.pi * 2));
			}
```

and getting this exception:

```
System.DllNotFoundException: 'Unable to load DLL 'python36': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'
```

**Comment by denfromufa** [comment]
Please read this comment from the issue linked in the wiki:

https://github.com/pythonnet/pythonnet/issues/259#issuecomment-245415530

**Comment by fandrei** [comment]
@denfromufa it's a workaround; and that still means that `PythonEngine.PythonHome` doesn't work, does it?

**Comment by denfromufa** [comment]
Please refer to official CPython embedding API if you think that this behavior is not correct and then contributions are welcome!

**Comment by fandrei** [comment]
@denfromufa I'm already contributing by testing your code.

Well, this workaround doesn't work properly too:

```
			var pythonPath = @"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python3_64";

			Environment.SetEnvironmentVariable("PATH", $@"{pythonPath};" + Environment.GetEnvironmentVariable("PATH"));
			Environment.SetEnvironmentVariable("PYTHONHOME", pythonPath);
			Environment.SetEnvironmentVariable("PYTHONPATH ", $@"{pythonPath}\Lib");

			using (Py.GIL())
			{
				dynamic np = Py.Import("numpy");
				Console.WriteLine(np.cos(np.pi * 2));
			}
```

```
System.DllNotFoundException: 'Unable to load DLL 'python36': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'
```

The DLL file does exist at the specified path.
```
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64>attrib python36.dll
A            C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\python36.dll
```

**Comment by denfromufa** [comment]
Are you mixing two different Python installations Python3_64 and Anaconda3_64?!

**Comment by fandrei** [comment]
@denfromufa in this sample, only one installation is used.

**Comment by fandrei** [comment]
Ah, now I see. My bad.

**Comment by epignatelli** [comment]
Would it be better to reopen this issue?

The only solution is actually a workaround. Also, why is `PythonEngine.PythonPath = ""` not working?
Any plan to fix it?
