### ISSUE TITLE
compile on linux 64 bit with mono

### ISSUE THREAD

**Issue by nikhil003** [pythonnet/pythonnet#71]
Hi,

I have compiled mono on my linux (Fedora 17) 64 but machine. With some basic checks, i can say that it is working. I then tried to compile the pythonnet downloaded from github but i have not been able to compile it. I wanted to know whether it is compatible with 64 bit systems. Honestly, I am not familiar with csharp, and i use pythondotnet to connect to some csharp libraries and use them in python.

I get this error, even though i have put NuGet.exe in mono, I still cant get it to work. I would appreciate any help

Unhandled Exception: System.TypeLoadException: Could not load type 'NuGet.Program' from assembly 'NuGet, Version=2.8.50126.400, Culture=neutral, PublicKeyToken=null'.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'NuGet.Program' from assembly 'NuGet, Version=2.8.50126.400, Culture=neutral, PublicKeyToken=null'.

**Comment by tonyroberts** [comment]
Hi,

you can see the current build status on linux here: https://travis-ci.org/pythonnet/pythonnet/branches

It looks like something is wrong with how nuget is installed on your system. Take a look at the .travis.yml file to see how the travis-ci build works. The travis build machines are 64 bit.

Tony

**Comment by nikhil003** [comment]
Hi,

Thanks for your reply. I modified the setup.py to have --release=v4.0 and then it installed NUnit and UnmanagedExports package. Now it gives me a new error. this is what I get when i run 

python setup.py build_ext --inplace


Installing 'NUnit 2.6.2'.
Successfully installed 'NUnit 2.6.2'.
Installing 'UnmanagedExports 1.2.6'.
Successfully installed 'UnmanagedExports 1.2.6'.
XBuild Engine Version 2.10.8.0
Mono, Version 2.10.8.0
Copyright (C) Marek Sieradzki 2005-2008, Novell 2008-2011.
/home/nikhil/Documents/mono/pythonnet/pythonnet.sln:  warning : The project configuration for project 'clrmodule' corresponding to the solution configuration 'ReleaseMono|x64' was not found.
XBuild Engine Version 2.10.8.0
Mono, Version 2.10.8.0
Copyright (C) Marek Sieradzki 2005-2008, Novell 2008-2011.
		Configuration: ReleaseMono Platform: x64
: error CS0016: Could not write to file `Python.Runtime', cause: AMD64

**Comment by tonyroberts** [comment]
It could be that it's trying to link some previously built x86 objects since you've been trying various different things to get it working. If I were you I'd delete all built objects and try again - or even just delete the whole lot and clone the repo again to start from scratch.

**Comment by tonyroberts** [comment]
Hi,

did you get this working? Can we close this issue now?

cheers,
Tony

**Comment by nikhil003** [comment]
Hi Tony,

I just tried the newest version but it seems like not compiling. I am getting error 

Error CS1566: Error reading resource file `/home/nikhil/Documents/conda/pythonnet-2.0.0/src/console/$(PythonBuildDir)/Python.Runtime.dll' (CS1566) (Console)

when I try to compile it

**Comment by nikhil003** [comment]
Hi, Sorry for my earlier message...I got it to work.

I compiled it from python in place of using monodevelop to compile.
