### ISSUE TITLE
How to call a Python embedded function from C#?

### ISSUE THREAD

**Issue by fandrei** [pythonnet/pythonnet#710]
### Environment

-    Pythonnet version: 2.3.0
-    Python version: 3.6
-    Operating System: Windows 7 x64

### Details

The samples only show how to import a module and call a function defined in this module; how do I call a Python's built-in function which is not defined in any module, for instance dir or eval?

**Comment by denfromufa** [comment]
@fandrei there is probably a lot of ways, e.g. in scriptcs:

```csharp
> #r "C:\Python\Anaconda3\lib\site-packages\Python.Runtime.dll"
> using Python.Runtime;
> dynamic dir;
> using (Py.GIL()) { using (PyScope scope = Py.CreateScope()) {
* { dir = scope.Eval("dir()");}}
*
* }
> dir.ToString()
['__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__']
>
```

**Comment by fandrei** [comment]
@denfromufa for some reason, Py.CreateScope() doesn't exist in the package that I have. Is it version dependent? I have 2.3.0-py35-dotnet

**Comment by denfromufa** [comment]
PyScope is in the master branch, which you can build or install according to wiki

**Comment by fandrei** [comment]
@denfromufa so, not in the released package yet. The build from latest master works, thanks.

**Comment by denfromufa** [comment]
@fandrei closing this issue, since no action items
