### ISSUE TITLE
Import .net lib failed due to nuget package dependency

### ISSUE THREAD

**Issue by weixu02** [pythonnet/pythonnet#711]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6.5
-   Operating System: windows 7

### Details
I am experiencing the same problem in the following post. Is there a way to specify nuget lib location so that python.net can load the lib. Can we add any lines in python.exe.config to achieve this? Thanks!

https://stackoverflow.com/questions/51609699/importing-net-standard-2-0-class-library-with-dependencies-using-python-net

**Comment by weixu02** [comment]
After some searching, the following workaround seems to work for me: Basically adding this section in your .net standard proj file and the necessary dlls will be copied to output folder:

<PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
</PropertyGroup>

**Comment by michaelosthege** [comment]
@weixu02 Thank you for sharing this link. The `dotnet publish` command was the key to get it working on my machine.  I can now treat my .NET Standard class library as a `git submodule`, build it with `dotnet publish` which puts all I need into `/bin/Debug/netstandard2.0/publish` and from there I can import it to Python.

**Comment by denfromufa** [comment]
@michaelosthege @weixu02 good finding guys, I'm closing this issue for now. no action items in pythonnet!
