### ISSUE TITLE
Exception thrown when initializing Python .NET after a domain unload

### ISSUE THREAD

**Issue by lassond** [pythonnet/pythonnet#714]
### Environment

-   Pythonnet version: latest master commit as of 2018-08-09 (fb84cd28254f1ed6bde82766dadd6ba18c3e7be1 )

-   Python version: 
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32

-   Operating System:
Windows 10

- In the context of running in Unity, but also reproducible in a simple standalone app made from scratch

### Details

Unity, whenever a C# script is changed, the AppDomain in which the Assemblies are loaded gets unloaded. Then, Unity creates a fresh AppDomain, recompiles the C# assemblies and loads them again.

The Python.Runtime assembly gets unloaded, but the Python interpreter survives (it is a native library). This results in an inconsistent state between the Python .NET Engine/Runtime classes (which are not initialized) and the Python interpreter (which is initialized). 

An exception is raised when Python .NET accesses the interpreter (System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.)

-   Describe what you were trying to get done.

See above

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

I will attach my standalone application which reproduces this crash along with the repro steps. (either ere or on the pull request if I cannot attach here)

**Comment by lassond** [comment]
[hotReloadCrashRepro.zip](https://github.com/pythonnet/pythonnet/files/2275521/hotReloadCrashRepro.zip)


(Note: with the upcoming fix, the application will still raise an exception, but on the second domain unload - a bit further. A fix for this second crash is under review)

**Comment by benoithudson** [comment]
This is fixed and the test case integrated in #752. But I don't have permissions to close the bug.

**Comment by filmor** [comment]
But I do, thanks again :)

**Comment by dyeo** [comment]
> By the way, I'm working on a new binding mode for Python call that supported IL2CPP and with more higher performance, this pythonnet will a part of my unity package.
> https://github.com/amos402/pythonnet/tree/fast-call

@amos402 did you ever make any headway with the new binding mode that enables IL2CPP support?
