### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by STREETKILLER007** [pythonnet/pythonnet#718]
From Wiki, i clicked into this link
https://pythonnet.github.io/readme.html
but it showed me a blank page.
Do you remove it ?

I am new in Python.
From Wiki, there is a term call CPython.
I tried to search it, but it keep bringing me to the Python installation official website.
I downloaded Python 3.6.
Wondering am i in the correct track ?

**Comment by denfromufa** [comment]
@STREETKILLER007 thanks for reporting a broken link - fixed!

ye,s you are on correct track! Install CPython 3.6 and then install pythonnet with pip.
