### ISSUE TITLE
Support for Python 3.7

### ISSUE THREAD

**Issue by iarspider** [pythonnet/pythonnet#720]
Installation with Python 3.7 fails because there is no `interop37.cs`

**Comment by MisterY** [comment]
What is the solution for this? 
I have pythonnet-2.4.0.dev0-cp37 that I'm using at the moment but still getting

![image](https://user-images.githubusercontent.com/462445/47842332-ad8ba380-ddbc-11e8-859a-17234f41d4c0.png)

so I assume this is still valid?

**Comment by denfromufa** [comment]
3 steps to install latest pythonnet with python3.7 support:

```
git clone https://github.com/pythonnet/pythonnet
cd pythonnet
python setup.py install
```

Note that I'm pushing a fix when only VS 2017 is installed on machine:

https://github.com/pythonnet/pythonnet/pull/758

Somehow Appveyor CI still works without this fix and you can also find the wheels from these builds in the Appveyor artifacts.

**Comment by denfromufa** [comment]
@MisterY you probably installed pybee from pypi and it depends on python 3.7, but pythonnet does not have python3.7 wheel on pypi yet.

**Comment by pallavi1292** [comment]
Pythonnet works for Python 3.7 now?
