### ISSUE TITLE
Running python code located in external file doesn't reflect changes in code for consecutive executions

### ISSUE THREAD

**Issue by msup** [pythonnet/pythonnet#726]
### Environment

-   Pythonnet version:  2.4, commit b6417cadce9f1ec56eba3e846a1fbef4096d69c7
-   Python version: Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
-   Operating System: Windows 10, 17746.rs5

### Details

-   I created simple WPF application with 2 buttons executing 2 different scripts - test_module1.py & test_module2.py
 
    What I want to do is to have an option to modify the external python script while the main wpf application is still running. When I first time start the script, modify it in the bin directory, delete the created python cache directory or delete the script py file itself and press the buttons in WPF 
again - modification are not executed. Always what runs is the first time executed script.

### Use case:
1. Start the app
2. Click the Start test_module1.py button
3. Go to the bin directory, modify the Start test_module1.py or delete it
4. Click the Start test_module1.py button again

### Minimal demo application in attachment
 
[Test_PyNet_2ndCallIssue.zip](https://github.com/pythonnet/pythonnet/files/2331647/Test_PyNet_2ndCallIssue.zip)

**Comment by filmor** [comment]
This has nothing to do with Python.NET, it is exactly how Python itself behaves.

Have a look at [importlib.reload](https://docs.python.org/3/library/importlib.html#importlib.reload) to achieve what you are trying to do.

**Comment by denfromufa** [comment]
Reloading Python modules is very flaky especially when calling into C-extensions such numpy
