### ISSUE TITLE
Use sys.meta_path instead of our old-style import hook

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#727]
Python.NET as of now overrides `__import__` directly which works, but has multiple nasty issues. Implementing a [PEP302](https://www.python.org/dev/peps/pep-0302/) compatible loader would allow us to keep `__import__` alone, solving at least #559, #547. There's probably more issues due to this.

**Comment by ramik91** [comment]
@filmor @denfromufa any update on this? I run into an issue using Kivy lib with pythonnet. Wondering if its worth trying to switch to different gui lib or moving to iron-python instead.
