### ISSUE TITLE
Incorporate additional type conversions from QuantConnect

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#728]
The fork at https://github.com/QuantConnect/pythonnet implements various type conversions (also includes a new version of #304), we should incorporate them into the upstream repository with version 3.

**Comment by christabella** [comment]
What kind of type conversions are implemented in the QC fork, and is this issue addressed by codecs now or still outstanding? https://github.com/pythonnet/pythonnet/wiki/Codecs:-customizing-object-marshalling-between-.NET-and-Python

**Comment by filmor** [comment]
This is indeed superceded by codecs, thanks for the hint.
