### ISSUE TITLE
How to define a UserControl in Python for WPF?

### ISSUE THREAD

**Issue by zenchanhk** [pythonnet/pythonnet#733]
Hi,

I'm wondering if it is possible to define a `UserControl` in Python with WPF? In C#, I need to implement a class partially, but how could I achieve that in Python? And how to use that `UserControl` in another `xaml` file? Should I define `__namespace__` to use it in another place?

Thanks a lot!

**Comment by filmor** [comment]
I'm sorry, this is not a support forum. If the existing documentation at https://github.com/pythonnet/pythonnet/wiki doesn't help you, ask the question on StackOverflow.
