### ISSUE TITLE
In c#: open npz-file with numpy, read data and than delete file: file is still used by an other process exception

### ISSUE THREAD

**Issue by LaryLary** [pythonnet/pythonnet#736]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: Anaconda 3 5.2.0 (Python 3.6)
-   Operating System: Windows 10 

### Details

Hello, 

I am an c#-programmer and want to read a npz-file in my c#-solution and it works great, but when I want to delete the file , I get the exception, that it is still used by an other process. I have tried some things and I have not found a solution.

here is my code:

```c#
using ( Py.GIL( ) )
{
   var locking = PythonEngine.AcquireLock( );
   dynamic np = Py.Import("numpy");
   PyObject data = np.load(path);
  
    //do something with the data ....

   data = null;
   np = null;
   PythonEngine.ReleaseLock(locking);
}
```

with the 3 lines at the end I finally made it possible to read the file again with this code (before this was not possible without closing my app), but it looks it is not enought to close the file.

**Comment by denfromufa** [comment]
According to numpy documentation it is possible to `.close()` the loaded
file, see examples:

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.load.html

**Comment by filmor** [comment]
It's necessary even, if you don't want to wait for the garbage collector to release the object.

**Comment by LaryLary** [comment]
Thank you, but I do not know how to call data.close() in c#. I have tried this                
data.GetAttr("close");
but it does not work.
