### ISSUE TITLE
app sometimes stuck on Py.GIL() 

### ISSUE THREAD

**Issue by pouyaSamie** [pythonnet/pythonnet#737]
### Environment

-   Pythonnet version:  2.3
-   Python version: 3.7.0
-   Operating System: Windows 10 - build 1803

### Details

I'm having a python script that I'm running in a class library and i call it from asp.net application.
it's working fine but sometimes it stuck on Py.GIL() and not doing anything.

i tried to use PythonEngine.Shutdown(); after my using block but it crashes my hole app and my iis get stop.

 ```
                dynamic clrPredict;
                dynamic forecats;
                using (Py.GIL())
                {
                    var converter = (new PythonHelper()).GetConverter();
                    dynamic syspy = Py.Import("sys");
                    syspy.path.append(_pythonFilePaths);
                    dynamic ts= Py.Import("TimeSeries");
                    predictResult = ts.main(values);
                    clrPredict = converter.ToClr(predictResult[0]);
                    forecats = converter.ToClr(predictResult[1]);
                    
                }
                //PythonEngine.Shutdown();
              
                return new TimeSeriesResultModel(clrPredict, forecats);
```

-   and when i call PythonEngine.Shutdown(); my app crashes with no error even in my event viewer.
so why my app sometimes stuck on Py.GIL() and how can i fix that?

**Comment by denfromufa** [comment]
@pouyaSamie iis is using appdomains, hence some issues:

https://github.com/pythonnet/pythonnet/search?q=iis&type=Issues

**Comment by filmor** [comment]
Since there have not been any updates in quite a while, I'll close this issue. Feel free to reopen and provide a information on the current state.

**Comment by NWcodeart** [comment]
did you solve it?? i have the same issue
