### ISSUE TITLE
Error with python 3.4

### ISSUE THREAD

**Issue by BrisingrAerowing** [pythonnet/pythonnet#74]
This is more for the [Renshaw Bay Fork](https://github.com/renshawbay/pythonnet) but I am posting here as there is no issue tracker there.

Basically Python 3.4 (and 3.3 AFAIK) have larger unicode support and trigger the UCS4 support in PythonNET's setup.py, causing the build to fail as Mono.Posix most likely is not available.

I get around this by editing setup.py to always use UCS2, but this needs to be fixed.

**Comment by tonyroberts** [comment]
I've enabled the issue tracker for that project and created the issue there.

thanks!
Tony

**Comment by tonyroberts** [comment]
I've pushed a fix for this to the renshawbay fork.

cheers,
Tony
