### ISSUE TITLE
Pythonnet tries to load python27.dll although Python 3.6 is installed

### ISSUE THREAD

**Issue by SamiLakka** [pythonnet/pythonnet#742]
### Environment

-   Pythonnet version: 2.3
-   Python version: 3.6
-   Operating System: Win10

### Details
I installed pythonnet 2.3 to my computer where I also have Anaconda3 as well as vanilla Python 3.6 installed. When I launch nPython or try to call PythonEngine.Intialize() in my .NET application, I get an exception that DLL library python27 could not be loaded. This is weird as I don't have Python 2.7 in my computer at all. How do I force the pythonnet to look for python36.dll?

**Comment by denfromufa** [comment]
@SamiLakka how did you install pythonnet? have you looked at installation and troubleshooting wiki?

https://github.com/pythonnet/pythonnet/wiki/Installation
https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX

What does output of `where python` show in the console?

**Comment by SamiLakka** [comment]
Hi, I'll look into the installation wiki now. 

I installed pythonnet in Anaconda3 prompt by typing pip install pythonnet. I also downloaded the src distribution and tried the nPython executable from there. 

where python give me:
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe

**Comment by SamiLakka** [comment]
Ok, now I got the nPython to link to correct python version. It was simply missing Python36 flag in the compiler properties.
