### ISSUE TITLE
Tarball contains mix of line endings

### ISSUE THREAD

**Issue by Cronan** [pythonnet/pythonnet#746]
Several files in the pypi tarball contain CRLF line terminators. The vast majority do not.
Is this intentional, as it can cause problems with certain Linux commands and processing?

```
me@me:~/pythonnet-2.3.0$ file -kf `find -type f` | grep CRLF
./pythonnet.egg-info/not-zip-safe:                           ASCII text, with CRLF line terminators
./pythonnet.egg-info/PKG-INFO:                               ASCII text, with CRLF line terminators
./setup.cfg:                                                 ASCII text, with CRLF line terminators
./src/runtime/debughelper.cs:                                ASCII text, with CRLF, LF line terminators
```

https://pypi.org/project/pythonnet/#files
pythonnet-2.3.0.tar.gz

**Comment by filmor** [comment]
It's not intentional and should be easy enough to fix. However, the files in `egg-info` are created by distutils, AFAIK, so they shouldn'tbe a problem.

**Comment by denfromufa** [comment]
@Cronan PR is welcome :)

**Comment by Cronan** [comment]
:)
I’ll take a look - got a few more too, will maybe have more time close to Christmas
