### ISSUE TITLE
building an MSI using bdist does not work

### ISSUE THREAD

**Issue by pradeeps** [pythonnet/pythonnet#747]
### Environment

-   Pythonnet version: latest
-   Python version: 2.7.9
-   Operating System: Windows 10
- .NET Framework installed: 4.7.x

### Details

I've synced pythonnet code and ran **python setup.py bdist --format=msi**

The first error I get is : 

CSC : error CS1617: Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default [C:\build\pythonnet
-master\pythonnet-master\src\runtime\Python.Runtime.csproj]
CSC : error CS1617: Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default [C:\build\pythonnet
-master\pythonnet-master\src\clrmodule\clrmodule.csproj]

and the process fails with the below

File "C:\python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" pythonnet.sln /p:Configuration=ReleaseWin /p:Platform=x86 /p:DefineConstants="PYTHON27%3BPYTHON2%3BUCS2" /p:PythonBuildDir="C:\build\pythonnet-master\pythonnet-master\build\lib.win32-2.7" /p:PythonInteropFile="interop27.cs" /verbosity:minimal /p:PythonManifest="C:\build\pythonnet-master\pythonnet-master\build\lib.win32-2.7\app.manifest" /t:Build' returned non-zero exit status 1

Is this looking for .NET framework 4.0.x?

**Comment by filmor** [comment]
You need a newer version of Visual Studio as we make use of C#6 features.
