### ISSUE TITLE
ImportError: No module named Azure  after importing a PowerShell dll

### ISSUE THREAD

**Issue by sdementen** [pythonnet/pythonnet#748]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6
-   Operating System: Windows 7

### Details

-   Describe what you were trying to get done.

    I am trying to use a power shell module for AzureRM

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
import sys

sys.path.append(r"C:\Program Files\WindowsPowerShell\Modules\AzureRM.ApiManagement\6.1.1")

import clr

a=clr.AddReference("Microsoft.Azure.Commands.ApiManagement.ServiceManagement")

from Microsoft.Azure.Commands.ApiManagement.ServiceManagement import Models
```

-   If there was a crash, please include the traceback here.

```python
Microsoft.Azure.Commands.ApiManagement.ServiceManagement, Version=6.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35                                             
Traceback (most recent call last):                                                                                                                                      
  File "main.py", line 10, in <module>                                                                                                                                  
    from Microsoft.Azure.Commands.ApiManagement.ServiceManagement import Models                                                                                         
ImportError: No module named Azure        
```

**Comment by denfromufa** [comment]
@sdementen most likely this is because AzureRM references assemblies from many subdirectories not in sys.path. Try inspecting these references in ILSPY. I'm not sure how powershell handles that.

**Comment by filmor** [comment]
This doesn't look like an issue with Python.NET itself. Feel free to reopen when you can provide more information
