### ISSUE TITLE
Running Unity is bound to crash, but I don't know why. Look forward to a Unity example to help me use it. Thanks!

### ISSUE THREAD

**Issue by shimaoye** [pythonnet/pythonnet#761]
### Environment

-   Pythonnet version:2.4
-   Python version:2.7
-   Operating System:win10

**Comment by denfromufa** [comment]
@shimaoye this fits more into stackoverflow with pythonnet tag. But you still need to ask your question as a minimal reproducible issue (see the link below). Feel free to link bacl your stackoverflow post here in the comments.

https://stackoverflow.com/help/mcve
