### ISSUE TITLE
After initializing, shutting down and initializing PythonEngine importing any Python library with native DLLs causes a crash

### ISSUE THREAD

**Issue by DragoonAethis** [pythonnet/pythonnet#762]
**This is not a pythonnet bug**, but rather a CPython bug that is somewhat hard to find in certain scenarios. I'd like to document it here so that it's kind of googlable in the future, but **this can be immediately closed if you wish so**, or may remain open to track this issue in the future.

Let's say you have an application that uses pythonnet for some time, importing libraries like numpy and using them somehow, and eventually shuts down pythonnet, then starts it again when needed and tries to load numpy again:

    PythonEngine.Initialize();
    dynamic np = Py.Import("numpy");
    PythonEngine.Shutdown();
    // Go do something else for a while...
    PythonEngine.Initialize();
    Py.Import("numpy"); // Crash!

The second time you try to import numpy (or any library that loads a native library and doesn't clean up after itself properly), the application will crash. This happens in any recent pythonnet version, including current master commit, and on any Python version.

The reason for that is that trying to load the native library after re-initializing the embedded CPython runtime is somehow broken and causes an access violation, as documented here:

- https://bugs.python.org/issue34309
- https://github.com/numpy/numpy/issues/11925
- https://github.com/numpy/numpy/issues/8097
- https://github.com/numpy/numpy/issues/656

This is especially problematic if you have pythonnet embedded in a Unity project. In Unity Editor, every time you enter/leave Play mode, the Python runtime gets initialized/shut down, but not completely cleaned up. After entering Play mode for the second time and trying to import a library with a native dependency, the Unity editor will crash. The crash log will contain something like this at the top (depends on the offending library):

    multiarray.cp37-win_amd64.pyd caused an Access Violation (0xc0000005)
      in module multiarray.cp37-win_amd64.pyd at 0033:564c58ec.

Other than "it's faster to close the Unity Editor the nice way rather than crash it", there's no solution for this at the moment.

**Comment by denfromufa** [comment]
The numpy reloading issue was discussed in this issue tracker, I'm not sure if some workaround was found.
Anyway this is not even CPython issue, but rather the way numpy works.

**Comment by denfromufa** [comment]
@benoithudson so your PR does not resolve this issue with numpy?

**Comment by benoithudson** [comment]
The issue is that Unity editor needs to shut down and restart frequently ("domain reload"). But a lot of libraries aren't set up to survive that -- our case was pyside.

What we ended up putting together is putting the pyside on a separate process, communicating with python.net in Unity via rpyc. It's non-trivial to get this working well.

We aspire to release this to the public sometime, but I can't give any promises for when.

**Comment by benoithudson** [comment]
If you can do that, you can do simpler than rpyc -- just spawn a python process to run the numpy code when you get a cache miss, then load the cached results when it's done processing.

**Comment by DragoonAethis** [comment]
The actual solution we've used for this is just to drop pydicom and migrate to a library that runs under Unity runtime (we've used fo-dicom). Back when we've started the project, we couldn't get it to work for various reasons, but eventually got it running much later, so this isn't a problem.

Loading in a separate process, writing cache, then loading the cache would take a fair bit longer (and it was already very slow to begin with). We didn't really mind all that much because once cached, we'd use the data in the editor for quite a while, plus the built player wasn't affected (it did load pydicom, numpy and friends, but because it never unloaded them, things were fine).

**Comment by benoithudson** [comment]
Awesome. You've made me think about this and I have notes in my notebook for my next meeting with the powers that be.

**Comment by DragoonAethis** [comment]
I think I just worked around the problem by dropping the whole problem completely, but I'm glad it helped :D

**Comment by lostmsu** [comment]
We no longer support completely reloading Python runtime.
