### ISSUE TITLE
Can't open dll

### ISSUE THREAD

**Issue by Lolo4991** [pythonnet/pythonnet#763]
### Environment

-   Pythonnet version: 2.7
-   Python version: 3.5
-   Operating System: Windows7

### Details

-   I m trying to use functions provided by a dll. The dll is placed in this directory C:\Program Files (x86)\WS Technologies Inc\STB Test Bench. And in this dll, that i have not written, I know that there is a function which is called "Ping". But i m not able to access it. 

```python
##PATH_DLL = r"C:\Program Files (x86)\WS Technologies Inc\STB Test Bench\STB.dll"

import sys

sys.path.append(r"C:\Program Files (x86)\WS Technologies Inc\STB Test Bench")

import clr
clr.AddReference("STB")

from STB import Ping


if __name__ == '__main__':
    print("gg")
```

-   If there was a crash, please include the traceback here.
![image](https://user-images.githubusercontent.com/44777018/48003347-801d5d80-e10e-11e8-8038-191883f6db2d.png)

**Comment by filmor** [comment]
This is not a support forum, in particular not for third-party DLLs.

.NET doesn't contain free functions, so if your function is named `Ping`, it must be included in some type. You can get the full names of all exported types of a DLL by using the result of `clr.AddReference`:

    ass = clr.AddReference("STB")
    list(x.FullName for x in ass.ExportedTypes)

I hope this helps.
