### ISSUE TITLE
I want to pass the byte[] array to the parameters of Python method.

### ISSUE THREAD

**Issue by liu7923032** [pythonnet/pythonnet#765]
### Environment

-   Pythonnet version:2.3
-   Python version:3.5
-   Operating System:window 10

### Details

       I want to pass the byte[] array to the parameters of Python method.
      Because I need to use it in image processing. 
      What should I do?
      Or how to convert byte[] to PyObject（PyByteArrayObject）

**Comment by filmor** [comment]
The code you posted is C++, Python.NET is a C# project. Try to use the provided APIs, there are lots of examples 

This issue tracker is not a support forum.
