### ISSUE TITLE
Interrupting running Python code from another thread

### ISSUE THREAD

**Issue by jduncalf** [pythonnet/pythonnet#766]
Hi, does anyone know the best way to stop a currently running PyScope.Exec() call. My C# app is multi-threaded and allows users to run scripts, however where there's an infinite loop, new Python calls can be executed but I can't stop the original infinite loop.

Thanks.

**Comment by filmor** [comment]
See here https://stackoverflow.com/questions/1420957/stopping-embedded-python.

We currently do not expose `Py_AddPendingCall`, though, but assuming we did (there is PR #692 that uses it), you could probably translate the given example like this:


    class Interrupter
    {
        public Interrupter()
        {
            _interruptAction = DoInterrupt;
        }

        int DoInterrupt(IntPtr arg)
        {
            Exceptions.SetError(Exceptions.KeyboardInterrupt, "interrupted");
        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        delegate int PendingCall(IntPtr arg);
        readonly PendingCall _interruptAction;

        void Interrupt()
        {
            IntPtr func = Marshal.GetFunctionPointerForDelegate(_interruptAction);
            Runtime.Py_AddPendingCall(func, IntPtr.Zero);
        }
    }

All `Runtime` functions are `internal`, so you will have to work within `pythonnet`'s codebase itself. A PR adding an `Interrupt()` function on `PythonEngine` and `PyScope` would be highly appreciated :)

**Comment by jduncalf** [comment]
Many thanks, i'll do that.

**Comment by jduncalf** [comment]
Hi, unfortunately I can't get this to work. I basically used the Interrupter class you posted above, but the DoInterrupt() callback never gets invoked.

Any ideas?

**Comment by jduncalf** [comment]
Hi filmor, apologies, got it working. Had to change my C# host apps threading model. As a COM/DCOM MTA server the .exe primary thread was not the thread which eventually called `PyEval_InitThreads`, which is required for the `Py_AddPendingCall` supplied callback to work.

Thanks again.

**Comment by filmor** [comment]
Nice, I'll see whether I can prepare a PR that includes this.

**Comment by amos402** [comment]
@jduncalf I think this extension should be help https://github.com/amos402/py-xtimeout

**Comment by denfromufa** [comment]
anyone would like to submit a PR?

**Comment by amos402** [comment]
I think this is not a problem that relate to pythonnet, the extension I supplied above can handle this case.
Or you can reference here to make a trace callback when you try to interrupt the work thread.
https://github.com/amos402/py-xtimeout/blob/3f17f5ed050045cd8dc13987ce2abb0187501f88/xtimeout/_xtimeout.cpp#L358-L379

**Comment by heartacker** [comment]
i have the same requirement of stopping runing code embbed in wpf. if there is any easy way to stop them.  tell me thanks

**Comment by kerol2r20** [comment]
I also meet this situation. Is there any idea to stop running script which embedded in C#?
thanks

**Comment by TheCollegedude** [comment]
> I also meet this situation. Is there any idea to stop running script which embedded in C#?
> thanks

it seems we have to wait for 3.0.0
