### ISSUE TITLE
Docs Suggestion: export LD_LIBRARY_PATH for Python 3.7 on mac

### ISSUE THREAD

**Issue by ztl8702** [pythonnet/pythonnet#767]
### Environment

-   Pythonnet version: master https://github.com/pythonnet/pythonnet/commit/f8e147b97112c526c6548e900dee0fc41cdb39b1
-   Python version: 3.7.0
-   Operating System: macOS 10.14.1

### Details

I was getting this runtime error:
```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'python3.7m' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libpython3.7m, 1): image not found
   at Python.Runtime.Runtime.Py_SetPythonHome(IntPtr home)
```

When running a netcoreapp2.1 Console app that uses Python Embedding with pythonnet. I tried setting `PYTHONHOME` but then realised that it seems to be a solution for a different problem.

Here is my csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.1</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="7.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Python.Runtime">
      <HintPath>.\pythonnet\build\lib.macosx-10.13-x86_64-3.7\netcoreapp2.0\Python.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="pythonnet\**\*" />
    <Compile Remove="pythonnet\src\**\*.cs" />
  </ItemGroup>
</Project>
```

----

This suggestion did _not_ work for me:

> CPython is not installed, or not registered in %PATH% and %PYTHONHOME% environment variables. 
> Alternatively set PythonEngine.PythonHome property before initializing Python runtime.

Neither setting $PATH and $PYTHONHOME nor `PythonEngine.PythonHome` property had any effect.

----

The solution that eventually worked for me was to set `LD_LIBRARY_PATH` as follows:
```
export LD_LIBRARY_PATH=/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/:$LD_LIBRARY_PATH
```

I noticed that this has not been in the [Troubleshooting Docs](https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX). **Therefore would like to suggest adding this fix to the docs.**

---

Plus, I noticed that after this fix, CPython can be successfully loaded into .NET Core. If I _then_ try to set $PYTHONHOME or `PythonEngine.PythonHome` to, say, `/usr/local/lib/python3.7/`, it will confuse CPython and cause the following error:

```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000000115f675c0 (most recent call first):
```

However if I do _not_ set `PythonEngine.PythonHome` and `unset PYTHONHOME`, it will work just fine. A quick look at the [Python docs](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME) shows that Python 3 will default to `prefix/lib/pythonversion`, which works on my machine.

So it seems to me that in my situation the correct solution is:
  - Leave `PYTHONHOME` unset
  - Include `/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/` in $LD_LIBRARY_PATH

I am not an expert of Python or pythonnet, so I actually do not understand _why_ it worked this way. **Would love to hear some insights on this.**  Thanks!

**Comment by denfromufa** [comment]
@ztl8702 is this macos/osx specific or the same observation on linux?

**Comment by lokinfey** [comment]
Anyone know about that :

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   python3.7m.dylib              	0x0000000109de8a37 PyUnicode_InternInPlace + 116
1   python3.7m.dylib              	0x0000000109e010b4 PyUnicode_InternFromString + 32
2   python3.7m.dylib              	0x0000000109e4c781 PyImport_Import + 87
3   python3.7m.dylib              	0x0000000109e4b228 PyImport_ImportModule + 28
4   ???                           	0x0000000116446c45 0 + 4668550213
5   ???                           	0x0000000116446afd 0 + 4668549885
6   ???                           	0x00000001164422f6 0 + 4668531446
7   libcoreclr.dylib              	0x0000000107722837 CallDescrWorkerInternal + 124
8   libcoreclr.dylib              	0x0000000107582c04 MethodDescCallSite::CallTargetWorker(unsigned long const*, unsigned long*, int) + 964
9   libcoreclr.dylib              	0x0000000107450cb7 RunMain(MethodDesc*, short, int*, PtrArray**) + 775
10  libcoreclr.dylib              	0x0000000107451042 Assembly::ExecuteMainMethod(PtrArray**, int) + 402
11  libcoreclr.dylib              	0x000000010749312a CorHost2::ExecuteAssembly(unsigned int, char16_t const*, int, char16_t const**, unsigned int*) + 442
12  libcoreclr.dylib              	0x00000001073c1524 coreclr_execute_assembly + 260
13  libhostpolicy.dylib           	0x00000001072ef148 0x107267000 + 557384
14  libhostpolicy.dylib           	0x00000001072d87c7 0x107267000 + 464839
15  libhostpolicy.dylib           	0x00000001072df069 0x107267000 + 491625
16  libhostfxr.dylib              	0x0000000107203223 0x10717a000 + 561699
17  libhostfxr.dylib              	0x0000000107222f44 0x10717a000 + 692036
18  libhostfxr.dylib              	0x0000000107225b22 0x10717a000 + 703266
19  libhostfxr.dylib              	0x0000000107223fd8 0x10717a000 + 696280
20  libhostfxr.dylib              	0x0000000107204299 0x10717a000 + 565913
21  dotnet                        	0x000000010714e402 0x107142000 + 50178
22  dotnet                        	0x000000010714e9f5 0x107142000 + 51701
23  libdyld.dylib                 	0x00007fff5aa173d5 start + 1

**Comment by gumbarros** [comment]
> @ztl8702 is this macos/osx specific or the same observation on linux?

This also happens on Linux.

**Comment by ztl8702** [comment]
(yeah sorry I haven't been using pythonnet recently)
