### ISSUE TITLE
Could you put up a detailed install procedure please, for .net developers who are new to Python

### ISSUE THREAD

**Issue by acrigney** [pythonnet/pythonnet#774]
### Environment

-   Pythonnet version:
-   Python version:
-   Operating System:

### Details

-   Describe what you were trying to get done.

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by filmor** [comment]
We have a Wiki that contains quite a bit of information.

**Comment by denfromufa** [comment]
There are also almost 300 Q&A on stackoverflow with "python.net" tag
