### ISSUE TITLE
New Release Version/NuGet Version?

### ISSUE THREAD

**Issue by thomashzhang** [pythonnet/pythonnet#778]
Apologize for not following the issues template, but the issue isn't related to implementation.

It seems like the last time a NuGet package was released was "Thursday, March 16, 2017 (3/16/2017)". Are there plans to update the package as it seems like there was a lot of work done the commits! Thank you.

**Comment by filmor** [comment]
We plan to release a new version before end of 2018. Check the 2.4.0 to see what still needs to be handled.
