### ISSUE TITLE
Same name functions , the pythonnet donl't found right function.

### ISSUE THREAD

**Issue by jiftle** [pythonnet/pythonnet#782]
### Environment

-   Pythonnet version: 2.3
-   Python version: Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
-   Operating System: win7 x64

### Details

-   Same name functions , the pythonnet donl't found right function.
**error info**
```python
Traceback (most recent call last):
  File "testdll.py", line 111, in <module>
    ret = _Interpreter.csc(1, filename, paramlist, errMsg)
TypeError: No method matches given arguments
```
**mycode**
  ```c#
public int csc(int type, string filename, strtParam[] paramArray, ref string strErr)
public int csc(string filename, strtParam[] paramArray, ref string strErr)
  ```
-   Modify code ,use different function name just successed.
**midify code**
```c#
public int cscPT(int type, string filename, strtParam[] paramArray, ref string strErr)
        {
            return csc(type, filename, paramArray, ref strErr);
        }
```

**Comment by filmor** [comment]
So, the modified code works?

**Comment by jiftle** [comment]
@filmor 
yes , it work good.

**Comment by filmor** [comment]
That's strange I'll try to reproduce it.

**Comment by jiftle** [comment]
@filmor 
thank you very much, you are good author.

**Comment by denfromufa** [comment]
This is from the method overloading pile, let me know if this is not covered by existing items:

https://github.com/pythonnet/pythonnet/issues/265

**Comment by lostmsu** [comment]
Just got this error. Can anyone explain why this happens when one of my overloads has matching number of arguments, and they are all of type `object`? E.g. surely this one can be called. Or does this error happen also when there's an ambiguity? In the later case, can the error be fixed to indicate that?
