### ISSUE TITLE
[Type Conversion] TypeError: Cannot convert 10 to System.Int32[]

### ISSUE THREAD

**Issue by amRsching** [pythonnet/pythonnet#788]
### Environment

-   Pythonnet version: 2.4.0 (master branch)
-   Python version: 3.7.0 (Anaconda)
-   Operating System: Windows 10

### Details

-   Describe what you were trying to get done.

    I think I've successfully installed the pythonnet. And all the demos work. But when I go through the homepage to verify my installation, there's something wrong. I'm sure it's because there's some problem for my installation or any change happened for pythonnet.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

<img width="557" alt="1" src="https://user-images.githubusercontent.com/22640166/49239918-cf2a7b80-f3b8-11e8-800f-a9a62003133b.png">

This usage is from the block of 'Using Arrays' on http://pythonnet.github.io/ 

I think for pythonnet, most elemental Python types (string, int, long, etc.) convert automatically to compatible managed equivalents (String, Int32, etc.) and vice-versa. So I've no idea about this.

**Comment by denfromufa** [comment]
related: https://github.com/pythonnet/pythonnet/issues/251
