### ISSUE TITLE
How to use external assembly (.dll) in pythonnet

### ISSUE THREAD

**Issue by amRsching** [pythonnet/pythonnet#789]
### Environment

-   Pythonnet version: 2.4.0 (master branch)
-   Python version: 3.7.0 (Anaconda)
-   Operating System: windows 10

### Details

-   Describe what you were trying to get done.

    I want to use external assembly (.dll) as api client.
    I found a previous issue:
    https://github.com/pythonnet/pythonnet/issues/459
    I guess our situations are a little similar. Works well in C#, but not in pythonnet.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

This is my sample code in VS2017.
<img width="939" alt="1" src="https://user-images.githubusercontent.com/22640166/49318004-a9ca6a00-f4ab-11e8-8f40-ea70cdd0ebf7.png">

But doesn't work in Jupyter notebook.
<img width="429" alt="2" src="https://user-images.githubusercontent.com/22640166/49318005-ad5df100-f4ab-11e8-886d-de2bc824683d.png">

**Comment by denfromufa** [comment]
Are all dependencies located in the same directory?
Did you try inspecting the references of this assembly with ILSPY to see if
some hidden dependencies could not be located?
Finally you can inspect the logs of assembly binding log viewer to see the
loading errors:

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX#assembly-binding-errors

**Comment by amRsching** [comment]
Thank you for your reply.

For my C# sample project all the DLLs are in the same directory, because I use these external assembly by directly modifying the .csproj file.

But for the jupyter notebook they aren't. Because I think I've add the corresponding folder to the sys.path, which should be equivalent to in the same directory.

I've added the ILSPY to my VS2017. But how to check the hidden dependencies? What is valid? What is invalid?

**Comment by denfromufa** [comment]
@amRsching search this issue tracker for ilspy usage.

**Comment by denfromufa** [comment]
closed due to inactivity
