### ISSUE TITLE
clr throws (File is blocked (NTFS Security)) error when trying to AddReference on Windows10

### ISSUE THREAD

**Issue by amRsching** [pythonnet/pythonnet#791]
### Environment

-   Pythonnet version: 2.4.0 (master branch)
-   Python version: 3.7.0 (Anaconda)
-   Operating System: Windows 10

### Details

-   Describe what you were trying to get done.

    I'm trying to use clr to add a reference to a DLL.
    I find a similar issue as follows.
    https://github.com/pythonnet/pythonnet/issues/732
    But it seems his scripts works well on Windows. But this time, I have exception even on Windows.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

    When I scanned the previous issues, I found someone said not to contain .dll when adding reference. So I tried different combinations. It turns out to be a little strange. Please check the picture below.

<img width="571" alt="1" src="https://user-images.githubusercontent.com/22640166/49551786-833e7180-f8a5-11e8-9976-09d469da39f4.png">

**Comment by denfromufa** [comment]
closing, let's keep track here:

https://github.com/pythonnet/pythonnet/issues/732
