### ISSUE TITLE
ValueError : call stack is not deep enough

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#792]
### Environment

-   PythonNET version: 2.3.0
-   Python version: 3.6.6
-   Operating System: Windows 10 x64

### Details

```csharp
Environment.SetEnvironmentVariable("PATH", @"C:\Path\To\Python;"
                + Environment.GetEnvironmentVariable("PATH"));
PythonEngine.PythonHome = @"C:\Path\To\Python";
PythonEngine.Initialize();

dynamic flags = ((dynamic)PythonEngine.ImportModule("tensorflow")).app.flags;
flags.DEFINE_integer("batch_size", 32, "Number of samples per batch");
```

### Steps:
1. Install tensorflow-gpu 1.10 (version might be important)
2. Configure PythonNET to call from C# into Python
3. Get tensorflow.app.flags (see above)
4. Invoke `flags.DEFINE_integer("batch_size", 32, "Number of samples per batch")`

### Problem
Expected: should succeed.
Actual: `Python.Runtime.PythonException: 'ValueError : call stack is not deep enough'`

This works fine:
```python
import tensorflow as tf
flags = tf.app.flags
flags.DEFINE_integer("batch_size", 32, "Number of samples per batch")
```

**Comment by denfromufa** [comment]
@lostmsu might be worth investigating in tensorflow, looks like a common issue for embedded python:

https://github.com/search?q=%22call+stack+is+not+deep+enough%22&type=Issues

**Comment by denfromufa** [comment]
@lostmsu this issue in not reproducible in earlier TF version hence reported to their issue tracker:

https://github.com/tensorflow/tensorflow/issues/24211

**Comment by lostmsu** [comment]
It might be a problem with Python itself. AFAIK, flags is actually coming from absl, e.g. https://github.com/abseil/abseil-py

**Comment by denfromufa** [comment]
@lostmsu yes, very similar problem in abseil with Swift for Tensorflow:

https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/Pr9LVkyUg8c

**Comment by filmor** [comment]
@lostmsu Is this still relevant?

**Comment by lostmsu** [comment]
I reproduced the issue on current master, but it appears to be an issue with one of the upstream libraries.

The smallest repro for the issue is calling `inspect.currentframe()` directly from .NET. I think the behavior is either by design or a bug in `currentframe`.
