### ISSUE TITLE
Windows 8 install error

### ISSUE THREAD

**Issue by qyangcaltech** [pythonnet/pythonnet#793]
### Environment

-   Pythonnet version: master
-   Python version: 3.7.0
-   Operating System: Windows 8 

### Details

-   Tried to install it from either package downloaded or pip install git+https://github.com/pythonnet/pythonnet
-  Also tried updating Wheel and Setuptools
-  Got the same error as following

$ pip install git+https://github.com/pythonnet/pythonnet
Collecting git+https://github.com/pythonnet/pythonnet
  Cloning https://github.com/pythonnet/pythonnet to c:\users\ateam\appdata\local\temp\pip-req-build-z0r5bt1p
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet: started
  Running setup.py bdist_wheel for pythonnet: finished with status 'error'
  Complete output from command c:\users\ateam\anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ateam\\AppData\\Local\\Temp\\pip-req-build-z0r5bt1p\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Ateam\AppData\Local\Temp\pip-wheel-9rfuysvc --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 4.7.1.
  Update successful.
  Cannot find the specified version of msbuild: '14'
  MSBuild auto-detection: using msbuild version '15.9.20.62856' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.ConsoleRunner.3.7.0.
  Restoring NuGet package NUnit.3.7.1.
  Adding package 'NUnit.3.7.1' to folder 'C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\packages'
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\packages'
  Adding package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\packages'
  Added package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\packages'
  Added package 'NUnit.3.7.1' to folder 'C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\packages'

  NuGet Config files used:
      C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\NuGet.Config
      C:\Users\Ateam\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      C:\Users\Ateam\.nuget\packages\
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      https://api.nuget.org/v3/index.json

  Installed:
      3 package(s) to packages.config projects
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\setup.py", line 534, in <module>
      zip_safe=False,
    File "c:\users\ateam\anaconda\lib\site-packages\setuptools\__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\ateam\anaconda\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\ateam\anaconda\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\ateam\anaconda\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\setup.py", line 482, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "c:\users\ateam\anaconda\lib\site-packages\wheel\bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "c:\users\ateam\anaconda\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ateam\anaconda\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\ateam\anaconda\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\ateam\anaconda\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ateam\anaconda\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\ateam\anaconda\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "c:\users\ateam\anaconda\lib\distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "c:\users\ateam\anaconda\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\setup.py", line 257, in build_extension
      manifest = self._get_manifest(dest_dir)
    File "C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\setup.py", line 274, in _get_manifest
      mt = self._find_msbuild_tool("mt.exe", use_windows_sdk=True)
    File "C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\setup.py", line 399, in _find_msbuild_tool
      raise RuntimeError("{0} could not be found".format(tool))
  RuntimeError: mt.exe could not be found

  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet: started
    Running setup.py install for pythonnet: finished with status 'error'
    Complete output from command c:\users\ateam\anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ateam\\AppData\\Local\\Temp\\pip-req-build-z0r5bt1p\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ateam\AppData\Local\Temp\pip-record-uqkgtmup\install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "c:\users\ateam\anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ateam\\AppData\\Local\\Temp\\pip-req-build-z0r5bt1p\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ateam\AppData\Local\Temp\pip-record-uqkgtmup\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Ateam\AppData\Local\Temp\pip-req-build-z0r5bt1p\

**Comment by denfromufa** [comment]
You are missing mt.exe from MSVC build tools.

https://github.com/pythonnet/pythonnet/issues/254

The second error is this:

https://github.com/pythonnet/pythonnet/issues/731

Search the issue tracker for python3.7 installation options (Appveyor artifacts or unofficial wheels)

**Comment by denfromufa** [comment]
@qyangcaltech you are likely getting some issues with this specific version of msbuild/nuget:

`CSC : error CS1617: Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default `
https://github.com/pythonnet/pythonnet/issues/539

Try downgrading your msbuild/nuget or grab the binaries like suggested here:

https://github.com/pythonnet/pythonnet/issues/780#issuecomment-440511159

**Comment by qyangcaltech** [comment]
Hi denformufa,

Thanks again for your response! I followed thread #780  and the unofficial installation worked.
