### ISSUE TITLE
ModuleNotFoundError : No module named 'numpy'"

### ISSUE THREAD

**Issue by frajos100** [pythonnet/pythonnet#794]
### Environment

-   Pythonnet version: latest
-   Python version:3.6.7
-   Windows 10

-   Describe what you were trying to get done.

 Getting error of {"ModuleNotFoundError : No module named 'numpy'"} , The same import runs on Command prompt 
Also tried with importlib  
np= importlib.import_module(\'numpy\')\n', '  File "C:\\Users\\f.fernandes\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\importlib\\__init__.py", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n']

**Comment by denfromufa** [comment]
Can you import numpy as from python?

**Comment by frajos100** [comment]
Resolved the issue by performing the following steps
a)  Python version:3.6.7 uninstalled and deleted the packages
b) Python version 3.6.6 installed and then installed all the packages
c) Python version:3.6.6 uninstalled and deleted the packages
d) Python version 3.6.7 installed and then installed all the packages
There was an update of VIsual Studio due to which it might have broken.
