### ISSUE TITLE
PyBool missing?

### ISSUE THREAD

**Issue by CSharpDummy** [pythonnet/pythonnet#798]
Hi,

I'm using pythonnet to access python function in NET.

I don't see the datatype PyBool or PyLogical. From what I see you could use a PyInt and Python treats 0,1 as boolean in expression. Is there another way to create a boolean with pythonnet?
 
Thanks...

**Comment by CSharpDummy** [comment]
Here is a snippet for a string datatype:
private PyScope _scope;
....
var pythonValue = new PyString(value);
_scope.Set(variableName, pythonValue);

So I was looking if there is something similar for bool ...

**Comment by denfromufa** [comment]
@CSharpDummy booleans are subclass of PyLong:

https://docs.python.org/3/c-api/bool.html
https://github.com/pythonnet/pythonnet/blob/master/src/runtime/pylong.cs

And in pythonnet there have very simple implementation:

https://github.com/pythonnet/pythonnet/blob/bf87239b8b50ca2799e2ff95b9a069d27f0ee0f6/src/runtime/runtime.cs#L310

Conversion is supported too:

https://github.com/pythonnet/pythonnet/blob/f807a81d9ca2b73a91ecf8294eea53c55ecf40cd/src/runtime/converter.cs#L119

**Comment by CSharpDummy** [comment]
Great ... thank you for your help!
