### ISSUE TITLE
how can i make pythonnet interpreter with wpf

### ISSUE THREAD

**Issue by Egnima** [pythonnet/pythonnet#799]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.7.2 32 bit
-   Operating System: Windows 10 home 1803 64 bit

### Details

-   Describe what you were trying to get done.
As a school project I am making python ide with wpf now and i'm trying to make python interpreter 
(like this [one](https://github.com/laynor/IronPythonConsole)) using pythonnet.

I need python 3.7 interpreter in wpf. What should I do?
please help me. thank you.

**Comment by denfromufa** [comment]
@Egnima for Python 3.7 you have to download unofficial wheels for now:

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet

Here is a simple demo for wpf embedding in python. Not sure if you are looking for opposite - embedding python in wpf.

https://github.com/pythonnet/pythonnet/blob/master/demo/DynamicGrid.py

**Comment by Egnima** [comment]
@denfromufa  Thank you for your reply. 
But what I want is embed python 3 repl in wpf.

**Comment by denfromufa** [comment]
Take a look here:

* very long threaded conversation about stdout redirection:
https://code.activestate.com/lists/pythondotnet/1736/

* actual console application (npython.exe) with python interpreter embedded with pythonnet:
https://github.com/pythonnet/pythonnet/tree/master/src/console

* also read this issue and linked and merged PR with stdout communication patterns:
https://github.com/pythonnet/pythonnet/issues/370

**Comment by Egnima** [comment]
@denfromufa  Thanks for the comment again. I'll try again and I'll ask you again if I have a problem.
Thank you :)

**Comment by denfromufa** [comment]
No problem
