### ISSUE TITLE
Error while importing dll AA.BB.CC is not a package

### ISSUE THREAD

**Issue by Annous87** [pythonnet/pythonnet#800]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6.0 (64bit)
-   Operating System: Win7

-   I would like to use some dlls developed by my C# team in my python code.
    Those dlls have many dependancies and different namespace AA.BB.CC
    I download for that NuGets and explore them via NuGet explorer, then I study dependencies using 
    DotPeek tool.
    Using pythonnet, I manage to import most of dlls (all except one) 
    My python module name pricer.py has a different name that all assemblies.

-   When I execute a this script:

```python
   import clr
   clr.FindAssembly(r"path\\myAssembly") # myAssembly is AA.BB.CC.DD
   clr.AddReference(r"path\\myAssembly.dll")
   import myAssembly.EE # Namespace AA.BB.CC.DD.EE
```
 I get this message error: ModuleNotFoundError: No module named 'AA.BB.CC.DD'; 'AA.BB.CC' is not a 
 package
 However, I can successfully import another assembly AA.BB.CC.FF in the same code!
 Can you advise please?
 If it's a dependency problem, how can I figure out what is missing for this assembly?
 Thank you

**Comment by denfromufa** [comment]
@Annous87 did you try with the master branch of pythonnet? If the problem still persists and it is a dependency problem, then it could be some transitive dependency. You may find out more by attached a debugger and inspecting the inner exceptions and the call stack.

**Comment by Annous87** [comment]
**@denfromufa** : I made an new installation based on master branch (version 2.4) and I still have the issue.
with pdb debugger I have this call stack when it succeed for a dll import 
--Call--
> <frozen importlib._bootstrap>(997)_handle_fromlist()
(Pdb)
> <frozen importlib._bootstrap>(1007)_handle_fromlist()
(Pdb)
> <frozen importlib._bootstrap>(1032)_handle_fromlist()
(Pdb)
--Return--
> <frozen importlib._bootstrap>(1032)_handle_fromlist()-><module '....cingExecutor'>
(Pdb)

However, that raise these errors when it fail for the other assembly:
--Call--
> <frozen importlib._bootstrap>(966)_find_and_load()
(Pdb)
> <frozen importlib._bootstrap>(968)_find_and_load()
(Pdb)
--Call--
> <frozen importlib._bootstrap>(143)__init__()
(Pdb)
> <frozen importlib._bootstrap>(144)__init__()
(Pdb)
> <frozen importlib._bootstrap>(145)__init__()
(Pdb)
--Return--
> <frozen importlib._bootstrap>(145)__init__()->None
(Pdb)
--Call--
> <frozen importlib._bootstrap>(147)__enter__()
(Pdb)
> <frozen importlib._bootstrap>(148)__enter__()
(Pdb)
--Call--
> <frozen importlib._bootstrap>(157)_get_module_lock()
(Pdb)
> <frozen importlib._bootstrap>(163)_get_module_lock()
(Pdb)
> <frozen importlib._bootstrap>(164)_get_module_lock()
(Pdb)
> <frozen importlib._bootstrap>(165)_get_module_lock()
(Pdb)
 <frozen importlib._bootstrap>(176)_get_module_lock()
(Pdb)
> <frozen importlib._bootstrap>(187)_get_module_lock()
(Pdb)
> <frozen importlib._bootstrap>(189)_get_module_lock()
(Pdb)
> <frozen importlib._bootstrap>(191)_get_module_lock()
(Pdb)
--Return--
> <frozen importlib._bootstrap>(191)_get_module_lock()->_ModuleLock('...') at 67019888
(Pdb)
> <frozen importlib._bootstrap>(149)__enter__()
(Pdb)
--Call--
> <frozen importlib._bootstrap>(78)acquire()
(Pdb)
> <frozen importlib._bootstrap>(84)acquire()
(Pdb)
> <frozen importlib._bootstrap>(85)acquire()
(Pdb)
> <frozen importlib._bootstrap>(86)acquire()
(Pdb)
> <frozen importlib._bootstrap>(87)acquire()
(Pdb)
> <frozen importlib._bootstrap>(88)acquire()
(Pdb)
> <frozen importlib._bootstrap>(89)acquire()
(Pdb)
> <frozen importlib._bootstrap>(90)acquire()
(Pdb)
> <frozen importlib._bootstrap>(91)acquire()
(Pdb)
> <frozen importlib._bootstrap>(92)acquire()
(Pdb)
> <frozen importlib._bootstrap>(101)acquire()
(Pdb)
KeyError: 5732
> <frozen importlib._bootstrap>(101)acquire()
(Pdb)
--Return--
> <frozen importlib._bootstrap>(101)acquire()->None

Do you have some ideas?

**Comment by denfromufa** [comment]
You need to use the C#/.NET debugger in Visual Studio

**Comment by denfromufa** [comment]
And compile debug version of pythonnet

**Comment by denfromufa** [comment]
closed due to inactivity
