### ISSUE TITLE
Feature request : specify python lib at runtime for coreclr

### ISSUE THREAD

**Issue by fradav** [pythonnet/pythonnet#804]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.6
-   Operating System: Windows/Linux

### Details

-   Describe what you were trying to get done.

My use case is using Python.Runtime from c#/f#, I use generated nuget packages from visual studio. 
I got one on my Windows developper machine and I have to make another for deploying to docker/linux, which is painful.
Problem is that for each platform I have to switch the target (ReleaseMonoPY3 and ReleaseWindowsPy3 for example). Currently I have to manage several .nupkg by hand with absolutely no way to distinguish between them (there are all Python.Runtime 2.4.0/netstandard, not platform tagging)

Ideally, I would like to have python lib runtime library and os specified and/or detectable at runtime. 
something like 
```
if (linux)
   PythonEngine.PythonLib <- "/usr/lib/libpython.3.6m"
else 
  PythonEngine.PythonLib <- "python36.dll"
```

**Comment by denfromufa** [comment]
@fradav you mean something like this?

https://github.com/pythonnet/pythonnet/pull/244

**Comment by dmitriyse** [comment]
I found the sources of my work that relates to runtime load of any python library!
You should clone this repo https://github.com/dmitriyse/pythonnet.root

But it's too hard to merge this work back to pythonnet master

**Comment by filmor** [comment]
@dmitriyse Just to get this straight, license-wise there is no change and we /could/ work on merging it, is that right?

**Comment by dmitriyse** [comment]
Yes, it have MIT license.
