### ISSUE TITLE
Make available additional binaries

### ISSUE THREAD

**Issue by GSPP** [pythonnet/pythonnet#807]
It is [documented](https://github.com/pythonnet/pythonnet/wiki/Installation) that binaries can be taken from the job artifacts. I tried [Python 3.6, x64](https://ci.appveyor.com/project/pythonnet/pythonnet/branch/master/job/7kqj28wmvgf1i6ji/artifacts). The artifacts do not contain binaries. Please make them available. In case I just did not find them consider documenting the location better.

**Comment by filmor** [comment]
The wheel contains the Python.Runtime.dll and clr.pyd, that's all that is needed from Python.NET. I think the .tar.gz that is also in this directory only contains the sources that were used for this particular build. Feel free to reopen if the wheel doesn't work for you :)
