### ISSUE TITLE
System.InvalidProgramException:Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by BenDerPan** [pythonnet/pythonnet#809]
### Environment

-   Pythonnet version: 2.4.0.dev
-   Python version:3.6.4 x64
-   Operating System:win10 x64

### Details

-   Describe what you were trying to get done.

    I want to load a .net/.netcore dll, and use the class in the dll.
    but I got exception when `import clr`
    
exception:
```bash
未经处理的异常:  System.InvalidProgramException: 公共语言运行时检测到无效的程序。
   在 clrModule.PyInit_clr()
```
I also wish to know if it support .netcore dll, thanks ：）

## python code:
```python
import clr

clr.AddReference("TestPython.Core")
print("OK")
from TestPython.Core import *


m = Man()
msg=m.Say("hi,big man!")

input("press enter to exit...")
```
## C# code(a simple library project only contains one class, .netframework4.6.1):
```C#
using System;

namespace TestPython.Core
{
    public class Man
    {
        public string Name { get; set; }
        public Man()
        {

        }

        public Man(string name)
        {
            Name = name;
        }

        public int Add(int a, int b)
        {
            return a + b;
        }

        public string Say(string msg)
        {
            var fullMsg = $"{Name} Say: {msg}";
            Console.WriteLine(fullMsg);
            return fullMsg;
        }
    }

}

```

## Exception:
`未经处理的异常:  System.InvalidProgramException: 公共语言运行时检测到无效的程序。
   在 clrModule.PyInit_clr()`

**Comment by denfromufa** [comment]
can you try with English-US locale? Also translate your errors to English.

**Comment by BenDerPan** [comment]
@denfromufa  sorry,  the exception:
```bash
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
clrModule.PyInit_clr()
```

**Comment by denfromufa** [comment]
did you try with English-US locale?

**Comment by BenDerPan** [comment]
@denfromufa  yes I changed to English-US locale, I worked after I reinstall pythonnet.  thanks!

**Comment by filmor** [comment]
This is an entirely unrelated issue. Please ask for support on StackOverflow, the issue tracker is used only for bug and feature tracking.

In your particular case, it could be that the dependencies could not be found or that `TimerEngine.Core.dll` actually uses a different namespace. Try explicitly adding all dependencies using `clr.AddReference` and print the return value.
