### ISSUE TITLE
Ability to specify a name resolver for different naming conventions

### ISSUE THREAD

**Issue by uberclops** [pythonnet/pythonnet#81]
Hi everyone, I thought it would be a nice feature to be able to specify a name resolver to allow a different naming convention to be used from python.

Right now you need to access methods / properties using whatever casing you use from .NET (so pascal-case in most cases), but from python most seem to use lower-case / camel-case names.

I altered `ClassManager.GetClassInfo` calls to `MethodInfo.Name` and lower-cased them, and that seemed to work fine for a quick test, but I don't know enough about the internals of this project to know what other issues this could cause.

**Comment by tonyroberts** [comment]
My personal view is that it's better to leave methods and properties as they are defined in .NET.

Modifying them in any way, even to make it more pythonic, means your Python code will be less instantly readable by someone familiar with the original API. Also it means methods and properties used in your code won't match up with any of the API docs making it less obvious what's going on in your Python code.

It's common for wrapped APIs to stick with conventions set out in the API they're wrapping (Qt, Wx etc).

**Comment by uberclops** [comment]
While agree with this, the specific use-case I have in mind has people who are not necessarily programmers (they have some programming experience and access to API docs we give them) editing some basic scripts for business logic. Certain objects will be exposed for the scripts to use.

Casing is sometimes a difficult concept for people at this level of experience to grasp, and asking them to get used to, and remember, which methods / properties to use pascal-case or camel-case for, is asking a lot.

So while I agree it's probably best practice to keep them separate, it would be nice to have the option to use a different convention if you needed to.

**Comment by vmuriart** [comment]
`PyWin32` does something similar to this and I found the feature to be very confusing. In part because some methods were case insensitive, while others weren't but granted this may be an issue with `PyWin32`.

A more concrete example is the following case

```csharp
        public static string CaseSensitive()
        {
            return "CaseSensitive";
        }

        public static string Casesensitive()
        {
            return "Casesensitive";
        }
```

```python
    res = MethodTest.CaseSensitive()
    res = MethodTest.Casesensitive()
    res = MethodTest.casesensitive()
```

It would be complicated to figure which method the user actually meant to call.
