### ISSUE TITLE
How to notify c# caller from python function when embedded in c#

### ISSUE THREAD

**Issue by szcnshow** [pythonnet/pythonnet#810]
I'm embedding python in c# now. When I'm calling a long time consuming python function, I want the python function notify the process to c# caller, how can I do this?

### Environment
Python 3.6, C#

'''Example

    def long_time_worker(callback):
        'callback: c# function'

        for i in range(1000):
            #do some work.......
            callable(i)  #notify current step to caller

**Comment by filmor** [comment]
This is very much unrelated to C# or Python.NET. You can just use different threads for the notified C# code and the Python function. Maybe try to get things working in pure Python or pure C# first and then try to adapt it. If you hit a roadblock, try something like StackOverflow, this issue tracker is used exclusively for bug/feature tracking of Python.NET.

**Comment by denfromufa** [comment]
@filmor i actually think that this could be a valuable best practice, if there is any easy way to do this. For example this may be accomplished via file object or stdout or logging. But I agree that stackoverflow may be a better place to put this and maybe link back here later.

**Comment by szcnshow** [comment]
Thank you @filmor @denfromufa , I'll post this question on stackoverflow.
