### ISSUE TITLE
Requesting wheel and conda binary release for Python 3.7

### ISSUE THREAD

**Issue by agilevic** [pythonnet/pythonnet#812]
Could you make the wheel and conda packages compatible with Python 3.7? Both PyPi and your channel on Anaconda only support up to Python 3.6.

https://pypi.org/project/pythonnet/#files

https://anaconda.org/pythonnet/pythonnet/files

**Comment by filmor** [comment]
As outlined in #509, I'm going to look into this soonish. I plan to release an RC for 2.4.0 next week to those channels.

**Comment by anamariamocanu** [comment]
Hi @filmor, any update on when that's going to happen? Many thanks

**Comment by filmor** [comment]
I've just published wheels for 2.4.0rc2 to Pypi, please go ahead and test it. This will become 2.4.0 if there is no release-blocking issue.
