### ISSUE TITLE
Pythonnet crashes in command line application

### ISSUE THREAD

**Issue by CSharpDummy** [pythonnet/pythonnet#814]
### Environment

-   Pythonnet version: compiled from masterbranch
-   Python version: 3.7
-   Operating System: windows 10

### Details

-   Describe what you were trying to get done.

I developed an app that app that works in unit tests but then chrashes or hangs in run time.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
The code is pretty much the same as TestPyScope. All the test cases executes successful, just when it’s called in a stand-alone it hangs.

My questions are: how can I narrow down the issue? 
Is 3.7 already fully supported?
Any ideas what it could be related to? It’s a single thread app, so there shouldn’t be any locking issue.
```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by filmor** [comment]
I'm sorry, we cannot provide that level of support here.

3.7 is supported on the master branch, if your example works with 3.6 but not 3.7, that's likely a bug.

If you have a stack trace that would greatly help with the error search, but the issue is only relevant if it's due to a bug in Python.NET.

**Comment by CSharpDummy** [comment]
It was a threading issue: unit test was single threaded and runtime called the Python code from a background thread.

All good now 👍
