### ISSUE TITLE
RFC: Dropping support for Python 3.4

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#817]
While looking into how to perform the release of version 2.4.0 I noticed that the `interop` files for all versions above 3.4 are completely identical while 3.4 is still missing the struct fields for `async`. Thus, by dropping Python 3.4 from the list of supported versions, we could get away with a version for Python 2 and 3 each instead of individual ones.

Would this pose a serious trouble for someone here? I'd leave the code for 3.4 around, I would just not provide an "official" release for this version. Long-term goal would be to get down to a single .NET Standard Python 3 nuget package and wheel.

**Comment by jpvlsmv** [comment]
According to https://www.python.org/dev/peps/pep-0429/, python3.4 is end of life -- no further patches will be (officially) released.

By dropping support for 3.4, will that mean that you will instantly support 3.7 and 3.8 (and 3.9 when it comes), assuming those releases don't need special handling?  That would be a big gain.

**Comment by denfromufa** [comment]
There was something special about tuples in Python  3.4 that should be in this issue tracker. 

Dropping Python 3.4 has nothing to do with supporting new python versions. It is more about maintainability.

**Comment by filmor** [comment]
Indeed, it won't make much of a difference. Although, nowadays I understand a lot better how the interop and release process works, so we might be able to provide 3.8 support immediately on release (October 19). I have also lined out some planning in https://github.com/pythonnet/pythonnet/wiki/Plan that should simplify things, and I wouldn't want to do new things with 3.4 compat in mind.

**Comment by filmor** [comment]
It's decided then, 2.4.0 is the last version to officially support 3.4.
