### ISSUE TITLE
Enable mono debug information

### ISSUE THREAD

**Issue by takumn** [pythonnet/pythonnet#820]
### Environment

-   Pythonnet version: 2.2.2
-   Python version: 3.6.1
-   Operating System: macOS/Linux

### Details

I want to get source files and line numbers partially from stack traces when exceptions occur inside monoclr, but currently it shows only`<filename unknown> :0`.

https://gist.github.com/jpcy/8646147#correct-source-files-and-line-numbers

According to this gist, `mono_debug_init(MONO_DEBUG_FORMAT_MONO);` seems to work, so I tried the patch like this:
https://github.com/takumn/pythonnet/commit/2293744036c626eec949bef7d5c6c9439454f118

It actually worked for DLL files compiled with `/debug` flag. Is it possible to extend `PyNet_Init` function  for enabling mono debug information?

**Comment by filmor** [comment]
What is the runtime impact of this? Python.NET is already quite slow, I wouldn't want to enable this if it slows the whole thing down even more.

**Comment by denfromufa** [comment]
@filmor it is possible to use the condition compilation symbol `IF DEBUG` to handle this.

**Comment by lostmsu** [comment]
@filmor this might be an option in `pythonnet` module.

**Comment by filmor** [comment]
See https://github.com/pythonnet/clr-loader/issues/13.
