### ISSUE TITLE
Array not modified

### ISSUE THREAD

**Issue by gnimor** [pythonnet/pythonnet#822]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6
-   Operating System: Windows 10

### Details

I have a .net method with the following signature:

`public long CalculateCoefficients(long id, long index, double[] coefficient)`

The method is modifiying the coefficient array internally. So after calling the method I have a modified array. Within the "CalculateCoefficients" method the array will be changed like this:

```
			for (int i = 0; i < 6; i++)
			{
				coefficient[i] = DoCalcuations();
			}
```

Now when I call this method with pythonnet I do the following:

```
    coefficients = 6 * [0.0]
    ret = myinstance.CalculateCoefficients(0, 0, coefficients)
```

The call returns without error but the array is not modified. It seems that within the method a copy of the array will be used and modified. Is this a bug or do I something wrong here?

**Comment by maximlt** [comment]
Hi,
You could have a look at the following StackOverflow [question ](https://stackoverflow.com/questions/54692267/python-net-call-c-sharp-method-which-has-a-return-value-and-an-out-parameter/54748602#54748602) to which I've answered something that might help you. I hope this helps!

**Comment by gnimor** [comment]
@maximlt : This was the right advise - Thanks!

Even if the method signature does not contain a 'ref' or 'out' parameter, the correct data type was the key here. After changing the code to:

```
    coefficients = Array[System.Double](6*[.0])
    ret = myinstance.CalculateCoefficients(0, 0, coefficients)
```
Everything works as expected.
