### ISSUE TITLE
No support for operating system

### ISSUE THREAD

**Issue by Syncinus** [pythonnet/pythonnet#826]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.2
-   Operating System: Windows 7 Home Premium

### Details

When compiling pythonnet from source, produces an error saying 'No support for ���s' when running it on ucs4, on ucs2 the error goes away, this also happens for the machine type.

This also happened when i was on python 3.5

**Comment by filmor** [comment]
What exactly did you try and what exactly was the output?

**Comment by denfromufa** [comment]
You should not manually change UCS2/UCS4 - it is set based on platform configuration in VS solution or calculated from setup.py during installation with Python.

**Comment by Syncinus** [comment]
It was set to ucs4 and this happened.

**Comment by Syncinus** [comment]
It came set as ucs4, and i was trying to run the basic pythonconsole.cs

**Comment by filmor** [comment]
Again, for us to say anything of use with regard to your problem, you will need to write down what exactly you did and what exactly the error was.

**Comment by denfromufa** [comment]
closed due to inactivity
