### ISSUE TITLE
Kernel crashed after variable assigning System.Double() 

### ISSUE THREAD

**Issue by simple-engineer** [pythonnet/pythonnet#827]
### Environment

-   Pythonnet version: 2..3.0
-   Python version: 3.6.5
-   Operating System: Windows10

### Details

Hi, I am new at Pythonnet.. and Python globally (I am sleftaught, and it has been only 1.5 years that I am coding, and barely had any coding education before!), so please bare with me

I am trying to call an element in a VB .NET written DLL through a Python code

I decompressed the DLL using JetBrains dotpeek software and it goes like this:

```
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;
using System;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Windows.Forms;

namespace CTool
{
  public class tool
  {
    public void Frist_Order_Approximation(double[] Xdata, double[] Ydata, ref double A, ref double B)
    {
      double Ave1;
      double stdev1;
      this.Get_Ave_Stdev(Xdata, ref Ave1, ref stdev1);
      double Ave2;
      double stdev2;
      this.Get_Ave_Stdev(Ydata, ref Ave2, ref stdev2);
      double[] Xdata1 = Xdata;
      double[] Ydata1 = Ydata;
      double num1;
      float num2 = (float) num1;
      ref float local = ref num2;
      this.Get_Covariance(Xdata1, Ydata1, ref local);
      double num3 = (double) num2;
      A = num3 / Math.Pow(stdev1, 2.0);
      B = Ave2 - A * Ave1;
    } 
```

I want to send 2 arrays Xdata and Ydata and return 2 float values A and B. For that purpose I wrote this:

```
import sys
import clr
import System
from System import *
sys.path.append(r"C:\\Users\\myPC\\desktop\\")
clr.AddReference('CTool')
from CTool import *

Pytool=tool()

Xdata=System.Array[float]([1,2,4])
Ydata=System.Array[float]([1,4,16])
a=System.Double
b=System.Double

print(tool.Frist_Order_Approximation(Xdata,Ydata,a,b))
```

And I got the following error message: `TypeError: No method matches given arguments`

So I suppose I am using the wrong syntaxe

    _TODO_

To workout the right syntaxe, I was trying change every element from that last line `print(tool.Frist_Order_Approximation(Xdata,Ydata,a,b))`

but when I wrote this line `a()`, the kernel just stopped, and I got this message:

> Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
> at Python.Runtime.ManagedType.GetManagedObject(IntPtr ob)
> at Python.Runtime.ClassBase.tp_richcompare(IntPtr ob, IntPtr other, Int32 op) Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
> at Python.Runtime.ManagedType.GetManagedObject(IntPtr ob)
> at Python.Runtime.ClassBase.tp_richcompare(IntPtr ob, IntPtr other, Int32 op)

Questions:
1- Can anyone tell me what I did wrong?
2- For the moment all functions in the DLL, I shared above, were declared within the DLL (for example: "Get_Ave_Stdev" or "Get_Covariance", are declared somewhere in that same DLL), but shall I adopt a different approach of .NET functions/elements?

Thanks

**Comment by filmor** [comment]
This kind of question belongs on StackOverflow, this here is the issue tracker which is meant for feature requests and bug reports.

Regarding your problem at hand, do something like this:

```python
 Xdata=System.Array[System.Double]()
for i in [1, 2, 4]:
    Xdata.Add(i)
#...
a = System.Double(0)
b = System.Double(0)
# ...
```

**Comment by simple-engineer** [comment]
Hi filmor

Thank you so much for your help. 

Even though `Xdata.Add(i)` didn't work (I got this error message `AttributeError: 'Double[]' object has no attribute 'Add'`), but the second part `a = System.Double(0)` did the job.

In fact, I wanted to report the Kernel crash but, once again, I am new at all this.

I will check more carefully StackOverflow from now on
Cheers

**Comment by denfromufa** [comment]
Also this is definitely not a kernel crash :) I would be interested to see if anyone managers to crash the OS KERNEL with pythonnet
