### ISSUE TITLE
Converting a c# array to a python list

### ISSUE THREAD

**Issue by Syncinus** [pythonnet/pythonnet#828]
Currently, there is no way i have found to convert a double array to a python list,
which i must do to use tflearn and tensorflow inside c#
```csharp
            using (Py.GIL())
            {
                using (PyScope scope = Py.CreateScope())
                {
                    double[] test = new double[] { 1, 2, 3, 4, 5 };

                    scope.Set("test", test.ToPython());
                    Console.WriteLine(scope.Variables().GetItem("test").ToString());
                    // Should return System.Double[]

                    PyObject testpy = scope.Eval("tst = [1, 2, 3, 4, 5]");
                    Console.WriteLine(testpy.ToString());
                    // Should return [1, 2, 3, 4, 5]
                }
            }
```
Shouldn't there be a method to convert c# arrays to a python lists? Or am i missing something?

**Comment by filmor** [comment]
There is currently no such method. `ToPython` will (for the most part losslessly) wrap .NET objects s.t. they can be used as is in Python. Only a selected set of types (strings, numbers, etc.) are one-to-one translated. Contributions are welcome, though it's not completely clear to me how such an interface would look like.

**Comment by evandavey** [comment]
So there is no way to use ToPython on a custom C# class?  I am trying to using a PyDict where the value is a C# class.  I've tried ToPython and PyObject.FromManagedObject(..) but both crash.
If I use a C# Dictionary instead I can loop through it and convert to a python dictionary within python but this is messy.

```
MyClass c = new MyClass()
PyDict d = new PyDict()
d.setItem("key",  c.ToPython()) // crash
d.setItem("key", PyObject.FromManagedObject(c)) // crash
```

```
def todict(cdict):
    d = {}
    for key in cdict.Keys:
        d[key] = cdict[key]
```

**Comment by filmor** [comment]
What is the actual error?

**Comment by kovapie** [comment]
```
double[] test = new double[] { 1, 2, 3, 4, 5 };

var pyTest = new PyList();
for (int i = 0; i < test.Length - 1; i++)
{
    pyTest.Append(new PyFloat(test[i]));
}
scope.Set("test", pyTest);
```
