### ISSUE TITLE
Binding redirects work on Linux but fail on Windows (.NET Core & .NET Framework 4.7.2)

### ISSUE THREAD

**Issue by fractus** [pythonnet/pythonnet#832]
### Environment

-   Pythonnet version: 2.4.0.dev0
-   Python version: 3.6.5
-   Operating System: Win10 1709; WSL Ubuntu 16.04 and 18.04
-   .NET Core 2.2.103

### Details

-  Projects: `Lib` (netstandard2.0) with Deedle package; `Runner` (netcoreapp2.2) executable
-   Deedle depends on FSharp.Core 4.4.30; explicitly added to the project FSharp.Core 4.6.2. 
-  The executable work in both platforms
-  The python script `run_example.py` fails works on Linux but fails on Windows. Explicitly adding the FSharp dll with `clr.AddReference` still fails;
```
user@HOST ~/Example
$ python run_example.py
['Core.Builder']
1 -> 10
2 -> 20
3 -> 30

F# version = 4.6.0.0
['Microsoft.FSharp.Core.Unit', 'Microsoft.FSharp.Core.SourceConstructFlags', 'Microsoft.FSharp.Core.CompilationRepresentationFlags']
1 -> 10
2 -> 20
3 -> 30
```

```
c:\temp\Example
λ python run_example.py
['Core.Builder']
 * FAILED *
Traceback (most recent call last):
  File "run_example.py", line 20, in try_run
    print(Core.Builder.Build(3).Format())
System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Deedle.Series`2..ctor(IEnumerable`1 keys, IEnumerable`1 values)
   at Core.Builder.Build(Int32 n)

F# version = 4.6.0.0
['Microsoft.FSharp.Core.Unit', 'Microsoft.FSharp.Core.SourceConstructFlags', 'Microsoft.FSharp.Core.CompilationRepresentationFlags']
 * FAILED *
Traceback (most recent call last):
  File "run_example.py", line 20, in try_run
    print(Core.Builder.Build(3).Format())
System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Deedle.Series`2..ctor(IEnumerable`1 keys, IEnumerable`1 values)
   at Core.Builder.Build(Int32 n)
```

-   To replicate, unzip the attached file, then 
```
dotnet build
python run_example.py
```

- Same behaviour if framework is changed to `net472`

[Example.zip](https://github.com/pythonnet/pythonnet/files/2996039/Example.zip)

**Comment by filmor** [comment]
How did you try to set up the binding redirect? At least for .NET Framework I remember that the lookup for the binding redirects uses the executable being run (in this case `python.exe`, so you'd need a `python.exe.config` close to it). As I couldn't find a good way to circumvent this, I hooked into .NET's assembly loading:

    public static class Support
    {
        public static void InstallResolveHandler()
        {
            AppDomain.CurrentDomain.AssemblyResolve += ResolveHandler;
            AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve +=
                ResolveHandler;
        }

        public static void RemoveResolveHandler()
        {
            AppDomain.CurrentDomain.AssemblyResolve -= ResolveHandler;
            AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve -=
                ResolveHandler;
        }

        static IDictionary<string, Assembly> _cache =
            new Dictionary<string, Assembly>();

        private static Assembly ResolveHandler(
            object sender, ResolveEventArgs args)
        {
            var name = new AssemblyName(args.Name).Name;
            Assembly result = null;

            if (!_cache.TryGetValue(name, out result))
            {
                var current = Assembly.GetAssembly(typeof(Support));
                var path = Path.GetDirectoryName(current.Location);
                var dllPath = Path.Combine(path, name + ".dll");

                if (File.Exists(dllPath))
                {
                    result = Assembly.LoadFrom(dllPath);
                }

                _cache[name] = result;
            }

            return result;
        }

It's very simple (and maybe unsafe), but it does the trick for us.

**Comment by fractus** [comment]
@filmor Thanks for your response. There's no explicit binding redirect in the attached example. 

In .NET Framework projects, I used a similar method to your C# code on the Python side; appending the resolver to `clr.System.AppDomain.CurrentDomain.AssemblyResolve`.

**Comment by fractus** [comment]
Updating to Deedle 2.0.4 and using the exact F# version works in Windows ; still no full redirect though; changes in Lib.csproj
```csharp
    <ItemGroup>
      <PackageReference Include="Deedle" Version="2.0.4" />
      <PackageReference Include="FSharp.Core" Version="4.5.2" />
    </ItemGroup>
```

**Comment by sridharan99** [comment]
@fractus can you please comment on how you added the binding redirect in linux ? 

for windows the binding redirect is done by adding python.exe.config in the same folder as python.exe. For more info see [this](https://stackoverflow.com/questions/44905819/applying-bindingredirect-config-to-pythonnet)

**Comment by fractus** [comment]
The example from the first post of this issue has no redirect -- neither on Windows or Linux. Linux never had an problem running; Windows only run if Deedle and the matching FSharp.Core are updated.

With non-exact match of the FSharp.Core version, i.e., change to 4.6.2, Windows passes only if the following redirect is added.

```python
def add_assembly_redirect():
    def assembly_resolve(app_domain, resolve_event_args):
        name = resolve_event_args.Name.split(',')[0]
        try:
            return next(x for x in app_domain.GetAssemblies() if x.GetName().Name == name)
        except StopIteration:
            pass
    clr.System.AppDomain.CurrentDomain.AssemblyResolve += assembly_resolve

```

**Comment by FaCoffee1984** [comment]
@fractus your snippet seems to have a problem:

```
def add_assembly_redirect():
    def assembly_resolve(app_domain, resolve_event_args):
        name = resolve_event_args.Name.split(',')[0]
        try:
            return next(x for x in app_domain.GetAssemblies() if x.GetName().Name == name)
        except StopIteration:
            pass
    clr.System.AppDomain.CurrentDomain.AssemblyResolve += assembly_resolve
```

When calling `add_assembly_redirect()`, it returns:
```
AttributeError: module 'clr' has no attribute 'System'
```

**Comment by fractus** [comment]
@FaCoffee1984 This is correct - I only use the redirect on Windows. On Linux, libraries such as Deedle or gRPC work without it. Last, on the latest version of Python.NET with .NET Core, I don't think you need it.

**Comment by filmor** [comment]
Recent versions of `pythonnet` also allow you to explicitly specify a configuration file via the `config_file` parameter, like

    from pythonnet import load
    load("netfx", config_file="path/to/some.dll.config")

    import clr

This should allow normal binding redirect configuration without using the hooks. For the concrete issue with the given snippet, `import System` and use `System.AppDomain...` (without the `clr.` prefix).
