### ISSUE TITLE
 Not able to use the .netcoreapp compiled dll's using CLR

### ISSUE THREAD

**Issue by bmu1kor** [pythonnet/pythonnet#833]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 2.7.13
-   Operating System: Windows 7

### Details

-   Not able to use the .netcoreapp compiled dll's
    .netcore app version 2.1
     Below code is used to load the .netcoreapp compiled dll's.
import clr
import os
clr.AddReference(os.path.abs.path("./sample.dll") - Reference added, no issues
from sample import *
Import Exception : No module named sample.

https://stackoverflow.com/questions/55186795/accessing-net-core-dll-using-python

**Comment by denfromufa** [comment]
pythonnet 2.3 does not support .net core. try master branch.
