### ISSUE TITLE
Method not found in .Net Standard initialize

### ISSUE THREAD

**Issue by Noppey** [pythonnet/pythonnet#834]
Updated issue name, as no replies yet and exception is different (and existing items are available for troubleshooting that error)

I'm using the following solution to try to get a working dll for .Net Standard 2.0:
https://ci.appveyor.com/project/pythonnet/pythonnet/branch/master/job/n3j22uks9uuyw9g5/artifacts

I'm using the .15 solution, compilation symbols XPLAT;;PYTHON3;PYTHON36;UCS2;NETSTANDARD;
Building works, but when I add the runtime.dll file as a reference in my .NetStandard 2.0 project, I get:

Message: System.MissingMethodException : Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.

Result StackTrace:	
at Python.Runtime.CodeGenerator..ctor()
   at Python.Runtime.DelegateManager..ctor()
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at Python.Runtime.Py.GIL()
   at Portal.Api.Jobs.RunJob.RunPython(Dataset source, Object[][] timeseries, String scriptFileName) in ...

**Comment by Noppey** [comment]
When I add the complete Python.Runtime.15 project in my solution, it does work.
In that case there is a Python.Runtime.deps.json in the bin folder that resolves the dependency to System.Reflection.Emit.

In my .Net Standard 2.0 (targeted using .net core 2.1) project, there is no System.Reflection.Emit available (and installing using nuget does not work either without net40 targetframework).
Using the methods from System.Reflection.Emit is apparently not recommended for .Net Standard 2.0: https://github.com/dotnet/standard/issues/712

Is there a way to rewrite that code according to .Net standard 2.0 standards? Or is there another workaround that I can use to get this working on a .Net Standard 2.0 project using .Net core.

**Comment by denfromufa** [comment]
@dmitriyse is expert on this

**Comment by Noppey** [comment]
Ok can @dmitriyse help me with this?

**Comment by Noppey** [comment]
Hello?

**Comment by JustinDe** [comment]
Same problem.

Bump

**Comment by JustinDe** [comment]
@Noppey 

This SE answer helped me and resolved this issue:
https://stackoverflow.com/a/56085756/5157700

Hope this helps!

**Comment by Noppey** [comment]
Good stuff. Thanks for sharing!

I ended up using a prebuilt version that was available on nuget, that
worked for me.

Op ma 16 dec. 2019 22:25 schreef Justin Demetroff <notifications@github.com
