### ISSUE TITLE
Running a multi-threaded python application from C#

### ISSUE THREAD

**Issue by AhmedAbdelmoneim** [pythonnet/pythonnet#837]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.6
-   Operating System: Windows 10

### Details

I'm trying to embed a python application into a .NET application, I'm hoping I can achieve the following with different threads in python

Here's an example python module:

```python
   class Example:
       def test_method_1(self):
            print("started method 1")
            t = threading.Thread(target=self.test_thread)
            t.start()

       def test_method_2(self):
            print("test method 2")

       def test_thread(self):
            while True:
                print("test thread")
                time.sleep(2000)
```

and then in C# I'm hoping to be able to call test_method_1 which starts the thread,  and then call test_method_2 periodically, for example:

```C#
    public void SomeMethod() {
        dynamic script = Py.Import("example_script");
        dynamic exampleObject = script.Example();
        
        exampleObject.test_method_1();

        while (true) {
             exampleObject.test_method_2();
             Thread.Sleep(2000);
        }
    }
```

I tried a couple of approaches like joining the threads in the python script, and calling BeginAllowThreads from C#, the first just causes the C# program to block until the thread is done, and the second approach just results in a bunch of exceptions from the different threads. 

I'm not an expert with python threading so any help will be appreciated!

**Comment by filmor** [comment]
Please ask questions like this on StackOverflow, this is an issue tracker. Also, always include stack traces instead of a vague "bunch of exceptions" :). In general, threading is supported in Python.NET, but must always be explicitly enabled using `BeginAllowThreads`, as you did in your second try.
