### ISSUE TITLE
Can't pickle .NET objects for multiprocessing

### ISSUE THREAD

**Issue by x1rubinho1x** [pythonnet/pythonnet#840]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6.8
-   Operating System: Windows 10

### Details

Using concurrent.futures.ProcessPoolExecutor to run parallel tasks various .NET types cannot be pickled meaning they cannot be used as input arguments or return types.  The trivial example below uses `System.Int64()` but my application is trying to send more complex objects.  

```python
import clr
from concurrent.futures import ProcessPoolExecutor, as_completed

clr.AddReference('System')

import System

def worker(a, b, c):
    
    d = a * b * c
    
    return(d)
    
if __name__ == "__main__":
    
    data = [(System.Int64(1), System.Int64(2), System.Int64(3)), 
        (System.Int64(4), System.Int64(5), System.Int64(6)), 
        (System.Int64(7), System.Int64(8), System.Int64(9))]
    
    with ProcessPoolExecutor(max_workers=4) as executor:
        jobs = []
            
        jobs = [executor.submit(worker, x[0], x[1], x[2]) for x in data]
        
        for job in as_completed(jobs):
            print(job.result())
```

Running this yields:
```
Traceback (most recent call last):
  File "C:\Users\cullr\AppData\Local\anaconda3\lib\multiprocessing\queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\cullr\AppData\Local\anaconda3\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Int64 objects
Traceback (most recent call last):
  File "C:\Users\cullr\AppData\Local\anaconda3\lib\multiprocessing\queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\cullr\AppData\Local\anaconda3\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Int64 objects
Traceback (most recent call last):
  File "C:\Users\cullr\AppData\Local\anaconda3\lib\multiprocessing\queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\cullr\AppData\Local\anaconda3\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Int64 objects
```

Converting in and out of .NET objects is not an option as this is expensive and not always possible.

**Comment by filmor** [comment]
I doubt that this can be implemented in a reasonable fashion. Even *if* we supported this directly, we would likely just expose .NET's own serialization functions, writing into a `bytes` instance, which you can just call directly yourself (which I'd advise you to do). If you can control the C# side of things you can do so in a quite optimal fashion (if you are careful) by preparing a buffer object on the Python side, passing a pointer back to C# and filling it directly there, same for the other direction.

If you wanted to implement pickling itself, I think you'd currently hit serious issues with the way the importing works, as it overrides (globally) `__import__`.

**Comment by x1rubinho1x** [comment]
Thanks for your reply.  

I think this will work well for standard .NET objects.  However it won't be possible for third party objects which are closed and do not have the [Serializable] decorator as the built in methods will refuse to serialize them (as I understand it).

**Comment by filmor** [comment]
Sure, but what would you want the library to do here? If they are not serialisable in .NET, they are also not in when calling into .NET from Python.

**Comment by denfromufa** [comment]
closed due to inactivity
