### ISSUE TITLE
how do use dedupe in C# code ?

### ISSUE THREAD

**Issue by omansak** [pythonnet/pythonnet#843]
I must make a Web Service with .Net that should communication to dedupe (https://github.com/dedupeio/dedupe)

- I used IronPython and i got a few error
- I used PythonNet and **i got System.DllNotFoundException: 'DLL 'python27' not load.** 

Visual Studio 2017 (15.9)
Python (3.5 and 2.7)
PythonNet last version build from master branch (Python.Runtime.dll)

I tried a lot of things and i failed all time. I couldn't connect with .net and python , always get errors.

I need run a function from py file to returns data. How do i make ?

**Comment by filmor** [comment]
Please read the wiki pages. The Python version you compile against must match the one you run against (so you'll either need to define PYTHON27 (the default) or PYTHON35).
