### ISSUE TITLE
ModuleNotFound on Azure Functions

### ISSUE THREAD

**Issue by Noppey** [pythonnet/pythonnet#845]
Hi,

I'm running .Net Standard 2.0 version of PythonNet.
The workaround I use in the initialize method is:
```
            var pythonPath = Environment.GetEnvironmentVariable("PythonPath");

            if (!string.IsNullOrEmpty(pythonPath))
            {
                string path = pythonPath + ";" + Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.Machine);
                Environment.SetEnvironmentVariable("PATH", path, EnvironmentVariableTarget.Process);
                Environment.SetEnvironmentVariable("PYTHONHOME", pythonPath);
                Environment.SetEnvironmentVariable("PYTHONPATH ", $@"{pythonPath}\Lib");
            }

```
where PythonPath is the directory where python.exe lives. 

When I run this on my machine everything works fine.

However, when I run this in Azure Functions using the Python Site Extensions including the module numpy, I get ModuleNotFoundError : No module named 'numpy'.

The module is installed correctly, since when I run this, it works fine:

```
private PythonResult RunPythonProcess(ExecutionContext executionContext)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            var file = Path.GetFullPath(Path.Combine(executionContext.FunctionDirectory, "..\\script.py"));
            start.FileName = Path.Combine(Environment.GetEnvironmentVariable("PythonPath"), "python.exe");
            start.Arguments = string.Format("\"{0}\" \"{1}\"", file, string.Empty);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
               
     throw new Exception($"Result: {result}, error: {stderr}");
                }
            }
        }
```

script.py:
```
import numpy
print('ok')
```

Since the process-method works out fine, the Azure Functions support can't really help me with this. 

Is this something that is specific to azure functions site extensions for which I have to set different paths in pythonnet initialize()? Or what else can I try?

(For sake of completeness, PythonPath is set to: D:\home\python364x86)

**Comment by Noppey** [comment]
Pythonnet uses another python instance, not the one at D:\home\python364x86.
Azure Functions provides another python instance somewhere else, and somehow that's the instance that's used to run. But I have no clue how I can make it more explicit to use D:\home\python364x86 than what I currently do (setting the environment variables in intiialize()).

Any ideas please?

**Comment by Noppey** [comment]
Ok solved by:
- Setting PythonEngine.Pythonhome directly instead of the environment variable, after path variable is updated.
- Removed Pythonpath environment setter.
- Renaming my custom environment variable from pythonpath to pythondir (to prevent conflicts with the pythonpath variable used by python).

**Comment by filmor** [comment]
I'll work on improving the path lookup in a future version.
