### ISSUE TITLE
PythonEngine.Initialize(); error

### ISSUE THREAD

**Issue by fbalobanov** [pythonnet/pythonnet#846]
### Environment

-  2.3.0
-  Python 3.6.8 |Anaconda custom (64-bit)
-  Windows 8 64

### Details

Trying to run PythonEngine.Initialize(); in VS 2012, 64bit, .NET 4.5
I've referenced Python.runtime from installed pythonet lib folder. 

Getting this error:
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000072c (most recent call first):

vshost.exe has stopped working
```
pythonnet in python works ok

**Comment by denfromufa** [comment]
This happens when multiple runtimes are loaded in the same process. I recall some nightmares with ctypes using registry keys for locating python instead of environment variables.

**Comment by fbalobanov** [comment]
Well, I had another version of Python installed, so I uninstalled it, now I have only one Anaconda python installed, rebooted, but I still see the same error.

Any suggestions what I could do next?

**Comment by denfromufa** [comment]
Have you tried this method? ;)

https://en.m.wikipedia.org/wiki/Rubber_duck_debugging

My guess is that something is wrong with your environment variables for Python. Also explore your python process with process explorer and see what gets loaded.
Debug print all your environment and compare it with working environment.

**Comment by fbalobanov** [comment]
Thanks for the attempt to help but I don't know how to understand what is wrong with environment variables, everything else just works. All the environment variables lead to one version. 

duck doesn't help me either, I have one line of code: PythonEngine.Initialize(); :)

Process explorer shows that anaconda python is loaded as it should be.

**Comment by fbalobanov** [comment]
Suddenly I found the solution
```
PythonEngine.PythonHome = @"C:\Users\user-name\Anaconda3";
```

and it works.

**Comment by denfromufa** [comment]
Well I guess you did not read the troubleshooting wiki

**Comment by filmor** [comment]
Glad you found it out yourself :)
