### ISSUE TITLE
pythonnet install fails with anaconda

### ISSUE THREAD

**Issue by mtclare** [pythonnet/pythonnet#848]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.7
-   Operating System: Windows 10

### Details

Trying to install pythonnet using anaconda 1.97 and python 3.7.  Used pip install git+https&#58;//github.com/pythonnet/pythonnet, but received error:

Collecting git+https&#58;//github.com/pythonnet/pythonnet
  Cloning https&#58;//github.com/pythonnet/pythonnet to c:\users\mtclare\appdata\local\temp\pip-req-build-0_5omddp
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py): started
  Building wheel for pythonnet (setup.py): finished with status 'error'
  Complete output from command C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mtclare\\AppData\\Local\\Temp\\pip-req-build-0_5omddp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\mtclare\AppData\Local\Temp\pip-wheel-iuk4qu8k --python-tag cp37:
  C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\site-packages\setuptools\dist.py:475: UserWarning: Normalizing '2.4.0-rc2' to '2.4.0rc2'
    normalized_version,
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https&#58;//www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 4.9.4.
  Update successful.
  Cannot find the specified version of msbuild: '14'
  MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'.
  Restoring NuGet package NUnit.3.7.1.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.ConsoleRunner.3.7.0.
  Adding package 'NUnit.3.7.1' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-req-build-0_5omddp\packages'
  Adding package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-req-build-0_5omddp\packages'
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-req-build-0_5omddp\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-req-build-0_5omddp\packages'
  Added package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-req-build-0_5omddp\packages'
  Added package 'NUnit.3.7.1' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-req-build-0_5omddp\packages'
  
  NuGet Config files used:
      C:\Users\mtclare\AppData\Local\Temp\pip-req-build-0_5omddp\NuGet.Config
      C:\Users\mtclare\AppData\Roaming\NuGet\NuGet.Config
  
  Feeds used:
      C:\Users\mtclare\.nuget\packages\
      https&#58;//dotnet.myget.org/F/dotnet-core/api/v3/index.json
      https&#58;//api.nuget.org/v3/index.json
  
  Installed:
      3 package(s) to packages.config projects
  error: [WinError 2] The system cannot find the file specified
  
  ----------------------------------------
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet: started
    Running setup.py install for pythonnet: finished with status 'error'
    Complete output from command C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mtclare\\AppData\\Local\\Temp\\pip-req-build-0_5omddp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mtclare\AppData\Local\Temp\pip-record-6xme8sez\install-record.txt --single-version-externally-managed --compile:
    C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\site-packages\setuptools\dist.py:475: UserWarning: Normalizing '2.4.0-rc2' to '2.4.0rc2'
      normalized_version,
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
  Failed building wheel for pythonnet
Command "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mtclare\\AppData\\Local\\Temp\\pip-req-build-0_5omddp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mtclare\AppData\Local\Temp\pip-record-6xme8sez\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\mtclare\AppData\Local\Temp\pip-req-build-0_5omddp\

**Comment by filmor** [comment]
You can just use the release candidate (`pip install pythonnet==2.4.0-rc2`). And please don't open new tickets with completely unformatted and uncommented error messages, follow up in the existing ticket (even though it's closed). The error at hand is probably due to an old `setuptools` version, I'll have a look into this.
