### ISSUE TITLE
Using in blazor

### ISSUE THREAD

**Issue by j209** [pythonnet/pythonnet#851]
Hi
Can we use pythonnet in [Blazor](https://github.com/aspnet/Blazor) as WebAssembly?

**Comment by denfromufa** [comment]
This is currently not possible at least due to this issue in blazor/mono/wasm. I guess your question was inspired by Pyiodide announcement from Mozilla. 

https://github.com/mono/mono/issues/8007

**Comment by GeorgeS2019** [comment]
@denfromufa  it is now possible to [run SkiaSharp using .NET6rc2 without using Uno](https://github.com/mattleibow/SkiaSharpBlazorWebAssembly)  what else in your view still missing?

**Comment by denfromufa** [comment]
I am not involved with the project anymore

**Comment by GeorgeS2019** [comment]
@lostmsu  hopefully you may be interested, once .NET7 is further in progress, the feasibility of making e.g. PythonNET and TorchSharp through Blazor WebAssembly may be feasible.
