### ISSUE TITLE
Fix the failing Finalizer test for Python 3.7

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#858]
We currently observe a failing test for Python 3.7 on Linux. I have not been able to reproduce it locally (where I use Anaconda's Python which is compiled with PYMALLOC) yet.

The last working build was https://travis-ci.org/pythonnet/pythonnet/builds/517298836, the first failing one is https://travis-ci.org/pythonnet/pythonnet/jobs/525395893.

Since between those two, only a completely unrelated test was changed as it started to fail with the new Mono version, I guess the new error is due to some package difference between the two builds, maybe Python itself.

**Comment by filmor** [comment]
Indeed, Mono went from 5.18 to 5.20...

**Comment by filmor** [comment]
I'm not able to reproduce this error with 5.20 locally either :/

If there are no objections, I'm going to do the release now anyway s.t. it's finally out of the door and will work on this afterwards.

**Comment by lidanger** [comment]
Could you publish a package on nuget ? 2.4.0 is much easier to use, but for now I have to use it from source project.

**Comment by vivainio** [comment]
Is this still release-blocking?

**Comment by filmor** [comment]
No, the release has been done already. I'm a bit reluctant to publish Nugets since the inflow of issues from people not installing correctly is already quite high as it's not really trivial (must have the right combination of .NET runtime, Python version, OS and architecture, and the Python installation needs to be findable). I'd much rather spend my limited time on enabling .NET Core support and reducing the platform dependencies to a minimum.

**Comment by HarelM** [comment]
@filmor See my Comment here:
https://github.com/pythonnet/pythonnet/issues/165#issuecomment-498292688
I understand the problem with the maintenance time, but releasing a NuGet file in appveyor should not get you into maintenance overhead, I hope.
Also there's an exiting NuGet package, so I think this sheep had sailed.
We'll be happy to lend a hand in order to improve the experience for .Net developers, just let us know how.
