### ISSUE TITLE
Upgrade C# language version to 7.0+

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#860]
What is still holding Python.NET on C# 6? Unity appears to have moved forward: https://blogs.unity3d.com/2018/12/13/introducing-unity-2018-3/

**Comment by filmor** [comment]
There is nothing holding us back, just go ahead and upgrade if it makes your life simpler :)

**Comment by filmor** [comment]
I think this is cleared up, whoever reads this and wants to contribute C#7 code, just go ahead.
