### ISSUE TITLE
Conda package of version 2.4.0

### ISSUE THREAD

**Issue by m-rossi** [pythonnet/pythonnet#861]
Do you plan to add a conda package of the recently released version to https://anaconda.org/pythonnet/pythonnet?

Furthermore, what's about adding the package to https://conda-forge.org? Have you ever thought about that or tried it? If not I would be happy to offer my help in building and also later maintaining the recipe. However, I'm sure I will need some help setting up the build process.

**Comment by filmor** [comment]
We do have a recipe already, but I don't have experience with setting up a conda-forge feedstock. My main problem with this right now is the multitude of different versions (.net framework, mono, .net standard; windows, linux, mac osx; python*; amd64, x86). I'd like to at least get rid of the first dimension by moving completely over to .NET Standard, only requiring Microsoft's dotnet-cli to build before tackling non-pypi packaging.

However, creating the feedstock already would be a great help :)

**Comment by m-rossi** [comment]
I will try and post the PR link here if there is a first version ready.

**Comment by m-rossi** [comment]
I've added a first version: https://github.com/conda-forge/staged-recipes/pull/8445
There are currently some issues, I will try to fix them.

**Comment by RJMW** [comment]
@m-rossi - Many thanks! Adding pythonnet to conda-forge has been on my todo list for a while.

ping @bgruening

See here for working examples (version 2.3.0 and 2.4.0 for unix64 and osx64):

https://anaconda.org/computational-metabolomics/pythonnet/files (2.4.0)
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pythonnet/meta.yaml (2.3.0)

We probably need to build this with `--prefix-length 128` as this is needed for mono. Not sure if there is a way to do configure this in conda-forge.

**Comment by m-rossi** [comment]
The current status is, the recipe is close to working everywhere, except the following:
* There is a weird behavior of the AppVeyor CI when building the Python 2.7 version. It uses some old version of MSBuild and fails then. I tried some hacks in other recipes but nothing seem to solve the issue completely. 
* You are right, the Linux Build needs a shorter `—prefix-length`. I was able to build it locally using the conda-forge Docker container. But there is currently no way to configure it in conda-forge except modifying the build string. So we may skip this architecture for now and discuss with the conda-forge/conda-build team how to add an option to configure this.

**Comment by bgruening** [comment]
@m-rossi you could skip the python2 builds. Python2 will "die" in a few months and maybe its ok to not support it anymore.

The other problem is a real bummer and I was fighting with this a year ago or so. What we can do is skip Linux. Merge it and on the feedstock, we modify the feedstock build string.

**Comment by m-rossi** [comment]
Ok, I will remove Python 2 later this day.

I thought about modifying the build string, too. Doing that in the feedstock repository is a clever idea.

**Comment by m-rossi** [comment]
@bgruening merged the PR and we have a feedstock now. Let's try if we get the linux package building on conda-forge: https://github.com/conda-forge/pythonnet-feedstock/pull/1
