### ISSUE TITLE
Disposing pyscope does not clean up resources

### ISSUE THREAD

**Issue by Noppey** [pythonnet/pythonnet#865]
I'm using Pythonnet with the code below. When I'm running diagnostics, my memory keeps increasing over time when running this code for say 170 timeseries objects.

When I explicitly set the timeseries variable back to null, the memory still increases, but far less then without this line of code.

I don't understand why the resources of this scope are still in memory, while I'm disposing PyScope. Shouldn't this clear all resources?

```
Initialize();
using (Py.GIL())
            {
                using (PyScope scope = Py.CreateScope())
                {
                    scope.Set("timeseries", timeseries);

                    scope.Exec(code);

                    var pythonDataset = GetDataset(scope, source);
                    var pythonProperties = GetProperties(scope);
                    scope.Set("timeseries", null);
                    return new PythonResult
                    {
                        Dataset = pythonDataset,
                        Properties = pythonProperties
                    };
                }
            }

private static void Initialize()
        {
            if (!PythonEngine.IsInitialized)
            {
                var pythonDir = Environment.GetEnvironmentVariable("PythonDir");

                if (!string.IsNullOrEmpty(pythonDir))
                {
                    string path = pythonDir + ";" + Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.Machine);
                    Environment.SetEnvironmentVariable("PATH", path, EnvironmentVariableTarget.Process);
                    PythonEngine.PythonHome = pythonDir;
                }

                PythonEngine.Initialize();
                PythonEngine.BeginAllowThreads();
            }
        }
```

**Comment by filmor** [comment]
`PyScope` doesn't capture everything that happens inside of the scope. First of all, you could be assigning or changing something globally in `scope.Exec(code);` and second, more importantly, you are returning a result as `pythonDataset` and `pythonProperties`. Maybe those still reference `timeseries`? That would keep it alive.

If you can give a minimal example in which you have a scope that is used to process something with code, that does not assign to anything but scoped variables, and you still see a memory issue, please reopen this ticket, with the information you have given it's completely valid that something is left over.

Also, please do not just erase the issue template, it's there for a reason. What are the versions of Python and Python.NET you are using? Which platform are you running on?
