### ISSUE TITLE
Unable to load DLL 'python36': The specified module could not be found. (Exception from HRESULT: 0x8007007E

### ISSUE THREAD

**Issue by kfavara** [pythonnet/pythonnet#871]
### Environment

-   Pythonnet version: 2.4
-   Python version: 3.6
-   Operating System: Win 10
-  .Net Framework 4.5.2
-  Visual Studio 2017

### Details

-   Implement Python within .Net using Pythonnet

I have been researching all day and have tried everything I could find. It crashes when trying to set the PythonHome variable.

Python is installed at c:\Python36.
Paths were added for C:\Python36, C:\Python36\lib\site-packages, C:\Python36\scripts, C:\Python36\lib  (redundant, but they were added one at a time trying ANYTHING).

I have added the following to try and fix path variables.

            string envPythonHome = @"C:\Python36";
            string envPythonLib = envPythonHome + @"\Lib\site-packages";
            PythonEngine.PythonHome = envPythonHome;
            PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH");
            Environment.SetEnvironmentVariable("PYTHONHOME", envPythonHome, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PATH", envPythonHome + ";" + Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.Machine),
                EnvironmentVariableTarget.Process);

            Environment.SetEnvironmentVariable("PYTHONPATH", envPythonLib, EnvironmentVariableTarget.Process);

            PythonEngine.Initialize();

I installed using pip install pythonnet

I have upgraded pip, setuptools, installed wheel

I have tried using the build target x64 and x86. 

I checked the 

I followed all of these links and couldn't find anything undone.
https://github.com/pythonnet/pythonnet/issues/259 https://github.com/pythonnet/pythonnet/issues/463 https://github.com/pythonnet/pythonnet/issues/467

I made sure the python36 was in the python.runtime.csproj.

I made sure the python.runtime.dll was in the site-packages folder that was referenced in the path. 

I am sure there are additional steps I have tried, but that is all I can remember at the moment. Any suggestions would be greatly appreciated.

**Comment by lidanger** [comment]
May it be about compile configuration. DebugWinPY3 will be OK on Windows while DebugMonoPY3 for Linux.

**Comment by kfavara** [comment]
> May it be about solution compile configuration. DebugWinPY3 will be OK on Windows while DebugMonoPY3 for Linux.

Where do I go to look for this? It was not in the project file.

**Comment by lidanger** [comment]
It is in the project file.
While in Visual Studio, you can get that on standard toolbar.

**Comment by filmor** [comment]
@lidanger Thanks for helping out :)
@kfavara I'll close this now, just comment again if you have follow up issues.
