### ISSUE TITLE
Mac installation from source does not create a clr module

### ISSUE THREAD

**Issue by andy-ms** [pythonnet/pythonnet#872]
### Environment

-   Pythonnet version: master branch
-   Python version: 3.7.3
-   Operating System: macOS 10.14.5 (18F132)

### Details

-   Describe what you were trying to get done.

Install the library from source.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

* `git clone https://github.com/pythonnet/pythonnet.git`
* `cd pythonnet`
* `python3.7 setup.py bdist_wheel --xplat`
* `python3.7 -m pip install --no-index --find-links=./dist/ pythonnet`

I see that it creates a directory `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonnet-2.4.1.dev0.dist-info`, but nothing named `clr`.

I have this working on linux and windows, the problem is only on mac.

On Linux I see that a similar directory `/usr/local/lib/python3.7/site-packages/pythonnet-2.4.0.dev0.dist-info` exists, but there's also `/usr/local/lib/python3.7/site-packages/clr.cpython-37m-x86_64-linux-gnu.so`.

On Windows I see `C:\Users\anhans\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\pythonnet-2.4.0.dev0.dist-info` is created, but also `C:\Users\anhans\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\clr.py`.

-   If there was a crash, please include the traceback here.

```
$ python3.7 -c "import clr"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'clr'
```

**Comment by filmor** [comment]
I don't have a Mac to test this, sorry. Is there anything in the build process that looks dodgy? Like an error compiling `monoclr` that is being ignored?

**Comment by filmor** [comment]
Since there have not been any updates in quite a while, I'll close this issue. Feel free to reopen and provide a information on the current state.
