### ISSUE TITLE
How do I use a class without a namespace (or global namespace)?

### ISSUE THREAD

**Issue by belgard** [pythonnet/pythonnet#876]
### Environment

-   Pythonnet version: pythonnet-2.4.0
-   Python version: 3.7
-   Operating System: Windows 7

### Details

-   Describe what you were trying to get done.
I have a 3rd party dll that I am importing and the class is not in a namespace, meaning it will be part of the global namespace (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/global). 

-   What commands did you run to trigger this issue? If you can provide a
I executed the following:
```python
import clr
clr.AddReference("mydll.dll")
```
After that I can easily import a namespace, however I cannot use the class that has no namespace.
I tried the following:
```python
import class_name
import global
import Global
import System
a = class_name()
```
and nothing worked.

Any ideas on how to proceed on this case?

**Comment by fbalobanov** [comment]
Maybe try global.class_name since the class_name in global namespace (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/global). 

Not sure if it will work in this case though. In C# it would be
global::class_name

**Comment by belgard** [comment]
Thank you, I tried a little more, it seems the correct way is the following:
```python
from clr import class_name
a=class_name()
```
Closing the case.
