### ISSUE TITLE
problems when loading the  C# dll with namespace name different from the dll file name

### ISSUE THREAD

**Issue by ohmydream666** [pythonnet/pythonnet#878]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7(32-bit)
-   Operating System: Win10

### Details

I want load a c# dll (mrc5_client)
### Python Code Start
import clr
assemblypathN = r"\mypath\mrc5_client"
AssmStr = clr.FindAssembly(assemblypathN)
from mrc5_client import *
### Python Code End
Traceback (most recent call last):
  File "D:/Programs/Python/Python37_32bit/test.py", line 8, in <module>
    from mrc5_client import *
ModuleNotFoundError: No module named 'mrc5_client'

I don't know how to import the namespace . when the name space name is different from the dll filename

![DllInfo](https://user-images.githubusercontent.com/27729598/58757439-2ca5ad80-853f-11e9-8c61-f59481a0990a.PNG)

**Comment by Cronan** [comment]
Hi, you need to do the following:

```clr.AddReference(AssmStr)```

Then import the type using the namespace (I can't see what the namespace name is in your example).
