### ISSUE TITLE
Compile error.NuGet:Not available in this source

### ISSUE THREAD

**Issue by lidanger** [pythonnet/pythonnet#879]
### Environment

-   Pythonnet version: 2.4.0 (source)
-   Python version: 3.7.3
-   Operating System: Windows 7

### Details

-   I can't compile the source project in Visual Studio 2019 or VSCode.

    - Visual Studio 2019 
    Compalition output:
    Unable to find package Microsoft.TargetingPack.NETFramework.v4.5. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org.

    - VSCode 
    Compile command:
    dotnet build ./Python.Runtime/Python.Runtime.15.csproj    
    Output:
    error NU1101: Unable to find package Microsoft.TargetingPack.NETFramework.v4.5. No packages exist with this id in source(s): nuget.org
    
Is there someone can help me?

**Comment by filmor** [comment]
The targeting pack needs to be installed via the Visual Studio installer.

**Comment by mjkkirschner** [comment]
Hi @filmor - apologies for bumping a closed issue but I think we're encountering the same or similar issue - 

we have a fork similar to the 2.5 backports branch, and get an error that this this targeting pack cannot be found - even when the targeting pack is installed via visual studio or independently via installer.

It appears the package is referenced directly from the csproj file. Are we missing a build step?

**Comment by DoLook** [comment]
I have same problem with pythonnet 2.5.2 release, Visual Studio 2019.
Nuget management of VS2019 can't connect the package source, I dont know if it is for network issues  in China.
At last I deleted the package source and dependcy item of Python.Runtime.15 project "net40/pacagke/Microsoft.TargetingPack.NetFramework.4.5(1.0.1)" in solution explorer. Then the project was compiled normally.
