### ISSUE TITLE
Unable to load shared library 'python36' or one of its dependencies.

### ISSUE THREAD

**Issue by emilmuller** [pythonnet/pythonnet#883]
### Environment

-   Pythonnet version: Latest from master
-   Python version: 3.6
-   Operating System: Linux Mint 19

Trying to use pythonnet in a .NET **Core** application on Linux. I have compiled Python.Runtime.15 on Windows in Visual Studio using the following compilation symbols: 

XPLAT;PYTHON3;PYTHON36;UCS2;

I am now attempting to use the dll on my Linux machine where I have Python 3.6 installed.

It gives me:

```
Exception has occurred: CLR/System.DllNotFoundException
An unhandled exception of type 'System.DllNotFoundException' occurred in Python.Runtime.dll: 'Unable to load shared library 'python36' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpython36: cannot open shared object file: No such file or directory'
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.Py.GIL()
   at ConsoleApp1.Program.Main(String[] args) in /home/emil/test/ConsoleApp1/ConsoleApp1/Program.cs:line 10
```

running python and printing sys.path gives me:

`['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/emil/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']`

I have tried setting PythonEngine.PythonPath with the above alternatives, but to no avail.

I have tried setting the MONO_LINUX compilation symbol, but the same occurs. Should MONO_LINUX be set for .NET Core?

**Comment by filmor** [comment]
On Linux, Python 3.6 is very often compiled with PYMALLOC which adds a `m` to the Python so (i.e. it would be `libpython3.6m.so`). Could you check whether that is the case?

**Comment by amos402** [comment]
Since `sizeof(whcar_t)` is 4 on Linux, you should change `UCS2` to `UCS4`.

**Comment by 3x0dv5** [comment]
@filmor I seeing a similar issue:

![image](https://user-images.githubusercontent.com/250271/73140081-e58ba000-406c-11ea-97aa-e7988ebf9654.png)


```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'python37' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpython37: cannot open shared object file: No such file or directory
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at Python.Runtime.Py.GIL()
   at DotPy.Program.Main(String[] args) in /home/usr/RiderProjects/DotPy/DotPy/Program.cs:line 11
```


![image](https://user-images.githubusercontent.com/250271/73140068-b2e1a780-406c-11ea-8a4e-318c28ce86ca.png)

**Comment by novecento** [comment]
Hi, any hint about that?

**Comment by lostmsu** [comment]
1. Ensure that the name of the library matches the name in the error message. On Linux it should be "lib{string_from_error_message}.so" where `string_from_error_message` is 'python37'. If they do not match in version or `m` suffix presence, it means you need to build a different configuration of Python.NET (for example `DebugMonoPY3`, see `Python.Runtime.15.csproj` for options).
2. Check your `PATH` and `LD_LIBRARY_PATH` environment variables (I think on Linux only the second one is needed).

@3x0dv5 you seem to be using out of tree build of Python.NET from https://github.com/henon/Python.Included . You should ask for support there: https://github.com/henon/pythonnet_netstandard

**Comment by novecento** [comment]
@lostmsu thank you!

**Comment by Nannoussa** [comment]
Hello guys,
I am using pythoonet and it  works like a charm on my local machine but once deployed on our test server I've got the famous error: python38.dll not found. I tried to reference it in my code without success . do you have any idea how to use python38. dll for the prod environment? Thank you.

**Comment by amos402** [comment]
> 
> 
> Hello guys,
> **Environment:**
> 
>     * pythonnet38
> 
>     * .net framework application 4.7.1
> 
>     * windows 10
> 
>     * Visual Studio 2019
> 
> 
> I am using pythoonet and it works like a charm on my local machine but once deployed on our test server I've got the famous error: python38.dll not found. I tried to reference it in my code without success . do you have any idea how to use python38. dll for the **prod environment**?
> Thank you.

Did you confirm your `python38.dll` at your environment variable `PATH`?
Run `where python38.dll` on `cmd` or `Get-Command python38.dll` on powershell make sure your environment correct at first.
I think this is not relate with this issue(the author's system is Linux), if you still having the same problem, feel free to create a new one.

**Comment by shv07** [comment]
> @lostmsu thank you!

@lostmsu  Could you elaborate on how were you able to fix the issue, please? I am stuck on same issue while deploying a keras.net code on Ubuntu.

**Comment by shv07** [comment]
> @filmor I seeing a similar issue:
> 
> ![image](https://user-images.githubusercontent.com/250271/73140081-e58ba000-406c-11ea-97aa-e7988ebf9654.png)
> 
> ```
> Unhandled exception. System.DllNotFoundException: Unable to load shared library 'python37' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpython37: cannot open shared object file: No such file or directory
>    at Python.Runtime.Runtime.Py_IsInitialized()
>    at Python.Runtime.Runtime.Initialize(Boolean initSigs)
>    at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
>    at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
>    at Python.Runtime.PythonEngine.Initialize()
>    at Python.Runtime.Py.GIL()
>    at DotPy.Program.Main(String[] args) in /home/usr/RiderProjects/DotPy/DotPy/Program.cs:line 11
> ```
> 
> ![image](https://user-images.githubusercontent.com/250271/73140068-b2e1a780-406c-11ea-8a4e-318c28ce86ca.png)

@3x0dv5 Were you able to fix the issue?

**Comment by shv07** [comment]
> 1. Ensure that the name of the library matches the name in the error message. On Linux it should be "lib{string_from_error_message}.so" where `string_from_error_message` is 'python37'. If they do not match in version or `m` suffix presence, it means you need to build a different configuration of Python.NET (for example `DebugMonoPY3`, see `Python.Runtime.15.csproj` for options).
> 2. Check your `PATH` and `LD_LIBRARY_PATH` environment variables (I think on Linux only the second one is needed).
> 
> @3x0dv5 you seem to be using out of tree build of Python.NET from https://github.com/henon/Python.Included . You should ask for support there: https://github.com/henon/pythonnet_netstandard . We can not provide you with support on their fork.

Hi,

I tried checking for the library name and add values to environment variables. I still get the same error as @3x0dv5 . I am trying to run a self contained dot net core app using keras.net on Ubuntu 16. 
![image](https://user-images.githubusercontent.com/25014324/100223449-85da7b80-2f41-11eb-8a2c-4ce74cdfce7b.png)

![image](https://user-images.githubusercontent.com/25014324/100223642-c934ea00-2f41-11eb-8f2e-00e2cf1ad62d.png)

**Comment by filmor** [comment]
Please direct questions regarding https://github.com/henon/pythonnet_netstandard or Keras.NET towards their respective issue trackers.
