### ISSUE TITLE
Add microbenchmarking to CI

### ISSUE THREAD

**Issue by lostmsu** [pythonnet/pythonnet#886]
Python.NET continuous integration needs microbenchmark tests to track changes in performance.

**Comment by amos402** [comment]
I suggest separate the benchmark from the normal tests, it's merely a assistance running. And it even not running the the newest branch code for now, that may disturb the judgement of test correctness.

**Comment by lostmsu** [comment]
@amos402 not sure what you mean by not running the newest branch code. It does run the newest Python.NET code, and compares it to the baseline.

**Comment by amos402** [comment]
Oh yeah, it is. Seems just the misunderstanding of mine. But I still thought it's better to separate them.

**Comment by lostmsu** [comment]
@amos402 why though? Having the benchmark run as part of CI (as long as it quick enough and reliable) has a major advantage: if your change fails it, you'll see, and will either have a chance to fix performance regression, or adjust the performance target explicitly in the test code, which would let reviewers immediately weight the performance impact against usefulness of the change.

**Comment by amos402** [comment]
Jumble functional test and performance test isn't a good idea. They're two things. Just make some search you may find more articles like this https://www.neotys.com/blog/what-does-test-driven-development-mean-for-performance-testers/

**Comment by lostmsu** [comment]
@amos402 the article you linked actually advocates perf tests alongside functional tests :-D

**Comment by amos402** [comment]
Yeah, they're two things, don't mix them.

**Comment by lostmsu** [comment]
@amos402 they are not mixed. They are two separate steps of the CI. The only problem is that the results report in the GitHub UI is mixed, but you can still drill down in AppVeyor. If it is a problem, feel free to separate the pipeline.
