### ISSUE TITLE
Failed in macos 10.14.5

### ISSUE THREAD

**Issue by lokinfey** [pythonnet/pythonnet#892]
### Environment

-   Pythonnet version: 2.4.1.dev0
-   Python version: 3.7.3
-   Operating System: macOS 10.14.5

### Details

-   I try to install pythonnet in my macos , I follow the guildine here https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX

    But when I use C#
    
            dynamic np = Py.Import("numpy");
            Console.WriteLine(np.cos(np.pi * 2));

            dynamic sin = np.sin;
            Console.WriteLine(sin(5));

            double c = np.cos(5) + sin(5);
            Console.WriteLine(c);

            dynamic a = np.array(new List<float> { 1, 2, 3 });
            Console.WriteLine(a.dtype);

            dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
            Console.WriteLine(b.dtype);

            Console.WriteLine(a * b);
            Console.ReadKey();

      It tells me 
      
      Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'python37' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libpython37, 1): image not found
   at Python.Runtime.Runtime.PyImport_ImportModule(String name)
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at Python.Runtime.Py.Import(String name)
   at demoapp.Program.Main(String[] args) in /Users/lokinfey/Desktop/demoapp/Program.cs:line 11

**Comment by filmor** [comment]
I see in the linked issue that you are getting support over there already.
