### ISSUE TITLE
macOS failed in .NET Core Project

### ISSUE THREAD

**Issue by lokinfey** [pythonnet/pythonnet#903]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.4rc1
-   Operating System: macOS 10.14.6

### Details

     I try to build pythonnet but when I add Python.Runtime.dll in my .net core project  it shows me like that

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   python3.7m.dylib              	0x0000000109de8a37 PyUnicode_InternInPlace + 116
1   python3.7m.dylib              	0x0000000109e010b4 PyUnicode_InternFromString + 32
2   python3.7m.dylib              	0x0000000109e4c781 PyImport_Import + 87
3   python3.7m.dylib              	0x0000000109e4b228 PyImport_ImportModule + 28
4   ???                           	0x0000000116446c45 0 + 4668550213
5   ???                           	0x0000000116446afd 0 + 4668549885
6   ???                           	0x00000001164422f6 0 + 4668531446
7   libcoreclr.dylib              	0x0000000107722837 CallDescrWorkerInternal + 124
8   libcoreclr.dylib              	0x0000000107582c04 MethodDescCallSite::CallTargetWorker(unsigned long const*, unsigned long*, int) + 964
9   libcoreclr.dylib              	0x0000000107450cb7 RunMain(MethodDesc*, short, int*, PtrArray**) + 775
10  libcoreclr.dylib              	0x0000000107451042 Assembly::ExecuteMainMethod(PtrArray**, int) + 402
11  libcoreclr.dylib              	0x000000010749312a CorHost2::ExecuteAssembly(unsigned int, char16_t const*, int, char16_t const**, unsigned int*) + 442
12  libcoreclr.dylib              	0x00000001073c1524 coreclr_execute_assembly + 260
13  libhostpolicy.dylib           	0x00000001072ef148 0x107267000 + 557384
14  libhostpolicy.dylib           	0x00000001072d87c7 0x107267000 + 464839
15  libhostpolicy.dylib           	0x00000001072df069 0x107267000 + 491625
16  libhostfxr.dylib              	0x0000000107203223 0x10717a000 + 561699
17  libhostfxr.dylib              	0x0000000107222f44 0x10717a000 + 692036
18  libhostfxr.dylib              	0x0000000107225b22 0x10717a000 + 703266
19  libhostfxr.dylib              	0x0000000107223fd8 0x10717a000 + 696280
20  libhostfxr.dylib              	0x0000000107204299 0x10717a000 + 565913
21  dotnet                        	0x000000010714e402 0x107142000 + 50178
22  dotnet                        	0x000000010714e9f5 0x107142000 + 51701
23  libdyld.dylib                 	0x00007fff5aa173d5 start + 1

**Comment by Oceania2018** [comment]
I ran it succssfully on Ubuntu, maybe it helpful for this issue. https://github.com/SciSharp/Numpy.NET/issues/5 @lokinfey

**Comment by filmor** [comment]
This should work nowadays, feel free to reopen if that's not the case.
