### ISSUE TITLE
_winreg renamed to winreg in Python 3

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#91]
This works with development version (2.1.0.dev1), but not release version.

installation failure: 

```
C:\Windows\system32>pip install pythonnet --use-wheel
Collecting pythonnet
  Using cached pythonnet-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\dta\AppData\Local\Temp\pip-build-t1jl63of\pythonnet\setup.py", line 79, in <module>
        _xbuild = "\"%s\"" % _find_msbuild_tool("msbuild.exe")
      File "C:\Users\dta\AppData\Local\Temp\pip-build-t1jl63of\pythonnet\setup.py", line 27, in _find_msbuild_tool
        import _winreg
    ImportError: No module named '_winreg'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\dta\AppData\Local\Temp\pip-build-t1jl63of\pythonnet
```

**Comment by tonyroberts** [comment]
This is a non-issue. 2.0 does not support Python 3, as that has only been added in 2.1.0.

**Comment by denfromufa** [comment]
I thought until 2.1.0 is released this issue should be kept open?

**Comment by tonyroberts** [comment]
If you look on PyPI you'll even see that 2.0.0 only lists support for 2.6 and 2.7. Python 3 support isn't going to be added to 2.0.0 so it's not a defect.

The issue tracker is for tracking open issues. Milestones should be used for tracking implemented but unreleased features. By leaving this open it makes it seem like there is coding work to be done.
