### ISSUE TITLE
Automatic conversions

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#912]
This is a meta-issue to collect all of the existing automatic conversions, possible future conversions and discussion on how we want to go forward.

As a start, we definitely have (in some places, not all!) the following identification:

- `null` <=> `None`

**Comment by Cronan** [comment]
Does anyone her have perms to mark issues with labels - in the minutes of 25-June project meeting it was suggested that proposed work to be done be marked with the tag epic - this isn't being done, probbaly because nobody has the permissions to do it, I guess ...

**Comment by filmor** [comment]
I have, I just forgot :)

**Comment by lostmsu** [comment]
This issue is not being used.
