### ISSUE TITLE
System.MissingMethodException: 'Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.'

### ISSUE THREAD

**Issue by selvatheeban** [pythonnet/pythonnet#914]
### Environment

-   Pythonnet version: 3.6
-   Python version:3.6
-   Operating System:windows 10

### Details

-  AM trying to use pythonnet in .net core 

    _TODO_

-   create a .net core web api, and wrote api to execute the python file, installed python 3.6 , then pythonhome and pythonpath has been added in system environment, done pip install pythonet  to generate python dll  ,Then added the dll as refference . and executed the below sample  code 

 PythonEngine.Initialize();
            //PythonEngine.BeginAllowThreads();
            using (Py.GIL())

            {
                dynamic np = Py.Import("numpy");
                Console.WriteLine(np.cos(np.pi * 2));
            }

this returned the error .

**Comment by filmor** [comment]
The Python.NET DLL generated by a bare `pip install` is currently not compatible with .NET Core. Try compiling it yourself with the `--xplat` flag to get a compatible version. I'll put some work into making this more seamless, there is no good reason for this to be a compile-time thing.
