### ISSUE TITLE
Special Parameter not Converting Correctly

### ISSUE THREAD

**Issue by sekkit** [pythonnet/pythonnet#916]
### Environment

-   Pythonnet version: latest
-   Python version: 3.7.4
-   Operating System: Win10 1903

### Details

-   Describe what you were trying to get done.
    class logger
    {
        public static void error(params object[] msgs)
         {
            //
         }
     }

     In Pyscript:
     logger.error("helloworld")
     
     the parameter msgs in C# stack, will become ['h', 'e', 'l', ..., 'd']

     Conclusion: parameter is not converted correctly.

**Comment by Cronan** [comment]
As a workaround, did you try:
```
logger.error(new object[] { "helloworld" })
```

**Comment by sekkit** [comment]
> As a workaround, please try:
> 
> ```
> logger.error(new object[] { "helloworld" })
> ```

Yes, I used this alternative way to bypass that bug.
