### ISSUE TITLE
C# DLL fails to find log4net DLL

### ISSUE THREAD

**Issue by joshnyce** [pythonnet/pythonnet#920]
### Environment

-   Pythonnet version: latest
-   Python version: 2.7.10 32bit
-   Operating System: windows 10

### Details

I'm trying to use a .NET framework DLL. I'm able to load the DLL and use its methods in python, but the DLL cannot load any of the DLLs it depends on, like log4net. 

All the dependent DLLs, including log4net, are copied to the directory with my compiled DLL, and that directly is added to the system path environment variable. My DLL is compiled for any CPU, and I've also tried x86 with no luck.

I've tested my complied DLL from a C# test harness, which worked correctly, so this problem is definitely related to PythonNET somehow. 

The error in C# when trying to load log4net: 
Could not load file or assembly 'log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. 
The system cannot find the file specified.

This is probably a common problem, but I've googled it extensively without finding any answers. 

Thank you

**Comment by joshnyce** [comment]
I copied all the dependent DLLs to the root python directory (C:\Python27 in this case), and my DLL started working correctly. 

This post led me to try that: https://stackoverflow.com/questions/2970681/how-do-i-get-python-to-load-net-dlls-referenced-by-mixed-mode-dlls

Obviously this is not a real solution, and I haven't looked into this answer yet: 
> I think I've resolved the problem. Assembly loading doesn't use the path set by SetDllDirectory(), and it looks like Python calls this function. By registering a delegate for the event AppDomain.AssemblyResolve(), I can catch the name of the dll that failed, append it to the directory obtained from GetDllDirectory(), and then manually load the assembly myself.

Also this was not an issue last time I used PythonNET. I used the same version of python, so I'm not sure what's changed since then. My DLL has changed, but it always referenced other DLLs.

It would be nice to find the real solution because copying DLLs to each user's root python directory is not ideal, and I'm sure I'm not the only one encountering this issue.

Thank you

**Comment by Cronan** [comment]
Did you call `clr.AddReference`?

**Comment by joshnyce** [comment]
@Cronan You mean to load the main C# DLL? Yes, of course, or it would not find that at all. This same code worked less than a year ago. I've tried all variations I can find online, so I'm not bothering to post the code, but I'm doing everything the standard way in python, and it works when the dependencies are in the root python directory.

**Comment by filmor** [comment]
It would be interesting to see a Fusion Log of the load attempts: https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer

Could it be that you require an assembly redirect right now?

**Comment by filmor** [comment]
This issue lacks required information, so I'll close it for now. Feel free to reopen if you have more info to share.
