### ISSUE TITLE
Any idea to reimplement DelegateManager without Reflection.emit

### ISSUE THREAD

**Issue by sekkit** [pythonnet/pythonnet#921]
### Environment

-   Pythonnet version: latest
-   Python version: 3.7.4
-   Operating System: Win10 1903

### Details

-   Describe what you were trying to get done.

    Need to compile with AOT compilation.
    System.Reflection.Emit not supported though.

**Comment by filmor** [comment]
If you find a viable alternative, feel free to reopen. I currently don't know of a way to replace this.

**Comment by lostmsu** [comment]
@sekkit why is Reflection.Emit not supported? Which exact platform are you using?

**Comment by sekkit** [comment]
> @sekkit why is Reflection.Emit not supported? Which exact platform are you using?

Unity il2cpp
