### ISSUE TITLE
Is there any way I can get the log in Python method?

### ISSUE THREAD

**Issue by liu7923032** [pythonnet/pythonnet#922]
### Environment

-   Pythonnet version:2.3
-   Python version:3.5
-   Operating System:win10

### Details

-  I use. net to call python's method. Can I get the log in python's method?

**Comment by filmor** [comment]
Hi, this is not a support forum. Please use either the mailing list, gitter or StackOverflow to ask for help that is not related to issues with Python.NET itself.
