### ISSUE TITLE
Python2 deprecated native method import

### ISSUE THREAD

**Issue by zhangyl08** [pythonnet/pythonnet#924]
### Environment

-   Pythonnet version: latest
-   Python version: 3.7.4
-   Operating System: MacOS 10.14.6

### Details 

-   Compiling under xcode for iOS, it throughs PyClass_New reference not found error.
     After diggin' around for a while, there is no PyClass_New definition in Python3 actually.
    Also there are other deprecated python3 APIs need to be nested in #if PYTHON2 condition.

     PyLong_GetMax(not exists)
     PyObject_GC_New(name error, should be _PyObject_GC_New)
    

```
[DllImport(_PythonDll, CallingConvention = CallingConvention.Cdecl)]
 internal static extern IntPtr PyClass_New(IntPtr bases, IntPtr dict, IntPtr name);
```

**Comment by Cronan** [comment]
I agree re: the others, but not PyObject_GC_New.
https://docs.python.org/3.7/c-api/gcsupport.html?highlight=pyobject_gc_new#c.PyObject_GC_New

Would you like to submit a PR?
