### ISSUE TITLE
When using some packages causes a hard crash

### ISSUE THREAD

**Issue by jnkramer3** [pythonnet/pythonnet#93]
I am using Python 3 and just starting to test/develop.
I am getting a hard crash if i use the following code.
This is a simple program which show the problem, but I have seen it in my own code.

```
import clr
from System import Array, Object
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

arr3=Array[Object]([np.float(1),np.long(1)])
list(arr3)  # returns [1.0, 1]

# crash if below is included, no crash if not
# no crash if above code is not included.but below is.

fig = plt.figure()
a=fig.add_subplot(1,2,1)
img = mpimg.imread(r"../Utilities/data/stinkbug.png")
lum_img = img[:,:,0]
imgplot = plt.imshow(lum_img)
a.set_title('Before')
plt.colorbar(ticks=[0.1,0.3,0.5,0.7], orientation ='horizontal')
a=fig.add_subplot(1,2,2)
imgplot = plt.imshow(lum_img)
imgplot.set_clim(0.0,0.7)
a.set_title('After')
plt.colorbar(ticks=[0.1,0.3,0.5,0.7], orientation='horizontal')
plt.show()

print ("Done")
```

I am able to fixed this but adding the following lines to 
moduleobject.cs at line 103.
I'm not sue this is the correct tweek but is seem to work for now.
```
			if (name == String.Empty)
			{
				return null;
			}
```

**Comment by denfromufa** [comment]
can you please fix code snippets in your issue? 
e.g.

https://github.com/pythonnet/pythonnet/blob/develop/src/runtime/moduleobject.cs#L103
```
if (name == String.Empty)
{
    return null;
}
```

**Comment by denfromufa** [comment]
@jnkramer3 I do not get this hard crash with python 2.7 and python 3.4 under 32-bit environments.

Note that I'm using conda packages, except pythonnet:

```
pip install pythonnet --pre
```
