### ISSUE TITLE
Unable to operate Managed Object(type) in Full AOT mode

### ISSUE THREAD

**Issue by zhangyl08** [pythonnet/pythonnet#931]
### Environment

-   Pythonnet version: latest
-   Python version: 3.7.4
-   Operating System: iOS

### Details
python code:
`getattr(unityobject,'attribute')` 

inside gc, there is null gc object.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/19667884/62415515-5cffea00-b65d-11e9-9885-5781479d1fb3.png">

**Comment by filmor** [comment]
This is not nearly enough information on what you are doing, what you are expecting and what you are getting.
