### ISSUE TITLE
TypeError when calling a method with an enum argument

### ISSUE THREAD

**Issue by vladt3** [pythonnet/pythonnet#935]
### Environment

-   Pythonnet version:  2.4.0
-   Python version: 3.6
-   Operating System: Windows10

### Details

-   calling a method that uses C# enum as an argument with the enum fails with TypeError: No method matches given arguments for XXX

The enum comes in Python as an int, and since the method signature is not int, it fails. 

I cannot see how to force the typecast, or whether I could somehow force the method call directly (__overloads__ lists the method, but I can't figure out whether I can call directly).

Searching google did not return anything recent, although some older comments (2017/18 IIRC) indicated there was a fix for this?

**Comment by Cronan** [comment]
This kind of thing should work, I believe ...

```python
from Tests import TestClass, TestEnum
a = TestClass()
a.EnumMethod[TestEnum](TestEnum.FirstValue)
```

**Comment by vladt3** [comment]
Thanks, it does indeed. Maybe there should be some FAQ that would cover things like these?

**Comment by Cronan** [comment]
> Thanks, it does indeed. Maybe there should be some FAQ that would cover things like these?

Thanks, that's a good idea
