### ISSUE TITLE
calling asp.net core 2.2 class library api from python using pythonet gives error as "module not found"

### ISSUE THREAD

**Issue by singh0506** [pythonnet/pythonnet#938]
### Environment

-   Pythonnet version: pythonnet-2.4.0
-   Python version: Python 3.7.4 (86_64)
-   Operating System: windows

### Details

-    I have created asp.net core 2.2 class library in c#, now want to invoke api from python script using pythonnet.
Following command, I have used , but got error.
>>> import clr
>>> clr.AddReference(r"C:\hkysyDemo\dotnetCoreLib\dotnetCoreLib\bin\x64\Debug\netcoreapp2.2\dotnetCoreLib.dll")
<System.Reflection.RuntimeAssembly object at 0x000001911A03C648>
                             ^
>>> from dotnetCoreLib import Class1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ModuleNotFoundError: No module named 'dotnetCoreLib'**

Dll is being loaded successfully, but class not able to be imported due to invalid module.

Whereas, same approach working perfectly for dotnet framework and standard framework.
But only, issues are coming in asp.net core 2.2 or 3.0.

can you please provide any pointer in order to resolve the same.

**Comment by Cronan** [comment]
What does your `dotnetCoreLib` source look like please?

**Comment by singh0506** [comment]
dotnetCoreLib.dll contains only Class1.cs file. And Class1.cs file contains following code:
using System;

namespace dotnetCoreLib
{
    public class Class1
    {
        public int Add(int a, int b)
        {
            return a + b;
        }
    }
}

**Comment by singh0506** [comment]
can anyone provide me input about does pythonnet support asp.net core ?

**Comment by singh0506** [comment]
@Cronan : Have you got chance to review this problem ?

**Comment by Cronan** [comment]
Currently .NET Core support is in the works, there has been more than one attempt to get it into master, none successful yet. When I’m back at my desk (on Tuesday) I’ll point you to a branch or a fork that should do the job for you.

What platform are you looking at, Linux?

**Comment by singh0506** [comment]
@Cronan  thank you for reply, I am looking for windows only, but c# project is in asp.net core.

One more question, is there any other way to call asp.net core dll from python script ?
I tried ctype, and to export the function , used unmanagedExport(1.2.7) nuget package, but this package not supported on asp.net core.

And also, when i opened pythonnet solution, then also found that unmanagedExport package used in pythonnet, which is not compatible with asp.net core.

Thanks again for your reply. Look forward for your reply.

**Comment by rmporsch** [comment]
@Cronan First of all thanks a lot for all your work. I was wondering if there is any update on this issue?

**Comment by milad1372** [comment]
> Currently .NET Core support is in the works, there has been more than one attempt to get it into master, none successful yet. When I’m back at my desk (on Tuesday) I’ll point you to a branch or a fork that should do the job for you. What platform are you looking at, Linux?
> […](#)
> On 23 Aug 2019, at 08:56, singh0506 ***@***.***> wrote: @Cronan : Have you got chance to review this problem ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Thanks for your effort on this. I have the same Issue. Any Update?

**Comment by AnlauTriCloud** [comment]
@Cronan , do you know where I can find the source code for adding .Net Core 2.1 support to Pythonnet? I am working on a IoT project, where I need to integrate from Python to a .Net Core 2.1 application (IoT Edge). Any input is much appreciated.

**Comment by filmor** [comment]
Please read #984, further info will be published there.
