### ISSUE TITLE
Python.Runtime.PythonException: TypeError : unsupported operand type(s) for *: 'Decimal' and 'int'

### ISSUE THREAD

**Issue by szmcdull** [pythonnet/pythonnet#942]
### Environment

-   Pythonnet version: Python.Runtime.NETStandard 3.7.1
-   Python version: 3.7.4
-   Operating System: Windows 10 [Version 10.0.18362.295]

### Details

-   Describe what you were trying to get done.

    parse some system.Decimal number to python and evaluate an expression with these numbers using PyScope.Eval

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```
        decimal Calc(Func<PriceSource, decimal> getter)
        {
            Getter = getter;
            return pyscope.Eval(expression).As<decimal>();
        }
```

-   If there was a crash, please include the traceback here.

```
['  File "<string>", line 1, in <module>\n']   at Python.Runtime.Runtime.CheckExceptionOccurred()
   at Python.Runtime.PyScope.Eval(String code, PyDict locals)
```

**Comment by filmor** [comment]
The example is neither complete nor verifiable, what is `expression` for example? Also what Python.NET version are you using exactly?

This does look like we don't implement `implicit` conversions, which I think is fine as it makes method resolution even more complicated and error-prone than it already is. Use an explicit conversion to `Decimal` instead: `Decimal(5)`.
