### ISSUE TITLE
Enable HiDPI for Windows Forms

### ISSUE THREAD

**Issue by voltagex** [pythonnet/pythonnet#947]
Is it possible to enable high DPI support in Windows Forms running using pythonnet?

```
clr.AddReference("System.Windows.Forms")
from System.Windows.Forms import Form
Form().DeviceDpi
```

returns 96.

Microsoft says for a .NET application running on 4.7+, you need the following in your app.config:

```
<System.Windows.Forms.ApplicationConfigurationSection>
  <add key="DpiAwareness" value="PerMonitorV2" />
</System.Windows.Forms.ApplicationConfigurationSection>
```

It's not clear how to do this for a Form created dynamically via Python code

If I have Windows scaling set at 150%, running a WinForms app with that config set, I get 144 as the output of the DeviceDpi call - i.e. 1.5 * 96.

**Comment by lostmsu** [comment]
@voltagex have you tried this: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846517(v=vs.85)

**Comment by filmor** [comment]
In particular https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846517(v=vs.85)#setting-default-awareness-programmatically tells you how to do it programmatically. `app.config` with Python.NET is always a bit tricky if you are not using it to embed Python into a .NET application as .NET's lookup will check in pretty global places for it and it doesn't seem to be configurable. In any case, this is not an issue that's specific to Python.NET.
