### ISSUE TITLE
About matplotlib can not show image

### ISSUE THREAD

**Issue by lokinfey** [pythonnet/pythonnet#948]
I want to show matplotlib image I use C# like that 

            using (Py.GIL())
            {
                dynamic plt = Py.Import("matplotlib.pyplot");

                dynamic Image =Py.Import("PIL.Image");

                dynamic np = Py.Import("numpy");

                plt.figure(figsize : np.array(new List<float> { 120,160}, dtype: np.int32));

                var img = Image.open("c3po.jpg") ;
                plt.imshow(img) ;

            }

but it can not show anything about that

**Comment by filmor** [comment]
This is not a support forum.
