### ISSUE TITLE
The custom DynamicObject object passed into pythonnet does not work

### ISSUE THREAD

**Issue by wuditnt** [pythonnet/pythonnet#952]
### Environment

-   Pythonnet version: v2.4.1 
-   Python version:  v3.7.3
-   Operating System: win 10
 
### Details
Pythonnet is embedded in C #. I pass in a custom Dynamic Object object through the SetObject function, hoping to make use of the function of dynamic attributes, but this does not work properly in pythonnet, and I find that I can not parse the dynamically defined attributes properly.

Thank you for your help.

**Comment by filmor** [comment]
This is not a support forum. If you need help, head over to StackOverflow, ask gitter or the mailing list. In any case you will have to include your code.
