### ISSUE TITLE
Joining the .NET Foundation

### ISSUE THREAD

**Issue by mjmvisser** [pythonnet/pythonnet#956]
We're getting ready to bring the project into the .NET Foundation, but before we
do we need to do the following:

## Getting into the .NET Foundation
- [x] Make sure the project has a good name that is easy to remember and 
 spell. Check that it doesn't [conflict with another existing project](http://ivantomic.com/projects/ospnc/)
- [x] Make sure the people involved in the project want to join the .NET Foundation
- [ ] Make sure the project has a clear understanding about how it accepts contributions and the process
     it follows when selecting new committers to the project.
- [x] [Register an interest](https://dotnetfoundation.org/get-involved) in joining the .NET Foundation
- [ ] Work with the .NET Foundation to fill out an On-Boarding Questionaire
- [ ] .NET Foundation sends out completed questionaire to .NET Foundation Advisory Council for comments
- [ ] .NET Foundation Executive Director submits new project proposal to the .NET Foundation Board
- [x] Configure a CI build for the project and ensure build status badges are available from the README

## Once accepted into the .NET Foundation
- [ ] Sign the contribution ~~/ assignment~~ agreement
- [ ] Agree a date to move into the .NET Foundation
- [ ] Prepare a guest blog post announcing the move on the .NET Foundation Blog
- [ ] Read the [code of conduct](https://dotnetfoundation.org/code-of-conduct), 
      [link to it in your code](be-nice.md) and 
      understand what to do if you are concerned about any behaviour or have
      concerns reported to you.
- [ ] Tell the world we have joined!
- [ ] Get CLA Automation enabled to ensure contributors can easily sign the 
      [Contribution License Agreement](https://github.com/dotnet/home/blob/master/guidance/net-foundation-contribution-license-agreement.pdf)
- [ ] Send a PR to add the Project into the .NET Foundation 
      [list](https://github.com/dotnet/home/tree/master/projects)
- [ ] Ensure the repo contents are up to date with [.NET Foundation guidance](https://github.com/dotnet/home/blob/master/guidance/repo-guide.md)
- [ ] Review the [README guidance](readme-guide.md) and update if necessary
- [ ] ~~If applicable [update the LICENSE file](copyright.md) to show Copyright has been assigned to the .NET Foundation
      and look to update any file headers.~~
- [ ] ~~If applicable, update any copyright statements in websites owned by the project to reflect 
      assignment to the .NET Foundation~~
- [ ] If applicable, update any websites associated with the project to include
      "Supported by the <a href="https://dotnetfoundation.org">.NET Foundation</a>" or
      similar link back to the .NET Foundation in the footer. If applicable, please
      include image links from [our swag repo](https://github.com/dotnet/swag). (We think a link in the footer using the horizontal logo looks very nice.)
- [ ] [Sign up for Project Leader news](http://eepurl.com/bOCfJP)
- [ ] Configure any resources requested from the .NET Foundation (SSL Certs, Code Signing,
      Secret Management, Build Servers etc)

(Checklist [source](https://github.com/dotnet/foundation/blob/master/guidance/new-projects.md))

Last update from @filmor: 
> I "applied" for having Python.NET in the .NET Foundation but haven't received an answer, yet.

**Comment by filmor** [comment]
Yeah, nothing happened here, I'll try to fill the forms again. Since they require copyright assignment, I'm not so sure anymore whether we should really go through with this.

**Comment by Cronan** [comment]
What's the copyright assignment issue?

**Comment by filmor** [comment]
Well, they require us to hand the copyright over to the .NET Foundation (at least as far as I understood). For a project with a lot of individual contributors like this one it's a lot of work to get everyone's agreement to this.

I filled the forms again now, if I don't hear back from them again I'll try to make more direct contact.

**Comment by Cronan** [comment]
[A good thread](https://github.com/nunit/governance/issues/27) on the steps nunit are going through to join.

It seems there is the option of licensing the foundation, instead of assigning copyright.

**Comment by mjmvisser** [comment]
Yup, here's the link: https://github.com/dotnet/foundation/blob/master/guidance/new-projects.md

> When projects join the foundation, there are two ways that they can come in.
> 
> - **License** - The first is for the maintainers of the project to sign a
   contribution agreement licensing
   the code to the .NET Foundation under the terms of the open source license and
   confirming that they have the rights to do that. This type of agreement is most
   common when projects have had a long history of being open source, with lots of
   contribution from many different individuals and the project community now wish to
   now be supported by the .NET Foundation.
>   
> - **Assignment** - The other is to assign the copyright of the project to the .NET Foundation and
   confirm that they have the rights to do this. This type of agreement is usually
   used when releasing something as open source for the first time or by a project
   that has had a high degree of control over contributions to the existing project 
   in the past.  

We're in the first bucket, same as NUnit.

**Comment by slide** [comment]
FYI, I went through this process with IronPython. If you need any help with anything, I'd be happy to lend my experience.

**Comment by filmor** [comment]
We have joined and are listed, just need to finish the on-boarding activities (adding to our README etc.). That will be done for the coming release.

@slide Thanks, turned out to just need some patience :)
