### ISSUE TITLE
Python.Runtime.PythonException: 'ModuleNotFoundError 

### ISSUE THREAD

**Issue by Tyler871203** [pythonnet/pythonnet#959]
### Environment

-   Pythonnet version:
-   Python version:3.6.8
-   Operating System:Windows

### Details

-  I was trying to use Keras.NET API to run a model through Visual Studio,
but got an Python.Runtime.PythonException: 'ModuleNotFoundError : No module named 'numpy'',
but I have already checked that there is a path called: 'C:\\Users\\ASUS\\source\\repos\\KerasNET\\KerasNET\\bin\\Debug\\netcoreapp2.1'
 in sys.path
and copy a real numpy.py to the path.

how can I solve this?

**Comment by filmor** [comment]
This is a bugtracker and not a support forum. If you are having a problem with Keras.NET, ask in their support channels.
