### ISSUE TITLE
"unresolved import" error

### ISSUE THREAD

**Issue by mtarverdians** [pythonnet/pythonnet#960]
### Environment

-   Pythonnet version: latest
-   Python version:  Python 2.7.15+
-   Operating System: Ubuntu 18.04

I run test projects from pythonnet/src/tests path and get "unresolved import" error  for all modules (for example: unresolved import 'clr' Python(unresolved-import))
pythonnet is installed successfully without any errors why I get this error how can I solve it?

**Comment by filmor** [comment]
This is not a support forum. If `clr` (which is the entry-point of Python.NET) can not be found, then your installation was not successful.
