### ISSUE TITLE
error CS0103: The name 'PythonEngine' does not exist in the current context

### ISSUE THREAD

**Issue by revolutioncse** [pythonnet/pythonnet#966]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.3
-   Operating System: MacOS Mojave

### Details

-   Describe what you were trying to get done.

  Not able to run pythonnet. Gives this error:
error CS0103: The name 'PythonEngine' does not exist in the current context

**Comment by filmor** [comment]
This issue is missing all relevant info and this is not a support forum. If you find a bug or you have a suggestion for change, feel free to open a ticket with details on that. If the installation docs are lacking, describe which you followed and how you tried to verify the installation.
