### ISSUE TITLE
ModuleNotFoundError: No module named 'Microsoft'

### ISSUE THREAD

**Issue by zapcity** [pythonnet/pythonnet#969]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.4
-   Operating System: Windows 10 Pro

### Details

I would like to access a SSAS Cube using python, and am trying to use pythonnet for this. I am having a problem related to loading an assembly. My reduced problematic code is: 
```
import clr
r = clr.AddReference(r"D:\dotnet\Microsoft.AnalysisServices.Tabular.dll")
print("ref:", r)
import Microsoft.AnalysisServices.Tabular as AMO
```

But I get the following error:

```
D:\dotnet>python ssas.py
ref: Microsoft.AnalysisServices.Tabular, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
Traceback (most recent call last):
  File "ssas.py", line 4, in <module>
    import Microsoft.AnalysisServices.Tabular as AMO
ModuleNotFoundError: No module named 'Microsoft'
```

For some reason this works on another pc (pcINT), but not on the pc (pcVM) with the above error. The difference is that pcINT has internet connectivity from where I installed pythonnet via pip. pcVM is on a VMware virtual machine without internet connectivity (due to security reasons) but has access to SSAS. I copied across the C:\Python374\Lib\site-packages folder from pcINT to pcVM. Doing this works for other packages like pandas etc. Other than that the two environments are identical.

Would anyone know what the issue could be? Thanks.

**Comment by zapcity** [comment]
I managed to sort this out. I downloaded 

- x64_15.0.2000.20_SQL_AS_ADOMD.msi 
- x64_15.0.2000.20_SQL_AS_AMO.msi

from https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-data-providers 

I believe the whole issue surrounding this was that the .dll's were not registered.

**Comment by ronakvpanchal** [comment]
how did you find out if the dll's were registered or not? trying to see if im able to check that in my project as well.

**Comment by CrasCris** [comment]
> Can we make it work on ubuntu as well?

Did you find how to run on ubuntu?
