### ISSUE TITLE
Error when import clr on raspbian buster

### ISSUE THREAD

**Issue by LightSaber22** [pythonnet/pythonnet#970]
### Environment

-   Pythonnet version: 2.4.1
-   Python version: 2.7
-   Operating System: Raspbian Buster
-   Mono version : 6.4.0

### Details

-   Can't run _import clr_ after installing pythonnet
```python
    ImportError: /usr/lib/libmonosgen-2.0.so.1: undefined symbol: _ZTIPi'
```

-   I was try to downgrade mono to 5.20 but there is no older version than 6.0 on raspbian buster repo, when i try to use raspbian stretch repo there is no error from import clr but error when i run program

**Comment by filmor** [comment]
Mono >=6 is not supported right now, there seems to be an incompatubility with regard to the linked C++ stdlib, nothing we can do here, I am afraid.
