### ISSUE TITLE
Unable to load DLL 'python35'?

### ISSUE THREAD

**Issue by merc-ury** [pythonnet/pythonnet#973]
### Environment

-   Pythonnet version: 2.3.0-py35-dotnet
-   Python version: 3.7.4 
-   Operating System: Windows

### Details

-   Describe what you were trying to get done.

I am trying to import my Python file within my C# code and I am getting a 
`System.DllNotFoundException: 'Unable to load DLL 'python35': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'`

I am using virtualenv 16.7.4 for this project.

-   What commands did you run to trigger this issue? If you can provide a
I have the code:

```c#
string virtualEnvPath = Environment.CurrentDirectory + @"\env\Scripts";
            string pythonPath = virtualEnvPath + @"\lib;" + virtualEnvPath + @"\lib\site-packages";

            Environment.SetEnvironmentVariable("PATH", virtualEnvPath, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONHOME", virtualEnvPath, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONPATH", pythonPath, EnvironmentVariableTarget.Process);

            PythonEngine.PythonHome = virtualEnvPath;
            PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH", EnvironmentVariableTarget.Process);
            using (Py.GIL())
            {
                dynamic script = Py.Import("test.py");
            }
```
I added Python.Runtime.dll to my References (the x64 bit) and I changed my build to x64 bit as well.  I am going crazy here. Please help! Thanks!

**Comment by merc-ury** [comment]
After look into it more, I believe it's more of an issue with Visual Studio's NuGet packages. Is there not a  NuGet package for Python 3.7? @denfromufa

**Comment by lostmsu** [comment]
@merc-ury, if you want a quick solution and don't care about using stable version of Python.Runtime, try https://www.nuget.org/packages/Python.Runtime.UnofficialNetStandard/

Then just set `Runtime.PythonDLL` to the full path to python37.dll from your virtualenv before everything else.
You might also have to set `Runtime.PythonVersion`.

**Comment by merc-ury** [comment]
@lostmsu 

Hey, that works wonder and I am now able to load in the correct DLL. I have a new problem now but maybe it's more of my virtual environment rather than the NuGet package. Here is my current code:
```c#
string virtualEnvPath = Environment.CurrentDirectory + @"\env\Scripts";
            string pythonPath = Environment.CurrentDirectory + @"env\lib\site-packages;" + Environment.CurrentDirectory + @"env\lib";

            Environment.SetEnvironmentVariable("PATH", virtualEnvPath, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONHOME", virtualEnvPath, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONPATH", pythonPath, EnvironmentVariableTarget.Process);

            PythonEngine.PythonHome = virtualEnvPath;
            PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH", EnvironmentVariableTarget.Process);

            Runtime.PythonVersion = Version.Parse("3.7.4");
            Runtime.PythonDLL = virtualEnvPath + @"\python37.dll";
```
The error now is:
```Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: no module named 'encodings'```

If you can't answer this then it's fine, but do you happen to know if it's a problem within my virtual environment?

**Comment by lostmsu** [comment]
@merc-ury  I had exact same problem with `encodings` in a new conda environment, but in my case setting `PYTHONHOME` environment variable was enough to solve it. I did not do anything else though. E.g. **no** `PYTHONPATH` or `PythonEngine.PythonHome` or `PythonEngine.PythonPath`.

**Comment by merc-ury** [comment]
@lostmsu 

Thank you! Your reply will definitely help someone using a conda environment, but this problem was entirely my fault! I had apparently forgotten a backslash in my variables so it wasn't running correctly. For anyone who is running into errors similar to I am:
```c#
string virtualEnvPath = Environment.CurrentDirectory + @"\venv\Scripts";
            string pythonPath = Environment.CurrentDirectory + @"\venv\lib\site-packages;" + Environment.CurrentDirectory + @"\venv\lib";

            Environment.SetEnvironmentVariable("PATH", virtualEnvPath, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONHOME", virtualEnvPath, EnvironmentVariableTarget.Process);
            Environment.SetEnvironmentVariable("PYTHONPATH", pythonPath, EnvironmentVariableTarget.Process);

            PythonEngine.PythonHome = Environment.GetEnvironmentVariable("PYTHONHOME", EnvironmentVariableTarget.Process);
            PythonEngine.PythonPath = Environment.GetEnvironmentVariable("PYTHONPATH", EnvironmentVariableTarget.Process);

            Runtime.PythonVersion = Version.Parse("3.7.4");
            Runtime.PythonDLL = virtualEnvPath + @"\python37.dll";
```

Thank you @lostmsu for the recommendation on the NuGet package. This works like a charm and I love using it!

**Comment by lostmsu** [comment]
@merc-ury that is why you should use `Path.Combine`. It will also make your code cross-platform.

**Comment by merc-ury** [comment]
@lostmsu 

I'll keep in mind for ```Path.Combine``` ! Thanks!

**Comment by SUYOG-KOTKAR** [comment]
@lostmsu 
1) Downloaded nuget package from below site,  https://www.nuget.org/packages/Python.Runtime.UnofficialNetStandard/

2) Extracted downloaded package and used Python.Runtime.dll (extracted from downloaded package) as a reference in visual studio project.

3) Then tool throws below error:
The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
To resolve this issue, i have added reference in csproject. (<Reference Include="netStandard" />)

4) Now, tool is throwing below error (System.TypeInitializationException).
![image](https://user-images.githubusercontent.com/14229451/83835786-8edf4400-a6a6-11ea-8604-b82a9773e5ad.png)

Please help me to resolve this issue.

**Comment by lostmsu** [comment]
@SUYOG-KOTKAR 

1. You need to add the details for your `TypeInitializationException` like message and stack trace, otherwise it is hard to understand what's going on. But I suspect you need to set `PythonDLL` property to the full path to your `python35.dll`
2. Normally, you should not need to reference netStandard. If your app is targeting .NET Framework 4.X, you should have used `Python.Runtime.dll` from `net40` instead of the `netstandard2.0` one.

Are you trying to use this in Unity or something? Why can't you reference the NuGet package normally?

**Comment by SUYOG-KOTKAR** [comment]
Hello @lostmsu ,

Actually my problem is different.
I want a Python.Runtime.dll which will not dependent on any specific python version.

ex. If python 3.0 installed in system, then same Python.Runtime dll should work for python 3.0. 
If python 3.5 installed in system, then same Python.Runtime dll should work for python 3.5.  
If python 3.7 installed in system, then same Python.Runtime dll should work for python 3.7. 

Whatever the python version installed in system, same python runtime dll should work for that version.

Is it possible ? 
If yes, then how?
Please help me.

**Comment by filmor** [comment]
This is not possible right now, there is coding involved with making it happen.

1. There is no way right now to decide at runtime, which `python*.dll` to load (there are prototypes in a few branches, but nothing final)
2. The code currently uses compile-time constants to decide which interop mappings to use

**Comment by lostmsu** [comment]
@SUYOG-KOTKAR , WhichPython NuGet package should allow you to enumerate installed Python environments. Then you can set `Runtime.PythonDLL` to one of them.

**Comment by codingwithashu** [comment]
Getting Error
"Could not load python37.dll"
I saved my python files in my application root folder, I checked with the default as well not work 
![Screenshot 2022-08-21 202126](https://user-images.githubusercontent.com/111554315/185796987-a4e4d783-3183-442a-9839-8b40327a63ca.png)
Please help
