### ISSUE TITLE
Finding out compatible version of Mono and pythonnet in Mac OS

### ISSUE THREAD

**Issue by BalaArs** [pythonnet/pythonnet#978]
Hi Folks,
I am trying to call .Net dll in Python in Mac OS Mojave (10.14.6).
Can someone share the versions of mono, python and pythonnet which works well in Mac ?
I have been trying different versions of mono, python and pythonnet, but all efforts ends up in error while installing pythonnet
Thanks.

### Environment

-   Pythonnet version: 
-   Python version:
-   Operating System: Mac OS Mojave (10.14.6)

### Details

-   Describe what you were trying to get done.

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by filmor** [comment]
This is far too broad. Python.NET should work fine with Mono < 6 and Python < 3.8.
