### ISSUE TITLE
UnicodeDecode error during import of modules

### ISSUE THREAD

**Issue by LucaBoss74** [pythonnet/pythonnet#979]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.5
-   Operating System: Windows 10

### Details

-   When trying to import an opaque DLL (I have sources, but I prefer to not compile on my system because is related to a project not maintained by me), i experience this error:

`
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 12: unexpected end of data

The above exception was the direct cause of the following exception:

SystemError: <class 'UnicodeDecodeError'> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method mro of CLR Metatype object at 0x09ABF208> returned a result with an error set
`

It seems related to encoding in function names, but I inspected the DLL (both source code and with ILSpy) and I don't find anything strange.

**Comment by filmor** [comment]
What is the stacktrace? e0 is à in latin1, is this a French library?

**Comment by LucaBoss74** [comment]
It's an italian DLL,

The stack trace seems not to belong to python; the application crashes and I can see lines like this:

First:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 12: unexpected end of data

Then a series of:

System Error:  <built-in method mro of CLR Metatype object at 0x...... > returned a result with an error set

and finally:

System Error: PyEval_EvalFrameEx returned an error with an error set

I've inspected library source code and it contains some string constants with letters "à", "è" and ""é"

**Comment by filmor** [comment]
Can you please share a bit more code? How exactly are you loading the DLL from Python? What is the smallest example that shows this issue?

Does the fix from this PR https://github.com/pythonnet/pythonnet/pull/824 help?

**Comment by LucaBoss74** [comment]
> Can you please share a bit more code? How exactly are you loading the DLL from Python? What is the smallest example that shows this issue?
> 

Hi,
I cannot share DLL name since they are covered by an NDA with the software house which built them, but essentially the code that raises the error is this:

# *-* encoding: utf-8
import clr, sys, os
from datetime import datetime

clr.AddReference('System')
clr.AddReference('CustomLibrary')

from CustomLibrary import BadClass

this triggers the error. I've just renamed library and class names.

> Does the fix from this PR #824 help?

Is there a windows binary whl ready to download or should I compile pythonnet ? I haven't got the whole sdk installed on the machine.

**Comment by filmor** [comment]
You can download a wheel here: https://ci.appveyor.com/project/pythonnet/pythonnet/builds/28411343/job/45f8e3jfv0uha5ij/artifacts

**Comment by LucaBoss74** [comment]
Sorry, I forgot to say I need the 32 bit version

Il 28/10/19 09:10, Benedikt Reinartz ha scritto:

**Comment by filmor** [comment]
https://ci.appveyor.com/project/pythonnet/pythonnet/builds/28411343/job/3yj6duedjoftpoqw/artifacts

There you go, two clicks away ;)

**Comment by LucaBoss74** [comment]
I'm sorry, but it doesn't solve the problem...

The error still the same

Il 28/10/19 15:02, Benedikt Reinartz ha scritto:

**Comment by vbsoftpl** [comment]
I have a similar issue with dll that contains Polish letter.

Stacktrace is:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 9: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\soneta_test3.py", line 23, in <module>
    login = database.Login(False, 'user_name', 'user_pass')
SystemError: <bound method 'Login'> returned a result with an error set

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import clr
clr.AddReference('Soneta.Business')
from Soneta.Business.App import BusApplication
database = BusApplication.Instance['database_name']

login = database.Login(False, 'user_name', 'user_password')
```

This issue not happened when use python 2.7

**Comment by filmor** [comment]
Well, `0xb3` *is* an invalid start byte, so your coding comment there is simply wrong...

**Comment by vbsoftpl** [comment]
So i change file encoding and comment encoding to # -*- coding: iso-8859-2 -*- and have the same issue:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 9: invalid start byte

That mean that I need to change encoding somewhere else?

**Comment by realgpasternak** [comment]
I have the same issue with `0xc5`, using QuantityTypes.dll from https://www.nuget.org/packages/QuantityTypes/ (version 4.0.0)

repro code:

```python
import clr
clr.AddReference("QuantityTypes")
from QuantityTypes import Length
print(Length().Millimetre)
```

However, if I run 
```python
import clr
clr.AddReference("QuantityTypes")
from QuantityTypes import Length
try:
    print(Length().Millimetre)
except:
    pass
print(Length().Millimetre)
```
this works.

**Comment by filmor** [comment]
Interesting, `0xc5` is `Å` which is used for Ångström, `1e-10 m`. I'll try to reproduce this. Thanks for providing an open source example :)

**Comment by filmor** [comment]
This is fixed on master.
