### ISSUE TITLE
Instances of Python class with Embedded PythonNet? (Question)

### ISSUE THREAD

**Issue by trippyeast** [pythonnet/pythonnet#989]
### Environment

-   Pythonnet version: 2.4.1
-   Python version: 3.7
-   Operating System: Windows 10 x64

### Details

I'm trying to create and instance of a Python class in .NET to serve as a wrapper for attributes and functions I want to call from the .NET side, as well as a framework for users to write python scripts within. I'm having some trouble correctly referencing the instance of this class in .NET.

Here is my Python class:
![image](https://user-images.githubusercontent.com/10554371/69171155-6bb5c400-0ac9-11ea-9b83-624761761baf.png)

And here is the .NET code that creates an instance of this class
![image](https://user-images.githubusercontent.com/10554371/69171328-b59eaa00-0ac9-11ea-8f8e-a50cf06f2c43.png)

The object is created, and I can set attributes or call "testFunction". See here where I'm confirming that "datafile" is being set.
![image](https://user-images.githubusercontent.com/10554371/69171504-17f7aa80-0aca-11ea-8d01-f2c5a50f629b.png)

But when I call "getCSV", I get this error:
![image](https://user-images.githubusercontent.com/10554371/69171753-876d9a00-0aca-11ea-8f27-e0c602983869.png)

"datafile" attribute is still set as "filepath", which is the initialization value. It looks like a new class instance is created somewhere when I call this function, or I'm losing scope of the original object, but I can't figure out where the problem is.

Any help would be greatly appreciated. Thanks!

**Comment by filmor** [comment]
`Scope.Set` will not resolve "object paths" like this. Try something like this:

```csharp
Scope.Set("path", formatPath);
Scope.Exec("EnterpriseObject.datafile = path")
```

What you did there was essentially creating a variable called `"EnterpriseObject.datafile"`.

**Comment by trippyeast** [comment]
I see, that makes sense. Thank you very much for the quick response!
