### ISSUE TITLE
The calling thread must be STA

### ISSUE THREAD

**Issue by jz499** [pythonnet/pythonnet#990]
### Environment

-   Pythonnet version: 2.4
-   Python version: 3.6.5
-   Operating System: Windows 10

### Details
Hi Everyone;
I'm trying to run a basic wpf application from within Python using VS code. When the script executes I get the error listed at the bottom of this page. Has anyone seen this error before?

My Code:
-----------
import clr
clr.AddReference("PresentationFramework")
clr.AddReference("PresentationCore")

from System.Windows import (Application, SizeToContent, Thickness, Window)
from System.Windows.Controls import (Button, Label, StackPanel)
from System.Windows.Media.Effects import DropShadowBitmapEffect

window = Window()
window.Title = 'Welcome'
window.SizeToContent = SizeToContent.Height
window.Width = 450

stack = StackPanel()
stack.Margin = Thickness(15)
window.Content = stack

button = Button()
button.Content = 'Button1'
button.FontSize = 24
button.BitmapEffect = DropShadowBitmapEffect()

def onClick(sender, event):
   message = Label()
   message.FontSize = 36
   message.Content = 'Welcome'
   stack.Children.Add(message)

button.Click += onClick
stack.Children.Add(button)

app = Application()
app.Run(window)
-------------------------------------------------------------------------------------------------------

Error Output:
--------------
File "c:/Users/WIN-VMMV970AOGL/pyfolder/test.py", line 10, in <module>
    window = Window()
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at System.Windows.Window..ctor()

**Comment by lostmsu** [comment]
What you need is a [single apartment thread](https://docs.microsoft.com/en-us/windows/win32/com/single-threaded-apartments) for COM.

You can do it either by manually call https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex or start a separate thread using .NET: https://stackoverflow.com/questions/11681666/starting-an-stathread-in-c-sharp

**Comment by jz499** [comment]
thanks you, I was able to create an apartment thread and the code runs with no errors, but It doesn't display any controls. Any idea on why this happening? Here's the revised code.

class myclass:
    def app_thread():
        pass
        stream = StreamReader("HelloWorld.xaml")
        window = XamlReader.Load(stream.BaseStream)
        Application().Run(window)

    thread = Thread(ThreadStart(app_thread))
    thread.SetApartmentState(ApartmentState.STA)
    thread.Start
    thread.Join

**Comment by lostmsu** [comment]
@jz499 I got more questions in email, but I don't see them in this thread. Have you been able to solve get it working? Should we close the topic?

**Comment by jz499** [comment]
Hi @lostmsu , I got it partially working. I created an apartment thread in Python, the code executes with no errors, but it does not display the window or controls. Here's the threading I added to the above code.

     thread = Thread(ThreadStart(window)
    thread.SetApartmentState(ApartmentState.STA)
    thread.Start
    thread.Join

**Comment by lostmsu** [comment]
@jz499 I think that happens, because Python can only execute 1 thread at time. E.g. while main Python interpreter is busy in `thread.Join()`, the `thread` is unable to run any of your Python code in `window`. 

Probably you need to call `BeginAllowThreads` somehow.

**Comment by jz499** [comment]
Hi @lostmsu, 
Thanks, adding an apartment thread did resolve my problem. To make my code work I simply used a Xaml file rather than defining each control directly in python code.

 stream = StreamReader("my_app.xaml")
 window = XamlReader.Load(stream.BaseStream)
 Application().Run(window)
