### ISSUE TITLE
Why configure LF in .editorconfig file even though every file has CRLF?

### ISSUE THREAD

**Issue by SnGmng** [pythonnet/pythonnet#998]
Every `.cs` file in this repo has `CRLF` line endings, but `LF` line endings are configured in the .editorconfig file. Because of this, my code editor automatically puts `LF` line endings in `.cs` files and i have to change it manually to `CRLF` every time.
https://github.com/pythonnet/pythonnet/blob/34d8d350fbbc0c2086c405733c7de2947c557784/.editorconfig#L9

**Comment by filmor** [comment]
Check your git autocrlf settings. All files have Unix line endings.
